import * as Linking from "expo-linking";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useAuth } from "../../context/AuthContext";

type PlanId="free"|"creator"|"pro"|"business";
type BillingStatus={plan:PlanId;planName:string;status:string;customerConfigured:boolean;subscriptionConfigured:boolean;cancelAtPeriodEnd?:boolean;currentPeriodEnd?:string};
type Plan={id:PlanId;name:string;monthlyCents:number;features:string[]};
const accents:Record<PlanId,string>={free:"#14b8a6",creator:"#2563eb",pro:"#9333ea",business:"#f59e0b"};
async function responseError(response:Response){try{const body=await response.json();return body?.error?.message??"Request failed"}catch{return "Request failed"}}
export default function BillingManager(){
 const auth=useAuth();const [plans,setPlans]=useState<Plan[]>([]);const [status,setStatus]=useState<BillingStatus|null>(null);const [busy,setBusy]=useState<PlanId|"portal"|"refresh"|null>(null);const [error,setError]=useState("");
 const load=useCallback(async()=>{setBusy("refresh");setError("");try{const [plansResponse,statusResponse]=await Promise.all([auth.authorizedFetch("/api/v1/billing/plans"),auth.authorizedFetch("/api/v1/billing/status")]);if(!plansResponse.ok)throw new Error(await responseError(plansResponse));if(!statusResponse.ok)throw new Error(await responseError(statusResponse));const planBody=await plansResponse.json();const statusBody=await statusResponse.json();setPlans(planBody.items??[]);setStatus(statusBody)}catch(e){setError(e instanceof Error?e.message:"Unable to load billing")}finally{setBusy(null)}},[auth]);
 useEffect(()=>{queueMicrotask(()=>{void load()})},[load]);
 const checkout=async(plan:PlanId)=>{setBusy(plan);setError("");try{const origin=typeof window!=="undefined"?window.location.origin:"https://yaposan.com";const response=await auth.authorizedFetch("/api/v1/billing/checkout",{method:"POST",body:JSON.stringify({plan,quantity:1,successUrl:`${origin}/account?billing=success`,cancelUrl:`${origin}/account?billing=canceled`})});if(!response.ok)throw new Error(await responseError(response));const body=await response.json();if(!body.url)throw new Error("Stripe Checkout URL was not returned");await Linking.openURL(body.url)}catch(e){const message=e instanceof Error?e.message:"Unable to open checkout";setError(message);Alert.alert("Checkout unavailable",message)}finally{setBusy(null)}};
 const portal=async()=>{setBusy("portal");setError("");try{const origin=typeof window!=="undefined"?window.location.origin:"https://yaposan.com";const response=await auth.authorizedFetch("/api/v1/billing/portal",{method:"POST",body:JSON.stringify({returnUrl:`${origin}/account`})});if(!response.ok)throw new Error(await responseError(response));const body=await response.json();if(!body.url)throw new Error("Billing portal URL was not returned");await Linking.openURL(body.url)}catch(e){const message=e instanceof Error?e.message:"Unable to open billing portal";setError(message);Alert.alert("Billing unavailable",message)}finally{setBusy(null)}};
 if(busy==="refresh"&&!status)return <View style={s.card}><ActivityIndicator/><Text style={s.muted}>Loading secure billing…</Text></View>;
 return <View style={{gap:14}}><View style={s.card}><View style={s.row}><View><Text style={s.title}>Current subscription</Text><Text style={s.muted}>{status?.planName??"Free"} • {status?.status??"active"}</Text>{status?.cancelAtPeriodEnd?<Text style={s.warning}>Cancellation is scheduled for the end of the billing period.</Text>:null}</View><Pressable onPress={()=>void load()}><Text style={s.link}>Refresh</Text></Pressable></View>{status?.plan!=="free"?<Pressable style={s.portal} onPress={()=>void portal()} disabled={busy!==null}>{busy==="portal"?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Manage payment, invoices, or cancellation</Text>}</Pressable>:<Text style={s.note}>Choose a paid plan below. Stripe securely collects payment details; Yaposan does not store card numbers.</Text>}{error?<Text style={s.error}>{error}</Text>:null}</View><View style={s.grid}>{plans.map(plan=><View key={plan.id} style={[s.plan,{borderColor:accents[plan.id]}]}><Text style={[s.planName,{color:accents[plan.id]}]}>{plan.name}</Text><Text style={s.price}>{plan.monthlyCents===0?"$0":`$${(plan.monthlyCents/100).toFixed(2)}/month`}</Text><View style={{gap:6,flex:1}}>{plan.features.slice(0,6).map(feature=><Text key={feature} style={s.feature}>✓ {feature.replaceAll("-"," ")}</Text>)}</View><Pressable disabled={status?.plan===plan.id||plan.id==="free"||busy!==null} onPress={()=>void checkout(plan.id)} style={[s.select,{backgroundColor:accents[plan.id]},(status?.plan===plan.id||plan.id==="free")&&s.disabled]}>{busy===plan.id?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>{status?.plan===plan.id?"Current plan":plan.id==="free"?"Included":"Select plan"}</Text>}</Pressable></View>)}</View><Text style={s.footer}>Plan access changes after Stripe confirms the subscription through the signed webhook. Usage limits refresh automatically.</Text></View>
}
const s=StyleSheet.create({card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dbe4ee",borderRadius:16,padding:18,gap:12},row:{flexDirection:"row",justifyContent:"space-between",gap:12},title:{fontSize:20,fontWeight:"900",color:"#172033"},muted:{color:"#64748b",fontSize:12,marginTop:3},warning:{color:"#b45309",fontWeight:"800",fontSize:12,marginTop:7},link:{color:"#7c3aed",fontWeight:"900"},portal:{backgroundColor:"#334155",padding:12,borderRadius:10,alignItems:"center"},note:{color:"#475569",fontSize:12,lineHeight:18},error:{color:"#b91c1c",fontWeight:"800"},grid:{flexDirection:"row",flexWrap:"wrap",gap:12},plan:{backgroundColor:"#fff",borderWidth:2,borderRadius:16,padding:16,width:"23%",minWidth:205,minHeight:285,gap:10},planName:{fontWeight:"900",fontSize:18},price:{fontSize:20,fontWeight:"900",color:"#172033"},feature:{color:"#475569",fontWeight:"700",fontSize:12,textTransform:"capitalize"},select:{padding:11,borderRadius:10,alignItems:"center"},buttonText:{color:"#fff",fontWeight:"900"},disabled:{opacity:.55},footer:{color:"#64748b",fontSize:11,lineHeight:17}});
