import type { PublisherElement, PublisherPage, PublisherProject } from "../types/publisher";

export type AiDocumentType = "Flyer"|"Poster"|"Brochure"|"Newsletter"|"Resume"|"Cover Letter"|"Business Card"|"Certificate"|"Church Bulletin"|"Church Program"|"Event Program"|"Restaurant Menu"|"Product Catalog"|"Company Profile"|"Book Cover"|"Magazine Cover"|"Invitation"|"Price List";
export type AiProviderId = "local"|"openai"|"azure"|"anthropic"|"gemini"|"ollama"|"lmstudio"|"custom";
export type AiProviderConfig = { id:AiProviderId; label:string; model:string; endpoint?:string; enabled:boolean; local:boolean; estimatedInputCostPerMillion:number; estimatedOutputCostPerMillion:number };
export type AdvancedDocumentMetrics = { words:number; sentences:number; paragraphs:number; readability:number; gradeLevel:number; passiveSentences:number; repeatedWords:string[]; longParagraphs:number; headings:number; style:string; summary:string };
export type LayoutSuggestion = { id:string; title:string; detail:string; kind:"spacing"|"alignment"|"margin"|"hierarchy"|"color"|"whitespace"; pageId:string; elementId?:string };
export type ImagePromptPlatform = "DALL-E"|"Midjourney"|"Stable Diffusion"|"Adobe Firefly"|"Flux";

export const AI_PROVIDERS:AiProviderConfig[]=[
 {id:"local",label:"Yaposan Local",model:"Local Writing Engine",enabled:true,local:true,estimatedInputCostPerMillion:0,estimatedOutputCostPerMillion:0},
 {id:"openai",label:"OpenAI",model:"gpt-4.1-mini",enabled:false,local:false,estimatedInputCostPerMillion:.4,estimatedOutputCostPerMillion:1.6},
 {id:"azure",label:"Azure OpenAI",model:"Configured deployment",enabled:false,local:false,estimatedInputCostPerMillion:0,estimatedOutputCostPerMillion:0},
 {id:"anthropic",label:"Anthropic Claude",model:"claude-sonnet",enabled:false,local:false,estimatedInputCostPerMillion:3,estimatedOutputCostPerMillion:15},
 {id:"gemini",label:"Google Gemini",model:"gemini-flash",enabled:false,local:false,estimatedInputCostPerMillion:.35,estimatedOutputCostPerMillion:1.05},
 {id:"ollama",label:"Ollama",model:"llama3.2",endpoint:"http://localhost:11434",enabled:false,local:true,estimatedInputCostPerMillion:0,estimatedOutputCostPerMillion:0},
 {id:"lmstudio",label:"LM Studio",model:"local-model",endpoint:"http://localhost:1234/v1",enabled:false,local:true,estimatedInputCostPerMillion:0,estimatedOutputCostPerMillion:0},
 {id:"custom",label:"Custom endpoint",model:"custom-model",enabled:false,local:false,estimatedInputCostPerMillion:0,estimatedOutputCostPerMillion:0},
];

const stop=new Set("the a an and or but for to of in on at by with from is are was were be been being this that these those it its your you our we they their as into about can will would should could".split(" "));
function textOf(project:PublisherProject){return project.pages.flatMap(p=>p.elements.filter(e=>e.type==="text").map(e=>e.text??"")).join("\n").trim();}
function syllables(word:string){const w=word.toLowerCase().replace(/[^a-z]/g,"");if(!w)return 0;const m=w.replace(/(?:[^laeiouy]es|ed|[^laeiouy]e)$/,"" ).match(/[aeiouy]{1,2}/g);return Math.max(1,m?.length??1);}
export function analyzeAdvancedDocument(project:PublisherProject):AdvancedDocumentMetrics{
 const text=textOf(project);const words:string[]=text.match(/[\p{L}\p{N}'-]+/gu)??[];const sentences=text.split(/[.!?]+/).map(x=>x.trim()).filter(Boolean);const paragraphs=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);
 const syl=words.reduce((n,w)=>n+syllables(w),0);const wc=Math.max(1,words.length),sc=Math.max(1,sentences.length);const readability=Math.max(0,Math.min(100,206.835-1.015*(wc/sc)-84.6*(syl/wc)));const grade=Math.max(0,.39*(wc/sc)+11.8*(syl/wc)-15.59);
 const passive=sentences.filter(s=>/\b(am|is|are|was|were|be|been|being)\b\s+\w+(ed|en)\b/i.test(s)).length;const counts=new Map<string,number>();for(const w of words.map(w=>w.toLowerCase()))if(w.length>4&&!stop.has(w))counts.set(w,(counts.get(w)??0)+1);const repeated=[...counts].filter(([,n])=>n>=3).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([w])=>w);
 const headings=project.pages.flatMap(p=>p.elements).filter(e=>e.type==="text"&&(e.fontSize??0)>=28).length;const style=words.length<80?"Concise":sentences.length&&wc/sc>22?"Dense":"Balanced";
 return{words:words.length,sentences:sentences.length,paragraphs:paragraphs.length,readability:Math.round(readability),gradeLevel:Math.round(grade*10)/10,passiveSentences:passive,repeatedWords:repeated,longParagraphs:paragraphs.filter(p=>(p.match(/\S+/g)??[]).length>100).length,headings,style,summary:`${style} document with ${words.length} words, readability ${Math.round(readability)}/100, and grade level ${Math.round(grade*10)/10}.`};
}
export function suggestLayouts(project:PublisherProject):LayoutSuggestion[]{const out:LayoutSuggestion[]=[];for(const p of project.pages){const visible=p.elements.filter(e=>!e.hidden);if(visible.length>8)out.push({id:`space-${p.id}`,title:"Increase whitespace",detail:"This page is visually dense. Group related objects and increase space between sections.",kind:"whitespace",pageId:p.id});const texts=visible.filter(e=>e.type==="text");if(texts.length&&!texts.some(e=>(e.fontSize??0)>=28))out.push({id:`head-${p.id}`,title:"Strengthen hierarchy",detail:"Add or enlarge a primary heading so readers can scan the page quickly.",kind:"hierarchy",pageId:p.id});for(const e of visible){if(e.x<p.margin||e.y<p.margin)out.push({id:`margin-${e.id}`,title:"Respect page margins",detail:`${e.name||"Object"} is close to the trim edge. Move it inside the safe margin.`,kind:"margin",pageId:p.id,elementId:e.id});}const lefts=visible.map(e=>Math.round(e.x)).filter((v,i,a)=>a.indexOf(v)===i);if(lefts.length>5)out.push({id:`align-${p.id}`,title:"Simplify alignment",detail:"Use fewer left edges to create a stronger visual grid.",kind:"alignment",pageId:p.id});}return out.slice(0,20);}
function el(id:string,name:string,type:PublisherElement["type"],x:number,y:number,width:number,height:number,zIndex:number,extra:Partial<PublisherElement>={}):PublisherElement{return{id,name,type,x,y,width,height,rotation:0,zIndex,opacity:1,...extra};}
export function generatePublication(project:PublisherProject,type:AiDocumentType,topic:string):PublisherProject{
 const source=project.pages[0];const width=source?.width??816,height=source?.height??1056;const pageId=`ai-page-${Date.now()}`;const title=(topic.trim()||`New ${type}`).replace(/\.$/,"");const accent="#0F766E",dark="#17212B",light="#ECFDF5";
 const elements:PublisherElement[]=[el(`${pageId}-bg`,`${type} Background`,"rectangle",0,0,width,height,0,{fillColor:"#FFFFFF",borderWidth:0}),el(`${pageId}-band`,`Accent Band`,"rectangle",0,0,width,Math.round(height*.18),1,{fillColor:accent,borderWidth:0}),el(`${pageId}-title`,`Main Title`,"text",48,42,width-96,100,2,{text:title,fontFamily:"Georgia",fontSize:44,fontWeight:"800",textColor:"#FFFFFF",textAlign:"left",lineHeight:50}),el(`${pageId}-subtitle`,`Subtitle`,"text",50,Math.round(height*.22),width-100,70,3,{text:`A professionally generated ${type.toLowerCase()} created in Yaposan Publisher.`,fontFamily:"Arial",fontSize:22,fontWeight:"600",textColor:dark,lineHeight:28}),el(`${pageId}-body`,`Main Content`,"text",50,Math.round(height*.34),width-100,Math.round(height*.34),4,{text:`${title}\n\nUse this editable publication to communicate the purpose, key details, benefits, schedule, and next steps. Replace this copy with your final information, then refine the typography, images, and brand colors.`,fontFamily:"Arial",fontSize:18,fontWeight:"400",textColor:dark,lineHeight:27}),el(`${pageId}-callout`,`Callout`,"rectangle",50,Math.round(height*.72),width-100,120,5,{fillColor:light,borderColor:accent,borderWidth:2,borderRadius:12}),el(`${pageId}-cta`,`Call to Action`,"text",75,Math.round(height*.755),width-150,50,6,{text:"Take the next step today",fontFamily:"Arial",fontSize:25,fontWeight:"800",textColor:accent,textAlign:"center",lineHeight:31}),el(`${pageId}-footer`,`Footer`,"text",50,height-70,width-100,30,7,{text:`${type} • Generated with Yaposan AI`,fontFamily:"Arial",fontSize:12,fontWeight:"600",textColor:"#64748B",textAlign:"center"})];
 const page:PublisherPage={id:pageId,name:`AI ${type}`,width,height,orientation:source?.orientation??"portrait",sizeKey:source?.sizeKey??"letter",backgroundColor:"#FFFFFF",margin:source?.margin??36,bleed:source?.bleed??0,elements};return{...project,pages:[...project.pages,page],activePageId:page.id,updatedAt:Date.now()};
}
export function contentLibrary(kind:string,topic:string){const t=topic.trim()||"your topic";const map:Record<string,string>={Quotes:`“Progress begins when purpose becomes action.” — Yaposan`,"Bible verses":`“Let all that you do be done in love.” — 1 Corinthians 16:14`,Testimonials:`“${t} made the process clear, professional, and easy from start to finish.”`,FAQs:`Q: What should people know about ${t}?\nA: It is designed to provide clear value, practical benefits, and an easy next step.`,"Product features":`• Reliable quality\n• Easy to use\n• Designed for real needs\n• Supported by a clear process`,Timelines:`1. Plan\n2. Prepare\n3. Launch\n4. Review\n5. Improve`,Agendas:`Welcome\nKey updates\nDiscussion\nDecisions\nNext steps`,Announcements:`Important announcement: ${t}. Please review the details and take the requested action.`,"Event schedules":`9:00 AM — Welcome\n9:30 AM — Main session\n11:00 AM — Break\n11:15 AM — Discussion\n12:00 PM — Closing`,Hashtags:`#${t.replace(/\W+/g,"")} #Yaposan #Community #Update`,Slogans:`${t}: designed to make every message matter.`};return map[kind]??`${kind}: ${t}`;}
export function buildImagePrompt(platform:ImagePromptPlatform,subject:string,style:string){const s=subject.trim()||"a professional publication hero image";const st=style.trim()||"clean editorial photography";const suffix:Record<ImagePromptPlatform,string>={"DALL-E":"clear composition, accurate text-free imagery, high detail","Midjourney":"--ar 4:3 --stylize 250 --quality 1","Stable Diffusion":"masterpiece, detailed, balanced lighting, negative prompt: text, watermark, distortion","Adobe Firefly":"commercial-safe editorial composition, clean background, print-ready","Flux":"photorealistic detail, natural lighting, precise composition"};return `${s}, ${st}, strong focal point, balanced negative space for publication text, ${suffix[platform]}`;}
