import { DEFAULT_BLEED } from "../constants/publisher";
import type { PublisherElement, PublisherPage } from "../types/publisher";
import type { ProfessionalTemplate, ProfessionalTemplateCategory, TemplateOrientation } from "./types";

const NOW = "2026-07-30T00:00:00.000Z";
const photo = {
  office: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=90",
  technology: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=90",
  city: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1600&q=90",
  shop: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=90",
  fashion: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1600&q=90",
  market: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1600&q=90",
  coffee: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=90",
  food: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1600&q=90",
  pizza: "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1600&q=90",
  clinic: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1600&q=90",
  wellness: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1600&q=90",
  school: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1600&q=90",
  kids: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1600&q=90",
  laptop: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1600&q=90",
  graduation: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1600&q=90",
  cyber: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1600&q=90",
  code: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1600&q=90",
  house: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=90",
  apartment: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=90",
  building: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=90",
  sports: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1600&q=90",
  fitness: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1600&q=90",
  soccer: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1600&q=90",
  running: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1600&q=90",
  church: "https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&w=1600&q=90",
  concert: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1600&q=90",
  community: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1600&q=90",
  podcast: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1600&q=90",
  microphone: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=1600&q=90",
  gaming: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=90",
  streaming: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1600&q=90",
  documentary: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1600&q=90",
  gadget: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1600&q=90",
  baby: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1600&q=90",
  celebration: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1600&q=90",
  holiday: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=1600&q=90",
  gala: "https://images.unsplash.com/photo-1507501336603-6e31db2be093?auto=format&fit=crop&w=1600&q=90",
  art: "https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1600&q=90",
  travel: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=90",
  mountain: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=90",
} as const;

const el=(id:string,name:string,type:PublisherElement["type"],x:number,y:number,width:number,height:number,zIndex:number,extra:Partial<PublisherElement>={}):PublisherElement=>({id,name,type,x,y,width,height,rotation:0,zIndex,opacity:1,locked:false,hidden:false,...extra});
const text=(id:string,value:string,x:number,y:number,width:number,height:number,size:number,color:string,weight:PublisherElement["fontWeight"]="700",extra:Partial<PublisherElement>={})=>el(id,value.slice(0,24),"text",x,y,width,height,30,{text:value,fontSize:size,textColor:color,fontWeight:weight,lineHeight:size*1.12,fontFamily:"Inter",...extra});
const rect=(id:string,x:number,y:number,width:number,height:number,fillColor:string,extra:Partial<PublisherElement>={})=>el(id,id,"rectangle",x,y,width,height,10,{fillColor,borderWidth:0,...extra});
const circle=(id:string,x:number,y:number,width:number,height:number,fillColor:string,extra:Partial<PublisherElement>={})=>el(id,id,"ellipse",x,y,width,height,12,{fillColor,borderWidth:0,...extra});
const image=(id:string,uri:string,x:number,y:number,width:number,height:number,extra:Partial<PublisherElement>={})=>el(id,id,"image",x,y,width,height,8,{imageUri:uri,imageFit:"cover",...extra});
const page=(id:string,name:string,width:number,height:number,orientation:"portrait"|"landscape",backgroundColor:string,elements:PublisherElement[]):PublisherPage=>({id,name,width,height,orientation,sizeKey:"custom",backgroundColor,margin:32,bleed:DEFAULT_BLEED,elements});

function compose(prefix:string,title:string,subtitle:string,dark:string,accent:string,uri:string,variant:number):PublisherPage {
 const W=1080,H=1350;
 const common=[image(`${prefix}-photo`,uri,0,0,W,H),rect(`${prefix}-shade`,0,0,W,H,"rgba(5,10,20,0.38)"),text(`${prefix}-brand`,"YAPOSAN CREATIVE STUDIO",64,58,520,30,14,"#ffffff","900",{letterSpacing:2.4})];
 const layouts:PublisherElement[][]=[
  [...common,rect(`${prefix}-panel`,-80,600,1240,560,dark,{rotation:-5,opacity:.96}),rect(`${prefix}-accent`,60,560,350,12,accent),text(`${prefix}-title`,title.toUpperCase(),60,650,880,190,72,"#ffffff","900",{fontFamily:"League Spartan",lineHeight:74}),text(`${prefix}-sub`,subtitle,65,865,700,90,22,"#e5e7eb","700",{lineHeight:31}),rect(`${prefix}-cta`,65,1030,320,66,accent,{borderRadius:8}),text(`${prefix}-cta-t`,"DISCOVER MORE",88,1049,274,28,16,dark,"900",{textAlign:"center",letterSpacing:1.8}),text(`${prefix}-foot`,"YAPOSAN.COM  •  410 555 0188",65,1180,600,30,14,"#ffffff","800",{letterSpacing:1.5})],
  [...common,rect(`${prefix}-left`,0,0,500,H,dark,{opacity:.97}),rect(`${prefix}-line`,455,0,36,H,accent),text(`${prefix}-kick`,"FEATURED EDITION",58,170,360,30,15,accent,"900",{letterSpacing:2.5}),text(`${prefix}-title`,title.toUpperCase(),55,240,430,260,68,"#ffffff","900",{fontFamily:"League Spartan",lineHeight:69}),text(`${prefix}-sub`,subtitle,58,540,365,105,21,"#d1d5db","700",{lineHeight:30}),rect(`${prefix}-box`,58,745,310,150,"rgba(255,255,255,.08)",{borderColor:accent,borderWidth:2}),text(`${prefix}-date`,"SEPTEMBER 2027",82,780,265,32,18,"#ffffff","900",{letterSpacing:1.4}),text(`${prefix}-place`,"BALTIMORE • MARYLAND",82,830,265,28,14,accent,"800",{letterSpacing:1.3}),text(`${prefix}-url`,"YAPOSAN.COM",58,1215,360,28,15,"#ffffff","900",{letterSpacing:2})],
  [...common,rect(`${prefix}-top`,0,0,W,500,dark,{opacity:.94}),rect(`${prefix}-band`,0,470,W,30,accent),text(`${prefix}-kick`,"A PROFESSIONAL PRESENTATION",70,95,760,30,15,accent,"900",{letterSpacing:2.8}),text(`${prefix}-title`,title.toUpperCase(),65,155,900,180,70,"#ffffff","900",{fontFamily:"League Spartan",lineHeight:70}),text(`${prefix}-sub`,subtitle,70,355,760,70,21,"#e5e7eb","700",{lineHeight:30}),rect(`${prefix}-card`,610,925,390,250,"rgba(255,255,255,.94)",{borderRadius:10}),text(`${prefix}-card1`,"SAVE THE DATE",650,970,310,30,16,dark,"900",{letterSpacing:2}),text(`${prefix}-card2`,"18 OCTOBER",650,1025,310,48,34,accent,"900",{fontFamily:"League Spartan"}),text(`${prefix}-card3`,"Details at yaposan.com",650,1100,310,28,15,"#475569","700")],
  [...common,rect(`${prefix}-diag`,-130,115,760,1240,dark,{rotation:-12,opacity:.97}),rect(`${prefix}-diag2`,520,-40,55,1450,accent,{rotation:-12}),text(`${prefix}-kick`,"PREMIUM SERIES",62,160,390,30,15,accent,"900",{letterSpacing:2.7}),text(`${prefix}-title`,title.toUpperCase(),55,250,500,270,70,"#ffffff","900",{fontFamily:"League Spartan",lineHeight:70}),text(`${prefix}-sub`,subtitle,62,560,390,105,21,"#d1d5db","700",{lineHeight:30}),circle(`${prefix}-badge`,770,860,220,220,accent),text(`${prefix}-badge1`,"2027",805,910,150,54,40,dark,"900",{textAlign:"center",fontFamily:"League Spartan"}),text(`${prefix}-badge2`,"SPECIAL EDITION",800,982,160,28,13,dark,"900",{textAlign:"center",letterSpacing:1.2}),text(`${prefix}-url`,"YAPOSAN.COM",58,1200,390,30,16,"#ffffff","900",{letterSpacing:2})],
  [...common,rect(`${prefix}-base`,58,625,964,600,"rgba(255,255,255,.94)",{borderRadius:8}),rect(`${prefix}-topline`,58,625,964,16,accent),text(`${prefix}-kick`,"CURATED FOR YOU",100,700,420,30,15,accent,"900",{letterSpacing:2.7}),text(`${prefix}-title`,title.toUpperCase(),95,755,840,170,66,dark,"900",{fontFamily:"League Spartan",lineHeight:67}),text(`${prefix}-sub`,subtitle,100,950,720,70,21,"#475569","700",{lineHeight:30}),rect(`${prefix}-rule`,100,1055,500,3,dark),text(`${prefix}-info`,"SEPTEMBER 18 • 7 PM • BALTIMORE",100,1090,720,30,16,dark,"900",{letterSpacing:1.5}),text(`${prefix}-url`,"YAPOSAN.COM",100,1150,520,28,15,accent,"900",{letterSpacing:2})]
 ];
 return page(`${prefix}-page`,title,W,H,"portrait",dark,layouts[variant%layouts.length]);
}

function make(config:{id:string;name:string;category:ProfessionalTemplateCategory;subcategory:string;industry:string;style:NonNullable<ProfessionalTemplate["metadata"]["style"]>;dark:string;accent:string;title:string;subtitle:string;photo:keyof typeof photo;variant:number;}):ProfessionalTemplate {
 return {metadata:{id:config.id,name:config.name,category:config.category,subcategory:config.subcategory,industry:config.industry,description:`A professional ${config.subcategory.toLowerCase()} template using strong photography, bold geometry, controlled typography, and fully editable Publisher objects.`,tags:[config.category.toLowerCase(),config.subcategory.toLowerCase(),config.industry.toLowerCase(),"editable","professional","phase 24.3D method"],pageSize:"1080 x 1350",orientation:"portrait" as TemplateOrientation,previewColor:config.accent,palette:[config.dark,config.accent,"#ffffff","#e5e7eb"],fonts:["League Spartan","Inter"],author:"Yaposan Design Studio",version:"43.4.7",editable:true,featured:true,trending:true,access:"premium",createdAt:NOW,updatedAt:NOW,style:config.style,masterTemplateId:config.id,qualityScore:100},pages:[compose(config.id,config.title,config.subtitle,config.dark,config.accent,photo[config.photo],config.variant)]};
}

const specs = [
  { id: "p4347-executive-strategy-report", name: "Executive Strategy Report", category: "Business" as ProfessionalTemplateCategory, subcategory: "Annual Reports", industry: "Corporate", style: "corporate" as const, dark: "#0f2747", accent: "#d6b25e", title: "STRATEGY 2027", subtitle: "A focused plan for resilient growth", photo: "office" as keyof typeof photo, variant: 0 },
  { id: "p4347-modern-consulting-proposal", name: "Modern Consulting Proposal", category: "Business" as ProfessionalTemplateCategory, subcategory: "Proposals", industry: "Consulting", style: "minimal" as const, dark: "#132a3a", accent: "#2dd4bf", title: "TRANSFORM WITH CLARITY", subtitle: "A practical roadmap for measurable change", photo: "office" as keyof typeof photo, variant: 1 },
  { id: "p4347-startup-investor-pitch-cover", name: "Startup Investor Pitch Cover", category: "Business" as ProfessionalTemplateCategory, subcategory: "Pitch Deck Covers", industry: "Startup", style: "bold" as const, dark: "#17152e", accent: "#8b5cf6", title: "BUILDING WHAT COMES NEXT", subtitle: "Seed round • 2027", photo: "technology" as keyof typeof photo, variant: 2 },
  { id: "p4347-professional-company-profile", name: "Professional Company Profile", category: "Business" as ProfessionalTemplateCategory, subcategory: "Company Profiles", industry: "Corporate", style: "editorial" as const, dark: "#1f2937", accent: "#f59e0b", title: "WHO WE ARE", subtitle: "Purpose. People. Performance.", photo: "office" as keyof typeof photo, variant: 3 },
  { id: "p4347-quarterly-results-snapshot", name: "Quarterly Results Snapshot", category: "Business" as ProfessionalTemplateCategory, subcategory: "Financial Reports", industry: "Finance", style: "corporate" as const, dark: "#0b3b60", accent: "#38bdf8", title: "Q3 PERFORMANCE", subtitle: "Momentum across every market", photo: "city" as keyof typeof photo, variant: 4 },
  { id: "p4347-black-friday-mega-sale", name: "Black Friday Mega Sale", category: "Retail" as ProfessionalTemplateCategory, subcategory: "Sale Flyers", industry: "Retail", style: "bold" as const, dark: "#111111", accent: "#ff3b30", title: "BLACK FRIDAY", subtitle: "UP TO 70% OFF", photo: "shop" as keyof typeof photo, variant: 0 },
  { id: "p4347-luxury-boutique-launch", name: "Luxury Boutique Launch", category: "Retail" as ProfessionalTemplateCategory, subcategory: "Grand Opening Flyers", industry: "Fashion Retail", style: "luxury" as const, dark: "#2b1b24", accent: "#d4af7a", title: "NOW OPEN", subtitle: "A new expression of modern style", photo: "fashion" as keyof typeof photo, variant: 1 },
  { id: "p4347-weekend-market-promotion", name: "Weekend Market Promotion", category: "Retail" as ProfessionalTemplateCategory, subcategory: "Market Posters", industry: "Local Retail", style: "creative" as const, dark: "#173b2c", accent: "#f4c95d", title: "WEEKEND MARKET", subtitle: "Local makers • Fresh finds", photo: "market" as keyof typeof photo, variant: 2 },
  { id: "p4347-new-collection-lookbook-cover", name: "New Collection Lookbook Cover", category: "Fashion" as ProfessionalTemplateCategory, subcategory: "Lookbook Covers", industry: "Fashion", style: "editorial" as const, dark: "#ede7df", accent: "#1f1f1f", title: "THE NEW EDIT", subtitle: "Autumn / Winter Collection", photo: "fashion" as keyof typeof photo, variant: 3 },
  { id: "p4347-minimal-product-drop-post", name: "Minimal Product Drop Post", category: "Fashion" as ProfessionalTemplateCategory, subcategory: "Product Launch Posts", industry: "Fashion", style: "minimal" as const, dark: "#f3f0ea", accent: "#d9485f", title: "LIMITED DROP", subtitle: "Designed in small numbers", photo: "fashion" as keyof typeof photo, variant: 4 },
  { id: "p4347-coffee-house-seasonal-menu", name: "Coffee House Seasonal Menu", category: "Restaurant" as ProfessionalTemplateCategory, subcategory: "Menus", industry: "Food & Beverage", style: "editorial" as const, dark: "#4a2f27", accent: "#d9a066", title: "AUTUMN MENU", subtitle: "Warm flavors for cooler days", photo: "coffee" as keyof typeof photo, variant: 0 },
  { id: "p4347-modern-brunch-promotion", name: "Modern Brunch Promotion", category: "Restaurant" as ProfessionalTemplateCategory, subcategory: "Restaurant Flyers", industry: "Hospitality", style: "creative" as const, dark: "#fff4e6", accent: "#f97316", title: "BRUNCH CLUB", subtitle: "Sundays made better", photo: "food" as keyof typeof photo, variant: 1 },
  { id: "p4347-fine-dining-tasting-menu", name: "Fine Dining Tasting Menu", category: "Restaurant" as ProfessionalTemplateCategory, subcategory: "Tasting Menus", industry: "Hospitality", style: "elegant" as const, dark: "#18231f", accent: "#c7a96b", title: "CHEF’S TASTING", subtitle: "Seven courses • One evening", photo: "food" as keyof typeof photo, variant: 2 },
  { id: "p4347-pizza-night-social-post", name: "Pizza Night Social Post", category: "Restaurant" as ProfessionalTemplateCategory, subcategory: "Social Media Posts", industry: "Food & Beverage", style: "bold" as const, dark: "#b42318", accent: "#fbbf24", title: "PIZZA NIGHT", subtitle: "Two pies. One perfect price.", photo: "pizza" as keyof typeof photo, variant: 3 },
  { id: "p4347-dental-care-awareness-flyer", name: "Dental Care Awareness Flyer", category: "Healthcare" as ProfessionalTemplateCategory, subcategory: "Awareness Flyers", industry: "Healthcare", style: "minimal" as const, dark: "#e8f5f7", accent: "#0f8b8d", title: "SMILE WITH CONFIDENCE", subtitle: "Preventive care for every age", photo: "clinic" as keyof typeof photo, variant: 4 },
  { id: "p4347-wellness-clinic-open-house", name: "Wellness Clinic Open House", category: "Healthcare" as ProfessionalTemplateCategory, subcategory: "Open House Flyers", industry: "Healthcare", style: "elegant" as const, dark: "#f1f7f3", accent: "#3d7a5f", title: "WELLNESS OPEN HOUSE", subtitle: "Meet the team. Tour the space.", photo: "wellness" as keyof typeof photo, variant: 0 },
  { id: "p4347-mental-wellness-workshop", name: "Mental Wellness Workshop", category: "Healthcare" as ProfessionalTemplateCategory, subcategory: "Workshop Posters", industry: "Healthcare", style: "editorial" as const, dark: "#22223b", accent: "#9a8c98", title: "PAUSE. RESET. RENEW.", subtitle: "A guided evening for your wellbeing", photo: "wellness" as keyof typeof photo, variant: 1 },
  { id: "p4347-community-vaccination-day", name: "Community Vaccination Day", category: "Healthcare" as ProfessionalTemplateCategory, subcategory: "Community Flyers", industry: "Public Health", style: "bold" as const, dark: "#0f4c81", accent: "#22c55e", title: "VACCINATION DAY", subtitle: "Free community health services", photo: "clinic" as keyof typeof photo, variant: 2 },
  { id: "p4347-university-research-symposium", name: "University Research Symposium", category: "Education" as ProfessionalTemplateCategory, subcategory: "Event Posters", industry: "Higher Education", style: "corporate" as const, dark: "#172554", accent: "#facc15", title: "RESEARCH SYMPOSIUM", subtitle: "Ideas that shape tomorrow", photo: "school" as keyof typeof photo, variant: 3 },
  { id: "p4347-preschool-enrollment-flyer", name: "Preschool Enrollment Flyer", category: "Education" as ProfessionalTemplateCategory, subcategory: "Enrollment Flyers", industry: "Education", style: "creative" as const, dark: "#fff7ed", accent: "#fb7185", title: "LEARN • PLAY • GROW", subtitle: "Now enrolling young explorers", photo: "kids" as keyof typeof photo, variant: 4 },
  { id: "p4347-online-course-promotion", name: "Online Course Promotion", category: "Education" as ProfessionalTemplateCategory, subcategory: "Course Flyers", industry: "Education", style: "bold" as const, dark: "#312e81", accent: "#a78bfa", title: "MASTER THE SKILL", subtitle: "Learn online at your pace", photo: "laptop" as keyof typeof photo, variant: 0 },
  { id: "p4347-graduation-celebration-invitation", name: "Graduation Celebration Invitation", category: "Education" as ProfessionalTemplateCategory, subcategory: "Graduation Invitations", industry: "Education", style: "elegant" as const, dark: "#101827", accent: "#d4af37", title: "CLASS OF 2027", subtitle: "Celebrate the journey", photo: "graduation" as keyof typeof photo, variant: 1 },
  { id: "p4347-ai-product-launch-poster", name: "AI Product Launch Poster", category: "Technology" as ProfessionalTemplateCategory, subcategory: "Product Launch Posters", industry: "Technology", style: "bold" as const, dark: "#090b1a", accent: "#22d3ee", title: "INTELLIGENCE, REIMAGINED", subtitle: "The next generation starts here", photo: "technology" as keyof typeof photo, variant: 2 },
  { id: "p4347-cybersecurity-webinar-flyer", name: "Cybersecurity Webinar Flyer", category: "Technology" as ProfessionalTemplateCategory, subcategory: "Webinar Flyers", industry: "Technology", style: "corporate" as const, dark: "#061a2b", accent: "#00c2ff", title: "SECURE THE FUTURE", subtitle: "Live cybersecurity briefing", photo: "cyber" as keyof typeof photo, variant: 3 },
  { id: "p4347-saas-feature-announcement", name: "SaaS Feature Announcement", category: "Technology" as ProfessionalTemplateCategory, subcategory: "Product Announcements", industry: "Software", style: "minimal" as const, dark: "#f8fafc", accent: "#2563eb", title: "WORK SMARTER", subtitle: "New automation tools are here", photo: "laptop" as keyof typeof photo, variant: 4 },
  { id: "p4347-developer-conference-pass", name: "Developer Conference Pass", category: "Technology" as ProfessionalTemplateCategory, subcategory: "Conference Flyers", industry: "Technology", style: "creative" as const, dark: "#14121f", accent: "#f43f5e", title: "CODE FORWARD", subtitle: "Three days of ideas and innovation", photo: "code" as keyof typeof photo, variant: 0 },
  { id: "p4347-luxury-home-open-house", name: "Luxury Home Open House", category: "Real Estate" as ProfessionalTemplateCategory, subcategory: "Open House Flyers", industry: "Real Estate", style: "luxury" as const, dark: "#1f2937", accent: "#c9a76a", title: "OPEN HOUSE", subtitle: "Modern living, beautifully framed", photo: "house" as keyof typeof photo, variant: 1 },
  { id: "p4347-urban-apartment-listing", name: "Urban Apartment Listing", category: "Real Estate" as ProfessionalTemplateCategory, subcategory: "Property Flyers", industry: "Real Estate", style: "editorial" as const, dark: "#f2eee8", accent: "#b45309", title: "CITY LIVING", subtitle: "Light-filled residence in the heart of downtown", photo: "apartment" as keyof typeof photo, variant: 2 },
  { id: "p4347-commercial-property-brochure-cover", name: "Commercial Property Brochure Cover", category: "Real Estate" as ProfessionalTemplateCategory, subcategory: "Brochure Covers", industry: "Commercial Real Estate", style: "corporate" as const, dark: "#0b2739", accent: "#40b7ad", title: "SPACE FOR GROWTH", subtitle: "Premium commercial opportunity", photo: "building" as keyof typeof photo, variant: 3 },
  { id: "p4347-real-estate-agent-social-post", name: "Real Estate Agent Social Post", category: "Real Estate" as ProfessionalTemplateCategory, subcategory: "Social Media Posts", industry: "Real Estate", style: "minimal" as const, dark: "#ffffff", accent: "#0f766e", title: "JUST LISTED", subtitle: "A standout property in a prime location", photo: "house" as keyof typeof photo, variant: 4 },
  { id: "p4347-championship-game-poster", name: "Championship Game Poster", category: "Sports" as ProfessionalTemplateCategory, subcategory: "Game Posters", industry: "Sports", style: "bold" as const, dark: "#111827", accent: "#f97316", title: "CHAMPIONSHIP NIGHT", subtitle: "One game. Everything on the line.", photo: "sports" as keyof typeof photo, variant: 0 },
  { id: "p4347-fitness-bootcamp-flyer", name: "Fitness Bootcamp Flyer", category: "Sports" as ProfessionalTemplateCategory, subcategory: "Fitness Flyers", industry: "Fitness", style: "creative" as const, dark: "#0f172a", accent: "#84cc16", title: "STRONGER STARTS NOW", subtitle: "Four weeks to a better routine", photo: "fitness" as keyof typeof photo, variant: 1 },
  { id: "p4347-youth-soccer-registration", name: "Youth Soccer Registration", category: "Sports" as ProfessionalTemplateCategory, subcategory: "Registration Flyers", industry: "Youth Sports", style: "bold" as const, dark: "#064e3b", accent: "#facc15", title: "JOIN THE TEAM", subtitle: "Registration now open", photo: "soccer" as keyof typeof photo, variant: 2 },
  { id: "p4347-marathon-event-poster", name: "Marathon Event Poster", category: "Sports" as ProfessionalTemplateCategory, subcategory: "Race Posters", industry: "Running", style: "editorial" as const, dark: "#f8fafc", accent: "#ef4444", title: "RUN THE CITY", subtitle: "26.2 miles of determination", photo: "running" as keyof typeof photo, variant: 3 },
  { id: "p4347-sunday-worship-invitation", name: "Sunday Worship Invitation", category: "Church" as ProfessionalTemplateCategory, subcategory: "Church Flyers", industry: "Faith", style: "elegant" as const, dark: "#efe9df", accent: "#8b6f47", title: "YOU ARE WELCOME", subtitle: "A place for hope, faith, and community", photo: "church" as keyof typeof photo, variant: 4 },
  { id: "p4347-youth-ministry-night", name: "Youth Ministry Night", category: "Church" as ProfessionalTemplateCategory, subcategory: "Youth Event Flyers", industry: "Faith", style: "creative" as const, dark: "#17122c", accent: "#a855f7", title: "YOUTH NIGHT", subtitle: "Music • Message • Community", photo: "concert" as keyof typeof photo, variant: 0 },
  { id: "p4347-community-food-drive", name: "Community Food Drive", category: "Church" as ProfessionalTemplateCategory, subcategory: "Community Outreach Flyers", industry: "Nonprofit", style: "bold" as const, dark: "#143d2b", accent: "#f59e0b", title: "GIVE WITH PURPOSE", subtitle: "Help stock local families’ tables", photo: "community" as keyof typeof photo, variant: 1 },
  { id: "p4347-podcast-season-launch", name: "Podcast Season Launch", category: "Podcast" as ProfessionalTemplateCategory, subcategory: "Podcast Covers", industry: "Media", style: "editorial" as const, dark: "#1d1734", accent: "#f472b6", title: "NEW SEASON", subtitle: "Stories worth hearing", photo: "podcast" as keyof typeof photo, variant: 2 },
  { id: "p4347-business-podcast-episode-cover", name: "Business Podcast Episode Cover", category: "Podcast" as ProfessionalTemplateCategory, subcategory: "Episode Covers", industry: "Business Media", style: "corporate" as const, dark: "#0f172a", accent: "#38bdf8", title: "THE GROWTH PLAYBOOK", subtitle: "Episode 42", photo: "microphone" as keyof typeof photo, variant: 3 },
  { id: "p4347-gaming-stream-schedule", name: "Gaming Stream Schedule", category: "Streaming" as ProfessionalTemplateCategory, subcategory: "Stream Schedules", industry: "Gaming", style: "bold" as const, dark: "#100c24", accent: "#7c3aed", title: "LIVE THIS WEEK", subtitle: "Streams • Challenges • Community", photo: "gaming" as keyof typeof photo, variant: 4 },
  { id: "p4347-creator-livestream-announcement", name: "Creator Livestream Announcement", category: "Streaming" as ProfessionalTemplateCategory, subcategory: "Livestream Posts", industry: "Creator", style: "creative" as const, dark: "#180b18", accent: "#ec4899", title: "GOING LIVE", subtitle: "Join the conversation tonight", photo: "streaming" as keyof typeof photo, variant: 0 },
  { id: "p4347-youtube-documentary-thumbnail", name: "YouTube Documentary Thumbnail", category: "YouTube" as ProfessionalTemplateCategory, subcategory: "Video Thumbnails", industry: "Media", style: "editorial" as const, dark: "#111827", accent: "#f59e0b", title: "THE UNTOLD STORY", subtitle: "A documentary premiere", photo: "documentary" as keyof typeof photo, variant: 1 },
  { id: "p4347-youtube-tech-review-thumbnail", name: "YouTube Tech Review Thumbnail", category: "YouTube" as ProfessionalTemplateCategory, subcategory: "Video Thumbnails", industry: "Technology Media", style: "bold" as const, dark: "#0b1020", accent: "#22d3ee", title: "WORTH THE UPGRADE?", subtitle: "Full review and real-world test", photo: "gadget" as keyof typeof photo, variant: 2 },
  { id: "p4347-baby-shower-invitation", name: "Baby Shower Invitation", category: "Personal" as ProfessionalTemplateCategory, subcategory: "Baby Shower Invitations", industry: "Personal Events", style: "elegant" as const, dark: "#f8f1ec", accent: "#c58c85", title: "A LITTLE ONE IS ON THE WAY", subtitle: "Join us for a beautiful afternoon", photo: "baby" as keyof typeof photo, variant: 3 },
  { id: "p4347-retirement-celebration-invitation", name: "Retirement Celebration Invitation", category: "Personal" as ProfessionalTemplateCategory, subcategory: "Retirement Invitations", industry: "Personal Events", style: "editorial" as const, dark: "#172a3a", accent: "#d9b36c", title: "A LIFE WELL WORKED", subtitle: "Celebrating 35 remarkable years", photo: "celebration" as keyof typeof photo, variant: 4 },
  { id: "p4347-holiday-party-invitation", name: "Holiday Party Invitation", category: "Events" as ProfessionalTemplateCategory, subcategory: "Holiday Invitations", industry: "Events", style: "luxury" as const, dark: "#18392b", accent: "#d6b25e", title: "HOLIDAY SOIRÉE", subtitle: "An evening of sparkle and celebration", photo: "holiday" as keyof typeof photo, variant: 0 },
  { id: "p4347-charity-gala-poster", name: "Charity Gala Poster", category: "Events" as ProfessionalTemplateCategory, subcategory: "Gala Posters", industry: "Nonprofit Events", style: "elegant" as const, dark: "#16131a", accent: "#c9a76a", title: "AN EVENING OF IMPACT", subtitle: "Dinner • Auction • Inspiration", photo: "gala" as keyof typeof photo, variant: 1 },
  { id: "p4347-art-exhibition-poster", name: "Art Exhibition Poster", category: "Events" as ProfessionalTemplateCategory, subcategory: "Exhibition Posters", industry: "Arts", style: "editorial" as const, dark: "#f4f1ec", accent: "#111111", title: "NEW PERSPECTIVES", subtitle: "Contemporary works in dialogue", photo: "art" as keyof typeof photo, variant: 2 },
  { id: "p4347-travel-adventure-social-post", name: "Travel Adventure Social Post", category: "Social Media" as ProfessionalTemplateCategory, subcategory: "Travel Posts", industry: "Travel", style: "creative" as const, dark: "#0f4c5c", accent: "#f4a261", title: "GO SOMEWHERE NEW", subtitle: "Your next adventure starts here", photo: "travel" as keyof typeof photo, variant: 3 },
  { id: "p4347-motivational-quote-post", name: "Motivational Quote Post", category: "Social Media" as ProfessionalTemplateCategory, subcategory: "Quote Posts", industry: "Lifestyle", style: "minimal" as const, dark: "#f6f2eb", accent: "#1f2937", title: "MAKE ROOM FOR POSSIBILITY", subtitle: "Small steps create big change", photo: "mountain" as keyof typeof photo, variant: 4 },
] as const;

export const PHASE4347_FIFTY_PROFESSIONAL_TEMPLATES: ProfessionalTemplate[] = specs.map(make);
export const PHASE4347_TEMPLATE_COUNT = PHASE4347_FIFTY_PROFESSIONAL_TEMPLATES.length;
export function phase4347Audit(){const ids=PHASE4347_FIFTY_PROFESSIONAL_TEMPLATES.map(t=>t.metadata.id);return{templateCount:PHASE4347_TEMPLATE_COUNT,pageCount:PHASE4347_FIFTY_PROFESSIONAL_TEMPLATES.reduce((s,t)=>s+t.pages.length,0),elementCount:PHASE4347_FIFTY_PROFESSIONAL_TEMPLATES.reduce((s,t)=>s+t.pages.reduce((p,e)=>p+e.elements.length,0),0),duplicateIds:ids.length-new Set(ids).size,allEditable:PHASE4347_FIFTY_PROFESSIONAL_TEMPLATES.every(t=>t.metadata.editable),allUseDirectPublisherObjects:PHASE4347_FIFTY_PROFESSIONAL_TEMPLATES.every(t=>t.pages.every(p=>p.elements.length>=10))};}
