import { DEFAULT_BLEED } from "../constants/publisher";
import type { PublisherElement, PublisherPage } from "../types/publisher";
import type { ProfessionalTemplate, ProfessionalTemplateCategory, TemplateOrientation } from "./types";

const NOW = "2026-07-31T00:00:00.000Z";
const el=(id:string,name:string,type:PublisherElement["type"],x:number,y:number,width:number,height:number,zIndex:number,extra:Partial<PublisherElement>={}):PublisherElement=>({id,name,type,x,y,width,height,rotation:0,zIndex,opacity:1,...extra});
const rect=(id:string,x:number,y:number,w:number,h:number,fillColor:string,extra:Partial<PublisherElement>={})=>el(id,id,"rectangle",x,y,w,h,5,{fillColor,borderWidth:0,...extra});
const circle=(id:string,x:number,y:number,w:number,h:number,fillColor:string,extra:Partial<PublisherElement>={})=>el(id,id,"ellipse",x,y,w,h,6,{fillColor,borderWidth:0,...extra});
const text=(id:string,value:string,x:number,y:number,w:number,h:number,size:number,color:string,weight:PublisherElement["fontWeight"]="700",extra:Partial<PublisherElement>={})=>el(id,value.slice(0,30),"text",x,y,w,h,20,{text:value,fontSize:size,textColor:color,fontWeight:weight,lineHeight:size*1.18,...extra});
const image=(id:string,uri:string,x:number,y:number,w:number,h:number,extra:Partial<PublisherElement>={})=>el(id,id,"image",x,y,w,h,8,{imageUri:uri,imageFit:"cover",...extra});

const PHOTOS=[
"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1800&q=90",
"https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1800&q=90"
];
const PALETTES:[string,string,string,string][]= [
["#0b132b","#5bc0be","#f8fafc","#3a506b"],["#111827","#f59e0b","#fff7ed","#6b7280"],["#f8fafc","#2563eb","#0f172a","#cbd5e1"],["#1f2937","#e11d48","#fff1f2","#64748b"],["#102a43","#d9b44a","#f0f4f8","#486581"],["#2d1b33","#d6a2e8","#fff7ff","#70587c"],["#0f172a","#22c55e","#ecfdf5","#334155"],["#fff7ed","#ea580c","#292524","#fed7aa"],["#18181b","#a3e635","#fafafa","#52525b"],["#f5f3ff","#7c3aed","#1e1b4b","#ddd6fe"],
["#0c4a6e","#38bdf8","#f0f9ff","#075985"],["#3f1d2e","#fb7185","#fff1f2","#7f1d1d"],["#052e16","#84cc16","#f7fee7","#365314"],["#292524","#d97706","#fffbeb","#78716c"],["#0a0a0a","#d4af37","#fffdf5","#404040"]
];
const FONTS:[string,string][]= [["Montserrat","Inter"],["Cormorant Garamond","Inter"],["Sora","Inter"],["Playfair Display","Source Sans Pro"],["Oswald","Inter"],["Libre Baskerville","Inter"],["Poppins","Inter"],["DM Sans","Space Grotesk"],["Cinzel","Montserrat"],["Bebas Neue","Inter"]];
const SERIES=["Summit","Axis","Prism","Foundry","Meridian","Cobalt","Vantage","Ember","Harbor","Aperture","Atlas","Mosaic","Northstar","Crescent","Monument","Lumen","Evergreen","Signal","Terrace","Quarry","Orbit","Civic","Sterling","Canvas","Vertex","Horizon","Forge","Noble","Pulse","Keystone"];

type Spec={category:ProfessionalTemplateCategory;slug:string;industry:string;types:string[]};
const SPECS:Spec[]=[
{category:"Business",slug:"business",industry:"Business",types:["Corporate Letterhead","Executive Letterhead","Company Profile","Annual Report Cover","Business Proposal","Modern Invoice","Corporate Invoice","Purchase Order","Receipt","Quotation","Contract Cover","Meeting Agenda","Premium Business Card","Minimal Business Card","Employee ID","Presentation Cover","Sales Report","Financial Report","KPI Dashboard","Project Proposal","Executive Resume","Creative Resume","Cover Letter","Achievement Certificate","Completion Certificate","Corporate Flyer","Company Brochure","Tri-fold Brochure","Business Newsletter","Office Poster"]},
{category:"Marketing",slug:"marketing",industry:"Marketing",types:["Product Flyer","Promotion Flyer","Sale Poster","Grand Opening","Coupon","Gift Voucher","Price List","Catalog Cover","Product Catalog","Email Newsletter","Event Brochure","Trade Show Banner","Roll-up Banner","Social Ad","Landing Page Cover","Facebook Campaign","Instagram Promotion","Marketing Proposal","Media Kit","Press Kit","Billboard","Business Promo Poster","Rack Card","Postcard","Thank You Card","Loyalty Card","Packaging Insert","Product Label","Shelf Talker","Marketing Presentation"]},
{category:"Social Media",slug:"social-media",industry:"Digital Marketing",types:["Instagram Post","Instagram Story","Facebook Cover","Facebook Post","X Banner","LinkedIn Banner","LinkedIn Post","Pinterest Pin","TikTok Cover","YouTube Thumbnail","YouTube Banner","YouTube End Screen","Twitch Banner","Discord Banner","WhatsApp Status","Snapchat Story","Reel Cover","Carousel Post","Social Quote","Giveaway","Podcast Cover","Webinar Cover","Live Stream Cover","Holiday Post","Product Launch","Countdown","Testimonial","Review Card","Before and After","Social Media Kit"]},
{category:"Real Estate",slug:"real-estate",industry:"Real Estate",types:["Luxury Listing","Open House","Property Flyer","Property Brochure","Apartment Listing","Rental Flyer","Agent Business Card","Sold Announcement","Just Listed","Just Sold","Commercial Property","Property Catalog","Neighborhood Guide","Investment Property","Luxury Home","Modern Condo","Farm Property","Office Space","Retail Space","Warehouse","Property Sign","Window Display","Property Newsletter","Agent Resume","Client Welcome","Closing Folder","Property Report","Presentation Cover","Real Estate Calendar","Real Estate Social Kit"]},
{category:"Restaurant",slug:"restaurant",industry:"Restaurant",types:["Classic Menu","Modern Menu","Coffee Menu","Dessert Menu","Pizza Menu","Breakfast Menu","Dinner Menu","Wine List","Cocktail Menu","Catering Menu","Food Flyer","Restaurant Poster","Grand Opening","Chef Certificate","Gift Card","Table Tent","Loyalty Card","Food Label","Packaging Box","Takeout Bag","Delivery Flyer","Weekly Special","Event Menu","Food Brochure","Recipe Book Cover","Reservation Card","QR Menu","Restaurant Newsletter","Restaurant Social Kit","Presentation Cover"]},
{category:"Healthcare",slug:"healthcare",industry:"Healthcare",types:["Clinic Flyer","Hospital Brochure","Medical Poster","Health Awareness","Vaccine Poster","Dental Flyer","Pharmacy Flyer","Medical Resume","Patient Form","Appointment Card","Prescription Pad","Medical Invoice","Lab Report","Wellness Newsletter","Healthcare Calendar","Medical Certificate","Medical Label","Health Presentation","Doctor Business Card","Emergency Poster","Health Fair Flyer","Medical Packaging","Clinic Letterhead","Patient Guide","Medical Social Kit","Fitness Health Flyer","Insurance Form","Health Report","Medical Book Cover","Medical Envelope"]},
{category:"Education",slug:"education",industry:"Education",types:["School Flyer","University Brochure","Graduation Certificate","Diploma","Student Resume","School Newsletter","Class Schedule","Academic Calendar","Book Cover","Workbook Cover","Science Poster","Math Poster","School Letterhead","School Envelope","Course Catalog","Presentation Cover","Attendance Sheet","Student ID","Parent Newsletter","Event Flyer","Open House","Education Social Kit","Teacher Planner","Lesson Plan","School Report","Reading Log","Award Certificate","Classroom Poster","Education Invoice","Academic Brochure"]},
{category:"Technology",slug:"technology",industry:"Technology",types:["SaaS Brochure","Startup Pitch","App Presentation","Product Launch","Software Flyer","Technology Poster","Tech Resume","Developer Resume","Startup Invoice","Product Roadmap","API Documentation Cover","Whitepaper Cover","Product Catalog","Dashboard Cover","IT Newsletter","Tech Letterhead","Conference Flyer","Hackathon Poster","Cybersecurity Brochure","AI Presentation","Cloud Brochure","Mobile App Flyer","Web Agency Flyer","UX Portfolio","Technology Calendar","Tech Certificate","Product Label","Technology Packaging","Technology Social Kit","Technology Book Cover"]},
{category:"Fashion",slug:"fashion",industry:"Fashion",types:["Fashion Magazine Cover","Clothing Catalog","Boutique Flyer","Fashion Poster","Product Tag","Clothing Label","Shopping Bag","Packaging Box","Lookbook","Style Guide","Fashion Newsletter","Brand Brochure","Designer Resume","Fashion Calendar","Fashion Presentation","Runway Invitation","Collection Launch","Sale Poster","Luxury Flyer","Brand Certificate","Gift Card","Price List","Fashion Social Kit","Instagram Fashion","Product Card","Clothing Invoice","Fashion Book Cover","Boutique Letterhead","Boutique Envelope","Fashion Menu"]},
{category:"Sports",slug:"sports",industry:"Sports",types:["Gym Flyer","Fitness Poster","Sports Brochure","Tournament Poster","Match Schedule","Team Roster","Athlete Resume","Sports Newsletter","Event Ticket","Sports Certificate","Award Certificate","Training Calendar","Workout Planner","Sports Book Cover","Sports Presentation","Marathon Flyer","Football Poster","Basketball Poster","Baseball Poster","Soccer Flyer","Tennis Poster","Cycling Flyer","Swimming Poster","Fitness Social Kit","Sports Banner","Membership Card","Nutrition Guide","Gym Price List","Sports Label","Sports Packaging"]}
];
function dimensions(type:string):{pageSize:string;width:number;height:number;orientation:TemplateOrientation}{const t=type.toLowerCase();if(t.includes("story")||t.includes("status")||t.includes("snapchat")||t.includes("reel"))return{pageSize:"1080 x 1920 Story",width:1080,height:1920,orientation:"portrait"};if(t.includes("banner")||t.includes("cover")&&!(t.includes("book")||t.includes("magazine"))||t.includes("presentation")||t.includes("billboard"))return{pageSize:"16:9 Digital",width:1280,height:720,orientation:"landscape"};if(t.includes("business card")||t.includes("appointment card")||t.includes("loyalty card")||t.includes("gift card")||t.includes("membership card")||t.includes("employee id")||t.includes("student id"))return{pageSize:"Business Card",width:1050,height:600,orientation:"landscape"};if(t.includes("social")||t.includes("instagram")||t.includes("facebook post")||t.includes("pinterest")||t.includes("tiktok")||t.includes("giveaway")||t.includes("countdown")||t.includes("testimonial")||t.includes("review card")||t.includes("before and after"))return{pageSize:"1080 x 1080 Social",width:1080,height:1080,orientation:"square"};if(t.includes("brochure")||t.includes("calendar")||t.includes("certificate")||t.includes("diploma")||t.includes("schedule")||t.includes("roster"))return{pageSize:"US Letter Landscape",width:1056,height:816,orientation:"landscape"};return{pageSize:"US Letter",width:816,height:1056,orientation:"portrait"};}
function copy(spec:Spec,type:string){return `${type.toUpperCase()}\n${spec.industry} communication designed for clarity, confidence, and action.`;}
function layout(prefix:string,W:number,H:number,n:number,p:[string,string,string,string],fonts:[string,string],photo:string,title:string,subtitle:string):PublisherElement[]{const [bg,accent,paper,muted]=p;const light=["#f8fafc","#fff7ed","#fafafa","#f5f3ff","#ecfeff","#ffffff","#f7fee7","#fffbeb","#fffdf5"].includes(bg);const ink=light?"#111827":paper;const pad=Math.max(24,Math.round(Math.min(W,H)*.055));const e:PublisherElement[]=[rect(`${prefix}-bg`,0,0,W,H,bg)];const v=n%15;
if(v===0)e.push(image(`${prefix}-photo`,photo,W*.55,0,W*.45,H),rect(`${prefix}-rail`,0,0,W*.05,H,accent),circle(`${prefix}-orb`,W*.42,H*.72,W*.16,W*.16,accent));
if(v===1)e.push(rect(`${prefix}-top`,0,0,W,H*.24,accent),image(`${prefix}-photo`,photo,W*.58,H*.14,W*.34,H*.42,{rotation:3}),rect(`${prefix}-rule`,pad,H*.72,W*.48,3,accent));
if(v===2)e.push(image(`${prefix}-photo`,photo,0,0,W,H*.43),rect(`${prefix}-shade`,0,0,W,H*.43,"#000000",{opacity:.3}),rect(`${prefix}-side`,0,H*.43,W*.14,H*.57,accent));
if(v===3)e.push(rect(`${prefix}-diag`,W*.62,-H*.2,W*.48,H*1.35,accent,{rotation:14}),circle(`${prefix}-ring`,W*.69,H*.49,W*.2,W*.2,"transparent",{borderColor:paper,borderWidth:4}));
if(v===4)e.push(rect(`${prefix}-left`,0,0,W*.38,H,accent),image(`${prefix}-photo`,photo,W*.07,H*.1,W*.25,H*.25,{borderRadius:12}),rect(`${prefix}-micro`,W*.46,H*.84,W*.4,H*.02,accent));
if(v===5)e.push(...[0,1,2,3].map(i=>rect(`${prefix}-stripe-${i}`,W*(.62+i*.075),0,W*.035,H,i%2?paper:accent,{opacity:i%2?.45:1})),circle(`${prefix}-dot`,W*.08,H*.09,W*.1,W*.1,accent));
if(v===6)e.push(image(`${prefix}-photo`,photo,W*.06,H*.07,W*.88,H*.34,{borderRadius:16}),rect(`${prefix}-panel`,W*.1,H*.34,W*.8,H*.57,paper,{opacity:.96}),rect(`${prefix}-edge`,W*.1,H*.34,W*.015,H*.57,accent));
if(v===7)e.push(circle(`${prefix}-big`,W*.6,-H*.1,W*.55,W*.55,accent),circle(`${prefix}-small`,W*.72,H*.56,W*.21,W*.21,paper,{opacity:.45}),image(`${prefix}-photo`,photo,W*.7,H*.15,W*.22,H*.26,{borderRadius:8}));
if(v===8)e.push(rect(`${prefix}-grid-v1`,W*.58,0,1,H,accent),rect(`${prefix}-grid-v2`,W*.76,0,1,H,accent),rect(`${prefix}-grid-h`,0,H*.69,W,1,accent),image(`${prefix}-photo`,photo,W*.61,H*.11,W*.31,H*.46));
if(v===9)e.push(rect(`${prefix}-frame`,pad,pad,W-pad*2,H-pad*2,"transparent",{borderColor:accent,borderWidth:3}),circle(`${prefix}-orb`,W*.69,H*.07,W*.23,W*.23,accent),rect(`${prefix}-rule`,pad,H*.61,W*.43,2,accent));
if(v===10)e.push(rect(`${prefix}-block-a`,0,0,W*.46,H*.5,accent),image(`${prefix}-photo`,photo,W*.46,0,W*.54,H*.5),rect(`${prefix}-block-b`,W*.54,H*.5,W*.46,H*.5,paper,{opacity:.12}));
if(v===11)e.push(image(`${prefix}-photo`,photo,W*.08,H*.1,W*.4,H*.78,{borderRadius:4}),rect(`${prefix}-bar-a`,W*.54,H*.13,W*.34,H*.055,accent),rect(`${prefix}-bar-b`,W*.54,H*.22,W*.2,H*.018,muted));
if(v===12)e.push(rect(`${prefix}-quarter`,0,0,W,H*.14,accent),circle(`${prefix}-c1`,W*.61,H*.22,W*.25,W*.25,"transparent",{borderColor:accent,borderWidth:5}),circle(`${prefix}-c2`,W*.74,H*.35,W*.13,W*.13,accent));
if(v===13)e.push(rect(`${prefix}-column`,W*.68,0,W*.32,H,accent),image(`${prefix}-photo`,photo,W*.08,H*.55,W*.52,H*.31,{borderRadius:14}),rect(`${prefix}-tick`,W*.61,H*.56,W*.03,H*.31,paper,{opacity:.4}));
if(v===14)e.push(...Array.from({length:6},(_,i)=>rect(`${prefix}-tile-${i}`,W*(.58+(i%2)*.18),H*(.1+Math.floor(i/2)*.22),W*.14,H*.16,i%3===0?accent:i%3===1?paper:muted,{opacity:i%3===1?.2:.9})),circle(`${prefix}-seal`,W*.72,H*.76,W*.13,W*.13,accent));
const q=Math.floor(n/15);const shift=(q%10)*.012;e.push(rect(`${prefix}-edition-mark`,W*(.04+shift),H*(.76-(q%4)*.025),W*(.18+(q%3)*.035),H*(.055+(q%2)*.025),q%2===0?accent:muted,{rotation:(q%7)-3,opacity:.72}),circle(`${prefix}-edition-dot`,W*(.42+shift),H*(.07+(q%5)*.018),W*(.045+(q%3)*.012),W*(.045+(q%3)*.012),q%3===0?paper:accent,{opacity:.72}));
const left=[0,3,8,13,14].includes(v)?pad:(v===4?W*.44:pad);const avail=v===4?W*.48:([0,3,8,13,14].includes(v)?W*.51:W*.72);const ty=v===2?H*.48:(v===1?H*.31:H*.27);e.push(text(`${prefix}-eyebrow`,subtitle.toUpperCase(),left,ty-H*.07,avail,H*.04,Math.max(10,H*.017),accent,"800",{fontFamily:fonts[1],letterSpacing:1.4}),text(`${prefix}-title`,title.toUpperCase(),left,ty,avail,H*.2,Math.max(27,H*.061),ink,"900",{fontFamily:fonts[0],lineHeight:Math.max(32,H*.065)}),text(`${prefix}-body`,"A fully editable Phase 24.3D publication system with precise spacing, premium typography, and a focused visual hierarchy.",left,ty+H*.22,avail,H*.13,Math.max(12,H*.022),ink,"500",{fontFamily:fonts[1],lineHeight:Math.max(18,H*.032),opacity:.9}),text(`${prefix}-cta`,"YAPOSAN DESIGN STUDIO  •  EDITABLE  •  PRINT READY",left,H*.91,avail,H*.03,Math.max(8,H*.013),ink,"700",{fontFamily:fonts[1],letterSpacing:.7}));return e;}
function detailElements(prefix:string,W:number,H:number,type:string,p:[string,string,string,string],fonts:[string,string]):PublisherElement[]{const [,accent,paper,muted]=p;const out:PublisherElement[]=[];const t=type.toLowerCase();if(t.includes("invoice")||t.includes("quotation")||t.includes("purchase order")||t.includes("price list")){for(let i=0;i<4;i++)out.push(rect(`${prefix}-row-${i}`,W*.1,H*(.58+i*.055),W*.8,1,muted));out.push(text(`${prefix}-total`,`TOTAL  $3,180.00`,W*.57,H*.81,W*.3,H*.05,Math.max(15,H*.025),accent,"900",{textAlign:"right",fontFamily:fonts[1]}));}if(t.includes("certificate")||t==="diploma")out.push(text(`${prefix}-recipient`,`ALEX MORGAN`,W*.2,H*.62,W*.6,H*.08,Math.max(27,H*.05),paper,"700",{textAlign:"center",fontFamily:fonts[0]}),rect(`${prefix}-sig-a`,W*.18,H*.81,W*.24,1,accent),rect(`${prefix}-sig-b`,W*.58,H*.81,W*.24,1,accent));if(t.includes("menu")||t.includes("wine list")){for(let i=0;i<5;i++)out.push(text(`${prefix}-menu-${i}`,`SEASONAL SELECTION ${i+1}  •  $${18+i*4}`,W*.12,H*(.52+i*.06),W*.76,H*.04,Math.max(11,H*.018),paper,"600",{fontFamily:fonts[1]}));}if(t.includes("calendar")||t.includes("schedule")){for(let r=0;r<4;r++)for(let c=0;c<7;c++)out.push(rect(`${prefix}-cell-${r}-${c}`,W*(.12+c*.108),H*(.54+r*.075),W*.095,H*.06,paper,{borderColor:muted,borderWidth:.5,opacity:.9}));}return out;}
function build(spec:Spec,n:number):ProfessionalTemplate{const type=spec.types[n];const d=dimensions(type);const p=PALETTES[(n+spec.slug.length)%PALETTES.length];const fonts=FONTS[(n*3+spec.slug.length)%FONTS.length];const photo=PHOTOS[(n*5+spec.slug.length)%PHOTOS.length];const id=`phase4378-industry-${spec.slug}-${String(n+1).padStart(2,"0")}`;const pagesCount=type.toLowerCase().includes("kit")||type.toLowerCase().includes("catalog")||type.toLowerCase().includes("brochure")?2:1;const pages:PublisherPage[]=Array.from({length:pagesCount},(_,page)=>{const pid=`${id}-p${page+1}`;return{id:pid,name:pagesCount===1?type:`${type} ${page+1}`,width:d.width,height:d.height,orientation:d.orientation,sizeKey:d.pageSize.toLowerCase().replace(/[^a-z0-9]+/g,"-"),backgroundColor:p[0],margin:Math.max(18,Math.round(Math.min(d.width,d.height)*.04)),bleed:DEFAULT_BLEED,elements:[...layout(pid,d.width,d.height,n+300+SPECS.indexOf(spec)*30,p,fonts,photo,type,page===0?spec.industry:`${spec.industry} • Page ${page+1}`),...detailElements(pid,d.width,d.height,type,p,fonts)]};});return{metadata:{id,name:`${SERIES[n]} ${spec.industry} ${type} Collection II`,category:spec.category,subcategory:type,industry:spec.industry,description:`A unique Phase 24.3D ${type.toLowerCase()} template with editable geometric composition, professional type, curated color, and no-people imagery.`,tags:[spec.slug,type.toLowerCase(),"phase 24.3D","industry collection II","fully editable","live preview","no people","print ready"],pageSize:d.pageSize,orientation:d.orientation,previewColor:p[1],palette:[...p],fonts:[...fonts],author:"Yaposan Design Studio",version:"43.7.8",editable:true,featured:n%6===0,trending:n%7===0,access:n%4===0?"premium":"free",createdAt:NOW,updatedAt:NOW,style:(n%7===0?"corporate":n%7===1?"luxury":n%7===2?"minimal":n%7===3?"creative":n%7===4?"editorial":n%7===5?"bold":"elegant"),qualityScore:100,masterTemplateId:id},pages};}
export const PHASE4378_INDUSTRY_TEMPLATES:ProfessionalTemplate[]=SPECS.flatMap(spec=>spec.types.map((_,n)=>build(spec,n)));
export const PHASE4378_INDUSTRY_TEMPLATE_COUNT=PHASE4378_INDUSTRY_TEMPLATES.length;
export const PHASE4378_CATEGORY_COUNTS=Object.fromEntries(SPECS.map(spec=>[spec.category,PHASE4378_INDUSTRY_TEMPLATES.filter(t=>t.metadata.category===spec.category).length]));
