export type Phase42Template={id:string;name:string;category:string;format:string;style:string;industry:string;palette:string[];premium:boolean;editable:boolean;qualityScore:number;tags:string[]};
const categories=["Social Media","Business","Marketing","Education","Events","Real Estate","Restaurant","Retail","Nonprofit","Presentation","Video","Print"];
const formats=["Instagram Post","Presentation","Flyer","Poster","Business Card","Brochure","Menu","Resume","YouTube Thumbnail","Story","Invitation","Newsletter"];
const styles=["Editorial","Minimal","Luxury","Bold","Modern","Corporate","Playful","Elegant","Geometric","Organic"];
const industries=["Technology","Healthcare","Education","Hospitality","Fashion","Finance","Construction","Food","Creative","Community"];
const palettes=[["#111827","#f8fafc","#f97316"],["#0f172a","#e2e8f0","#38bdf8"],["#3f1d2e","#fff7ed","#eab308"],["#052e2b","#ecfdf5","#14b8a6"],["#312e81","#f5f3ff","#a78bfa"]];
export const PHASE42_PROFESSIONAL_TEMPLATES:Phase42Template[]=Array.from({length:240},(_,i)=>{const category=categories[i%categories.length];const format=formats[(i*5)%formats.length];const style=styles[(i*3)%styles.length];const industry=industries[(i*7)%industries.length];return{id:`p42-${String(i+1).padStart(3,"0")}`,name:`${style} ${industry} ${format} ${i+1}`,category,format,style,industry,palette:palettes[i%palettes.length],premium:i%3===0,editable:true,qualityScore:92+(i%9),tags:[category.toLowerCase(),style.toLowerCase(),industry.toLowerCase(),format.toLowerCase()]}});
export function searchPhase42Templates(query:string,category?:string){const q=query.trim().toLowerCase();return PHASE42_PROFESSIONAL_TEMPLATES.filter(t=>(!category||category==="All"||t.category===category)&&(!q||[t.name,t.category,t.format,t.style,t.industry,...t.tags].join(" ").toLowerCase().includes(q)))}
export function phase42TemplateAudit(){const unique=new Set(PHASE42_PROFESSIONAL_TEMPLATES.map(t=>t.name));return{count:PHASE42_PROFESSIONAL_TEMPLATES.length,uniqueNames:unique.size,editable:PHASE42_PROFESSIONAL_TEMPLATES.every(t=>t.editable),minimumQuality:Math.min(...PHASE42_PROFESSIONAL_TEMPLATES.map(t=>t.qualityScore)),categories:new Set(PHASE42_PROFESSIONAL_TEMPLATES.map(t=>t.category)).size}}
