import { DEFAULT_BLEED } from "../constants/publisher";
import type { PublisherElement, PublisherPage } from "../types/publisher";
import type { ProfessionalTemplate, ProfessionalTemplateCategory, TemplateOrientation } from "./types";

const NOW = "2026-07-30T00:00:00.000Z";
const photo = {
  office: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=90",
  technology: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=90",
  city: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1600&q=90",
  shop: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=90",
  fashion: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1600&q=90",
  market: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1600&q=90",
  coffee: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=90",
  food: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1600&q=90",
  pizza: "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1600&q=90",
  clinic: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1600&q=90",
  wellness: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1600&q=90",
  school: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1600&q=90",
  kids: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1600&q=90",
  laptop: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1600&q=90",
  graduation: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1600&q=90",
  cyber: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1600&q=90",
  code: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1600&q=90",
  house: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=90",
  apartment: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=90",
  building: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=90",
  sports: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1600&q=90",
  fitness: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1600&q=90",
  soccer: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1600&q=90",
  running: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1600&q=90",
  church: "https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&w=1600&q=90",
  concert: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1600&q=90",
  community: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1600&q=90",
  podcast: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1600&q=90",
  microphone: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=1600&q=90",
  gaming: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=90",
  streaming: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1600&q=90",
  documentary: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1600&q=90",
  gadget: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1600&q=90",
  baby: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1600&q=90",
  celebration: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1600&q=90",
  holiday: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=1600&q=90",
  gala: "https://images.unsplash.com/photo-1507501336603-6e31db2be093?auto=format&fit=crop&w=1600&q=90",
  art: "https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1600&q=90",
  travel: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=90",
  mountain: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=90",
} as const;

const el=(id:string,name:string,type:PublisherElement["type"],x:number,y:number,width:number,height:number,zIndex:number,extra:Partial<PublisherElement>={}):PublisherElement=>({id,name,type,x,y,width,height,rotation:0,zIndex,opacity:1,locked:false,hidden:false,...extra});
const text=(id:string,value:string,x:number,y:number,width:number,height:number,size:number,color:string,weight:PublisherElement["fontWeight"]="700",extra:Partial<PublisherElement>={})=>el(id,value.slice(0,24),"text",x,y,width,height,30,{text:value,fontSize:size,textColor:color,fontWeight:weight,lineHeight:size*1.12,fontFamily:"Inter",...extra});
const rect=(id:string,x:number,y:number,width:number,height:number,fillColor:string,extra:Partial<PublisherElement>={})=>el(id,id,"rectangle",x,y,width,height,10,{fillColor,borderWidth:0,...extra});
const circle=(id:string,x:number,y:number,width:number,height:number,fillColor:string,extra:Partial<PublisherElement>={})=>el(id,id,"ellipse",x,y,width,height,12,{fillColor,borderWidth:0,...extra});
const image=(id:string,uri:string,x:number,y:number,width:number,height:number,extra:Partial<PublisherElement>={})=>el(id,id,"image",x,y,width,height,8,{imageUri:uri,imageFit:"cover",...extra});
const page=(id:string,name:string,width:number,height:number,orientation:"portrait"|"landscape",backgroundColor:string,elements:PublisherElement[]):PublisherPage=>({id,name,width,height,orientation,sizeKey:"custom",backgroundColor,margin:32,bleed:DEFAULT_BLEED,elements});

function compose(prefix:string,title:string,subtitle:string,dark:string,accent:string,uri:string,variant:number):PublisherPage {
 const W=1080,H=1350;
 const common=[image(`${prefix}-photo`,uri,0,0,W,H),rect(`${prefix}-shade`,0,0,W,H,"rgba(5,10,20,0.38)"),text(`${prefix}-brand`,"YAPOSAN CREATIVE STUDIO",64,58,520,30,14,"#ffffff","900",{letterSpacing:2.4})];
 const layouts:PublisherElement[][]=[
  [...common,rect(`${prefix}-panel`,-80,600,1240,560,dark,{rotation:-5,opacity:.96}),rect(`${prefix}-accent`,60,560,350,12,accent),text(`${prefix}-title`,title.toUpperCase(),60,650,880,190,72,"#ffffff","900",{fontFamily:"League Spartan",lineHeight:74}),text(`${prefix}-sub`,subtitle,65,865,700,90,22,"#e5e7eb","700",{lineHeight:31}),rect(`${prefix}-cta`,65,1030,320,66,accent,{borderRadius:8}),text(`${prefix}-cta-t`,"DISCOVER MORE",88,1049,274,28,16,dark,"900",{textAlign:"center",letterSpacing:1.8}),text(`${prefix}-foot`,"YAPOSAN.COM  •  410 555 0188",65,1180,600,30,14,"#ffffff","800",{letterSpacing:1.5})],
  [...common,rect(`${prefix}-left`,0,0,500,H,dark,{opacity:.97}),rect(`${prefix}-line`,455,0,36,H,accent),text(`${prefix}-kick`,"FEATURED EDITION",58,170,360,30,15,accent,"900",{letterSpacing:2.5}),text(`${prefix}-title`,title.toUpperCase(),55,240,430,260,68,"#ffffff","900",{fontFamily:"League Spartan",lineHeight:69}),text(`${prefix}-sub`,subtitle,58,540,365,105,21,"#d1d5db","700",{lineHeight:30}),rect(`${prefix}-box`,58,745,310,150,"rgba(255,255,255,.08)",{borderColor:accent,borderWidth:2}),text(`${prefix}-date`,"SEPTEMBER 2027",82,780,265,32,18,"#ffffff","900",{letterSpacing:1.4}),text(`${prefix}-place`,"BALTIMORE • MARYLAND",82,830,265,28,14,accent,"800",{letterSpacing:1.3}),text(`${prefix}-url`,"YAPOSAN.COM",58,1215,360,28,15,"#ffffff","900",{letterSpacing:2})],
  [...common,rect(`${prefix}-top`,0,0,W,500,dark,{opacity:.94}),rect(`${prefix}-band`,0,470,W,30,accent),text(`${prefix}-kick`,"A PROFESSIONAL PRESENTATION",70,95,760,30,15,accent,"900",{letterSpacing:2.8}),text(`${prefix}-title`,title.toUpperCase(),65,155,900,180,70,"#ffffff","900",{fontFamily:"League Spartan",lineHeight:70}),text(`${prefix}-sub`,subtitle,70,355,760,70,21,"#e5e7eb","700",{lineHeight:30}),rect(`${prefix}-card`,610,925,390,250,"rgba(255,255,255,.94)",{borderRadius:10}),text(`${prefix}-card1`,"SAVE THE DATE",650,970,310,30,16,dark,"900",{letterSpacing:2}),text(`${prefix}-card2`,"18 OCTOBER",650,1025,310,48,34,accent,"900",{fontFamily:"League Spartan"}),text(`${prefix}-card3`,"Details at yaposan.com",650,1100,310,28,15,"#475569","700")],
  [...common,rect(`${prefix}-diag`,-130,115,760,1240,dark,{rotation:-12,opacity:.97}),rect(`${prefix}-diag2`,520,-40,55,1450,accent,{rotation:-12}),text(`${prefix}-kick`,"PREMIUM SERIES",62,160,390,30,15,accent,"900",{letterSpacing:2.7}),text(`${prefix}-title`,title.toUpperCase(),55,250,500,270,70,"#ffffff","900",{fontFamily:"League Spartan",lineHeight:70}),text(`${prefix}-sub`,subtitle,62,560,390,105,21,"#d1d5db","700",{lineHeight:30}),circle(`${prefix}-badge`,770,860,220,220,accent),text(`${prefix}-badge1`,"2027",805,910,150,54,40,dark,"900",{textAlign:"center",fontFamily:"League Spartan"}),text(`${prefix}-badge2`,"SPECIAL EDITION",800,982,160,28,13,dark,"900",{textAlign:"center",letterSpacing:1.2}),text(`${prefix}-url`,"YAPOSAN.COM",58,1200,390,30,16,"#ffffff","900",{letterSpacing:2})],
  [...common,rect(`${prefix}-base`,58,625,964,600,"rgba(255,255,255,.94)",{borderRadius:8}),rect(`${prefix}-topline`,58,625,964,16,accent),text(`${prefix}-kick`,"CURATED FOR YOU",100,700,420,30,15,accent,"900",{letterSpacing:2.7}),text(`${prefix}-title`,title.toUpperCase(),95,755,840,170,66,dark,"900",{fontFamily:"League Spartan",lineHeight:67}),text(`${prefix}-sub`,subtitle,100,950,720,70,21,"#475569","700",{lineHeight:30}),rect(`${prefix}-rule`,100,1055,500,3,dark),text(`${prefix}-info`,"SEPTEMBER 18 • 7 PM • BALTIMORE",100,1090,720,30,16,dark,"900",{letterSpacing:1.5}),text(`${prefix}-url`,"YAPOSAN.COM",100,1150,520,28,15,accent,"900",{letterSpacing:2})]
 ];
 return page(`${prefix}-page`,title,W,H,"portrait",dark,layouts[variant%layouts.length]);
}

function make(config:{id:string;name:string;category:ProfessionalTemplateCategory;subcategory:string;industry:string;style:NonNullable<ProfessionalTemplate["metadata"]["style"]>;dark:string;accent:string;title:string;subtitle:string;photo:keyof typeof photo;variant:number;}):ProfessionalTemplate {
 return {metadata:{id:config.id,name:config.name,category:config.category,subcategory:config.subcategory,industry:config.industry,description:`A professional ${config.subcategory.toLowerCase()} template using strong photography, bold geometry, controlled typography, and fully editable Publisher objects.`,tags:[config.category.toLowerCase(),config.subcategory.toLowerCase(),config.industry.toLowerCase(),"editable","professional","method"],pageSize:"1080 x 1350",orientation:"portrait" as TemplateOrientation,previewColor:config.accent,palette:[config.dark,config.accent,"#ffffff","#e5e7eb"],fonts:["League Spartan","Inter"],author:"Yaposan Design Studio",version:"43.4.8",editable:true,featured:true,trending:true,access:"premium",createdAt:NOW,updatedAt:NOW,style:config.style,masterTemplateId:config.id,qualityScore:100},pages:[compose(config.id,config.title,config.subtitle,config.dark,config.accent,photo[config.photo],config.variant)]};
}

const specs = [
  { id: "p4348-nonprofit-impact-report", name: "Nonprofit Impact Report", category: "Business" as ProfessionalTemplateCategory, subcategory: "Impact Reports", industry: "Nonprofit", style: "editorial" as const, dark: "#153243", accent: "#f4b942", title: "IMPACT IN ACTION", subtitle: "A year of service, growth, and measurable change", photo: "community" as keyof typeof photo, variant: 0 },
  { id: "p4348-law-firm-practice-guide", name: "Law Firm Practice Guide", category: "Business" as ProfessionalTemplateCategory, subcategory: "Practice Guides", industry: "Legal", style: "corporate" as const, dark: "#172033", accent: "#c6a15b", title: "TRUSTED COUNSEL", subtitle: "Clear guidance for complex decisions", photo: "office" as keyof typeof photo, variant: 1 },
  { id: "p4348-architecture-studio-profile", name: "Architecture Studio Profile", category: "Business" as ProfessionalTemplateCategory, subcategory: "Company Profiles", industry: "Architecture", style: "minimal" as const, dark: "#e8e3da", accent: "#111827", title: "DESIGN WITH PURPOSE", subtitle: "Spaces shaped by clarity and craft", photo: "building" as keyof typeof photo, variant: 2 },
  { id: "p4348-small-business-service-menu", name: "Small Business Service Menu", category: "Business" as ProfessionalTemplateCategory, subcategory: "Service Menus", industry: "Professional Services", style: "bold" as const, dark: "#102a43", accent: "#2dd4bf", title: "SERVICES THAT MOVE YOU", subtitle: "Flexible support built around your goals", photo: "office" as keyof typeof photo, variant: 3 },
  { id: "p4348-annual-meeting-agenda", name: "Annual Meeting Agenda", category: "Business" as ProfessionalTemplateCategory, subcategory: "Meeting Agendas", industry: "Corporate", style: "corporate" as const, dark: "#1e293b", accent: "#60a5fa", title: "ANNUAL MEETING", subtitle: "Strategy, performance, and priorities", photo: "city" as keyof typeof photo, variant: 4 },
  { id: "p4348-spring-clearance-sale", name: "Spring Clearance Sale", category: "Retail" as ProfessionalTemplateCategory, subcategory: "Sale Flyers", industry: "Retail", style: "bold" as const, dark: "#7f1d1d", accent: "#fde047", title: "SPRING CLEARANCE", subtitle: "Fresh deals across the entire store", photo: "shop" as keyof typeof photo, variant: 0 },
  { id: "p4348-artisan-market-flyer", name: "Artisan Market Flyer", category: "Retail" as ProfessionalTemplateCategory, subcategory: "Market Flyers", industry: "Local Retail", style: "creative" as const, dark: "#264653", accent: "#e9c46a", title: "MADE LOCAL", subtitle: "Craft, flavor, and community in one place", photo: "market" as keyof typeof photo, variant: 1 },
  { id: "p4348-new-store-opening-post", name: "New Store Opening Post", category: "Retail" as ProfessionalTemplateCategory, subcategory: "Grand Opening Posts", industry: "Retail", style: "bold" as const, dark: "#111827", accent: "#fb7185", title: "HELLO, NEIGHBOR", subtitle: "Our newest location is now open", photo: "shop" as keyof typeof photo, variant: 2 },
  { id: "p4348-luxury-accessories-campaign", name: "Luxury Accessories Campaign", category: "Fashion" as ProfessionalTemplateCategory, subcategory: "Campaign Posters", industry: "Fashion", style: "luxury" as const, dark: "#261a1f", accent: "#d4af7a", title: "THE FINISHING TOUCH", subtitle: "Refined details for modern style", photo: "fashion" as keyof typeof photo, variant: 3 },
  { id: "p4348-seasonal-style-guide", name: "Seasonal Style Guide", category: "Fashion" as ProfessionalTemplateCategory, subcategory: "Style Guides", industry: "Fashion", style: "editorial" as const, dark: "#f1ece4", accent: "#8b1e3f", title: "STYLE THE SEASON", subtitle: "A curated edit for effortless dressing", photo: "fashion" as keyof typeof photo, variant: 4 },
  { id: "p4348-farm-to-table-menu", name: "Farm to Table Menu", category: "Restaurant" as ProfessionalTemplateCategory, subcategory: "Menus", industry: "Hospitality", style: "elegant" as const, dark: "#1f3d2b", accent: "#e3b23c", title: "FROM FARM TO TABLE", subtitle: "Seasonal plates made with intention", photo: "food" as keyof typeof photo, variant: 0 },
  { id: "p4348-bakery-grand-opening", name: "Bakery Grand Opening", category: "Restaurant" as ProfessionalTemplateCategory, subcategory: "Grand Opening Flyers", industry: "Food & Beverage", style: "creative" as const, dark: "#5b2c2c", accent: "#f6c1a5", title: "FRESH FROM THE OVEN", subtitle: "Celebrate our opening weekend", photo: "coffee" as keyof typeof photo, variant: 1 },
  { id: "p4348-happy-hour-promotion", name: "Happy Hour Promotion", category: "Restaurant" as ProfessionalTemplateCategory, subcategory: "Promotional Flyers", industry: "Hospitality", style: "bold" as const, dark: "#2d1b46", accent: "#f59e0b", title: "HAPPY HOUR", subtitle: "Good drinks. Better company.", photo: "food" as keyof typeof photo, variant: 2 },
  { id: "p4348-food-truck-festival", name: "Food Truck Festival", category: "Restaurant" as ProfessionalTemplateCategory, subcategory: "Event Posters", industry: "Food & Beverage", style: "creative" as const, dark: "#0f4c5c", accent: "#ffb703", title: "STREET FOOD FEST", subtitle: "Big flavor rolls into town", photo: "pizza" as keyof typeof photo, variant: 3 },
  { id: "p4348-family-health-checkup", name: "Family Health Checkup", category: "Healthcare" as ProfessionalTemplateCategory, subcategory: "Clinic Flyers", industry: "Healthcare", style: "minimal" as const, dark: "#eaf6f6", accent: "#0f766e", title: "CARE FOR EVERY AGE", subtitle: "Simple preventive care for the whole family", photo: "clinic" as keyof typeof photo, variant: 4 },
  { id: "p4348-physical-therapy-open-house", name: "Physical Therapy Open House", category: "Healthcare" as ProfessionalTemplateCategory, subcategory: "Open House Flyers", industry: "Healthcare", style: "editorial" as const, dark: "#16324f", accent: "#5bc0be", title: "MOVE BETTER", subtitle: "Tour our clinic and meet the care team", photo: "wellness" as keyof typeof photo, variant: 0 },
  { id: "p4348-nutrition-workshop-poster", name: "Nutrition Workshop Poster", category: "Healthcare" as ProfessionalTemplateCategory, subcategory: "Workshop Posters", industry: "Wellness", style: "creative" as const, dark: "#2f5233", accent: "#f2c14e", title: "NOURISH YOUR DAY", subtitle: "Practical habits for lasting wellbeing", photo: "wellness" as keyof typeof photo, variant: 1 },
  { id: "p4348-community-blood-drive", name: "Community Blood Drive", category: "Healthcare" as ProfessionalTemplateCategory, subcategory: "Community Flyers", industry: "Public Health", style: "bold" as const, dark: "#7f1d1d", accent: "#ffffff", title: "GIVE BLOOD", subtitle: "One hour can change a life", photo: "clinic" as keyof typeof photo, variant: 2 },
  { id: "p4348-college-open-house", name: "College Open House", category: "Education" as ProfessionalTemplateCategory, subcategory: "Open House Flyers", industry: "Higher Education", style: "corporate" as const, dark: "#172554", accent: "#fbbf24", title: "EXPLORE YOUR FUTURE", subtitle: "Tour campus and meet your community", photo: "school" as keyof typeof photo, variant: 3 },
  { id: "p4348-stem-camp-registration", name: "STEM Camp Registration", category: "Education" as ProfessionalTemplateCategory, subcategory: "Camp Flyers", industry: "Education", style: "creative" as const, dark: "#0f3d56", accent: "#34d399", title: "BUILD • TEST • DISCOVER", subtitle: "Hands-on learning for curious minds", photo: "kids" as keyof typeof photo, variant: 4 },
  { id: "p4348-teacher-training-workshop", name: "Teacher Training Workshop", category: "Education" as ProfessionalTemplateCategory, subcategory: "Workshop Flyers", industry: "Education", style: "editorial" as const, dark: "#3f3cbb", accent: "#f8fafc", title: "TEACH WITH IMPACT", subtitle: "Fresh strategies for today’s classroom", photo: "school" as keyof typeof photo, variant: 0 },
  { id: "p4348-scholarship-announcement", name: "Scholarship Announcement", category: "Education" as ProfessionalTemplateCategory, subcategory: "Announcement Flyers", industry: "Education", style: "elegant" as const, dark: "#182235", accent: "#d4af37", title: "INVEST IN YOUR FUTURE", subtitle: "Applications now open", photo: "graduation" as keyof typeof photo, variant: 1 },
  { id: "p4348-cloud-platform-launch", name: "Cloud Platform Launch", category: "Technology" as ProfessionalTemplateCategory, subcategory: "Product Launch Posters", industry: "Software", style: "bold" as const, dark: "#07111f", accent: "#38bdf8", title: "BUILD WITHOUT LIMITS", subtitle: "A faster cloud for ambitious teams", photo: "technology" as keyof typeof photo, variant: 2 },
  { id: "p4348-data-analytics-webinar", name: "Data Analytics Webinar", category: "Technology" as ProfessionalTemplateCategory, subcategory: "Webinar Flyers", industry: "Technology", style: "corporate" as const, dark: "#10243e", accent: "#2dd4bf", title: "TURN DATA INTO DIRECTION", subtitle: "A live session for smarter decisions", photo: "laptop" as keyof typeof photo, variant: 3 },
  { id: "p4348-mobile-app-release", name: "Mobile App Release", category: "Technology" as ProfessionalTemplateCategory, subcategory: "App Launch Posts", industry: "Software", style: "creative" as const, dark: "#1b1638", accent: "#a78bfa", title: "YOUR WORK, ANYWHERE", subtitle: "The new mobile experience is here", photo: "gadget" as keyof typeof photo, variant: 4 },
  { id: "p4348-developer-hackathon-poster", name: "Developer Hackathon Poster", category: "Technology" as ProfessionalTemplateCategory, subcategory: "Hackathon Posters", industry: "Technology", style: "bold" as const, dark: "#0b0f19", accent: "#f43f5e", title: "BUILD ALL NIGHT", subtitle: "Ideas become products by sunrise", photo: "code" as keyof typeof photo, variant: 0 },
  { id: "p4348-modern-townhome-listing", name: "Modern Townhome Listing", category: "Real Estate" as ProfessionalTemplateCategory, subcategory: "Property Flyers", industry: "Real Estate", style: "luxury" as const, dark: "#1f2937", accent: "#d2b48c", title: "MODERN TOWNHOME", subtitle: "Space, light, and thoughtful design", photo: "house" as keyof typeof photo, variant: 1 },
  { id: "p4348-commercial-leasing-flyer", name: "Commercial Leasing Flyer", category: "Real Estate" as ProfessionalTemplateCategory, subcategory: "Leasing Flyers", industry: "Commercial Real Estate", style: "corporate" as const, dark: "#0d2a3b", accent: "#22c55e", title: "SPACE TO GROW", subtitle: "Flexible commercial suites available", photo: "building" as keyof typeof photo, variant: 2 },
  { id: "p4348-new-development-brochure", name: "New Development Brochure", category: "Real Estate" as ProfessionalTemplateCategory, subcategory: "Brochure Covers", industry: "Real Estate", style: "editorial" as const, dark: "#ece7df", accent: "#9a3412", title: "A NEW WAY TO LIVE", subtitle: "Contemporary homes in a connected community", photo: "apartment" as keyof typeof photo, variant: 3 },
  { id: "p4348-just-sold-social-post", name: "Just Sold Social Post", category: "Real Estate" as ProfessionalTemplateCategory, subcategory: "Social Media Posts", industry: "Real Estate", style: "minimal" as const, dark: "#f8fafc", accent: "#0f766e", title: "JUST SOLD", subtitle: "Another successful move completed", photo: "house" as keyof typeof photo, variant: 4 },
  { id: "p4348-basketball-tournament-poster", name: "Basketball Tournament Poster", category: "Sports" as ProfessionalTemplateCategory, subcategory: "Tournament Posters", industry: "Sports", style: "bold" as const, dark: "#111827", accent: "#f97316", title: "HOOPS SHOWDOWN", subtitle: "Three days. One champion.", photo: "sports" as keyof typeof photo, variant: 0 },
  { id: "p4348-yoga-studio-promotion", name: "Yoga Studio Promotion", category: "Sports" as ProfessionalTemplateCategory, subcategory: "Fitness Flyers", industry: "Wellness", style: "elegant" as const, dark: "#334155", accent: "#c4b5fd", title: "FIND YOUR FLOW", subtitle: "Movement, breath, and balance", photo: "fitness" as keyof typeof photo, variant: 1 },
  { id: "p4348-summer-soccer-camp", name: "Summer Soccer Camp", category: "Sports" as ProfessionalTemplateCategory, subcategory: "Camp Flyers", industry: "Youth Sports", style: "creative" as const, dark: "#064e3b", accent: "#facc15", title: "PLAY ALL SUMMER", subtitle: "Skills, teamwork, and fun", photo: "soccer" as keyof typeof photo, variant: 2 },
  { id: "p4348-charity-5k-poster", name: "Charity 5K Poster", category: "Sports" as ProfessionalTemplateCategory, subcategory: "Race Posters", industry: "Nonprofit", style: "bold" as const, dark: "#0f172a", accent: "#22c55e", title: "RUN FOR GOOD", subtitle: "Every mile supports a stronger community", photo: "running" as keyof typeof photo, variant: 3 },
  { id: "p4348-easter-service-invitation", name: "Easter Service Invitation", category: "Church" as ProfessionalTemplateCategory, subcategory: "Church Invitations", industry: "Faith", style: "elegant" as const, dark: "#f3eee7", accent: "#8b6f47", title: "HOPE IS ALIVE", subtitle: "Celebrate Easter with us", photo: "church" as keyof typeof photo, variant: 4 },
  { id: "p4348-community-prayer-night", name: "Community Prayer Night", category: "Church" as ProfessionalTemplateCategory, subcategory: "Church Flyers", industry: "Faith", style: "editorial" as const, dark: "#1e293b", accent: "#e2b857", title: "PRAYER NIGHT", subtitle: "An evening of reflection and unity", photo: "church" as keyof typeof photo, variant: 0 },
  { id: "p4348-volunteer-recruitment-flyer", name: "Volunteer Recruitment Flyer", category: "Church" as ProfessionalTemplateCategory, subcategory: "Volunteer Flyers", industry: "Nonprofit", style: "bold" as const, dark: "#174a3b", accent: "#f59e0b", title: "SERVE WITH US", subtitle: "Bring your time, talent, and heart", photo: "community" as keyof typeof photo, variant: 1 },
  { id: "p4348-leadership-podcast-cover", name: "Leadership Podcast Cover", category: "Podcast" as ProfessionalTemplateCategory, subcategory: "Podcast Covers", industry: "Business Media", style: "corporate" as const, dark: "#10243e", accent: "#38bdf8", title: "LEAD FORWARD", subtitle: "Conversations that sharpen your leadership", photo: "podcast" as keyof typeof photo, variant: 2 },
  { id: "p4348-true-story-episode-cover", name: "True Story Episode Cover", category: "Podcast" as ProfessionalTemplateCategory, subcategory: "Episode Covers", industry: "Media", style: "editorial" as const, dark: "#221c2f", accent: "#f472b6", title: "THE STORY BEHIND IT", subtitle: "A new episode is now available", photo: "microphone" as keyof typeof photo, variant: 3 },
  { id: "p4348-weekly-stream-calendar", name: "Weekly Stream Calendar", category: "Streaming" as ProfessionalTemplateCategory, subcategory: "Stream Schedules", industry: "Creator", style: "bold" as const, dark: "#130c2d", accent: "#8b5cf6", title: "STREAM WEEK", subtitle: "Live sessions, games, and community", photo: "gaming" as keyof typeof photo, variant: 4 },
  { id: "p4348-music-livestream-poster", name: "Music Livestream Poster", category: "Streaming" as ProfessionalTemplateCategory, subcategory: "Livestream Posters", industry: "Music", style: "creative" as const, dark: "#1a1026", accent: "#ec4899", title: "LIVE SESSIONS", subtitle: "A one-night digital performance", photo: "concert" as keyof typeof photo, variant: 0 },
  { id: "p4348-business-tips-thumbnail", name: "Business Tips Thumbnail", category: "YouTube" as ProfessionalTemplateCategory, subcategory: "Video Thumbnails", industry: "Business Media", style: "bold" as const, dark: "#0f172a", accent: "#f59e0b", title: "5 MOVES THAT WORK", subtitle: "Simple strategies for faster growth", photo: "office" as keyof typeof photo, variant: 1 },
  { id: "p4348-travel-guide-thumbnail", name: "Travel Guide Thumbnail", category: "YouTube" as ProfessionalTemplateCategory, subcategory: "Video Thumbnails", industry: "Travel Media", style: "editorial" as const, dark: "#0f4c5c", accent: "#f4a261", title: "48 HOURS HERE", subtitle: "The perfect weekend itinerary", photo: "travel" as keyof typeof photo, variant: 2 },
  { id: "p4348-wedding-anniversary-invitation", name: "Wedding Anniversary Invitation", category: "Personal" as ProfessionalTemplateCategory, subcategory: "Anniversary Invitations", industry: "Personal Events", style: "elegant" as const, dark: "#3a2630", accent: "#d8b4a0", title: "STILL CHOOSING YOU", subtitle: "Celebrate a beautiful milestone", photo: "celebration" as keyof typeof photo, variant: 3 },
  { id: "p4348-housewarming-invitation", name: "Housewarming Invitation", category: "Personal" as ProfessionalTemplateCategory, subcategory: "Housewarming Invitations", industry: "Personal Events", style: "minimal" as const, dark: "#f1ede7", accent: "#2f6f5e", title: "WELCOME HOME", subtitle: "Join us for drinks, food, and good company", photo: "house" as keyof typeof photo, variant: 4 },
  { id: "p4348-summer-block-party", name: "Summer Block Party", category: "Events" as ProfessionalTemplateCategory, subcategory: "Community Event Flyers", industry: "Community", style: "creative" as const, dark: "#0f4c5c", accent: "#ffb703", title: "BLOCK PARTY", subtitle: "Music, food, games, and neighbors", photo: "community" as keyof typeof photo, variant: 0 },
  { id: "p4348-wine-tasting-event", name: "Wine Tasting Event", category: "Events" as ProfessionalTemplateCategory, subcategory: "Event Invitations", industry: "Hospitality", style: "luxury" as const, dark: "#2b1823", accent: "#c9a76a", title: "AN EVENING OF TASTE", subtitle: "A curated flight and chef pairing", photo: "gala" as keyof typeof photo, variant: 1 },
  { id: "p4348-museum-night-poster", name: "Museum Night Poster", category: "Events" as ProfessionalTemplateCategory, subcategory: "Exhibition Posters", industry: "Arts", style: "editorial" as const, dark: "#161616", accent: "#f5f5f5", title: "MUSEUM AFTER DARK", subtitle: "Art, music, and late-night access", photo: "art" as keyof typeof photo, variant: 2 },
  { id: "p4348-wellness-quote-social-post", name: "Wellness Quote Social Post", category: "Social Media" as ProfessionalTemplateCategory, subcategory: "Quote Posts", industry: "Lifestyle", style: "minimal" as const, dark: "#eef5f1", accent: "#4f6f61", title: "REST IS PRODUCTIVE", subtitle: "Make space for what restores you", photo: "mountain" as keyof typeof photo, variant: 3 },
  { id: "p4348-city-break-travel-post", name: "City Break Travel Post", category: "Social Media" as ProfessionalTemplateCategory, subcategory: "Travel Posts", industry: "Travel", style: "creative" as const, dark: "#102a43", accent: "#f97316", title: "WEEKEND ESCAPE", subtitle: "A short trip with a big reset", photo: "city" as keyof typeof photo, variant: 4 },
] as const;

export const PHASE4348_FIFTY_PROFESSIONAL_TEMPLATES: ProfessionalTemplate[] = specs.map(make);
export const PHASE4348_TEMPLATE_COUNT = PHASE4348_FIFTY_PROFESSIONAL_TEMPLATES.length;
export function phase4348Audit(){const ids=PHASE4348_FIFTY_PROFESSIONAL_TEMPLATES.map(t=>t.metadata.id);return{templateCount:PHASE4348_TEMPLATE_COUNT,pageCount:PHASE4348_FIFTY_PROFESSIONAL_TEMPLATES.reduce((s,t)=>s+t.pages.length,0),elementCount:PHASE4348_FIFTY_PROFESSIONAL_TEMPLATES.reduce((s,t)=>s+t.pages.reduce((p,e)=>p+e.elements.length,0),0),duplicateIds:ids.length-new Set(ids).size,allEditable:PHASE4348_FIFTY_PROFESSIONAL_TEMPLATES.every(t=>t.metadata.editable),allUseDirectPublisherObjects:PHASE4348_FIFTY_PROFESSIONAL_TEMPLATES.every(t=>t.pages.every(p=>p.elements.length>=10))};}
