import test from "node:test";
import assert from "node:assert/strict";
import type { PublisherProject } from "../src/types/publisher";
import { certifyFullFidelityWebsite, createFullFidelityWebsiteFiles, createFullFidelityWebsitePackage, normalizeFullFidelityWebRuntime } from "../src/utils/fullFidelityWebRuntimeEngine";
const project:PublisherProject={id:"p227",name:"Phase 22.7 Site",createdAt:1,updatedAt:1,activePageId:"home",autoSave:true,version:2,pages:[{id:"home",name:"Home",width:816,height:1056,orientation:"portrait",sizeKey:"letter",backgroundColor:"#fff",margin:36,bleed:0,elements:[{id:"hero",name:"Hero",type:"text",x:20,y:20,width:300,height:60,rotation:0,zIndex:1,opacity:1,text:"Welcome",fontSize:32,textColor:"#111827",accessibilityLabel:"Welcome heading"},{id:"safe-svg",name:"Safe SVG",type:"svg",x:20,y:100,width:100,height:100,rotation:0,zIndex:2,opacity:1,svgMarkup:"<svg><script>alert(1)</script><circle cx='50' cy='50' r='40'/></svg>"}]},{id:"about",name:"About Us",width:816,height:1056,orientation:"portrait",sizeKey:"letter",backgroundColor:"#fff",margin:36,bleed:0,elements:[]},{id:"about2",name:"About-Us",width:816,height:1056,orientation:"portrait",sizeKey:"letter",backgroundColor:"#fff",margin:36,bleed:0,elements:[]}]};
test("migrates 22.6 to 22.7",()=>{const p=normalizeFullFidelityWebRuntime(project);assert.equal(p.phase22Version,"22.7");assert.equal(p.fullFidelityWebRuntime?.version,"22.7");});
test("exports collision-proof routes and full runtime",()=>{const files=createFullFidelityWebsiteFiles(project);const paths=files.map(f=>f.path);assert.ok(paths.includes("about-us/index.html"));assert.ok(paths.includes("about-us-2/index.html"));assert.ok(paths.includes("service-worker.js"));assert.ok(paths.includes("netlify.toml"));assert.match(files.find(f=>f.path==="runtime.js")!.content,/checkValidity/);});
test("sanitizes unsafe SVG",()=>{const html=createFullFidelityWebsiteFiles(project).find(f=>f.path==="index.html")!.content;assert.doesNotMatch(html,/<script>/i);});
test("certifies and packages 22.7",()=>{const cert=certifyFullFidelityWebsite(project);assert.match(cert.checksum,/^cert-/);const pkg=createFullFidelityWebsitePackage(project);assert.equal(pkg.version,"22.7");assert.match(pkg.checksum,/^site-/);});
