import test from "node:test";
import assert from "node:assert/strict";
import { createBranch, createProjectVersion, evaluateReleaseReadiness, getPhase23State, promoteBranch, revokeBranchApproval, submitBranchApproval, switchBranch, withPhase23State } from "../src/utils/collaborationVersionControlEngine";
import type { PublisherProject } from "../src/types/publisher";

const project=():PublisherProject=>({id:"p1",name:"Governed Project",createdAt:1,updatedAt:1,activePageId:"page1",pages:[{id:"page1",name:"Page 1",width:800,height:600,backgroundColor:"#fff",elements:[{id:"e1",type:"text",x:10,y:10,width:200,height:40,text:"Approved content"}]}]}) as PublisherProject;
const versioned=()=>{const p=project();return withPhase23State(p,createProjectVersion(p,"Baseline","Owner"));};
const feature=()=>{let p=createBranch(versioned(),"Feature","Owner",undefined,undefined,"development");const id=getPhase23State(p).branches.find(branch=>branch.name==="Feature")!.id;p=switchBranch(p,id);p=withPhase23State(p,createProjectVersion(p,"Feature baseline","Owner"));return {p,id};};

test("migrates Phase 23.1 workspaces to Phase 23.2 governance state",()=>{const state=getPhase23State(versioned());assert.equal(state.version,"23.2");assert.equal(state.releasePolicies.length,4);assert.deepEqual(state.approvals,[]);});
test("records reviewer decisions against an exact branch hash",()=>{let {p,id}=feature();p=submitBranchApproval(p,id,"Alex","editor","approved","Editorial review passed");const approval=getPhase23State(p).approvals[0];assert.equal(approval.reviewer,"Alex");assert.equal(approval.branchHash,getPhase23State(p).branches.find(branch=>branch.id===id)!.headHash);});
test("invalidates approval readiness when branch content changes",()=>{let {p,id}=feature();p=submitBranchApproval(p,id,"Alex","editor","approved");p={...p,pages:[{...p.pages[0],elements:[{...p.pages[0].elements[0],text:"Changed after approval"}]}]};const readiness=evaluateReleaseReadiness(p,id,"review");assert.equal(readiness.ready,false);assert.match(readiness.blockers.join(" "),/approval/i);});
test("blocks release promotion until required review gates pass",()=>{const {p,id}=feature();const readiness=evaluateReleaseReadiness(p,id,"review");assert.equal(readiness.ready,false);assert.throws(()=>promoteBranch(p,id,"review","Owner"));});
test("promotes an approved immutable branch and writes audit history",()=>{let {p,id}=feature();p=submitBranchApproval(p,id,"Alex","editor","approved");p=promoteBranch(p,id,"review","Owner","Ready for review channel");const state=getPhase23State(p);assert.equal(state.branches.find(branch=>branch.id===id)!.channel,"review");assert.equal(state.promotionHistory.length,1);assert.equal(state.promotionHistory[0].toChannel,"review");});
test("changes-requested decisions block controlled promotion",()=>{let {p,id}=feature();p=submitBranchApproval(p,id,"Alex","editor","approved");p=submitBranchApproval(p,id,"Morgan","brand","changes-requested","Update logo spacing");const readiness=evaluateReleaseReadiness(p,id,"review");assert.equal(readiness.ready,false);assert.match(readiness.blockers.join(" "),/requested changes/i);});
test("revokes review decisions without changing branch content",()=>{let {p,id}=feature();p=submitBranchApproval(p,id,"Alex","editor","approved");const approvalId=getPhase23State(p).approvals[0].id;p=revokeBranchApproval(p,approvalId);assert.equal(getPhase23State(p).approvals.length,0);assert.equal(p.pages[0].elements[0].text,"Approved content");});
test("keeps governance isolated across branches",()=>{let p=createBranch(versioned(),"Campaign","Owner");const id=getPhase23State(p).branches.find(branch=>branch.name==="Campaign")!.id;p=switchBranch(p,id);p=submitBranchApproval(p,id,"Alex","editor","approved");assert.equal(getPhase23State(p).approvals.filter(item=>item.branchId===id).length,1);assert.equal(getPhase23State(p).approvals.filter(item=>item.branchId==="branch-main").length,0);});
