import test from "node:test";
import assert from "node:assert/strict";
import type { PublisherProject } from "../src/types/publisher";
import { certifyPublication, createPublicationPackageManifest, normalizePublicationCompletion, optimizePublication, repairPublicationIssues, runPublicationPreflight } from "../src/utils/publicationCompletionEngine";
const project:PublisherProject={id:"p",name:"Test",createdAt:1,updatedAt:1,activePageId:"pg",autoSave:true,version:2,pages:[{id:"pg",name:"Page 1",width:612,height:792,orientation:"portrait",sizeKey:"letter",backgroundColor:"#fff",margin:36,bleed:0,elements:[{id:"t",name:"Text",type:"text",x:-5,y:10,width:100,height:20,rotation:0,zIndex:1,opacity:1,text:"Hello",fontSize:7}]}]};
test("migrates to phase 21.4",()=>assert.equal(normalizePublicationCompletion(project).phase21Version,"21.4"));
test("audits layout and accessibility",()=>{const issues=runPublicationPreflight(project);assert.ok(issues.some(i=>i.category==="layout"));assert.ok(issues.some(i=>i.category==="accessibility"));});
test("repairs safe issues",()=>assert.equal(repairPublicationIssues(project).pages[0].elements[0].x,0));
test("creates package manifest",()=>assert.ok(createPublicationPackageManifest(project).files.includes("project.json")));
test("optimizes and certifies",()=>{const optimized=optimizePublication(project);assert.ok(optimized.publicationCompletion?.optimizedAt);assert.ok(certifyPublication(optimized).publicationCompletion?.lastCertificate);});
