import test from "node:test";
import assert from "node:assert/strict";
import {applyInkLimit2,buildColorPlan2,buildSeparations2,buildSoftProof2,contrastRatio2,convertColor2,createSpotColor2,deltaE76_2,mergeSwatches2,rgbToCmyk2,rgbToLab2,validateColorEngine2} from "../src/utils/professionalColorEngine2.ts";
const rgb=(r:number,g:number,b:number):any=>({space:"rgb",value:{r,g,b}});
const cmykProfile:any={id:"fog39",name:"FOGRA39",space:"cmyk",version:"4",intent:"relative-colorimetric",blackPointCompensation:true};
test("Phase 63 converts RGB, CMYK and Lab colors",()=>{const c=rgbToCmyk2({r:255,g:0,b:0});assert.equal(c.c,0);assert.equal(c.m,1);const lab=rgbToLab2({r:255,g:255,b:255});assert.ok(lab.l>99);const back=convertColor2({space:"cmyk",value:c},"rgb") as any;assert.equal(back.value.r,255);assert.ok(deltaE76_2(lab,lab)===0);});
test("Phase 63 supports spot colors, ink limits and separations",()=>{const spot=createSpotColor2("PANTONE 186 C",{c:0,m:1,y:.81,k:.04},.75,true);assert.equal(spot.tint,.75);const limited=applyInkLimit2({c:1,m:1,y:1,k:1},3);assert.equal(Number((limited.c+limited.m+limited.y+limited.k).toFixed(3)),3);const plates=buildSeparations2([{id:"a",color:{space:"spot",name:spot.name,tint:spot.tint,alternate:spot.alternate},overprint:true},{id:"b",color:rgb(0,0,0)}]);assert.ok(plates.some(p=>p.name==="PANTONE 186 C"));assert.ok(plates.some(p=>p.name==="Black"));});
test("Phase 63 builds soft proofs and manages global swatches",()=>{const source:any={id:"srgb",name:"sRGB",space:"rgb",version:"4",intent:"perceptual",blackPointCompensation:true};const proof=buildSoftProof2([rgb(12,250,30)],{sourceProfile:source,proofProfile:cmykProfile,paperColor:true,blackInk:true,simulateOverprint:true,gamutWarning:true});assert.equal(proof[0].paperSimulation,true);const merged=mergeSwatches2([{id:"brand",name:"Brand",color:rgb(0,0,0),global:true,locked:true}],[{id:"brand",name:"Changed",color:rgb(255,0,0),global:true},{id:"accent",name:"Accent",color:rgb(10,20,30),global:true}]);assert.equal(merged[0].name,"Brand");assert.equal(merged.length,2);});
test("Phase 63 validates contrast, profiles and color plans",()=>{assert.equal(contrastRatio2(rgb(0,0,0),rgb(255,255,255)),21);const bad:any={profiles:[cmykProfile,cmykProfile],swatches:[{id:"x",name:"",color:rgb(0,0,0),global:true},{id:"x",name:"X",color:rgb(1,1,1),global:true}],objects:[]};assert.ok(validateColorEngine2(bad).length>=3);const plan=buildColorPlan2({workingSpace:"Display P3",swatches:[],objects:[{id:"x",color:rgb(255,0,0)}]});assert.equal(plan.version,"63.0");assert.equal(plan.workingSpace,"Display P3");});
