import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';const read=p=>readFileSync(p,'utf8');
test('91.4 engine normalizes orientation and compares masks',()=>{const s=read('services/background-removal/app.py');for(const x of ['ImageOps.exif_transpose','mask_iou','model-disagreement','model_agreement_iou'])assert.match(s,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'))) });
test('91.4 engine adds mask integrity diagnostics',()=>{const s=read('services/background-removal/app.py');for(const x of ['foreground_coverage','soft_alpha_fraction','border_leak_fraction','component_count','bbox_coverage'])assert.ok(s.includes(x))});
test('quality mode evaluates both standard and detail candidates',()=>{const s=read('services/background-removal/app.py');assert.match(s,/quality_mode == "quality"[\s\S]*add_candidate\(STANDARD_MODEL,False(?:,[^)]*)?\)[\s\S]*add_candidate\(DETAIL_MODEL,True(?:,[^)]*)?\)/)});
test('manual correction no longer fabricates a 100 percent AI score',()=>{const s=read('src/app/product-photo-studio.tsx');assert.doesNotMatch(s,/score:1,reasons:\[\]/);assert.match(s,/human-approved-manual-correction/)});
test('model configuration is consistent',()=>{const env=read('.env.example');const app=read('services/background-removal/app.py');const policy=JSON.parse(read('release/phase91.0/model-policy.json'));assert.match(env,/YAPOSAN_BG_DETAIL_MODEL=birefnet-general/);assert.match(app,/DETAIL_MODEL.*birefnet-general/);assert.equal(policy.detailModel.name,'birefnet-general')});
test('parity evidence cannot be self-certified',()=>{const p=JSON.parse(read('release/phase91.4/parity-policy.json'));assert.equal(p.claimStatus,'PARITY_TARGET_NOT_EXTERNALLY_CERTIFIED');assert.ok(p.minimumBenchmarkImages>=300);assert.ok(p.maximumAcceptableRateDeficitVsComparisonTool<=0.01);assert.equal(p.maximumUnexpectedPaidApiSpendUsd,0)});
test('paid API firewall remains closed',()=>{const p=JSON.parse(read('release/phase91.0/cost-policy.json'));assert.equal(p.paidPerImageProviderEnabled,false);assert.equal(p.paidProviderMonthlyBudgetUsd,0);assert.equal(p.autoOverage,false)});
test('91.4 files exist and product UI remains organization-neutral',()=>{for(const f of ['scripts/evaluate-phase91.4-parity.mjs','scripts/verify-phase91.4.mjs','release/phase91.4/benchmark-template.csv'])assert.equal(existsSync(f),true);assert.doesNotMatch(read('src/app/product-photo-studio.tsx'),/good\s*will/i)});

test('91.4 is included in source packaging and top-level release gates',()=>{const pack=read('scripts/create-source-release.mjs');for(const f of ['release/phase91.4/parity-policy.json','release/phase91.4/benchmark-template.csv','scripts/evaluate-phase91.4-parity.mjs','scripts/verify-phase91.4.mjs','tests/phase914-quality-parity-hardening.test.mjs','PHASE91.4-PRODUCT-PHOTO-QUALITY-PARITY-HARDENING.md'])assert.match(pack,new RegExp(f.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));const pkg=JSON.parse(read('package.json'));assert.match(pkg.scripts.test,/test:phase91\.4/);assert.ok(pkg.scripts['check:phase91.4']);assert.match(pkg.scripts['verify:phase91.4'],/check:phase91\.4/)})
