import test from "node:test";
import assert from "node:assert/strict";
import type { PublisherProject } from "../src/types/publisher";
import { certifyDigitalWebsiteExport, createDigitalWebsiteExportPackage, createDigitalWebsiteFiles, normalizeDigitalWebsiteExport } from "../src/utils/digitalWebsiteExportEngine";
const project: PublisherProject={id:"web",name:"Yaposan Site",createdAt:1,updatedAt:1,activePageId:"home",autoSave:true,version:2,pages:[{id:"home",name:"Home",width:816,height:1056,orientation:"portrait",sizeKey:"letter",backgroundColor:"#fff",margin:36,bleed:0,elements:[{id:"t",name:"Heading",type:"text",x:20,y:20,width:300,height:50,rotation:0,zIndex:1,opacity:1,text:"Welcome",fontSize:32,textColor:"#111827"}]},{id:"about",name:"About Us",width:816,height:1056,orientation:"portrait",sizeKey:"letter",backgroundColor:"#fff",margin:36,bleed:0,elements:[]}]};
test("migrates Phase 22.5 into 22.6 export state",()=>{const next=normalizeDigitalWebsiteExport(project);assert.equal(next.phase22Version,"22.6");assert.equal(next.digitalWebsiteExport?.version,"22.6");});
test("generates real HTML CSS JavaScript and deployment files",()=>{const files=createDigitalWebsiteFiles(project);const paths=files.map(f=>f.path);assert.ok(paths.includes("index.html"));assert.ok(paths.includes("about-us/index.html"));assert.ok(paths.includes("styles.css"));assert.ok(paths.includes("runtime.js"));assert.ok(paths.includes("sitemap.xml"));assert.match(files.find(f=>f.path==="index.html")!.content,/Welcome/);});
test("production certification validates routes and runtime",()=>{const cert=certifyDigitalWebsiteExport(project);assert.ok(cert.checks.some(c=>c.id==="html-pages"&&c.passed));assert.match(cert.checksum,/^cert-/);});
test("export package has deterministic manifest checksum prefix",()=>{const pkg=createDigitalWebsiteExportPackage(project);assert.equal(pkg.version,"22.6");assert.match(pkg.checksum,/^web-/);assert.equal(pkg.certification.files.length,pkg.files.length);});
