import test from 'node:test';import assert from 'node:assert/strict';
import {InMemoryDatabase} from '../server/database.ts';
import {PLAN_CATALOG,resolveEntitlements,requireFeature} from '../server/billingPlatform.ts';
import {estimateCredits,moderateAiInput,runAiGateway} from '../server/aiPlatform.ts';

test('plan catalog exposes commercial tiers and limits',()=>{assert.equal(PLAN_CATALOG.creator.monthlyCents,999);assert.equal(PLAN_CATALOG.business.seats,25);assert.ok(PLAN_CATALOG.pro.features.includes('advanced-export'))});
test('inactive subscription falls back to free entitlements',()=>{const org:any={plan:'business'};const sub:any={plan:'business',status:'past_due'};const e=resolveEntitlements(org,sub);assert.equal(e.plan,'free');assert.throws(()=>requireFeature(e,'team-workspaces'))});
test('AI moderation and credit estimates are deterministic',()=>{assert.equal(moderateAiInput('write a product description').allowed,true);assert.equal(moderateAiInput('malware payload').allowed,false);assert.equal(estimateCredits('image',100,50),21)});
test('AI gateway records usage and succeeds with provider fallback',async()=>{const db=new InMemoryDatabase();await db.connect();await db.migrate();const providers=[{name:'broken',endpoint:'x',apiKey:'x'},{name:'working',endpoint:'x',apiKey:'x'}];const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;if(calls===1)return new Response('{}',{status:500});return new Response(JSON.stringify({model:'test',choices:[{message:{content:'done'}}],usage:{prompt_tokens:2,completion_tokens:1}}),{status:200,headers:{'content-type':'application/json'}})};try{const result=await runAiGateway(db,{organizationId:'o1',userId:'u1',plan:'creator',task:'write',prompt:'hello'},providers);assert.equal(result.provider,'working');assert.equal(result.output,'done');const jobs=await db.find('jobs',j=>j.kind==='ai');assert.equal(jobs[0].status,'succeeded');assert.equal(jobs[0].attempts,2)}finally{globalThis.fetch=original}});
