import test from "node:test";
import assert from "node:assert/strict";
import { InMemoryDatabase } from "../server/database.ts";
import { applyCollaborationOperation, createComment, joinCollaboration, listPresence, setApproval } from "../server/collaboration.ts";
import { buildExportManifest, buildExportPipeline, cancelExportJob, claimNextExportJob, createExportJob, ffmpegPlan, retryExportJob, updateExportJob } from "../server/productionExport.ts";

async function seed(){const db=new InMemoryDatabase();await db.connect();await db.migrate();const user=await db.insert("users",{email:"owner@example.com",passwordHash:"x",emailVerified:true,status:"active"});const org=await db.insert("organizations",{name:"Yaposan",ownerUserId:user.id,plan:"business"});const ws=await db.insert("workspaces",{organizationId:org.id,name:"Main",region:"us-east"});const project=await db.insert("projects",{workspaceId:ws.id,ownerUserId:user.id,name:"Catalog",revision:1,payload:{title:"A"}});return{db,user,ws,project}}

test("collaboration presence, operations, comments, approvals",async()=>{const{db,user,project}=await seed();const session=await joinCollaboration({userId:user.id,projectId:project.id,displayName:"Owner",color:"#f97316",selectionIds:[]});assert.equal((await listPresence(project.id)).length,1);const applied=await applyCollaborationOperation(db,{projectId:project.id,actorUserId:user.id,baseRevision:1,kind:"patch",payload:{title:"B"}});assert.equal(applied.project.revision,2);assert.equal((applied.project.payload as any).title,"B");assert.equal((await createComment({projectId:project.id,authorUserId:user.id,body:"Review this",mentions:["a","a"]})).mentions.length,1);assert.equal((await setApproval({projectId:project.id,reviewerUserId:user.id,status:"approved"})).status,"approved");assert.ok(session.sessionId)});

test("export pipelines include professional PDF and media stages",()=>{assert.ok(buildExportPipeline({projectId:"p",workspaceId:"w",userId:"u",format:"pdfx1a"}).includes("flatten-transparency"));assert.ok(buildExportPipeline({projectId:"p",workspaceId:"w",userId:"u",format:"mp4"}).includes("encode-ffmpeg"));assert.ok(ffmpegPlan({projectId:"p",workspaceId:"w",userId:"u",format:"mp4"}).includes("libx264"))});

test("persistent export jobs support claim, progress, cancel, retry",async()=>{const{db,user,ws,project}=await seed();const job=await createExportJob(db,{projectId:project.id,workspaceId:ws.id,userId:user.id,format:"pdfx4",options:{colorSpace:"cmyk",fontPolicy:"subset"}});assert.equal(job.status,"queued");const claimed=await claimNextExportJob(db);assert.equal(claimed?.status,"running");await updateExportJob(db,job.id,{progress:55});const cancelled=await cancelExportJob(db,job.id);assert.equal(cancelled.status,"cancelled");const retried=await retryExportJob(db,job.id);assert.equal(retried.status,"queued")});

test("export manifest is deterministic and production-oriented",async()=>{const{db,user,ws,project}=await seed();const job=await createExportJob(db,{projectId:project.id,workspaceId:ws.id,userId:user.id,format:"tiff",options:{dpi:300,colorSpace:"cmyk"}});const manifest=buildExportManifest(job);assert.equal(manifest.format,"tiff");assert.equal(manifest.checksum.length,64);assert.equal(manifest.artifacts[0].mediaType,"image/tiff")});
