import assert from "node:assert/strict";
import test from "node:test";
import type { PublisherElement } from "../src/types/publisher";
import { applyParagraphPreset, formatListText, normalizeParagraphTypography, PARAGRAPH_STYLE_PRESETS, splitTextColumns } from "../src/utils/paragraphTypography";
const base:PublisherElement={id:"p1",name:"Text",type:"text",x:0,y:0,width:300,height:180,rotation:0,zIndex:1,opacity:1,text:"One\nTwo\nThree"};
test("normalizes paragraph measurements",()=>{const v=normalizeParagraphTypography({...base,columnCount:99,lineHeight:9,leftIndent:-5,dropCapLines:20});assert.equal(v.columnCount,6);assert.equal(v.lineHeight,4);assert.equal(v.leftIndent,0);assert.equal(v.dropCapLines,10);});
test("formats bullets and numbering",()=>{assert.equal(formatListText("One\nTwo","bullet"),"• One\n• Two");assert.equal(formatListText("One\nTwo","number",3),"3. One\n4. Two");});
test("splits text into requested columns",()=>{const c=splitTextColumns("one two three four five six",2);assert.equal(c.length,2);assert.ok(c[0].includes("one"));assert.ok(c[1].includes("six"));});
test("applies newsletter paragraph preset",()=>{const v=applyParagraphPreset(base,"newsletter");assert.equal(v.paragraphStyleId,"newsletter");assert.equal(v.columnCount,2);assert.equal(v.textAlign,"justify");assert.equal(v.hyphenation,true);});
test("includes professional paragraph styles",()=>{for(const id of ["body","lead","quote","newsletter","compact"])assert.ok(PARAGRAPH_STYLE_PRESETS.some(p=>p.id===id));});
