import test from "node:test";
import assert from "node:assert/strict";
import { applyChangeSet, certifyPhase23, createChangeSet, createProjectVersion, diffProjects, getPhase23State, hashProject, parseChangeSet, serializeChangeSet, withPhase23State } from "../src/utils/collaborationVersionControlEngine";
import type { PublisherProject } from "../src/types/publisher";

const project=(text="Hello"):PublisherProject=>({id:"p1",name:"Project",createdAt:1,updatedAt:1,activePageId:"page1",pages:[{id:"page1",name:"Page 1",width:800,height:600,backgroundColor:"#fff",elements:[{id:"e1",type:"text",x:10,y:10,width:200,height:40,text}]}]}) as PublisherProject;

test("creates immutable versions with stable integrity hashes",()=>{ const p=project(); const state=createProjectVersion(p,"Initial","Owner","baseline"); assert.equal(state.versions.length,1); assert.equal(state.versions[0].projectHash,hashProject(state.versions[0].project)); assert.equal(state.versions[0].label,"Initial"); });
test("calculates object-level project differences",()=>{ const changes=diffProjects(project("Before"),project("After")); assert.equal(changes.length,1); assert.equal(changes[0].kind,"element-updated"); assert.equal(changes[0].elementId,"e1"); });
test("exports, parses, and applies portable change sets",()=>{ const base=project("Before"); const versioned=withPhase23State(base,createProjectVersion(base,"Base")); const current={...versioned,pages:[{...versioned.pages[0],elements:[{...versioned.pages[0].elements[0],text:"After"}]}]}; const baseId=getPhase23State(current).versions[0].id; const set=createChangeSet(current,baseId,"Owner"); const parsed=parseChangeSet(serializeChangeSet(set)); const target=withPhase23State(base,getPhase23State(current)); const merged=applyChangeSet(target,parsed,"incoming"); assert.equal(merged.project.pages[0].elements[0].text,"After"); assert.equal(merged.conflicts.length,0); });
test("detects real three-way merge conflicts",()=>{ const base=project("Base"); const state=createProjectVersion(base,"Base"); const source=withPhase23State({...base,pages:[{...base.pages[0],elements:[{...base.pages[0].elements[0],text:"Incoming"}]}]},state); const set=createChangeSet(source,state.versions[0].id); const local=withPhase23State({...base,pages:[{...base.pages[0],elements:[{...base.pages[0].elements[0],text:"Local"}]}]},state); const result=applyChangeSet(local,set,"incoming"); assert.ok(result.conflicts.some(c=>c.field==="text")); assert.equal(result.project.pages[0].elements[0].text,"Incoming"); });
test("production certification requires a valid version",()=>{ assert.equal(certifyPhase23(project()).passed,false); const p=withPhase23State(project(),createProjectVersion(project(),"Initial")); assert.equal(certifyPhase23(p).passed,true); });
