import test from "node:test";
import assert from "node:assert/strict";
import { applyLiveCorners, applyMeshGradient, applyVariableWidth, applyVectorBrush, applyVectorLiveEffect, applyVectorRepeat, applyVectorWarp, createLiveShape, createVectorSymbol, eraseVectorNodes, knifeVectorPath, vectorElementToSvg } from "../src/utils/professionalVectorEngine";
import type { PublisherElement } from "../src/types/publisher";
const base={id:"v1",name:"Vector",type:"shape",x:0,y:0,width:100,height:100,rotation:0,opacity:1,visible:true,locked:false,zIndex:1,fillColor:"#7C3AED",borderColor:"#111827",borderWidth:2,editableVector:true,shapeKind:"custom-path",vectorClosed:true,vectorNodes:[{x:0,y:0},{x:100,y:0},{x:100,y:100},{x:0,y:100}]} as unknown as PublisherElement;
test("live shapes remain editable",()=>{const star:any=createLiveShape(base as any,"star",{points:7});assert.equal(star.liveShape.kind,"star");assert.equal(star.vectorNodes.length,14);assert.equal(star.vectorClosed,true);});
test("width profiles and brushes preserve pressure",()=>{const width:any=applyVariableWidth(base as any,"taper-both");assert.ok(width.vectorNodes.some((node:any)=>node.pressure!==1));const ink:any=applyVectorBrush(base as any,"ink");assert.equal(ink.vectorBrush.preset,"ink");assert.equal(ink.shapeKind,"brush-stroke");});
test("symbols, corners, mesh, warps and effects remain saved metadata",()=>{assert.equal((createVectorSymbol(base as any) as any).vectorSymbol.isMaster,true);assert.equal((applyLiveCorners(base as any,18) as any).liveCornerRadius,18);assert.equal((applyMeshGradient(base as any) as any).vectorMeshGradient.points.length,4);assert.equal((applyVectorWarp(base as any,"wave",.3) as any).vectorWarp.mode,"wave");assert.equal((applyVectorLiveEffect(base as any,"twist",.2) as any).vectorLiveEffects.length,1);});
test("repeat knife eraser and SVG export work",()=>{assert.equal((applyVectorRepeat(base as any,"radial",8) as any).vectorRepeat.count,8);assert.equal((knifeVectorPath(base as any) as any).vectorClosed,false);assert.ok((eraseVectorNodes({...base,vectorNodes:[{x:0,y:0},{x:20,y:0},{x:40,y:0},{x:60,y:0},{x:80,y:0},{x:100,y:0}]} as any,3,0) as any).vectorNodes.length<6);assert.match(vectorElementToSvg(createLiveShape(base as any,"gear",{teeth:8})),/<path/);});
