import test from "node:test";
import assert from "node:assert/strict";
import { addRasterAdjustment2, addRasterExportPreset2, addRasterMask2, addSmartFilter2, applyContentAwareOperation, buildRasterRenderPlan2, configureFrequencySeparation2, configureHdrMerge2, configurePanorama2, createRasterSelection2, refineRasterMask2, reorderSmartFilters2, setRawPipeline2, validateRasterEngine2 } from "../src/utils/professionalRasterEngine2";

const base:any={id:"r1",name:"Photo",type:"image",x:0,y:0,width:1200,height:800,rotation:0,opacity:1,visible:true,locked:false,zIndex:1,imageUri:"file://photo.tif"};

test("Phase 60 smart filters and nondestructive adjustment stack",()=>{let e=addSmartFilter2(base,{kind:"denoise",enabled:true,opacity:1,parameters:{strength:45}});e=addSmartFilter2(e,{kind:"unsharp-mask",enabled:true,opacity:.8,parameters:{amount:120,radius:1.2}});e=reorderSmartFilters2(e,[e.rasterSmartFilters2[1].id,e.rasterSmartFilters2[0].id]);e=addRasterAdjustment2(e,{kind:"curves",enabled:true,opacity:1,blendMode:"normal",parameters:{points:[[0,0],[128,142],[255,255]]}});const plan=buildRasterRenderPlan2(e);assert.equal(plan.smartFilters[0].kind,"unsharp-mask");assert.equal(plan.adjustments.length,1);assert.equal(plan.nondestructive,true);});

test("Phase 60 masks, selections and content-aware operations",()=>{let e=addRasterMask2(base,{kind:"subject",feather:12});const id=e.rasterMasks2[0].id;e=refineRasterMask2(e,id,{smooth:20,shiftEdge:-8,decontaminateColor:true});e=createRasterSelection2(e,{kind:"lasso",feather:4,antiAlias:true,points:[{x:0,y:0},{x:100,y:0},{x:50,y:80}]});e=applyContentAwareOperation(e,{type:"remove",sourceSelectionId:e.activeRasterSelectionId,preserveTexture:.9,colorAdaptation:.8,rotationAdaptation:.5,scaleAdaptation:.5});assert.equal(e.rasterMasks2[0].refinement.shiftEdge,-8);assert.equal(e.rasterContentAwareOperations.length,1);});

test("Phase 60 RAW, HDR, panorama and frequency separation",()=>{let e=setRawPipeline2(base,{exposure:1.25,dehaze:120,noiseReduction:35});e=configureHdrMerge2(e,{sources:["a.dng","b.dng","c.dng"]});e=configurePanorama2(e,{sources:["left.jpg","center.jpg","right.jpg"],boundaryWarp:35});e=configureFrequencySeparation2(e,{radius:10,preserveEdges:true});const plan=buildRasterRenderPlan2(e);assert.equal(plan.rawPipeline.dehaze,100);assert.equal(plan.hdrMerge.sources.length,3);assert.equal(plan.panorama.sources.length,3);assert.equal(plan.frequencySeparation.enabled,true);assert.equal(plan.requiresGpu,true);});

test("Phase 60 professional export presets and validation",()=>{let e=addRasterExportPreset2(base,{format:"tiff",bitDepth:16,colorSpace:"adobe-rgb",scale:2});e=addRasterExportPreset2(e,{format:"webp",quality:82,alpha:true});assert.equal(buildRasterRenderPlan2(e).exportPresets.length,2);assert.deepEqual(validateRasterEngine2(e),[]);const invalid=configureHdrMerge2({...base,imageUri:""},{sources:["one.jpg"]});assert.equal(validateRasterEngine2(invalid).length,2);});
