import test from "node:test";
import assert from "node:assert/strict";
import type { PublisherElement, PublisherProject } from "../src/types/publisher";
import { auditProfessionalVectors, cleanVectorPath, flattenCompoundVector, releaseCompoundVector, validateVectorSvgRoundTrip, vectorElementToSvg, vectorProjectToSvgLibrary } from "../src/utils/professionalVectorEngine";

const gradient: PublisherElement={id:"gradient",name:"Gradient",type:"line",x:20,y:30,width:120,height:90,rotation:0,zIndex:1,opacity:1,borderColor:"#111827",borderWidth:4,fillColor:"transparent",shapeKind:"bezier-path",editableVector:true,vectorClosed:true,vectorNodes:[{x:5,y:5},{x:115,y:5},{x:60,y:85},{x:60,y:85}],vectorGradient:{type:"linear",angle:45,stops:[{offset:0,color:"#7C3AED"},{offset:1,color:"#06B6D4"}]},strokeDashArray:[8,4],endArrowhead:"arrow"};
const source: PublisherElement={id:"source",name:"Source",type:"line",x:0,y:0,width:40,height:40,rotation:0,zIndex:1,opacity:1,borderColor:"#000",borderWidth:2,fillColor:"#fff",shapeKind:"custom-path",editableVector:true,vectorClosed:true,vectorNodes:[{x:0,y:0},{x:40,y:0},{x:20,y:40}]};
const compound: PublisherElement={...source,id:"compound",name:"Compound",x:100,y:80,width:80,height:60,shapeKind:"compound-path",booleanOperation:"combine",compoundSources:[source,{...source,id:"source2",x:30,y:10}]};

test("Phase 16.3 cleans duplicate nodes and validates SVG round trip",()=>{const cleaned=cleanVectorPath(gradient);assert.equal(cleaned.vectorNodes?.length,3);const result=validateVectorSvgRoundTrip(cleaned);assert.equal(result.valid,true);assert.match(result.svg,/<linearGradient/);assert.match(result.svg,/marker-end/);});
test("Phase 16.3 renders and finalizes compound vectors",()=>{const svg=vectorElementToSvg(compound);assert.match(svg,/data-boolean-operation="combine"/);assert.ok((svg.match(/<path/g)||[]).length>=2);const flattened=flattenCompoundVector(compound);assert.equal(flattened.shapeKind,"custom-path");assert.equal(flattened.compoundSources,undefined);assert.ok((flattened.vectorNodes?.length??0)>=6);const released=releaseCompoundVector([compound],compound.id);assert.equal(released.released.length,2);assert.equal(released.elements.length,2);});
test("Phase 16.3 exports a complete multi-page vector SVG library",()=>{const project:PublisherProject={id:"p",name:"Final Vector",createdAt:1,updatedAt:1,activePageId:"page",autoSave:true,version:2,phase16Version:"16.3",pages:[{id:"page",name:"Page",width:500,height:400,orientation:"landscape",sizeKey:"custom",backgroundColor:"#fff",margin:20,bleed:0,elements:[gradient,compound]}]};const svg=vectorProjectToSvgLibrary(project);assert.match(svg,/Final Vector Vector Library/);assert.match(svg,/id="page"/);assert.ok((svg.match(/<path/g)||[]).length>=3);const issues=auditProfessionalVectors({...project,pages:[{...project.pages[0],elements:[cleanVectorPath(gradient),compound]}]});assert.equal(issues.filter(issue=>issue.severity==="error").length,0);});
