import test from "node:test";
import assert from "node:assert/strict";
import { applyMasterOverrides2, buildImpositionPlan2, buildLayoutPlan2, resolveCollisions2, resolveResponsiveLayout2, setAdvancedGrid2, setAnchor2, setImposition2, setLayoutConstraints2, setMasterPage2, setReflowRule2, setResponsiveBreakpoints2, validateLayoutEngine2 } from "../src/utils/professionalLayoutEngine2.ts";

const element=(id:string,x:number,y:number,width=200,height=100):any=>({id,name:id,type:"shape",x,y,width,height,rotation:0,opacity:1,visible:true,locked:false,zIndex:1});
const page:any={id:"p1",name:"Page 1",width:1000,height:800,elements:[element("a",20,20),element("b",240,20)]};

test("Phase 62 responsive constraints and adaptive reflow",()=>{let p=setResponsiveBreakpoints2(page,[{id:"desktop",minWidth:900,columns:12,gutter:24,margin:48},{id:"mobile",minWidth:0,maxWidth:899,columns:4,gutter:12,margin:16,scaleTypography:.8}]);p={...p,elements:[setLayoutConstraints2(p.elements[0],{left:16,right:16,widthMode:"fill",minWidth:120}),setReflowRule2(p.elements[1],{allowHide:true,collision:"avoid"})]};p.elements[1].hideBelowWidth=700;const result=resolveResponsiveLayout2(p,480,700);assert.equal(result.breakpoint?.id,"mobile");assert.equal(result.frames[0].width,448);assert.equal(result.frames[1].hidden,true);assert.equal(buildLayoutPlan2(p,480,700).version,"62.0");});

test("Phase 62 advanced grids, anchors and collision resolution",()=>{let p=setAdvancedGrid2(page,{type:"modular",columns:6,rows:8,gutterX:20,gutterY:16,baseline:12,snap:true});p={...p,elements:[setAnchor2(p.elements[0],{mode:"page",horizontal:"left",vertical:"top",offsetX:10,offsetY:10,keepWithinBounds:true}),p.elements[1]]};const frames=resolveCollisions2([{id:"a",x:0,y:0,width:100,height:100},{id:"b",x:50,y:50,width:100,height:100}],10);assert.equal(p.advancedGrid2.columns,6);assert.equal(p.elements[0].layoutAnchor2.keepWithinBounds,true);assert.equal(frames[1].y,110);});

test("Phase 62 master pages and controlled overrides",()=>{let p=setMasterPage2(page,{id:"master-a",name:"A-Master",lockedElementIds:["a","a"],overridesAllowed:false,pageNumberStyle:"arabic"});let result=applyMasterOverrides2(p,{a:{x:400},b:{x:500}});assert.equal(result.elements[0].x,20);assert.equal(result.elements[1].x,500);p=setMasterPage2(p,{...p.masterPage2,overridesAllowed:true});result=applyMasterOverrides2(p,{a:{x:400}});assert.equal(result.elements[0].x,400);assert.deepEqual(p.masterPage2.lockedElementIds,["a"]);});

test("Phase 62 print imposition and layout preflight",()=>{const options:any={mode:"booklet",sheetWidth:1200,sheetHeight:800,rows:1,columns:2,gutter:20,bleed:12,creep:1.5,duplex:true,binding:"left"};const doc=setImposition2({id:"d1"},options);const plan=buildImpositionPlan2(8,doc.layoutImposition2);assert.equal(plan.sheets,2);assert.equal(plan.placements.length,8);assert.equal(plan.bookletReady,true);assert.deepEqual(validateLayoutEngine2(page),[]);const bad={...page,width:0,elements:[...page.elements,{...page.elements[0]}]};assert.ok(validateLayoutEngine2(bad).length>=2);});
