import test from "node:test";
import assert from "node:assert/strict";
import { buildTypographyLayoutPlan2, configureParagraphComposer2, configureTextPath2, configureTextThread2, setFontFallbackChain2, setOpenTypeFeatures2, setOpticalTypography2, setTypographyExport2, setVariableFontAxes2, shapeText2, validateTypographyEngine2 } from "../src/utils/professionalTypographyEngine2.ts";

const base:any={id:"t1",name:"Headline",type:"text",x:0,y:0,width:420,height:160,rotation:0,opacity:1,visible:true,locked:false,zIndex:1,text:"Professional publishing typography",fontFamily:"Inter Variable",fontSize:36,lineHeight:44,columnCount:1};

test("Phase 61 variable fonts and OpenType features",()=>{let e=setVariableFontAxes2(base,[{tag:"wght",min:100,max:900,value:1200},{tag:"wdth",min:75,max:125,value:95}]);e=setOpenTypeFeatures2(e,["kern","liga","ss01","liga"]);const run=shapeText2(e)[0];assert.equal(e.variableFontAxes.wght,900);assert.deepEqual(run.features,["kern","liga","ss01"]);assert.equal(run.axes.wdth,95);});

test("Phase 61 multilingual shaping and fallback",()=>{let e=setFontFallbackChain2(base,[{family:"Noto Sans Ethiopic",scripts:["Ethiopic"]},{family:"Noto Sans Arabic",scripts:["Arabic/Hebrew"]}]);const run=shapeText2(e,"ሰላም ዓለም")[0];assert.equal(run.script,"Ethiopic");assert.equal(run.fontFamily,"Noto Sans Ethiopic");assert.equal(run.fallbackUsed,true);});

test("Phase 61 text paths, composition, threading and optical typography",()=>{let e=configureTextPath2(base,{pathId:"curve-1",startOffset:25,side:"left",align:"center",reverse:false,baselineOffset:4,keepUpright:true});e=configureParagraphComposer2(e,{mode:"balanced",language:"en-US",hyphenation:true,widowLines:3,orphanLines:3,justification:{minWordSpacing:80,desiredWordSpacing:100,maxWordSpacing:140,minLetterSpacing:-2,desiredLetterSpacing:0,maxLetterSpacing:4,glyphScalingMin:96,glyphScalingMax:104}});e=configureTextThread2(e,{threadId:"thread-1",frameIds:["t1","t2","t2"],overflowBehavior:"auto-create-frame",balanceColumns:true});e=setOpticalTypography2(e,{kerning:"optical",hangingPunctuation:true,baselineGrid:true,baselineGridSpacing:14});const plan=buildTypographyLayoutPlan2(e);assert.equal(plan.textPath.pathId,"curve-1");assert.equal(plan.composer.mode,"balanced");assert.deepEqual(plan.thread.frameIds,["t1","t2"]);assert.equal(plan.optical.baselineGrid,true);});

test("Phase 61 export-safe typography and preflight",()=>{let e=setTypographyExport2(base,{embedFonts:true,subsetFonts:true,preserveVariableFonts:true,taggedText:true});assert.deepEqual(validateTypographyEngine2(e),[]);const bad=configureTextPath2({...base,fontFamily:"",height:10},{pathId:"",startOffset:0,side:"left",align:"start",reverse:false,baselineOffset:0,keepUpright:true});const issues=validateTypographyEngine2(bad);assert.ok(issues.length>=3);assert.equal(buildTypographyLayoutPlan2(bad).version,"61.0");});
