import test from "node:test";
import assert from "node:assert/strict";
import type { PublisherElement, PublisherProject } from "../src/types/publisher";
import { auditProfessionalVectors, clearVectorAppearanceFill, normalizeGradientStops, setVectorGradient, setVectorPattern, vectorElementToSvg } from "../src/utils/professionalVectorEngine";
const path: PublisherElement={id:"v",name:"Appearance",type:"line",x:0,y:0,width:120,height:80,rotation:0,zIndex:1,opacity:1,borderColor:"#111827",borderWidth:3,fillColor:"transparent",shapeKind:"bezier-path",editableVector:true,vectorClosed:true,vectorNodes:[{x:5,y:5},{x:115,y:5},{x:60,y:75}]};
test("Phase 16.2 normalizes multi-stop gradients",()=>{const stops=normalizeGradientStops([{offset:1.4,color:"#fff"},{offset:-.2,color:"#000"},{offset:.5,color:"#f00",opacity:.5}]);assert.deepEqual(stops.map(s=>s.offset),[0,.5,1]);assert.equal(stops[1].opacity,.5);});
test("Phase 16.2 exports gradient definitions",()=>{const linear=setVectorGradient(path,{type:"linear",angle:45,spread:"reflect",stops:[{offset:0,color:"#7C3AED"},{offset:1,color:"#06B6D4"}]});const svg=vectorElementToSvg(linear);assert.match(svg,/<linearGradient/);assert.match(svg,/spreadMethod="reflect"/);const radial=setVectorGradient(path,{type:"radial",cx:.4,cy:.6,radius:.7,stops:[{offset:0,color:"#fff"},{offset:1,color:"#000"}]});assert.match(vectorElementToSvg(radial),/<radialGradient/);});
test("Phase 16.2 exports patterns and appearance",()=>{const patterned=setVectorPattern(path,{type:"crosshatch",foreground:"#111827",background:"#F8FAFC",size:14,angle:15,strokeWidth:2});const svg=vectorElementToSvg({...patterned,vectorFillOpacity:.65,vectorStrokeOpacity:.4,vectorBlendMode:"multiply"});assert.match(svg,/<pattern/);assert.match(svg,/fill-opacity="0.65"/);assert.match(svg,/stroke-opacity="0.4"/);assert.match(svg,/mix-blend-mode:multiply/);const cleared=clearVectorAppearanceFill(patterned,"#123456");assert.equal(cleared.vectorPattern,undefined);assert.equal(cleared.fillColor,"#123456");});
test("Phase 16.2 audit validates appearance",()=>{const bad={...path,vectorPattern:{type:"dots",foreground:"#000",background:"#fff",size:1},vectorFillOpacity:2} as PublisherElement;const project:PublisherProject={id:"p",name:"Audit",createdAt:1,updatedAt:1,activePageId:"page",autoSave:true,version:2,pages:[{id:"page",name:"Page",width:500,height:500,orientation:"portrait",sizeKey:"custom",backgroundColor:"#fff",margin:20,bleed:0,elements:[bad]}]};const issues=auditProfessionalVectors(project);assert.ok(issues.some(i=>i.id.startsWith("pattern-")));assert.ok(issues.some(i=>i.id.startsWith("appearance-opacity-")));});
