import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
const read=p=>readFileSync(p,'utf8');

test('91.5 adds advanced matting and edge cleanup',()=>{const s=read('services/background-removal/app.py');for(const t of ['alpha_matting=True','refine_alpha','decontaminate_edges','thin-structures','hole_fraction'])assert.ok(s.includes(t),t)});
test('91.5 adds shadow, geometry and catalog consistency',()=>{const s=read('services/background-removal/app.py');for(const t of ['extract_shadow','bbox_geometry','catalog_layout','catalog_target_occupancy','foreground_geometry'])assert.ok(s.includes(t),t)});
test('91.5 adds multi-candidate category-aware routing and failover',()=>{const s=read('services/background-removal/app.py');for(const t of ['model_strategy','candidate_rank','category_hint','detail-soft-matte','model_agreement_iou'])assert.ok(s.includes(t),t)});
test('91.5 supports high resolution and multiple optimized outputs',()=>{const s=read('services/background-removal/app.py');assert.match(s,/MAX_PIXELS.*50000000/);assert.ok(s.includes('full-resolution-staged'));for(const t of ['image/webp','image/jpeg','output_format'])assert.ok(s.includes(t),t)});
test('91.5 adds duplicate cache retries warm pool concurrency and metrics',()=>{const s=read('services/background-removal/app.py');for(const t of ['duplicate_cache_hits','remove_with_retry','session_for','BoundedSemaphore','/metrics','/review-feedback','/analyze-photo'])assert.ok(s.includes(t),t)});
test('91.5 keeps paid API firewall closed and product changes opt-in',()=>{const cost=JSON.parse(read('release/phase91.0/cost-policy.json'));assert.equal(cost.paidPerImageProviderEnabled,false);assert.equal(cost.paidProviderMonthlyBudgetUsd,0);assert.equal(cost.autoOverage,false);const s=read('services/background-removal/app.py');assert.match(s,/normalize_lighting: bool = False/);assert.match(s,/paid_api_cost_usd":0/)});
test('91.5 UI includes batch consistency, format choice and category routing',()=>{const s=read('src/app/product-photo-studio.tsx');for(const t of ['Batch consistency','outputFormat','categoryHint','Batch lighting normalization','91.5 · PRODUCT PHOTO ENGINE'])assert.ok(s.includes(t),t);assert.doesNotMatch(s,/good\s*will/i)});
test('91.5 category parity policy is strict and cannot self certify',()=>{const p=JSON.parse(read('release/phase91.5/category-parity-policy.json'));assert.equal(p.claimStatus,'CATEGORY_PARITY_TARGET_NOT_EXTERNALLY_CERTIFIED');assert.ok(p.minimumBenchmarkImages>=400);assert.equal(p.maximumCriticalProductLosses,0);assert.equal(p.maximumUnexpectedPaidApiSpendUsd,0);assert.equal(p.maximumDeficitVsComparisonTool['hard-goods'],0.01);assert.equal(p.maximumDeficitVsComparisonTool['glass-transparent'],0.03)});
test('91.5 release artifacts and gates exist',()=>{for(const f of ['scripts/evaluate-phase91.5-category-parity.mjs','scripts/verify-phase91.5.mjs','release/phase91.5/benchmark-template.csv','PHASE91.5-ADVANCED-PRODUCT-PHOTO-PARITY.md','services/background-removal/Dockerfile.gpu','services/background-removal/requirements-gpu.txt'])assert.equal(existsSync(f),true,f);const pkg=JSON.parse(read('package.json'));assert.match(pkg.scripts.test,/test:phase91\.5/);assert.ok(pkg.scripts['check:phase91.5']);assert.match(pkg.scripts['verify:phase91.5'],/check:phase91\.5/)});
test('91.5 source packager requires the new release artifacts',()=>{const s=read('scripts/create-source-release.mjs');for(const f of ['release/phase91.5/category-parity-policy.json','release/phase91.5/benchmark-template.csv','scripts/evaluate-phase91.5-category-parity.mjs','scripts/verify-phase91.5.mjs','tests/phase915-advanced-product-photo-parity.test.mjs','PHASE91.5-ADVANCED-PRODUCT-PHOTO-PARITY.md','services/background-removal/Dockerfile.gpu','services/background-removal/requirements-gpu.txt'])assert.ok(s.includes(f),f)});
