import assert from "node:assert/strict";
import test from "node:test";
import { buildDataSource } from "../src/utils/mailMergeEngine";
import { buildPrintMergeProject, createContactGroup, DEFAULT_MERGE_PRINT_SETTINGS, estimatePrintJob, importContactsFromSource, LABEL_TEMPLATES, validateAddressBook } from "../src/utils/mailMergePrintEngine";
import type { PublisherProject } from "../src/types/publisher";

test("Phase 14.3 provides professional label and card templates",()=>{assert.ok(LABEL_TEMPLATES.some((item)=>item.productCode?.includes("5160")));assert.ok(LABEL_TEMPLATES.some((item)=>item.kind==="business-card"));assert.ok(LABEL_TEMPLATES.some((item)=>item.kind==="certificate"));});
test("Phase 14.3 imports, validates and groups recipients",()=>{const source=buildDataSource("people.csv","csv",[{name:"Ada",address:"1 Main St",city:"Baltimore",zip:"21201"},{name:"Ben",address:"",city:"Baltimore",zip:"bad!"}]);const contacts=importContactsFromSource(source);assert.equal(contacts.length,2);assert.ok(validateAddressBook(contacts).length>=2);const result=createContactGroup("VIP",contacts,[contacts[0].id]);assert.equal(result.group.contactIds.length,1);assert.ok(result.contacts[0].groupIds.includes(result.group.id));});
test("Phase 14.3 builds imposed print-ready sheets",()=>{const source=buildDataSource("people.csv","csv",Array.from({length:31},(_,i)=>({name:`Person ${i+1}`,address:`${i+1} Main St`,city:"Baltimore",zip:"21201"})));const project:PublisherProject={id:"p",name:"Labels",createdAt:1,updatedAt:1,version:2,autoSave:true,activePageId:"page",pages:[{id:"page",name:"Label",width:252,height:96,orientation:"landscape",sizeKey:"custom",backgroundColor:"#fff",margin:0,bleed:0,elements:[{id:"t",name:"Name",type:"text",x:8,y:8,width:220,height:30,rotation:0,zIndex:1,opacity:1,text:"{{name}}",fontSize:14,textColor:"#000"}]}],mailMergeData:{sources:[source],activeSourceId:source.id}};const settings={...DEFAULT_MERGE_PRINT_SETTINGS,templateId:"avery-5160"};const estimate=estimatePrintJob(project.mailMergeData!,settings);assert.equal(estimate.sheets,2);const output=buildPrintMergeProject(project,settings);assert.equal(output.pages.length,2);assert.equal(output.pages[0].elements[0].text,"Person 1");assert.ok(output.mailMergeData?.printHistory?.length);});
