import test from "node:test";
import assert from "node:assert/strict";
import { InMemoryDatabase } from "../server/database.ts";
import { MemoryCollaborationStore, RedisCollaborationStore, createComment, joinCollaboration, listComments, listPresence, setCollaborationStore, updatePresence } from "../server/collaboration.ts";
import { claimNextExportJob, createExportJob, recoverStaleExportJobs, updateExportJob } from "../server/productionExport.ts";

class FakeRedis { values=new Map<string,string>(); async get(k:string){return this.values.get(k)??null} async set(k:string,v:string){this.values.set(k,v);return "OK"} async del(k:string){return this.values.delete(k)?1:0} }
async function seed(){const db=new InMemoryDatabase();await db.connect();const user=await db.insert("users",{email:"owner@example.com",passwordHash:"x",emailVerified:true,status:"active"});const org=await db.insert("organizations",{name:"Yaposan",ownerUserId:user.id,plan:"business"});const ws=await db.insert("workspaces",{organizationId:org.id,name:"Main",region:"us-east"});const project=await db.insert("projects",{workspaceId:ws.id,ownerUserId:user.id,name:"Catalog",revision:1,payload:{}});return{db,user,ws,project}}

test("Redis collaboration store shares presence and comments across store instances",async()=>{const redis=new FakeRedis();const a=new RedisCollaborationStore(redis);const b=new RedisCollaborationStore(redis);setCollaborationStore(a);const session=await joinCollaboration({userId:"u1",projectId:"p1",displayName:"One",color:"#000",selectionIds:[]});await createComment({projectId:"p1",authorUserId:"u1",body:"Shared"});setCollaborationStore(b);assert.equal((await listPresence("p1")).length,1);assert.equal((await listComments("p1"))[0].body,"Shared");await assert.rejects(updatePresence(session.sessionId,"other",{displayName:"Hack"}),/FORBIDDEN/);setCollaborationStore(new MemoryCollaborationStore())});

test("export claims are exclusive and enforce worker leases",async()=>{const{db,user,ws,project}=await seed();const job=await createExportJob(db,{projectId:project.id,workspaceId:ws.id,userId:user.id,format:"pdf"});const first=await claimNextExportJob(db,"worker-a",30);const second=await claimNextExportJob(db,"worker-b",30);assert.equal(first?.id,job.id);assert.equal(second,undefined);await assert.rejects(updateExportJob(db,job.id,{progress:20,workerId:"worker-b"}),/LEASE_MISMATCH/);const finished=await updateExportJob(db,job.id,{progress:100,status:"succeeded",workerId:"worker-a"});assert.equal(finished.workerId,undefined);assert.equal(finished.leaseExpiresAt,undefined)});

test("expired export leases are recovered for another worker",async()=>{const{db,user,ws,project}=await seed();const job=await createExportJob(db,{projectId:project.id,workspaceId:ws.id,userId:user.id,format:"png"});await claimNextExportJob(db,"dead-worker",1);await db.update("jobs",job.id,{leaseExpiresAt:"2000-01-01T00:00:00.000Z"});assert.equal(await recoverStaleExportJobs(db,new Date()),1);const claimed=await claimNextExportJob(db,"replacement",30);assert.equal(claimed?.id,job.id);assert.equal(claimed?.attempts,2)});
