import test from "node:test";
import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import { canActivateDevice, commercialDiagnostics, issueLicense, stripePriceForPlan, validateCheckoutSelection, verifyLicense } from "../server/commercialReadiness.ts";
import { verifyStripeWebhook } from "../server/payments.ts";
import { loadCloudConfig, validateProductionConfig } from "../server/config.ts";

const secret = "0123456789abcdef0123456789abcdef";
const base = { licenseId:"lic_1", organizationId:"org_1", plan:"pro" as const, seats:5, deviceLimit:3, issuedAt:1_000, expiresAt:10_000, graceDays:2 };

test("RC7 signs and verifies active licenses",()=>{const token=issueLicense(base,secret);const result=verifyLicense(token,secret,5_000);assert.equal(result.valid,true);assert.equal(result.status,"active");assert.equal(result.payload?.plan,"pro")});
test("RC7 detects license tampering",()=>{const token=issueLicense(base,secret);assert.equal(verifyLicense(token+"x",secret,5_000).valid,false)});
test("RC7 supports bounded grace periods",()=>{const token=issueLicense(base,secret);assert.equal(verifyLicense(token,secret,10_001).status,"grace");assert.equal(verifyLicense(token,secret,10_000+2*86_400_000+1).status,"expired")});
test("RC7 enforces device activation limits",()=>{assert.equal(canActivateDevice(base,["a","b","c"],"d").allowed,false);assert.equal(canActivateDevice(base,["a","b","c"],"b").allowed,true)});
test("RC7 rejects weak license signing secrets",()=>assert.throws(()=>issueLicense(base,"weak"),/LICENSE_SECRET_TOO_WEAK/));
test("RC7 maps plans only through configured Stripe price IDs",()=>{assert.equal(stripePriceForPlan("creator",{STRIPE_PRICE_CREATOR:"price_creator123"} as NodeJS.ProcessEnv),"price_creator123");assert.throws(()=>stripePriceForPlan("creator",{} as NodeJS.ProcessEnv),/STRIPE_PRICE_NOT_CONFIGURED/)});
test("RC7 validates checkout plan, quantity, and redirect URLs",()=>{const result=validateCheckoutSelection({plan:"pro",quantity:4,successUrl:"https://app.yaposan.com/success",cancelUrl:"https://app.yaposan.com/cancel"},{STRIPE_PRICE_PRO:"price_pro123"} as NodeJS.ProcessEnv);assert.equal(result.quantity,4);assert.throws(()=>validateCheckoutSelection({plan:"free",successUrl:"https://a.test",cancelUrl:"https://a.test"},{} as NodeJS.ProcessEnv),/INVALID_CHECKOUT_PLAN/);assert.throws(()=>validateCheckoutSelection({plan:"pro",successUrl:"http://evil.test",cancelUrl:"https://a.test"},{STRIPE_PRICE_PRO:"price_pro123"} as NodeJS.ProcessEnv),/UNSAFE_CHECKOUT_URL/)});
test("RC7 rejects stale Stripe webhook signatures",()=>{const payload='{"id":"evt_1"}', timestamp=1000;const signature=createHmac("sha256",secret).update(`${timestamp}.${payload}`).digest("hex");assert.equal(verifyStripeWebhook(payload,`t=${timestamp},v1=${signature}`,secret,300,1001),true);assert.equal(verifyStripeWebhook(payload,`t=${timestamp},v1=${signature}`,secret,300,1400),false)});
test("RC7 reports identity and commercial provider readiness",()=>{const d=commercialDiagnostics({LICENSE_SIGNING_SECRET:secret,STRIPE_SECRET_KEY:"sk_test",STRIPE_WEBHOOK_SECRET:"whsec",STRIPE_PRICE_CREATOR:"price_c",STRIPE_PRICE_PRO:"price_p",STRIPE_PRICE_BUSINESS:"price_b",MICROSOFT_CLIENT_ID:"id",MICROSOFT_CLIENT_SECRET:"secret",MICROSOFT_TENANT_ID:"tenant"} as NodeJS.ProcessEnv);assert.equal(d.licenseSigning,true);assert.equal(d.stripePrices.business,true);assert.equal(d.oauth.microsoft,true);assert.equal(d.oauth.google,false)});
test("RC7 production validation requires a license signing secret",()=>{const config=loadCloudConfig({NODE_ENV:"production",DATABASE_URL:"postgres://db",SESSION_SECRET:secret,STORAGE_DRIVER:"r2",STORAGE_BUCKET:"bucket",STORAGE_ENDPOINT:"https://r2.example",R2_ACCESS_KEY_ID:"id",R2_SECRET_ACCESS_KEY:"secret",COLLABORATION_DRIVER:"redis",REDIS_URL:"redis://redis",STRIPE_SECRET_KEY:"sk",STRIPE_WEBHOOK_SECRET:"wh",OPENAI_API_KEY:"oa",ADMIN_EMAILS:"admin@example.com"} as NodeJS.ProcessEnv);assert.ok(validateProductionConfig(config,"production").some(x=>x.includes("LICENSE_SIGNING_SECRET")))});
