import React from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherElement } from "../../types/publisher";
import { normalizeAdvancedPaintingSettings, type AdvancedPaintingSettings } from "../../utils/advancedPaintingEngine";

type Props={visible:boolean;settings:AdvancedPaintingSettings;element:PublisherElement|null;onChange:(settings:AdvancedPaintingSettings)=>void;onApply:()=>void;onClose:()=>void};
const choices=<T extends string|number>(values:T[],selected:T,onSelect:(value:T)=>void)=><View style={styles.row}>{values.map(value=><Pressable key={String(value)} style={[styles.chip,selected===value&&styles.chipActive]} onPress={()=>onSelect(value)}><Text style={[styles.chipText,selected===value&&styles.chipTextActive]}>{String(value)}</Text></Pressable>)}</View>;
export default function AdvancedPaintingModal({visible,settings,element,onChange,onApply,onClose}:Props){
 const update=(patch:Partial<AdvancedPaintingSettings>)=>onChange(normalizeAdvancedPaintingSettings({...settings,...patch}));
 const numberField=(label:string,key:keyof AdvancedPaintingSettings)=><View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} keyboardType="numeric" value={String(settings[key])} onChangeText={text=>update({[key]:Number(text)} as Partial<AdvancedPaintingSettings>)}/></View>;
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.panel}><View style={styles.header}><View><Text style={styles.title}>Advanced Painting</Text><Text style={styles.subtitle}>Brush tips, mixer, recording, stylus, large canvas and interchange</Text></View><Pressable onPress={onClose}><Text style={styles.close}>Close</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}>
 <Text style={styles.section}>Brush Tip Editor</Text>{choices(["round","square","ellipse","bristle","rake","stamp","pixel"],settings.brushTipShape,value=>update({brushTipShape:value}))}{numberField("Roundness", "brushTipRoundness")}{numberField("Angle", "brushTipAngle")}{numberField("Spacing", "brushTipSpacing")}{numberField("Tip count", "brushTipCount")}{numberField("Random seed", "brushTipSeed")}
 <Text style={styles.section}>Natural Color Mixer</Text>{choices(["off","on"],settings.mixerEnabled?"on":"off",value=>update({mixerEnabled:value==="on"}))}{choices(["rgb","subtractive","natural-pigment"],settings.mixerModel,value=>update({mixerModel:value}))}{numberField("Wetness", "mixerWetness")}{numberField("Paint load", "mixerLoad")}{numberField("Color pickup", "mixerPickup")}
 <Text style={styles.section}>Stroke Recording</Text>{choices(["off","on"],settings.recordStrokes?"on":"off",value=>update({recordStrokes:value==="on"}))}{choices(["cursor hidden","cursor visible"],settings.recordCursor?"cursor visible":"cursor hidden",value=>update({recordCursor:value==="cursor visible"}))}{numberField("Recording FPS", "recordingFps")}
 <Text style={styles.section}>Stylus Input</Text>{choices(["mouse","generic-pen","windows-ink","apple-pencil","wacom"],settings.stylusProfile,value=>update({stylusProfile:value}))}{choices(["tilt off","tilt on"],settings.tiltEnabled?"tilt on":"tilt off",value=>update({tiltEnabled:value==="tilt on"}))}{choices(["rotation off","rotation on"],settings.barrelRotationEnabled?"rotation on":"rotation off",value=>update({barrelRotationEnabled:value==="rotation on"}))}{choices(["palm rejection off","palm rejection on"],settings.palmRejection?"palm rejection on":"palm rejection off",value=>update({palmRejection:value==="palm rejection on"}))}
 <Text style={styles.section}>Large Canvas</Text>{choices(["standard","tiled"],settings.largeCanvasMode?"tiled":"standard",value=>update({largeCanvasMode:value==="tiled"}))}{choices([256,512,1024,2048],settings.tileSize,value=>update({tileSize:value}))}{numberField("Resident tile limit", "maxResidentTiles")}
 <Text style={styles.section}>Color & Interchange</Text>{choices([8,16,32],settings.colorDepth,value=>update({colorDepth:value}))}{choices(["HDR preview off","HDR preview on"],settings.hdrPreview?"HDR preview on":"HDR preview off",value=>update({hdrPreview:value==="HDR preview on"}))}{choices(["native","psd-compatible","ora-compatible","flattened"],settings.interchangeFormat,value=>update({interchangeFormat:value}))}{choices(["embed brushes","reference brushes"],settings.embedBrushes?"embed brushes":"reference brushes",value=>update({embedBrushes:value==="embed brushes"}))}{choices(["embed timelapse","no timelapse"],settings.embedTimelapse?"embed timelapse":"no timelapse",value=>update({embedTimelapse:value==="embed timelapse"}))}
 <Text style={styles.summary}>Selected object: {element?.name ?? "None"} · Engine version: {element?.phase18Version ?? "not configured"}</Text>
 </ScrollView><View style={styles.footer}><Pressable style={[styles.primary,!element&&styles.disabled]} disabled={!element} onPress={onApply}><Text style={styles.primaryText}>Apply Advanced Painting</Text></Pressable></View></View></View></Modal>;
}
const styles=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(8,15,30,.76)",alignItems:"center",justifyContent:"center",padding:24},panel:{width:"94%",maxWidth:1040,maxHeight:"94%",backgroundColor:"#f7f9fc",borderRadius:18,overflow:"hidden"},header:{padding:20,backgroundColor:"#172033",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"white",fontSize:20,fontWeight:"800"},subtitle:{color:"#b9c6dc",marginTop:4},close:{color:"#fff",fontWeight:"700"},content:{padding:20},section:{fontSize:15,fontWeight:"800",color:"#172033",marginTop:14,marginBottom:8},label:{fontSize:12,fontWeight:"700",color:"#526078",marginBottom:5},row:{flexDirection:"row",flexWrap:"wrap",gap:7,marginBottom:10},chip:{borderWidth:1,borderColor:"#c7cfdb",borderRadius:999,paddingHorizontal:11,paddingVertical:7,backgroundColor:"#fff"},chipActive:{backgroundColor:"#2157d5",borderColor:"#2157d5"},chipText:{fontSize:12,color:"#27354d",textTransform:"capitalize"},chipTextActive:{color:"white",fontWeight:"700"},field:{marginBottom:10},input:{borderWidth:1,borderColor:"#c7cfdb",borderRadius:8,backgroundColor:"white",paddingHorizontal:10,paddingVertical:8,color:"#172033",marginBottom:8},summary:{marginTop:16,padding:12,backgroundColor:"#e9eef8",borderRadius:8,color:"#33445f"},footer:{flexDirection:"row",justifyContent:"flex-end",padding:16,borderTopWidth:1,borderTopColor:"#dce2ec"},primary:{backgroundColor:"#2157d5",paddingHorizontal:18,paddingVertical:11,borderRadius:9},primaryText:{color:"white",fontWeight:"800"},disabled:{opacity:.45}});
