import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { describeObjects, getCompletionData, processTextElements, resolvePromptVariables, restoreRevision, PROFILE_GUIDANCE, type AiObjectScope, type AiProjectProfile } from "../../services/aiCompletionService";
import type { AiWritingAction } from "../../types/aiWriting";
import type { PublisherProject } from "../../types/publisher";

type Props={project:PublisherProject;selectedElementIds:string[];onApplyProject:(project:PublisherProject)=>void;onSelectObject:(pageId:string,elementId?:string)=>void};
const PROFILES:AiProjectProfile[]=["Church","Business","Nonprofit","School","Restaurant","Medical","Retail","Custom"];
const ACTIONS:AiWritingAction[]=["rewrite","grammar","professional","friendly","summarize","translate","headline"];
export default function AiCompletionPanel({project,selectedElementIds,onApplyProject,onSelectObject}:Props){
 const[data,setData]=useState(()=>getCompletionData(project));const[scope,setScope]=useState<AiObjectScope>("selection"),[action,setAction]=useState<AiWritingAction>("rewrite"),[prompt,setPrompt]=useState("Improve this content while preserving its meaning."),[targetLanguage,setTargetLanguage]=useState("Spanish"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const activePage=project.pages.find(p=>p.id===project.activePageId)??project.pages[0];
 const scoped=useMemo(()=>scope==="document"?project.pages.flatMap(p=>p.elements):scope==="page"?(activePage?.elements??[]):(activePage?.elements??[]).filter(e=>selectedElementIds.includes(e.id)),[scope,project.pages,activePage,selectedElementIds]);
 const context=describeObjects(scoped,scope);const textIds=scoped.filter(e=>e.type==="text").map(e=>e.id);const preview=resolvePromptVariables(prompt,project,Math.max(1,project.pages.findIndex(p=>p.id===project.activePageId)+1));
 const setProfile=(profile:AiProjectProfile,eventTime:number)=>{const next={...data,profile};setData(next);onApplyProject({...project,aiCompletionData:next,updatedAt:eventTime});};
 const run=async()=>{if(!textIds.length){setMessage("No text objects are available in this scope.");return;}setBusy(true);setMessage("");try{const done=await processTextElements({...project,aiCompletionData:data},textIds,action,prompt,action==="translate"?targetLanguage:undefined);onApplyProject(done.project);setData(getCompletionData(done.project));setMessage(`Updated ${done.revisions.length} text object${done.revisions.length===1?"":"s"}.`);}catch(e){setMessage(e instanceof Error?e.message:"Batch processing failed.");}finally{setBusy(false);}};
 const revisions=getCompletionData(project).revisions;
 return <View style={s.wrap}><Text style={s.heading}>AI Object Awareness</Text><Text style={s.context}>{context.summary}</Text><View style={s.row}>{(["selection","page","document"] as AiObjectScope[]).map(x=><Pressable key={x} onPress={()=>setScope(x)} style={[s.chip,scope===x&&s.chipOn]}><Text style={s.chipText}>{x}</Text></Pressable>)}</View>
 <Text style={s.heading}>Project Profile</Text><ScrollView horizontal contentContainerStyle={s.row}>{PROFILES.map(x=><Pressable key={x} onPress={(event)=>setProfile(x,Math.trunc(Number(event.nativeEvent.timestamp ?? project.updatedAt)))} style={[s.chip,data.profile===x&&s.chipOn]}><Text style={s.chipText}>{x}</Text></Pressable>)}</ScrollView><Text style={s.help}>{PROFILE_GUIDANCE[data.profile]}</Text>
 <Text style={s.heading}>Prompt Variables & Batch Processing</Text><TextInput value={prompt} onChangeText={setPrompt} multiline style={s.input}/><Text style={s.preview}>{preview}</Text><ScrollView horizontal contentContainerStyle={s.row}>{ACTIONS.map(x=><Pressable key={x} onPress={()=>setAction(x)} style={[s.chip,action===x&&s.chipOn]}><Text style={s.chipText}>{x}</Text></Pressable>)}</ScrollView>{action==="translate"&&<TextInput value={targetLanguage} onChangeText={setTargetLanguage} style={s.smallInput}/>}<Pressable disabled={busy} onPress={()=>void run()} style={s.primary}><Text style={s.primaryText}>{busy?"Processing…":`Run on ${textIds.length} text object${textIds.length===1?"":"s"}`}</Text></Pressable>{!!message&&<Text style={s.message}>{message}</Text>}
 <Text style={s.heading}>AI Revision History & Compare</Text><ScrollView style={s.list}>{revisions.length?revisions.slice(0,40).map(r=><View key={r.id} style={s.card}><Pressable onPress={()=>onSelectObject(r.pageId,r.elementId)} style={{flex:1}}><Text style={s.cardTitle}>{r.action} · Confidence {r.confidence}%</Text><Text numberOfLines={2} style={s.original}>Original: {r.original}</Text><Text numberOfLines={2} style={s.result}>AI: {r.result}</Text></Pressable><View style={s.actions}><Pressable onPress={()=>onApplyProject(restoreRevision(project,r,false))}><Ionicons name="arrow-undo" size={18} color="#B45309"/></Pressable><Pressable onPress={()=>onApplyProject(restoreRevision(project,r,true))}><Ionicons name="checkmark-circle" size={19} color="#047857"/></Pressable></View></View>):<Text style={s.help}>AI revisions will appear here after a batch or object-aware action.</Text>}</ScrollView></View>;
}
const s=StyleSheet.create({wrap:{gap:9},heading:{fontSize:12,fontWeight:"900",color:"#312E81"},context:{fontSize:10,color:"#475569",backgroundColor:"#EEF2FF",padding:9,borderRadius:8},row:{flexDirection:"row",gap:6},chip:{backgroundColor:"#E2E8F0",paddingHorizontal:9,paddingVertical:7,borderRadius:14},chipOn:{backgroundColor:"#7C3AED"},chipText:{fontSize:9,fontWeight:"800",color:"#334155"},help:{fontSize:9,lineHeight:14,color:"#64748B"},input:{minHeight:70,borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,padding:9,fontSize:10,backgroundColor:"#fff",textAlignVertical:"top"},smallInput:{borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,padding:9,fontSize:10,backgroundColor:"#fff"},preview:{fontSize:9,lineHeight:14,color:"#5B21B6",backgroundColor:"#F5F3FF",padding:8,borderRadius:7},primary:{backgroundColor:"#7C3AED",padding:10,borderRadius:8,alignItems:"center"},primaryText:{color:"#fff",fontSize:10,fontWeight:"900"},message:{fontSize:10,fontWeight:"700",color:"#0F766E"},list:{maxHeight:360},card:{flexDirection:"row",gap:8,borderWidth:1,borderColor:"#E2E8F0",backgroundColor:"#fff",borderRadius:8,padding:9,marginBottom:7},cardTitle:{fontSize:10,fontWeight:"900",color:"#1E293B"},original:{fontSize:9,lineHeight:14,color:"#64748B",marginTop:4},result:{fontSize:9,lineHeight:14,color:"#0F766E",marginTop:3},actions:{gap:10,justifyContent:"center"}});
