import { Ionicons } from "@expo/vector-icons";
import { useMemo, useRef, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AI_COMMANDS, DEFAULT_WORKFLOWS, createQueueJob, executeQueueJob, runWorkflow, streamChunks, usageSummary, type AiQueueJob, type AiUsageEntry, type AiWorkflow } from "../../services/aiWorkflowService";
import type { AiWritingAction } from "../../types/aiWriting";

type Area="Stream"|"Queue"|"Commands"|"Workflows"|"Usage";
type Props={selectedText:string;onInsertText:(text:string)=>void;onRunAction:(action:AiWritingAction,prompt:string,targetLanguage?:string)=>void};
export default function AiWorkflowPanel({selectedText,onInsertText,onRunAction}:Props){
 const[area,setArea]=useState<Area>("Stream"),[input,setInput]=useState(selectedText),[streamed,setStreamed]=useState(""),[streaming,setStreaming]=useState(false),[paused,setPaused]=useState(false),[jobs,setJobs]=useState<AiQueueJob[]>([]),[usage,setUsage]=useState<AiUsageEntry[]>([]),[query,setQuery]=useState(""),[workflows,setWorkflows]=useState<AiWorkflow[]>(DEFAULT_WORKFLOWS),[result,setResult]=useState("");
 const cancelRef=useRef(false),pauseRef=useRef(false);const summary=useMemo(()=>usageSummary(usage),[usage]);
 const filtered=AI_COMMANDS.filter(c=>`${c.label} ${c.keywords.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
 const startStream=async(action:AiWritingAction="rewrite")=>{cancelRef.current=false;pauseRef.current=false;setPaused(false);setStreaming(true);setStreamed("");const job=createQueueJob(action,input||selectedText||"Create a professional publication message");const done=await executeQueueJob(job);setUsage(u=>[done.usage,...u]);const chunks=streamChunks(done.job.result??"");let text="";for(const chunk of chunks){if(cancelRef.current)break;while(pauseRef.current&&!cancelRef.current)await new Promise(r=>setTimeout(r,100));text=`${text}${text?" ":""}${chunk}`;setStreamed(text);await new Promise(r=>setTimeout(r,70));}setStreaming(false);};
 const addJob=(action:AiWritingAction)=>setJobs(j=>[...j,createQueueJob(action,input||selectedText||"Create publication content")]);
 const processQueue=async()=>{for(const original of jobs){if(original.status!=="queued")continue;setJobs(list=>list.map(j=>j.id===original.id?{...j,status:"running",progress:25}:j));const done=await executeQueueJob(original);setJobs(list=>list.map(j=>j.id===original.id?done.job:j));setUsage(u=>[done.usage,...u]);}};
 const executeWorkflow=async(w:AiWorkflow)=>{const done=await runWorkflow(w,input||selectedText||"Create publication content");setResult(done.result);setUsage(u=>[...done.usage,...u]);};
 return <View style={s.wrap}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{(["Stream","Queue","Commands","Workflows","Usage"] as Area[]).map(x=><Pressable key={x} onPress={()=>setArea(x)} style={[s.tab,area===x&&s.tabOn]}><Text style={[s.tabText,area===x&&s.tabTextOn]}>{x}</Text></Pressable>)}</ScrollView>
 <TextInput value={input} onChangeText={setInput} placeholder="Selected text or AI task input" multiline style={s.input}/>
 {area==="Stream"&&<><Text style={s.heading}>Live AI Streaming</Text><View style={s.row}><Pressable disabled={streaming} onPress={()=>void startStream("rewrite")} style={s.primary}><Text style={s.primaryText}>Stream rewrite</Text></Pressable>{streaming&&<Pressable onPress={()=>{pauseRef.current=!pauseRef.current;setPaused(p=>!p);}} style={s.secondary}><Text style={s.secondaryText}>{paused?"Resume":"Pause"}</Text></Pressable>}{streaming&&<Pressable onPress={()=>{cancelRef.current=true;pauseRef.current=false;}} style={s.danger}><Text style={s.primaryText}>Cancel</Text></Pressable>}</View>{!!streamed&&<View style={s.output}><Text selectable style={s.outputText}>{streamed}</Text><Pressable onPress={()=>onInsertText(streamed)} style={s.primary}><Text style={s.primaryText}>Insert result</Text></Pressable></View>}</>}
 {area==="Queue"&&<><Text style={s.heading}>Background AI Queue</Text><ScrollView horizontal contentContainerStyle={s.chips}>{(["rewrite","grammar","summarize","translate","marketing"] as AiWritingAction[]).map(a=><Pressable key={a} onPress={()=>addJob(a)} style={s.chip}><Text style={s.chipText}>+ {a}</Text></Pressable>)}</ScrollView><Pressable onPress={()=>void processQueue()} style={s.primary}><Text style={s.primaryText}>Process queued tasks</Text></Pressable><ScrollView style={s.list}>{jobs.map(j=><View key={j.id} style={s.card}><Ionicons name={j.status==="completed"?"checkmark-circle":j.status==="failed"?"alert-circle":"time-outline"} size={18} color={j.status==="completed"?"#047857":j.status==="failed"?"#B91C1C":"#7C3AED"}/><View style={{flex:1}}><Text style={s.cardTitle}>{j.label}</Text><Text style={s.cardText}>{j.status} · {j.progress}%</Text>{j.result&&<Text numberOfLines={2} style={s.cardText}>{j.result}</Text>}</View>{j.status==="queued"&&<Pressable onPress={()=>setJobs(list=>list.map(x=>x.id===j.id?{...x,status:"cancelled"}:x))}><Ionicons name="close" size={18} color="#B91C1C"/></Pressable>}</View>)}</ScrollView></>}
 {area==="Commands"&&<><Text style={s.heading}>AI Command Palette · Ctrl+Shift+P</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search AI commands" style={s.search}/><ScrollView style={s.list}>{filtered.map(c=><Pressable key={c.id} onPress={()=>onRunAction(c.action,input,c.action==="translate"?"Spanish":undefined)} style={s.card}><Ionicons name="flash-outline" size={17} color="#7C3AED"/><View><Text style={s.cardTitle}>{c.label}</Text><Text style={s.cardText}>{c.keywords.join(" · ")}</Text></View></Pressable>)}</ScrollView></>}
 {area==="Workflows"&&<><Text style={s.heading}>Reusable AI Workflows</Text><ScrollView style={s.list}>{workflows.map(w=><View key={w.id} style={s.card}><View style={{flex:1}}><Text style={s.cardTitle}>{w.name}</Text><Text style={s.cardText}>{w.steps.map(x=>x.label).join(" → ")}</Text></View><Pressable onPress={()=>void executeWorkflow(w)} style={s.run}><Text style={s.runText}>Run</Text></Pressable><Pressable onPress={()=>setWorkflows(list=>list.map(x=>x.id===w.id?{...x,favorite:!x.favorite}:x))}><Ionicons name={w.favorite?"star":"star-outline"} size={18} color="#D97706"/></Pressable></View>)}</ScrollView>{!!result&&<View style={s.output}><Text selectable style={s.outputText}>{result}</Text><Pressable onPress={()=>onInsertText(result)} style={s.primary}><Text style={s.primaryText}>Insert workflow result</Text></Pressable></View>}</>}
 {area==="Usage"&&<><Text style={s.heading}>AI Usage Dashboard</Text><View style={s.metrics}>{[["Requests",summary.requests],["Input tokens",summary.inputTokens],["Output tokens",summary.outputTokens],["Est. cost",`$${summary.cost.toFixed(4)}`]].map(([a,b])=><View key={String(a)} style={s.metric}><Text style={s.metricValue}>{b}</Text><Text style={s.metricLabel}>{a}</Text></View>)}</View><Text style={s.help}>Local AI usage is tracked at $0.00. Cloud-provider costs become active when real provider credentials and pricing are configured.</Text><ScrollView style={s.list}>{usage.map(u=><View key={u.id} style={s.card}><View style={{flex:1}}><Text style={s.cardTitle}>{u.action} · {u.provider}</Text><Text style={s.cardText}>{u.inputTokens} in / {u.outputTokens} out · {u.durationMs} ms · ${u.estimatedCost.toFixed(6)}</Text></View></View>)}</ScrollView></>}
 </View>;
}
const s=StyleSheet.create({wrap:{gap:9},tabs:{gap:5},tab:{paddingHorizontal:9,paddingVertical:7,borderRadius:14,backgroundColor:"#E2E8F0"},tabOn:{backgroundColor:"#7C3AED"},tabText:{fontSize:9,fontWeight:"800",color:"#334155"},tabTextOn:{color:"#fff"},heading:{fontSize:12,fontWeight:"900",color:"#312E81"},input:{minHeight:62,borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,padding:9,backgroundColor:"#fff",fontSize:11,textAlignVertical:"top"},search:{borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,padding:9,backgroundColor:"#fff",fontSize:11},row:{flexDirection:"row",gap:6},primary:{flex:1,backgroundColor:"#7C3AED",borderRadius:7,paddingVertical:9,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontSize:10,fontWeight:"900"},secondary:{paddingHorizontal:12,backgroundColor:"#EDE9FE",borderRadius:7,justifyContent:"center"},secondaryText:{fontSize:10,fontWeight:"900",color:"#5B21B6"},danger:{paddingHorizontal:12,backgroundColor:"#B91C1C",borderRadius:7,justifyContent:"center"},output:{borderWidth:1,borderColor:"#C4B5FD",backgroundColor:"#F5F3FF",borderRadius:8,padding:9,gap:8},outputText:{fontSize:11,lineHeight:17,color:"#312E81"},chips:{gap:6},chip:{backgroundColor:"#EDE9FE",borderRadius:13,paddingHorizontal:9,paddingVertical:7},chipText:{fontSize:9,fontWeight:"800",color:"#5B21B6"},list:{maxHeight:310},card:{flexDirection:"row",alignItems:"center",gap:8,borderWidth:1,borderColor:"#E2E8F0",backgroundColor:"#fff",borderRadius:8,padding:9,marginBottom:6},cardTitle:{fontSize:10,fontWeight:"900",color:"#1E293B"},cardText:{fontSize:9,lineHeight:14,color:"#64748B",marginTop:2},run:{backgroundColor:"#0F766E",paddingHorizontal:10,paddingVertical:6,borderRadius:6},runText:{fontSize:9,fontWeight:"900",color:"#fff"},metrics:{flexDirection:"row",flexWrap:"wrap",gap:7},metric:{width:"48%",backgroundColor:"#F5F3FF",padding:10,borderRadius:8,alignItems:"center"},metricValue:{fontSize:18,fontWeight:"900",color:"#6D28D9"},metricLabel:{fontSize:8,color:"#64748B"},help:{fontSize:9,lineHeight:14,color:"#64748B"}});
