import { Ionicons } from "@expo/vector-icons";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherProject } from "../../types/publisher";
import { DEFAULT_ANIMATION_EXPORT_SETTINGS, estimateAnimationExport, type AnimationExportFormat, type AnimationExportQuality, type AnimationExportSettings } from "../../utils/animationExportEngine";

type Props = { visible: boolean; project: PublisherProject; settings: AnimationExportSettings; onChange: (settings: AnimationExportSettings) => void; onExport: () => void; onClose: () => void };
const formats: Array<{id:AnimationExportFormat;label:string;detail:string}> = [
  {id:"interactive-html",label:"Interactive HTML",detail:"Self-contained browser presentation"},
  {id:"presentation-zip",label:"Presentation ZIP",detail:"HTML runtime, manifest and project package"},
  {id:"gif",label:"Animated GIF",detail:"Real frame-rendered GIF output"},
  {id:"video",label:"MP4 / Video",detail:"Browser-encoded MP4 or WebM video"},
  {id:"presentation-json",label:"Presentation JSON",detail:"Project, animation and interaction manifest"},
];
const qualities: AnimationExportQuality[] = ["draft","standard","high","ultra"];
const num = (value:string,fallback:number) => Number.isFinite(Number(value)) ? Number(value) : fallback;
export default function AnimationExportModal({visible,project,settings,onChange,onExport,onClose}:Props){
  const estimate=estimateAnimationExport(project,settings);
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.backdrop}><View style={s.modal}>
    <View style={s.header}><View><Text style={s.title}>Animation Export & Certification</Text><Text style={s.sub}>Production hardening, secure export, packaged assets, GIF/video fallback and final certification</Text></View><Pressable onPress={onClose}><Ionicons name="close" size={25} color="#fff"/></Pressable></View>
    <ScrollView contentContainerStyle={s.body}>
      <Text style={s.section}>Export Format</Text><View style={s.grid}>{formats.map(item=><Pressable key={item.id} style={[s.card,settings.format===item.id&&s.cardOn]} onPress={()=>onChange({...settings,format:item.id})}><Text style={s.cardTitle}>{item.label}</Text><Text style={s.cardDetail}>{item.detail}</Text></Pressable>)}</View>
      <Text style={s.section}>Output</Text><View style={s.row}><Text style={s.label}>Title</Text><TextInput style={s.titleInput} value={settings.title} onChangeText={title=>onChange({...settings,title})}/><Text style={s.label}>Width</Text><TextInput style={s.input} value={String(settings.width)} keyboardType="numeric" onChangeText={v=>onChange({...settings,width:Math.max(320,num(v,settings.width))})}/><Text style={s.label}>Height</Text><TextInput style={s.input} value={String(settings.height)} keyboardType="numeric" onChangeText={v=>onChange({...settings,height:Math.max(240,num(v,settings.height))})}/></View>
      <View style={s.row}><Text style={s.label}>FPS</Text>{([12,24,30,60] as const).map(fps=><Pressable key={fps} style={[s.chip,settings.fps===fps&&s.chipOn]} onPress={()=>onChange({...settings,fps})}><Text style={s.chipText}>{fps}</Text></Pressable>)}<Text style={s.label}>Quality</Text>{qualities.map(quality=><Pressable key={quality} style={[s.chip,settings.quality===quality&&s.chipOn]} onPress={()=>onChange({...settings,quality})}><Text style={s.chipText}>{quality}</Text></Pressable>)}</View>
      <Text style={s.section}>Production Controls</Text><View style={s.row}>{(["includeInteractions","includeNavigation","loop","reducedMotionFallback","optimizeAssets","embedProjectData"] as const).map(key=><Pressable key={key} style={[s.toggle,settings[key]&&s.toggleOn]} onPress={()=>onChange({...settings,[key]:!settings[key]})}><Text style={s.toggleText}>{key.replace(/([A-Z])/g," $1")}</Text></Pressable>)}</View>
      <Text style={s.section}>Preflight & Performance</Text><View style={s.stats}><View><Text style={s.stat}>{estimate.score}%</Text><Text style={s.statLabel}>Readiness</Text></View><View><Text style={s.stat}>{estimate.animationCount}</Text><Text style={s.statLabel}>Animations</Text></View><View><Text style={s.stat}>{estimate.interactionCount}</Text><Text style={s.statLabel}>Interactions</Text></View><View><Text style={s.stat}>{estimate.estimatedFrames}</Text><Text style={s.statLabel}>Frames</Text></View><View><Text style={s.stat}>{estimate.estimatedMegabytes} MB</Text><Text style={s.statLabel}>Raw estimate</Text></View></View>
      {estimate.issues.length===0?<Text style={s.good}>No export issues found.</Text>:estimate.issues.map((issue,index)=><View key={`${issue.code}-${index}`} style={[s.issue,issue.severity==="error"&&s.error]}><Text style={s.issueTitle}>{issue.severity.toUpperCase()} · {issue.code}</Text><Text style={s.issueText}>{issue.message}</Text></View>)}
      <View style={s.footer}><Pressable style={s.secondary} onPress={()=>onChange({...DEFAULT_ANIMATION_EXPORT_SETTINGS,title:project.name})}><Text style={s.secondaryText}>Reset</Text></Pressable><Pressable style={[s.primary,!estimate.valid&&s.disabled]} disabled={!estimate.valid} onPress={onExport}><Ionicons name="download-outline" size={17} color="#fff"/><Text style={s.primaryText}>Export {formats.find(item=>item.id===settings.format)?.label}</Text></Pressable></View>
    </ScrollView>
  </View></View></Modal>;
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(2,6,23,.78)",alignItems:"center",justifyContent:"center"},modal:{width:"94%",maxWidth:1120,maxHeight:"92%",backgroundColor:"#0F172A",borderRadius:16,borderWidth:1,borderColor:"#334155",overflow:"hidden"},header:{padding:18,flexDirection:"row",justifyContent:"space-between",alignItems:"center",backgroundColor:"#111827"},title:{color:"#F8FAFC",fontSize:20,fontWeight:"800"},sub:{color:"#94A3B8",fontSize:12,marginTop:3},body:{padding:18,gap:12},section:{color:"#67E8F9",fontSize:13,fontWeight:"800"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{width:230,padding:12,borderRadius:10,backgroundColor:"#1E293B",borderWidth:1,borderColor:"#334155"},cardOn:{borderColor:"#22D3EE",backgroundColor:"#164E63"},cardTitle:{color:"#F8FAFC",fontWeight:"800"},cardDetail:{color:"#94A3B8",fontSize:10,marginTop:4},row:{flexDirection:"row",alignItems:"center",gap:7,flexWrap:"wrap"},label:{color:"#CBD5E1",fontSize:11},input:{width:78,height:32,borderWidth:1,borderColor:"#475569",borderRadius:6,color:"#F8FAFC",paddingHorizontal:7,backgroundColor:"#1E293B"},titleInput:{minWidth:230,height:32,borderWidth:1,borderColor:"#475569",borderRadius:6,color:"#F8FAFC",paddingHorizontal:7,backgroundColor:"#1E293B"},chip:{paddingHorizontal:10,paddingVertical:7,borderRadius:12,backgroundColor:"#334155"},chipOn:{backgroundColor:"#0E7490"},chipText:{color:"#fff",fontSize:9,fontWeight:"800",textTransform:"capitalize"},toggle:{paddingHorizontal:10,paddingVertical:8,borderRadius:7,backgroundColor:"#334155"},toggleOn:{backgroundColor:"#0F766E"},toggleText:{color:"#fff",fontSize:9,fontWeight:"700",textTransform:"capitalize"},stats:{flexDirection:"row",gap:24,flexWrap:"wrap",padding:14,borderRadius:10,backgroundColor:"#111827"},stat:{color:"#F8FAFC",fontWeight:"900",fontSize:17},statLabel:{color:"#94A3B8",fontSize:9},issue:{padding:10,borderRadius:8,backgroundColor:"#1E293B",borderLeftWidth:3,borderLeftColor:"#F59E0B"},error:{borderLeftColor:"#EF4444"},issueTitle:{color:"#E2E8F0",fontSize:9,fontWeight:"900"},issueText:{color:"#CBD5E1",fontSize:10,marginTop:3},good:{padding:12,borderRadius:8,backgroundColor:"#064E3B",color:"#D1FAE5",fontWeight:"800"},footer:{flexDirection:"row",justifyContent:"flex-end",gap:10,marginTop:6},primary:{flexDirection:"row",alignItems:"center",gap:7,paddingHorizontal:16,paddingVertical:10,borderRadius:8,backgroundColor:"#0891B2"},primaryText:{color:"#fff",fontWeight:"900"},secondary:{paddingHorizontal:16,paddingVertical:10,borderRadius:8,backgroundColor:"#334155"},secondaryText:{color:"#fff",fontWeight:"800"},disabled:{opacity:.35}});
