import { Ionicons } from "@expo/vector-icons";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherElement } from "../../types/publisher";
import { CHARACTER_STYLE_PRESETS, clampTypography } from "../../utils/characterTypography";

type Props = { visible: boolean; element: PublisherElement | null; onChange: (updates: Partial<PublisherElement>) => void; onClose: () => void };
function NumberField({ label, value, min, max, onChange }: { label:string; value:number; min:number; max:number; onChange:(value:number)=>void }) {
  return <View style={s.field}><Text style={s.label}>{label}</Text><View style={s.stepper}><Pressable onPress={()=>onChange(clampTypography(value-1,min,max))} style={s.step}><Text style={s.stepText}>−</Text></Pressable><TextInput value={String(value)} keyboardType="numeric" onChangeText={(text)=>onChange(clampTypography(Number(text),min,max))} style={s.input}/><Pressable onPress={()=>onChange(clampTypography(value+1,min,max))} style={s.step}><Text style={s.stepText}>+</Text></Pressable></View></View>;
}
function Toggle({ label, active, onPress }: { label:string; active:boolean; onPress:()=>void }) { return <Pressable onPress={onPress} style={[s.toggle,active&&s.toggleOn]}><Text style={[s.toggleText,active&&s.toggleTextOn]}>{label}</Text></Pressable>; }
export default function CharacterTypographyModal({visible,element,onChange,onClose}:Props){
 if(!element)return null;
 const tracking=element.tracking??element.letterSpacing??0;
 const axis=element.variableFontAxes??{};
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.overlay}><View style={s.card}><View style={s.header}><View><Text style={s.title}>Advanced Character Typography</Text><Text style={s.subtitle}>{element.fontFamily??"Arial"} · {element.fontSize??24} pt</Text></View><Pressable onPress={onClose}><Ionicons name="close" size={22} color="#CBD5E1"/></Pressable></View><ScrollView contentContainerStyle={s.content}>
 <Text style={s.section}>Character spacing</Text><View style={s.row}><NumberField label="Kerning" value={element.kerning??0} min={-10} max={10} onChange={(kerning)=>onChange({kerning})}/><NumberField label="Tracking" value={tracking} min={-10} max={50} onChange={(tracking)=>onChange({tracking,letterSpacing:tracking})}/><NumberField label="Baseline shift" value={element.baselineShift??0} min={-100} max={100} onChange={(baselineShift)=>onChange({baselineShift})}/></View>
 <Text style={s.section}>OpenType and case</Text><View style={s.wrap}><Toggle label="Ligatures" active={element.ligatures!==false} onPress={()=>onChange({ligatures:element.ligatures===false})}/><Toggle label="Small Caps" active={!!element.smallCaps} onPress={()=>onChange({smallCaps:!element.smallCaps})}/><Toggle label="ALL CAPS" active={element.textTransform==="uppercase"} onPress={()=>onChange({textTransform:element.textTransform==="uppercase"?"none":"uppercase"})}/><Toggle label="lowercase" active={element.textTransform==="lowercase"} onPress={()=>onChange({textTransform:element.textTransform==="lowercase"?"none":"lowercase"})}/><Toggle label="Strike" active={!!element.strikethrough} onPress={()=>onChange({strikethrough:!element.strikethrough})}/><Toggle label="Superscript" active={(element.baselineShift??0)>0} onPress={()=>onChange({baselineShift:(element.baselineShift??0)>0?0:Math.round((element.fontSize??24)*.35)})}/><Toggle label="Subscript" active={(element.baselineShift??0)<0} onPress={()=>onChange({baselineShift:(element.baselineShift??0)<0?0:-Math.round((element.fontSize??24)*.25)})}/></View>
 <Text style={s.section}>Underline style</Text><View style={s.wrap}>{(["solid","double","dotted","dashed","wavy"] as const).map(v=><Toggle key={v} label={v} active={(element.underlineStyle??"solid")===v} onPress={()=>onChange({underline:true,underlineStyle:v})}/>)}</View>
 <Text style={s.section}>Variable font axes</Text><View style={s.row}><NumberField label="Weight (wght)" value={axis.wght??Number(element.fontWeight??400)} min={100} max={900} onChange={(v)=>onChange({variableFontAxes:{...axis,wght:v},fontWeight:String(Math.round(v/100)*100) as any})}/><NumberField label="Width (wdth)" value={axis.wdth??100} min={50} max={200} onChange={(v)=>onChange({variableFontAxes:{...axis,wdth:v}})}/><NumberField label="Optical size" value={axis.opsz??element.fontSize??24} min={6} max={144} onChange={(v)=>onChange({variableFontAxes:{...axis,opsz:v}})}/></View>
 <Text style={s.section}>Character styles</Text><View style={s.wrap}>{CHARACTER_STYLE_PRESETS.map(p=><Pressable key={p.id} onPress={()=>onChange({...p.updates,characterStyleId:p.id})} style={[s.preset,element.characterStyleId===p.id&&s.presetOn]}><Text style={s.presetName}>{p.name}</Text><Text style={s.presetMeta}>{p.id}</Text></Pressable>)}</View>
 </ScrollView><View style={s.footer}><Text style={s.preview}>{element.text?.slice(0,60)||"Typography preview"}</Text><Pressable onPress={onClose} style={s.done}><Text style={s.doneText}>Done</Text></Pressable></View></View></View></Modal>;
}
const s=StyleSheet.create({overlay:{flex:1,backgroundColor:"rgba(2,6,23,.76)",alignItems:"center",justifyContent:"center",padding:24},card:{width:"100%",maxWidth:850,maxHeight:"88%",backgroundColor:"#111827",borderRadius:15,borderWidth:1,borderColor:"#334155",overflow:"hidden"},header:{padding:18,flexDirection:"row",justifyContent:"space-between",alignItems:"center",borderBottomWidth:1,borderBottomColor:"#293548"},title:{color:"#F8FAFC",fontSize:18,fontWeight:"900"},subtitle:{color:"#94A3B8",fontSize:11,marginTop:3},content:{padding:18,gap:12},section:{color:"#5EEAD4",fontSize:9,fontWeight:"900",letterSpacing:1,textTransform:"uppercase",marginTop:3},row:{flexDirection:"row",gap:10,flexWrap:"wrap"},wrap:{flexDirection:"row",gap:8,flexWrap:"wrap"},field:{minWidth:180,flex:1},label:{color:"#CBD5E1",fontSize:10,fontWeight:"700",marginBottom:5},stepper:{height:38,flexDirection:"row",borderWidth:1,borderColor:"#334155",borderRadius:8,overflow:"hidden"},step:{width:36,alignItems:"center",justifyContent:"center",backgroundColor:"#1E293B"},stepText:{color:"#F8FAFC",fontSize:18},input:{flex:1,color:"#F8FAFC",textAlign:"center",backgroundColor:"#0F172A",padding:0},toggle:{paddingHorizontal:12,paddingVertical:8,borderRadius:16,backgroundColor:"#1E293B",borderWidth:1,borderColor:"#334155"},toggleOn:{backgroundColor:"#0F766E",borderColor:"#2DD4BF"},toggleText:{color:"#CBD5E1",fontSize:10,fontWeight:"800"},toggleTextOn:{color:"#FFFFFF"},preset:{width:130,padding:12,borderRadius:9,backgroundColor:"#1E293B",borderWidth:1,borderColor:"#334155"},presetOn:{borderColor:"#2DD4BF",backgroundColor:"#134E4A"},presetName:{color:"#F8FAFC",fontSize:12,fontWeight:"900"},presetMeta:{color:"#94A3B8",fontSize:8,marginTop:3},footer:{padding:14,borderTopWidth:1,borderTopColor:"#293548",flexDirection:"row",alignItems:"center",gap:12},preview:{flex:1,color:"#E2E8F0",fontSize:14},done:{backgroundColor:"#E2E8F0",paddingHorizontal:22,paddingVertical:9,borderRadius:8},doneText:{color:"#0F172A",fontWeight:"900"}});
