import { Ionicons } from "@expo/vector-icons";
import { useEffect, useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { checkForDesktopUpdates, DEFAULT_UPDATE_POLICY, desktopUpdaterAvailable, downloadDesktopUpdate, getDesktopUpdateStatus, installDesktopUpdate, setDesktopUpdatePolicy, subscribeToDesktopUpdates, type DesktopUpdatePolicy, type DesktopUpdateStatus, type UpdateChannel } from "../../utils/desktopUpdateEngine";

type Props = { visible: boolean; onClose: () => void };
const channels: UpdateChannel[] = ["stable", "beta", "development"];

export default function DesktopUpdateCenterModal({ visible, onClose }: Props) {
  const [status, setStatus] = useState<DesktopUpdateStatus>({ state: "idle", currentVersion: "-", channel: "stable" });
  const [policy, setPolicy] = useState<DesktopUpdatePolicy>(DEFAULT_UPDATE_POLICY);
  const available = desktopUpdaterAvailable();
  useEffect(() => { if (!visible) return; void getDesktopUpdateStatus().then((next) => { setStatus(next); setPolicy((p) => ({ ...p, channel: next.channel })); }); return subscribeToDesktopUpdates(setStatus); }, [visible]);
  const savePolicy = async (next: DesktopUpdatePolicy) => { setPolicy(next); setStatus(await setDesktopUpdatePolicy(next)); };
  const busy = status.state === "checking" || status.state === "downloading";
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}>
    <View style={styles.backdrop}><View style={styles.card} accessibilityViewIsModal>
      <View style={styles.header}><View><Text style={styles.title}>Desktop Update Center</Text><Text style={styles.subtitle}>Check, download, install, and review Yaposan releases</Text></View><Pressable onPress={onClose} style={styles.iconButton} accessibilityLabel="Close update center"><Ionicons name="close" size={22} color="#172033" /></Pressable></View>
      <ScrollView contentContainerStyle={styles.content}>
        {!available && <View style={styles.notice}><Ionicons name="information-circle" size={22} color="#2354d8" /><Text style={styles.noticeText}>Open the installed desktop application to use automatic updates. Web builds remain unchanged.</Text></View>}
        <View style={styles.summary}><View><Text style={styles.label}>Installed</Text><Text style={styles.value}>{status.currentVersion}</Text></View><View><Text style={styles.label}>Status</Text><Text style={styles.value}>{status.state.replace("-", " ")}</Text></View><View><Text style={styles.label}>Channel</Text><Text style={styles.value}>{status.channel}</Text></View></View>
        {status.availableVersion && <View style={styles.release}><Text style={styles.releaseTitle}>{status.releaseName || `Yaposan ${status.availableVersion}`}</Text><Text style={styles.releaseMeta}>Version {status.availableVersion}</Text>{status.releaseNotes ? <Text style={styles.notes}>{status.releaseNotes}</Text> : null}</View>}
        {status.state === "downloading" && <View><Text style={styles.progressText}>Downloading {Math.round(status.progress ?? 0)}%</Text><View style={styles.track}><View style={[styles.fill, { width: `${Math.max(0, Math.min(100, status.progress ?? 0))}%` }]} /></View></View>}
        {status.error && <View style={styles.error}><Text style={styles.errorText}>{status.error}</Text></View>}
        <Text style={styles.section}>Release channel</Text><View style={styles.channels}>{channels.map((channel) => <Pressable key={channel} disabled={!available} onPress={() => void savePolicy({ ...policy, channel })} style={[styles.channel, policy.channel === channel && styles.channelActive]}><Text style={[styles.channelText, policy.channel === channel && styles.channelTextActive]}>{channel}</Text></Pressable>)}</View>
        <Text style={styles.section}>Update preferences</Text>
        {[["Check automatically", "automaticChecks"], ["Download automatically", "automaticDownload"], ["Install when Yaposan closes", "installOnQuit"]].map(([label, key]) => <View key={key} style={styles.setting}><Text style={styles.settingText}>{label}</Text><Switch disabled={!available} value={Boolean(policy[key as keyof DesktopUpdatePolicy])} onValueChange={(value) => void savePolicy({ ...policy, [key]: value })} /></View>)}
      </ScrollView>
      <View style={styles.footer}><Pressable onPress={onClose} style={styles.secondary}><Text style={styles.secondaryText}>Close</Text></Pressable><Pressable disabled={!available || busy} onPress={() => void checkForDesktopUpdates().then(setStatus)} style={[styles.primary, (!available || busy) && styles.disabled]}>{busy && status.state === "checking" ? <ActivityIndicator color="#fff" /> : <Ionicons name="refresh" size={18} color="#fff" />}<Text style={styles.primaryText}>Check for Updates</Text></Pressable>{status.state === "available" && <Pressable onPress={() => void downloadDesktopUpdate().then(setStatus)} style={styles.primary}><Ionicons name="cloud-download" size={18} color="#fff" /><Text style={styles.primaryText}>Download</Text></Pressable>}{status.state === "downloaded" && <Pressable onPress={() => void installDesktopUpdate()} style={styles.install}><Ionicons name="power" size={18} color="#fff" /><Text style={styles.primaryText}>Restart and Install</Text></Pressable>}</View>
    </View></View>
  </Modal>;
}
const styles=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(10,18,35,0.58)",alignItems:"center",justifyContent:"center",padding:20},card:{width:"100%",maxWidth:820,maxHeight:"90%",backgroundColor:"#fff",borderRadius:18,padding:20},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:16},title:{fontSize:24,fontWeight:"800",color:"#172033"},subtitle:{marginTop:3,color:"#667085"},iconButton:{width:40,height:40,borderRadius:20,alignItems:"center",justifyContent:"center",backgroundColor:"#f2f4f7"},content:{gap:16,paddingVertical:18},notice:{flexDirection:"row",gap:10,padding:13,borderRadius:12,backgroundColor:"#eef4ff"},noticeText:{flex:1,color:"#344054",lineHeight:20},summary:{flexDirection:"row",gap:28,padding:16,borderRadius:14,backgroundColor:"#f8fafc"},label:{fontSize:12,fontWeight:"700",color:"#667085"},value:{marginTop:3,fontSize:18,fontWeight:"900",color:"#172033",textTransform:"capitalize"},release:{borderWidth:1,borderColor:"#d0d5dd",borderRadius:14,padding:15},releaseTitle:{fontSize:17,fontWeight:"800",color:"#172033"},releaseMeta:{marginTop:3,color:"#667085"},notes:{marginTop:10,color:"#475467",lineHeight:20},progressText:{fontWeight:"700",color:"#344054"},track:{height:10,marginTop:8,borderRadius:5,backgroundColor:"#eaecf0",overflow:"hidden"},fill:{height:10,backgroundColor:"#2354d8"},error:{padding:12,borderRadius:10,backgroundColor:"#fef3f2"},errorText:{color:"#b42318"},section:{fontSize:15,fontWeight:"800",color:"#172033"},channels:{flexDirection:"row",gap:8},channel:{paddingHorizontal:14,paddingVertical:9,borderRadius:9,backgroundColor:"#f2f4f7"},channelActive:{backgroundColor:"#2354d8"},channelText:{fontWeight:"700",color:"#475467",textTransform:"capitalize"},channelTextActive:{color:"#fff"},setting:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingVertical:8,borderBottomWidth:1,borderBottomColor:"#eaecf0"},settingText:{fontWeight:"600",color:"#344054"},footer:{flexDirection:"row",justifyContent:"flex-end",gap:10,flexWrap:"wrap"},secondary:{paddingHorizontal:17,paddingVertical:11,borderRadius:10,backgroundColor:"#f2f4f7"},secondaryText:{fontWeight:"700",color:"#344054"},primary:{flexDirection:"row",alignItems:"center",gap:7,paddingHorizontal:17,paddingVertical:11,borderRadius:10,backgroundColor:"#2354d8"},install:{flexDirection:"row",alignItems:"center",gap:7,paddingHorizontal:17,paddingVertical:11,borderRadius:10,backgroundColor:"#087a43"},primaryText:{fontWeight:"800",color:"#fff"},disabled:{opacity:.45}});
