import { Ionicons } from "@expo/vector-icons";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import type { PublisherProject } from "../../types/publisher";
import { createDigitalEditorRuntimeManifest, type DigitalDeviceMode, type DigitalPanelId, type DigitalPreviewMode } from "../../utils/digitalPublishingEditorIntegrationEngine";

type Props = { visible: boolean; project: PublisherProject; onClose: () => void; onChange: (updates: Partial<import("../../utils/digitalPublishingEditorIntegrationEngine").DigitalPublishingEditorState>) => void; onExportReport: () => void; onExportWebsite: () => void };
const devices: DigitalDeviceMode[] = ["desktop", "tablet", "mobile"];
const panels: DigitalPanelId[] = ["overview", "responsive", "navigation", "forms", "analytics", "deployment", "preflight"];
const previews: DigitalPreviewMode[] = ["design", "live", "seo", "social", "accessibility", "performance"];

export function DigitalPublishingStudioModal({ visible, project, onClose, onChange, onExportReport, onExportWebsite }: Props) {
  const manifest = createDigitalEditorRuntimeManifest(project);
  const state = project.digitalPublishingEditor ?? { deviceMode: "desktop", activePanel: "overview", previewMode: "design", previewPageId: project.activePageId };
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.backdrop}><View style={s.modal}>
    <View style={s.header}><View><Text style={s.title}>Digital Publishing Studio</Text><Text style={s.sub}>Full-fidelity responsive runtime, working forms, PWA and deployment certification</Text></View><Pressable onPress={onClose}><Ionicons name="close" size={24} color="#fff"/></Pressable></View>
    <ScrollView contentContainerStyle={s.body}>
      <Text style={s.section}>Device workspace</Text><View style={s.row}>{devices.map((device)=><Pressable key={device} style={[s.chip,state.deviceMode===device&&s.on]} onPress={()=>onChange({deviceMode:device})}><Ionicons name={device==="desktop"?"desktop-outline":device==="tablet"?"tablet-portrait-outline":"phone-portrait-outline"} size={15} color="#fff"/><Text style={s.chipText}>{device}</Text></Pressable>)}</View>
      <Text style={s.section}>Publishing panels</Text><View style={s.row}>{panels.map((panel)=><Pressable key={panel} style={[s.chip,state.activePanel===panel&&s.on]} onPress={()=>onChange({activePanel:panel})}><Text style={s.chipText}>{panel}</Text></Pressable>)}</View>
      <Text style={s.section}>Preview mode</Text><View style={s.row}>{previews.map((mode)=><Pressable key={mode} style={[s.chip,state.previewMode===mode&&s.on]} onPress={()=>onChange({previewMode:mode})}><Text style={s.chipText}>{mode}</Text></Pressable>)}</View>
      <Text style={s.section}>Pages and routes</Text>{manifest.pages.map((page)=><Pressable key={page.id} style={[s.card,state.previewPageId===page.id&&s.cardOn]} onPress={()=>onChange({previewPageId:page.id})}><Text style={s.cardTitle}>{page.name}</Text><Text style={s.muted}>{page.route} · {page.elementCount} objects · {page.width}×{page.height}</Text></Pressable>)}
      <View style={s.preview}><Text style={s.previewTitle}>{manifest.deviceMode.toUpperCase()} LIVE PREVIEW</Text><Text style={s.muted}>{manifest.viewport.width} × {manifest.viewport.height}</Text><Text style={s.previewText}>Runtime executes responsive layouts, navigation, interactions, forms, analytics settings, and deployment preflight from the current project state.</Text></View>
      <View style={s.status}><Ionicons name={manifest.validation.passed?"checkmark-circle":"warning"} size={20} color={manifest.validation.passed?"#34D399":"#FBBF24"}/><Text style={s.statusText}>{manifest.validation.passed?"Production preflight passed":"Production preflight needs attention"} · {manifest.validation.errors} errors · {manifest.validation.warnings} warnings</Text></View>
      <Pressable style={s.primary} onPress={onExportWebsite}><Ionicons name="globe-outline" size={17} color="#fff"/><Text style={s.primaryText}>Export Full-Fidelity Website ZIP</Text></Pressable>
      <Pressable style={s.secondary} onPress={onExportReport}><Ionicons name="document-text-outline" size={17} color="#fff"/><Text style={s.primaryText}>Export Runtime Report</Text></Pressable>
    </ScrollView>
  </View></View></Modal>;
}
export default DigitalPublishingStudioModal;

const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(2,6,23,.78)",alignItems:"center",justifyContent:"center"},modal:{width:"94%",maxWidth:1100,maxHeight:"92%",backgroundColor:"#0F172A",borderRadius:16,borderWidth:1,borderColor:"#334155",overflow:"hidden"},header:{padding:18,backgroundColor:"#111827",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"#F8FAFC",fontSize:20,fontWeight:"800"},sub:{color:"#94A3B8",fontSize:12,marginTop:3},body:{padding:18,gap:12},section:{color:"#5EEAD4",fontSize:13,fontWeight:"800"},row:{flexDirection:"row",gap:8,flexWrap:"wrap"},chip:{flexDirection:"row",gap:6,alignItems:"center",paddingHorizontal:11,paddingVertical:8,borderRadius:8,backgroundColor:"#334155"},on:{backgroundColor:"#0F766E"},chipText:{color:"#fff",fontSize:10,fontWeight:"800",textTransform:"capitalize"},card:{padding:12,borderRadius:9,backgroundColor:"#1E293B",borderWidth:1,borderColor:"transparent"},cardOn:{borderColor:"#2DD4BF"},cardTitle:{color:"#F8FAFC",fontWeight:"800"},muted:{color:"#94A3B8",fontSize:11,marginTop:3},preview:{minHeight:170,borderRadius:12,borderWidth:1,borderStyle:"dashed",borderColor:"#475569",backgroundColor:"#020617",alignItems:"center",justifyContent:"center",padding:20},previewTitle:{color:"#67E8F9",fontSize:16,fontWeight:"900"},previewText:{color:"#CBD5E1",fontSize:12,textAlign:"center",maxWidth:680,marginTop:12,lineHeight:18},status:{flexDirection:"row",gap:8,alignItems:"center",padding:12,borderRadius:9,backgroundColor:"#1E293B"},statusText:{color:"#E2E8F0",fontWeight:"700"},primary:{flexDirection:"row",gap:7,alignItems:"center",justifyContent:"center",padding:12,borderRadius:8,backgroundColor:"#2563EB"},secondary:{flexDirection:"row",gap:7,alignItems:"center",justifyContent:"center",padding:12,borderRadius:8,backgroundColor:"#475569"},primaryText:{color:"#fff",fontWeight:"900"}});
