import { Ionicons } from "@expo/vector-icons";
import React, { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherProject } from "../../types/publisher";
import { buildPageNumberMap, calculateDocumentStatistics, normalizeDocumentFoundation, searchDocument, type DocumentSection, type DocumentViewMode, type PageNumberStyle, type PublicationMetadata } from "../../utils/documentFoundationEngine";

type Props = {
  visible: boolean;
  project: PublisherProject;
  onClose: () => void;
  onAddSection: (name: string) => void;
  onUpdateSection: (sectionId: string, updates: Partial<DocumentSection>) => void;
  onDeleteSection: (sectionId: string) => void;
  onMoveSection: (sectionId: string, direction: -1 | 1) => void;
  onMovePage: (pageId: string, sectionId: string) => void;
  onSettings: (viewMode: DocumentViewMode, metadata: Partial<PublicationMetadata>) => void;
  onNavigate: (pageId: string, elementId?: string) => void;
  onExportReport: () => void;
};

const STYLES: Array<{id:PageNumberStyle;label:string}> = [{id:"arabic",label:"1, 2, 3"},{id:"roman-upper",label:"I, II, III"},{id:"roman-lower",label:"i, ii, iii"},{id:"letters-upper",label:"A, B, C"},{id:"letters-lower",label:"a, b, c"}];
const VIEWS: DocumentViewMode[] = ["single","facing","book","magazine"];

export default function DocumentFoundationModal(props: Props) {
  const project = useMemo(() => normalizeDocumentFoundation(props.project), [props.project]);
  const state = project.documentFoundation!;
  const numbers = useMemo(() => new Map(buildPageNumberMap(project).map(item => [item.pageId,item])), [project]);
  const stats = useMemo(() => calculateDocumentStatistics(project), [project]);
  const [sectionName,setSectionName]=useState("");
  const [query,setQuery]=useState("");
  const results=useMemo(()=>searchDocument(project,query),[project,query]);
  const [tab,setTab]=useState<"navigator"|"metadata"|"statistics">("navigator");
  return <Modal visible={props.visible} transparent animationType="fade" onRequestClose={props.onClose}><View style={styles.backdrop}><View style={styles.modal}>
    <View style={styles.header}><View><Text style={styles.title}>Professional Document Foundation</Text><Text style={styles.subtitle}>Sections, chapters, page numbering, facing pages, metadata, navigation, and publication statistics</Text></View><Pressable onPress={props.onClose} style={styles.close}><Ionicons name="close" size={22}/></Pressable></View>
    <View style={styles.tabs}>{(["navigator","metadata","statistics"] as const).map(item=><Pressable key={item} onPress={()=>setTab(item)} style={[styles.tab,tab===item&&styles.tabOn]}><Text style={[styles.tabText,tab===item&&styles.tabTextOn]}>{item[0].toUpperCase()+item.slice(1)}</Text></Pressable>)}</View>
    <ScrollView contentContainerStyle={styles.content}>
      {tab==="navigator"?<>
        <View style={styles.card}><Text style={styles.heading}>Document view</Text><View style={styles.row}>{VIEWS.map(view=><Pressable key={view} onPress={()=>props.onSettings(view,{})} style={[styles.chip,state.viewMode===view&&styles.chipOn]}><Text style={styles.chipText}>{view}</Text></Pressable>)}</View></View>
        <View style={styles.card}><Text style={styles.heading}>Search publication</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search sections, pages, objects, or text" style={styles.input}/>{results.map(result=><Pressable key={result.id} onPress={()=>result.pageId&&props.onNavigate(result.pageId,result.elementId)} style={styles.result}><Ionicons name={result.kind==="section"?"bookmark-outline":result.kind==="page"?"document-outline":"search-outline"} size={17}/><Text style={styles.resultText}>{result.label}</Text><Text style={styles.meta}>{result.kind}</Text></Pressable>)}</View>
        <View style={styles.card}><Text style={styles.heading}>Add section or chapter</Text><View style={styles.row}><TextInput value={sectionName} onChangeText={setSectionName} placeholder="Section name" style={[styles.input,{flex:1,marginTop:0}]}/><Pressable onPress={()=>{props.onAddSection(sectionName);setSectionName("");}} style={styles.primary}><Text style={styles.primaryText}>Add section</Text></Pressable></View></View>
        {state.sections.map((section,index)=><View key={section.id} style={[styles.card,{borderLeftColor:section.color,borderLeftWidth:6}]}>
          <View style={styles.sectionHead}><View style={{flex:1}}><TextInput value={section.name} onChangeText={name=>props.onUpdateSection(section.id,{name})} style={styles.sectionName}/><Text style={styles.meta}>{section.pageIds.length} pages · {section.numbering.prefix}{STYLES.find(s=>s.id===section.numbering.style)?.label}</Text></View><Pressable onPress={()=>props.onMoveSection(section.id,-1)} disabled={index===0} style={styles.icon}><Ionicons name="arrow-up" size={17}/></Pressable><Pressable onPress={()=>props.onMoveSection(section.id,1)} disabled={index===state.sections.length-1} style={styles.icon}><Ionicons name="arrow-down" size={17}/></Pressable><Pressable onPress={()=>props.onUpdateSection(section.id,{locked:!section.locked})} style={styles.icon}><Ionicons name={section.locked?"lock-closed":"lock-open-outline"} size={17}/></Pressable><Pressable onPress={()=>props.onDeleteSection(section.id)} style={styles.danger}><Ionicons name="trash-outline" size={17}/></Pressable></View>
          <View style={styles.row}>{STYLES.map(item=><Pressable key={item.id} onPress={()=>props.onUpdateSection(section.id,{numbering:{...section.numbering,style:item.id}})} style={[styles.smallChip,section.numbering.style===item.id&&styles.chipOn]}><Text style={styles.smallText}>{item.label}</Text></Pressable>)}</View>
          <View style={styles.row}><TextInput value={section.numbering.prefix} onChangeText={prefix=>props.onUpdateSection(section.id,{numbering:{...section.numbering,prefix}})} placeholder="Prefix" style={styles.smallInput}/><TextInput value={String(section.numbering.startAt)} onChangeText={value=>props.onUpdateSection(section.id,{numbering:{...section.numbering,startAt:Math.max(1,Number(value)||1),continueFromPrevious:false}})} keyboardType="number-pad" style={styles.smallInput}/><Pressable onPress={()=>props.onUpdateSection(section.id,{numbering:{...section.numbering,continueFromPrevious:!section.numbering.continueFromPrevious}})} style={[styles.chip,section.numbering.continueFromPrevious&&styles.chipOn]}><Text style={styles.chipText}>Continue numbering</Text></Pressable></View>
          {section.pageIds.map(pageId=>{const page=project.pages.find(p=>p.id===pageId);const number=numbers.get(pageId);return <View key={pageId} style={styles.pageRow}><Pressable onPress={()=>props.onNavigate(pageId)} style={{flex:1}}><Text style={styles.pageTitle}>{number?.display} · {page?.name??"Untitled page"}</Text><Text style={styles.meta}>{number?.side} page · {page?.orientation} · {page?.sizeKey}</Text></Pressable><View style={styles.pageMoves}>{state.sections.filter(s=>s.id!==section.id).slice(0,3).map(target=><Pressable key={target.id} onPress={()=>props.onMovePage(pageId,target.id)} style={styles.moveChip}><Text style={styles.moveText}>To {target.name}</Text></Pressable>)}</View></View>})}
        </View>)}
      </>:null}
      {tab==="metadata"?<View style={styles.card}><Text style={styles.heading}>Publication metadata</Text>{(["title","author","company","subject","description","language","publisher","copyright","license"] as const).map(key=><View key={key}><Text style={styles.label}>{key}</Text><TextInput value={String(state.metadata[key]??"")} onChangeText={value=>props.onSettings(state.viewMode,{[key]:value})} multiline={key==="description"} style={styles.input}/></View>)}<Text style={styles.label}>Keywords</Text><TextInput value={state.metadata.keywords.join(", ")} onChangeText={value=>props.onSettings(state.viewMode,{keywords:value.split(",").map(v=>v.trim()).filter(Boolean)})} style={styles.input}/><Text style={styles.label}>Revision</Text><TextInput value={String(state.metadata.revision)} onChangeText={value=>props.onSettings(state.viewMode,{revision:Math.max(1,Number(value)||1)})} keyboardType="number-pad" style={styles.input}/></View>:null}
      {tab==="statistics"?<><View style={styles.metrics}>{Object.entries(stats).map(([key,value])=><View key={key} style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.meta}>{key}</Text></View>)}</View><View style={styles.card}><Text style={styles.heading}>Production report</Text><Text style={styles.body}>The report includes document structure, formatted page numbers, metadata, statistics, and document migration information.</Text><Pressable onPress={props.onExportReport} style={[styles.primary,{alignSelf:"flex-start",marginTop:12}]}><Text style={styles.primaryText}>Export document report</Text></Pressable></View></>:null}
    </ScrollView>
  </View></View></Modal>;
}

const styles=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(15,23,42,.65)",alignItems:"center",justifyContent:"center",padding:20},modal:{width:"96%",maxWidth:1120,height:"91%",backgroundColor:"#f8fafc",borderRadius:18,overflow:"hidden"},header:{backgroundColor:"#312e81",padding:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"white",fontSize:22,fontWeight:"900"},subtitle:{color:"#c7d2fe",marginTop:4},close:{backgroundColor:"white",padding:7,borderRadius:9},tabs:{flexDirection:"row",backgroundColor:"#e0e7ff",padding:8,gap:8},tab:{paddingHorizontal:16,paddingVertical:9,borderRadius:9},tabOn:{backgroundColor:"#4338ca"},tabText:{fontWeight:"800",color:"#3730a3"},tabTextOn:{color:"white"},content:{padding:16,gap:12},card:{backgroundColor:"white",borderWidth:1,borderColor:"#e2e8f0",borderRadius:14,padding:15},heading:{fontSize:16,fontWeight:"900",color:"#0f172a"},body:{color:"#475569",marginTop:6},row:{flexDirection:"row",gap:8,flexWrap:"wrap",alignItems:"center",marginTop:10},input:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:9,padding:10,backgroundColor:"#f8fafc",marginTop:6},primary:{backgroundColor:"#4338ca",paddingHorizontal:14,paddingVertical:10,borderRadius:9},primaryText:{color:"white",fontWeight:"800"},chip:{backgroundColor:"#e2e8f0",paddingHorizontal:12,paddingVertical:8,borderRadius:20},chipOn:{backgroundColor:"#c7d2fe"},chipText:{fontWeight:"700",textTransform:"capitalize"},sectionHead:{flexDirection:"row",gap:8,alignItems:"center"},sectionName:{fontSize:17,fontWeight:"900",color:"#0f172a",paddingVertical:3},icon:{padding:8,backgroundColor:"#e2e8f0",borderRadius:8},danger:{padding:8,backgroundColor:"#fee2e2",borderRadius:8},smallChip:{backgroundColor:"#f1f5f9",paddingHorizontal:8,paddingVertical:6,borderRadius:12},smallText:{fontSize:11,fontWeight:"700"},smallInput:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:8,padding:8,minWidth:75},pageRow:{flexDirection:"row",alignItems:"center",paddingVertical:10,borderTopWidth:1,borderTopColor:"#e2e8f0",marginTop:8,gap:10},pageTitle:{fontWeight:"800",color:"#1e293b"},pageMoves:{flexDirection:"row",gap:5,flexWrap:"wrap",justifyContent:"flex-end"},moveChip:{backgroundColor:"#eef2ff",padding:6,borderRadius:8},moveText:{fontSize:10,fontWeight:"700",color:"#3730a3"},meta:{fontSize:12,color:"#64748b",marginTop:3},result:{flexDirection:"row",gap:8,alignItems:"center",paddingVertical:9,borderBottomWidth:1,borderBottomColor:"#e2e8f0"},resultText:{flex:1,fontWeight:"700"},label:{fontSize:12,fontWeight:"800",color:"#475569",textTransform:"capitalize",marginTop:12},metrics:{flexDirection:"row",gap:10,flexWrap:"wrap"},metric:{backgroundColor:"white",borderWidth:1,borderColor:"#c7d2fe",padding:14,borderRadius:12,minWidth:140},metricValue:{fontSize:22,fontWeight:"900",color:"#3730a3"}});
