import { Ionicons } from "@expo/vector-icons";
import React,{useMemo,useState} from "react";
import {Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import type {PublisherProject} from "../../types/publisher";
import {buildIndex,buildTableOfContents,normalizeDocumentReferences,resolveCrossReference,validateDocumentReferences,type NoteKind} from "../../utils/documentReferenceEngine";

type Props={visible:boolean;project:PublisherProject;activePageId:string;selectedElementId?:string;onClose:()=>void;onBookmark:(name:string)=>void;onDeleteBookmark:(id:string)=>void;onNote:(kind:NoteKind,text:string)=>void;onDeleteNote:(id:string)=>void;onIndex:(term:string,subterm?:string)=>void;onDeleteIndex:(id:string)=>void;onCrossReference:(label:string,targetKind:"page"|"section"|"bookmark"|"element"|"url",targetId:string)=>void;onDeleteCrossReference:(id:string)=>void;onNavigate:(pageId:string,elementId?:string)=>void;onExport:()=>void};
export default function DocumentReferencesModal(p:Props){const project=useMemo(()=>normalizeDocumentReferences(p.project),[p.project]),state=project.documentReferences!,toc=buildTableOfContents(project),index=buildIndex(project),issues=validateDocumentReferences(project);const[name,setName]=useState("");const[note,setNote]=useState("");const[term,setTerm]=useState("");const[subterm,setSubterm]=useState("");const[label,setLabel]=useState("");const[url,setUrl]=useState("");return <Modal visible={p.visible} transparent animationType="fade" onRequestClose={p.onClose}><View style={css.back}><View style={css.modal}><View style={css.head}><View><Text style={css.title}>References & Navigation</Text><Text style={css.sub}>TOC, index, bookmarks, notes, cross-references, and hyperlinks</Text></View><Pressable onPress={p.onClose} style={css.close}><Ionicons name="close" size={21}/></Pressable></View><ScrollView contentContainerStyle={css.body}>
<View style={css.metrics}><Metric label="TOC" value={toc.length}/><Metric label="Bookmarks" value={state.bookmarks.length}/><Metric label="Notes" value={state.notes.length}/><Metric label="Index" value={state.indexEntries.length}/><Metric label="Issues" value={issues.length}/></View>
<View style={css.card}><Text style={css.h}>Table of Contents</Text>{toc.length?toc.map(x=><Pressable key={x.id} onPress={()=>p.onNavigate(x.pageId,x.elementId)} style={[css.item,{paddingLeft:10+x.level*14}]}><Text style={css.itemText}>{x.title}</Text><Text style={css.page}>{x.pageNumber}</Text></Pressable>):<Text style={css.meta}>Add sections or apply Heading 1–3 styles to text.</Text>}</View>
<View style={css.card}><Text style={css.h}>Bookmarks</Text><View style={css.row}><TextInput value={name} onChangeText={setName} placeholder="Bookmark name" style={[css.input,{flex:1}]}/><Pressable onPress={()=>{p.onBookmark(name);setName("");}} style={css.primary}><Text style={css.primaryText}>Add at selection</Text></Pressable></View>{state.bookmarks.map(b=><View key={b.id} style={css.item}><Pressable style={{flex:1}} onPress={()=>p.onNavigate(b.pageId,b.elementId)}><Text style={css.itemText}>{b.name}</Text><Text style={css.meta}>{b.elementId?"Selected object":"Page bookmark"}</Text></Pressable><Pressable onPress={()=>p.onDeleteBookmark(b.id)}><Ionicons name="trash-outline" size={18}/></Pressable></View>)}</View>
<View style={css.card}><Text style={css.h}>Footnotes & Endnotes</Text><TextInput value={note} onChangeText={setNote} placeholder="Note text" multiline style={[css.input,{minHeight:58}]}/><View style={css.row}><Pressable onPress={()=>{p.onNote("footnote",note);setNote("");}} style={css.primary}><Text style={css.primaryText}>Add footnote</Text></Pressable><Pressable onPress={()=>{p.onNote("endnote",note);setNote("");}} style={css.secondary}><Text>Add endnote</Text></Pressable></View>{state.notes.map(n=><View key={n.id} style={css.item}><Text style={css.marker}>{n.marker}</Text><Pressable style={{flex:1}} onPress={()=>p.onNavigate(n.pageId,n.elementId)}><Text style={css.itemText}>{n.text}</Text><Text style={css.meta}>{n.kind}</Text></Pressable><Pressable onPress={()=>p.onDeleteNote(n.id)}><Ionicons name="trash-outline" size={18}/></Pressable></View>)}</View>
<View style={css.card}><Text style={css.h}>Index</Text><View style={css.row}><TextInput value={term} onChangeText={setTerm} placeholder="Term" style={[css.input,{flex:1}]}/><TextInput value={subterm} onChangeText={setSubterm} placeholder="Subterm" style={[css.input,{flex:1}]}/><Pressable onPress={()=>{p.onIndex(term,subterm);setTerm("");setSubterm("");}} style={css.primary}><Text style={css.primaryText}>Mark</Text></Pressable></View>{index.map(e=><View key={e.id} style={css.item}><Text style={[css.itemText,{flex:1}]}>{e.term}{e.subterm?` — ${e.subterm}`:""}</Text><Text style={css.page}>{e.pageNumbers.join(", ")}</Text><Pressable onPress={()=>p.onDeleteIndex(e.id)}><Ionicons name="trash-outline" size={18}/></Pressable></View>)}</View>
<View style={css.card}><Text style={css.h}>Cross-reference / Hyperlink</Text><View style={css.row}><TextInput value={label} onChangeText={setLabel} placeholder="Label" style={[css.input,{flex:1}]}/><TextInput value={url} onChangeText={setUrl} placeholder="https://… or mailto:…" style={[css.input,{flex:2}]}/><Pressable onPress={()=>{p.onCrossReference(label,"url",url);setLabel("");setUrl("");}} style={css.primary}><Text style={css.primaryText}>Add link</Text></Pressable></View>{state.crossReferences.map(r=><View key={r.id} style={css.item}><View style={{flex:1}}><Text style={css.itemText}>{r.label}</Text><Text style={css.meta}>{r.targetKind}: {resolveCrossReference(project,r.id)}</Text></View><Pressable onPress={()=>p.onDeleteCrossReference(r.id)}><Ionicons name="trash-outline" size={18}/></Pressable></View>)}</View>
{issues.length>0&&<View style={css.card}><Text style={css.h}>Validation</Text>{issues.map(i=><Text key={i.id} style={css.issue}>• {i.message}</Text>)}</View>}
<Pressable onPress={p.onExport} style={css.export}><Ionicons name="download-outline" size={18} color="white"/><Text style={css.primaryText}>Export reference report</Text></Pressable>
</ScrollView></View></View></Modal>}
function Metric({label,value}:{label:string;value:number}){return <View style={css.metric}><Text style={css.metricValue}>{value}</Text><Text style={css.meta}>{label}</Text></View>}
const css=StyleSheet.create({back:{flex:1,backgroundColor:"rgba(15,23,42,.68)",alignItems:"center",justifyContent:"center",padding:20},modal:{width:"95%",maxWidth:1120,height:"92%",backgroundColor:"#f8fafc",borderRadius:18,overflow:"hidden"},head:{backgroundColor:"#4338ca",padding:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"white",fontSize:22,fontWeight:"900"},sub:{color:"#e0e7ff",marginTop:4},close:{backgroundColor:"white",padding:7,borderRadius:9},body:{padding:16,gap:12},metrics:{flexDirection:"row",gap:10,flexWrap:"wrap"},metric:{backgroundColor:"white",borderWidth:1,borderColor:"#c7d2fe",borderRadius:12,padding:12,minWidth:105},metricValue:{fontSize:22,fontWeight:"900",color:"#3730a3"},card:{backgroundColor:"white",borderWidth:1,borderColor:"#dbeafe",borderRadius:14,padding:15,gap:9},h:{fontSize:16,fontWeight:"900"},row:{flexDirection:"row",gap:8,alignItems:"center",flexWrap:"wrap"},input:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:9,paddingHorizontal:10,paddingVertical:8,backgroundColor:"white"},primary:{backgroundColor:"#4338ca",paddingHorizontal:13,paddingVertical:9,borderRadius:9},primaryText:{color:"white",fontWeight:"900"},secondary:{borderWidth:1,borderColor:"#94a3b8",paddingHorizontal:12,paddingVertical:8,borderRadius:9},item:{flexDirection:"row",gap:10,alignItems:"center",borderTopWidth:1,borderTopColor:"#eef2ff",paddingVertical:9},itemText:{fontWeight:"800",color:"#1e1b4b"},page:{fontWeight:"900",color:"#4338ca"},meta:{color:"#64748b",fontSize:12},marker:{fontWeight:"900",color:"#4338ca",minWidth:24},issue:{color:"#b91c1c"},export:{backgroundColor:"#312e81",padding:13,borderRadius:10,flexDirection:"row",gap:8,alignItems:"center",justifyContent:"center"}});
