import { Ionicons } from "@expo/vector-icons";
import React,{useMemo,useState} from "react";
import {Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import type {PublisherProject} from "../../types/publisher";
import {normalizeDocumentVariables,renderRunningContent,validateDocumentVariables,type RunningContentRule} from "../../utils/documentVariableEngine";

type Props={visible:boolean;project:PublisherProject;activePageId:string;selectedElementIds:string[];onClose:()=>void;onAddVariable:(name:string,value:string)=>void;onUpdateVariable:(id:string,value:string)=>void;onDeleteVariable:(id:string)=>void;onInsert:(token:string)=>void;onAddRule:(input:Omit<RunningContentRule,"id"|"createdAt"|"updatedAt">)=>void;onToggleRule:(id:string,enabled:boolean)=>void;onDeleteRule:(id:string)=>void;onResolveSelection:()=>void;onExport:()=>void};
export default function DocumentVariablesModal(p:Props){const project=useMemo(()=>normalizeDocumentVariables(p.project),[p.project]),state=project.documentVariables!,issues=validateDocumentVariables(project),preview=renderRunningContent(project,p.activePageId);const[name,setName]=useState("");const[value,setValue]=useState("");const[ruleName,setRuleName]=useState("");const[template,setTemplate]=useState("{{document.title}} — {{page.number}}");return <Modal visible={p.visible} transparent animationType="fade" onRequestClose={p.onClose}><View style={css.back}><View style={css.modal}><View style={css.head}><View><Text style={css.title}>Variables & Smart Content</Text><Text style={css.sub}>Dynamic fields, running headers, running footers, and document automation</Text></View><Pressable onPress={p.onClose} style={css.close}><Ionicons name="close" size={21}/></Pressable></View><ScrollView contentContainerStyle={css.body}>
<View style={css.metrics}><Metric label="Variables" value={state.variables.length}/><Metric label="Custom" value={state.variables.filter(v=>v.kind==="custom").length}/><Metric label="Running rules" value={state.runningContent.length}/><Metric label="Issues" value={issues.length}/></View>
<View style={css.card}><Text style={css.h}>Smart variables</Text><Text style={css.meta}>Insert a token into selected text. It resolves from document metadata, page numbering, section structure, dates, or custom data.</Text>{state.variables.map(v=><View key={v.id} style={css.item}><View style={{flex:1}}><Text style={css.itemText}>{v.name}</Text><Text style={css.token}>{v.token}</Text>{v.kind==="custom"&&<TextInput defaultValue={v.value} onEndEditing={e=>p.onUpdateVariable(v.id,e.nativeEvent.text)} style={css.smallInput}/>}</View><Pressable onPress={()=>p.onInsert(v.token)} style={css.secondary}><Text>Insert</Text></Pressable>{v.kind==="custom"&&<Pressable onPress={()=>p.onDeleteVariable(v.id)}><Ionicons name="trash-outline" size={18}/></Pressable>}</View>)}</View>
<View style={css.card}><Text style={css.h}>Custom variable</Text><View style={css.row}><TextInput value={name} onChangeText={setName} placeholder="Variable name" style={[css.input,{flex:1}]}/><TextInput value={value} onChangeText={setValue} placeholder="Value" style={[css.input,{flex:2}]}/><Pressable onPress={()=>{p.onAddVariable(name,value);setName("");setValue("");}} style={css.primary}><Text style={css.primaryText}>Add variable</Text></Pressable></View></View>
<View style={css.card}><Text style={css.h}>Running headers and footers</Text><View style={css.row}><TextInput value={ruleName} onChangeText={setRuleName} placeholder="Rule name" style={[css.input,{flex:1}]}/><TextInput value={template} onChangeText={setTemplate} placeholder="Template" style={[css.input,{flex:2}]}/><Pressable onPress={()=>{p.onAddRule({name:ruleName.trim()||"Running Header",position:"header",scope:"document",leftTemplate:template,rightTemplate:template,enabled:true});setRuleName("");}} style={css.primary}><Text style={css.primaryText}>Add header</Text></Pressable><Pressable onPress={()=>{p.onAddRule({name:ruleName.trim()||"Running Footer",position:"footer",scope:"document",leftTemplate:template,rightTemplate:template,enabled:true});setRuleName("");}} style={css.secondary}><Text>Add footer</Text></Pressable></View>{state.runningContent.map(r=><View key={r.id} style={css.item}><View style={{flex:1}}><Text style={css.itemText}>{r.name}</Text><Text style={css.meta}>{r.position} · {r.scope}</Text><Text style={css.token}>{r.rightTemplate}</Text></View><Pressable onPress={()=>p.onToggleRule(r.id,!r.enabled)} style={css.secondary}><Text>{r.enabled?"Disable":"Enable"}</Text></Pressable><Pressable onPress={()=>p.onDeleteRule(r.id)}><Ionicons name="trash-outline" size={18}/></Pressable></View>)}</View>
<View style={css.card}><Text style={css.h}>Active page preview</Text><Text style={css.preview}>Header: {preview.header||"—"}</Text><Text style={css.preview}>Footer: {preview.footer||"—"}</Text><Pressable disabled={!p.selectedElementIds.length} onPress={p.onResolveSelection} style={[css.primary,!p.selectedElementIds.length&&{opacity:.45}]}><Text style={css.primaryText}>Resolve smart content in selection</Text></Pressable></View>
{issues.length>0&&<View style={css.card}><Text style={css.h}>Validation</Text>{issues.map(i=><Text key={i.id} style={css.issue}>• {i.message}</Text>)}</View>}
<Pressable onPress={p.onExport} style={css.export}><Ionicons name="download-outline" size={18} color="white"/><Text style={css.primaryText}>Export smart-content report</Text></Pressable>
</ScrollView></View></View></Modal>}
function Metric({label,value}:{label:string;value:number}){return <View style={css.metric}><Text style={css.metricValue}>{value}</Text><Text style={css.meta}>{label}</Text></View>}
const css=StyleSheet.create({back:{flex:1,backgroundColor:"rgba(15,23,42,.68)",alignItems:"center",justifyContent:"center",padding:20},modal:{width:"95%",maxWidth:1120,height:"92%",backgroundColor:"#f8fafc",borderRadius:18,overflow:"hidden"},head:{backgroundColor:"#0f766e",padding:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"white",fontSize:22,fontWeight:"900"},sub:{color:"#ccfbf1",marginTop:4},close:{backgroundColor:"white",padding:7,borderRadius:9},body:{padding:16,gap:12},metrics:{flexDirection:"row",gap:10,flexWrap:"wrap"},metric:{backgroundColor:"white",borderWidth:1,borderColor:"#99f6e4",borderRadius:12,padding:12,minWidth:110},metricValue:{fontSize:22,fontWeight:"900",color:"#0f766e"},card:{backgroundColor:"white",borderWidth:1,borderColor:"#ccfbf1",borderRadius:14,padding:15,gap:9},h:{fontSize:16,fontWeight:"900"},row:{flexDirection:"row",gap:8,alignItems:"center",flexWrap:"wrap"},input:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:9,paddingHorizontal:10,paddingVertical:8,backgroundColor:"white"},smallInput:{borderWidth:1,borderColor:"#d1fae5",borderRadius:7,paddingHorizontal:8,paddingVertical:5,marginTop:5},primary:{backgroundColor:"#0f766e",paddingHorizontal:13,paddingVertical:9,borderRadius:9,alignSelf:"flex-start"},primaryText:{color:"white",fontWeight:"900"},secondary:{borderWidth:1,borderColor:"#5eead4",paddingHorizontal:12,paddingVertical:8,borderRadius:9},item:{flexDirection:"row",gap:10,alignItems:"center",borderTopWidth:1,borderTopColor:"#ecfdf5",paddingVertical:9},itemText:{fontWeight:"800",color:"#134e4a"},token:{fontFamily:"monospace",color:"#0f766e",fontSize:12},meta:{color:"#64748b",fontSize:12},preview:{fontWeight:"700",color:"#134e4a"},issue:{color:"#b91c1c"},export:{backgroundColor:"#115e59",padding:13,borderRadius:10,flexDirection:"row",gap:8,alignItems:"center",justifyContent:"center"}});
