import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AI_PROVIDERS, analyzeAdvancedDocument, buildImagePrompt, contentLibrary, generatePublication, suggestLayouts, type AiDocumentType, type ImagePromptPlatform } from "../../services/enterpriseAiService";
import type { PublisherProject } from "../../types/publisher";

const DOCS:AiDocumentType[]=["Flyer","Poster","Brochure","Newsletter","Resume","Cover Letter","Business Card","Certificate","Church Bulletin","Church Program","Event Program","Restaurant Menu","Product Catalog","Company Profile","Book Cover","Magazine Cover","Invitation","Price List"];
const CONTENT=["Quotes","Bible verses","Testimonials","FAQs","Product features","Timelines","Agendas","Announcements","Event schedules","Hashtags","Slogans"];
const PLATFORMS:ImagePromptPlatform[]=["DALL-E","Midjourney","Stable Diffusion","Adobe Firefly","Flux"];
type Area="Documents"|"Analysis"|"Layout"|"Content"|"Images"|"Providers";
type Props={project:PublisherProject;onApplyProject:(project:PublisherProject)=>void;onInsertText:(text:string)=>void;onSelectIssue:(pageId:string,elementId?:string)=>void};
export default function EnterpriseAiPanel({project,onApplyProject,onInsertText,onSelectIssue}:Props){
 const[area,setArea]=useState<Area>("Documents"),[topic,setTopic]=useState(""),[docType,setDocType]=useState<AiDocumentType>("Flyer"),[contentType,setContentType]=useState("Quotes"),[platform,setPlatform]=useState<ImagePromptPlatform>("DALL-E"),[style,setStyle]=useState("clean editorial photography"),[output,setOutput]=useState("");
 const metrics=useMemo(()=>analyzeAdvancedDocument(project),[project]);const layouts=useMemo(()=>suggestLayouts(project),[project]);
 return <View style={s.wrap}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{(["Documents","Analysis","Layout","Content","Images","Providers"] as Area[]).map(x=><Pressable key={x} onPress={()=>setArea(x)} style={[s.tab,area===x&&s.tabOn]}><Text style={[s.tabText,area===x&&s.tabTextOn]}>{x}</Text></Pressable>)}</ScrollView>
 {area==="Documents"&&<><Text style={s.heading}>AI Document Generator</Text><TextInput value={topic} onChangeText={setTopic} placeholder="Describe the publication topic and audience" multiline style={s.input}/><ScrollView horizontal contentContainerStyle={s.chips}>{DOCS.map(x=><Pressable key={x} onPress={()=>setDocType(x)} style={[s.chip,docType===x&&s.chipOn]}><Text style={s.chipText}>{x}</Text></Pressable>)}</ScrollView><Pressable style={s.primary} onPress={()=>onApplyProject(generatePublication(project,docType,topic))}><Ionicons name="albums-outline" size={17} color="#fff"/><Text style={s.primaryText}>Create editable {docType}</Text></Pressable><Text style={s.help}>Adds a native editable page with text, shapes, typography, colors, and call-to-action content.</Text></>}
 {area==="Analysis"&&<><Text style={s.heading}>Advanced Document Intelligence</Text><View style={s.grid}>{[["Readability",`${metrics.readability}/100`],["Grade level",String(metrics.gradeLevel)],["Words",String(metrics.words)],["Style",metrics.style],["Passive",String(metrics.passiveSentences)],["Long paragraphs",String(metrics.longParagraphs)]].map(([a,b])=><View key={a} style={s.metric}><Text style={s.metricValue}>{b}</Text><Text style={s.metricLabel}>{a}</Text></View>)}</View><Text style={s.summary}>{metrics.summary}</Text>{metrics.repeatedWords.length>0&&<Text style={s.help}>Repeated words: {metrics.repeatedWords.join(", ")}</Text>}{metrics.headings===0&&<Text style={s.warning}>No strong heading detected. Add a text object of at least 28px.</Text>}</>}
 {area==="Layout"&&<><Text style={s.heading}>AI Layout Assistant</Text><ScrollView style={{maxHeight:350}}>{layouts.length?layouts.map(x=><Pressable key={x.id} onPress={()=>onSelectIssue(x.pageId,x.elementId)} style={s.card}><Ionicons name="grid-outline" size={18} color="#0F766E"/><View style={{flex:1}}><Text style={s.cardTitle}>{x.title}</Text><Text style={s.cardText}>{x.detail}</Text></View></Pressable>):<Text style={s.success}>No major layout suggestions detected.</Text>}</ScrollView></>}
 {area==="Content"&&<><Text style={s.heading}>AI Content Library</Text><TextInput value={topic} onChangeText={setTopic} placeholder="Topic, event, product, or organization" style={s.input}/><ScrollView horizontal contentContainerStyle={s.chips}>{CONTENT.map(x=><Pressable key={x} onPress={()=>setContentType(x)} style={[s.chip,contentType===x&&s.chipOn]}><Text style={s.chipText}>{x}</Text></Pressable>)}</ScrollView><Pressable style={s.primary} onPress={()=>setOutput(contentLibrary(contentType,topic))}><Text style={s.primaryText}>Generate {contentType}</Text></Pressable></>}
 {area==="Images"&&<><Text style={s.heading}>AI Image Prompt Builder</Text><TextInput value={topic} onChangeText={setTopic} placeholder="Describe the image subject" multiline style={s.input}/><TextInput value={style} onChangeText={setStyle} placeholder="Visual style" style={s.input}/><ScrollView horizontal contentContainerStyle={s.chips}>{PLATFORMS.map(x=><Pressable key={x} onPress={()=>setPlatform(x)} style={[s.chip,platform===x&&s.chipOn]}><Text style={s.chipText}>{x}</Text></Pressable>)}</ScrollView><Pressable style={s.primary} onPress={()=>setOutput(buildImagePrompt(platform,topic,style))}><Text style={s.primaryText}>Build {platform} prompt</Text></Pressable></>}
 {area==="Providers"&&<><Text style={s.heading}>AI Provider Manager</Text>{AI_PROVIDERS.map(x=><View key={x.id} style={s.card}><Ionicons name={x.local?"desktop-outline":"cloud-outline"} size={18} color="#0F766E"/><View style={{flex:1}}><Text style={s.cardTitle}>{x.label}</Text><Text style={s.cardText}>{x.model} · {x.local?"Local/offline capable":"Cloud provider"}</Text></View><Text style={x.enabled?s.ready:s.setup}>{x.enabled?"Ready":"Setup"}</Text></View>)}<Text style={s.help}>Cloud providers remain disabled until credentials and an endpoint are configured. The Yaposan Local engine works without an API key.</Text></>}
 {!!output&&<View style={s.output}><Text selectable style={s.outputText}>{output}</Text><Pressable style={s.primary} onPress={()=>onInsertText(output)}><Text style={s.primaryText}>Insert into publication</Text></Pressable></View>}
 </View>;
}
const s=StyleSheet.create({wrap:{gap:10},tabs:{gap:5},tab:{paddingHorizontal:9,paddingVertical:7,borderRadius:14,backgroundColor:"#E2E8F0"},tabOn:{backgroundColor:"#7C3AED"},tabText:{fontSize:9,fontWeight:"800",color:"#334155"},tabTextOn:{color:"#fff"},heading:{fontSize:12,fontWeight:"900",color:"#312E81"},input:{minHeight:44,borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,padding:9,backgroundColor:"#fff",fontSize:11,textAlignVertical:"top"},chips:{gap:6,paddingVertical:2},chip:{backgroundColor:"#EDE9FE",borderRadius:14,paddingHorizontal:10,paddingVertical:7},chipOn:{backgroundColor:"#C4B5FD"},chipText:{fontSize:9,fontWeight:"800",color:"#4C1D95"},primary:{backgroundColor:"#7C3AED",borderRadius:7,paddingVertical:10,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:6},primaryText:{color:"#fff",fontSize:11,fontWeight:"900"},help:{fontSize:9,lineHeight:14,color:"#64748B"},grid:{flexDirection:"row",flexWrap:"wrap",gap:7},metric:{width:"31%",backgroundColor:"#F5F3FF",borderRadius:8,padding:8,alignItems:"center"},metricValue:{fontSize:17,fontWeight:"900",color:"#6D28D9"},metricLabel:{fontSize:8,color:"#64748B",marginTop:2},summary:{fontSize:11,lineHeight:17,color:"#334155",backgroundColor:"#fff",padding:9,borderRadius:7},warning:{fontSize:10,color:"#B45309",backgroundColor:"#FFFBEB",padding:8,borderRadius:7},card:{flexDirection:"row",gap:8,alignItems:"center",backgroundColor:"#fff",borderWidth:1,borderColor:"#E2E8F0",borderRadius:8,padding:9,marginBottom:6},cardTitle:{fontSize:10,fontWeight:"900",color:"#1E293B"},cardText:{fontSize:9,lineHeight:14,color:"#64748B",marginTop:2},success:{padding:16,textAlign:"center",color:"#047857",fontWeight:"800"},ready:{fontSize:9,fontWeight:"900",color:"#047857"},setup:{fontSize:9,fontWeight:"900",color:"#B45309"},output:{borderWidth:1,borderColor:"#C4B5FD",backgroundColor:"#F5F3FF",borderRadius:8,padding:9,gap:8},outputText:{fontSize:11,lineHeight:17,color:"#312E81"}});
