import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherProject } from "../../types/publisher";
import { type FontCategory, fontUsage, searchFonts } from "../../utils/typographyManager";

type Props = {
  visible: boolean; project: PublisherProject; selectedFamily: string; favorites: string[]; recents: string[];
  onClose: () => void; onSelect: (family: string) => void; onToggleFavorite: (family: string) => void; onImport: () => void; onRemoveCustom: (family: string) => void;
};
const categories: Array<FontCategory | "All"> = ["All", "Sans Serif", "Serif", "Display", "Monospace", "Handwriting", "Custom"];
export default function FontManagerModal({ visible, project, selectedFamily, favorites, recents, onClose, onSelect, onToggleFavorite, onImport, onRemoveCustom }: Props) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState<FontCategory | "All">("All");
  const usage = useMemo(() => fontUsage(project), [project]);
  const fonts = useMemo(() => searchFonts(project, query, category), [project, query, category]);
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.modal}>
    <View style={styles.header}><View><Text style={styles.title}>Professional Font Manager</Text><Text style={styles.subtitle}>Search, organize, import, and apply publication fonts.</Text></View><Pressable onPress={onClose}><Ionicons name="close" size={24} color="#E2E8F0"/></Pressable></View>
    <View style={styles.toolbar}><View style={styles.search}><Ionicons name="search" size={16} color="#64748B"/><TextInput value={query} onChangeText={setQuery} placeholder="Search fonts" placeholderTextColor="#64748B" style={styles.searchInput}/></View><Pressable onPress={onImport} style={styles.importButton}><Ionicons name="cloud-upload-outline" size={16} color="#FFFFFF"/><Text style={styles.importText}>Import font</Text></Pressable></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.categories}>{categories.map((item)=><Pressable key={item} onPress={()=>setCategory(item)} style={[styles.category, category===item&&styles.categoryActive]}><Text style={[styles.categoryText,category===item&&styles.categoryTextActive]}>{item}</Text></Pressable>)}</ScrollView>
    {recents.length>0&&category==="All"&&!query&&<View style={styles.quick}><Text style={styles.quickTitle}>RECENT</Text>{recents.slice(0,5).map((family)=><Pressable key={family} onPress={()=>onSelect(family)} style={styles.quickChip}><Text style={styles.quickText}>{family}</Text></Pressable>)}</View>}
    <ScrollView style={styles.list}>{fonts.map((font)=>{const custom=!font.builtIn; const active=font.family===selectedFamily; return <Pressable key={font.family} onPress={()=>onSelect(font.family)} style={[styles.row,active&&styles.rowActive]}>
      <Pressable onPress={()=>onToggleFavorite(font.family)} hitSlop={8}><Ionicons name={favorites.includes(font.family)?"star":"star-outline"} size={18} color={favorites.includes(font.family)?"#FBBF24":"#64748B"}/></Pressable>
      <View style={styles.fontInfo}><Text style={[styles.preview,{fontFamily:font.family}]} numberOfLines={1}>{font.family} — Aa Bb Cc 123</Text><Text style={styles.meta}>{font.category}{custom?" • Embedded in project":""}{usage.get(font.family)?` • Used ${usage.get(font.family)} time(s)`:""}</Text></View>
      {active&&<Ionicons name="checkmark-circle" size={20} color="#2DD4BF"/>}{custom&&<Pressable onPress={()=>onRemoveCustom(font.family)} hitSlop={8}><Ionicons name="trash-outline" size={18} color="#FB7185"/></Pressable>}
    </Pressable>})}{fonts.length===0&&<Text style={styles.empty}>No fonts match this search.</Text>}</ScrollView>
    <View style={styles.footer}><Text style={styles.footerText}>{fonts.length} font(s) • {Object.keys(project.embeddedFonts??{}).length} custom</Text><Pressable onPress={onClose} style={styles.done}><Text style={styles.doneText}>Done</Text></Pressable></View>
  </View></View></Modal>;
}
const styles=StyleSheet.create({overlay:{flex:1,backgroundColor:"rgba(2,6,23,.72)",alignItems:"center",justifyContent:"center",padding:24},modal:{width:"100%",maxWidth:760,height:"82%",backgroundColor:"#111827",borderRadius:14,borderWidth:1,borderColor:"#334155",overflow:"hidden"},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",padding:18,borderBottomWidth:1,borderBottomColor:"#273449"},title:{color:"#F8FAFC",fontSize:18,fontWeight:"900"},subtitle:{color:"#94A3B8",fontSize:11,marginTop:3},toolbar:{flexDirection:"row",gap:10,padding:14},search:{flex:1,height:38,backgroundColor:"#0F172A",borderRadius:8,borderWidth:1,borderColor:"#334155",paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:8},searchInput:{flex:1,color:"#F8FAFC",fontSize:12},importButton:{height:38,paddingHorizontal:14,borderRadius:8,backgroundColor:"#0F766E",flexDirection:"row",alignItems:"center",gap:7},importText:{color:"#FFFFFF",fontSize:11,fontWeight:"800"},categories:{maxHeight:42,paddingHorizontal:14},category:{paddingHorizontal:12,paddingVertical:7,marginRight:7,borderRadius:16,backgroundColor:"#1E293B"},categoryActive:{backgroundColor:"#0F766E"},categoryText:{color:"#CBD5E1",fontSize:10,fontWeight:"700"},categoryTextActive:{color:"#FFFFFF"},quick:{paddingHorizontal:14,paddingVertical:10,flexDirection:"row",alignItems:"center",gap:7,flexWrap:"wrap"},quickTitle:{color:"#64748B",fontSize:8,fontWeight:"900",letterSpacing:1},quickChip:{backgroundColor:"#1E293B",borderRadius:12,paddingHorizontal:9,paddingVertical:5},quickText:{color:"#CBD5E1",fontSize:9},list:{flex:1,paddingHorizontal:14},row:{minHeight:62,flexDirection:"row",alignItems:"center",gap:12,paddingHorizontal:12,paddingVertical:9,borderBottomWidth:1,borderBottomColor:"#243044"},rowActive:{backgroundColor:"#134E4A55",borderRadius:8},fontInfo:{flex:1},preview:{color:"#F8FAFC",fontSize:17},meta:{color:"#64748B",fontSize:9,marginTop:4},empty:{color:"#94A3B8",textAlign:"center",padding:30},footer:{padding:14,borderTopWidth:1,borderTopColor:"#273449",flexDirection:"row",alignItems:"center",justifyContent:"space-between"},footerText:{color:"#64748B",fontSize:10},done:{backgroundColor:"#E2E8F0",paddingHorizontal:20,paddingVertical:8,borderRadius:7},doneText:{color:"#0F172A",fontWeight:"900",fontSize:11}});
