import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherElement, PublisherPage } from "../../types/publisher";
import type { AnchorMode } from "../../utils/frameContainerEngine";
import { frameDiagnostics } from "../../utils/frameContainerEngine";

type Props = { visible:boolean; page:PublisherPage; selectedIds:string[]; onCreateFrame:(padding:number)=>void; onDetach:()=>void; onRemoveFrame:(keepChildren:boolean)=>void; onAnchor:(mode:AnchorMode,targetId?:string)=>void; onFitFrame:()=>void; onFitContent:()=>void; onUpdateFrame:(updates:Partial<PublisherElement>)=>void; onClose:()=>void };
export default function FrameContainerManagerModal(props:Props){
 const selected=props.page.elements.filter(e=>props.selectedIds.includes(e.id)); const frame=selected.find(e=>e.isFrame) ?? null; const frames=props.page.elements.filter(e=>e.isFrame); const d=frameDiagnostics(props.page); const padding=frame?.framePadding ?? 16;
 return <Modal visible={props.visible} transparent animationType="fade" onRequestClose={props.onClose}><View style={s.backdrop}><View style={s.card}><View style={s.header}><View><Text style={s.title}>Frames, Containers & Anchoring</Text><Text style={s.sub}>Professional object structure</Text></View><Pressable onPress={props.onClose}><Text style={s.close}>Close</Text></Pressable></View><ScrollView contentContainerStyle={s.body}>
 <Text style={s.status}>{d.frames} frames · {d.anchored} anchored · {d.overflow} overflow · {d.orphaned} orphaned</Text>
 <Text style={s.section}>Create container</Text><View style={s.row}><Button label="Frame Selection" disabled={!selected.length} onPress={()=>props.onCreateFrame(16)}/><Button label="Detach Selected" disabled={!selected.some(e=>e.parentFrameId)} onPress={props.onDetach}/><Button label="Remove Frame" disabled={!frame} onPress={()=>props.onRemoveFrame(true)}/><Button label="Delete Frame + Content" disabled={!frame} onPress={()=>props.onRemoveFrame(false)}/></View>
 <Text style={s.section}>Anchoring</Text><View style={s.row}><Button label="No Anchor" disabled={!selected.length} onPress={()=>props.onAnchor("none")}/><Button label="Anchor to Page" disabled={!selected.length} onPress={()=>props.onAnchor("page")}/><Button label="Anchor to Margins" disabled={!selected.length} onPress={()=>props.onAnchor("margins")}/>{frames.map(f=><Button key={f.id} label={`Anchor to ${f.name}`} disabled={!selected.length} onPress={()=>props.onAnchor("frame",f.id)}/>)}</View>
 <Text style={s.section}>Frame fitting</Text><View style={s.row}><Button label="Fit Frame to Content" disabled={!frame} onPress={props.onFitFrame}/><Button label="Fit Content to Frame" disabled={!frame} onPress={props.onFitContent}/></View>
 {frame&&<><Text style={s.section}>Frame settings</Text><View style={s.field}><Text style={s.label}>Padding</Text><TextInput style={s.input} keyboardType="numeric" value={String(padding)} onChangeText={v=>props.onUpdateFrame({framePadding:Math.max(0,Number(v)||0)})}/></View><View style={s.row}><Toggle label="Clip content" active={frame.frameClipContent!==false} onPress={()=>props.onUpdateFrame({frameClipContent:frame.frameClipContent===false})}/><Toggle label="Preserve aspect" active={frame.framePreserveAspect!==false} onPress={()=>props.onUpdateFrame({framePreserveAspect:frame.framePreserveAspect===false})}/><Toggle label="Auto size" active={!!frame.frameAutoSize} onPress={()=>props.onUpdateFrame({frameAutoSize:!frame.frameAutoSize})}/></View></>}
 <Text style={s.note}>Frames remain standard editor objects, so selection, layers, save/load, export, locking, undo, and z-order continue to work. Container membership is stored by frame ID.</Text>
 </ScrollView></View></View></Modal>;
}
function Button({label,onPress,disabled}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,disabled&&s.disabled]}><Text style={s.buttonText}>{label}</Text></Pressable>};
function Toggle({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.toggle,active&&s.toggleOn]}><Text style={[s.toggleText,active&&s.toggleTextOn]}>{label}</Text></Pressable>};
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(15,23,42,.58)",alignItems:"center",justifyContent:"center",padding:24},card:{width:"92%",maxWidth:920,maxHeight:"90%",backgroundColor:"#fff",borderRadius:14,overflow:"hidden"},header:{padding:18,borderBottomWidth:1,borderBottomColor:"#E2E8F0",flexDirection:"row",justifyContent:"space-between"},title:{fontSize:20,fontWeight:"800",color:"#0F172A"},sub:{color:"#64748B",marginTop:3},close:{color:"#0F766E",fontWeight:"700"},body:{padding:18,gap:11},status:{color:"#475569",fontWeight:"700"},section:{fontSize:15,fontWeight:"800",color:"#0F172A",marginTop:7},row:{flexDirection:"row",gap:8,flexWrap:"wrap"},button:{paddingHorizontal:13,paddingVertical:10,borderRadius:8,backgroundColor:"#E2E8F0"},buttonText:{fontWeight:"700",color:"#334155"},disabled:{opacity:.4},toggle:{paddingHorizontal:12,paddingVertical:9,borderRadius:8,borderWidth:1,borderColor:"#CBD5E1"},toggleOn:{backgroundColor:"#CCFBF1",borderColor:"#0F766E"},toggleText:{color:"#475569"},toggleTextOn:{color:"#0F766E",fontWeight:"700"},field:{flexDirection:"row",alignItems:"center",gap:8},label:{fontSize:12,color:"#64748B",fontWeight:"700"},input:{width:90,borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,padding:8},note:{marginTop:10,padding:12,borderRadius:8,backgroundColor:"#F8FAFC",color:"#64748B",lineHeight:19}});
