import { Ionicons } from "@expo/vector-icons";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherElement, PublisherPage, PublisherProject } from "../../types/publisher";
import { createElementInteraction, DEFAULT_PAGE_TRANSITION, getInteractiveSettings, type ElementInteraction, type InteractionActionType, type InteractionTrigger, type InteractiveProjectSettings, type PageTransition } from "../../utils/interactivePublishingEngine";

type Props = {
  visible: boolean; project: PublisherProject; page: PublisherPage; element: PublisherElement | null; previewPageId: string;
  onClose: () => void; onAdd: (interaction: ElementInteraction) => void; onUpdate: (id: string, updates: Partial<ElementInteraction>) => void; onRemove: (id: string) => void;
  onTransition: (transition: PageTransition) => void; onSettings: (settings: InteractiveProjectSettings) => void; onPreviewPage: (pageId: string) => void; onStartPresentation: () => void;
};
const triggers: InteractionTrigger[] = ["click", "double-click", "hover", "mouse-leave", "page-load", "animation-end"];
const actions: InteractionActionType[] = ["go-to-page", "next-page", "previous-page", "open-url", "show-element", "hide-element", "toggle-element", "play-animation", "pause-animation", "stop-animation"];
const transitions: PageTransition["type"][] = ["none", "fade", "slide-left", "slide-right", "slide-up", "slide-down", "zoom", "push", "wipe"];
const n = (v: string, fallback: number) => Number.isFinite(Number(v)) ? Number(v) : fallback;
export default function InteractivePublishingModal(props: Props) {
  const settings = getInteractiveSettings(props.project); const transition = props.page.transition ?? DEFAULT_PAGE_TRANSITION; const interactions = props.element?.interactions ?? [];
  return <Modal visible={props.visible} transparent animationType="fade" onRequestClose={props.onClose}><View style={s.backdrop}><View style={s.modal}>
    <View style={s.header}><View><Text style={s.title}>Interactive Publishing & Presentation</Text><Text style={s.sub}>Page transitions, actions, links, show/hide and presentation preview</Text></View><Pressable onPress={props.onClose}><Ionicons name="close" size={25} color="#fff" /></Pressable></View>
    <ScrollView contentContainerStyle={s.body}>
      <View style={s.sectionHeader}><Text style={s.section}>Presentation Preview</Text><Pressable style={s.primary} onPress={props.onStartPresentation}><Ionicons name="play" size={15} color="#fff"/><Text style={s.primaryText}>Start Presentation</Text></Pressable></View>
      <View style={s.row}>{props.project.pages.map((page, index) => <Pressable key={page.id} style={[s.chip, props.previewPageId === page.id && s.chipOn]} onPress={() => props.onPreviewPage(page.id)}><Text style={s.chipText}>{index + 1}. {page.name}</Text></Pressable>)}</View>

      <Text style={s.section}>Page Transition</Text><View style={s.row}>{transitions.map((type) => <Pressable key={type} style={[s.chip, transition.type === type && s.chipOn]} onPress={() => props.onTransition({ ...transition, type })}><Text style={s.chipText}>{type}</Text></Pressable>)}</View>
      <View style={s.row}><Text style={s.label}>Duration</Text><TextInput style={s.input} value={String(transition.duration)} onChangeText={(v) => props.onTransition({ ...transition, duration: Math.max(0, n(v, transition.duration)) })} keyboardType="numeric"/><Text style={s.label}>Easing</Text>{(["linear","ease","ease-in","ease-out","ease-in-out"] as const).map((easing) => <Pressable key={easing} style={[s.chip, transition.easing === easing && s.chipOn]} onPress={() => props.onTransition({ ...transition, easing })}><Text style={s.chipText}>{easing}</Text></Pressable>)}</View>

      <Text style={s.section}>Presentation Settings</Text><View style={s.row}>{(["manual","auto","kiosk"] as const).map((mode) => <Pressable key={mode} style={[s.chip, settings.presentationMode === mode && s.chipOn]} onPress={() => props.onSettings({ ...settings, presentationMode: mode })}><Text style={s.chipText}>{mode}</Text></Pressable>)}<Text style={s.label}>Advance</Text><TextInput style={s.input} value={String(settings.autoAdvanceSeconds)} onChangeText={(v) => props.onSettings({ ...settings, autoAdvanceSeconds: Math.max(.5, n(v, settings.autoAdvanceSeconds)) })} keyboardType="numeric"/></View>
      <View style={s.row}>{(["loopPresentation","showNavigation","showProgress","keyboardNavigation","swipeNavigation"] as const).map((key) => <Pressable key={key} style={[s.toggle, settings[key] && s.toggleOn]} onPress={() => props.onSettings({ ...settings, [key]: !settings[key] })}><Text style={s.toggleText}>{key.replace(/([A-Z])/g," $1")}</Text></Pressable>)}</View>

      <View style={s.sectionHeader}><Text style={s.section}>Selected Object Interactions</Text><Pressable style={[s.primary, !props.element && s.disabled]} disabled={!props.element} onPress={() => props.onAdd(createElementInteraction())}><Text style={s.primaryText}>+ Add Interaction</Text></Pressable></View>
      {!props.element ? <Text style={s.empty}>Select an object to add click, hover, navigation or visibility actions.</Text> : interactions.length === 0 ? <Text style={s.empty}>No interactions on this object.</Text> : interactions.map((interaction) => <View key={interaction.id} style={s.card}>
        <View style={s.sectionHeader}><TextInput style={s.nameInput} value={interaction.name} onChangeText={(name) => props.onUpdate(interaction.id, { name })}/><Pressable onPress={() => props.onRemove(interaction.id)}><Ionicons name="trash-outline" size={18} color="#FCA5A5"/></Pressable></View>
        <Text style={s.mini}>Trigger</Text><View style={s.row}>{triggers.map((trigger) => <Pressable key={trigger} style={[s.chip, interaction.trigger === trigger && s.chipOn]} onPress={() => props.onUpdate(interaction.id, { trigger })}><Text style={s.chipText}>{trigger}</Text></Pressable>)}</View>
        <Text style={s.mini}>Action</Text><View style={s.row}>{actions.map((action) => <Pressable key={action} style={[s.chip, interaction.action === action && s.chipOn]} onPress={() => props.onUpdate(interaction.id, { action })}><Text style={s.chipText}>{action}</Text></Pressable>)}</View>
        {interaction.action === "go-to-page" && <View style={s.row}>{props.project.pages.map((page) => <Pressable key={page.id} style={[s.chip, interaction.targetPageId === page.id && s.chipOn]} onPress={() => props.onUpdate(interaction.id, { targetPageId: page.id })}><Text style={s.chipText}>{page.name}</Text></Pressable>)}</View>}
        {interaction.action === "open-url" && <TextInput style={s.urlInput} placeholder="https://example.com" placeholderTextColor="#64748B" value={interaction.url ?? ""} onChangeText={(url) => props.onUpdate(interaction.id, { url })}/>} 
        {["show-element","hide-element","toggle-element"].includes(interaction.action) && <View style={s.row}>{props.page.elements.filter((item) => item.id !== props.element?.id).map((item) => <Pressable key={item.id} style={[s.chip, interaction.targetElementId === item.id && s.chipOn]} onPress={() => props.onUpdate(interaction.id, { targetElementId: item.id })}><Text style={s.chipText}>{item.name || item.type}</Text></Pressable>)}</View>}
        <View style={s.row}><Pressable style={[s.toggle, interaction.enabled && s.toggleOn]} onPress={() => props.onUpdate(interaction.id, { enabled: !interaction.enabled })}><Text style={s.toggleText}>Enabled</Text></Pressable><Text style={s.label}>Delay</Text><TextInput style={s.input} value={String(interaction.delay)} onChangeText={(v) => props.onUpdate(interaction.id, { delay: Math.max(0, n(v, interaction.delay)) })} keyboardType="numeric"/></View>
      </View>)}
    </ScrollView>
  </View></View></Modal>;
}
const s = StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(2,6,23,.76)",alignItems:"center",justifyContent:"center"},modal:{width:"94%",maxWidth:1120,maxHeight:"92%",backgroundColor:"#0F172A",borderRadius:16,borderWidth:1,borderColor:"#334155",overflow:"hidden"},header:{padding:18,flexDirection:"row",justifyContent:"space-between",alignItems:"center",backgroundColor:"#111827"},title:{color:"#F8FAFC",fontSize:20,fontWeight:"800"},sub:{color:"#94A3B8",fontSize:12,marginTop:3},body:{padding:18,gap:12},section:{color:"#5EEAD4",fontSize:13,fontWeight:"800"},sectionHeader:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},row:{flexDirection:"row",alignItems:"center",gap:7,flexWrap:"wrap"},chip:{paddingHorizontal:9,paddingVertical:6,borderRadius:12,backgroundColor:"#334155"},chipOn:{backgroundColor:"#0F766E"},chipText:{color:"#E2E8F0",fontSize:9,fontWeight:"700"},primary:{flexDirection:"row",gap:6,alignItems:"center",paddingHorizontal:12,paddingVertical:8,borderRadius:7,backgroundColor:"#2563EB"},primaryText:{color:"#fff",fontSize:10,fontWeight:"800"},disabled:{opacity:.35},label:{color:"#CBD5E1",fontSize:11},mini:{color:"#C4B5FD",fontSize:10,fontWeight:"800"},input:{width:68,height:31,borderWidth:1,borderColor:"#475569",borderRadius:6,color:"#F8FAFC",paddingHorizontal:7,backgroundColor:"#1E293B"},urlInput:{height:34,borderWidth:1,borderColor:"#475569",borderRadius:7,color:"#F8FAFC",paddingHorizontal:9,backgroundColor:"#111827"},nameInput:{flex:1,color:"#F8FAFC",fontWeight:"800",borderBottomWidth:1,borderBottomColor:"#475569",paddingVertical:4},toggle:{paddingHorizontal:10,paddingVertical:7,borderRadius:7,backgroundColor:"#334155"},toggleOn:{backgroundColor:"#0F766E"},toggleText:{color:"#fff",fontSize:9,fontWeight:"700",textTransform:"capitalize"},card:{padding:12,borderRadius:10,backgroundColor:"#1E293B",gap:9},empty:{color:"#94A3B8",padding:12,backgroundColor:"#1E293B",borderRadius:8}});
