import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherProject } from "../../types/publisher";
import { applyGuidePreset, applyGridPreset, createLayerFolder, getPhase124Data, phase124Diagnostics, resetMasterOverrides, saveGridPreset, saveGuidePreset, setMasterEditing, updateAdvancedLayer } from "../../utils/layoutInteractionEngine";
import { DEFAULT_LAYERS, layoutCompletionDiagnostics } from "../../utils/spreadLayerEngine";

type Props = { visible: boolean; project: PublisherProject; selectedIds: string[]; onClose: () => void; onChange: (project: PublisherProject) => void; onAddLayer: (name: string) => void; onUpdateLayer: (id: string, updates: any) => void; onDeleteLayer: (id: string) => void; onMoveLayer: (id: string, direction: -1 | 1) => void; onAssignLayer: (id: string) => void; onCreateMaster: (name: string) => void; onApplyMaster: (id: string) => void; onDetachMaster: () => void; onMovePage: (direction: -1 | 1) => void };
const Button=({label,onPress,disabled}:{label:string;onPress:()=>void;disabled?:boolean})=><Pressable disabled={disabled} onPress={onPress} style={[s.button,disabled&&s.disabled]}><Text style={s.buttonText}>{label}</Text></Pressable>;
export default function LayoutCompletionManagerModal(props: Props){
 const [layerName,setLayerName]=useState("New Layer"); const [masterName,setMasterName]=useState("Master Spread"); const [presetName,setPresetName]=useState("Publishing Layout");
 const layers=props.project.layers?.length?props.project.layers:DEFAULT_LAYERS; const diagnostics=useMemo(()=>layoutCompletionDiagnostics(props.project),[props.project]); const polish=useMemo(()=>phase124Diagnostics(props.project),[props.project]);
 const settings={facingPages:false,startOnRight:true,pageGap:24,spineGap:12,allowShuffle:true,...props.project.spreadSettings}; const phase=getPhase124Data(props.project); const active=props.project.pages.find(p=>p.id===props.project.activePageId)??props.project.pages[0];
 const replaceActive=(page:any)=>props.onChange({...props.project,pages:props.project.pages.map(p=>p.id===page.id?page:p)});
 const patchInteraction=(updates:any)=>props.onChange({...props.project,phase124Data:{...phase,interaction:{...phase.interaction,...updates}}});
 return <Modal visible={props.visible} transparent animationType="fade" onRequestClose={props.onClose}><View style={s.backdrop}><View style={s.card}><View style={s.header}><View><Text style={s.title}>Layout Interaction & Professional Polish</Text><Text style={s.sub}>Final professional layout completion</Text></View><Pressable onPress={props.onClose}><Text style={s.close}>Close</Text></Pressable></View><ScrollView contentContainerStyle={s.body}>
 <Text style={s.section}>Visual Spread Workspace</Text><View style={s.row}><Button label={settings.facingPages?"Facing Pages: On":"Facing Pages: Off"} onPress={()=>props.onChange({...props.project,spreadSettings:{...settings,facingPages:!settings.facingPages}})}/><Button label={settings.startOnRight?"Starts Right":"Starts Left"} onPress={()=>props.onChange({...props.project,spreadSettings:{...settings,startOnRight:!settings.startOnRight}})}/><Button label={settings.allowShuffle?"Live Shuffle: On":"Live Shuffle: Off"} onPress={()=>props.onChange({...props.project,spreadSettings:{...settings,allowShuffle:!settings.allowShuffle}})}/><Button label="Move Page Left" onPress={()=>props.onMovePage(-1)}/><Button label="Move Page Right" onPress={()=>props.onMovePage(1)}/><Text style={s.metric}>{diagnostics.pages} pages · {diagnostics.spreads} spreads</Text></View>
 <Text style={s.section}>Guide & Grid Presets</Text><View style={s.row}><TextInput value={presetName} onChangeText={setPresetName} style={s.input}/><Button label="Save Guides" onPress={()=>props.onChange(saveGuidePreset(props.project,active,presetName))}/><Button label="Save Grid" onPress={()=>props.onChange(saveGridPreset(props.project,active,presetName))}/></View>
 <View style={s.row}>{phase.guidePresets.map(p=><Button key={p.id} label={`Guides: ${p.name}`} onPress={()=>replaceActive(applyGuidePreset(active,p))}/>)}{phase.gridPresets.map(p=><Button key={p.id} label={`Grid: ${p.name}`} onPress={()=>replaceActive(applyGridPreset(active,p))}/>)}</View>
 <Text style={s.section}>Smart Alignment & Pasteboard</Text><View style={s.row}><Button label={phase.interaction.showSnapLabels?"Snap Labels: On":"Snap Labels: Off"} onPress={()=>patchInteraction({showSnapLabels:!phase.interaction.showSnapLabels})}/><Button label={phase.interaction.showDistances?"Distances: On":"Distances: Off"} onPress={()=>patchInteraction({showDistances:!phase.interaction.showDistances})}/><Button label={phase.interaction.showEqualSpacing?"Equal Spacing: On":"Equal Spacing: Off"} onPress={()=>patchInteraction({showEqualSpacing:!phase.interaction.showEqualSpacing})}/><Button label={phase.interaction.altDisablesSnap?"Alt Override: On":"Alt Override: Off"} onPress={()=>patchInteraction({altDisablesSnap:!phase.interaction.altDisablesSnap})}/><Button label={phase.interaction.pasteboardSnap?"Pasteboard Snap: On":"Pasteboard Snap: Off"} onPress={()=>patchInteraction({pasteboardSnap:!phase.interaction.pasteboardSnap})}/><Field label="Magnet" value={phase.interaction.magnetStrength} onChange={v=>patchInteraction({magnetStrength:Math.max(.1,v)})}/><Field label="Pasteboard" value={phase.interaction.pasteboardSize} onChange={v=>patchInteraction({pasteboardSize:Math.max(100,v)})}/></View>
 <Text style={s.section}>Advanced Layers</Text><View style={s.row}><TextInput value={layerName} onChangeText={setLayerName} style={s.input}/><Button label="Add Layer" onPress={()=>props.onAddLayer(layerName)}/><Button label="Add Folder" onPress={()=>props.onChange(createLayerFolder(props.project,layerName||"Layer Folder"))}/></View>
 {[...layers].sort((a,b)=>a.order-b.order).map(layer=><View key={layer.id} style={s.layer}><View style={[s.swatch,{backgroundColor:layer.color}]}/><Text style={s.layerName}>{layer.isFolder?"▸ ":""}{layer.name}</Text><Button label={layer.visible?"Visible":"Hidden"} onPress={()=>props.onUpdateLayer(layer.id,{visible:!layer.visible})}/><Button label={layer.locked?"Locked":"Unlocked"} onPress={()=>props.onUpdateLayer(layer.id,{locked:!layer.locked})}/><Button label={layer.printable?"Print":"No Print"} onPress={()=>props.onUpdateLayer(layer.id,{printable:!layer.printable})}/><Button label={layer.exportEnabled===false?"Export Off":"Export On"} onPress={()=>props.onChange(updateAdvancedLayer(props.project,layer.id,{exportEnabled:layer.exportEnabled===false}))}/><Field label="Opacity" value={Math.round((layer.opacity??1)*100)} onChange={v=>props.onChange(updateAdvancedLayer(props.project,layer.id,{opacity:Math.max(0,Math.min(1,v/100))}))}/><Button label="Assign" onPress={()=>props.onAssignLayer(layer.id)} disabled={!props.selectedIds.length||layer.isFolder}/><Button label="↑" onPress={()=>props.onMoveLayer(layer.id,-1)}/><Button label="↓" onPress={()=>props.onMoveLayer(layer.id,1)}/><Button label="Delete" onPress={()=>props.onDeleteLayer(layer.id)} disabled={layers.length<=1}/></View>)}
 <Text style={s.section}>Master Spread Workspace</Text><View style={s.row}><TextInput value={masterName} onChangeText={setMasterName} style={s.input}/><Button label="Create From Active Page" onPress={()=>props.onCreateMaster(masterName)}/><Button label="Detach Master" onPress={props.onDetachMaster}/><Button label="Reset Overrides" onPress={()=>replaceActive(resetMasterOverrides(active))}/></View>
 {(props.project.masterSpreads??[]).map(master=><View key={master.id} style={s.layer}><Text style={s.layerName}>{master.name}</Text><Text style={s.metric}>{master.facingPages?"Facing":"Single"}</Text><Button label="Edit Master" onPress={()=>props.onChange(setMasterEditing(props.project,master.id))}/><Button label="Apply" onPress={()=>props.onApplyMaster(master.id)}/></View>)}
 <Text style={s.section}>Layout Preflight</Text><Text style={s.metric}>{diagnostics.layers} layers · {diagnostics.masters} masters · {polish.guidePresets} guide presets · {polish.gridPresets} grid presets · {polish.layerFolders} folders · {polish.masterOverrides} overrides · {polish.brokenAnchors} broken anchors · {polish.invalidFrames} invalid frames</Text>
 </ScrollView></View></View></Modal>
}
function Field({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <View><Text style={s.fieldLabel}>{label}</Text><TextInput value={String(value)} keyboardType="numeric" onChangeText={v=>onChange(Number(v)||0)} style={s.smallInput}/></View>}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(15,23,42,.6)",alignItems:"center",justifyContent:"center",padding:18},card:{width:"96%",maxWidth:1180,maxHeight:"92%",backgroundColor:"#fff",borderRadius:14,overflow:"hidden"},header:{padding:16,backgroundColor:"#0F172A",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"#fff",fontSize:18,fontWeight:"900"},sub:{color:"#94A3B8",fontSize:12},close:{color:"#5EEAD4",fontWeight:"900"},body:{padding:16,gap:12},section:{fontSize:14,fontWeight:"900",color:"#0F172A",marginTop:6},row:{flexDirection:"row",alignItems:"flex-end",gap:8,flexWrap:"wrap"},button:{paddingVertical:7,paddingHorizontal:10,borderRadius:7,backgroundColor:"#E2E8F0"},buttonText:{fontSize:11,fontWeight:"800",color:"#334155"},disabled:{opacity:.4},input:{minWidth:180,borderWidth:1,borderColor:"#CBD5E1",borderRadius:7,paddingHorizontal:10,paddingVertical:7},smallInput:{width:76,borderWidth:1,borderColor:"#CBD5E1",borderRadius:7,paddingHorizontal:8,paddingVertical:6},fieldLabel:{fontSize:10,color:"#64748B",marginBottom:2},layer:{flexDirection:"row",alignItems:"flex-end",gap:7,borderWidth:1,borderColor:"#E2E8F0",padding:8,borderRadius:9,flexWrap:"wrap"},swatch:{width:12,height:12,borderRadius:6,marginBottom:9},layerName:{fontWeight:"900",color:"#1E293B",minWidth:120,marginBottom:8},metric:{fontSize:12,color:"#64748B",fontWeight:"700",marginBottom:8}});
