import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherPage } from "../../types/publisher";
import { addLayoutGuide, deleteLayoutGuide, getLayoutSettings, type LayoutGridType, type LayoutSettings, updateLayoutGuide } from "../../utils/layoutGuideEngine";

type Props = { visible: boolean; page: PublisherPage; onChange: (page: PublisherPage) => void; onClose: () => void };
const gridTypes: LayoutGridType[] = ["square","modular","columns","rows","baseline","thirds","golden","fibonacci","diagonal","crosshair"];
export default function LayoutManagerModal({ visible, page, onChange, onClose }: Props) {
  const settings = getLayoutSettings(page);
  const patch = (updates: Partial<LayoutSettings>) => onChange({ ...page, layoutSettings: { ...settings, ...updates } });
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.card}>
    <View style={styles.header}><View><Text style={styles.title}>Guides, Grids & Snapping</Text><Text style={styles.sub}>Professional document layout manager</Text></View><Pressable onPress={onClose}><Text style={styles.close}>Close</Text></Pressable></View>
    <ScrollView contentContainerStyle={styles.body}>
      <Text style={styles.section}>Guides</Text><View style={styles.row}><Button label="+ Vertical" onPress={() => onChange(addLayoutGuide(page,"vertical",page.width/2))}/><Button label="+ Horizontal" onPress={() => onChange(addLayoutGuide(page,"horizontal",page.height/2))}/><Toggle label="Visible" value={settings.guidesVisible} onPress={() => patch({guidesVisible:!settings.guidesVisible})}/><Toggle label="Lock all" value={settings.guidesLocked} onPress={() => patch({guidesLocked:!settings.guidesLocked})}/></View>
      {settings.guides.map(g=><View key={g.id} style={styles.guideRow}><TextInput value={g.name} onChangeText={name=>onChange(updateLayoutGuide(page,g.id,{name}))} style={styles.input}/><TextInput value={String(Math.round(g.position))} keyboardType="numeric" onChangeText={v=>onChange(updateLayoutGuide(page,g.id,{position:Number(v)||0}))} style={styles.smallInput}/><Toggle label="Lock" value={!!g.locked} onPress={()=>onChange(updateLayoutGuide(page,g.id,{locked:!g.locked}))}/><Toggle label="Hide" value={!!g.hidden} onPress={()=>onChange(updateLayoutGuide(page,g.id,{hidden:!g.hidden}))}/><Button label="Delete" onPress={()=>onChange(deleteLayoutGuide(page,g.id))}/></View>)}
      <Text style={styles.section}>Grid & Composition</Text><View style={styles.wrap}>{gridTypes.map(type=><Toggle key={type} label={type} value={settings.gridType===type} onPress={()=>patch({gridType:type,gridVisible:true})}/>)}</View>
      <View style={styles.row}><Toggle label="Show grid" value={settings.gridVisible} onPress={()=>patch({gridVisible:!settings.gridVisible})}/><Field label="Spacing" value={settings.gridSpacing} onChange={gridSpacing=>patch({gridSpacing})}/><Field label="Subdivisions" value={settings.gridSubdivisions} onChange={gridSubdivisions=>patch({gridSubdivisions:Math.max(1,gridSubdivisions)})}/><Field label="Columns" value={settings.columns} onChange={columns=>patch({columns:Math.max(1,columns)})}/><Field label="Rows" value={settings.rows} onChange={rows=>patch({rows:Math.max(1,rows)})}/></View>
      <Text style={styles.section}>Print & Safety Areas</Text><View style={styles.row}><Field label="Safe" value={settings.safeArea} onChange={safeArea=>patch({safeArea})}/><Field label="Live" value={settings.liveArea} onChange={liveArea=>patch({liveArea})}/><Field label="Slug" value={settings.slug} onChange={slug=>patch({slug})}/><Field label="Gutter" value={settings.gutter} onChange={gutter=>patch({gutter})}/></View>
      <Text style={styles.section}>Smart Snapping</Text><View style={styles.wrap}>{(["snapToGuides","snapToGrid","snapToMargins","snapToBleed","snapToSafeArea","snapToPage","snapToObjects","snapToSpacing","snapToBaseline"] as const).map(k=><Toggle key={k} label={k.replace("snapTo","")} value={settings[k]} onPress={()=>patch({[k]:!settings[k]})}/>)}</View><Field label="Tolerance" value={settings.snapTolerance} onChange={snapTolerance=>patch({snapTolerance:Math.max(1,snapTolerance)})}/>
    </ScrollView>
  </View></View></Modal>;
}
function Button({label,onPress}:{label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.button}><Text style={styles.buttonText}>{label}</Text></Pressable>}
function Toggle({label,value,onPress}:{label:string;value:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.toggle,value&&styles.toggleOn]}><Text style={[styles.toggleText,value&&styles.toggleTextOn]}>{label}</Text></Pressable>}
function Field({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <View><Text style={styles.label}>{label}</Text><TextInput value={String(value)} keyboardType="numeric" onChangeText={v=>onChange(Number(v)||0)} style={styles.smallInput}/></View>}
const styles=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(15,23,42,.55)",alignItems:"center",justifyContent:"center",padding:24},card:{width:"94%",maxWidth:980,maxHeight:"90%",backgroundColor:"#fff",borderRadius:14,overflow:"hidden"},header:{padding:18,borderBottomWidth:1,borderBottomColor:"#E2E8F0",flexDirection:"row",justifyContent:"space-between"},title:{fontSize:20,fontWeight:"800",color:"#0F172A"},sub:{color:"#64748B",marginTop:3},close:{color:"#0F766E",fontWeight:"700"},body:{padding:18,gap:12},section:{fontSize:15,fontWeight:"800",color:"#0F172A",marginTop:8},row:{flexDirection:"row",gap:8,alignItems:"flex-end",flexWrap:"wrap"},wrap:{flexDirection:"row",gap:8,flexWrap:"wrap"},button:{paddingHorizontal:12,paddingVertical:9,borderRadius:8,backgroundColor:"#E2E8F0"},buttonText:{fontWeight:"700",color:"#334155"},toggle:{paddingHorizontal:12,paddingVertical:9,borderRadius:8,borderWidth:1,borderColor:"#CBD5E1"},toggleOn:{backgroundColor:"#CCFBF1",borderColor:"#0F766E"},toggleText:{color:"#475569",textTransform:"capitalize"},toggleTextOn:{color:"#0F766E",fontWeight:"700"},guideRow:{flexDirection:"row",gap:8,alignItems:"center"},input:{flex:1,minWidth:150,borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,padding:8},smallInput:{width:82,borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,padding:8},label:{fontSize:11,color:"#64748B",marginBottom:3}});
