import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherProject } from "../../types/publisher";
import { buildPrintMergeProject, createContactGroup, DEFAULT_MERGE_PRINT_SETTINGS, estimatePrintJob, importContactsFromSource, LABEL_TEMPLATES, validateAddressBook, type MergePrintSettings } from "../../utils/mailMergePrintEngine";

type Props={visible:boolean;project:PublisherProject;onChange:(project:PublisherProject)=>void;onClose:()=>void};
export default function MailMergePrintModal({visible,project,onChange,onClose}:Props){
 const data=project.mailMergeData; const [tab,setTab]=useState<"layouts"|"recipients"|"print">("layouts"); const [groupName,setGroupName]=useState("Mailing List");
 const settings:MergePrintSettings={...DEFAULT_MERGE_PRINT_SETTINGS,...data?.printSettings}; const source=data?.sources.find((item)=>item.id===data.activeSourceId)??data?.sources[0]; const book=data?.addressBook??{contacts:[],groups:[],validationIssues:[]};
 const template=LABEL_TEMPLATES.find((item)=>item.id===settings.templateId)??LABEL_TEMPLATES[0]; const estimate=useMemo(()=>data?estimatePrintJob(data,settings):undefined,[data,settings]);
 const patch=(updates:Partial<MergePrintSettings>)=>{if(!data)return;onChange({...project,updatedAt:Date.now(),mailMergeData:{...data,printSettings:{...settings,...updates}}});};
 const importRecipients=()=>{if(!data||!source)return;const contacts=importContactsFromSource(source,book.contacts);onChange({...project,updatedAt:Date.now(),mailMergeData:{...data,addressBook:{...book,contacts,validationIssues:validateAddressBook(contacts)}}});};
 const makeGroup=()=>{if(!data||!book.contacts.length)return;const created=createContactGroup(groupName,book.contacts,book.contacts.map((item)=>item.id));onChange({...project,updatedAt:Date.now(),mailMergeData:{...data,addressBook:{contacts:created.contacts,groups:[...book.groups,created.group],validationIssues:validateAddressBook(created.contacts)}}});};
 const prepare=()=>{try{onChange(buildPrintMergeProject(project,settings));onClose();}catch{}}
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={st.back}><View style={st.modal}>
  <View style={st.header}><View><Text style={st.title}>Labels, Cards & Mail Merge Printing</Text><Text style={st.sub}>Avery layouts, recipient groups, imposition and print sequencing</Text></View><Pressable onPress={onClose}><Ionicons name="close" size={24}/></Pressable></View>
  <View style={st.tabs}>{(["layouts","recipients","print"] as const).map((item)=><Pressable key={item} style={[st.tab,tab===item&&st.tabOn]} onPress={()=>setTab(item)}><Text style={[st.tabText,tab===item&&st.tabTextOn]}>{item==="layouts"?"Labels & Cards":item==="recipients"?"Address Book":"Print Setup"}</Text></Pressable>)}</View>
  <ScrollView contentContainerStyle={st.content}>
   {tab==="layouts"&&<><Text style={st.section}>Professional layouts</Text><View style={st.grid}>{LABEL_TEMPLATES.map((item)=><Pressable key={item.id} style={[st.card,item.id===settings.templateId&&st.cardOn]} onPress={()=>patch({templateId:item.id})}><Text style={st.cardTitle}>{item.manufacturer} {item.productCode??""}</Text><Text style={st.cardName}>{item.name}</Text><Text style={st.meta}>{item.columns} × {item.rows} · {item.columns*item.rows} per sheet</Text><Text style={st.meta}>{item.itemWidthIn} × {item.itemHeightIn} in</Text></Pressable>)}</View></>}
   {tab==="recipients"&&<><View style={st.rowBetween}><View><Text style={st.section}>Recipient manager</Text><Text style={st.meta}>{book.contacts.length} contacts · {book.groups.length} groups · {book.validationIssues.length} validation issues</Text></View><Pressable style={st.primary} onPress={importRecipients} disabled={!source}><Text style={st.primaryText}>Import active source</Text></Pressable></View><View style={st.groupBox}><TextInput style={st.input} value={groupName} onChangeText={setGroupName} placeholder="Contact group name"/><Pressable style={st.button} onPress={makeGroup}><Text style={st.buttonText}>Create group from all contacts</Text></Pressable></View>{book.groups.map((group)=><Pressable key={group.id} style={[st.contact,settings.selectedGroupId===group.id&&st.cardOn]} onPress={()=>patch({selectedGroupId:settings.selectedGroupId===group.id?undefined:group.id})}><Text style={st.cardTitle}>{group.name}</Text><Text style={st.meta}>{group.contactIds.length} recipients</Text></Pressable>)}{book.contacts.slice(0,100).map((contact)=><View key={contact.id} style={st.contact}><Text style={st.cardTitle}>{contact.values.full_name||contact.values.name||contact.values.company||contact.values.email||"Unnamed recipient"}</Text><Text style={st.meta}>{contact.values.address||contact.values.address_1||contact.values.street||"No street address"} · {contact.values.city||"No city"}</Text></View>)}</>}
   {tab==="print"&&<><Text style={st.section}>Print job settings</Text><Text style={st.summaryTitle}>{template.name}</Text><View style={st.formRow}><Text style={st.label}>Copies per recipient</Text><TextInput style={st.number} keyboardType="numeric" value={String(settings.copies)} onChangeText={(value)=>patch({copies:Math.max(1,Number(value)||1)})}/></View><View style={st.formRow}><Text style={st.label}>Starting label position</Text><TextInput style={st.number} keyboardType="numeric" value={String(settings.startPosition)} onChangeText={(value)=>patch({startPosition:Math.max(0,Math.min(template.columns*template.rows-1,Number(value)||0))})}/></View>{[["Duplex printing","duplex"],["Include duplicate records","includeDuplicates"],["Crop marks","cropMarks"],["Print backgrounds","printBackgrounds"]].map(([label,key])=><Pressable key={key} style={st.toggle} onPress={()=>patch({[key]:!settings[key as keyof MergePrintSettings]} as Partial<MergePrintSettings>)}><Ionicons name={settings[key as keyof MergePrintSettings]?"checkbox":"square-outline"} size={20} color="#007D76"/><Text>{label}</Text></Pressable>)}<View style={st.options}>{(["record-major","sheet-major"] as const).map((value)=><Pressable key={value} style={[st.chip,settings.sequencing===value&&st.chipOn]} onPress={()=>patch({sequencing:value})}><Text>{value==="record-major"?"Copies together":"Collated sheets"}</Text></Pressable>)}</View>{estimate&&<View style={st.summary}><Text style={st.summaryTitle}>Print job summary</Text><Text>{estimate.records} recipients · {estimate.impressions} impressions</Text><Text>{estimate.sheets} sheets · {estimate.pages} print pages</Text><Text>{estimate.slotsPerSheet} items per sheet · {estimate.unusedSlots} unused positions</Text></View>}<Pressable style={st.prepare} onPress={prepare} disabled={!estimate?.records}><Ionicons name="print-outline" size={18} color="white"/><Text style={st.primaryText}>Create print-ready publication</Text></Pressable></>}
  </ScrollView><View style={st.footer}><Text style={st.meta}>The print-ready publication uses the real editor, merge resolver, and export/print system.</Text><Pressable style={st.button} onPress={onClose}><Text style={st.buttonText}>Close</Text></Pressable></View>
 </View></View></Modal>
}
const st=StyleSheet.create({back:{flex:1,backgroundColor:"rgba(15,23,42,.58)",alignItems:"center",justifyContent:"center",padding:20},modal:{width:"92%",maxWidth:1050,height:"86%",backgroundColor:"#F8FAFC",borderRadius:14,overflow:"hidden"},header:{padding:18,backgroundColor:"white",flexDirection:"row",justifyContent:"space-between",alignItems:"center",borderBottomWidth:1,borderBottomColor:"#E2E8F0"},title:{fontSize:19,fontWeight:"800",color:"#0F172A"},sub:{fontSize:11,color:"#64748B",marginTop:3},tabs:{flexDirection:"row",backgroundColor:"white",paddingHorizontal:18,gap:6},tab:{paddingHorizontal:14,paddingVertical:11,borderBottomWidth:3,borderBottomColor:"transparent"},tabOn:{borderBottomColor:"#007D76"},tabText:{fontSize:12,fontWeight:"700",color:"#64748B"},tabTextOn:{color:"#007D76"},content:{padding:18,gap:12},section:{fontSize:15,fontWeight:"800",color:"#0F172A"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{width:"31.8%",minWidth:220,padding:13,borderWidth:1,borderColor:"#CBD5E1",backgroundColor:"white",borderRadius:9},cardOn:{borderColor:"#007D76",backgroundColor:"#ECFDF5"},cardTitle:{fontSize:12,fontWeight:"800",color:"#1E293B"},cardName:{fontSize:11,color:"#334155",marginTop:4},meta:{fontSize:10,color:"#64748B",marginTop:3},rowBetween:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},primary:{backgroundColor:"#007D76",paddingHorizontal:14,paddingVertical:9,borderRadius:7},primaryText:{color:"white",fontSize:12,fontWeight:"800"},groupBox:{flexDirection:"row",gap:8},input:{flex:1,height:38,borderWidth:1,borderColor:"#CBD5E1",backgroundColor:"white",borderRadius:7,paddingHorizontal:10},button:{paddingHorizontal:14,paddingVertical:9,borderWidth:1,borderColor:"#CBD5E1",backgroundColor:"white",borderRadius:7},buttonText:{fontSize:11,fontWeight:"700",color:"#334155"},contact:{padding:10,borderWidth:1,borderColor:"#E2E8F0",backgroundColor:"white",borderRadius:7},formRow:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingVertical:6},label:{fontSize:12,fontWeight:"700",color:"#334155"},number:{width:90,height:36,borderWidth:1,borderColor:"#CBD5E1",backgroundColor:"white",borderRadius:7,paddingHorizontal:10,textAlign:"right"},toggle:{flexDirection:"row",alignItems:"center",gap:8,paddingVertical:5},options:{flexDirection:"row",gap:8},chip:{paddingHorizontal:12,paddingVertical:8,borderWidth:1,borderColor:"#CBD5E1",backgroundColor:"white",borderRadius:7},chipOn:{borderColor:"#007D76",backgroundColor:"#CCFBF1"},summary:{padding:14,backgroundColor:"white",borderWidth:1,borderColor:"#E2E8F0",borderRadius:9,gap:5},summaryTitle:{fontSize:13,fontWeight:"800",color:"#0F172A"},prepare:{backgroundColor:"#0F172A",padding:13,borderRadius:8,flexDirection:"row",gap:8,alignItems:"center",justifyContent:"center"},footer:{padding:14,backgroundColor:"white",borderTopWidth:1,borderTopColor:"#E2E8F0",flexDirection:"row",justifyContent:"space-between",alignItems:"center"}});
