import { Ionicons } from "@expo/vector-icons";
import { useRef, useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherProject } from "../../types/publisher";
import { DEFAULT_MERGE_BATCH_SETTINGS, executeMergeBatch, getBatchRecords, type MergeBatchFormat, type MergeBatchHistoryItem, type MergeBatchSettings } from "../../utils/mailMergeBatchEngine";

type Props={visible:boolean;project:PublisherProject;onChange:(project:PublisherProject)=>void;onClose:()=>void};
export default function MailMergeBatchModal({visible,project,onChange,onClose}:Props){
 const data=project.mailMergeData; const saved=data?.batchSettings;
 const [settings,setSettings]=useState<MergeBatchSettings>(saved??DEFAULT_MERGE_BATCH_SETTINGS); const [busy,setBusy]=useState(false); const [progress,setProgress]=useState(0); const [step,setStep]=useState(""); const [error,setError]=useState(""); const cancelled=useRef(false);
 const records=data?getBatchRecords(data,settings.includeDuplicates):[]; const history=data?.batchHistory??[];
 const patch=(next:Partial<MergeBatchSettings>)=>{const value={...settings,...next};setSettings(value);if(data)onChange({...project,updatedAt:Date.now(),mailMergeData:{...data,batchSettings:value}});};
 const addHistory=(item:MergeBatchHistoryItem)=>{if(data)onChange({...project,updatedAt:Date.now(),mailMergeData:{...data,batchSettings:settings,batchHistory:[item,...history].slice(0,50)}});};
 const run=async()=>{setBusy(true);setError("");setProgress(0);cancelled.current=false;try{const result=await executeMergeBatch(project,settings,(p,s)=>{setProgress(p);setStep(s)},()=>cancelled.current);addHistory(result.history);}catch(reason){const err=reason as Error&{history?:MergeBatchHistoryItem};setError(err.message);if(err.history)addHistory(err.history);}finally{setBusy(false)}};
 const toggle=(format:MergeBatchFormat)=>patch({formats:settings.formats.includes(format)?settings.formats.filter(x=>x!==format):[...settings.formats,format]});
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.backdrop}><View style={s.modal}><View style={s.header}><View><Text style={s.title}>Batch Merge & Export</Text><Text style={s.sub}>Generate individual publications or one combined document</Text></View><Pressable onPress={onClose}><Ionicons name="close" size={24}/></Pressable></View><ScrollView contentContainerStyle={s.body}>
 <Text style={s.label}>Output mode</Text><View style={s.row}>{(["individual","combined"] as const).map(mode=><Pressable key={mode} style={[s.choice,settings.mode===mode&&s.active]} onPress={()=>patch({mode})}><Text style={s.choiceText}>{mode==="individual"?"One publication per record":"One combined document"}</Text></Pressable>)}</View>
 <Text style={s.label}>Formats</Text><View style={s.row}>{(["pdf","png","jpg","svg"] as MergeBatchFormat[]).map(format=><Pressable key={format} style={[s.format,settings.formats.includes(format)&&s.active]} onPress={()=>toggle(format)}><Text style={s.choiceText}>{format.toUpperCase()}</Text></Pressable>)}</View>
 <Text style={s.label}>File name template</Text><TextInput style={s.input} value={settings.fileNameTemplate} onChangeText={fileNameTemplate=>patch({fileNameTemplate})}/><Text style={s.hint}>Tokens: {'{project}'} {'{record}'} {'{format}'} {'{number}'} {'{date}'}</Text>
 <View style={s.row}><Pressable style={[s.choice,settings.includeDuplicates&&s.active]} onPress={()=>patch({includeDuplicates:!settings.includeDuplicates})}><Text style={s.choiceText}>Include duplicate records</Text></Pressable><Pressable style={[s.choice,settings.generateReport&&s.active]} onPress={()=>patch({generateReport:!settings.generateReport})}><Text style={s.choiceText}>Generate export report</Text></Pressable></View>
 <View style={s.summary}><Text style={s.summaryTitle}>Generation summary</Text><Text>{records.length} records · {project.pages.length} template pages · {settings.mode==="combined"?1:records.length} publication(s)</Text><Text>{settings.mode==="combined"?records.length*project.pages.length:project.pages.length} pages per combined output · {settings.formats.length} format(s)</Text></View>
 {busy&&<View style={s.progress}><ActivityIndicator/><Text>{progress}% · {step}</Text><Pressable style={s.cancel} onPress={()=>{cancelled.current=true;setStep("Cancelling…")}}><Text style={s.cancelText}>Cancel</Text></Pressable></View>}{!!error&&<Text style={s.error}>{error}</Text>}
 <Pressable style={[s.run,(!records.length||!settings.formats.length||busy)&&s.disabled]} disabled={!records.length||!settings.formats.length||busy} onPress={()=>void run()}><Ionicons name="layers-outline" size={18} color="white"/><Text style={s.runText}>Generate & Export Batch</Text></Pressable>
 <Text style={s.label}>Merge history</Text>{history.length===0?<Text style={s.hint}>No batch jobs yet.</Text>:history.map(item=><View key={item.id} style={s.history}><Text style={s.historyTitle}>{item.sourceName} · {item.mode}</Text><Text style={s.hint}>{new Date(item.createdAt).toLocaleString()} · {item.recordCount} records · {item.pageCount} pages · {item.formats.join(", ").toUpperCase()}</Text><Text style={[s.hint,item.status==="failed"&&s.error]}>{item.status.toUpperCase()} · {item.files.length} files · {(item.durationMs/1000).toFixed(1)}s</Text></View>)}</ScrollView></View></View></Modal>
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(15,23,42,.62)",alignItems:"center",justifyContent:"center",padding:24},modal:{width:"92%",maxWidth:850,maxHeight:"88%",backgroundColor:"#F8FAFC",borderRadius:14,overflow:"hidden"},header:{padding:18,backgroundColor:"white",borderBottomWidth:1,borderBottomColor:"#E2E8F0",flexDirection:"row",justifyContent:"space-between"},title:{fontSize:20,fontWeight:"800"},sub:{fontSize:12,color:"#64748B",marginTop:3},body:{padding:18,gap:12},label:{fontSize:12,fontWeight:"800",color:"#334155",marginTop:5},row:{flexDirection:"row",flexWrap:"wrap",gap:8},choice:{paddingHorizontal:12,paddingVertical:9,borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,backgroundColor:"white"},format:{width:74,paddingVertical:10,alignItems:"center",borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,backgroundColor:"white"},active:{backgroundColor:"#CCFBF1",borderColor:"#0F766E"},choiceText:{fontSize:11,fontWeight:"700",color:"#334155"},input:{height:40,borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,backgroundColor:"white",paddingHorizontal:12},hint:{fontSize:10,color:"#64748B"},summary:{padding:13,borderRadius:9,backgroundColor:"#EFF6FF",gap:4},summaryTitle:{fontSize:12,fontWeight:"800",color:"#1E3A8A"},progress:{padding:12,borderRadius:8,backgroundColor:"white",flexDirection:"row",alignItems:"center",gap:10},cancel:{marginLeft:"auto",padding:7,backgroundColor:"#FEE2E2",borderRadius:6},cancelText:{color:"#B91C1C",fontWeight:"700",fontSize:11},error:{color:"#B42318",fontSize:11},run:{height:44,borderRadius:9,backgroundColor:"#007D76",alignItems:"center",justifyContent:"center",flexDirection:"row",gap:8},disabled:{opacity:.45},runText:{color:"white",fontWeight:"800"},history:{padding:11,borderWidth:1,borderColor:"#E2E8F0",borderRadius:8,backgroundColor:"white",gap:3},historyTitle:{fontSize:11,fontWeight:"800",color:"#1E293B"}});
