import { useEffect, useMemo, useState } from "react";
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { normalizePaintingSettings, type PaintingSettings } from "../../utils/paintingEngine";
import { BUILT_IN_BRUSH_LIBRARY, createCustomBrush, duplicateBrush, exportBrushPack, importBrushPack, loadBrushLibrary, saveBrushLibrary, type BrushCategory, type BrushLibraryItem } from "../../utils/brushLibrary";

const Field=({label,value,onChange,min=0,max=100}:{label:string;value:number;onChange:(value:number)=>void;min?:number;max?:number})=><View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} value={String(Math.round(value*100)/100)} keyboardType="numeric" onChangeText={text=>onChange(Math.max(min,Math.min(max,Number(text)||0)))} /></View>;
const Toggle=({label,value,onPress}:{label:string;value:boolean;onPress:()=>void})=><Pressable style={[styles.toggle,value&&styles.toggleOn]} onPress={onPress}><Text style={[styles.toggleText,value&&styles.toggleTextOn]}>{value?"✓ ":""}{label}</Text></Pressable>;

type Tool="pencil"|"brush"|"calligraphy"|"marker"|"crayon"|"airbrush"|"highlighter";
type Props={visible:boolean;settings:PaintingSettings;hasSelection:boolean;onChange:(settings:PaintingSettings)=>void;onApplyToSelection:()=>void;onChooseTool:(tool:Tool)=>void;onClose:()=>void};
export default function PaintingStudioModal({visible,settings,hasSelection,onChange,onApplyToSelection,onChooseTool,onClose}:Props){
 const s=normalizePaintingSettings(settings); const patch=(p:Partial<PaintingSettings>)=>onChange(normalizePaintingSettings({...s,...p}));
 const [library,setLibrary]=useState<BrushLibraryItem[]>(BUILT_IN_BRUSH_LIBRARY); const [search,setSearch]=useState(""); const [category,setCategory]=useState<"All"|BrushCategory>("All"); const [packText,setPackText]=useState(""); const [customName,setCustomName]=useState("My Brush");
 useEffect(()=>{if(visible) void loadBrushLibrary().then(setLibrary)},[visible]);
 const persist=(next:BrushLibraryItem[])=>{setLibrary(next);void saveBrushLibrary(next)};
 const filtered=useMemo(()=>library.filter(item=>(category==="All"||item.category===category)&&(`${item.name} ${item.tags?.join(" ")??""}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>Number(Boolean(b.favorite))-Number(Boolean(a.favorite))+(b.recentAt??0)-(a.recentAt??0)),[library,search,category]);
 const choose=(item:BrushLibraryItem)=>{onChange(normalizePaintingSettings({...s,...item,presetId:item.presetId}));onChooseTool(item.tool);persist(library.map(entry=>entry.presetId===item.presetId?{...entry,recentAt:Date.now()}:entry));};
 const selected=library.find(item=>item.presetId===s.presetId);
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.panel}>
  <View style={styles.header}><View><Text style={styles.title}>Professional Brush Studio</Text><Text style={styles.sub}>Persistent library, custom presets, pressure, velocity, prediction, jitter and dual-brush controls</Text></View><Pressable onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View>
  <ScrollView contentContainerStyle={styles.body}>
   <Text style={styles.section}>Brush Library</Text><View style={styles.row}><TextInput style={[styles.input,{flex:1}]} value={search} onChangeText={setSearch} placeholder="Search brushes, tips or textures"/><Pressable style={styles.secondary} onPress={()=>setCategory(category==="All"?"Inking":"All")}><Text style={styles.secondaryText}>{category}</Text></Pressable></View>
   <ScrollView horizontal showsHorizontalScrollIndicator={false}><View style={styles.row}>{(["All","Inking","Painting","Wet Media","Dry Media","Airbrush","Lettering","Markers","Special"] as const).map(value=><Pressable key={value} style={[styles.chip,category===value&&styles.chipOn]} onPress={()=>setCategory(value)}><Text style={[styles.chipText,category===value&&styles.chipTextOn]}>{value}</Text></Pressable>)}</View></ScrollView>
   <View style={styles.grid}>{filtered.map(item=><Pressable key={item.presetId} style={[styles.preset,s.presetId===item.presetId&&styles.active]} onPress={()=>choose(item)}><View style={styles.presetTop}><Text style={styles.presetName}>{item.name}</Text><Pressable onPress={()=>persist(library.map(entry=>entry.presetId===item.presetId?{...entry,favorite:!entry.favorite}:entry))}><Text>{item.favorite?"★":"☆"}</Text></Pressable></View><Text style={styles.meta}>{item.category} · {item.tip} · {item.size}px</Text></Pressable>)}</View>
   <View style={styles.actions}><TextInput style={[styles.input,{minWidth:180}]} value={customName} onChangeText={setCustomName}/><Pressable style={styles.primary} onPress={()=>{const item=createCustomBrush(customName,s);persist([...library,item]);choose(item)}}><Text style={styles.primaryText}>Save Custom Brush</Text></Pressable><Pressable style={styles.secondary} disabled={!selected} onPress={()=>selected&&persist([...library,duplicateBrush(selected)])}><Text style={styles.secondaryText}>Duplicate</Text></Pressable><Pressable style={[styles.danger,!selected?.custom&&styles.disabled]} disabled={!selected?.custom} onPress={()=>selected&&persist(library.filter(item=>item.presetId!==selected.presetId))}><Text style={styles.dangerText}>Delete Custom</Text></Pressable></View>
   <Text style={styles.section}>Color & Core Dynamics</Text><View style={styles.row}><TextInput style={[styles.colorInput,{backgroundColor:s.color}]} value={s.color} onChangeText={color=>patch({color})}/><TextInput style={[styles.colorInput,{backgroundColor:s.secondaryColor}]} value={s.secondaryColor} onChangeText={secondaryColor=>patch({secondaryColor})}/></View>
   <View style={styles.fields}><Field label="Size" value={s.size} min={1} max={500} onChange={size=>patch({size})}/><Field label="Opacity %" value={s.opacity*100} onChange={v=>patch({opacity:v/100})}/><Field label="Flow %" value={s.flow*100} onChange={v=>patch({flow:v/100})}/><Field label="Hardness %" value={s.hardness*100} onChange={v=>patch({hardness:v/100})}/><Field label="Spacing %" value={s.spacing*100} max={200} onChange={v=>patch({spacing:v/100})}/><Field label="Smoothing %" value={s.smoothing*100} onChange={v=>patch({smoothing:v/100})}/><Field label="Prediction %" value={s.strokePrediction*100} onChange={v=>patch({strokePrediction:v/100})}/><Field label="Scatter %" value={s.scatter*100} max={200} onChange={v=>patch({scatter:v/100})}/></View>
   <Text style={styles.section}>Professional Input Dynamics</Text><View style={styles.toggleRow}><Toggle label="Pressure Size" value={s.pressureSize} onPress={()=>patch({pressureSize:!s.pressureSize})}/><Toggle label="Pressure Opacity" value={s.pressureOpacity} onPress={()=>patch({pressureOpacity:!s.pressureOpacity})}/><Toggle label="Dual Brush" value={s.dualBrush} onPress={()=>patch({dualBrush:!s.dualBrush})}/></View>
   <View style={styles.fields}><Field label="Velocity Size %" value={s.velocitySize*100} onChange={v=>patch({velocitySize:v/100})}/><Field label="Velocity Opacity %" value={s.velocityOpacity*100} onChange={v=>patch({velocityOpacity:v/100})}/><Field label="Tilt Size %" value={s.tiltSize*100} onChange={v=>patch({tiltSize:v/100})}/><Field label="Size Jitter %" value={s.sizeJitter*100} onChange={v=>patch({sizeJitter:v/100})}/><Field label="Opacity Jitter %" value={s.opacityJitter*100} onChange={v=>patch({opacityJitter:v/100})}/><Field label="Rotation Jitter" value={s.rotationJitter} max={180} onChange={rotationJitter=>patch({rotationJitter})}/><Field label="Dual Scale" value={s.dualBrushScale} min={.1} max={4} onChange={dualBrushScale=>patch({dualBrushScale})}/><Field label="Wet Mix %" value={s.wetMix*100} onChange={v=>patch({wetMix:v/100})}/><Field label="Angle" value={s.angle} min={-180} max={180} onChange={angle=>patch({angle})}/><Field label="Roundness %" value={s.roundness*100} min={5} onChange={v=>patch({roundness:v/100})}/></View>
   <Text style={styles.section}>Brush Pack Import / Export</Text><TextInput style={styles.pack} multiline value={packText} onChangeText={setPackText} placeholder="Paste a Yaposan brush pack here, or export your custom brushes"/><View style={styles.actions}><Pressable style={styles.secondary} onPress={()=>setPackText(exportBrushPack(library.filter(item=>item.custom)))}><Text style={styles.secondaryText}>Export Custom Pack</Text></Pressable><Pressable style={styles.secondary} onPress={()=>{try{persist([...library,...importBrushPack(packText)]);Alert.alert("Brush pack imported")}catch(error){Alert.alert("Import failed",error instanceof Error?error.message:"Invalid brush pack")}}}><Text style={styles.secondaryText}>Import Pack</Text></Pressable></View>
   <View style={styles.actions}><Pressable style={styles.primary} onPress={()=>onChooseTool(selected?.tool??"brush")}><Text style={styles.primaryText}>Use Brush</Text></Pressable><Pressable disabled={!hasSelection} style={[styles.secondary,!hasSelection&&styles.disabled]} onPress={onApplyToSelection}><Text style={styles.secondaryText}>Apply to Selected Stroke</Text></Pressable></View>
  </ScrollView>
 </View></View></Modal>
}
const styles=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(2,6,23,.76)",alignItems:"center",justifyContent:"center",padding:20},panel:{width:"95%",maxWidth:1040,maxHeight:"94%",backgroundColor:"#F8FAFC",borderRadius:18,overflow:"hidden",borderWidth:1,borderColor:"#334155"},header:{backgroundColor:"#0F172A",padding:18,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"#FFF",fontSize:20,fontWeight:"900"},sub:{color:"#94A3B8",fontSize:12,marginTop:4},close:{width:34,height:34,borderRadius:17,backgroundColor:"#334155",alignItems:"center",justifyContent:"center"},closeText:{color:"#FFF",fontSize:24},body:{padding:18,gap:12},section:{fontSize:13,fontWeight:"900",color:"#0F172A",marginTop:6},grid:{flexDirection:"row",flexWrap:"wrap",gap:9},preset:{width:180,padding:11,borderRadius:12,backgroundColor:"#FFF",borderWidth:1,borderColor:"#CBD5E1"},active:{borderColor:"#7C3AED",borderWidth:2,backgroundColor:"#F5F3FF"},presetTop:{flexDirection:"row",justifyContent:"space-between"},presetName:{fontWeight:"800",color:"#172033",flex:1},meta:{fontSize:10,color:"#64748B",marginTop:3},row:{flexDirection:"row",gap:9,alignItems:"center"},chip:{paddingHorizontal:11,paddingVertical:7,borderRadius:16,backgroundColor:"#E2E8F0"},chipOn:{backgroundColor:"#6D28D9"},chipText:{fontSize:11,fontWeight:"800",color:"#334155"},chipTextOn:{color:"#FFF"},colorInput:{flex:1,minHeight:42,borderRadius:10,borderWidth:1,borderColor:"#94A3B8",paddingHorizontal:12,color:"#FFF",fontWeight:"900",textShadowColor:"#000",textShadowRadius:3},fields:{flexDirection:"row",flexWrap:"wrap",gap:9},field:{width:150},label:{fontSize:10,fontWeight:"800",color:"#475569",marginBottom:4},input:{backgroundColor:"#FFF",borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,paddingHorizontal:10,paddingVertical:8,color:"#0F172A"},toggleRow:{flexDirection:"row",flexWrap:"wrap",gap:8},toggle:{paddingHorizontal:12,paddingVertical:8,borderRadius:9,backgroundColor:"#E2E8F0",borderWidth:1,borderColor:"#CBD5E1"},toggleOn:{backgroundColor:"#DDD6FE",borderColor:"#7C3AED"},toggleText:{fontWeight:"800",color:"#475569",fontSize:11},toggleTextOn:{color:"#5B21B6"},actions:{flexDirection:"row",flexWrap:"wrap",gap:9,marginTop:5},primary:{backgroundColor:"#7C3AED",paddingHorizontal:16,paddingVertical:11,borderRadius:10},primaryText:{color:"#FFF",fontWeight:"900"},secondary:{backgroundColor:"#E2E8F0",paddingHorizontal:14,paddingVertical:10,borderRadius:10},secondaryText:{color:"#172033",fontWeight:"900"},danger:{backgroundColor:"#FEE2E2",paddingHorizontal:14,paddingVertical:10,borderRadius:10},dangerText:{color:"#B91C1C",fontWeight:"900"},pack:{minHeight:90,backgroundColor:"#FFF",borderWidth:1,borderColor:"#CBD5E1",borderRadius:10,padding:10,textAlignVertical:"top",fontFamily:"monospace"},disabled:{opacity:.42}});
