import React from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherElement } from "../../types/publisher";
import { normalizePaintingCompletionSettings, type PaintingCompletionSettings } from "../../utils/paintingCompletionEngine";

type Props={visible:boolean;settings:PaintingCompletionSettings;element:PublisherElement|null;onChange:(settings:PaintingCompletionSettings)=>void;onApply:()=>void;onAddLayer:()=>void;onClose:()=>void};
const choices=<T extends string>(values:T[],selected:T,onSelect:(value:T)=>void)=><View style={styles.row}>{values.map(value=><Pressable key={value} style={[styles.chip,selected===value&&styles.chipActive]} onPress={()=>onSelect(value)}><Text style={[styles.chipText,selected===value&&styles.chipTextActive]}>{value}</Text></Pressable>)}</View>;
export default function PaintingCompletionModal({visible,settings,element,onChange,onApply,onAddLayer,onClose}:Props){
 const update=(patch:Partial<PaintingCompletionSettings>)=>onChange(normalizePaintingCompletionSettings({...settings,...patch}));
 const numberField=(label:string,key:keyof PaintingCompletionSettings)=><View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} keyboardType="numeric" value={String(settings[key])} onChangeText={text=>update({[key]:Number(text)} as Partial<PaintingCompletionSettings>)}/></View>;
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.panel}><View style={styles.header}><View><Text style={styles.title}>Painting Completion</Text><Text style={styles.subtitle}>Layers, masks, symmetry, perspective and seamless production</Text></View><Pressable onPress={onClose}><Text style={styles.close}>Close</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}>
 <Text style={styles.section}>Paint Layer</Text><TextInput style={styles.input} value={settings.layerName} onChangeText={layerName=>update({layerName})}/>{numberField("Opacity", "layerOpacity")}<Text style={styles.label}>Blend mode</Text>{choices(["normal","multiply","screen","overlay","soft-light","hard-light","color-dodge","color-burn"],settings.layerBlendMode,value=>update({layerBlendMode:value}))}
 <Text style={styles.section}>Masks</Text>{choices(["none","layer-mask","clipping-mask","alpha-lock"],settings.maskMode,value=>update({maskMode:value}))}
 <Text style={styles.section}>Symmetry</Text>{choices(["none","horizontal","vertical","quadrant","radial"],settings.symmetryMode,value=>update({symmetryMode:value}))}{numberField("Radial segments", "radialSegments")}{numberField("Symmetry angle", "symmetryAngle")}
 <Text style={styles.section}>Perspective painting</Text>{choices(["none","one-point","two-point","three-point"],settings.perspectiveMode,value=>update({perspectiveMode:value}))}{numberField("Perspective snap", "perspectiveSnap")}
 <Text style={styles.section}>Pattern painting</Text>{choices(["off","on"],settings.patternEnabled?"on":"off",value=>update({patternEnabled:value==="on"}))}{numberField("Pattern width", "patternWidth")}{numberField("Pattern height", "patternHeight")}{choices(["seamless","fixed"],settings.seamlessWrap?"seamless":"fixed",value=>update({seamlessWrap:value==="seamless"}))}
 <Text style={styles.section}>Production</Text>{choices(["editable strokes","flatten strokes"],settings.strokeEditable?"editable strokes":"flatten strokes",value=>update({strokeEditable:value==="editable strokes"}))}{choices(["preserve vectors","rasterize"],settings.preserveVectors?"preserve vectors":"rasterize",value=>update({preserveVectors:value==="preserve vectors"}))}{choices(["metadata on","metadata off"],settings.exportPaintMetadata?"metadata on":"metadata off",value=>update({exportPaintMetadata:value==="metadata on"}))}
 <Text style={styles.summary}>Selected object: {element?.name ?? "None"} · Layers: {element?.paintLayers?.length ?? 0}</Text>
 </ScrollView><View style={styles.footer}><Pressable style={styles.secondary} disabled={!element} onPress={onAddLayer}><Text style={styles.secondaryText}>Add Paint Layer</Text></Pressable><Pressable style={[styles.primary,!element&&styles.disabled]} disabled={!element} onPress={onApply}><Text style={styles.primaryText}>Apply Completion Settings</Text></Pressable></View></View></View></Modal>;
}
const styles=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(8,15,30,.72)",alignItems:"center",justifyContent:"center",padding:24},panel:{width:"92%",maxWidth:980,maxHeight:"92%",backgroundColor:"#f7f9fc",borderRadius:18,overflow:"hidden"},header:{padding:20,backgroundColor:"#172033",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"white",fontSize:20,fontWeight:"800"},subtitle:{color:"#b9c6dc",marginTop:4},close:{color:"#fff",fontWeight:"700"},content:{padding:20},section:{fontSize:15,fontWeight:"800",color:"#172033",marginTop:14,marginBottom:8},label:{fontSize:12,fontWeight:"700",color:"#526078",marginBottom:5},row:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:10},chip:{borderWidth:1,borderColor:"#c7cfdb",borderRadius:20,paddingHorizontal:11,paddingVertical:7,backgroundColor:"white"},chipActive:{backgroundColor:"#2157d5",borderColor:"#2157d5"},chipText:{fontSize:12,color:"#27354d",textTransform:"capitalize"},chipTextActive:{color:"white",fontWeight:"700"},field:{marginBottom:10},input:{borderWidth:1,borderColor:"#c7cfdb",borderRadius:8,backgroundColor:"white",paddingHorizontal:10,paddingVertical:8,color:"#172033",marginBottom:8},summary:{marginTop:16,padding:12,backgroundColor:"#e9eef8",borderRadius:8,color:"#33445f"},footer:{flexDirection:"row",justifyContent:"flex-end",gap:10,padding:16,borderTopWidth:1,borderTopColor:"#dce2ec"},primary:{backgroundColor:"#2157d5",paddingHorizontal:18,paddingVertical:11,borderRadius:9},primaryText:{color:"white",fontWeight:"800"},secondary:{backgroundColor:"#e7ecf5",paddingHorizontal:18,paddingVertical:11,borderRadius:9},secondaryText:{color:"#22324a",fontWeight:"800"},disabled:{opacity:.45}});
