import { Ionicons } from "@expo/vector-icons";
import { Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import type { PublisherElement } from "../../types/publisher";
import { PARAGRAPH_STYLE_PRESETS,clampParagraph,formatListText } from "../../utils/paragraphTypography";
type Props={visible:boolean;element:PublisherElement|null;onChange:(u:Partial<PublisherElement>)=>void;onClose:()=>void};
const Toggle=({label,active,onPress}:{label:string;active:boolean;onPress:()=>void})=><Pressable onPress={onPress} style={[s.toggle,active&&s.on]}><Text style={s.txt}>{label}</Text></Pressable>;
const Num=({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(v:number)=>void})=><View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={String(value)} keyboardType="numeric" onChangeText={t=>onChange(clampParagraph(Number(t),min,max))} style={s.input}/></View>;
export default function ParagraphTypographyModal({visible,element,onChange,onClose}:Props){if(!element)return null;return <Modal visible={visible} transparent animationType="fade"><View style={s.overlay}><View style={s.card}><View style={s.header}><View><Text style={s.title}>Paragraph & Layout Typography</Text><Text style={s.sub}>Professional spacing, lists, columns and flow</Text></View><Pressable onPress={onClose}><Ionicons name="close" size={22} color="#CBD5E1"/></Pressable></View><ScrollView contentContainerStyle={s.content}>
<Text style={s.section}>Alignment and flow</Text><View style={s.wrap}>{(["left","center","right","justify"] as const).map(v=><Toggle key={v} label={v} active={(element.textAlign??"left")===v} onPress={()=>onChange({textAlign:v})}/>)}<Toggle label="Hyphenation" active={!!element.hyphenation} onPress={()=>onChange({hyphenation:!element.hyphenation})}/><Toggle label="Distribute" active={element.justification==="distribute"} onPress={()=>onChange({justification:element.justification==="distribute"?"normal":"distribute",textAlign:"justify"})}/></View>
<Text style={s.section}>Spacing and indents</Text><View style={s.row}><Num label="Line height" value={element.lineHeight??1.2} min={.7} max={4} onChange={lineHeight=>onChange({lineHeight})}/><Num label="Before" value={element.paragraphSpacingBefore??0} min={0} max={200} onChange={paragraphSpacingBefore=>onChange({paragraphSpacingBefore})}/><Num label="After" value={element.paragraphSpacingAfter??0} min={0} max={200} onChange={paragraphSpacingAfter=>onChange({paragraphSpacingAfter})}/><Num label="First line" value={element.firstLineIndent??0} min={-200} max={400} onChange={firstLineIndent=>onChange({firstLineIndent})}/><Num label="Hanging" value={element.hangingIndent??0} min={0} max={200} onChange={hangingIndent=>onChange({hangingIndent})}/><Num label="Left indent" value={element.leftIndent??0} min={0} max={400} onChange={leftIndent=>onChange({leftIndent})}/><Num label="Right indent" value={element.rightIndent??0} min={0} max={400} onChange={rightIndent=>onChange({rightIndent})}/></View>
<Text style={s.section}>Lists and drop caps</Text><View style={s.wrap}><Toggle label="No list" active={(element.listType??"none")==="none"} onPress={()=>onChange({listType:"none"})}/><Toggle label="Bullets" active={element.listType==="bullet"} onPress={()=>onChange({listType:"bullet",text:formatListText(element.text??"","bullet")})}/><Toggle label="Numbering" active={element.listType==="number"} onPress={()=>onChange({listType:"number",text:formatListText(element.text??"","number",element.listStart??1)})}/></View><View style={s.row}><Num label="List start" value={element.listStart??1} min={1} max={999} onChange={listStart=>onChange({listStart,text:element.listType==="number"?formatListText(element.text??"","number",listStart):element.text})}/><Num label="Drop cap lines" value={element.dropCapLines??0} min={0} max={10} onChange={dropCapLines=>onChange({dropCapLines})}/></View>
<Text style={s.section}>Columns and baseline grid</Text><View style={s.row}><Num label="Columns" value={element.columnCount??1} min={1} max={6} onChange={columnCount=>onChange({columnCount:Math.round(columnCount)})}/><Num label="Column gap" value={element.columnGap??18} min={0} max={100} onChange={columnGap=>onChange({columnGap})}/><Num label="Grid spacing" value={element.baselineGridSpacing??12} min={4} max={100} onChange={baselineGridSpacing=>onChange({baselineGridSpacing})}/></View><Toggle label="Show baseline grid" active={!!element.baselineGrid} onPress={()=>onChange({baselineGrid:!element.baselineGrid})}/>
<Text style={s.section}>Tab stops</Text><TextInput value={(element.tabStops??[]).join(", ")} placeholder="36, 72, 144" placeholderTextColor="#64748B" onChangeText={t=>onChange({tabStops:t.split(",").map(Number).filter(Number.isFinite)})} style={s.wide}/>
<Text style={s.section}>Paragraph styles</Text><View style={s.wrap}>{PARAGRAPH_STYLE_PRESETS.map(p=><Pressable key={p.id} onPress={()=>onChange({...p.updates,paragraphStyleId:p.id})} style={[s.preset,element.paragraphStyleId===p.id&&s.on]}><Text style={s.txt}>{p.name}</Text></Pressable>)}</View>
</ScrollView><View style={s.footer}><Pressable onPress={onClose} style={s.done}><Text style={s.doneTxt}>Done</Text></Pressable></View></View></View></Modal>}
const s=StyleSheet.create({overlay:{flex:1,backgroundColor:"rgba(2,6,23,.78)",alignItems:"center",justifyContent:"center",padding:24},card:{width:"100%",maxWidth:900,maxHeight:"90%",backgroundColor:"#111827",borderRadius:15,borderWidth:1,borderColor:"#334155"},header:{padding:18,flexDirection:"row",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:"#293548"},title:{color:"#F8FAFC",fontSize:18,fontWeight:"900"},sub:{color:"#94A3B8",fontSize:11},content:{padding:18,gap:12},section:{color:"#5EEAD4",fontSize:9,fontWeight:"900",letterSpacing:1,textTransform:"uppercase"},wrap:{flexDirection:"row",gap:8,flexWrap:"wrap"},row:{flexDirection:"row",gap:10,flexWrap:"wrap"},toggle:{paddingHorizontal:12,paddingVertical:8,borderRadius:16,backgroundColor:"#1E293B",borderWidth:1,borderColor:"#334155"},on:{backgroundColor:"#0F766E",borderColor:"#2DD4BF"},txt:{color:"#F8FAFC",fontSize:10,fontWeight:"800"},field:{width:120},label:{color:"#CBD5E1",fontSize:9,marginBottom:4},input:{height:36,color:"#F8FAFC",backgroundColor:"#0F172A",borderWidth:1,borderColor:"#334155",borderRadius:7,textAlign:"center"},wide:{height:40,color:"#F8FAFC",backgroundColor:"#0F172A",borderWidth:1,borderColor:"#334155",borderRadius:7,paddingHorizontal:10},preset:{padding:12,minWidth:105,borderRadius:8,backgroundColor:"#1E293B",borderWidth:1,borderColor:"#334155"},footer:{padding:14,borderTopWidth:1,borderTopColor:"#293548",alignItems:"flex-end"},done:{backgroundColor:"#E2E8F0",paddingHorizontal:24,paddingVertical:9,borderRadius:8},doneTxt:{color:"#0F172A",fontWeight:"900"}});
