import { Ionicons } from "@expo/vector-icons";
import * as DocumentPicker from "expo-document-picker";
import { File as ExpoFile } from "expo-file-system";
import { useMemo, useState } from "react";
import { Alert, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { addAnnotation, addBookmark, addFormField, createPdfStudioDocument, deletePages, exportPdf, importPdf, reorderPage, rotatePage, validatePdf, type PdfStandard, type PdfStudioDocument } from "../../utils/professionalPdfStudioEngine";

type Props={visible:boolean;projectName:string;onClose:()=>void;onExport:(bytes:Uint8Array,name:string)=>Promise<void>|void};
const standards:PdfStandard[]=["PDF","PDF/A-1b","PDF/A-2b","PDF/A-3b","PDF/X-1a","PDF/X-3","PDF/X-4"];
export default function ProfessionalPdfStudioModal({visible,projectName,onClose,onExport}:Props){
 const [doc,setDoc]=useState<PdfStudioDocument>(()=>createPdfStudioDocument(`${projectName}.pdf`)); const [busy,setBusy]=useState(false); const [selected,setSelected]=useState<string|undefined>(); const [panel,setPanel]=useState<"pages"|"forms"|"annotations"|"metadata"|"security"|"standards">("pages");
 const audit=useMemo(()=>validatePdf(doc),[doc]); const active=doc.pages.find(p=>p.id===selected)||doc.pages[0];
 const pick=async()=>{const result=await DocumentPicker.getDocumentAsync({type:"application/pdf",multiple:false,copyToCacheDirectory:true});if(result.canceled)return;setBusy(true);try{const asset=result.assets[0];const bytes=Platform.OS==="web"?new Uint8Array(await (await fetch(asset.uri)).arrayBuffer()):await new ExpoFile(asset.uri).bytes();const imported=await importPdf(bytes,asset.name||"Imported.pdf");setDoc(imported);setSelected(imported.pages[0]?.id);}catch(e){Alert.alert("PDF import failed",e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const save=async()=>{setBusy(true);try{const bytes=await exportPdf(doc);await onExport(bytes,doc.name.endsWith(".pdf")?doc.name:`${doc.name}.pdf`);}catch(e){Alert.alert("PDF export failed",e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const tool=(label:string,icon:keyof typeof Ionicons.glyphMap,onPress:()=>void,disabled=false)=><Pressable disabled={disabled} onPress={onPress} style={[s.tool,disabled&&s.disabled]}><Ionicons name={icon} size={18} color="#164E63"/><Text style={s.toolText}>{label}</Text></Pressable>;
 return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={s.shell}><View style={s.header}><View><Text style={s.title}>Professional PDF Studio</Text><Text style={s.sub}>{doc.pages.length} pages · readiness {audit.score}%</Text></View><View style={s.row}>{tool("Import","folder-open-outline",()=>void pick())}{tool(busy?"Working…":"Export PDF","download-outline",()=>void save(),busy||!doc.pages.length)}{tool("Close","close-outline",onClose)}</View></View>
 <ScrollView horizontal style={s.tabs} contentContainerStyle={s.tabRow}>{(["pages","forms","annotations","metadata","security","standards"] as const).map(v=><Pressable key={v} onPress={()=>setPanel(v)} style={[s.tab,panel===v&&s.tabActive]}><Text style={[s.tabText,panel===v&&s.tabTextActive]}>{v[0].toUpperCase()+v.slice(1)}</Text></Pressable>)}</ScrollView>
 <View style={s.body}><View style={s.left}><Text style={s.section}>Pages</Text><ScrollView>{doc.pages.map((p,i)=><Pressable key={p.id} onPress={()=>setSelected(p.id)} style={[s.page,p.id===active?.id&&s.pageActive]}><View style={s.thumb}><Text style={s.thumbNo}>{i+1}</Text><Text style={s.rotation}>{p.rotation}°</Text></View><Text style={s.pageLabel}>{p.label}</Text></Pressable>)}</ScrollView></View>
 <ScrollView style={s.main} contentContainerStyle={s.content}>{panel==="pages"&&<><Text style={s.heading}>Page management</Text><View style={s.grid}>{tool("Rotate left","arrow-undo-outline",()=>active&&setDoc(d=>rotatePage(d,active.id,-90)),!active)}{tool("Rotate right","arrow-redo-outline",()=>active&&setDoc(d=>rotatePage(d,active.id,90)),!active)}{tool("Move up","arrow-up-outline",()=>active&&setDoc(d=>reorderPage(d,active.id,Math.max(0,d.pages.findIndex(p=>p.id===active.id)-1))),!active)}{tool("Move down","arrow-down-outline",()=>active&&setDoc(d=>reorderPage(d,active.id,d.pages.findIndex(p=>p.id===active.id)+1)),!active)}{tool("Delete page","trash-outline",()=>active&&setDoc(d=>deletePages(d,[active.id])),!active)}</View><Preview active={active}/></>}
 {panel==="forms"&&<><Text style={s.heading}>Fillable forms</Text><Text style={s.help}>Add production form fields to the selected PDF page.</Text><View style={s.grid}>{["text","checkbox","dropdown","date","signature"].map(kind=>tool(`Add ${kind}`,"create-outline",()=>active&&setDoc(d=>addFormField(d,{pageId:active.id,kind:kind as any,name:`${kind}_${d.fields.length+1}`,x:72,y:72,width:160,height:28,required:false})),!active))}</View><Text style={s.count}>{doc.fields.length} form fields configured</Text></>}
 {panel==="annotations"&&<><Text style={s.heading}>Annotations and review</Text><View style={s.grid}>{["highlight","underline","strikeout","comment","freehand","rectangle","stamp","redaction"].map(kind=>tool(kind,"pencil-outline",()=>active&&setDoc(d=>addAnnotation(d,{pageId:active.id,kind:kind as any,x:72,y:120,width:180,height:30,text:kind})),!active))}</View><Text style={s.count}>{doc.annotations.length} annotations configured</Text></>}
 {panel==="metadata"&&<><Text style={s.heading}>Metadata and navigation</Text>{(["title","author","subject","language","creator","producer"] as const).map(k=><Field key={k} label={k} value={doc.metadata[k]} onChange={v=>setDoc(d=>({...d,metadata:{...d.metadata,[k]:v}}))}/>)}<View style={s.grid}>{tool("Add bookmark","bookmark-outline",()=>active&&setDoc(d=>addBookmark(d,`Page ${d.pages.findIndex(p=>p.id===active.id)+1}`,active.id)),!active)}</View><Text style={s.count}>{doc.bookmarks.length} bookmarks</Text></>}
 {panel==="security"&&<><Text style={s.heading}>Security and signatures</Text><Field label="User password" value={doc.security.userPassword||""} secure onChange={v=>setDoc(d=>({...d,security:{...d.security,userPassword:v}}))}/><Field label="Owner password" value={doc.security.ownerPassword||""} secure onChange={v=>setDoc(d=>({...d,security:{...d.security,ownerPassword:v}}))}/><Text style={s.help}>Password policy and permissions are retained in the PDF Studio document. Native encrypted output requires the desktop signing/encryption adapter.</Text></>}
 {panel==="standards"&&<><Text style={s.heading}>PDF standards and accessibility</Text><View style={s.grid}>{standards.map(v=><Pressable key={v} onPress={()=>setDoc(d=>({...d,standard:v}))} style={[s.standard,doc.standard===v&&s.standardActive]}><Text>{v}</Text></Pressable>)}</View><Text style={s.audit}>{audit.valid?"Ready for validation":"Validation findings"}</Text>{audit.issues.map(v=><Text key={v} style={s.issue}>• {v}</Text>)}<Text style={s.help}>Profiles include metadata, searchable-text, form-flattening, font, print and accessibility preflight rules. Final conformance depends on the source PDF and export adapter.</Text></>}</ScrollView></View></View></Modal>;
}
function Field({label,value,onChange,secure}:{label:string;value:string;onChange:(v:string)=>void;secure?:boolean}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} secureTextEntry={secure} style={s.input}/></View>}
function Preview({active}:{active?:{label:string;width:number;height:number;rotation:number}}){return <View style={s.preview}><Ionicons name="document-text-outline" size={72} color="#0E7490"/><Text style={s.previewTitle}>{active?.label||"Import a PDF"}</Text>{active&&<Text style={s.help}>{Math.round(active.width)} × {Math.round(active.height)} pt · rotation {active.rotation}°</Text>}</View>}
const s=StyleSheet.create({shell:{flex:1,backgroundColor:"#F1F5F9"},header:{minHeight:76,paddingHorizontal:18,paddingVertical:12,backgroundColor:"#0F172A",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"white",fontSize:21,fontWeight:"800"},sub:{color:"#CBD5E1",marginTop:4},row:{flexDirection:"row",gap:8},tabs:{maxHeight:50,backgroundColor:"white"},tabRow:{paddingHorizontal:14,alignItems:"center",gap:6},tab:{paddingHorizontal:16,paddingVertical:10,borderRadius:8},tabActive:{backgroundColor:"#CFFAFE"},tabText:{fontWeight:"700",color:"#475569"},tabTextActive:{color:"#0E7490"},body:{flex:1,flexDirection:"row"},left:{width:180,backgroundColor:"white",borderRightWidth:1,borderColor:"#CBD5E1",padding:12},section:{fontSize:13,fontWeight:"800",marginBottom:10},page:{marginBottom:10,alignItems:"center",padding:6,borderRadius:8},pageActive:{backgroundColor:"#CFFAFE"},thumb:{width:82,height:104,backgroundColor:"white",borderWidth:1,borderColor:"#94A3B8",justifyContent:"center",alignItems:"center"},thumbNo:{fontSize:24,fontWeight:"800",color:"#0F172A"},rotation:{fontSize:11,color:"#64748B"},pageLabel:{fontSize:12,marginTop:4},main:{flex:1},content:{padding:22},heading:{fontSize:20,fontWeight:"800",color:"#0F172A",marginBottom:14},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},tool:{minWidth:104,padding:10,borderRadius:9,backgroundColor:"white",borderWidth:1,borderColor:"#CBD5E1",alignItems:"center",gap:4},toolText:{fontSize:12,fontWeight:"700",color:"#334155"},disabled:{opacity:.4},preview:{marginTop:22,minHeight:360,backgroundColor:"#E2E8F0",borderRadius:12,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#CBD5E1"},previewTitle:{fontSize:18,fontWeight:"800",marginTop:12},help:{color:"#64748B",lineHeight:20,marginBottom:12},count:{fontWeight:"700",marginTop:18},field:{marginBottom:12},label:{fontSize:12,textTransform:"capitalize",fontWeight:"700",color:"#475569",marginBottom:5},input:{backgroundColor:"white",borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,padding:10},standard:{paddingHorizontal:14,paddingVertical:11,backgroundColor:"white",borderWidth:1,borderColor:"#CBD5E1",borderRadius:8},standardActive:{backgroundColor:"#A5F3FC",borderColor:"#0891B2"},audit:{fontSize:16,fontWeight:"800",marginTop:22,marginBottom:8},issue:{color:"#9A3412",marginBottom:5}});
