import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherElement, PublisherProject } from "../../types/publisher";
import {
  auditRasterRuntime,
  buildRasterExecutionManifest,
  checkpointRasterRuntime,
  configureLayeredRasterExport,
  configureRasterBrush,
  configureRasterColorPipeline,
  configureRasterPerformance,
  configureRasterSelectionRuntime,
  initializeRasterTiles,
  normalizeRasterRuntime,
  queueRasterJob,
} from "../../utils/professionalRasterRuntime";
import { auditPhase1712, ensureNonDestructiveRasterSource, executeRasterJobs, renderNonDestructivePreview, restoreOriginalRasterSource } from "../../utils/professionalRasterFinalIntegration";
import {
  RASTER_PRESETS,
  addRasterAdjustment,
  addRasterChannel,
  addRasterMask,
  addRasterSelection,
  addRasterSmartFilter,
  addRetouchStroke,
  applyRasterPreset,
  auditRasterElement,
  buildRasterRenderPlan,
  clearRasterSelections,
  clearRetouchStrokes,
  convertToRasterSmartObject,
  duplicateRasterAdjustment,
  ensureRasterChannels,
  moveRasterAdjustment,
  moveRasterSmartFilter,
  rasterProjectSummary,
  rasterizeSmartObject,
  recordRasterHistory,
  removeRasterAdjustment,
  removeRasterMask,
  removeRasterSmartFilter,
  resetRasterCrop,
  restoreRasterHistory,
  selectionToMask,
  setRasterColorProfile,
  setRasterComposite,
  setRasterCrop,
  updateRasterAdjustment,
  updateRasterChannel,
  updateRasterMask,
  updateRasterSelection,
  updateRasterSmartFilter,
  updateRasterSmartObject,
  validateRasterRenderPlan,
  addRasterExportRecipe,
  removeRasterExportRecipe,
  setFrequencySeparation,
  setRasterCompositeStack,
  setRasterHDR,
  setRasterLut,
  setRasterMetadata,
  setRasterRawDevelopment,
  type RasterAdjustmentKind,
  type RasterBlendMode,
  type RasterFilterKind,
  type RasterSelectionKind,
} from "../../utils/professionalRasterEngine";

type Props = {
  visible: boolean;
  project: PublisherProject;
  element: PublisherElement | null;
  onChange: (updates: Partial<PublisherElement>) => void;
  onBake: () => void;
  onRemoveBackground: () => void;
  onClose: () => void;
};
type Tab = "adjust" | "select" | "retouch" | "transform" | "filters" | "channels" | "finish" | "runtime" | "history" | "audit";
const adjustmentKinds: RasterAdjustmentKind[] = ["exposure", "brightness-contrast", "temperature-tint", "hsl", "curves", "levels", "black-white", "vibrance", "sharpen", "blur", "vignette"];
const selectionKinds: RasterSelectionKind[] = ["rectangle", "ellipse", "lasso", "polygon", "subject", "color-range"];
const filterKinds: RasterFilterKind[] = ["gaussian-blur", "motion-blur", "radial-blur", "unsharp-mask", "high-pass", "noise", "median", "emboss", "mosaic", "edge-detect", "liquify"];
const blends: RasterBlendMode[] = ["normal", "multiply", "screen", "overlay", "soft-light", "hard-light", "darken", "lighten", "difference", "exclusion", "color", "luminosity"];
const title = (value: string) => value.replace(/-/g, " ").replace(/\b\w/g, (m) => m.toUpperCase());

export default function ProfessionalRasterManagerModal({ visible, project, element, onChange, onBake, onRemoveBackground, onClose }: Props) {
  const [tab, setTab] = useState<Tab>("adjust");
  const [renderStatus, setRenderStatus] = useState("");
  const image = element?.type === "image" ? element : null;
  const a = image?.imageAdjustments ?? {};
  const audit = image ? [...auditRasterElement(image), ...validateRasterRenderPlan(image), ...auditPhase1712(image)] : [];
  const summary = rasterProjectSummary(project);
  const plan = image ? buildRasterRenderPlan(image) : null;
  const commit = (next: PublisherElement, label: string) => onChange(recordRasterHistory(next, label));
  const renderPreviewNow = async () => {
    if (!image) return;
    try {
      setRenderStatus("Running non-destructive pipeline…");
      const next = await renderNonDestructivePreview(ensureNonDestructiveRasterSource(image));
      onChange(recordRasterHistory(next, "Rendered non-destructive preview"));
      setRenderStatus("Preview rendered; original source preserved");
    } catch (error) { setRenderStatus(error instanceof Error ? error.message : String(error)); }
  };
  const runQueuedJobs = async () => {
    if (!image) return;
    try { setRenderStatus("Processing queued raster jobs…"); onChange(await executeRasterJobs(image)); setRenderStatus("Queued jobs processed"); }
    catch (error) { setRenderStatus(error instanceof Error ? error.message : String(error)); }
  };
  const adjust = (key: string, value: number) => image && commit({ ...image, imageAdjustments: { ...a, [key]: value }, rasterEditedAt: Date.now() }, `Changed ${key}`);
  const crop = image?.rasterCrop ?? { x: 0, y: 0, width: 1, height: 1, angle: 0, perspective: false };
  const profile = image?.rasterColorProfile ?? { workingSpace: "srgb", renderingIntent: "relative-colorimetric", blackPointCompensation: true, softProof: false, gamutWarning: false, bitDepth: 16 };

  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}>
    <View style={s.backdrop}><View style={s.modal}>
      <View style={s.header}><View><Text style={s.title}>Professional Photo Studio</Text><Text style={s.subtitle}>Non-destructive canvas, masks, retouch, queued jobs and export-ready raster delivery</Text></View><Pressable onPress={onClose}><Ionicons name="close" size={25} color="#e2e8f0" /></Pressable></View>
      <View style={s.stats}><Text style={s.stat}>Images {summary.images}</Text><Text style={s.stat}>Adjustments {summary.adjustments}</Text><Text style={s.stat}>Masks {summary.masks}</Text><Text style={s.stat}>Filters {image?.rasterSmartFilters?.length ?? 0}</Text><Text style={s.stat}>Channels {image?.rasterChannels?.length ?? 0}</Text></View>
      <View style={s.tabs}>{(["adjust", "select", "retouch", "transform", "filters", "channels", "finish", "runtime", "history", "audit"] as Tab[]).map((item) => <Pressable key={item} onPress={() => setTab(item)} style={[s.tab, tab === item && s.tabActive]}><Text style={[s.tabText, tab === item && s.tabTextActive]}>{title(item)}</Text></Pressable>)}</View>
      {!image ? <View style={s.empty}><Ionicons name="image-outline" size={44} color="#64748b" /><Text style={s.emptyText}>Select an image to use Photo Studio.</Text></View> : <ScrollView contentContainerStyle={s.body}>
        {tab === "adjust" && <>
          <Section name="Professional presets"><View style={s.wrap}>{Object.keys(RASTER_PRESETS).map((preset) => <Button key={preset} label={title(preset)} onPress={() => commit(applyRasterPreset(image, preset as keyof typeof RASTER_PRESETS), `Applied ${preset} preset`)} />)}</View></Section>
          <Section name="Direct corrections">{[["Brightness", "brightness", 0, 300], ["Contrast", "contrast", 0, 300], ["Saturation", "saturation", 0, 300], ["Exposure", "exposure", -100, 100], ["Highlights", "highlights", -100, 100], ["Shadows", "shadows", -100, 100], ["Warmth", "warmth", -100, 100], ["Tint", "tint", -100, 100]].map(([label, key, min, max]) => <SliderField key={String(key)} label={String(label)} value={Number(a[String(key)] ?? (min === 0 ? 100 : 0))} min={Number(min)} max={Number(max)} onChange={(v) => adjust(String(key), v)} />)}</Section>
          <Section name="Adjustment layers"><View style={s.wrap}>{adjustmentKinds.map((kind) => <Button key={kind} label={`+ ${title(kind)}`} onPress={() => commit(addRasterAdjustment(image, kind), `Added ${kind} adjustment`)} />)}</View>{(image.rasterAdjustments ?? []).map((layer) => <View key={layer.id} style={s.layer}><Pressable onPress={() => commit(updateRasterAdjustment(image, layer.id, { enabled: !layer.enabled }), `Toggled ${layer.name}`)}><Ionicons name={layer.enabled ? "eye-outline" : "eye-off-outline"} size={18} color="#cbd5e1" /></Pressable><Text style={s.layerName}>{layer.name}</Text><Text style={s.layerMeta}>{Math.round(layer.opacity * 100)}% · {layer.blendMode}</Text><Mini icon="arrow-up" onPress={() => commit(moveRasterAdjustment(image, layer.id, -1), `Moved ${layer.name}`)} /><Mini icon="arrow-down" onPress={() => commit(moveRasterAdjustment(image, layer.id, 1), `Moved ${layer.name}`)} /><Mini icon="copy-outline" onPress={() => commit(duplicateRasterAdjustment(image, layer.id), `Duplicated ${layer.name}`)} /><Mini icon="trash-outline" danger onPress={() => commit(removeRasterAdjustment(image, layer.id), `Removed ${layer.name}`)} /></View>)}</Section>
          <Section name="Object blend mode"><View style={s.wrap}>{blends.map((blend) => <Button key={blend} label={title(blend)} active={(image.rasterBlendMode ?? "normal") === blend} onPress={() => commit({ ...image, rasterBlendMode: blend }, `Blend mode ${blend}`)} />)}</View></Section>
        </>}
        {tab === "select" && <>
          <Section name="Selection tools"><View style={s.wrap}>{selectionKinds.map((kind) => <Button key={kind} label={`+ ${title(kind)}`} onPress={() => commit(addRasterSelection(image, kind), `Created ${kind} selection`)} />)}<Button label="Clear selections" onPress={() => commit(clearRasterSelections(image), "Cleared selections")} /></View></Section>
          <Section name="Saved selections">{(image.rasterSelections ?? []).length === 0 ? <Text style={s.muted}>No saved selections.</Text> : (image.rasterSelections ?? []).map((selection) => <View key={selection.id} style={s.card}><Text style={s.layerName}>{title(selection.name)}</Text><SliderField label="Feather" value={selection.feather} min={0} max={250} onChange={(v) => commit(updateRasterSelection(image, selection.id, { feather: v }), "Changed selection feather")} /><SliderField label="Expand / contract" value={selection.expand} min={-100} max={100} onChange={(v) => commit(updateRasterSelection(image, selection.id, { expand: v }), "Changed selection expansion")} /><View style={s.wrap}><Button label={selection.inverted ? "Use normal" : "Invert"} active={selection.inverted} onPress={() => commit(updateRasterSelection(image, selection.id, { inverted: !selection.inverted }), "Inverted selection")} /><Button label="Convert to mask" onPress={() => commit(selectionToMask(image, selection.id), "Converted selection to mask")} /></View></View>)}</Section>
          <Section name="Masks"><View style={s.wrap}><Button label="Add vector mask" onPress={() => commit(addRasterMask(image), "Added raster mask")} /><Button label="Remove background" onPress={onRemoveBackground} /></View>{(image.rasterMasks ?? []).map((mask) => <View key={mask.id} style={s.card}><View style={s.layer}><Text style={s.layerName}>{mask.name}</Text><Mini icon="trash-outline" danger onPress={() => commit(removeRasterMask(image, mask.id), "Removed mask")} /></View><SliderField label="Feather" value={mask.feather} min={0} max={250} onChange={(v) => commit(updateRasterMask(image, mask.id, { feather: v }), "Mask feather")} /><SliderField label="Density" value={(mask.density ?? 1) * 100} min={0} max={100} onChange={(v) => commit(updateRasterMask(image, mask.id, { density: v / 100 }), "Mask density")} /><View style={s.wrap}><Button label="Invert" active={mask.inverted} onPress={() => commit(updateRasterMask(image, mask.id, { inverted: !mask.inverted }), "Inverted mask")} /><Button label={mask.linked === false ? "Unlinked" : "Linked"} active={mask.linked !== false} onPress={() => commit(updateRasterMask(image, mask.id, { linked: mask.linked === false }), "Toggled mask link")} /></View></View>)}</Section>
        </>}
        {tab === "retouch" && <Section name="Direct canvas tools"><View style={s.wrap}>{([["none","Pointer"],["brush","Brush"],["eraser","Eraser"],["clone","Clone"],["heal","Heal"],["select-rectangle","Rectangle select"],["select-ellipse","Ellipse select"],["select-lasso","Lasso select"]] as const).map(([tool,label]) => <Button key={tool} label={label} active={(image.rasterCanvasTool ?? "none")===tool} onPress={() => commit({...image,rasterCanvasTool:tool,phase17Version:"17.13"},`Canvas tool ${label}`)} />)}</View><Text style={s.muted}>Close Photo Studio, then drag directly over the selected image. Actions are stored non-destructively and rendered through the non-destructive raster pipeline.</Text></Section>}
        {tab === "retouch" && <Section name="Retouch tools"><View style={s.wrap}>{(["heal", "clone", "dodge", "burn", "smudge"] as const).map((tool) => <Button key={tool} label={title(tool)} onPress={() => commit(addRetouchStroke(image, tool, [{ x: .35, y: .5 }, { x: .65, y: .5 }], { size: image.rasterRetouch?.brushSize ?? 40, strength: (image.rasterRetouch?.strength ?? 50) / 100 }), `Added ${tool} stroke`)} />)}<Button label="Clear retouch" onPress={() => commit(clearRetouchStrokes(image), "Cleared retouch strokes")} /></View><SliderField label="Brush size" value={image.rasterRetouch?.brushSize ?? 40} min={1} max={500} onChange={(v) => commit({ ...image, rasterRetouch: { ...image.rasterRetouch, brushSize: v } }, "Retouch brush size")} /><SliderField label="Strength" value={image.rasterRetouch?.strength ?? 50} min={0} max={100} onChange={(v) => commit({ ...image, rasterRetouch: { ...image.rasterRetouch, strength: v } }, "Retouch strength")} /><Text style={s.muted}>{image.rasterRetouchStrokes?.length ?? 0} non-destructive retouch strokes stored.</Text></Section>}
        {tab === "transform" && <><Section name="Crop"><SliderField label="Crop X %" value={crop.x * 100} min={0} max={99} onChange={(v) => commit(setRasterCrop(image, { x: v / 100 }), "Crop X")} /><SliderField label="Crop Y %" value={crop.y * 100} min={0} max={99} onChange={(v) => commit(setRasterCrop(image, { y: v / 100 }), "Crop Y")} /><SliderField label="Crop width %" value={crop.width * 100} min={1} max={100} onChange={(v) => commit(setRasterCrop(image, { width: v / 100 }), "Crop width")} /><SliderField label="Crop height %" value={crop.height * 100} min={1} max={100} onChange={(v) => commit(setRasterCrop(image, { height: v / 100 }), "Crop height")} /><SliderField label="Straighten angle" value={crop.angle} min={-45} max={45} onChange={(v) => commit(setRasterCrop(image, { angle: v }), "Straighten crop")} /><View style={s.wrap}>{["free", "1:1", "4:3", "3:2", "16:9"].map((aspect) => <Button key={aspect} label={aspect} active={(crop.aspect ?? "free") === aspect} onPress={() => commit(setRasterCrop(image, { aspect }), `Crop ${aspect}`)} />)}<Button label="Perspective crop" active={crop.perspective} onPress={() => commit(setRasterCrop(image, { perspective: !crop.perspective }), "Perspective crop")} /><Button label="Reset crop" onPress={() => commit(resetRasterCrop(image), "Reset crop")} /></View></Section><Section name="Lens and perspective"><SliderField label="Lens correction" value={image.rasterTransform?.lensCorrection ?? 0} min={-100} max={100} onChange={(v) => commit({ ...image, rasterTransform: { ...image.rasterTransform, lensCorrection: v } }, "Lens correction")} /><SliderField label="Perspective X" value={image.rasterTransform?.perspectiveX ?? 0} min={-100} max={100} onChange={(v) => commit({ ...image, rasterTransform: { ...image.rasterTransform, perspectiveX: v } }, "Perspective X")} /><SliderField label="Perspective Y" value={image.rasterTransform?.perspectiveY ?? 0} min={-100} max={100} onChange={(v) => commit({ ...image, rasterTransform: { ...image.rasterTransform, perspectiveY: v } }, "Perspective Y")} /><SliderField label="Chromatic aberration" value={image.rasterTransform?.chromaticAberration ?? 0} min={0} max={100} onChange={(v) => commit({ ...image, rasterTransform: { ...image.rasterTransform, chromaticAberration: v } }, "Chromatic aberration")} /></Section></>}
        {tab === "filters" && <>
          <Section name="Smart object"><View style={s.wrap}><Button label="Convert to embedded smart object" active={image.rasterSmartObject?.mode === "embedded"} onPress={() => commit(convertToRasterSmartObject(image, "embedded"), "Converted to embedded smart object")} /><Button label="Convert to linked smart object" active={image.rasterSmartObject?.mode === "linked"} onPress={() => commit(convertToRasterSmartObject(image, "linked"), "Converted to linked smart object")} />{image.rasterSmartObject && <Button label="Rasterize smart object" onPress={() => commit(rasterizeSmartObject(image), "Rasterized smart object")} />}</View>{image.rasterSmartObject && <><Text style={s.muted}>Mode: {image.rasterSmartObject.mode} · source preserved</Text><SliderField label="Smart rotation" value={image.rasterSmartObject.rotation} min={-360} max={360} onChange={(v) => commit(updateRasterSmartObject(image, { rotation: v }), "Smart object rotation")} /><SliderField label="Smart scale X %" value={image.rasterSmartObject.scaleX * 100} min={-1000} max={1000} onChange={(v) => commit(updateRasterSmartObject(image, { scaleX: v / 100 }), "Smart object scale X")} /></>}</Section>
          <Section name="Live smart filters"><View style={s.wrap}>{filterKinds.map((kind) => <Button key={kind} label={`+ ${title(kind)}`} onPress={() => commit(addRasterSmartFilter(image, kind, { amount: 25, radius: 8 }), `Added ${kind} smart filter`)} />)}</View>{(image.rasterSmartFilters ?? []).map((filter) => <View key={filter.id} style={s.card}><View style={s.layer}><Pressable onPress={() => commit(updateRasterSmartFilter(image, filter.id, { enabled: !filter.enabled }), `Toggled ${filter.name}`)}><Ionicons name={filter.enabled ? "eye-outline" : "eye-off-outline"} size={18} color="#cbd5e1" /></Pressable><Text style={s.layerName}>{filter.name}</Text><Text style={s.layerMeta}>{Math.round(filter.opacity * 100)}%</Text><Mini icon="arrow-up" onPress={() => commit(moveRasterSmartFilter(image, filter.id, -1), `Moved ${filter.name}`)} /><Mini icon="arrow-down" onPress={() => commit(moveRasterSmartFilter(image, filter.id, 1), `Moved ${filter.name}`)} /><Mini icon="trash-outline" danger onPress={() => commit(removeRasterSmartFilter(image, filter.id), `Removed ${filter.name}`)} /></View><SliderField label="Filter opacity" value={filter.opacity * 100} min={0} max={100} onChange={(v) => commit(updateRasterSmartFilter(image, filter.id, { opacity: v / 100 }), "Changed filter opacity")} /></View>)}</Section>
          <Section name="Advanced compositing"><View style={s.wrap}><Button label="Clipping mask" active={Boolean(image.rasterComposite?.clippingMask)} onPress={() => commit(setRasterComposite(image, { clippingMask: !image.rasterComposite?.clippingMask }), "Toggled clipping mask")} /><Button label="Isolate blending" active={Boolean(image.rasterComposite?.isolateBlending)} onPress={() => commit(setRasterComposite(image, { isolateBlending: !image.rasterComposite?.isolateBlending }), "Toggled isolated blending")} />{(["none", "shallow", "deep"] as const).map((knockout) => <Button key={knockout} label={`Knockout ${knockout}`} active={(image.rasterComposite?.knockout ?? "none") === knockout} onPress={() => commit(setRasterComposite(image, { knockout }), `Knockout ${knockout}`)} />)}</View></Section>
        </>}
        {tab === "channels" && <>
          <Section name="Channels"><View style={s.wrap}><Button label="Initialize RGB channels" onPress={() => commit(ensureRasterChannels(image), "Initialized RGB channels")} /><Button label="Add alpha channel" onPress={() => commit(addRasterChannel(image, "alpha"), "Added alpha channel")} /><Button label="Add spot channel" onPress={() => commit(addRasterChannel(image, "spot"), "Added spot channel")} /></View>{(image.rasterChannels ?? []).map((channel) => <View key={channel.id} style={s.layer}><Pressable onPress={() => commit(updateRasterChannel(image, channel.id, { enabled: !channel.enabled }), `Toggled ${channel.name}`)}><Ionicons name={channel.enabled ? "eye-outline" : "eye-off-outline"} size={18} color="#cbd5e1" /></Pressable><Text style={s.layerName}>{channel.name}</Text><Text style={s.layerMeta}>{Math.round(channel.opacity * 100)}%</Text><Mini icon={channel.locked ? "lock-closed-outline" : "lock-open-outline"} onPress={() => commit(updateRasterChannel(image, channel.id, { locked: !channel.locked }), `Toggled ${channel.name} lock`)} /></View>)}</Section>
          <Section name="Color management"><View style={s.wrap}>{(["srgb", "display-p3", "adobe-rgb", "prophoto-rgb", "cmyk-preview"] as const).map((workingSpace) => <Button key={workingSpace} label={workingSpace.toUpperCase()} active={profile.workingSpace === workingSpace} onPress={() => commit(setRasterColorProfile(image, { workingSpace }), `Working space ${workingSpace}`)} />)}</View><View style={s.wrap}>{([8, 16, 32] as const).map((bitDepth) => <Button key={bitDepth} label={`${bitDepth}-bit`} active={profile.bitDepth === bitDepth} onPress={() => commit(setRasterColorProfile(image, { bitDepth }), `${bitDepth}-bit document`)} />)}<Button label="Soft proof" active={profile.softProof} onPress={() => commit(setRasterColorProfile(image, { softProof: !profile.softProof }), "Toggled soft proof")} /><Button label="Gamut warning" active={profile.gamutWarning} onPress={() => commit(setRasterColorProfile(image, { gamutWarning: !profile.gamutWarning }), "Toggled gamut warning")} /><Button label="Black point compensation" active={profile.blackPointCompensation} onPress={() => commit(setRasterColorProfile(image, { blackPointCompensation: !profile.blackPointCompensation }), "Toggled black point compensation")} /></View></Section>
        </>}
        {tab === "finish" && <>
          <Section name="RAW development"><View style={s.wrap}><Button label="Enable RAW pipeline" active={Boolean(image.rasterRawDevelopment?.enabled)} onPress={() => commit(setRasterRawDevelopment(image,{enabled:!image.rasterRawDevelopment?.enabled,format:"raw"}),"RAW development")} />{(["as-shot","auto","daylight","cloudy","tungsten"] as const).map((whiteBalance)=><Button key={whiteBalance} label={title(whiteBalance)} active={(image.rasterRawDevelopment?.whiteBalance??"as-shot")===whiteBalance} onPress={()=>commit(setRasterRawDevelopment(image,{whiteBalance}),`White balance ${whiteBalance}`)} />)}</View><SliderField label="RAW denoise" value={image.rasterRawDevelopment?.denoise??0} min={0} max={100} onChange={(v)=>commit(setRasterRawDevelopment(image,{denoise:v}),"RAW denoise")} /><SliderField label="Dehaze" value={image.rasterRawDevelopment?.dehaze??0} min={-100} max={100} onChange={(v)=>commit(setRasterRawDevelopment(image,{dehaze:v}),"RAW dehaze")} /></Section>
          <Section name="HDR and professional retouch"><View style={s.wrap}><Button label="HDR merge" active={Boolean(image.rasterHDR?.enabled)} onPress={()=>commit(setRasterHDR(image,{enabled:!image.rasterHDR?.enabled,sourceCount:3}),"HDR merge")} /><Button label="Frequency separation" active={Boolean(image.rasterFrequencySeparation?.enabled)} onPress={()=>commit(setFrequencySeparation(image,{enabled:!image.rasterFrequencySeparation?.enabled}),"Frequency separation")} /></View><SliderField label="HDR strength" value={image.rasterHDR?.strength??50} min={0} max={100} onChange={(v)=>commit(setRasterHDR(image,{strength:v}),"HDR strength")} /><SliderField label="Separation radius" value={image.rasterFrequencySeparation?.radius??8} min={1} max={250} onChange={(v)=>commit(setFrequencySeparation(image,{radius:v}),"Frequency separation radius")} /></Section>
          <Section name="Panorama, stacking and LUT"><View style={s.wrap}>{(["none","panorama","focus-stack","exposure-fusion"] as const).map((mode)=><Button key={mode} label={title(mode)} active={(image.rasterCompositeStack?.mode??"none")===mode} onPress={()=>commit(setRasterCompositeStack(image,{mode}),`Composite ${mode}`)} />)}<Button label="Cinematic LUT" active={Boolean(image.rasterLut?.enabled)} onPress={()=>commit(setRasterLut(image,{enabled:!image.rasterLut?.enabled,name:"Yaposan Cinematic",intensity:.75}),"Cinematic LUT")} /></View><SliderField label="LUT intensity" value={(image.rasterLut?.intensity??1)*100} min={0} max={100} onChange={(v)=>commit(setRasterLut(image,{intensity:v/100}),"LUT intensity")} /></Section>
          <Section name="Metadata and delivery"><View style={s.wrap}>{([1,2,3,4,5] as const).map((rating)=><Button key={rating} label={`${rating}★`} active={(image.rasterMetadata?.rating??0)===rating} onPress={()=>commit(setRasterMetadata(image,{rating}),`Rating ${rating}`)} />)}<Button label="Add Web PNG" onPress={()=>commit(addRasterExportRecipe(image,{name:"Web PNG",format:"png",scale:1}),"Added Web PNG recipe")} /><Button label="Add Print TIFF" onPress={()=>commit(addRasterExportRecipe(image,{name:"Print TIFF",format:"tiff",bitDepth:16,colorSpace:"adobe-rgb",sharpenFor:"glossy"}),"Added Print TIFF recipe")} /></View>{(image.rasterExportRecipes??[]).map((recipe)=><View key={recipe.id} style={s.layer}><Text style={s.layerName}>{recipe.name}</Text><Text style={s.layerMeta}>{recipe.format.toUpperCase()} · {recipe.bitDepth}-bit · {Math.round(recipe.scale*100)}%</Text><Mini icon="trash-outline" danger onPress={()=>commit(removeRasterExportRecipe(image,recipe.id),`Removed ${recipe.name}`)} /></View>)}</Section>
        </>}
        {tab === "runtime" && (() => { const runtime=normalizeRasterRuntime(image.rasterRuntime); const manifest=buildRasterExecutionManifest(image); const runtimeAudit=auditRasterRuntime(image); return <>
          <Section name="Rendering backend"><View style={s.wrap}>{(["webgpu","webgl2","skia","canvas2d","cpu"] as const).map((backend)=><Button key={backend} label={backend.toUpperCase()} active={runtime.performance.backend===backend} onPress={()=>commit(configureRasterPerformance(image,{backend,gpuAcceleration:backend!=="cpu"}),`Raster backend ${backend}`)} />)}<Button label="Initialize tiles" onPress={()=>commit(initializeRasterTiles(image,4096,4096),"Initialized tiled raster canvas")} /></View><SliderField label="Memory MB" value={runtime.performance.maxMemoryMB} min={128} max={32768} onChange={(v)=>commit(configureRasterPerformance(image,{maxMemoryMB:v}),"Raster memory budget")} /><SliderField label="Workers" value={runtime.performance.workerCount} min={1} max={32} onChange={(v)=>commit(configureRasterPerformance(image,{workerCount:v}),"Raster worker count")} /></Section>
          <Section name="Professional brush engine"><SliderField label="Brush size" value={runtime.brush.size} min={1} max={2000} onChange={(v)=>commit(configureRasterBrush(image,{size:v}),"Brush size")} /><SliderField label="Hardness" value={runtime.brush.hardness*100} min={0} max={100} onChange={(v)=>commit(configureRasterBrush(image,{hardness:v/100}),"Brush hardness")} /><SliderField label="Flow" value={runtime.brush.flow*100} min={0} max={100} onChange={(v)=>commit(configureRasterBrush(image,{flow:v/100}),"Brush flow")} /><View style={s.wrap}><Button label="Pressure size" active={runtime.brush.pressureSize} onPress={()=>commit(configureRasterBrush(image,{pressureSize:!runtime.brush.pressureSize}),"Pressure size")} /><Button label="Pressure opacity" active={runtime.brush.pressureOpacity} onPress={()=>commit(configureRasterBrush(image,{pressureOpacity:!runtime.brush.pressureOpacity}),"Pressure opacity")} /><Button label="Tilt" active={runtime.brush.tilt} onPress={()=>commit(configureRasterBrush(image,{tilt:!runtime.brush.tilt}),"Brush tilt")} /><Button label="Wet edges" active={runtime.brush.wetEdges} onPress={()=>commit(configureRasterBrush(image,{wetEdges:!runtime.brush.wetEdges}),"Wet edges")} /></View></Section>
          <Section name="Selections and masks execution"><View style={s.wrap}>{(["replace","add","subtract","intersect"] as const).map((mode)=><Button key={mode} label={title(mode)} active={runtime.selection.mode===mode} onPress={()=>commit(configureRasterSelectionRuntime(image,{mode}),`Selection mode ${mode}`)} />)}<Button label="Marching ants" active={runtime.selection.marchingAnts} onPress={()=>commit(configureRasterSelectionRuntime(image,{marchingAnts:!runtime.selection.marchingAnts}),"Marching ants")} /><Button label="Hair refine" active={runtime.selection.hairRefinement} onPress={()=>commit(configureRasterSelectionRuntime(image,{hairRefinement:!runtime.selection.hairRefinement}),"Hair refinement")} /></View><SliderField label="Magic tolerance" value={runtime.selection.magicWandTolerance} min={0} max={255} onChange={(v)=>commit(configureRasterSelectionRuntime(image,{magicWandTolerance:v}),"Magic wand tolerance")} /><SliderField label="Edge refine" value={runtime.selection.edgeRefine} min={0} max={250} onChange={(v)=>commit(configureRasterSelectionRuntime(image,{edgeRefine:v}),"Selection edge refine")} /></Section>
          <Section name="Color and layered output"><View style={s.wrap}><Button label="Linear light" active={runtime.color.linearLight} onPress={()=>commit(configureRasterColorPipeline(image,{linearLight:!runtime.color.linearLight}),"Linear light")} /><Button label="Float processing" active={runtime.color.floatingPoint} onPress={()=>commit(configureRasterColorPipeline(image,{floatingPoint:!runtime.color.floatingPoint}),"Floating point")} /><Button label="ICC profiles" active={runtime.color.iccEnabled} onPress={()=>commit(configureRasterColorPipeline(image,{iccEnabled:!runtime.color.iccEnabled}),"ICC color")} />{(["yaposan-raster","psd-compatible","tiff-layered"] as const).map((format)=><Button key={format} label={title(format)} active={runtime.layeredExport.format===format} onPress={()=>commit(configureLayeredRasterExport(image,{format}),`Layered export ${format}`)} />)}</View></Section>
          <Section name="Execution queue"><View style={s.wrap}><Button label="Render preview now" onPress={renderPreviewNow} /><Button label="Run queued jobs" onPress={runQueuedJobs} /><Button label="Restore original" onPress={()=>onChange(restoreOriginalRasterSource(image))} /><Button label="Queue full render" onPress={()=>commit(queueRasterJob(image,"render","Render full-resolution raster"),"Queued full raster render")} /><Button label="Queue RAW" onPress={()=>commit(queueRasterJob(image,"raw","Decode and develop camera RAW"),"Queued RAW processing")} /><Button label="Queue HDR" onPress={()=>commit(queueRasterJob(image,"hdr","Align and merge HDR bracket"),"Queued HDR merge")} /><Button label="Queue panorama" onPress={()=>commit(queueRasterJob(image,"panorama","Align and stitch panorama"),"Queued panorama")} /><Button label="Checkpoint" onPress={()=>commit(checkpointRasterRuntime(image),"Raster checkpoint")} /></View>{renderStatus ? <Text style={s.muted}>{renderStatus}</Text> : null}{runtime.jobs.slice().reverse().map(job=><View key={job.id} style={s.layer}><Text style={s.layerName}>{job.label}</Text><Text style={s.layerMeta}>{job.status} · {Math.round(job.progress*100)}%</Text></View>)}</Section>
          <Section name="Runtime certification"><Text style={s.muted}>{manifest.backend.toUpperCase()} · {manifest.workers} workers · {manifest.tiles} tiles · {manifest.bitDepth}-bit · {manifest.layeredExport}</Text>{runtimeAudit.map((issue,i)=><View key={`${issue.message}-${i}`} style={s.issue}><Text style={[s.issueSeverity,issue.severity==="error"&&s.error]}>{issue.severity.toUpperCase()}</Text><Text style={s.issueText}>{issue.message}</Text></View>)}</Section>
        </>; })()}
        {tab === "history" && <Section name="Raster history">{(image.rasterHistory ?? []).slice().reverse().map((entry) => <Pressable key={entry.id} style={s.history} onPress={() => onChange(restoreRasterHistory(image, entry.id))}><Text style={s.layerName}>{entry.label}</Text><Text style={s.layerMeta}>{new Date(entry.createdAt).toLocaleTimeString()}</Text></Pressable>)}{!(image.rasterHistory ?? []).length && <Text style={s.muted}>No raster history yet.</Text>}</Section>}
        {tab === "audit" && <><Section name="Render plan">{plan && <Text style={s.muted}>{plan.smartObject ? "Smart object" : "Raster source"} · {plan.filters.length} filters · {plan.adjustments.length} adjustments · {plan.masks} masks · {plan.bitDepth}-bit {plan.colorProfile.toUpperCase()}</Text>}</Section><Section name="Audit and output">{audit.map((issue, i) => <View key={`${issue.message}-${i}`} style={s.issue}><Text style={[s.issueSeverity, issue.severity === "error" && s.error]}>{issue.severity.toUpperCase()}</Text><Text style={s.issueText}>{issue.message}</Text></View>)}<View style={s.wrap}><Button label="Bake pixel edits" onPress={onBake} /><Button label="Reset all raster edits" onPress={() => onChange({ imageAdjustments: RASTER_PRESETS.original.imageAdjustments, rasterAdjustments: [], rasterMasks: [], rasterSelections: [], rasterRetouchStrokes: [], rasterSmartFilters: [], rasterSmartObject: undefined, rasterChannels: [], rasterColorProfile: undefined, rasterComposite: undefined, rasterRawDevelopment: undefined, rasterHDR: undefined, rasterFrequencySeparation: undefined, rasterCompositeStack: undefined, rasterLut: undefined, rasterMetadata: undefined, rasterExportRecipes: [], rasterCrop: undefined, rasterBlendMode: "normal", rasterOpacity: 1, rasterRetouch: undefined, rasterTransform: undefined })} /></View></Section></>}
      </ScrollView>}
    </View></View>
  </Modal>;
}
function Section({ name, children }: { name: string; children: React.ReactNode }) { return <View style={s.section}><Text style={s.sectionTitle}>{name}</Text>{children}</View>; }
function Button({ label, onPress, active }: { label: string; onPress: () => void; active?: boolean }) { return <Pressable onPress={onPress} style={[s.button, active && s.buttonActive]}><Text style={[s.buttonText, active && s.buttonTextActive]}>{label}</Text></Pressable>; }
function Mini({ icon, onPress, danger }: { icon: any; onPress: () => void; danger?: boolean }) { return <Pressable onPress={onPress}><Ionicons name={icon} size={17} color={danger ? "#fca5a5" : "#cbd5e1"} /></Pressable>; }
function SliderField({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) { return <View style={s.field}><Text style={s.fieldLabel}>{label}</Text><Pressable style={s.step} onPress={() => onChange(Math.max(min, value - 5))}><Text style={s.stepText}>−</Text></Pressable><TextInput keyboardType="numeric" value={String(Math.round(value))} onChangeText={(text) => { const v = Number(text); if (Number.isFinite(v)) onChange(Math.max(min, Math.min(max, v))); }} style={s.input} /><Pressable style={s.step} onPress={() => onChange(Math.min(max, value + 5))}><Text style={s.stepText}>+</Text></Pressable></View>; }
const s = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: "rgba(2,6,23,.72)", alignItems: "center", justifyContent: "center", padding: 20 }, modal: { width: "94%", maxWidth: 1080, maxHeight: "92%", backgroundColor: "#0f172a", borderRadius: 16, borderWidth: 1, borderColor: "#334155", overflow: "hidden" }, header: { padding: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: "#111827" }, title: { fontSize: 20, fontWeight: "800", color: "#f8fafc" }, subtitle: { color: "#94a3b8", marginTop: 3 }, stats: { flexDirection: "row", gap: 16, paddingHorizontal: 18, paddingVertical: 10, backgroundColor: "#1e293b", flexWrap: "wrap" }, stat: { color: "#cbd5e1", fontSize: 12, fontWeight: "700" }, tabs: { flexDirection: "row", backgroundColor: "#020617", padding: 8, gap: 6, flexWrap: "wrap" }, tab: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8 }, tabActive: { backgroundColor: "#0f766e" }, tabText: { color: "#94a3b8", fontWeight: "700", fontSize: 12 }, tabTextActive: { color: "#fff" }, body: { padding: 18, gap: 14 }, empty: { padding: 50, alignItems: "center", gap: 12 }, emptyText: { color: "#94a3b8" }, section: { backgroundColor: "#111827", borderRadius: 12, padding: 14, borderWidth: 1, borderColor: "#263244", gap: 10 }, sectionTitle: { color: "#f8fafc", fontWeight: "800", fontSize: 15 }, wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, button: { paddingHorizontal: 12, paddingVertical: 9, borderRadius: 8, backgroundColor: "#263244", borderWidth: 1, borderColor: "#3b4b63" }, buttonActive: { backgroundColor: "#0f766e", borderColor: "#2dd4bf" }, buttonText: { color: "#dbeafe", fontSize: 12, fontWeight: "700" }, buttonTextActive: { color: "#fff" }, field: { flexDirection: "row", alignItems: "center", gap: 8 }, fieldLabel: { color: "#cbd5e1", width: 150 }, step: { width: 32, height: 32, borderRadius: 7, alignItems: "center", justifyContent: "center", backgroundColor: "#263244" }, stepText: { color: "#fff", fontSize: 18 }, input: { width: 72, height: 34, color: "#fff", textAlign: "center", backgroundColor: "#020617", borderRadius: 7, borderWidth: 1, borderColor: "#334155" }, layer: { flexDirection: "row", alignItems: "center", gap: 10, padding: 10, borderRadius: 8, backgroundColor: "#020617" }, card: { gap: 9, padding: 10, borderRadius: 8, backgroundColor: "#020617" }, layerName: { color: "#e2e8f0", fontWeight: "700", flex: 1 }, layerMeta: { color: "#94a3b8", fontSize: 11 }, history: { flexDirection: "row", alignItems: "center", padding: 11, borderRadius: 8, backgroundColor: "#020617", gap: 10 }, muted: { color: "#94a3b8", fontSize: 12 }, issue: { flexDirection: "row", gap: 10, alignItems: "flex-start" }, issueSeverity: { fontSize: 10, fontWeight: "900", color: "#5eead4", width: 58 }, error: { color: "#fca5a5" }, issueText: { color: "#cbd5e1", flex: 1, fontSize: 12 } });
