import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { DEFAULT_AUTOMATION_WORKSPACE, auditAutomationWorkspace, executeAutomationRule, updateAutomationRule, type AutomationWorkspace } from "../../utils/professionalWorkflowAutomationEngine";

type Props = { visible: boolean; projectName: string; onClose: () => void };

export default function ProfessionalWorkflowAutomationModal({ visible, projectName, onClose }: Props) {
  const [workspace, setWorkspace] = useState<AutomationWorkspace>(DEFAULT_AUTOMATION_WORKSPACE);
  const [section, setSection] = useState<"rules" | "runs" | "audit">("rules");
  const audit = useMemo(() => auditAutomationWorkspace(workspace), [workspace]);
  const run = (id: string) => setWorkspace((current) => executeAutomationRule(current, id, { projectName, approved: true }));
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}>
    <View style={styles.screen}>
      <View style={styles.header}><View><Text style={styles.title}>Professional Workflow Automation</Text><Text style={styles.subtitle}>{projectName} · </Text></View><Pressable onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color="#fff" /></Pressable></View>
      <View style={styles.tabs}>{(["rules","runs","audit"] as const).map((item)=><Pressable key={item} onPress={()=>setSection(item)} style={[styles.tab,section===item&&styles.tabActive]}><Text style={[styles.tabText,section===item&&styles.tabTextActive]}>{item.toUpperCase()}</Text></Pressable>)}</View>
      <ScrollView contentContainerStyle={styles.content}>
        {section === "rules" && <>
          <View style={styles.hero}><Ionicons name="flash-outline" size={28} color="#7C3AED"/><View style={{flex:1}}><Text style={styles.heroTitle}>Automate repeatable publishing work</Text><Text style={styles.heroText}>Create controlled workflows for preflight, PDF export, packaging, backups, notifications, and channel publishing.</Text></View><View style={styles.safe}><Text style={styles.safeText}>{workspace.safeMode ? "SAFE MODE" : "LIVE MODE"}</Text></View></View>
          {workspace.rules.map((rule)=><View key={rule.id} style={styles.card}><View style={styles.row}><View style={{flex:1}}><Text style={styles.cardTitle}>{rule.name}</Text><Text style={styles.meta}>{rule.description}</Text></View><View style={[styles.badge,rule.status==="active"&&styles.badgeActive]}><Text style={styles.badgeText}>{rule.status}</Text></View></View><Text style={styles.meta}>Trigger: {rule.trigger} · {rule.actions.length} action(s) · {rule.runCount} run(s)</Text><View style={styles.actions}><Pressable style={styles.primary} onPress={()=>run(rule.id)}><Ionicons name="play" size={14} color="#fff"/><Text style={styles.primaryText}>Run now</Text></Pressable><Pressable style={styles.secondary} onPress={()=>setWorkspace((current)=>updateAutomationRule(current,rule.id,{status:rule.status==="active"?"paused":"active"}))}><Text style={styles.secondaryText}>{rule.status==="active"?"Pause":"Activate"}</Text></Pressable></View>{rule.actions.map((action)=><View key={action.id} style={styles.step}><Ionicons name="checkmark-circle-outline" size={16} color="#059669"/><Text style={styles.stepText}>{action.label}</Text></View>)}</View>)}
        </>}
        {section === "runs" && <>{workspace.runs.length===0?<View style={styles.empty}><Ionicons name="time-outline" size={34} color="#94A3B8"/><Text style={styles.emptyTitle}>No automation runs yet</Text><Text style={styles.meta}>Run a workflow to create execution history.</Text></View>:workspace.runs.map((runItem)=><View key={runItem.id} style={styles.card}><Text style={styles.cardTitle}>{workspace.rules.find((r)=>r.id===runItem.ruleId)?.name ?? "Automation"}</Text><Text style={styles.meta}>{runItem.status} · {runItem.steps.length} step(s) · {new Date(runItem.completedAt).toLocaleString()}</Text>{runItem.steps.map((step)=><View key={step.actionId} style={styles.step}><Ionicons name={step.status==="completed"?"checkmark-circle":"remove-circle-outline"} size={16} color={step.status==="completed"?"#059669":"#D97706"}/><View style={{flex:1}}><Text style={styles.stepText}>{step.label}</Text><Text style={styles.meta}>{step.message}</Text></View></View>)}</View>)}</>}
        {section === "audit" && <><View style={styles.auditHero}><Text style={styles.score}>{audit.score}</Text><View><Text style={styles.cardTitle}>Automation readiness score</Text><Text style={styles.meta}>{audit.issues.length} issue(s) require attention</Text></View></View>{audit.issues.length===0?<View style={styles.success}><Text style={styles.successText}>All automation governance checks passed.</Text></View>:audit.issues.map((issue)=><View key={issue.id} style={styles.card}><Text style={styles.issue}>{issue.severity.toUpperCase()}</Text><Text style={styles.cardTitle}>{issue.message}</Text><Text style={styles.meta}>{issue.fix}</Text></View>)}</>}
      </ScrollView>
    </View>
  </Modal>;
}

const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#F8FAFC"},header:{height:68,backgroundColor:"#111827",paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{color:"#fff",fontWeight:"900",fontSize:19},subtitle:{color:"#C4B5FD",fontSize:11,marginTop:3},close:{width:38,height:38,borderRadius:19,backgroundColor:"#374151",alignItems:"center",justifyContent:"center"},tabs:{height:48,backgroundColor:"#1F2937",flexDirection:"row",paddingHorizontal:16,gap:6},tab:{paddingHorizontal:18,justifyContent:"center",borderBottomWidth:3,borderBottomColor:"transparent"},tabActive:{borderBottomColor:"#8B5CF6"},tabText:{color:"#94A3B8",fontWeight:"800",fontSize:11},tabTextActive:{color:"#fff"},content:{padding:18,maxWidth:1050,width:"100%",alignSelf:"center"},hero:{backgroundColor:"#F5F3FF",borderWidth:1,borderColor:"#DDD6FE",borderRadius:12,padding:16,flexDirection:"row",alignItems:"center",gap:13,marginBottom:14},heroTitle:{fontSize:17,fontWeight:"900",color:"#312E81"},heroText:{fontSize:12,color:"#5B21B6",marginTop:4,lineHeight:17},safe:{backgroundColor:"#DCFCE7",paddingHorizontal:10,paddingVertical:7,borderRadius:14},safeText:{fontSize:10,fontWeight:"900",color:"#166534"},card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#E2E8F0",borderRadius:11,padding:14,marginBottom:10},row:{flexDirection:"row",alignItems:"center",gap:10},cardTitle:{fontSize:14,fontWeight:"900",color:"#0F172A"},meta:{fontSize:11,color:"#64748B",marginTop:4,lineHeight:16},badge:{backgroundColor:"#E2E8F0",paddingHorizontal:9,paddingVertical:5,borderRadius:12},badgeActive:{backgroundColor:"#DCFCE7"},badgeText:{fontSize:9,fontWeight:"900",textTransform:"uppercase",color:"#334155"},actions:{flexDirection:"row",gap:8,marginTop:12,marginBottom:8},primary:{backgroundColor:"#7C3AED",borderRadius:7,paddingHorizontal:12,paddingVertical:9,flexDirection:"row",gap:6,alignItems:"center"},primaryText:{color:"#fff",fontWeight:"900",fontSize:11},secondary:{backgroundColor:"#F1F5F9",borderRadius:7,paddingHorizontal:12,paddingVertical:9},secondaryText:{color:"#334155",fontWeight:"900",fontSize:11},step:{flexDirection:"row",alignItems:"flex-start",gap:8,paddingVertical:8,borderTopWidth:1,borderTopColor:"#F1F5F9"},stepText:{fontSize:12,fontWeight:"700",color:"#334155"},empty:{alignItems:"center",padding:50,backgroundColor:"#fff",borderRadius:12,borderWidth:1,borderColor:"#E2E8F0"},emptyTitle:{fontWeight:"900",color:"#334155",fontSize:15,marginTop:10},auditHero:{backgroundColor:"#fff",borderWidth:1,borderColor:"#E2E8F0",borderRadius:12,padding:16,flexDirection:"row",alignItems:"center",gap:14,marginBottom:12},score:{fontSize:38,fontWeight:"900",color:"#7C3AED"},success:{backgroundColor:"#DCFCE7",padding:14,borderRadius:9},successText:{color:"#166534",fontWeight:"900"},issue:{fontSize:9,fontWeight:"900",color:"#B45309",marginBottom:5}});
