import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { DEFAULT_PHASE25_CERTIFICATION_CHECKS, generatePhase25ReleaseCertification, updateCertificationCheck, type Phase25CertificationCheck } from "../../utils/professionalPhase25CertificationEngine";

type Props={visible:boolean;projectName:string;onClose:()=>void};
export default function ProfessionalPhase25CertificationModal({visible,projectName,onClose}:Props){
 const [checks,setChecks]=useState<Phase25CertificationCheck[]>(DEFAULT_PHASE25_CERTIFICATION_CHECKS);
 const report=useMemo(()=>generatePhase25ReleaseCertification(checks),[checks]);
 const markRuntimePassed=()=>setChecks(c=>updateCertificationCheck(c,"runtime","passed","Manual runtime interaction certification completed."));
 return <Modal visible={visible} animationType="slide" transparent={false} onRequestClose={onClose}><View style={s.root}>
  <View style={s.header}><View><Text style={s.title}>Phase 25 Final Release Certification</Text><Text style={s.sub}>{projectName} · Phase 25.11</Text></View><Pressable style={s.close} onPress={onClose}><Ionicons name="close" size={22} color="#fff"/></Pressable></View>
  <ScrollView contentContainerStyle={s.content}>
   <View style={s.hero}><View><Text style={s.eye}>PHASE 25 READINESS</Text><Text style={s.score}>{report.score}</Text><Text style={s.sub}>{report.releaseReady?"Certified for release":"Certification actions remain"}</Text></View><Ionicons name="ribbon" size={70} color={report.releaseReady?"#34d399":"#38bdf8"}/></View>
   <View style={s.cards}>{[["Passed",report.passed],["Warnings",report.warnings],["Failed",report.failed],["Modules",report.modules.length]].map(([a,b])=><View style={s.card} key={String(a)}><Text style={s.value}>{b}</Text><Text style={s.label}>{a}</Text></View>)}</View>
   <View style={s.actions}><Pressable style={s.primary} onPress={markRuntimePassed}><Text style={s.primaryText}>Mark Runtime Validation Passed</Text></Pressable><Pressable style={s.secondary} onPress={()=>setChecks(DEFAULT_PHASE25_CERTIFICATION_CHECKS)}><Text style={s.primaryText}>Reset Audit</Text></Pressable></View>
   <Text style={s.section}>Certification checks</Text><View style={s.panel}>{report.checks.map(c=><View style={s.row} key={c.id}><Ionicons name={c.status==="passed"?"checkmark-circle":c.status==="failed"?"close-circle":"warning"} size={23} color={c.status==="passed"?"#34d399":c.status==="failed"?"#fb7185":"#fbbf24"}/><View style={s.body}><Text style={s.name}>{c.area}</Text><Text style={s.sub}>{c.message}</Text>{c.remediation?<Text style={s.fix}>{c.remediation}</Text>:null}</View><Text style={c.status==="passed"?s.good:c.status==="failed"?s.bad:s.warn}>{c.status.toUpperCase()}</Text></View>)}</View>
   <Text style={s.section}>Phase 25 module coverage</Text><View style={s.panel}>{report.modules.map(m=><View style={s.row} key={m.id}><Ionicons name="layers-outline" size={22} color="#60a5fa"/><View style={s.body}><Text style={s.name}>Phase {m.id} — {m.name}</Text><Text style={s.sub}>{m.passed}/{m.checks} certification controls passed</Text></View><Text style={s.good}>{m.status.toUpperCase()}</Text></View>)}</View>
  </ScrollView>
 </View></Modal>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#07101a'},header:{height:78,paddingHorizontal:24,backgroundColor:'#0d1b2a',flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#203b55'},title:{fontSize:23,fontWeight:'800',color:'#fff'},sub:{marginTop:4,color:'#9fb3c8'},close:{width:40,height:40,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'#1d3550'},content:{padding:24,gap:18},hero:{padding:24,borderRadius:16,backgroundColor:'#102a43',flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderWidth:1,borderColor:'#1d5f8a'},eye:{color:'#38bdf8',fontSize:12,fontWeight:'800',letterSpacing:1.5},score:{fontSize:52,fontWeight:'900',color:'#fff'},cards:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{minWidth:145,flexGrow:1,padding:18,borderRadius:12,backgroundColor:'#0d1b2a',borderWidth:1,borderColor:'#203b55'},value:{fontSize:25,fontWeight:'800',color:'#fff'},label:{marginTop:5,color:'#91a9bf'},actions:{flexDirection:'row',gap:12},primary:{paddingHorizontal:18,paddingVertical:12,borderRadius:10,backgroundColor:'#0369a1'},secondary:{paddingHorizontal:18,paddingVertical:12,borderRadius:10,backgroundColor:'#334155'},primaryText:{color:'#fff',fontWeight:'800'},section:{fontSize:17,fontWeight:'800',color:'#fff'},panel:{borderRadius:14,backgroundColor:'#0b1724',borderWidth:1,borderColor:'#203b55',overflow:'hidden'},row:{padding:15,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#1b3045'},body:{flex:1,gap:4},name:{color:'#fff',fontWeight:'800'},fix:{color:'#7dd3fc'},good:{color:'#34d399',fontWeight:'800'},warn:{color:'#fbbf24',fontWeight:'800'},bad:{color:'#fb7185',fontWeight:'800'}});
