import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { addBookChapter, addIndexEntry, addPublishingNote, buildOpenTypeFeatureString, composeText, createDesktopPublishingDocument, generateIndex, generateTableOfContents, type DesktopPublishingDocument } from "../../utils/professionalDesktopPublishingEngine";

type Props = { visible: boolean; projectName: string; onClose: () => void };
type Panel = "compose" | "typography" | "grid" | "notes" | "book" | "preflight";
const sample = `Professional publishing requires more than placing text on a page. Yaposan balances line endings, preserves typographic rhythm, and keeps long publications structurally consistent.\n\nintroduces book-level composition with baseline grids, OpenType controls, notes, chapters, tables of contents, and indexes.`;

export default function ProfessionalDesktopPublishingModal({ visible, projectName, onClose }: Props) {
  const [doc, setDoc] = useState<DesktopPublishingDocument>(() => ({ ...createDesktopPublishingDocument(projectName), bodyText: sample }));
  const [panel, setPanel] = useState<Panel>("compose");
  const report = useMemo(() => composeText(doc.bodyText, doc.settings), [doc.bodyText, doc.settings]);
  const patchSettings = (patch: Partial<DesktopPublishingDocument["settings"]>) => setDoc((current) => ({ ...current, settings: { ...current.settings, ...patch }, updatedAt: Date.now() }));
  const button = (label:string, icon:keyof typeof Ionicons.glyphMap, action:()=>void) => <Pressable onPress={action} style={s.button}><Ionicons name={icon} size={18} color="#164E63"/><Text style={s.buttonText}>{label}</Text></Pressable>;
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={s.shell}>
    <View style={s.header}><View><Text style={s.title}>Professional Desktop Publishing Engine</Text><Text style={s.sub}>{report.words} words · {report.estimatedPages} estimated pages</Text></View>{button("Close","close-outline",onClose)}</View>
    <ScrollView horizontal style={s.tabs} contentContainerStyle={s.tabRow}>{(["compose","typography","grid","notes","book","preflight"] as Panel[]).map((item)=><Pressable key={item} onPress={()=>setPanel(item)} style={[s.tab,panel===item&&s.tabActive]}><Text style={[s.tabText,panel===item&&s.tabTextActive]}>{item[0].toUpperCase()+item.slice(1)}</Text></Pressable>)}</ScrollView>
    <ScrollView style={s.main} contentContainerStyle={s.content}>
      {panel==="compose"&&<><Text style={s.heading}>Professional text composition</Text><TextInput multiline value={doc.bodyText} onChangeText={(bodyText)=>setDoc((current)=>({...current,bodyText,updatedAt:Date.now()}))} style={s.editor}/><View style={s.grid}><NumberField label="Columns" value={doc.settings.columns} onChange={(columns)=>patchSettings({columns:Math.max(1,Math.min(8,columns))})}/><NumberField label="Column gap" value={doc.settings.columnGap} onChange={(columnGap)=>patchSettings({columnGap})}/><Toggle label="Optical margins" value={doc.settings.opticalMarginAlignment} onChange={(opticalMarginAlignment)=>patchSettings({opticalMarginAlignment})}/><Toggle label="Keep headings" value={doc.settings.keepHeadingsWithNext} onChange={(keepHeadingsWithNext)=>patchSettings({keepHeadingsWithNext})}/></View><Text style={s.previewHeading}>Composed preview</Text><View style={s.preview}>{report.lines.slice(0,24).map((line,index)=><Text key={index} style={[s.line,line.hyphenated&&s.hyphen]}>{line.text||" "}</Text>)}</View></>}
      {panel==="typography"&&<><Text style={s.heading}>OpenType typography and hyphenation</Text><View style={s.grid}><Toggle label="Standard ligatures" value={doc.settings.openType.ligatures} onChange={(value)=>patchSettings({openType:{...doc.settings.openType,ligatures:value}})}/><Toggle label="Discretionary ligatures" value={doc.settings.openType.discretionaryLigatures} onChange={(value)=>patchSettings({openType:{...doc.settings.openType,discretionaryLigatures:value}})}/><Toggle label="Small caps" value={doc.settings.openType.smallCaps} onChange={(value)=>patchSettings({openType:{...doc.settings.openType,smallCaps:value}})}/><Toggle label="Fractions" value={doc.settings.openType.fractions} onChange={(value)=>patchSettings({openType:{...doc.settings.openType,fractions:value}})}/><Toggle label="Hyphenation" value={doc.settings.hyphenation.enabled} onChange={(value)=>patchSettings({hyphenation:{...doc.settings.hyphenation,enabled:value}})}/><NumberField label="Minimum word" value={doc.settings.hyphenation.minWordLength} onChange={(value)=>patchSettings({hyphenation:{...doc.settings.hyphenation,minWordLength:value}})}/></View><Text style={s.code}>{buildOpenTypeFeatureString(doc.settings.openType)}</Text></>}
      {panel==="grid"&&<><Text style={s.heading}>Baseline grid and pagination</Text><View style={s.grid}><Toggle label="Enable baseline grid" value={doc.settings.baselineGrid.enabled} onChange={(value)=>patchSettings({baselineGrid:{...doc.settings.baselineGrid,enabled:value}})}/><Toggle label="Snap body text" value={doc.settings.baselineGrid.snapBodyText} onChange={(value)=>patchSettings({baselineGrid:{...doc.settings.baselineGrid,snapBodyText:value}})}/><NumberField label="Grid start" value={doc.settings.baselineGrid.start} onChange={(value)=>patchSettings({baselineGrid:{...doc.settings.baselineGrid,start:value}})}/><NumberField label="Grid increment" value={doc.settings.baselineGrid.increment} onChange={(value)=>patchSettings({baselineGrid:{...doc.settings.baselineGrid,increment:value}})}/><NumberField label="Widow lines" value={doc.settings.widowLines} onChange={(widowLines)=>patchSettings({widowLines})}/><NumberField label="Orphan lines" value={doc.settings.orphanLines} onChange={(orphanLines)=>patchSettings({orphanLines})}/></View></>}
      {panel==="notes"&&<><Text style={s.heading}>Footnotes and endnotes</Text><View style={s.row}>{button("Add footnote","return-down-forward-outline",()=>setDoc((current)=>addPublishingNote(current,"footnote",`Footnote ${current.notes.length+1}`)))}{button("Add endnote","list-outline",()=>setDoc((current)=>addPublishingNote(current,"endnote",`Endnote ${current.notes.length+1}`)))}</View>{doc.notes.map((note)=><View key={note.id} style={s.card}><Text style={s.cardTitle}>{note.kind} {note.marker}</Text><Text>{note.text}</Text></View>)}</>}
      {panel==="book"&&<><Text style={s.heading}>Book publishing</Text><View style={s.row}>{button("Add chapter","albums-outline",()=>setDoc((current)=>addBookChapter(current,`Chapter ${current.chapters.length+1}`,current.chapters.reduce((n,c)=>Math.max(n,c.startPage+c.pageCount),1),4)))}{button("Add index term","text-outline",()=>setDoc((current)=>addIndexEntry(current,`Term ${current.indexEntries.length+1}`,Math.max(1,report.estimatedPages))))}</View><Text style={s.previewHeading}>Table of contents</Text><Text style={s.output}>{generateTableOfContents(doc)||"Add chapters to generate a table of contents."}</Text><Text style={s.previewHeading}>Index</Text><Text style={s.output}>{generateIndex(doc)||"Add index entries to generate an index."}</Text></>}
      {panel==="preflight"&&<><Text style={s.heading}>Composition preflight</Text><View style={s.stats}><Stat label="Paragraphs" value={report.paragraphs}/><Stat label="Words" value={report.words}/><Stat label="Characters" value={report.characters}/><Stat label="Pages" value={report.estimatedPages}/><Stat label="Overset risk" value={report.oversetRisk}/></View>{report.warnings.length?report.warnings.map((warning)=><Text key={warning} style={s.warning}>• {warning}</Text>):<Text style={s.ready}>Composition passes current preflight rules.</Text>}</>}
    </ScrollView>
  </View></Modal>;
}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}){return <View style={s.control}><Text style={s.controlLabel}>{label}</Text><Switch value={value} onValueChange={onChange}/></View>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <View style={s.control}><Text style={s.controlLabel}>{label}</Text><TextInput keyboardType="numeric" value={String(value)} onChangeText={(text)=>onChange(Number(text)||0)} style={s.number}/></View>}
function Stat({label,value}:{label:string;value:string|number}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
const s=StyleSheet.create({shell:{flex:1,backgroundColor:"#F1F5F9"},header:{minHeight:76,paddingHorizontal:18,paddingVertical:12,backgroundColor:"#0F172A",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"white",fontSize:21,fontWeight:"800"},sub:{color:"#CBD5E1",marginTop:4},tabs:{maxHeight:50,backgroundColor:"white"},tabRow:{paddingHorizontal:14,alignItems:"center",gap:6},tab:{paddingHorizontal:16,paddingVertical:10,borderRadius:8},tabActive:{backgroundColor:"#CFFAFE"},tabText:{fontWeight:"700",color:"#475569"},tabTextActive:{color:"#0E7490"},main:{flex:1},content:{padding:22},heading:{fontSize:20,fontWeight:"800",color:"#0F172A",marginBottom:14},editor:{minHeight:190,backgroundColor:"white",borderWidth:1,borderColor:"#CBD5E1",borderRadius:10,padding:14,textAlignVertical:"top",lineHeight:22},grid:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:14},row:{flexDirection:"row",flexWrap:"wrap",gap:10},button:{minWidth:110,padding:10,borderRadius:9,backgroundColor:"white",borderWidth:1,borderColor:"#CBD5E1",alignItems:"center",gap:4},buttonText:{fontSize:12,fontWeight:"700",color:"#334155"},control:{minWidth:190,backgroundColor:"white",borderWidth:1,borderColor:"#CBD5E1",borderRadius:9,padding:10,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:12},controlLabel:{fontWeight:"700",color:"#475569"},number:{width:64,borderWidth:1,borderColor:"#CBD5E1",borderRadius:6,padding:7,textAlign:"center"},previewHeading:{fontSize:15,fontWeight:"800",marginTop:20,marginBottom:8,color:"#334155"},preview:{backgroundColor:"white",borderWidth:1,borderColor:"#CBD5E1",borderRadius:10,padding:18,maxWidth:720},line:{fontFamily:"serif",fontSize:15,lineHeight:21,color:"#1E293B"},hyphen:{color:"#0E7490"},code:{marginTop:18,padding:14,backgroundColor:"#0F172A",color:"#E2E8F0",borderRadius:8,fontFamily:"monospace"},card:{backgroundColor:"white",borderWidth:1,borderColor:"#CBD5E1",borderRadius:9,padding:12,marginTop:10},cardTitle:{fontWeight:"800",textTransform:"capitalize",marginBottom:4},output:{backgroundColor:"white",borderWidth:1,borderColor:"#CBD5E1",borderRadius:9,padding:14,fontFamily:"monospace",lineHeight:20},stats:{flexDirection:"row",flexWrap:"wrap",gap:10},stat:{minWidth:130,backgroundColor:"white",borderWidth:1,borderColor:"#CBD5E1",borderRadius:9,padding:14},statValue:{fontSize:22,fontWeight:"800",color:"#0E7490",textTransform:"capitalize"},statLabel:{color:"#64748B",marginTop:4},warning:{marginTop:10,color:"#9A3412",fontWeight:"600"},ready:{marginTop:18,color:"#166534",fontWeight:"800"}});
