import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { auditEnterpriseIntegrations, DEFAULT_ENTERPRISE_INTEGRATION_WORKSPACE, queueIntegrationJob, type IntegrationWorkspace } from "../../utils/professionalEnterpriseIntegrationEngine";

type Props = { visible: boolean; projectName: string; onClose: () => void };

export default function ProfessionalEnterpriseIntegrationModal({ visible, projectName, onClose }: Props) {
  const [workspace, setWorkspace] = useState<IntegrationWorkspace>(DEFAULT_ENTERPRISE_INTEGRATION_WORKSPACE);
  const audit = useMemo(() => auditEnterpriseIntegrations(workspace), [workspace]);
  const runSync = (connectorId: string) => setWorkspace((current) => queueIntegrationJob(current, connectorId, "sync"));
  return <Modal visible={visible} animationType="slide" transparent={false} onRequestClose={onClose}>
    <View style={styles.root}>
      <View style={styles.header}><View><Text style={styles.title}>Enterprise Integration Platform</Text><Text style={styles.subtitle}>{projectName} · </Text></View><Pressable onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color="#fff" /></Pressable></View>
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.hero}><View><Text style={styles.eyebrow}>INTEGRATION READINESS</Text><Text style={styles.score}>{audit.score}</Text><Text style={styles.muted}>Secure connector and API governance score</Text></View><Ionicons name="extension-puzzle" size={66} color="#a78bfa" /></View>
        <View style={styles.cards}>{[["Connected", audit.connected], ["Attention", audit.attention], ["Webhooks", audit.activeWebhooks], ["Successful Jobs", audit.successfulJobs], ["Failed Jobs", audit.failedJobs]].map(([label, value]) => <View key={String(label)} style={styles.card}><Text style={styles.cardValue}>{value}</Text><Text style={styles.cardLabel}>{label}</Text></View>)}</View>
        <Text style={styles.sectionTitle}>Connectors</Text>
        <View style={styles.panel}>{workspace.connectors.map((connector) => <View key={connector.id} style={styles.row}><View style={styles.icon}><Ionicons name={connector.category === "cloud-storage" ? "cloud-outline" : connector.category === "commerce" ? "cart-outline" : "link-outline"} size={22} color="#a78bfa" /></View><View style={styles.body}><Text style={styles.name}>{connector.name}</Text><Text style={styles.muted}>{connector.category} · {connector.syncDirection} · {connector.scopes.length} scopes</Text></View><Text style={[styles.status, connector.status === "connected" ? styles.good : connector.status === "attention" ? styles.warn : styles.off]}>{connector.status.toUpperCase()}</Text>{connector.enabled && <Pressable onPress={() => runSync(connector.id)} style={styles.action}><Text style={styles.actionText}>Queue Sync</Text></Pressable>}</View>)}</View>
        <Text style={styles.sectionTitle}>Webhooks and API events</Text>
        <View style={styles.panel}>{workspace.webhooks.map((hook) => <View key={hook.id} style={styles.row}><Ionicons name="radio-outline" size={22} color="#60a5fa" /><View style={styles.body}><Text style={styles.name}>{hook.name}</Text><Text style={styles.muted}>{hook.event} · signed: {hook.secretConfigured ? "yes" : "no"}</Text></View><Text style={hook.active ? styles.good : styles.off}>{hook.active ? "ACTIVE" : "OFF"}</Text></View>)}</View>
        <Text style={styles.sectionTitle}>Recent integration jobs</Text>
        <View style={styles.panel}>{workspace.jobs.slice(0, 8).map((job) => <View key={job.id} style={styles.row}><Ionicons name={job.status === "completed" ? "checkmark-circle-outline" : job.status === "failed" ? "alert-circle-outline" : "time-outline"} size={22} color={job.status === "completed" ? "#34d399" : job.status === "failed" ? "#fb7185" : "#fbbf24"} /><View style={styles.body}><Text style={styles.name}>{job.operation.toUpperCase()} · {job.connectorId}</Text><Text style={styles.muted}>{job.recordsProcessed} records · {job.status}</Text></View></View>)}</View>
        <Text style={styles.sectionTitle}>Governance audit</Text>
        <View style={styles.panel}>{audit.issues.length === 0 ? <View style={styles.audit}><Ionicons name="shield-checkmark" size={22} color="#34d399" /><Text style={styles.name}>All integration governance checks passed.</Text></View> : audit.issues.map((issue, index) => <View key={`${issue.message}-${index}`} style={styles.audit}><Ionicons name={issue.severity === "error" ? "alert-circle" : "warning"} size={22} color={issue.severity === "error" ? "#fb7185" : "#fbbf24"} /><View style={styles.body}><Text style={styles.name}>{issue.message}</Text><Text style={styles.recommend}>{issue.remediation}</Text></View></View>)}</View>
        <View style={styles.security}><Ionicons name="lock-closed" size={20} color="#34d399" /><Text style={styles.securityText}>Credentials remain outside project documents. Connector adapters use encrypted secrets, least-privilege scopes, signed webhooks, approval gates, and auditable jobs.</Text></View>
      </ScrollView>
    </View>
  </Modal>;
}

const styles = StyleSheet.create({root:{flex:1,backgroundColor:'#080d18'},header:{height:78,paddingHorizontal:24,backgroundColor:'#151a2b',flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#313952'},title:{fontSize:23,fontWeight:'800',color:'#fff'},subtitle:{marginTop:4,color:'#9ca8bd'},close:{width:40,height:40,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'#2a3148'},content:{padding:24,gap:18},hero:{padding:24,borderRadius:16,backgroundColor:'#171b35',flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderWidth:1,borderColor:'#443c74'},eyebrow:{color:'#a78bfa',fontSize:12,fontWeight:'800',letterSpacing:1.5},score:{fontSize:52,fontWeight:'900',color:'#fff'},muted:{color:'#9daac0'},cards:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{minWidth:145,flexGrow:1,padding:18,borderRadius:12,backgroundColor:'#121a2a',borderWidth:1,borderColor:'#2b3650'},cardValue:{fontSize:25,fontWeight:'800',color:'#fff'},cardLabel:{marginTop:5,color:'#91a0b8'},sectionTitle:{fontSize:17,fontWeight:'800',color:'#fff'},panel:{borderRadius:14,backgroundColor:'#101827',borderWidth:1,borderColor:'#29364d',overflow:'hidden'},row:{padding:15,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#233047'},icon:{width:38,height:38,borderRadius:10,backgroundColor:'#272344',alignItems:'center',justifyContent:'center'},body:{flex:1,gap:4},name:{color:'#fff',fontWeight:'800'},status:{fontSize:11,fontWeight:'900'},good:{color:'#34d399',fontWeight:'800'},warn:{color:'#fbbf24',fontWeight:'800'},off:{color:'#94a3b8',fontWeight:'800'},action:{paddingHorizontal:12,paddingVertical:8,borderRadius:8,backgroundColor:'#6d28d9'},actionText:{color:'#fff',fontWeight:'800',fontSize:12},audit:{padding:16,flexDirection:'row',gap:12,alignItems:'flex-start',borderBottomWidth:1,borderBottomColor:'#233047'},recommend:{color:'#a78bfa'},security:{padding:16,borderRadius:12,backgroundColor:'#0d2927',flexDirection:'row',gap:10,alignItems:'center'},securityText:{color:'#b8e4d8',flex:1}});
