import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { auditEnterpriseSecurity, DEFAULT_ENTERPRISE_SECURITY_WORKSPACE, resolveSecurityEvent, setMemberSuspended, type EnterpriseSecurityWorkspace } from "../../utils/professionalEnterpriseSecurityEngine";

type Props = { visible: boolean; projectName: string; onClose: () => void };

export default function ProfessionalEnterpriseSecurityModal({ visible, projectName, onClose }: Props) {
  const [workspace, setWorkspace] = useState<EnterpriseSecurityWorkspace>(DEFAULT_ENTERPRISE_SECURITY_WORKSPACE);
  const audit = useMemo(() => auditEnterpriseSecurity(workspace), [workspace]);
  return <Modal visible={visible} animationType="slide" transparent={false} onRequestClose={onClose}>
    <View style={styles.root}>
      <View style={styles.header}><View><Text style={styles.title}>Enterprise Security & Compliance Center</Text><Text style={styles.subtitle}>{projectName} · </Text></View><Pressable onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color="#fff" /></Pressable></View>
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.hero}><View><Text style={styles.eyebrow}>SECURITY READINESS</Text><Text style={styles.score}>{audit.score}</Text><Text style={styles.muted}>Identity, data protection, sharing, and compliance score</Text></View><Ionicons name="shield-checkmark" size={68} color="#34d399" /></View>
        <View style={styles.cards}>{[["Protected Members", `${audit.protectedMembers}/${workspace.members.filter((m) => !m.suspended).length}`], ["Compliance", `${audit.complianceCoverage}%`], ["Unresolved Events", audit.unresolvedEvents], ["Warnings", audit.warnings], ["Failed Controls", audit.failed]].map(([label, value]) => <View key={String(label)} style={styles.card}><Text style={styles.cardValue}>{value}</Text><Text style={styles.cardLabel}>{label}</Text></View>)}</View>

        <Text style={styles.sectionTitle}>Identity and access</Text>
        <View style={styles.panel}>{workspace.members.map((member) => <View key={member.id} style={styles.row}><View style={styles.icon}><Ionicons name={member.mfaEnabled ? "person-circle" : "person-circle-outline"} size={24} color={member.mfaEnabled ? "#34d399" : "#fbbf24"} /></View><View style={styles.body}><Text style={styles.name}>{member.name}</Text><Text style={styles.muted}>{member.role} · MFA {member.mfaEnabled ? "enabled" : "missing"} · {member.trustedDevice ? "trusted device" : "untrusted device"}</Text></View><Text style={member.suspended ? styles.off : styles.good}>{member.suspended ? "SUSPENDED" : "ACTIVE"}</Text><Pressable onPress={() => setWorkspace((current) => setMemberSuspended(current, member.id, !member.suspended))} style={styles.action}><Text style={styles.actionText}>{member.suspended ? "Restore" : "Suspend"}</Text></Pressable></View>)}</View>

        <Text style={styles.sectionTitle}>Security policies</Text>
        <View style={styles.panel}>{workspace.policies.map((policy) => <View key={policy.id} style={styles.row}><Ionicons name={policy.enforced ? "lock-closed" : "lock-open-outline"} size={22} color={policy.enforced ? "#34d399" : "#fbbf24"} /><View style={styles.body}><Text style={styles.name}>{policy.name}</Text><Text style={styles.muted}>{policy.category} · {policy.description}</Text></View><Text style={policy.enforced ? styles.good : styles.warn}>{policy.enforced ? "ENFORCED" : "MONITOR"}</Text></View>)}</View>

        <Text style={styles.sectionTitle}>Compliance frameworks</Text>
        <View style={styles.panel}>{workspace.frameworks.map((framework) => <View key={framework.id} style={styles.row}><Ionicons name="ribbon-outline" size={22} color="#60a5fa" /><View style={styles.body}><Text style={styles.name}>{framework.name}</Text><Text style={styles.muted}>{framework.passedControls} of {framework.controls} controls passed</Text></View><Text style={styles.good}>{Math.round((framework.passedControls / framework.controls) * 100)}%</Text></View>)}</View>

        <Text style={styles.sectionTitle}>Security events</Text>
        <View style={styles.panel}>{workspace.events.map((event) => <View key={event.id} style={styles.row}><Ionicons name={event.resolved ? "checkmark-circle-outline" : "alert-circle-outline"} size={22} color={event.resolved ? "#34d399" : event.severity === "high" || event.severity === "critical" ? "#fb7185" : "#fbbf24"} /><View style={styles.body}><Text style={styles.name}>{event.message}</Text><Text style={styles.muted}>{event.category} · {event.severity} · {event.actor ?? "system"}</Text></View>{!event.resolved && <Pressable onPress={() => setWorkspace((current) => resolveSecurityEvent(current, event.id))} style={styles.action}><Text style={styles.actionText}>Resolve</Text></Pressable>}</View>)}</View>

        <Text style={styles.sectionTitle}>Security audit</Text>
        <View style={styles.panel}>{audit.issues.length === 0 ? <View style={styles.audit}><Ionicons name="shield-checkmark" size={22} color="#34d399" /><Text style={styles.name}>All enterprise security checks passed.</Text></View> : audit.issues.map((issue, index) => <View key={`${issue.message}-${index}`} style={styles.audit}><Ionicons name={issue.severity === "critical" || issue.severity === "high" ? "alert-circle" : "warning"} size={22} color={issue.severity === "critical" || issue.severity === "high" ? "#fb7185" : "#fbbf24"} /><View style={styles.body}><Text style={styles.name}>{issue.message}</Text><Text style={styles.recommend}>{issue.remediation}</Text></View></View>)}</View>
        <View style={styles.security}><Ionicons name="lock-closed" size={20} color="#34d399" /><Text style={styles.securityText}>Enterprise controls are designed for secure identity, encrypted project handling, governed sharing, auditable publishing, configurable retention, and adapter-based identity-provider integration.</Text></View>
      </ScrollView>
    </View>
  </Modal>;
}

const styles = StyleSheet.create({root:{flex:1,backgroundColor:'#07110f'},header:{height:78,paddingHorizontal:24,backgroundColor:'#10201e',flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#29433e'},title:{fontSize:23,fontWeight:'800',color:'#fff'},subtitle:{marginTop:4,color:'#9ab7b0'},close:{width:40,height:40,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'#25413c'},content:{padding:24,gap:18},hero:{padding:24,borderRadius:16,backgroundColor:'#102c27',flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderWidth:1,borderColor:'#276b5d'},eyebrow:{color:'#34d399',fontSize:12,fontWeight:'800',letterSpacing:1.5},score:{fontSize:52,fontWeight:'900',color:'#fff'},muted:{color:'#9db9b2'},cards:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{minWidth:145,flexGrow:1,padding:18,borderRadius:12,backgroundColor:'#0e1d1b',borderWidth:1,borderColor:'#29443e'},cardValue:{fontSize:25,fontWeight:'800',color:'#fff'},cardLabel:{marginTop:5,color:'#91aaa4'},sectionTitle:{fontSize:17,fontWeight:'800',color:'#fff'},panel:{borderRadius:14,backgroundColor:'#0c1917',borderWidth:1,borderColor:'#29443e',overflow:'hidden'},row:{padding:15,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#203732'},icon:{width:38,height:38,borderRadius:10,backgroundColor:'#17352f',alignItems:'center',justifyContent:'center'},body:{flex:1,gap:4},name:{color:'#fff',fontWeight:'800'},good:{color:'#34d399',fontWeight:'800'},warn:{color:'#fbbf24',fontWeight:'800'},off:{color:'#94a3b8',fontWeight:'800'},action:{paddingHorizontal:12,paddingVertical:8,borderRadius:8,backgroundColor:'#047857'},actionText:{color:'#fff',fontWeight:'800',fontSize:12},audit:{padding:16,flexDirection:'row',gap:12,alignItems:'flex-start',borderBottomWidth:1,borderBottomColor:'#203732'},recommend:{color:'#6ee7b7'},security:{padding:16,borderRadius:12,backgroundColor:'#0d2927',flexDirection:'row',gap:10,alignItems:'center'},securityText:{color:'#b8e4d8',flex:1}});
