import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { certifyEnterpriseProduction, DEFAULT_ENTERPRISE_OPERATIONS_WORKSPACE, optimizeEnterpriseWorkspace, retryOperationsJob, verifyRecoveryPoint, type EnterpriseOperationsWorkspace } from "../../utils/professionalEnterpriseOperationsEngine";

type Props = { visible: boolean; projectName: string; onClose: () => void };
export default function ProfessionalEnterpriseOperationsModal({ visible, projectName, onClose }: Props) {
  const [workspace, setWorkspace] = useState<EnterpriseOperationsWorkspace>(DEFAULT_ENTERPRISE_OPERATIONS_WORKSPACE);
  const report = useMemo(() => certifyEnterpriseProduction(workspace), [workspace]);
  return <Modal visible={visible} animationType="slide" transparent={false} onRequestClose={onClose}><View style={styles.root}>
    <View style={styles.header}><View><Text style={styles.title}>Enterprise Operations & Production Center</Text><Text style={styles.subtitle}>{projectName} · </Text></View><Pressable onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color="#fff" /></Pressable></View>
    <ScrollView contentContainerStyle={styles.content}>
      <View style={styles.hero}><View><Text style={styles.eyebrow}>ENTERPRISE READINESS</Text><Text style={styles.score}>{report.score}</Text><Text style={styles.muted}>Unified production certification score</Text></View><Ionicons name="speedometer" size={68} color="#38bdf8" /></View>
      <View style={styles.cards}>{[["Operational Services", `${report.operationalServices}/${workspace.services.length}`],["Failed Jobs", report.failedJobs],["Verified Backups", `${report.verifiedBackups}/${workspace.recoveryPoints.length}`],["Warnings", report.warnings],["Failed Controls", report.failed]].map(([l,v])=><View key={String(l)} style={styles.card}><Text style={styles.cardValue}>{v}</Text><Text style={styles.cardLabel}>{l}</Text></View>)}</View>
      <View style={styles.actions}><Pressable style={styles.primary} onPress={()=>setWorkspace(optimizeEnterpriseWorkspace(workspace))}><Text style={styles.primaryText}>Optimize Workspace</Text></Pressable><View style={styles.cost}><Text style={styles.name}>AI usage</Text><Text style={styles.muted}>{workspace.metrics.aiRequests} requests · ${workspace.metrics.estimatedAiCost.toFixed(2)} estimated</Text></View></View>
      <Text style={styles.sectionTitle}>System health</Text><View style={styles.panel}>{workspace.services.map(s=><View key={s.id} style={styles.row}><Ionicons name={s.status==="operational"?"checkmark-circle":"warning"} size={22} color={s.status==="operational"?"#34d399":"#fbbf24"}/><View style={styles.body}><Text style={styles.name}>{s.name}</Text><Text style={styles.muted}>{s.latencyMs} ms · checked {new Date(s.lastCheckedAt).toLocaleString()}</Text></View><Text style={s.status==="operational"?styles.good:styles.warn}>{s.status.toUpperCase()}</Text></View>)}</View>
      <Text style={styles.sectionTitle}>Background jobs</Text><View style={styles.panel}>{workspace.jobs.map(j=><View key={j.id} style={styles.row}><Ionicons name={j.status==="failed"?"alert-circle":"cog-outline"} size={22} color={j.status==="failed"?"#fb7185":"#60a5fa"}/><View style={styles.body}><Text style={styles.name}>{j.name}</Text><Text style={styles.muted}>{j.category} · {j.progress}% · retries {j.retries}</Text></View><Text style={j.status==="failed"?styles.bad:styles.good}>{j.status.toUpperCase()}</Text>{j.status==="failed"&&<Pressable style={styles.action} onPress={()=>setWorkspace(c=>retryOperationsJob(c,j.id))}><Text style={styles.actionText}>Retry</Text></Pressable>}</View>)}</View>
      <Text style={styles.sectionTitle}>Recovery center</Text><View style={styles.panel}>{workspace.recoveryPoints.map(p=><View key={p.id} style={styles.row}><Ionicons name="cloud-done-outline" size={22} color={p.verified?"#34d399":"#fbbf24"}/><View style={styles.body}><Text style={styles.name}>{p.name}</Text><Text style={styles.muted}>{p.sizeMb} MB · {new Date(p.createdAt).toLocaleString()}</Text></View><Text style={p.verified?styles.good:styles.warn}>{p.verified?"VERIFIED":"PENDING"}</Text>{!p.verified&&<Pressable style={styles.action} onPress={()=>setWorkspace(c=>verifyRecoveryPoint(c,p.id))}><Text style={styles.actionText}>Verify</Text></Pressable>}</View>)}</View>
      <Text style={styles.sectionTitle}>Production certification</Text><View style={styles.panel}>{report.findings.length===0?<View style={styles.audit}><Ionicons name="ribbon" size={22} color="#34d399"/><Text style={styles.name}>All enterprise production checks passed.</Text></View>:report.findings.map((f,i)=><View key={`${f.area}-${i}`} style={styles.audit}><Ionicons name={f.severity==="critical"||f.severity==="high"?"alert-circle":"warning"} size={22} color={f.severity==="critical"||f.severity==="high"?"#fb7185":"#fbbf24"}/><View style={styles.body}><Text style={styles.name}>{f.area}: {f.message}</Text><Text style={styles.recommend}>{f.remediation}</Text></View></View>)}</View>
    </ScrollView>
  </View></Modal>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#07101a'},header:{height:78,paddingHorizontal:24,backgroundColor:'#0d1b2a',flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#203b55'},title:{fontSize:23,fontWeight:'800',color:'#fff'},subtitle:{marginTop:4,color:'#9fb3c8'},close:{width:40,height:40,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'#1d3550'},content:{padding:24,gap:18},hero:{padding:24,borderRadius:16,backgroundColor:'#102a43',flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderWidth:1,borderColor:'#1d5f8a'},eyebrow:{color:'#38bdf8',fontSize:12,fontWeight:'800',letterSpacing:1.5},score:{fontSize:52,fontWeight:'900',color:'#fff'},muted:{color:'#9fb3c8'},cards:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{minWidth:145,flexGrow:1,padding:18,borderRadius:12,backgroundColor:'#0d1b2a',borderWidth:1,borderColor:'#203b55'},cardValue:{fontSize:25,fontWeight:'800',color:'#fff'},cardLabel:{marginTop:5,color:'#91a9bf'},actions:{flexDirection:'row',gap:12,alignItems:'center'},primary:{paddingHorizontal:18,paddingVertical:12,borderRadius:10,backgroundColor:'#0369a1'},primaryText:{color:'#fff',fontWeight:'800'},cost:{flex:1,padding:12,borderRadius:10,backgroundColor:'#0d1b2a'},sectionTitle:{fontSize:17,fontWeight:'800',color:'#fff'},panel:{borderRadius:14,backgroundColor:'#0b1724',borderWidth:1,borderColor:'#203b55',overflow:'hidden'},row:{padding:15,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#1b3045'},body:{flex:1,gap:4},name:{color:'#fff',fontWeight:'800'},good:{color:'#34d399',fontWeight:'800'},warn:{color:'#fbbf24',fontWeight:'800'},bad:{color:'#fb7185',fontWeight:'800'},action:{paddingHorizontal:12,paddingVertical:8,borderRadius:8,backgroundColor:'#0369a1'},actionText:{color:'#fff',fontWeight:'800',fontSize:12},audit:{padding:16,flexDirection:'row',gap:12,alignItems:'flex-start',borderBottomWidth:1,borderBottomColor:'#1b3045'},recommend:{color:'#7dd3fc'}});
