import { Ionicons } from "@expo/vector-icons";
import React,{useState} from "react";
import {Modal,Pressable,ScrollView,StyleSheet,Text,View} from "react-native";
import type {PublisherProject} from "../../types/publisher";
import {buildProductionReport,normalizePublicationCompletion,runPublicationPreflight,type PublicationIssueCategory} from "../../utils/publicationCompletionEngine";

type Props={visible:boolean;project:PublisherProject;onClose:()=>void;onRunAudit:()=>void;onRepair:()=>void;onPackage:()=>void;onOptimize:()=>void;onCertify:()=>void;onExportJson:()=>void;onExportText:()=>void;onNavigate:(pageId:string,elementId?:string)=>void};
const categories:PublicationIssueCategory[]=["document","typography","asset","layout","style","variable","reference","accessibility","performance"];
export default function PublicationCompletionModal(p:Props){const project=normalizePublicationCompletion(p.project),report=buildProductionReport(project),[filter,setFilter]=useState<PublicationIssueCategory|"all">("all"),issues=runPublicationPreflight(project).filter(i=>filter==="all"||i.category===filter),state=project.publicationCompletion!;return <Modal visible={p.visible} transparent animationType="fade" onRequestClose={p.onClose}><View style={css.back}><View style={css.modal}><View style={css.head}><View><Text style={css.title}>Professional Publishing Completion</Text><Text style={css.sub}>Preflight, repair, accessibility, packaging, optimization, reporting, and certification</Text></View><Pressable onPress={p.onClose} style={css.close}><Ionicons name="close" size={21}/></Pressable></View><ScrollView contentContainerStyle={css.body}>
<View style={css.metrics}><Metric label="Quality score" value={`${report.certificate.score}%`}/><Metric label="Errors" value={report.certificate.errors}/><Metric label="Warnings" value={report.certificate.warnings}/><Metric label="Accessibility" value={`${report.accessibilityScore}%`}/><Metric label="Production ready" value={report.certificate.productionReady?"YES":"NO"}/></View>
<View style={css.actions}><Action icon="scan-outline" label="Run live preflight" onPress={p.onRunAudit}/><Action icon="construct-outline" label="Repair all safe issues" onPress={p.onRepair}/><Action icon="archive-outline" label="Build package manifest" onPress={p.onPackage}/><Action icon="speedometer-outline" label="Optimize publication" onPress={p.onOptimize}/><Action icon="ribbon-outline" label="Certify publication" onPress={p.onCertify}/></View>
<View style={css.card}><Text style={css.h}>Preflight issues</Text><View style={css.filters}><Filter active={filter==="all"} label="All" onPress={()=>setFilter("all")}/>{categories.map(c=><Filter key={c} active={filter===c} label={c} onPress={()=>setFilter(c)}/>)}</View>{issues.length===0?<Text style={css.good}>No issues in this category.</Text>:issues.map(i=><Pressable key={i.id} onPress={()=>i.pageId&&p.onNavigate(i.pageId,i.elementId)} style={css.issue}><Ionicons name={i.severity==="error"?"close-circle":i.severity==="warning"?"warning":"information-circle"} size={18} color={i.severity==="error"?"#b91c1c":i.severity==="warning"?"#b45309":"#0369a1"}/><View style={{flex:1}}><Text style={css.issueText}>{i.message}</Text><Text style={css.meta}>{i.category} · {i.severity}{i.fixId?" · safe repair available":""}</Text></View></Pressable>)}</View>
<View style={css.grid}><View style={css.card}><Text style={css.h}>Certification checks</Text>{Object.entries(report.certificate.checks).map(([k,v])=><View key={k} style={css.line}><Text>{k}</Text><Text style={[css.badge,v==="PASS"?css.pass:v==="WARN"?css.warn:css.fail]}>{v}</Text></View>)}</View><View style={css.card}><Text style={css.h}>Production package</Text><Text style={css.meta}>Package manifest includes project, styles, variables, references, metadata, reports, license, and README.</Text>{state.packageManifest?<><Text style={css.strong}>Checksum: {state.packageManifest.checksum}</Text><Text style={css.meta}>{state.packageManifest.files.length} files · {state.packageManifest.counts.assets} assets · {state.packageManifest.counts.elements} elements</Text></>:<Text style={css.meta}>No package manifest has been generated.</Text>}<Text style={css.meta}>Last optimization: {state.optimizedAt?new Date(state.optimizedAt).toLocaleString():"Not run"}</Text></View></View>
<View style={css.exportRow}><Pressable onPress={p.onExportJson} style={css.primary}><Ionicons name="download-outline" size={18} color="white"/><Text style={css.primaryText}>Export JSON report</Text></Pressable><Pressable onPress={p.onExportText} style={css.secondary}><Ionicons name="document-text-outline" size={18}/><Text>Export text report</Text></Pressable></View>
</ScrollView></View></View></Modal>}
function Metric({label,value}:{label:string;value:string|number}){return <View style={css.metric}><Text style={css.metricValue}>{value}</Text><Text style={css.meta}>{label}</Text></View>}
function Action({icon,label,onPress}:{icon:any;label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={css.action}><Ionicons name={icon} size={20} color="#1e3a8a"/><Text style={css.actionText}>{label}</Text></Pressable>}
function Filter({active,label,onPress}:{active:boolean;label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[css.filter,active&&css.filterActive]}><Text style={active&&css.filterText}>{label}</Text></Pressable>}
const css=StyleSheet.create({back:{flex:1,backgroundColor:"rgba(15,23,42,.72)",alignItems:"center",justifyContent:"center",padding:18},modal:{width:"96%",maxWidth:1180,height:"94%",backgroundColor:"#f8fafc",borderRadius:18,overflow:"hidden"},head:{backgroundColor:"#1e3a8a",padding:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"white",fontSize:22,fontWeight:"900"},sub:{color:"#dbeafe",marginTop:4},close:{backgroundColor:"white",padding:7,borderRadius:9},body:{padding:16,gap:12},metrics:{flexDirection:"row",gap:10,flexWrap:"wrap"},metric:{backgroundColor:"white",borderWidth:1,borderColor:"#bfdbfe",borderRadius:12,padding:12,minWidth:130},metricValue:{fontSize:22,fontWeight:"900",color:"#1e3a8a"},meta:{color:"#64748b",fontSize:12},actions:{flexDirection:"row",gap:8,flexWrap:"wrap"},action:{backgroundColor:"white",borderWidth:1,borderColor:"#bfdbfe",padding:11,borderRadius:10,flexDirection:"row",gap:7,alignItems:"center"},actionText:{fontWeight:"800",color:"#1e3a8a"},card:{backgroundColor:"white",borderWidth:1,borderColor:"#dbeafe",borderRadius:14,padding:15,gap:9,flex:1},h:{fontSize:16,fontWeight:"900"},filters:{flexDirection:"row",gap:6,flexWrap:"wrap"},filter:{borderWidth:1,borderColor:"#cbd5e1",paddingHorizontal:9,paddingVertical:5,borderRadius:999},filterActive:{backgroundColor:"#1e3a8a",borderColor:"#1e3a8a"},filterText:{color:"white",fontWeight:"800"},issue:{flexDirection:"row",gap:9,alignItems:"center",paddingVertical:8,borderTopWidth:1,borderTopColor:"#eff6ff"},issueText:{fontWeight:"700",color:"#1e293b"},good:{color:"#047857",fontWeight:"800",paddingVertical:10},grid:{flexDirection:"row",gap:12,flexWrap:"wrap"},line:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",borderTopWidth:1,borderTopColor:"#eff6ff",paddingVertical:7},badge:{fontWeight:"900",paddingHorizontal:8,paddingVertical:3,borderRadius:999,overflow:"hidden"},pass:{backgroundColor:"#dcfce7",color:"#166534"},warn:{backgroundColor:"#fef3c7",color:"#92400e"},fail:{backgroundColor:"#fee2e2",color:"#991b1b"},strong:{fontWeight:"800",color:"#1e3a8a"},exportRow:{flexDirection:"row",gap:9},primary:{backgroundColor:"#1e3a8a",paddingHorizontal:14,paddingVertical:11,borderRadius:9,flexDirection:"row",gap:7,alignItems:"center"},primaryText:{color:"white",fontWeight:"900"},secondary:{borderWidth:1,borderColor:"#93c5fd",paddingHorizontal:14,paddingVertical:11,borderRadius:9,flexDirection:"row",gap:7,alignItems:"center"}});
