import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherElement } from "../../types/publisher";
import { normalizeRetouchSettings, type RetouchSettings, type RetouchTool } from "../../utils/retouchEngine";

const TOOLS: {id:RetouchTool;label:string;group:string}[]=[
 {id:"smudge",label:"Smudge",group:"Paint Mix"},{id:"liquify-push",label:"Push",group:"Liquify"},{id:"liquify-twirl",label:"Twirl",group:"Liquify"},{id:"liquify-pinch",label:"Pinch",group:"Liquify"},{id:"liquify-bloat",label:"Bloat",group:"Liquify"},
 {id:"clone",label:"Clone Stamp",group:"Repair"},{id:"heal",label:"Healing Brush",group:"Repair"},{id:"dodge",label:"Dodge",group:"Tone"},{id:"burn",label:"Burn",group:"Tone"},{id:"sponge",label:"Sponge",group:"Tone"},{id:"blur",label:"Blur",group:"Detail"},{id:"sharpen",label:"Sharpen",group:"Detail"},{id:"eraser",label:"Advanced Eraser",group:"Detail"},
];
const Field=({label,value,onChange,max=100,min=0}:{label:string;value:number;onChange:(v:number)=>void;max?:number;min?:number})=><View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput keyboardType="numeric" value={String(Math.round(value*100)/100)} onChangeText={t=>onChange(Math.max(min,Math.min(max,Number(t)||0)))} style={styles.input}/></View>;
const Toggle=({label,value,onPress}:{label:string;value:boolean;onPress:()=>void})=><Pressable onPress={onPress} style={[styles.toggle,value&&styles.toggleOn]}><Text style={[styles.toggleText,value&&styles.toggleTextOn]}>{value?"✓ ":""}{label}</Text></Pressable>;
export default function RetouchStudioModal({visible,settings,element,onChange,onApply,onClose}:{visible:boolean;settings:RetouchSettings;element:PublisherElement|null;onChange:(v:RetouchSettings)=>void;onApply:()=>void;onClose:()=>void}){
 const s=normalizeRetouchSettings(settings); const patch=(u:Partial<RetouchSettings>)=>onChange(normalizeRetouchSettings({...s,...u}));
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.panel}>
  <View style={styles.header}><View><Text style={styles.title}>Retouch & Liquify Studio</Text><Text style={styles.sub}>Non-destructive smudge, liquify, repair, tone and detail tools</Text></View><Pressable onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View>
  <ScrollView contentContainerStyle={styles.body}>
   <Text style={styles.section}>Professional Tools</Text><View style={styles.grid}>{TOOLS.map(tool=><Pressable key={tool.id} onPress={()=>patch({tool:tool.id})} style={[styles.tool,s.tool===tool.id&&styles.toolOn]}><Text style={[styles.toolName,s.tool===tool.id&&styles.toolNameOn]}>{tool.label}</Text><Text style={styles.toolGroup}>{tool.group}</Text></Pressable>)}</View>
   <Text style={styles.section}>Brush Control</Text><View style={styles.fields}><Field label="Size" value={s.size} min={1} max={500} onChange={size=>patch({size})}/><Field label="Strength %" value={s.strength*100} onChange={v=>patch({strength:v/100})}/><Field label="Hardness %" value={s.hardness*100} onChange={v=>patch({hardness:v/100})}/><Field label="Flow %" value={s.flow*100} onChange={v=>patch({flow:v/100})}/><Field label="Spacing %" value={s.spacing*100} max={200} onChange={v=>patch({spacing:v/100})}/><Field label="Smoothing %" value={s.smoothing*100} onChange={v=>patch({smoothing:v/100})}/></View>
   <Text style={styles.section}>Tool Dynamics</Text><View style={styles.fields}><Field label="Liquify Density %" value={s.liquifyDensity*100} onChange={v=>patch({liquifyDensity:v/100})}/><Field label="Liquify Rate %" value={s.liquifyRate*100} onChange={v=>patch({liquifyRate:v/100})}/><Field label="Smudge Mix %" value={s.smudgeMix*100} onChange={v=>patch({smudgeMix:v/100})}/><Field label="Smudge Load %" value={s.smudgeLoad*100} onChange={v=>patch({smudgeLoad:v/100})}/><Field label="Healing Diffusion %" value={s.healingDiffusion*100} onChange={v=>patch({healingDiffusion:v/100})}/></View>
   <View style={styles.row}><Toggle label="Pressure Size" value={s.pressureSize} onPress={()=>patch({pressureSize:!s.pressureSize})}/><Toggle label="Pressure Strength" value={s.pressureStrength} onPress={()=>patch({pressureStrength:!s.pressureStrength})}/><Toggle label="Protect Alpha" value={s.protectAlpha} onPress={()=>patch({protectAlpha:!s.protectAlpha})}/><Toggle label="Aligned Clone" value={s.cloneAligned} onPress={()=>patch({cloneAligned:!s.cloneAligned})}/></View>
   <Text style={styles.section}>Non-Destructive Workflow</Text><View style={styles.row}><Pressable style={[styles.choice,s.mode==="non-destructive"&&styles.choiceOn]} onPress={()=>patch({mode:"non-destructive"})}><Text style={styles.choiceText}>Non-destructive</Text></Pressable><Pressable style={[styles.choice,s.mode==="baked"&&styles.choiceOn]} onPress={()=>patch({mode:"baked"})}><Text style={styles.choiceText}>Bake on Apply</Text></Pressable></View>
   <Text style={styles.status}>{element?`${element.retouchOperations?.length??0} retouch operations on selected object`:"Select an image or painted stroke to apply retouching."}</Text>
   <View style={styles.actions}><Pressable disabled={!element} style={[styles.primary,!element&&styles.disabled]} onPress={onApply}><Text style={styles.primaryText}>Apply {TOOLS.find(t=>t.id===s.tool)?.label}</Text></Pressable><Pressable style={styles.secondary} onPress={onClose}><Text style={styles.secondaryText}>Close</Text></Pressable></View>
  </ScrollView>
 </View></View></Modal>
}
const styles=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(2,6,23,.78)",alignItems:"center",justifyContent:"center",padding:20},panel:{width:"94%",maxWidth:1000,maxHeight:"92%",backgroundColor:"#F8FAFC",borderRadius:18,overflow:"hidden",borderWidth:1,borderColor:"#334155"},header:{backgroundColor:"#0F172A",padding:18,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"#FFF",fontSize:20,fontWeight:"900"},sub:{color:"#94A3B8",fontSize:12,marginTop:4},close:{width:34,height:34,borderRadius:17,backgroundColor:"#334155",alignItems:"center",justifyContent:"center"},closeText:{color:"#FFF",fontSize:24},body:{padding:18,gap:12},section:{fontSize:13,fontWeight:"900",color:"#0F172A",marginTop:5},grid:{flexDirection:"row",flexWrap:"wrap",gap:8},tool:{width:142,padding:11,borderRadius:11,backgroundColor:"#FFF",borderWidth:1,borderColor:"#CBD5E1"},toolOn:{backgroundColor:"#EDE9FE",borderColor:"#7C3AED",borderWidth:2},toolName:{fontWeight:"900",color:"#172033"},toolNameOn:{color:"#5B21B6"},toolGroup:{fontSize:10,color:"#64748B",marginTop:3},fields:{flexDirection:"row",flexWrap:"wrap",gap:9},field:{width:155},label:{fontSize:10,fontWeight:"800",color:"#475569",marginBottom:4},input:{backgroundColor:"#FFF",borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,paddingHorizontal:10,paddingVertical:8},row:{flexDirection:"row",flexWrap:"wrap",gap:8},toggle:{paddingHorizontal:12,paddingVertical:8,borderRadius:9,backgroundColor:"#E2E8F0"},toggleOn:{backgroundColor:"#DDD6FE",borderWidth:1,borderColor:"#7C3AED"},toggleText:{fontWeight:"800",color:"#475569",fontSize:11},toggleTextOn:{color:"#5B21B6"},choice:{paddingHorizontal:14,paddingVertical:10,borderRadius:9,backgroundColor:"#E2E8F0"},choiceOn:{backgroundColor:"#C4B5FD"},choiceText:{fontWeight:"900",color:"#312E81"},status:{backgroundColor:"#E0F2FE",color:"#075985",padding:10,borderRadius:9,fontWeight:"700"},actions:{flexDirection:"row",gap:9,marginTop:5},primary:{backgroundColor:"#7C3AED",paddingHorizontal:17,paddingVertical:11,borderRadius:10},primaryText:{color:"#FFF",fontWeight:"900"},secondary:{backgroundColor:"#E2E8F0",paddingHorizontal:16,paddingVertical:11,borderRadius:10},secondaryText:{color:"#172033",fontWeight:"900"},disabled:{opacity:.4}});
