import { Ionicons } from "@expo/vector-icons";
import { useEffect, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { clearTelemetryData, DEFAULT_TELEMETRY_CONSENT, exportTelemetryReport, getTelemetrySnapshot, recordTelemetryEvent, setTelemetryConsent, telemetryAvailable, type TelemetryConsent, type TelemetrySnapshot } from "../../utils/telemetryDiagnosticsEngine";

type Props = { visible: boolean; onClose: () => void; onExportReport: (source: string) => void };
export default function TelemetryDiagnosticsCenterModal({ visible, onClose, onExportReport }: Props) {
  const [snapshot, setSnapshot] = useState<TelemetrySnapshot>({ consent: DEFAULT_TELEMETRY_CONSENT, queuedEvents: 0, recentEvents: [], sessionId: "-", storage: "browser-memory" });
  useEffect(() => { if (visible) void getTelemetrySnapshot().then(setSnapshot); }, [visible]);
  const update = async (patch: Partial<Omit<TelemetryConsent, "updatedAt">>) => setSnapshot(await setTelemetryConsent({ ...snapshot.consent, ...patch }));
  const runDiagnostic = async () => { await recordTelemetryEvent({ category: "performance", name: "manual-diagnostics-check", durationMs: 1, properties: { source: "diagnostics-center" } }); setSnapshot(await getTelemetrySnapshot()); };
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.card} accessibilityViewIsModal>
    <View style={styles.header}><View><Text style={styles.title}>Telemetry & Diagnostics Center</Text><Text style={styles.subtitle}>Private by default. Nothing is collected until you opt in.</Text></View><Pressable onPress={onClose} style={styles.iconButton}><Ionicons name="close" size={22} color="#172033" /></Pressable></View>
    <ScrollView contentContainerStyle={styles.content}>
      <View style={styles.notice}><Ionicons name="shield-checkmark" size={23} color="#087a43" /><Text style={styles.noticeText}>Telemetry contains no document content, names, email addresses, or imported assets. You can review, export, or erase the local queue at any time.</Text></View>
      <View style={styles.summary}><View><Text style={styles.label}>Runtime</Text><Text style={styles.value}>{telemetryAvailable() ? "Desktop" : "Web preview"}</Text></View><View><Text style={styles.label}>Stored events</Text><Text style={styles.value}>{snapshot.queuedEvents}</Text></View><View><Text style={styles.label}>Storage</Text><Text style={styles.value}>{snapshot.storage}</Text></View></View>
      <Text style={styles.section}>Privacy controls</Text>
      <Setting label="Enable optional telemetry" description="Master switch for all anonymous diagnostics." value={snapshot.consent.enabled} onChange={(value) => void update({ enabled: value, crashReports: value && snapshot.consent.crashReports, performanceMetrics: value && snapshot.consent.performanceMetrics, anonymousUsage: value && snapshot.consent.anonymousUsage })} />
      <Setting label="Crash reports" description="Records error type, app version, and operating system—never document content." value={snapshot.consent.crashReports} disabled={!snapshot.consent.enabled} onChange={(value) => void update({ crashReports: value })} />
      <Setting label="Performance metrics" description="Measures startup, rendering, and export duration." value={snapshot.consent.performanceMetrics} disabled={!snapshot.consent.enabled} onChange={(value) => void update({ performanceMetrics: value })} />
      <Setting label="Anonymous feature usage" description="Counts feature opens and successful operations without user identity." value={snapshot.consent.anonymousUsage} disabled={!snapshot.consent.enabled} onChange={(value) => void update({ anonymousUsage: value })} />
      <Text style={styles.section}>Recent local events</Text>
      <View style={styles.events}>{snapshot.recentEvents.length ? snapshot.recentEvents.slice(0, 12).map((event) => <View key={event.id} style={styles.event}><Ionicons name={event.category === "crash" ? "warning-outline" : event.category === "performance" ? "speedometer-outline" : "analytics-outline"} size={18} color="#2354d8" /><View style={{flex:1}}><Text style={styles.eventName}>{event.name}</Text><Text style={styles.eventMeta}>{event.category} · {new Date(event.timestamp).toLocaleString()}{event.durationMs != null ? ` · ${event.durationMs} ms` : ""}</Text></View></View>) : <Text style={styles.empty}>No telemetry events are stored.</Text>}</View>
    </ScrollView>
    <View style={styles.footer}><Pressable onPress={() => void clearTelemetryData().then(setSnapshot)} style={styles.danger}><Text style={styles.dangerText}>Erase Local Data</Text></Pressable><Pressable onPress={() => void runDiagnostic()} style={styles.secondary}><Text style={styles.secondaryText}>Run Diagnostic</Text></Pressable><Pressable onPress={() => void exportTelemetryReport().then(onExportReport)} style={styles.primary}><Ionicons name="download-outline" size={18} color="#fff" /><Text style={styles.primaryText}>Export Report</Text></Pressable></View>
  </View></View></Modal>;
}
function Setting({ label, description, value, disabled, onChange }: { label:string; description:string; value:boolean; disabled?:boolean; onChange:(value:boolean)=>void }) { return <View style={[styles.setting, disabled && styles.disabled]}><View style={{flex:1}}><Text style={styles.settingTitle}>{label}</Text><Text style={styles.settingDescription}>{description}</Text></View><Switch disabled={disabled} value={value} onValueChange={onChange} /></View>; }
const styles=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(10,18,35,.6)",alignItems:"center",justifyContent:"center",padding:20},card:{width:"100%",maxWidth:880,maxHeight:"92%",backgroundColor:"#fff",borderRadius:18,padding:20},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:16},title:{fontSize:24,fontWeight:"900",color:"#172033"},subtitle:{marginTop:4,color:"#667085"},iconButton:{width:40,height:40,borderRadius:20,alignItems:"center",justifyContent:"center",backgroundColor:"#f2f4f7"},content:{gap:14,paddingVertical:18},notice:{flexDirection:"row",gap:10,padding:14,borderRadius:12,backgroundColor:"#ecfdf3"},noticeText:{flex:1,color:"#344054",lineHeight:20},summary:{flexDirection:"row",flexWrap:"wrap",gap:28,padding:16,borderRadius:14,backgroundColor:"#f8fafc"},label:{fontSize:12,fontWeight:"700",color:"#667085"},value:{marginTop:3,fontSize:17,fontWeight:"900",color:"#172033"},section:{fontSize:16,fontWeight:"900",color:"#172033",marginTop:4},setting:{flexDirection:"row",alignItems:"center",gap:15,padding:13,borderWidth:1,borderColor:"#eaecf0",borderRadius:12},settingTitle:{fontWeight:"800",color:"#344054"},settingDescription:{marginTop:3,color:"#667085",lineHeight:18},disabled:{opacity:.5},events:{borderWidth:1,borderColor:"#eaecf0",borderRadius:12,overflow:"hidden"},event:{flexDirection:"row",alignItems:"center",gap:10,padding:12,borderBottomWidth:1,borderBottomColor:"#f2f4f7"},eventName:{fontWeight:"800",color:"#344054"},eventMeta:{marginTop:2,fontSize:12,color:"#667085"},empty:{padding:18,textAlign:"center",color:"#667085"},footer:{flexDirection:"row",justifyContent:"flex-end",gap:10,flexWrap:"wrap"},primary:{flexDirection:"row",alignItems:"center",gap:7,paddingHorizontal:17,paddingVertical:11,borderRadius:10,backgroundColor:"#2354d8"},primaryText:{fontWeight:"800",color:"#fff"},secondary:{paddingHorizontal:17,paddingVertical:11,borderRadius:10,backgroundColor:"#f2f4f7"},secondaryText:{fontWeight:"800",color:"#344054"},danger:{paddingHorizontal:17,paddingVertical:11,borderRadius:10,backgroundColor:"#fef3f2"},dangerText:{fontWeight:"800",color:"#b42318"}});
