import { Ionicons } from "@expo/vector-icons";
import { router, usePathname } from "expo-router";
import type { ReactNode } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { buildContactHref } from "../../utils/supportContext";

export default function Phase241IShell({title,subtitle,accent="#0ea5e9",children,actions=[]}:{title:string;subtitle:string;accent?:string;children:ReactNode;actions?:ReactNode[]}){
  const pathname = usePathname();
  const helpHref = `/help?topic=${encodeURIComponent(title)}`;
  const reportHref = buildContactHref({source:title,page:pathname});
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><View style={s.top}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={()=>router.canGoBack() ? router.back() : router.replace("/" as never)} style={s.back}><Ionicons name="arrow-back" size={20} color="#fff"/></Pressable><View style={{flex:1}}><Text style={s.brand}>Yaposan Creative Suite · Phase 24.1I</Text><Text style={s.topTitle}>{title}</Text></View><View style={s.actions}><Pressable accessibilityRole="link" accessibilityLabel={`Help for ${title}`} onPress={()=>router.push(helpHref as never)} style={s.help}><Ionicons name="help-circle-outline" size={17} color="#fff"/><Text style={s.helpText}>Help</Text></Pressable><Pressable accessibilityRole="link" accessibilityLabel={`Report a problem in ${title}`} onPress={()=>router.push(reportHref as never)} style={s.report}><Ionicons name="warning-outline" size={16} color="#fff"/><Text style={s.helpText}>Report</Text></Pressable>{actions.map((a,i)=><View key={i}>{a}</View>)}</View></View><View style={s.hero}><View style={s.heroCopy}><Text style={s.title}>{title}</Text><Text style={s.sub}>{subtitle}</Text></View><View style={[s.badge,{backgroundColor:accent}]}><Ionicons name="flash" size={20} color="#fff"/><Text style={s.badgeText}>Productivity ready</Text></View></View>{children}</ScrollView></SafeAreaView>
}
export const phase241IStyles=StyleSheet.create({section:{backgroundColor:"#fff",borderRadius:18,padding:18,borderWidth:1,borderColor:"#d8e2ec",gap:12},sectionTitle:{fontSize:18,fontWeight:"900",color:"#13283b"},grid:{flexDirection:"row",flexWrap:"wrap",gap:12},card:{minWidth:210,flex:1,backgroundColor:"#f8fbfd",borderWidth:1,borderColor:"#dbe5ee",borderRadius:14,padding:14,gap:7},label:{fontSize:11,fontWeight:"900",color:"#526b80",textTransform:"uppercase"},input:{height:42,borderWidth:1,borderColor:"#cbd7e2",borderRadius:10,paddingHorizontal:11,backgroundColor:"#fff",color:"#13283b"},button:{paddingHorizontal:14,paddingVertical:11,borderRadius:10,backgroundColor:"#0ea5e9",alignItems:"center",justifyContent:"center"},buttonText:{color:"#fff",fontWeight:"900"},secondary:{backgroundColor:"#e7eef5"},secondaryText:{color:"#183149",fontWeight:"900"},row:{flexDirection:"row",alignItems:"center",gap:10,flexWrap:"wrap"},muted:{color:"#64748b",lineHeight:19},metric:{fontSize:28,fontWeight:"900",color:"#13283b"},pill:{paddingHorizontal:9,paddingVertical:5,borderRadius:99,backgroundColor:"#e2e8f0"},pillText:{fontSize:10,fontWeight:"900",color:"#334155"}});
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#eaf0f6"},page:{padding:22,gap:16},top:{backgroundColor:"#0b1d2d",borderRadius:16,padding:15,flexDirection:"row",alignItems:"center",gap:12,flexWrap:"wrap"},back:{width:36,height:36,borderRadius:10,backgroundColor:"#18364d",alignItems:"center",justifyContent:"center"},brand:{color:"#9fb1c1",fontSize:10,fontWeight:"800"},topTitle:{color:"#fff",fontSize:17,fontWeight:"900",marginTop:2},actions:{flexDirection:"row",gap:8,alignItems:"center",flexWrap:"wrap"},help:{flexDirection:"row",alignItems:"center",gap:6,backgroundColor:"#18364d",paddingHorizontal:11,paddingVertical:9,borderRadius:9},report:{flexDirection:"row",alignItems:"center",gap:6,backgroundColor:"#7c2d12",paddingHorizontal:11,paddingVertical:9,borderRadius:9},helpText:{color:"#fff",fontWeight:"900",fontSize:12},hero:{backgroundColor:"#fff",borderRadius:20,padding:24,flexDirection:"row",flexWrap:"wrap",gap:12,justifyContent:"space-between",alignItems:"center",borderWidth:1,borderColor:"#d8e2ec"},heroCopy:{flex:1,minWidth:240},title:{fontSize:32,fontWeight:"900",color:"#102234"},sub:{fontSize:14,color:"#64748b",marginTop:6,maxWidth:760},badge:{paddingHorizontal:14,paddingVertical:11,borderRadius:13,flexDirection:"row",alignItems:"center",gap:7},badgeText:{color:"#fff",fontWeight:"900"}});
