import { Ionicons } from '@expo/vector-icons';
import type { Dispatch, SetStateAction } from 'react';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import PostAudiencePicker, { type AudienceCandidate, type PostAudience } from './PostAudiencePicker';

export type Reaction='like'|'dislike'|'love'|'laugh'|'wow'|'fire';
export type PageComment={id:string;body:string;createdAt:string;parentCommentId?:string;reactions?:Record<string,number>;myReaction?:Reaction};
export type PagePost={id:string;spaceId?:string;body:string;createdAt:string;visibility?:string;audienceUserIds?:string[];comments:PageComment[];reactions?:Record<string,number>;myReaction?:Reaction;bookmarked?:boolean;repostsCount?:number};
const emojiReactions:[Reaction,string][]=[['love','❤️'],['laugh','😂'],['wow','😮'],['fire','🔥']];

type Props={post:PagePost;text:string;muted:string;border:string;panel:string;comments:Record<string,string>;setComments:Dispatch<SetStateAction<Record<string,string>>>;replyTo:Record<string,string|undefined>;setReplyTo:Dispatch<SetStateAction<Record<string,string|undefined>>>;onPostAction:(post:PagePost,path:string,payload?:unknown)=>Promise<void>;onComment:(post:PagePost,parentCommentId?:string)=>Promise<void>;onCommentReaction:(post:PagePost,comment:PageComment,kind:Reaction)=>Promise<void>;audienceCandidates:AudienceCandidate[];onPrivacyChange:(post:PagePost,visibility:PostAudience,audienceUserIds:string[])=>Promise<void>};

function ReactionControls({myReaction,reactions,onReact,border,panel,compact=false}:{myReaction?:Reaction;reactions?:Record<string,number>;onReact:(kind:Reaction)=>void;border:string;panel:string;compact?:boolean}){
 const [open,setOpen]=useState(false); const likeCount=reactions?.like??0,dislikeCount=reactions?.dislike??0;
 return <View style={s.inlineActions}><Pressable onPress={()=>onReact('like')} style={[s.actionButton,{borderColor:border,backgroundColor:panel},myReaction==='like'&&s.reactionOn]}><Text>{compact?'👍':`👍 Like ${likeCount}`}</Text></Pressable><Pressable onPress={()=>onReact('dislike')} style={[s.actionButton,{borderColor:border,backgroundColor:panel},myReaction==='dislike'&&s.reactionOn]}><Text>{compact?'👎':`👎 Dislike ${dislikeCount}`}</Text></Pressable><View style={s.menuAnchor}><Pressable onPress={()=>setOpen(v=>!v)} style={[s.actionButton,{borderColor:border,backgroundColor:panel}]}><Text>😊</Text><Ionicons name="chevron-down" size={12}/></Pressable>{open?<View style={[s.emojiMenu,{borderColor:border,backgroundColor:panel}]}>{emojiReactions.map(([kind,emoji])=><Pressable key={kind} onPress={()=>{onReact(kind);setOpen(false)}} style={[s.emojiChoice,myReaction===kind&&s.reactionOn]}><Text>{emoji} {reactions?.[kind]??0}</Text></Pressable>)}</View>:null}</View></View>;
}

export default function PagePostCard({post:p,text,muted,border,panel,comments,setComments,replyTo,setReplyTo,onPostAction,onComment,onCommentReaction,audienceCandidates,onPrivacyChange}:Props){
 const commentActions=(c:PageComment)=><ReactionControls compact myReaction={c.myReaction} reactions={c.reactions} border={border} panel={panel} onReact={kind=>void onCommentReaction(p,c,kind)}/>;
 return <View style={[s.card,{backgroundColor:panel,borderColor:border}]}><Text style={[s.postText,{color:text}]}>{p.body}</Text><Text style={[s.meta,{color:muted}]}>{new Date(p.createdAt).toLocaleString()} · {p.comments.length} comments · {p.repostsCount??0} reposts</Text><View style={s.actions}><ReactionControls myReaction={p.myReaction} reactions={p.reactions} border={border} panel={panel} onReact={kind=>void onPostAction(p,`/posts/${p.id}/reaction`,{kind})}/><PostAudiencePicker value={((p.visibility==='friends'?'followers':['private','followers','specific','public'].includes(String(p.visibility))?p.visibility:'private') as PostAudience)} selectedUserIds={p.audienceUserIds??[]} candidates={audienceCandidates} text={text} muted={muted} border={border} panel={panel} onChange={(visibility,userIds)=>void onPrivacyChange(p,visibility,userIds)}/></View>{p.comments.filter(c=>!c.parentCommentId).map(c=><View key={c.id} style={[s.comment,{borderColor:border}]}><Text style={{color:text}}>{c.body}</Text>{commentActions(c)}<Pressable onPress={()=>setReplyTo(v=>({...v,[p.id]:v[p.id]===c.id?undefined:c.id}))}><Text style={s.replyLink}>Reply</Text></Pressable>{p.comments.filter(r=>r.parentCommentId===c.id).map(r=><View key={r.id} style={[s.nested,{borderLeftColor:border}]}><Text style={{color:text}}>↳ {r.body}</Text>{commentActions(r)}<Pressable onPress={()=>setReplyTo(v=>({...v,[p.id]:c.id}))}><Text style={s.replyLink}>Reply to reply</Text></Pressable></View>)}{replyTo[p.id]===c.id?<View style={s.commentRow}><TextInput value={comments[`${p.id}:${c.id}`]??''} onChangeText={v=>setComments(x=>({...x,[`${p.id}:${c.id}`]:v}))} placeholder="Reply…" placeholderTextColor={muted} style={[s.input,{color:text,borderColor:border}]}/><Pressable onPress={()=>void onComment(p,c.id)} style={s.send}><Ionicons name="send" size={16} color="#fff"/></Pressable></View>:null}</View>)}<View style={s.commentRow}><TextInput value={comments[p.id]??''} onChangeText={v=>setComments(x=>({...x,[p.id]:v}))} placeholder="Write a comment…" placeholderTextColor={muted} style={[s.input,{color:text,borderColor:border}]}/><Pressable onPress={()=>void onComment(p)} style={s.send}><Ionicons name="send" size={16} color="#fff"/></Pressable></View></View>;
}
const s=StyleSheet.create({card:{borderWidth:1,borderRadius:18,padding:16,marginBottom:12},postText:{fontSize:15,lineHeight:23},meta:{fontSize:11,marginTop:10},actions:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:11,alignItems:'center'},inlineActions:{flexDirection:'row',flexWrap:'wrap',gap:6,alignItems:'center'},actionButton:{borderWidth:1,borderRadius:999,paddingHorizontal:9,paddingVertical:6,flexDirection:'row',gap:4,alignItems:'center'},reactionOn:{backgroundColor:'#ede9fe',borderColor:'#7c3aed'},menuAnchor:{position:'relative'},emojiMenu:{position:'absolute',zIndex:40,top:38,left:0,flexDirection:'row',gap:3,borderWidth:1,borderRadius:12,padding:6,shadowColor:'#000',shadowOpacity:.12,shadowRadius:10},emojiChoice:{padding:7,borderRadius:8},privacyMenu:{position:'absolute',zIndex:40,top:38,right:0,minWidth:190,borderWidth:1,borderRadius:12,padding:6,shadowColor:'#000',shadowOpacity:.12,shadowRadius:10},privacyChoice:{flexDirection:'row',gap:8,alignItems:'center',padding:9,borderRadius:8},comment:{marginTop:12,padding:11,borderWidth:1,borderRadius:12},nested:{marginTop:9,marginLeft:18,paddingLeft:10,borderLeftWidth:2},replyLink:{color:'#7c3aed',fontWeight:'800',fontSize:11,marginTop:7},commentRow:{flexDirection:'row',gap:8,marginTop:10},input:{flex:1,borderWidth:1,borderRadius:10,paddingHorizontal:11,paddingVertical:8},send:{width:40,borderRadius:10,backgroundColor:'#7c3aed',alignItems:'center',justifyContent:'center'}});
