import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useMemo,useState } from "react";
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View,useWindowDimensions } from "react-native";
import { addMotionClip,createMotionProject,formatTime,removeMotionClip,setPlayhead,splitMotionClip,type MotionTrackKind } from "../../utils/motionStudioEngine";
const kinds:MotionTrackKind[]=["video","image","text","audio","effect"];
export default function MotionWorkspace({mode}:{mode:"video"|"animation"}){const router=useRouter();const {width}=useWindowDimensions();const compact=width<900;const [project,setProject]=useState(()=>createMotionProject(mode==="video"?"New Video":"New Animation"));const [selected,setSelected]=useState(project.clips[0]?.id??"");const active=useMemo(()=>project.clips.find(c=>c.id===selected),[project,selected]);const accent=mode==="video"?"#f97316":"#ec4899";const title=mode==="video"?"Video Studio":"Animation Studio";
const step=(d:number)=>setProject(p=>setPlayhead(p,p.playhead+d));
return <SafeAreaView style={s.safe}><View style={s.top}><Pressable style={s.back} onPress={()=>router.replace("/")}><Ionicons name="arrow-back" size={18} color="#fff"/><Text style={s.bt}>Home</Text></Pressable><View style={{flex:1}}><Text style={s.brand}>YAPOSAN PHASE 26</Text><Text style={s.title}>{title}</Text></View><View style={[s.ready,{borderColor:accent}]}><Text style={{color:accent,fontWeight:"900"}}>PRO WORKSPACE</Text></View></View><View style={[s.body,compact&&s.compact]}>
<View style={s.left}><Text style={s.h}>Add media & layers</Text>{kinds.map(k=><Pressable key={k} style={s.tool} onPress={()=>setProject(p=>addMotionClip(p,k))}><Ionicons name={k==="video"?"videocam-outline":k==="audio"?"musical-notes-outline":k==="text"?"text-outline":k==="image"?"image-outline":"sparkles-outline"} size={18} color={accent}/><Text style={s.toolText}>Add {k}</Text></Pressable>)}<Text style={s.h}>Output</Text><Text style={s.meta}>1920 × 1080 • {project.fps} fps</Text><Text style={s.meta}>MP4 • WebM • GIF • Lottie</Text></View>
<View style={s.main}><View style={s.preview}><Ionicons name={mode==="video"?"play-circle-outline":"color-wand-outline"} size={78} color={accent}/><Text style={s.previewTitle}>{project.name}</Text><Text style={s.previewSub}>{formatTime(project.playhead,project.fps)} / {formatTime(project.duration,project.fps)}</Text></View><View style={s.controls}><Pressable style={s.control} onPress={()=>step(-1)}><Ionicons name="play-back" size={20} color="#fff"/></Pressable><Pressable style={[s.control,{backgroundColor:accent}]} onPress={()=>setProject(p=>({...p,playing:!p.playing}))}><Ionicons name={project.playing?"pause":"play"} size={22} color="#fff"/></Pressable><Pressable style={s.control} onPress={()=>step(1)}><Ionicons name="play-forward" size={20} color="#fff"/></Pressable><Pressable style={s.action} disabled={!active} onPress={()=>active&&setProject(p=>splitMotionClip(p,active.id,p.playhead))}><Text style={s.actionText}>Split</Text></Pressable><Pressable style={s.action} disabled={!active} onPress={()=>active&&setProject(p=>removeMotionClip(p,active.id))}><Text style={s.actionText}>Delete</Text></Pressable></View>
<View style={s.timeline}><ScrollView><Pressable style={s.ruler} onPress={()=>setProject(p=>setPlayhead(p,(p.playhead+5)%p.duration))}><Text style={s.rulerText}>00:00     00:05     00:10     00:15     00:20     00:25     00:30</Text></Pressable>{project.clips.map(c=><Pressable key={c.id} onPress={()=>setSelected(c.id)} style={[s.clip,{marginLeft:`${(c.start/project.duration)*82}%`,width:`${Math.max(14,(c.duration/project.duration)*82)}%`,backgroundColor:c.color},selected===c.id&&s.clipOn]}><Text numberOfLines={1} style={s.clipText}>{c.name} • {c.kind}</Text></Pressable>)}<View style={[s.playhead,{left:`${10+(project.playhead/project.duration)*82}%`,backgroundColor:accent}]}/></ScrollView></View></View>
<View style={s.right}><Text style={s.h}>Inspector</Text><Text style={s.label}>Selected layer</Text><Text style={s.value}>{active?.name??"None"}</Text><Text style={s.label}>Start</Text><Text style={s.value}>{active?formatTime(active.start):"--"}</Text><Text style={s.label}>Duration</Text><Text style={s.value}>{active?`${active.duration.toFixed(1)} sec`:"--"}</Text><Text style={s.h}>Phase 26 tools</Text>{["Trim & split","Multi-track timeline","Keyframes & motion paths","Transitions & effects","Titles & captions","Social resize & export"].map(x=><View key={x} style={s.check}><Ionicons name="checkmark-circle" size={16} color="#22c55e"/><Text style={s.checkText}>{x}</Text></View>)}</View>
</View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#020817"},top:{minHeight:74,padding:12,flexDirection:"row",alignItems:"center",gap:14,borderBottomWidth:1,borderColor:"#1f3349"},back:{flexDirection:"row",gap:7,alignItems:"center",backgroundColor:"#14263a",padding:11,borderRadius:10},bt:{color:"#fff",fontWeight:"800"},brand:{color:"#67e8f9",fontSize:10,fontWeight:"900",letterSpacing:1.5},title:{color:"#fff",fontSize:22,fontWeight:"900"},ready:{borderWidth:1,borderRadius:99,padding:10},body:{flex:1,flexDirection:"row",gap:12,padding:12},compact:{flexDirection:"column"},left:{width:210,backgroundColor:"#071426",borderRadius:16,padding:14},right:{width:230,backgroundColor:"#071426",borderRadius:16,padding:14},main:{flex:1,minWidth:0},h:{color:"#fff",fontWeight:"900",fontSize:15,marginBottom:10,marginTop:8},tool:{flexDirection:"row",gap:9,alignItems:"center",backgroundColor:"#10243a",padding:11,borderRadius:10,marginBottom:8},toolText:{color:"#dcecff",fontWeight:"800"},meta:{color:"#91abc2",fontSize:12,lineHeight:20},preview:{flex:1,minHeight:300,backgroundColor:"#0b1727",borderRadius:18,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#233b55"},previewTitle:{color:"#fff",fontSize:24,fontWeight:"900",marginTop:8},previewSub:{color:"#91abc2",marginTop:5},controls:{height:58,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},control:{width:40,height:40,borderRadius:10,backgroundColor:"#13283d",alignItems:"center",justifyContent:"center"},action:{backgroundColor:"#13283d",paddingHorizontal:14,paddingVertical:11,borderRadius:10},actionText:{color:"#fff",fontWeight:"800"},timeline:{height:245,backgroundColor:"#071426",borderRadius:16,padding:12,overflow:"hidden"},ruler:{height:30},rulerText:{color:"#6f8aa3",fontSize:11},clip:{height:34,borderRadius:7,marginBottom:8,justifyContent:"center",paddingHorizontal:9},clipOn:{borderWidth:2,borderColor:"#fff"},clipText:{color:"#fff",fontWeight:"900",fontSize:11},playhead:{position:"absolute",top:0,bottom:0,width:2},label:{color:"#718da7",fontSize:11,fontWeight:"900",marginTop:10,textTransform:"uppercase"},value:{color:"#fff",fontWeight:"800",marginTop:3},check:{flexDirection:"row",gap:7,alignItems:"center",marginBottom:8},checkText:{color:"#bed0df",fontSize:12}})
