import type { DatabaseAdapter } from "./database";

export type AICreditPackId = "small" | "standard" | "more";
export type AICreditPack = { id:AICreditPackId; name:string; priceCents:number; credits:number; stripePriceEnv:string };
export const AI_CREDIT_PACKS:Record<AICreditPackId,AICreditPack> = {
  small:{id:"small",name:"Small",priceCents:200,credits:200,stripePriceEnv:"STRIPE_PRICE_AI_CREDITS_SMALL"},
  standard:{id:"standard",name:"Standard",priceCents:500,credits:550,stripePriceEnv:"STRIPE_PRICE_AI_CREDITS_STANDARD"},
  more:{id:"more",name:"More",priceCents:1000,credits:1200,stripePriceEnv:"STRIPE_PRICE_AI_CREDITS_MORE"},
};
export const getCreditPack=(id:string)=>AI_CREDIT_PACKS[id as AICreditPackId];
export async function creditBalance(db:DatabaseAdapter,organizationId:string){const rows=await db.find("aiCreditTransactions",x=>x.organizationId===organizationId);return rows.reduce((sum,row)=>sum+row.credits,0)}
export async function grantPurchasedCredits(db:DatabaseAdapter,event:any){
  if(event?.type!=="checkout.session.completed") return undefined;const session=event?.data?.object??{};
  if(String(session.metadata?.purpose??"")!=="ai_credits" || String(session.payment_status??"")!=="paid") return undefined;
  const eventId=String(event.id??""); const checkoutSessionId=String(session.id??"");if(!eventId||!checkoutSessionId)return undefined;
  return db.transaction(async tx=>{await tx.lock?.(`stripe-event:${eventId}`);const duplicate=(await tx.find("aiCreditTransactions",x=>x.providerEventId===eventId||x.providerCheckoutSessionId===checkoutSessionId))[0];if(duplicate)return duplicate;
    const organizationId=String(session.metadata?.organizationId??session.client_reference_id??"");const pack=getCreditPack(String(session.metadata?.pack??""));if(!organizationId||!pack)return undefined;
    return tx.insert("aiCreditTransactions",{organizationId,credits:pack.credits,kind:"purchase",packId:pack.id,amountCents:Number(session.amount_total??pack.priceCents),currency:String(session.currency??"usd"),providerEventId:eventId,providerCheckoutSessionId:checkoutSessionId,metadata:{paymentIntentId:String(session.payment_intent??'')}});});
}
export async function applyStripeCreditReversal(db:DatabaseAdapter,event:any){
 const type=String(event?.type??'');if(!['charge.refunded','charge.dispute.created'].includes(type))return undefined;const obj=event?.data?.object??{};const eventId=String(event.id??'');const paymentIntentId=String(obj.payment_intent??'');if(!eventId||!paymentIntentId)return undefined;
 return db.transaction(async tx=>{await tx.lock?.(`stripe-event:${eventId}`);if((await tx.find('aiCreditTransactions',x=>x.providerEventId===eventId))[0])return undefined;const purchase=(await tx.find('aiCreditTransactions',x=>x.kind==='purchase'&&String(x.metadata?.paymentIntentId??'')===paymentIntentId))[0];if(!purchase)return undefined;
   const previous=(await tx.find('aiCreditTransactions',x=>x.kind==='refund'&&String(x.metadata?.purchaseTransactionId??'')===purchase.id)).reduce((n,x)=>n+Math.abs(x.credits),0);const ratio=type==='charge.dispute.created'?1:Math.min(1,Math.max(0,Number(obj.amount_refunded??obj.amount??0)/Math.max(1,Number(obj.amount??purchase.amountCents??1))));const target=Math.ceil(purchase.credits*ratio);const revoke=Math.max(0,Math.min(purchase.credits-previous,target-previous));if(!revoke)return undefined;return tx.insert('aiCreditTransactions',{organizationId:purchase.organizationId,credits:-revoke,kind:'refund',amountCents:Number(obj.amount_refunded??obj.amount??0),currency:String(obj.currency??purchase.currency??'usd'),providerEventId:eventId,metadata:{purchaseTransactionId:purchase.id,paymentIntentId,reason:type}});});
}
export async function spendCredits(db:DatabaseAdapter,organizationId:string,credits:number,metadata?:Record<string,unknown>){const amount=Math.max(0,Math.ceil(credits));if(!amount)return creditBalance(db,organizationId);return db.transaction(async tx=>{await tx.lock?.(`ai-credits:${organizationId}`);const balance=await creditBalance(tx,organizationId);if(balance<amount)throw new Error("AI_CREDITS_INSUFFICIENT");await tx.insert("aiCreditTransactions",{organizationId,credits:-amount,kind:"usage",metadata});return balance-amount;})}
export async function adjustCredits(db:DatabaseAdapter,organizationId:string,credits:number,metadata?:Record<string,unknown>){const amount=Math.trunc(credits);if(!amount)return creditBalance(db,organizationId);return db.transaction(async tx=>{await tx.lock?.(`ai-credits:${organizationId}`);const balance=await creditBalance(tx,organizationId);if(balance+amount<0)throw new Error("AI_CREDITS_INSUFFICIENT");await tx.insert("aiCreditTransactions",{organizationId,credits:amount,kind:"adjustment",metadata});return balance+amount;})}
export async function reserveCredits(db:DatabaseAdapter,organizationId:string,credits:number,reservationId:string,metadata?:Record<string,unknown>){return db.transaction(async tx=>{await tx.lock?.(`ai-credits:${organizationId}`);const existing=(await tx.find("aiCreditTransactions",x=>x.organizationId===organizationId&&String(x.metadata?.reservationId??"")===reservationId&&x.kind==="usage"))[0];if(existing)return creditBalance(tx,organizationId);const balance=await creditBalance(tx,organizationId);const amount=Math.max(0,Math.ceil(credits));if(balance<amount)throw new Error('AI_CREDITS_INSUFFICIENT');await tx.insert('aiCreditTransactions',{organizationId,credits:-amount,kind:'usage',metadata:{...metadata,reservationId,reservation:true}});return balance-amount;})}
export async function settleCreditReservation(db:DatabaseAdapter,organizationId:string,reservationId:string,actualCredits:number){return db.transaction(async tx=>{await tx.lock?.(`ai-credits:${organizationId}`);const rows=await tx.find("aiCreditTransactions",x=>x.organizationId===organizationId&&String(x.metadata?.reservationId??"")===reservationId);if(rows.some(x=>x.metadata?.settlement===true))return creditBalance(tx,organizationId);const reserved=Math.abs(rows.filter(x=>x.kind==="usage"&&x.metadata?.reservation===true).reduce((n,x)=>n+x.credits,0));if(!reserved)throw new Error("AI_CREDIT_RESERVATION_NOT_FOUND");const actual=Math.max(0,Math.ceil(actualCredits));const charged=Math.min(actual,reserved);const refund=reserved-charged;await tx.insert("aiCreditTransactions",{organizationId,credits:refund,kind:"adjustment",metadata:{reservationId,settlement:true,actualCredits:actual,chargedCredits:charged,overageCredits:Math.max(0,actual-reserved)}});return creditBalance(tx,organizationId);})}
