import { createHash, randomUUID } from 'node:crypto';
import type { DatabaseAdapter } from './database.ts';
import { PLAN_CATALOG, type PlanId } from './billingPlatform.ts';
export type AiTask='write'|'translate'|'ocr'|'image'|'background-remove'|'upscale'|'design-suggest';
export type ProviderConfig={name:string;endpoint:string;apiKey:string;models?:Partial<Record<AiTask,string>>};
export type AiGatewayRequest={organizationId:string;userId:string;plan:PlanId;task:AiTask;prompt?:string;inputUrl?:string;language?:string;maxTokens?:number};
export type AiGatewayResult={id:string;provider:string;model:string;output:unknown;usage:{credits:number;inputTokens:number;outputTokens:number};checksum:string};
const blocked=[/sexual content involving minors/i,/credit card number/i,/malware payload/i];
export function moderateAiInput(value:string){const hit=blocked.find(x=>x.test(value));return{allowed:!hit,reason:hit?'POLICY_BLOCKED':undefined}}
export function estimateCredits(task:AiTask,inputTokens:number,outputTokens=0){const base:{[K in AiTask]:number}={write:1,translate:1,ocr:2,image:20,'background-remove':5,upscale:8,'design-suggest':3};return base[task]+Math.ceil((inputTokens+outputTokens)/1000)}
export function loadAiProviders():ProviderConfig[]{const providers:ProviderConfig[]=[];for(const prefix of ['OPENAI','AI_FALLBACK']){const endpoint=process.env[`${prefix}_BASE_URL`]??(prefix==='OPENAI'?'https://api.openai.com/v1/chat/completions':'');const apiKey=process.env[`${prefix}_API_KEY`]??'';if(endpoint&&apiKey)providers.push({name:prefix.toLowerCase(),endpoint,apiKey})}return providers}
async function invoke(provider:ProviderConfig,request:AiGatewayRequest,signal?:AbortSignal){const model=provider.models?.[request.task]??process.env.AI_DEFAULT_MODEL??'gpt-4.1-mini';const response=await fetch(provider.endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${provider.apiKey}`,'x-request-id':randomUUID()},body:JSON.stringify({model,messages:[{role:'user',content:request.prompt??request.inputUrl??''}],max_tokens:request.maxTokens??1024}),signal});if(!response.ok)throw new Error(`AI_PROVIDER_${response.status}`);const data:any=await response.json();return{provider:provider.name,model:data.model??model,output:data.choices?.[0]?.message?.content??data.output??data,usage:data.usage??{}}}
export async function runAiGateway(db:DatabaseAdapter,request:AiGatewayRequest,providers=loadAiProviders()):Promise<AiGatewayResult>{const text=request.prompt??request.inputUrl??'';const moderation=moderateAiInput(text);if(!moderation.allowed)throw new Error(moderation.reason);const inputTokens=Math.max(1,Math.ceil(text.length/4));const monthlyLimit=PLAN_CATALOG[request.plan]?.aiCredits??PLAN_CATALOG.free.aiCredits;const month=new Date().toISOString().slice(0,7);const used=(await db.find('jobs',j=>j.kind==='ai'&&String((j.payload as any)?.organizationId)===request.organizationId&&String((j.payload as any)?.month)===month&&j.status==='succeeded')).reduce((n,j)=>n+Number((j.result as any)?.usage?.credits??0),0);if(used>=monthlyLimit)throw new Error('AI_QUOTA_EXCEEDED');const job=await db.insert('jobs',{kind:'ai',status:'running',progress:10,attempts:0,payload:{...request,month}});let last:unknown;for(let i=0;i<providers.length;i++){try{const raw=await invoke(providers[i],request);const outputText=typeof raw.output==='string'?raw.output:JSON.stringify(raw.output);const outputTokens=Number(raw.usage.completion_tokens??Math.ceil(outputText.length/4));const result:AiGatewayResult={id:job.id,provider:raw.provider,model:raw.model,output:raw.output,usage:{credits:estimateCredits(request.task,inputTokens,outputTokens),inputTokens,outputTokens},checksum:createHash('sha256').update(outputText).digest('hex')};await db.update('jobs',job.id,{status:'succeeded',progress:100,attempts:i+1,result});return result}catch(error){last=error;await db.update('jobs',job.id,{attempts:i+1,error:error instanceof Error?error.message:String(error)})}}await db.update('jobs',job.id,{status:'failed',progress:100,error:last instanceof Error?last.message:String(last)});throw last??new Error('AI_PROVIDER_UNAVAILABLE')}
