import type { DatabaseAdapter, OrganizationRecord, SubscriptionRecord } from './database.ts';

export type PlanId='free'|'creator'|'pro'|'business';
export type PlanDefinition={id:PlanId;name:string;monthlyCents:number;storageBytes:number;aiCredits:number;seats:number;features:string[];stripePriceEnv?:string};
export const PLAN_CATALOG:Record<PlanId,PlanDefinition>={
 free:{id:'free',name:'Free',monthlyCents:0,storageBytes:1_000_000_000,aiCredits:50,seats:1,features:['editor','standard-templates','local-export']},
 creator:{id:'creator',name:'Professional',monthlyCents:999,storageBytes:20_000_000_000,aiCredits:1_000,seats:1,features:['editor','premium-templates','cloud-sync','ai-basic','premium-export','priority-support'],stripePriceEnv:'STRIPE_PRICE_CREATOR'},
 pro:{id:'pro',name:'Professional Plus',monthlyCents:1999,storageBytes:100_000_000_000,aiCredits:5_000,seats:5,features:['editor','premium-templates','cloud-sync','ai-pro','brand-kit','custom-fonts','background-removal','upscale','advanced-export'],stripePriceEnv:'STRIPE_PRICE_PRO'},
 business:{id:'business',name:'Enterprise',monthlyCents:3999,storageBytes:1_000_000_000_000,aiCredits:25_000,seats:25,features:['editor','unlimited-templates','cloud-sync','ai-full','team-workspaces','collaboration','approvals','sso','advanced-security','audit-log','dedicated-support'],stripePriceEnv:'STRIPE_PRICE_BUSINESS'}
};
export type EntitlementSnapshot={plan:PlanId;status:string;features:string[];limits:{storageBytes:number;aiCredits:number;seats:number}};
export function resolveEntitlements(org:OrganizationRecord,sub?:SubscriptionRecord):EntitlementSnapshot{const requested=(sub?.plan??org.plan) as PlanId;const plan=PLAN_CATALOG[requested]??PLAN_CATALOG.free;const active=!sub||['active','trialing'].includes(sub.status);const effective=active?plan:PLAN_CATALOG.free;return{plan:effective.id,status:sub?.status??'active',features:[...effective.features],limits:{storageBytes:effective.storageBytes,aiCredits:effective.aiCredits,seats:effective.seats}}}
export function requireFeature(snapshot:EntitlementSnapshot,feature:string){if(!snapshot.features.includes(feature))throw new Error('FEATURE_NOT_INCLUDED')}
export async function syncStripeSubscription(db:DatabaseAdapter,event:any){const object=event?.data?.object??{};const customer=String(object.customer??'');const subscriptionId=String(object.id??'');const existing=(await db.find('subscriptions',s=>s.providerCustomerId===customer||s.providerSubscriptionId===subscriptionId))[0];if(!existing)return undefined;const priceId=object.items?.data?.[0]?.price?.id;const plan=(Object.values(PLAN_CATALOG).find(p=>p.stripePriceEnv&&process.env[p.stripePriceEnv]===priceId)?.id??existing.plan);return db.update('subscriptions',existing.id,{providerCustomerId:customer||existing.providerCustomerId,providerSubscriptionId:subscriptionId||existing.providerSubscriptionId,plan,status:String(object.status??existing.status),seats:Number(object.quantity??existing.seats??1)})}
