import type { DatabaseAdapter, SpaceStoreProductKind } from './database';
import { creditBalance } from './aiCredits';
import { PLAN_CATALOG, resolveEntitlements } from './billingPlatform';

export type MarketplaceKind = SpaceStoreProductKind;
const MARKETPLACE_KINDS: MarketplaceKind[]=['ai','studio','template','workflow','digital_product','service'];
export const GPU_CREDIT_PACKS={
 small:{id:'small',name:'GPU Starter',priceCents:500,credits:500,stripePriceEnv:'STRIPE_PRICE_GPU_CREDITS_SMALL'},
 standard:{id:'standard',name:'GPU Standard',priceCents:1500,credits:1650,stripePriceEnv:'STRIPE_PRICE_GPU_CREDITS_STANDARD'},
 power:{id:'power',name:'GPU Power',priceCents:4000,credits:4600,stripePriceEnv:'STRIPE_PRICE_GPU_CREDITS_POWER'},
} as const;
export type GPUCreditPackId=keyof typeof GPU_CREDIT_PACKS;

async function organizationForUser(db:DatabaseAdapter,userId:string){const membership=(await db.find('memberships',m=>m.userId===userId))[0];if(!membership)throw new Error('NO_ORGANIZATION');const organization=await db.get('organizations',membership.organizationId);if(!organization)throw new Error('NO_ORGANIZATION');return {membership,organization};}
export async function gpuCreditBalance(db:DatabaseAdapter,organizationId:string){return (await db.find('gpuCreditTransactions',x=>x.organizationId===organizationId)).reduce((n,x)=>n+x.credits,0)}
export async function spendGPUCredits(db:DatabaseAdapter,organizationId:string,credits:number,metadata?:Record<string,unknown>){const amount=Math.max(0,Math.ceil(credits));if(!amount)return gpuCreditBalance(db,organizationId);return db.transaction(async tx=>{await tx.lock?.(`gpu-credits:${organizationId}`);const balance=await gpuCreditBalance(tx,organizationId);if(balance<amount)throw new Error('GPU_CREDITS_INSUFFICIENT');await tx.insert('gpuCreditTransactions',{organizationId,credits:-amount,kind:'usage',metadata});return balance-amount;});}
export async function adjustGPUCredits(db:DatabaseAdapter,organizationId:string,credits:number,metadata?:Record<string,unknown>){const amount=Math.trunc(credits);if(!amount)return gpuCreditBalance(db,organizationId);return db.transaction(async tx=>{await tx.lock?.(`gpu-credits:${organizationId}`);const balance=await gpuCreditBalance(tx,organizationId);if(balance+amount<0)throw new Error('GPU_CREDITS_INSUFFICIENT');await tx.insert('gpuCreditTransactions',{organizationId,credits:amount,kind:'adjustment',metadata});return balance+amount;});}

export async function listMarketplace(db:DatabaseAdapter,userId:string,query='',kind?:string){const q=query.trim().toLowerCase();const kinds=MARKETPLACE_KINDS.includes(kind as MarketplaceKind)?new Set([kind as MarketplaceKind]):null;const products=(await db.find('spaceStoreProducts',p=>p.status==='active'&&p.visibility==='public'&&p.marketplaceListed===true&&(!kinds||kinds.has(p.kind))&&(!q||`${p.name} ${p.description??''} ${p.kind}`.toLowerCase().includes(q)))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));const spaces=new Map((await db.find('spaces',s=>products.some(p=>p.spaceId===s.id))).map(s=>[s.id,s]));const owned=new Set((await db.find('marketplaceEntitlements',e=>e.userId===userId&&e.status==='active')).map(e=>e.productId));return {items:products.map(p=>({id:p.id,spaceId:p.spaceId,creatorName:spaces.get(p.spaceId)?.name??'Creator',kind:p.kind,name:p.name,description:p.description,priceCents:p.priceCents,currency:p.currency,owned:owned.has(p.id)})),filters:{kinds:MARKETPLACE_KINDS}};}

export async function installMarketplaceProduct(db:DatabaseAdapter,userId:string,productId:string){return db.transaction(async tx=>{await tx.lock?.(`marketplace-entitlement:${userId}:${productId}`);const product=await tx.get('spaceStoreProducts',productId);if(!product||product.status!=='active'||product.visibility!=='public'||product.marketplaceListed!==true)throw new Error('MARKETPLACE_PRODUCT_NOT_AVAILABLE');if(product.ownerUserId===userId)throw new Error('MARKETPLACE_SELF_INSTALL_NOT_ALLOWED');if(product.priceCents>0)throw new Error('MARKETPLACE_PURCHASE_REQUIRED');const existing=(await tx.find('marketplaceEntitlements',e=>e.userId===userId&&e.productId===productId))[0];if(existing)return existing.status==='active'?existing:tx.update('marketplaceEntitlements',existing.id,{status:'active'});return tx.insert('marketplaceEntitlements',{userId,spaceId:product.spaceId,productId:product.id,kind:product.kind,source:'install',status:'active'});});}

export async function createMarketplaceOrder(db:DatabaseAdapter,userId:string,productId:string){return db.transaction(async tx=>{await tx.lock?.(`marketplace-order:${userId}:${productId}`);const product=await tx.get('spaceStoreProducts',productId);if(!product||product.status!=='active'||product.visibility!=='public'||product.marketplaceListed!==true)throw new Error('MARKETPLACE_PRODUCT_NOT_AVAILABLE');if(product.ownerUserId===userId)throw new Error('MARKETPLACE_SELF_PURCHASE_NOT_ALLOWED');if(product.priceCents<=0){const existingFree=(await tx.find('marketplaceEntitlements',e=>e.userId===userId&&e.productId===productId))[0];const entitlement=existingFree?(existingFree.status==='active'?existingFree:await tx.update('marketplaceEntitlements',existingFree.id,{status:'active'})):await tx.insert('marketplaceEntitlements',{userId,spaceId:product.spaceId,productId:product.id,kind:product.kind,source:'install',status:'active'});return {order:null,entitlement,free:true};}const entitlement=(await tx.find('marketplaceEntitlements',e=>e.userId===userId&&e.productId===productId&&e.status==='active'))[0];if(entitlement)return {order:entitlement.orderId?await tx.get('spaceStoreOrders',entitlement.orderId):null,entitlement,alreadyOwned:true};const prior=(await tx.find('spaceStoreOrders',o=>o.productId===productId&&o.buyerUserId===userId&&o.status==='pending'))[0];if(prior)return {order:prior};const platformFeeCents=Math.floor(product.priceCents*.10);const order=await tx.insert('spaceStoreOrders',{spaceId:product.spaceId,productId:product.id,buyerUserId:userId,sellerUserId:product.ownerUserId,quantity:1,grossCents:product.priceCents,platformFeeCents,creatorNetCents:product.priceCents-platformFeeCents,currency:product.currency,status:'pending'});await tx.insert('creatorEarnings',{orderId:order.id,spaceId:order.spaceId,productId:order.productId,sellerUserId:order.sellerUserId,grossCents:order.grossCents,platformFeeCents:order.platformFeeCents,creatorNetCents:order.creatorNetCents,currency:order.currency,status:'pending'});return {order};});}

export async function attachMarketplaceCheckout(db:DatabaseAdapter,orderId:string,sessionId:string){return db.update('spaceStoreOrders',orderId,{providerCheckoutSessionId:sessionId});}
export async function settleMarketplaceCheckout(db:DatabaseAdapter,event:any){if(event?.type!=='checkout.session.completed')return undefined;const session=event?.data?.object??{};if(String(session.metadata?.purpose??'')!=='marketplace')return undefined;if(String(session.payment_status??'')!=='paid')return undefined;const orderId=String(session.metadata?.orderId??'');if(!orderId)return undefined;return db.transaction(async tx=>{await tx.lock?.(`marketplace-order:${orderId}`);const order=await tx.get('spaceStoreOrders',orderId);if(!order)throw new Error('MARKETPLACE_ORDER_NOT_FOUND');if(order.status==='paid')return order;const paid=await tx.update('spaceStoreOrders',order.id,{status:'paid',providerCheckoutSessionId:String(session.id??order.providerCheckoutSessionId??''),providerPaymentIntentId:String(session.payment_intent??'')||undefined});const earning=(await tx.find('creatorEarnings',e=>e.orderId===order.id))[0];if(earning)await tx.update('creatorEarnings',earning.id,{status:'available'});const existing=(await tx.find('marketplaceEntitlements',e=>e.userId===order.buyerUserId&&e.productId===order.productId))[0];if(existing)await tx.update('marketplaceEntitlements',existing.id,{orderId:order.id,source:'purchase',status:'active'});else{const product=await tx.get('spaceStoreProducts',order.productId);if(!product)throw new Error('MARKETPLACE_PRODUCT_NOT_FOUND');await tx.insert('marketplaceEntitlements',{userId:order.buyerUserId,spaceId:order.spaceId,productId:order.productId,orderId:order.id,kind:product.kind,source:'purchase',status:'active'});}return paid;});}

export async function grantPurchasedGPUCredits(db:DatabaseAdapter,event:any){if(event?.type!=='checkout.session.completed')return undefined;const session=event?.data?.object??{};if(String(session.metadata?.purpose??'')!=='gpu_credits'||String(session.payment_status??'')!=='paid')return undefined;const eventId=String(event.id??''),sessionId=String(session.id??''),organizationId=String(session.metadata?.organizationId??session.client_reference_id??''),pack=GPU_CREDIT_PACKS[String(session.metadata?.pack??'') as GPUCreditPackId];if(!eventId||!sessionId||!organizationId||!pack)return undefined;return db.transaction(async tx=>{await tx.lock?.(`stripe-event:${eventId}`);const duplicate=(await tx.find('gpuCreditTransactions',x=>x.providerEventId===eventId||x.providerCheckoutSessionId===sessionId))[0];if(duplicate)return duplicate;return tx.insert('gpuCreditTransactions',{organizationId,credits:pack.credits,kind:'purchase',packId:pack.id,amountCents:Number(session.amount_total??pack.priceCents),currency:String(session.currency??'usd'),providerEventId:eventId,providerCheckoutSessionId:sessionId,metadata:{paymentIntentId:String(session.payment_intent??'')}});});}

export async function myMarketplaceLibrary(db:DatabaseAdapter,userId:string){const entitlements=(await db.find('marketplaceEntitlements',e=>e.userId===userId&&e.status==='active')).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));const items=[] as any[];for(const e of entitlements){const p=await db.get('spaceStoreProducts',e.productId);if(p)items.push({entitlement:e,product:{id:p.id,name:p.name,description:p.description,kind:p.kind,spaceId:p.spaceId}});}const orders=(await db.find('spaceStoreOrders',o=>o.buyerUserId===userId)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return {items,orders};}

export async function myUsageAndBilling(db:DatabaseAdapter,userId:string){const {organization}=await organizationForUser(db,userId);const sub=(await db.find('subscriptions',s=>s.organizationId===organization.id))[0];const entitlements=resolveEntitlements(organization,sub);const [aiBalance,gpuBalance,aiLedger,gpuLedger,library]=await Promise.all([creditBalance(db,organization.id),gpuCreditBalance(db,organization.id),db.find('aiCreditTransactions',x=>x.organizationId===organization.id),db.find('gpuCreditTransactions',x=>x.organizationId===organization.id),myMarketplaceLibrary(db,userId)]);const providerConnections=await db.find('spaceConnections',c=>c.ownerUserId===userId);return {subscription:{plan:entitlements.plan,planName:PLAN_CATALOG[entitlements.plan]?.name??'Free',status:entitlements.status,features:entitlements.features,limits:entitlements.limits},credits:{ai:{balance:aiBalance,ledger:aiLedger.slice(-100).reverse()},gpu:{balance:gpuBalance,ledger:gpuLedger.slice(-100).reverse()}},externalBilling:{message:'Bring-your-own OpenAI, Claude, Gemini, Hugging Face and custom API usage is billed by those providers, not by Yaposan.',connections:providerConnections.filter(c=>c.billing==='external').map(c=>({id:c.id,name:c.name,kind:c.kind,status:c.status}))},marketplace:{entitlements:library.items.length,orders:library.orders.length}};}

export async function creatorEarningsDashboard(db:DatabaseAdapter,userId:string){const earnings=(await db.find('creatorEarnings',e=>e.sellerUserId===userId)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const payouts=(await db.find('creatorPayouts',p=>p.sellerUserId===userId)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const sum=(status?:string)=>earnings.filter(e=>!status||e.status===status).reduce((n,e)=>n+e.creatorNetCents,0);return {earnings,payouts,summary:{grossCents:earnings.filter(e=>e.status!=='refunded').reduce((n,e)=>n+e.grossCents,0),creatorNetCents:earnings.filter(e=>e.status!=='refunded').reduce((n,e)=>n+e.creatorNetCents,0),availableCents:sum('available'),paidCents:sum('paid'),pendingCents:sum('pending')}};}
