import { createHmac, timingSafeEqual } from "node:crypto";
const stripeBase="https://api.stripe.com/v1";
const key=()=>{const value=process.env.STRIPE_SECRET_KEY;if(!value)throw new Error("STRIPE_NOT_CONFIGURED");return value};
async function stripe(path:string,params:Record<string,string|number|boolean|undefined>){const body=new URLSearchParams();for(const [k,v] of Object.entries(params))if(v!==undefined)body.set(k,String(v));const r=await fetch(`${stripeBase}${path}`,{method:"POST",headers:{authorization:`Bearer ${key()}`,"content-type":"application/x-www-form-urlencoded"},body});const data=await r.json() as any;if(!r.ok)throw new Error(data.error?.message??`STRIPE_${r.status}`);return data}
export const createCustomer=(email:string,name?:string,metadata?:Record<string,string>)=>stripe("/customers",{email,name,...Object.fromEntries(Object.entries(metadata??{}).map(([k,v])=>[`metadata[${k}]`,v]))});
export const createCheckoutSession=(args:{customerId:string;priceId:string;successUrl:string;cancelUrl:string;quantity?:number;organizationId:string;plan:string})=>stripe("/checkout/sessions",{customer:args.customerId,"line_items[0][price]":args.priceId,"line_items[0][quantity]":args.quantity??1,mode:"subscription",success_url:args.successUrl,cancel_url:args.cancelUrl,"allow_promotion_codes":true,"client_reference_id":args.organizationId,"metadata[organizationId]":args.organizationId,"metadata[plan]":args.plan,"subscription_data[metadata][organizationId]":args.organizationId,"subscription_data[metadata][plan]":args.plan});
export const createBillingPortal=(customerId:string,returnUrl:string)=>stripe("/billing_portal/sessions",{customer:customerId,return_url:returnUrl});
export const cancelSubscription=(subscriptionId:string)=>stripe(`/subscriptions/${encodeURIComponent(subscriptionId)}`,{cancel_at_period_end:true});
export function verifyStripeWebhook(payload:string,signatureHeader:string,secret=process.env.STRIPE_WEBHOOK_SECRET,toleranceSeconds=300,nowSeconds=Math.floor(Date.now()/1000)){if(!secret)throw new Error("STRIPE_WEBHOOK_SECRET_MISSING");const entries=signatureHeader.split(",").map(x=>x.trim().split("="));const timestamp=entries.find(([k])=>k==="t")?.[1];const signatures=entries.filter(([k])=>k==="v1").map(([,v])=>v).filter(Boolean);if(!timestamp||signatures.length===0)return false;const parsed=Number(timestamp);if(!Number.isFinite(parsed)||Math.abs(nowSeconds-parsed)>toleranceSeconds)return false;const expected=createHmac("sha256",secret).update(`${timestamp}.${payload}`).digest("hex");return signatures.some(value=>{const a=Buffer.from(expected);const b=Buffer.from(value);return a.length===b.length&&timingSafeEqual(a,b)})}

export const createAICreditCheckoutSession=(args:{customerId?:string;priceId:string;successUrl:string;cancelUrl:string;organizationId:string;pack:string})=>stripe("/checkout/sessions",{customer:args.customerId,"line_items[0][price]":args.priceId,"line_items[0][quantity]":1,mode:"payment",success_url:args.successUrl,cancel_url:args.cancelUrl,"client_reference_id":args.organizationId,"metadata[organizationId]":args.organizationId,"metadata[purpose]":"ai_credits","metadata[pack]":args.pack,"payment_intent_data[metadata][organizationId]":args.organizationId,"payment_intent_data[metadata][purpose]":"ai_credits","payment_intent_data[metadata][pack]":args.pack});
