import type { DatabaseAdapter, DatabaseSchema, EntityName, RecordBase } from "./database";

export type SqlConnection = {
  query<T = Record<string, unknown>>(text: string, values?: unknown[]): Promise<{ rows: T[] }>;
  release?(): void;
};
export type SqlClient = SqlConnection & {
  connect?(): Promise<SqlConnection>;
  end?(): Promise<void>;
};

const TABLES: Record<EntityName, string> = {
  users: "users", organizations: "organizations", memberships: "memberships", workspaces: "workspaces",
  spaces: "spaces", spaceMemberships: "space_memberships", spacePosts: "space_posts", spaceComments: "space_comments", spaceFollows: "space_follows", spaceAIAgents: "space_ai_agents", spaceConnections: "space_connections", spaceComputeProfiles: "space_compute_profiles", spaceStudios: "space_studios", spaceStudioRuns: "space_studio_runs", spaceInvites: "space_invites", spaceStoreProducts: "space_store_products", spaceStoreOrders: "space_store_orders", marketplaceEntitlements: "marketplace_entitlements", gpuCreditTransactions: "gpu_credit_transactions", creatorEarnings: "creator_earnings", creatorPayouts: "creator_payouts",
  projects: "projects", assets: "assets", versions: "project_versions", subscriptions: "subscriptions",
  auditEvents: "audit_events", jobs: "jobs", aiCreditTransactions: "ai_credit_transactions", aiCommunityTransactions: "ai_community_transactions", aiProviderCredentials: "ai_provider_credentials", supportTickets: "support_tickets", supportTicketMessages: "support_ticket_messages", helpFeedback: "help_feedback", adminPrincipals: "admin_principals", adminSessions: "admin_sessions", adminAuditEvents: "admin_audit_events", adminModerationActions: "admin_moderation_actions", platformCostEntries: "platform_cost_entries", spacePrivacySettings: "space_privacy_settings", spaceDataGrants: "space_data_grants", userSessions: "user_sessions", spaceSecuritySettings: "space_security_settings", spacePostReactions: "space_post_reactions", spaceCommentReactions: "space_comment_reactions", spacePostBookmarks: "space_post_bookmarks", spacePostReposts: "space_post_reposts", spacePostHashtags: "space_post_hashtags", socialNotifications: "social_notifications", socialConversations: "social_conversations", socialConversationMembers: "social_conversation_members", socialMessages: "social_messages", socialBlocks: "social_blocks", socialReports: "social_reports", socialMediaAssets: "social_media_assets", socialPostMedia: "social_post_media", socialStories: "social_stories", socialStoryViews: "social_story_views", socialHighlights: "social_highlights", socialReels: "social_reels", socialCommunities: "social_communities", socialCommunityMembers: "social_community_members", socialCommunityPosts: "social_community_posts", socialCommunityModeration: "social_community_moderation", socialPages: "social_pages", socialEvents: "social_events", socialEventRsvps: "social_event_rsvps", socialLiveSessions: "social_live_sessions", socialLiveChatMessages: "social_live_chat_messages", socialLiveReactions: "social_live_reactions", socialAiProfiles: "social_ai_profiles", socialAiGenerations: "social_ai_generations", socialAiModerationSuggestions: "social_ai_moderation_suggestions", creatorMembershipPlans:"creator_membership_plans", creatorMembershipSubscriptions:"creator_membership_subscriptions", creatorTips:"creator_tips", paidContentAccess:"paid_content_access", creatorRevenueEvents:"creator_revenue_events", creatorAdSettings:"creator_ad_settings", creatorAdCampaigns:"creator_ad_campaigns", creatorAdEvents:"creator_ad_events", paymentWebhookEvents:"payment_webhook_events", paymentSecurityEvents:"payment_security_events", paymentReconciliations:"payment_reconciliations", moderationAppeals:"moderation_appeals", userSafetyProfiles:"user_safety_profiles", authTokens:"auth_tokens",
};

const snake = (key: string) => key.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`);
const camel = (key: string) => key.replace(/_([a-z])/g, (_, letter: string) => letter.toUpperCase());
const decode = <T>(row: Record<string, unknown>): T => Object.fromEntries(Object.entries(row).map(([k, v]) => [camel(k), v])) as T;

export const POSTGRES_MIGRATIONS = [
`CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE NOT NULL, password_hash text NOT NULL, email_verified boolean NOT NULL DEFAULT false, mfa_secret text, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, owner_user_id uuid NOT NULL REFERENCES users(id), plan text NOT NULL DEFAULT 'free', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,user_id));
CREATE TABLE IF NOT EXISTS workspaces (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, name text NOT NULL, region text NOT NULL DEFAULT 'us-east', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());`,
`CREATE TABLE IF NOT EXISTS projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id), name text NOT NULL, revision integer NOT NULL DEFAULT 1, payload jsonb NOT NULL DEFAULT '{}'::jsonb, deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS project_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, revision integer NOT NULL, payload jsonb NOT NULL, actor_user_id uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,revision));
CREATE TABLE IF NOT EXISTS assets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id), name text NOT NULL, mime_type text NOT NULL, size bigint NOT NULL, storage_key text UNIQUE NOT NULL, checksum text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());`,
`CREATE TABLE IF NOT EXISTS subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, provider_customer_id text, provider_subscription_id text, plan text NOT NULL, status text NOT NULL, seats integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid, actor_user_id uuid, action text NOT NULL, target text, request_id text, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kind text NOT NULL, status text NOT NULL, progress integer NOT NULL DEFAULT 0, attempts integer NOT NULL DEFAULT 0, payload jsonb NOT NULL DEFAULT '{}'::jsonb, result jsonb, error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_projects_workspace_updated ON projects(workspace_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_versions_project_revision ON project_versions(project_id,revision DESC);
CREATE INDEX IF NOT EXISTS idx_assets_workspace ON assets(workspace_id);
CREATE INDEX IF NOT EXISTS idx_audit_org_created ON audit_events(organization_id,created_at DESC);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS worker_id text;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS lease_expires_at timestamptz;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS heartbeat_at timestamptz;
CREATE INDEX IF NOT EXISTS idx_jobs_claim ON jobs(kind,status,created_at);`,
`CREATE TABLE IF NOT EXISTS ai_credit_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, credits integer NOT NULL, kind text NOT NULL, pack_id text, amount_cents integer, currency text, provider_event_id text UNIQUE, provider_checkout_session_id text UNIQUE, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_ai_credit_org_created ON ai_credit_transactions(organization_id,created_at DESC);`,
`CREATE TABLE IF NOT EXISTS ai_community_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES organizations(id) ON DELETE SET NULL, month text NOT NULL, request_id text NOT NULL, amount_micros bigint NOT NULL, kind text NOT NULL, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_ai_community_month ON ai_community_transactions(month,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_community_request ON ai_community_transactions(request_id);
CREATE TABLE IF NOT EXISTS ai_provider_credentials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, provider text NOT NULL, endpoint text, model text, encrypted_api_key text NOT NULL, key_last4 text, key_version text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,provider));
CREATE INDEX IF NOT EXISTS idx_ai_provider_credentials_org ON ai_provider_credentials(organization_id);
ALTER TABLE ai_provider_credentials ADD COLUMN IF NOT EXISTS key_version text;`,
`CREATE TABLE IF NOT EXISTS support_tickets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE SET NULL, email text NOT NULL, name text NOT NULL, category text NOT NULL, priority text NOT NULL DEFAULT 'normal', subject text NOT NULL, message text NOT NULL, status text NOT NULL DEFAULT 'open', source text, page text, action text, diagnostics jsonb, attachment_name text, attachment_mime_type text, attachment_size bigint, attachment_storage_key text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_support_tickets_created ON support_tickets(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets(status,created_at DESC);
CREATE TABLE IF NOT EXISTS support_ticket_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE, author_user_id uuid REFERENCES users(id) ON DELETE SET NULL, author_type text NOT NULL, body text NOT NULL, attachment_name text, attachment_mime_type text, attachment_size bigint, attachment_storage_key text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_support_ticket_messages_ticket ON support_ticket_messages(ticket_id,created_at);
CREATE TABLE IF NOT EXISTS help_feedback (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE SET NULL, content_type text NOT NULL, content_id text NOT NULL, helpful boolean NOT NULL, page text, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_help_feedback_content ON help_feedback(content_type,content_id,created_at DESC);`,
`CREATE TABLE IF NOT EXISTS spaces (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id), name text NOT NULL, slug text NOT NULL UNIQUE, kind text NOT NULL DEFAULT 'personal', visibility text NOT NULL DEFAULT 'private', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS space_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(space_id,user_id));
CREATE INDEX IF NOT EXISTS idx_spaces_owner ON spaces(owner_user_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_space_memberships_user ON space_memberships(user_id,space_id);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS space_id uuid REFERENCES spaces(id) ON DELETE SET NULL;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS space_id uuid REFERENCES spaces(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_projects_space_updated ON projects(space_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_assets_space ON assets(space_id);`,

`CREATE TABLE IF NOT EXISTS space_ai_agents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id), name text NOT NULL, provider text NOT NULL, model text, instructions text, visibility text NOT NULL DEFAULT 'private', enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS space_connections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id), name text NOT NULL, kind text NOT NULL, endpoint text, credential_ref text, billing text NOT NULL DEFAULT 'external', status text NOT NULL DEFAULT 'connected', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS space_compute_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id), name text NOT NULL, kind text NOT NULL, endpoint text, provider text, billing text NOT NULL DEFAULT 'none', status text NOT NULL DEFAULT 'online', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_space_ai_agents_space ON space_ai_agents(space_id);
CREATE INDEX IF NOT EXISTS idx_space_connections_space ON space_connections(space_id);
CREATE INDEX IF NOT EXISTS idx_space_compute_profiles_space ON space_compute_profiles(space_id);`,

`CREATE TABLE IF NOT EXISTS space_studios (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id), name text NOT NULL, description text, visibility text NOT NULL DEFAULT 'private', status text NOT NULL DEFAULT 'draft', nodes jsonb NOT NULL DEFAULT '[]'::jsonb, edges jsonb NOT NULL DEFAULT '[]'::jsonb, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS space_studio_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, studio_id uuid NOT NULL REFERENCES space_studios(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id), status text NOT NULL DEFAULT 'running', input jsonb, output jsonb, steps jsonb NOT NULL DEFAULT '[]'::jsonb, error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_space_studios_space ON space_studios(space_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_space_studio_runs_studio ON space_studio_runs(studio_id,created_at DESC);`,

`CREATE TABLE IF NOT EXISTS space_invites (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, email text NOT NULL, role text NOT NULL, invited_by_user_id uuid NOT NULL REFERENCES users(id), status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS idx_space_invites_pending ON space_invites(space_id,lower(email)) WHERE status='pending';
CREATE TABLE IF NOT EXISTS space_store_products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id), kind text NOT NULL, name text NOT NULL, description text, price_cents integer NOT NULL DEFAULT 0, currency text NOT NULL DEFAULT 'USD', visibility text NOT NULL DEFAULT 'private', status text NOT NULL DEFAULT 'draft', resource_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_space_store_products_space ON space_store_products(space_id,updated_at DESC);
CREATE TABLE IF NOT EXISTS space_store_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, product_id uuid NOT NULL REFERENCES space_store_products(id), buyer_user_id uuid NOT NULL REFERENCES users(id), seller_user_id uuid NOT NULL REFERENCES users(id), quantity integer NOT NULL DEFAULT 1, gross_cents integer NOT NULL DEFAULT 0, platform_fee_cents integer NOT NULL DEFAULT 0, creator_net_cents integer NOT NULL DEFAULT 0, currency text NOT NULL DEFAULT 'USD', status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_space_store_orders_space ON space_store_orders(space_id,created_at DESC);`,

`ALTER TABLE space_store_orders ADD COLUMN IF NOT EXISTS provider_checkout_session_id text;
ALTER TABLE space_store_orders ADD COLUMN IF NOT EXISTS provider_payment_intent_id text;
CREATE UNIQUE INDEX IF NOT EXISTS idx_space_store_order_checkout ON space_store_orders(provider_checkout_session_id) WHERE provider_checkout_session_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS marketplace_entitlements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, product_id uuid NOT NULL REFERENCES space_store_products(id) ON DELETE CASCADE, order_id uuid REFERENCES space_store_orders(id) ON DELETE SET NULL, kind text NOT NULL, source text NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,product_id));
CREATE INDEX IF NOT EXISTS idx_marketplace_entitlements_user ON marketplace_entitlements(user_id,updated_at DESC);
CREATE TABLE IF NOT EXISTS gpu_credit_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, credits integer NOT NULL, kind text NOT NULL, pack_id text, amount_cents integer, currency text, provider_event_id text UNIQUE, provider_checkout_session_id text UNIQUE, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_gpu_credit_org_created ON gpu_credit_transactions(organization_id,created_at DESC);
CREATE TABLE IF NOT EXISTS creator_earnings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL UNIQUE REFERENCES space_store_orders(id) ON DELETE CASCADE, space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, product_id uuid NOT NULL REFERENCES space_store_products(id), seller_user_id uuid NOT NULL REFERENCES users(id), gross_cents integer NOT NULL, platform_fee_cents integer NOT NULL, creator_net_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_creator_earnings_seller ON creator_earnings(seller_user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS creator_payouts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), seller_user_id uuid NOT NULL REFERENCES users(id), amount_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', status text NOT NULL DEFAULT 'pending', provider text, provider_payout_id text, note text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_creator_payouts_seller ON creator_payouts(seller_user_id,created_at DESC);`,

`CREATE TABLE IF NOT EXISTS admin_principals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE NOT NULL, password_hash text NOT NULL, role text NOT NULL, status text NOT NULL DEFAULT 'active', last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS admin_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), principal_id uuid NOT NULL REFERENCES admin_principals(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL, revoked_at timestamptz, ip_hash text, user_agent_hash text, external_session_key text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_admin_sessions_principal ON admin_sessions(principal_id,expires_at DESC);
CREATE TABLE IF NOT EXISTS admin_audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), principal_id uuid REFERENCES admin_principals(id) ON DELETE SET NULL, action text NOT NULL, target text, request_id text, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_admin_audit_created ON admin_audit_events(created_at DESC);
CREATE TABLE IF NOT EXISTS admin_moderation_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), principal_id uuid NOT NULL REFERENCES admin_principals(id), resource_type text NOT NULL, resource_id text NOT NULL, action text NOT NULL, reason text, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_admin_moderation_resource ON admin_moderation_actions(resource_type,resource_id,created_at DESC);
CREATE TABLE IF NOT EXISTS platform_cost_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), principal_id uuid NOT NULL REFERENCES admin_principals(id), category text NOT NULL, amount_cents integer NOT NULL CHECK(amount_cents >= 0), currency text NOT NULL DEFAULT 'USD', period text, note text, source text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_platform_cost_created ON platform_cost_entries(created_at DESC);`,

`CREATE TABLE IF NOT EXISTS space_posts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, author_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, body text NOT NULL, visibility text NOT NULL DEFAULT 'public', media_url text, media_type text, quote_post_id uuid REFERENCES space_posts(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS space_comments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, author_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE space_comments ADD COLUMN IF NOT EXISTS parent_comment_id uuid REFERENCES space_comments(id) ON DELETE CASCADE;
CREATE TABLE IF NOT EXISTS space_follows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, follower_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(space_id,follower_user_id));
CREATE INDEX IF NOT EXISTS idx_space_posts_space_created ON space_posts(space_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_space_comments_post_created ON space_comments(post_id,created_at);
CREATE INDEX IF NOT EXISTS idx_space_follows_space ON space_follows(space_id);`,

`CREATE TABLE IF NOT EXISTS space_privacy_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL UNIQUE REFERENCES spaces(id) ON DELETE CASCADE, public_page_enabled boolean NOT NULL DEFAULT false, discoverable boolean NOT NULL DEFAULT false, show_follower_count boolean NOT NULL DEFAULT false, profile_audience text NOT NULL DEFAULT 'private', dm_audience text NOT NULL DEFAULT 'followers', default_post_visibility text NOT NULL DEFAULT 'private', external_sharing_enabled boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS profile_audience text NOT NULL DEFAULT 'private';
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS dm_audience text NOT NULL DEFAULT 'followers';
INSERT INTO space_privacy_settings (space_id,public_page_enabled,discoverable,show_follower_count,default_post_visibility,external_sharing_enabled) SELECT id,(visibility='public'),false,false,'private',false FROM spaces ON CONFLICT (space_id) DO NOTHING;
UPDATE spaces SET visibility='private', updated_at=now() WHERE visibility='public';
ALTER TABLE space_posts ALTER COLUMN visibility SET DEFAULT 'private';
CREATE TABLE IF NOT EXISTS space_data_grants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, connection_id uuid NOT NULL REFERENCES space_connections(id) ON DELETE CASCADE, granted_by_user_id uuid NOT NULL REFERENCES users(id), scopes text[] NOT NULL DEFAULT ARRAY[]::text[], resource_ids text[] NOT NULL DEFAULT ARRAY[]::text[], purpose text, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(space_id,connection_id));
CREATE INDEX IF NOT EXISTS idx_space_data_grants_space ON space_data_grants(space_id,status);
ALTER TABLE space_store_products ADD COLUMN IF NOT EXISTS marketplace_listed boolean NOT NULL DEFAULT false;`,
`ALTER TABLE space_studio_runs ADD COLUMN IF NOT EXISTS trace_id text;
ALTER TABLE space_studio_runs ADD COLUMN IF NOT EXISTS execution_key text;
ALTER TABLE space_studio_runs ADD COLUMN IF NOT EXISTS studio_version integer;
ALTER TABLE space_studio_runs ADD COLUMN IF NOT EXISTS node_states jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE space_studio_runs ADD COLUMN IF NOT EXISTS approved_node_ids text[] NOT NULL DEFAULT ARRAY[]::text[];
ALTER TABLE space_studio_runs ADD COLUMN IF NOT EXISTS started_at timestamptz;
ALTER TABLE space_studio_runs ADD COLUMN IF NOT EXISTS finished_at timestamptz;
ALTER TABLE space_studio_runs ADD COLUMN IF NOT EXISTS duration_ms integer;
ALTER TABLE space_studio_runs ADD COLUMN IF NOT EXISTS parent_run_id uuid REFERENCES space_studio_runs(id) ON DELETE SET NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_space_studio_runs_execution_key ON space_studio_runs(space_id,studio_id,user_id,execution_key) WHERE execution_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_space_studio_runs_trace ON space_studio_runs(trace_id);`,
`ALTER TABLE assets ADD COLUMN IF NOT EXISTS security_status text NOT NULL DEFAULT 'clean';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS security_reason text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS identity_provider text NOT NULL DEFAULT 'local';
ALTER TABLE users ADD COLUMN IF NOT EXISTS external_subject text;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_external_identity ON users(identity_provider,external_subject) WHERE external_subject IS NOT NULL;
CREATE TABLE IF NOT EXISTS user_sessions (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, version integer NOT NULL DEFAULT 1, auth_method text NOT NULL, assurance text NOT NULL DEFAULT 'password', expires_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz, ip_hash text, user_agent_hash text, external_session_key text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_user_sessions_user ON user_sessions(user_id,last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_sessions_active ON user_sessions(user_id,expires_at) WHERE revoked_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_sessions_external ON user_sessions(external_session_key) WHERE external_session_key IS NOT NULL;
CREATE TABLE IF NOT EXISTS space_security_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL UNIQUE REFERENCES spaces(id) ON DELETE CASCADE, require_step_up_for_public_sharing boolean NOT NULL DEFAULT true, require_step_up_for_team_admin boolean NOT NULL DEFAULT false, allow_public_comments boolean NOT NULL DEFAULT false, allow_external_connections boolean NOT NULL DEFAULT false, allow_file_downloads boolean NOT NULL DEFAULT false, invite_policy text NOT NULL DEFAULT 'admins_only', upload_policy text NOT NULL DEFAULT 'strict', security_alerts boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO space_security_settings (space_id) SELECT id FROM spaces ON CONFLICT (space_id) DO NOTHING;`,
`-- Yaposan 108.0 — AI social media essentials, independently implemented from common OSS patterns.
CREATE TABLE IF NOT EXISTS space_post_reactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,user_id));
CREATE TABLE IF NOT EXISTS space_comment_reactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, comment_id uuid NOT NULL REFERENCES space_comments(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(comment_id,user_id));
CREATE INDEX IF NOT EXISTS idx_space_comment_reactions_comment ON space_comment_reactions(comment_id);
CREATE TABLE IF NOT EXISTS space_post_bookmarks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,user_id));
CREATE TABLE IF NOT EXISTS space_post_reposts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,user_id));
CREATE TABLE IF NOT EXISTS space_post_hashtags (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, tag text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,tag));
CREATE INDEX IF NOT EXISTS idx_space_post_hashtags_tag ON space_post_hashtags(space_id,tag,created_at DESC);
CREATE TABLE IF NOT EXISTS social_notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, actor_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL, resource_type text NOT NULL, resource_id text NOT NULL, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_notifications_user ON social_notifications(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS social_conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, created_by_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, title text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS social_conversation_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id uuid NOT NULL REFERENCES social_conversations(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, last_read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(conversation_id,user_id));
CREATE TABLE IF NOT EXISTS social_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, conversation_id uuid NOT NULL REFERENCES social_conversations(id) ON DELETE CASCADE, sender_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_messages_conversation ON social_messages(conversation_id,created_at);
CREATE TABLE IF NOT EXISTS social_blocks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, target_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(space_id,user_id,target_user_id));
CREATE TABLE IF NOT EXISTS social_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, reporter_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, resource_type text NOT NULL, resource_id text NOT NULL, reason text NOT NULL, status text NOT NULL DEFAULT 'open', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_reports_status ON social_reports(space_id,status,created_at DESC);
`,
`-- Yaposan 110.0 — Reels, Stories and Media Platform.
CREATE TABLE IF NOT EXISTS social_media_assets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL, storage_key text NOT NULL UNIQUE, url text, mime_type text NOT NULL, size bigint NOT NULL, caption text, alt_text text, thumbnail_url text, width integer, height integer, duration_ms integer, processing_status text NOT NULL DEFAULT 'uploaded', moderation_status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_media_space ON social_media_assets(space_id,created_at DESC);
CREATE TABLE IF NOT EXISTS social_post_media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, media_asset_id uuid NOT NULL REFERENCES social_media_assets(id) ON DELETE CASCADE, position integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,media_asset_id));
CREATE INDEX IF NOT EXISTS idx_social_post_media_post ON social_post_media(post_id,position);
CREATE TABLE IF NOT EXISTS social_highlights (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, cover_media_asset_id uuid REFERENCES social_media_assets(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS social_stories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, author_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, media_asset_id uuid REFERENCES social_media_assets(id) ON DELETE SET NULL, body text, visibility text NOT NULL DEFAULT 'followers', expires_at timestamptz NOT NULL, highlight_id uuid REFERENCES social_highlights(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_stories_active ON social_stories(expires_at DESC,created_at DESC);
CREATE TABLE IF NOT EXISTS social_story_views (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), story_id uuid NOT NULL REFERENCES social_stories(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, viewed_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(story_id,user_id));
CREATE TABLE IF NOT EXISTS social_reels (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL UNIQUE REFERENCES space_posts(id) ON DELETE CASCADE, author_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, media_asset_id uuid NOT NULL REFERENCES social_media_assets(id) ON DELETE CASCADE, caption text, audio_title text, duration_ms integer, status text NOT NULL DEFAULT 'published', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_reels_created ON social_reels(status,created_at DESC);`,
`-- Yaposan 111.0 — Communities, Pages, Events and Live.
CREATE TABLE IF NOT EXISTS social_communities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, slug text NOT NULL UNIQUE, description text, visibility text NOT NULL DEFAULT 'public', join_policy text NOT NULL DEFAULT 'open', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_communities_discovery ON social_communities(status,visibility,created_at DESC);
CREATE TABLE IF NOT EXISTS social_community_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), community_id uuid NOT NULL REFERENCES social_communities(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL DEFAULT 'member', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(community_id,user_id));
CREATE INDEX IF NOT EXISTS idx_social_community_members ON social_community_members(community_id,status,role);
CREATE TABLE IF NOT EXISTS social_community_posts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), community_id uuid NOT NULL REFERENCES social_communities(id) ON DELETE CASCADE, post_id uuid NOT NULL UNIQUE REFERENCES space_posts(id) ON DELETE CASCADE, author_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'published', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS social_community_moderation (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), community_id uuid NOT NULL REFERENCES social_communities(id) ON DELETE CASCADE, actor_user_id uuid NOT NULL REFERENCES users(id), target_type text NOT NULL, target_id text NOT NULL, action text NOT NULL, reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS social_pages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL, name text NOT NULL, slug text NOT NULL UNIQUE, bio text, category text, website text, verified boolean NOT NULL DEFAULT false, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_pages_discovery ON social_pages(status,kind,created_at DESC);
CREATE TABLE IF NOT EXISTS social_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id), community_id uuid REFERENCES social_communities(id) ON DELETE SET NULL, page_id uuid REFERENCES social_pages(id) ON DELETE SET NULL, title text NOT NULL, description text, location_type text NOT NULL DEFAULT 'online', location text, starts_at timestamptz NOT NULL, ends_at timestamptz, visibility text NOT NULL DEFAULT 'public', status text NOT NULL DEFAULT 'scheduled', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_events_upcoming ON social_events(status,starts_at);
CREATE TABLE IF NOT EXISTS social_event_rsvps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), event_id uuid NOT NULL REFERENCES social_events(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, response text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(event_id,user_id));
CREATE TABLE IF NOT EXISTS social_live_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, host_user_id uuid NOT NULL REFERENCES users(id), community_id uuid REFERENCES social_communities(id) ON DELETE SET NULL, page_id uuid REFERENCES social_pages(id) ON DELETE SET NULL, event_id uuid REFERENCES social_events(id) ON DELETE SET NULL, title text NOT NULL, description text, stream_key_hash text, playback_url text, status text NOT NULL DEFAULT 'scheduled', started_at timestamptz, ended_at timestamptz, viewer_count integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_live_status ON social_live_sessions(status,created_at DESC);
CREATE TABLE IF NOT EXISTS social_live_chat_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), live_session_id uuid NOT NULL REFERENCES social_live_sessions(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id), body text NOT NULL, status text NOT NULL DEFAULT 'visible', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_live_chat ON social_live_chat_messages(live_session_id,created_at);
CREATE TABLE IF NOT EXISTS social_live_reactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), live_session_id uuid NOT NULL REFERENCES social_live_sessions(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id), kind text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_live_reactions ON social_live_reactions(live_session_id,created_at DESC);`,
`-- Yaposan 112.0 — AI-native social identities, assistance, discovery and moderation suggestions.
ALTER TABLE space_posts ADD COLUMN IF NOT EXISTS ai_generated boolean NOT NULL DEFAULT false;
ALTER TABLE space_posts ADD COLUMN IF NOT EXISTS ai_agent_id uuid REFERENCES space_ai_agents(id) ON DELETE SET NULL;
ALTER TABLE space_posts ADD COLUMN IF NOT EXISTS ai_disclosure text;
CREATE TABLE IF NOT EXISTS social_ai_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, agent_id uuid NOT NULL UNIQUE REFERENCES space_ai_agents(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, display_name text NOT NULL, handle text NOT NULL UNIQUE, bio text, identity_type text NOT NULL DEFAULT 'ai', disclosure text NOT NULL DEFAULT 'AI agent', autonomous_posting boolean NOT NULL DEFAULT false, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_ai_profiles_discovery ON social_ai_profiles(status,handle);
CREATE TABLE IF NOT EXISTS social_ai_generations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, agent_id uuid REFERENCES space_ai_agents(id) ON DELETE SET NULL, kind text NOT NULL, prompt text NOT NULL, source_text text, output text NOT NULL, provider text, model text, ai_generated boolean NOT NULL DEFAULT true, status text NOT NULL DEFAULT 'completed', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_ai_generations_user ON social_ai_generations(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS social_ai_moderation_suggestions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, reviewer_user_id uuid NOT NULL REFERENCES users(id), resource_type text NOT NULL, resource_id text NOT NULL, risk text NOT NULL, indicators text[] NOT NULL DEFAULT ARRAY[]::text[], status text NOT NULL DEFAULT 'suggested', human_decision text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_ai_moderation_review ON social_ai_moderation_suggestions(space_id,status,created_at DESC);
`,
`-- Yaposan 113.0 — creator memberships, tips, paid posts, revenue accounting and analytics.
ALTER TABLE social_communities ADD COLUMN IF NOT EXISTS membership_plan_id uuid;
ALTER TABLE space_posts ADD COLUMN IF NOT EXISTS access_model text NOT NULL DEFAULT 'free';
ALTER TABLE space_posts ADD COLUMN IF NOT EXISTS price_cents integer;
CREATE TABLE IF NOT EXISTS creator_membership_plans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, description text, monthly_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', benefits text[] NOT NULL DEFAULT ARRAY[]::text[], status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_creator_membership_plans ON creator_membership_plans(space_id,status);
CREATE TABLE IF NOT EXISTS creator_membership_subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_id uuid NOT NULL REFERENCES creator_membership_plans(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id), subscriber_user_id uuid NOT NULL REFERENCES users(id), status text NOT NULL DEFAULT 'pending', current_period_end timestamptz, provider_customer_id text, provider_subscription_id text, provider_checkout_session_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(plan_id,subscriber_user_id));
CREATE TABLE IF NOT EXISTS creator_tips (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id), sender_user_id uuid NOT NULL REFERENCES users(id), amount_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', message text, status text NOT NULL DEFAULT 'pending', provider_checkout_session_id text, provider_payment_intent_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS paid_content_access (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id), buyer_user_id uuid NOT NULL REFERENCES users(id), price_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', status text NOT NULL DEFAULT 'pending', provider_checkout_session_id text, provider_payment_intent_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,buyer_user_id));
CREATE TABLE IF NOT EXISTS creator_revenue_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), creator_user_id uuid NOT NULL REFERENCES users(id), source_type text NOT NULL, source_id text NOT NULL, gross_cents integer NOT NULL, platform_fee_cents integer NOT NULL, creator_net_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(source_type,source_id));
CREATE INDEX IF NOT EXISTS idx_creator_revenue_events ON creator_revenue_events(creator_user_id,status,created_at DESC);
`
,`-- Yaposan 114.0 — creator-owned page advertising marketplace, CPC accounting and fraud controls.
CREATE TABLE IF NOT EXISTS creator_ad_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL UNIQUE REFERENCES spaces(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id), enabled boolean NOT NULL DEFAULT false, cpc_cents integer NOT NULL DEFAULT 10, currency text NOT NULL DEFAULT 'USD', placement text NOT NULL DEFAULT 'bottom_overlay', require_approval boolean NOT NULL DEFAULT true, platform_fee_bps integer NOT NULL DEFAULT 2000, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS creator_ad_campaigns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id), advertiser_user_id uuid NOT NULL REFERENCES users(id), title text NOT NULL, description text, image_url text, target_url text NOT NULL, budget_cents integer NOT NULL, funded_cents integer NOT NULL DEFAULT 0, spent_cents integer NOT NULL DEFAULT 0, cpc_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', status text NOT NULL DEFAULT 'pending_funding', provider_checkout_session_id text, provider_payment_intent_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_creator_ad_campaigns_delivery ON creator_ad_campaigns(space_id,status,created_at DESC);
CREATE TABLE IF NOT EXISTS creator_ad_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid NOT NULL REFERENCES creator_ad_campaigns(id) ON DELETE CASCADE, space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id), event_type text NOT NULL, visitor_key text NOT NULL, billed_cents integer NOT NULL DEFAULT 0, platform_fee_cents integer NOT NULL DEFAULT 0, creator_net_cents integer NOT NULL DEFAULT 0, currency text NOT NULL DEFAULT 'USD', fraud_status text NOT NULL DEFAULT 'accepted', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_creator_ad_events_dedupe ON creator_ad_events(campaign_id,event_type,visitor_key,created_at DESC);
`
,`-- Yaposan 115.0 — payment webhook idempotency and payment-security audit trail.
CREATE TABLE IF NOT EXISTS payment_webhook_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), provider text NOT NULL DEFAULT 'stripe', provider_event_id text NOT NULL UNIQUE, event_type text NOT NULL, status text NOT NULL DEFAULT 'processing', processed_at timestamptz, error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_payment_webhook_events_status ON payment_webhook_events(status,created_at DESC);
CREATE TABLE IF NOT EXISTS payment_security_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE SET NULL, kind text NOT NULL, severity text NOT NULL, provider text, resource_type text, resource_id text, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_payment_security_events_kind ON payment_security_events(kind,created_at DESC);
`,`-- Yaposan 116.0 — payment integrity, moderation appeals, youth-safety defaults.
CREATE TABLE IF NOT EXISTS payment_reconciliations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), creator_user_id uuid NOT NULL REFERENCES users(id), provider text NOT NULL DEFAULT 'stripe', provider_event_id text NOT NULL UNIQUE, kind text NOT NULL, resource_type text NOT NULL, resource_id text NOT NULL, gross_cents integer NOT NULL DEFAULT 0, platform_fee_cents integer NOT NULL DEFAULT 0, creator_net_cents integer NOT NULL DEFAULT 0, currency text NOT NULL DEFAULT 'USD', status text NOT NULL, reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_payment_reconciliations_creator ON payment_reconciliations(creator_user_id,status,created_at DESC);
CREATE TABLE IF NOT EXISTS moderation_appeals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, resource_type text NOT NULL, resource_id text NOT NULL, reason text NOT NULL, status text NOT NULL DEFAULT 'open', reviewed_by_principal_id uuid REFERENCES admin_principals(id) ON DELETE SET NULL, decision_note text, resolved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_moderation_appeals_queue ON moderation_appeals(status,created_at DESC);
CREATE TABLE IF NOT EXISTS user_safety_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, age_band text NOT NULL, guardian_consent_status text NOT NULL, personalized_ads boolean NOT NULL DEFAULT false, unknown_dm boolean NOT NULL DEFAULT false, live_host boolean NOT NULL DEFAULT false, creator_monetization boolean NOT NULL DEFAULT false, sensitive_media_default text NOT NULL DEFAULT 'blur', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
`,
`CREATE TABLE IF NOT EXISTS auth_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject_type text NOT NULL, subject_id uuid NOT NULL, email text NOT NULL, purpose text NOT NULL, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, used_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_auth_tokens_subject_purpose ON auth_tokens(subject_type,subject_id,purpose,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_expires ON auth_tokens(expires_at);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at timestamptz;`,
`-- Yaposan 119.3.2 — persistent Page presentation.
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS bio text;
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS avatar_uri text;
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS cover_uri text;
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS cover_x double precision NOT NULL DEFAULT 0;
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS cover_y double precision NOT NULL DEFAULT 0;
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS cover_zoom double precision NOT NULL DEFAULT 1;`,
`-- Post audience and profile field privacy hardening.
ALTER TABLE space_posts ADD COLUMN IF NOT EXISTS audience_user_ids uuid[] NOT NULL DEFAULT ARRAY[]::uuid[];
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS location text;
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS display_name_audience text NOT NULL DEFAULT 'private';
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS email_audience text NOT NULL DEFAULT 'private';
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS bio_audience text NOT NULL DEFAULT 'private';
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS website_audience text NOT NULL DEFAULT 'private';
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS location_audience text NOT NULL DEFAULT 'private';
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS avatar_audience text NOT NULL DEFAULT 'private';
ALTER TABLE space_privacy_settings ADD COLUMN IF NOT EXISTS cover_audience text NOT NULL DEFAULT 'private';`

] as const;

export class PostgresDatabase implements DatabaseAdapter {
  private readonly client: SqlClient;
  private readonly ownsClient: boolean;
  constructor(client: SqlClient, ownsClient=true) { this.client = client; this.ownsClient=ownsClient; }
  async connect() { await this.client.query("SELECT 1"); }
  async close() { if(this.ownsClient) await this.client.end?.(); }
  async migrate() { for (const migration of POSTGRES_MIGRATIONS) await this.client.query(migration); return POSTGRES_MIGRATIONS.length; }
  async insert<K extends EntityName>(table: K, value: Omit<DatabaseSchema[K], keyof RecordBase> & Partial<RecordBase>) {
    const entries = Object.entries(value).filter(([, v]) => v !== undefined);
    const columns = entries.map(([k]) => snake(k));
    const values = entries.map(([, v]) => v);
    const sql = `INSERT INTO ${TABLES[table]} (${columns.join(",")}) VALUES (${values.map((_, i) => `$${i + 1}`).join(",")}) RETURNING *`;
    return decode<DatabaseSchema[K]>((await this.client.query(sql, values)).rows[0] as Record<string, unknown>);
  }
  async get<K extends EntityName>(table: K, id: string) { const row = (await this.client.query(`SELECT * FROM ${TABLES[table]} WHERE id=$1`, [id])).rows[0]; return row ? decode<DatabaseSchema[K]>(row as Record<string, unknown>) : undefined; }
  async find<K extends EntityName>(table: K, predicate: (row: DatabaseSchema[K]) => boolean) { const rows = (await this.client.query(`SELECT * FROM ${TABLES[table]}`)).rows.map(row => decode<DatabaseSchema[K]>(row as Record<string, unknown>)); return rows.filter(predicate); }
  async update<K extends EntityName>(table: K, id: string, patch: Partial<DatabaseSchema[K]>) {
    const entries = Object.entries(patch).filter(([k, v]) => k !== "id" && v !== undefined);
    if (!entries.length) { const current = await this.get(table, id); if (!current) throw new Error("RECORD_NOT_FOUND"); return current; }
    const sets = entries.map(([k], i) => `${snake(k)}=$${i + 2}`);
    const row = (await this.client.query(`UPDATE ${TABLES[table]} SET ${sets.join(",")},updated_at=now() WHERE id=$1 RETURNING *`, [id, ...entries.map(([, v]) => v)])).rows[0];
    if (!row) throw new Error("RECORD_NOT_FOUND"); return decode<DatabaseSchema[K]>(row as Record<string, unknown>);
  }
  async delete<K extends EntityName>(table: K, id: string) { return (await this.client.query(`DELETE FROM ${TABLES[table]} WHERE id=$1 RETURNING id`, [id])).rows.length > 0; }

  async claimNextJob(kind: import("./database").JobRecord["kind"], workerId: string, leaseSeconds: number) {
    const sql = `WITH candidate AS (SELECT id FROM jobs WHERE kind=$1 AND status='queued' ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE jobs SET status='running',attempts=attempts+1,progress=1,worker_id=$2,heartbeat_at=now(),lease_expires_at=now()+($3 * interval '1 second'),updated_at=now() WHERE id=(SELECT id FROM candidate) RETURNING *`;
    const row=(await this.client.query(sql,[kind,workerId,leaseSeconds])).rows[0]; return row?decode<import("./database").JobRecord>(row as Record<string,unknown>):undefined;
  }
  async recoverStaleJobs(kind: import("./database").JobRecord["kind"], now=new Date()) {
    const result=await this.client.query<{id:string}>(`UPDATE jobs SET status='queued',progress=0,worker_id=NULL,heartbeat_at=NULL,lease_expires_at=NULL,error='Recovered after worker lease expired',updated_at=now() WHERE kind=$1 AND status='running' AND lease_expires_at <= $2 RETURNING id`,[kind,now.toISOString()]); return result.rows.length;
  }
  async lock(key:string){ await this.client.query("SELECT pg_advisory_xact_lock(hashtext($1))",[key]); }
  async transaction<T>(fn: (db: DatabaseAdapter) => Promise<T>) {
    const connection=this.client.connect?await this.client.connect():this.client;
    const tx=new PostgresDatabase(connection as SqlClient,false);
    await connection.query("BEGIN");
    try { const value = await fn(tx); await connection.query("COMMIT"); return value; }
    catch (error) { await connection.query("ROLLBACK"); throw error; }
    finally { connection.release?.(); }
  }
}

export async function createPostgresDatabase(databaseUrl: string) {
  const pg = await import("pg") as unknown as { Pool: new (options: { connectionString: string; max: number; ssl?: { rejectUnauthorized: boolean } }) => SqlClient };
  const client = new pg.Pool({ connectionString: databaseUrl, max: 10, ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : undefined });
  const database = new PostgresDatabase(client); await database.connect(); await database.migrate(); return database;
}
