import { createHash, randomUUID } from "node:crypto";
import type { DatabaseAdapter, JobRecord } from "./database";

export type ProductionFormat="pdf"|"pdfx1a"|"pdfx4"|"pdfa2b"|"svg"|"png"|"jpg"|"webp"|"tiff"|"avif"|"html"|"zip"|"mp4"|"webm"|"gif"|"wav"|"mp3";
export type ExportRequest={projectId:string;workspaceId:string;userId:string;format:ProductionFormat;options?:{dpi?:number;colorSpace?:"rgb"|"cmyk"|"gray";bleedMm?:number;iccProfile?:string;fontPolicy?:"embed"|"subset"|"outline";spotColors?:boolean;transparent?:boolean;width?:number;height?:number;fps?:number};};
export type ExportManifest={jobId:string;projectId:string;format:ProductionFormat;pipeline:string[];artifacts:{name:string;mediaType:string;role:string}[];checksum:string;createdAt:string};

const mediaType:Record<ProductionFormat,string>={pdf:"application/pdf",pdfx1a:"application/pdf",pdfx4:"application/pdf",pdfa2b:"application/pdf",svg:"image/svg+xml",png:"image/png",jpg:"image/jpeg",webp:"image/webp",tiff:"image/tiff",avif:"image/avif",html:"text/html",zip:"application/zip",mp4:"video/mp4",webm:"video/webm",gif:"image/gif",wav:"audio/wav",mp3:"audio/mpeg"};
export function buildExportPipeline(request:ExportRequest){const p=["load-project","resolve-assets","preflight"];if(request.format.startsWith("pdf")){p.push("compose-pages","apply-font-policy","apply-color-management");if(request.format==="pdfx1a")p.push("flatten-transparency","convert-cmyk","embed-output-intent");if(request.format==="pdfx4")p.push("preserve-transparency","embed-output-intent");if(request.format==="pdfa2b")p.push("embed-metadata","validate-archival-profile");p.push("write-pdf")}
 else if(["mp4","webm","gif"].includes(request.format))p.push("render-frames","mix-audio","encode-ffmpeg");else if(["wav","mp3"].includes(request.format))p.push("mix-audio","encode-audio");else if(request.format==="html")p.push("bundle-responsive-html","package-assets");else p.push("render-surface","encode-image");p.push("checksum","publish-artifact");return p}
export async function createExportJob(db:DatabaseAdapter,request:ExportRequest){const project=await db.get("projects",request.projectId);if(!project||project.workspaceId!==request.workspaceId)throw new Error("PROJECT_NOT_FOUND");const job=await db.insert("jobs",{kind:"export",status:"queued",progress:0,attempts:0,payload:{...request,pipeline:buildExportPipeline(request)}});return job}
export async function claimNextExportJob(db:DatabaseAdapter,workerId="worker-local",leaseSeconds=60){if(db.claimNextJob)return db.claimNextJob("export",workerId,leaseSeconds);return db.transaction(async tx=>{const jobs=(await tx.find("jobs",j=>j.kind==="export"&&j.status==="queued")).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));const job=jobs[0];if(!job)return undefined;return tx.update("jobs",job.id,{status:"running",attempts:job.attempts+1,progress:1,workerId,heartbeatAt:new Date().toISOString(),leaseExpiresAt:new Date(Date.now()+leaseSeconds*1000).toISOString()})})}
export async function updateExportJob(db:DatabaseAdapter,id:string,patch:{progress?:number;status?:JobRecord["status"];result?:unknown;error?:string;workerId?:string;leaseSeconds?:number}){const current=await db.get("jobs",id);if(!current||current.kind!=="export")throw new Error("EXPORT_JOB_NOT_FOUND");if(patch.workerId&&current.workerId&&patch.workerId!==current.workerId)throw new Error("EXPORT_JOB_LEASE_MISMATCH");const terminal=patch.status&&["succeeded","failed","cancelled"].includes(patch.status);const {leaseSeconds=60,...persisted}=patch;return db.update("jobs",id,{...persisted,progress:Math.max(0,Math.min(100,patch.progress??current.progress)),heartbeatAt:terminal?undefined:new Date().toISOString(),leaseExpiresAt:terminal?undefined:new Date(Date.now()+leaseSeconds*1000).toISOString(),workerId:terminal?undefined:(patch.workerId??current.workerId)})}
export async function cancelExportJob(db:DatabaseAdapter,id:string){const current=await db.get("jobs",id);if(!current||current.kind!=="export")throw new Error("EXPORT_JOB_NOT_FOUND");if(current.status==="succeeded")throw new Error("EXPORT_ALREADY_COMPLETED");return db.update("jobs",id,{status:"cancelled"})}
export async function retryExportJob(db:DatabaseAdapter,id:string){const current=await db.get("jobs",id);if(!current||current.kind!=="export")throw new Error("EXPORT_JOB_NOT_FOUND");if(!["failed","cancelled"].includes(current.status))throw new Error("EXPORT_NOT_RETRYABLE");return db.update("jobs",id,{status:"queued",progress:0,error:undefined})}
export function buildExportManifest(job:JobRecord):ExportManifest{const payload=job.payload as ExportRequest&{pipeline:string[]};const ext=payload.format.replace("pdfx1a","pdf").replace("pdfx4","pdf").replace("pdfa2b","pdf");const base=`${payload.projectId}-${job.id.slice(0,8)}`;const data=JSON.stringify({jobId:job.id,projectId:payload.projectId,format:payload.format,pipeline:payload.pipeline,options:payload.options});return{jobId:job.id,projectId:payload.projectId,format:payload.format,pipeline:payload.pipeline,artifacts:[{name:`${base}.${ext}`,mediaType:mediaType[payload.format],role:"primary"},{name:`${base}-manifest.json`,mediaType:"application/json",role:"manifest"}],checksum:createHash("sha256").update(data).digest("hex"),createdAt:new Date().toISOString()}}
export function ffmpegPlan(request:ExportRequest,inputPattern="frame-%06d.png",audioInput?:string){if(!["mp4","webm","gif"].includes(request.format))throw new Error("FFMPEG_FORMAT_REQUIRED");const fps=request.options?.fps??30;const args=["-y","-framerate",String(fps),"-i",inputPattern];if(audioInput)args.push("-i",audioInput,"-shortest");if(request.format==="mp4")args.push("-c:v","libx264","-pix_fmt","yuv420p",...(audioInput?["-c:a","aac"]:[]),"output.mp4");if(request.format==="webm")args.push("-c:v","libvpx-vp9",...(audioInput?["-c:a","libopus"]:[]),"output.webm");if(request.format==="gif")args.push("-vf",`fps=${fps},split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse`,"output.gif");return args}
export function createCollaborationChannel(projectId:string){return `project:${projectId}:${randomUUID().slice(0,8)}`}

export async function recoverStaleExportJobs(db:DatabaseAdapter,now=new Date()){if(db.recoverStaleJobs)return db.recoverStaleJobs("export",now);return 0}
