import net from "node:net";
import tls from "node:tls";

export type RedisCommandClient={get(key:string):Promise<string|null>;set(key:string,value:string,options?:{EX?:number}):Promise<string>;del(key:string):Promise<number>};
const encode=(parts:(string|number)[])=>`*${parts.length}\r\n${parts.map(part=>{const value=String(part);return `$${Buffer.byteLength(value)}\r\n${value}\r\n`}).join("")}`;
function parse(buffer:Buffer):string|number|null{const text=buffer.toString("utf8");const type=text[0];if(type==="+")return text.slice(1,text.indexOf("\r\n"));if(type===":")return Number(text.slice(1,text.indexOf("\r\n")));if(type==="$" ){const lineEnd=text.indexOf("\r\n");const length=Number(text.slice(1,lineEnd));if(length===-1)return null;return text.slice(lineEnd+2,lineEnd+2+length)}if(type==="-")throw new Error(`REDIS_ERROR:${text.slice(1,text.indexOf("\r\n"))}`);throw new Error("REDIS_PROTOCOL_ERROR")}
export function createRedisCommandClient(redisUrl:string):RedisCommandClient{const url=new URL(redisUrl);if(!["redis:","rediss:"].includes(url.protocol))throw new Error("REDIS_URL_INVALID");const port=Number(url.port||("rediss:"===url.protocol?6380:6379));const host=url.hostname;const password=url.password?decodeURIComponent(url.password):undefined;const username=url.username?decodeURIComponent(url.username):undefined;
 const command=(parts:(string|number)[])=>new Promise<string|number|null>((resolve,reject)=>{const socket=url.protocol==="rediss:"?tls.connect({host,port,servername:host}):net.connect({host,port});const responses:Buffer[]=[];let authenticated=!password;const send=()=>{if(password&&!authenticated)socket.write(encode(username?["AUTH",username,password]:["AUTH",password]));else socket.write(encode(parts))};socket.setTimeout(10_000,()=>socket.destroy(new Error("REDIS_TIMEOUT")));if(url.protocol==="rediss:")socket.on("secureConnect",send);else socket.on("connect",send);socket.on("data",chunk=>{responses.push(chunk);const joined=Buffer.concat(responses);try{const result=parse(joined);if(!authenticated){authenticated=true;responses.length=0;socket.write(encode(parts));return}socket.end();resolve(result)}catch(error){if(error instanceof Error&&error.message==="REDIS_PROTOCOL_ERROR")return;socket.destroy();reject(error)}});socket.on("error",reject)});
 return{async get(key){const result=await command(["GET",key]);return result===null?null:String(result)},async set(key,value,options){const result=await command(options?.EX?["SET",key,value,"EX",options.EX]:["SET",key,value]);return String(result)},async del(key){return Number(await command(["DEL",key]))}}}
