import type { DatabaseAdapter, CreatorRevenueEventRecord } from './database';
import { requireSpaceAccess } from './spaces';

const clean=(v:unknown,n:number)=>String(v??'').trim().slice(0,n);
const money=(v:unknown,min=50,max=100000)=>{const n=Math.round(Number(v));if(!Number.isFinite(n)||n<min||n>max)throw new Error('INVALID_AMOUNT');return n};
const currency=(v:unknown)=>{const c=clean(v||'USD',3).toUpperCase();if(!/^[A-Z]{3}$/.test(c))throw new Error('INVALID_CURRENCY');return c};
export const CREATOR_PLATFORM_FEE_BPS=Math.max(0,Math.min(5000,Number(process.env.YAPOSAN_CREATOR_PLATFORM_FEE_BPS??1000)));
export function splitCreatorRevenue(grossCents:number){const platformFeeCents=Math.floor(grossCents*CREATOR_PLATFORM_FEE_BPS/10000);return {grossCents,platformFeeCents,creatorNetCents:grossCents-platformFeeCents};}

export async function createMembershipPlan(db:DatabaseAdapter,userId:string,input:{spaceId:string;name:string;description?:string;monthlyCents:number;currency?:string;benefits?:string[]}){
 const space=await requireSpaceAccess(db,userId,input.spaceId,'admin');if(space.ownerUserId!==userId){const m=(await db.find('spaceMemberships',x=>x.spaceId===space.id&&x.userId===userId))[0];if(!m||!['owner','admin'].includes(m.role))throw new Error('CREATOR_ADMIN_REQUIRED');}
 return db.insert('creatorMembershipPlans',{spaceId:space.id,creatorUserId:space.ownerUserId,name:clean(input.name,80)||'Membership',description:clean(input.description,1000)||undefined,monthlyCents:money(input.monthlyCents,100,100000),currency:currency(input.currency),benefits:(input.benefits??[]).map(x=>clean(x,120)).filter(Boolean).slice(0,20),status:'active'});
}
export async function listMembershipPlans(db:DatabaseAdapter,spaceId:string){return (await db.find('creatorMembershipPlans',x=>x.spaceId===spaceId&&x.status==='active')).sort((a,b)=>a.monthlyCents-b.monthlyCents);}
export async function beginMembershipSubscription(db:DatabaseAdapter,userId:string,planId:string){const plan=await db.get('creatorMembershipPlans',planId);if(!plan||plan.status!=='active')throw new Error('MEMBERSHIP_PLAN_NOT_FOUND');if(plan.creatorUserId===userId)throw new Error('CANNOT_SUBSCRIBE_TO_SELF');const existing=(await db.find('creatorMembershipSubscriptions',x=>x.planId===plan.id&&x.subscriberUserId===userId))[0];if(existing&&['pending','active'].includes(existing.status))return existing;return db.insert('creatorMembershipSubscriptions',{planId:plan.id,creatorUserId:plan.creatorUserId,subscriberUserId:userId,status:'pending'});}
export async function createTip(db:DatabaseAdapter,userId:string,input:{spaceId:string;amountCents:number;currency?:string;message?:string}){const space=await db.get('spaces',input.spaceId);if(!space||space.status!=='active'||!['public','unlisted','paid'].includes(space.visibility))throw new Error('CREATOR_NOT_AVAILABLE');if(space.ownerUserId===userId)throw new Error('CANNOT_TIP_SELF');return db.insert('creatorTips',{spaceId:space.id,creatorUserId:space.ownerUserId,senderUserId:userId,amountCents:money(input.amountCents),currency:currency(input.currency),message:clean(input.message,280)||undefined,status:'pending'});}
export async function setPaidPost(db:DatabaseAdapter,userId:string,spaceId:string,postId:string,priceCents:number){await requireSpaceAccess(db,userId,spaceId,'editor');const post=await db.get('spacePosts',postId);if(!post||post.spaceId!==spaceId||post.authorUserId!==userId)throw new Error('POST_NOT_OWNED');return db.update('spacePosts',post.id,{accessModel:'paid',priceCents:money(priceCents,50,50000)} as any);}
export async function beginPaidPostUnlock(db:DatabaseAdapter,userId:string,postId:string){const post=await db.get('spacePosts',postId) as any;if(!post||post.visibility!=='public'||post.accessModel!=='paid'||!post.priceCents)throw new Error('PAID_POST_NOT_FOUND');if(post.authorUserId===userId)throw new Error('CONTENT_ALREADY_OWNED');const existing=(await db.find('paidContentAccess',x=>x.postId===post.id&&x.buyerUserId===userId))[0];if(existing&&['pending','active'].includes(existing.status))return existing;return db.insert('paidContentAccess',{postId:post.id,creatorUserId:post.authorUserId,buyerUserId:userId,priceCents:post.priceCents,currency:'USD',status:'pending'});}
export async function grantCreatorPurchase(db:DatabaseAdapter,sourceType:'membership'|'tip'|'paid_post',sourceId:string,provider:{checkoutSessionId?:string;paymentIntentId?:string;subscriptionId?:string;customerId?:string;periodEnd?:string}){return db.transaction(async tx=>{let creatorUserId='',grossCents=0,curr='USD';if(sourceType==='tip'){const row=await tx.get('creatorTips',sourceId);if(!row)return;creatorUserId=row.creatorUserId;grossCents=row.amountCents;curr=row.currency;await tx.update('creatorTips',row.id,{status:'paid',providerCheckoutSessionId:provider.checkoutSessionId,providerPaymentIntentId:provider.paymentIntentId});}else if(sourceType==='paid_post'){const row=await tx.get('paidContentAccess',sourceId);if(!row)return;creatorUserId=row.creatorUserId;grossCents=row.priceCents;curr=row.currency;await tx.update('paidContentAccess',row.id,{status:'active',providerCheckoutSessionId:provider.checkoutSessionId,providerPaymentIntentId:provider.paymentIntentId});}else{const sub=await tx.get('creatorMembershipSubscriptions',sourceId);if(!sub)return;const plan=await tx.get('creatorMembershipPlans',sub.planId);if(!plan)return;creatorUserId=sub.creatorUserId;grossCents=plan.monthlyCents;curr=plan.currency;await tx.update('creatorMembershipSubscriptions',sub.id,{status:'active',providerCheckoutSessionId:provider.checkoutSessionId,providerSubscriptionId:provider.subscriptionId,providerCustomerId:provider.customerId,currentPeriodEnd:provider.periodEnd});}
 const prior=(await tx.find('creatorRevenueEvents',x=>x.sourceType===sourceType&&x.sourceId===sourceId))[0];if(prior)return prior;const split=splitCreatorRevenue(grossCents);return tx.insert('creatorRevenueEvents',{creatorUserId,sourceType,sourceId,...split,currency:curr,status:'available'});});}
export async function settleCreatorEconomyStripe(db:DatabaseAdapter,event:any){const obj=event?.data?.object??{};const meta=obj.metadata??{};const purpose=String(meta.purpose??'');if(!['creator_membership','creator_tip','paid_post'].includes(purpose))return undefined;const sourceType=purpose==='creator_membership'?'membership':purpose==='creator_tip'?'tip':'paid_post';const sourceId=String(meta.sourceId??'');if(!sourceId)return undefined;if(event.type==='checkout.session.completed'||event.type==='invoice.paid'){return grantCreatorPurchase(db,sourceType as any,sourceId,{checkoutSessionId:String(obj.id??''),paymentIntentId:String(obj.payment_intent??''),subscriptionId:String(obj.subscription??''),customerId:String(obj.customer??''),periodEnd:obj.current_period_end?new Date(Number(obj.current_period_end)*1000).toISOString():undefined});}if(event.type==='customer.subscription.deleted'&&sourceType==='membership'){const sub=await db.get('creatorMembershipSubscriptions',sourceId);return sub?db.update('creatorMembershipSubscriptions',sub.id,{status:'canceled'}):undefined;}return undefined;}
export async function creatorEconomyDashboard(db:DatabaseAdapter,userId:string){const [plans,subs,tips,access,revenue,posts,reactions,comments,follows,reels,storyViews]=await Promise.all([db.find('creatorMembershipPlans',x=>x.creatorUserId===userId),db.find('creatorMembershipSubscriptions',x=>x.creatorUserId===userId),db.find('creatorTips',x=>x.creatorUserId===userId),db.find('paidContentAccess',x=>x.creatorUserId===userId),db.find('creatorRevenueEvents',x=>x.creatorUserId===userId),db.find('spacePosts',x=>x.authorUserId===userId),db.find('spacePostReactions',()=>true),db.find('spaceComments',()=>true),db.find('spaceFollows',()=>true),db.find('socialReels',x=>x.authorUserId===userId),db.find('socialStoryViews',()=>true)]);const postIds=new Set(posts.map(x=>x.id));const spaces=new Set(posts.map(x=>x.spaceId));return {memberships:{plans:plans.length,activeSubscribers:subs.filter(x=>x.status==='active').length},tips:{paid:tips.filter(x=>x.status==='paid').length,grossCents:tips.filter(x=>x.status==='paid').reduce((n,x)=>n+x.amountCents,0)},paidContent:{unlocks:access.filter(x=>x.status==='active').length},revenue:{availableCents:revenue.filter(x=>x.status==='available').reduce((n,x)=>n+x.creatorNetCents,0),grossCents:revenue.filter(x=>x.status!=='refunded').reduce((n,x)=>n+x.grossCents,0),platformFeeCents:revenue.filter(x=>x.status!=='refunded').reduce((n,x)=>n+x.platformFeeCents,0),currency:'USD'},engagement:{posts:posts.length,reels:reels.length,reactions:reactions.filter(x=>postIds.has(x.postId)).length,comments:comments.filter(x=>postIds.has(x.postId)).length,followers:follows.filter(x=>spaces.has(x.spaceId)).length,storyViews:storyViews.length},note:'Creator-facing analytics exclude Yaposan operating expenses.'};}

export async function linkPaidCommunity(db:DatabaseAdapter,userId:string,communityId:string,planId:string){const community=await db.get('socialCommunities',communityId);if(!community)throw new Error('COMMUNITY_NOT_FOUND');await requireSpaceAccess(db,userId,community.spaceId,'admin');const plan=await db.get('creatorMembershipPlans',planId);if(!plan||plan.spaceId!==community.spaceId||plan.status!=='active')throw new Error('MEMBERSHIP_PLAN_NOT_FOUND');return db.update('socialCommunities',community.id,{membershipPlanId:plan.id});}
