import type { DatabaseAdapter } from './database';
import { requireSpaceAccess } from './spaces';
import { createHash } from 'node:crypto';
const clean=(v:unknown,n:number)=>String(v??'').trim().slice(0,n);
const money=(v:unknown,min:number,max:number)=>{const n=Math.round(Number(v));if(!Number.isFinite(n)||n<min||n>max)throw new Error('INVALID_AMOUNT');return n};
const safeUrl=(v:unknown)=>{let u:URL;try{u=new URL(clean(v,2000))}catch{throw new Error('INVALID_URL')}if(!['https:','http:'].includes(u.protocol))throw new Error('INVALID_URL');return u.toString()};
export const AD_PLATFORM_FEE_BPS=Math.max(1000,Math.min(3000,Number(process.env.YAPOSAN_AD_PLATFORM_FEE_BPS??2000)));
export const adSplit=(gross:number,feeBps=AD_PLATFORM_FEE_BPS)=>{const platformFeeCents=Math.floor(gross*Math.max(1000,Math.min(3000,feeBps))/10000);return {grossCents:gross,platformFeeCents,creatorNetCents:gross-platformFeeCents}};
export async function getAdSettings(db:DatabaseAdapter,spaceId:string){const existing=(await db.find('creatorAdSettings',x=>x.spaceId===spaceId))[0];if(existing)return existing;const space=await db.get('spaces',spaceId);if(!space)throw new Error('SPACE_NOT_FOUND');return {spaceId,creatorUserId:space.ownerUserId,enabled:false,cpcCents:10,currency:'USD',placement:'bottom_overlay' as const,requireApproval:true,platformFeeBps:AD_PLATFORM_FEE_BPS,status:'active' as const};}
export async function updateAdSettings(db:DatabaseAdapter,userId:string,spaceId:string,input:any){const space=await requireSpaceAccess(db,userId,spaceId,'admin');const values={enabled:Boolean(input.enabled),cpcCents:money(input.cpcCents,1,100000),currency:'USD',placement:input.placement==='bottom_banner'?'bottom_banner' as const:'bottom_overlay' as const,requireApproval:input.requireApproval!==false,platformFeeBps:AD_PLATFORM_FEE_BPS,status:'active' as const};const current=(await db.find('creatorAdSettings',x=>x.spaceId===spaceId))[0];return current?db.update('creatorAdSettings',current.id,values):db.insert('creatorAdSettings',{spaceId,creatorUserId:space.ownerUserId,...values});}
export async function publicAdOffer(db:DatabaseAdapter,slug:string){const space=(await db.find('spaces',x=>x.slug===slug&&x.status==='active'&&x.visibility==='public'))[0];if(!space)throw new Error('PAGE_NOT_FOUND');const settings=await getAdSettings(db,space.id);return {space:{id:space.id,name:space.name,slug:space.slug},enabled:settings.enabled&&settings.status==='active',cpcCents:settings.cpcCents,currency:settings.currency,placement:settings.placement,platformFeePercent:settings.platformFeeBps/100,minimumBudgetCents:1000,maximumBudgetCents:10000000};}
export async function createAdCampaign(db:DatabaseAdapter,userId:string,input:any){const space=await db.get('spaces',clean(input.spaceId,80));if(!space||space.status!=='active'||space.visibility!=='public')throw new Error('PAGE_NOT_AVAILABLE');if(space.ownerUserId===userId)throw new Error('CANNOT_ADVERTISE_TO_SELF');const settings=await getAdSettings(db,space.id);if(!settings.enabled||settings.status!=='active')throw new Error('ADS_NOT_ENABLED');return db.insert('creatorAdCampaigns',{spaceId:space.id,creatorUserId:space.ownerUserId,advertiserUserId:userId,title:clean(input.title,100)||'Sponsored',description:clean(input.description,300)||undefined,imageUrl:input.imageUrl?safeUrl(input.imageUrl):undefined,targetUrl:safeUrl(input.targetUrl),budgetCents:money(input.budgetCents,1000,10000000),fundedCents:0,spentCents:0,cpcCents:settings.cpcCents,currency:'USD',status:'pending_funding'});}
export async function settleAdCampaignStripe(db:DatabaseAdapter,event:any){const obj=event?.data?.object??{},meta=obj.metadata??{};if(String(meta.purpose??'')!=='creator_ad_campaign'||event.type!=='checkout.session.completed')return undefined;const id=String(meta.campaignId??'');const campaign=await db.get('creatorAdCampaigns',id);if(!campaign||campaign.status!=='pending_funding')return campaign;const settings=await getAdSettings(db,campaign.spaceId);return db.update('creatorAdCampaigns',campaign.id,{fundedCents:campaign.budgetCents,providerCheckoutSessionId:String(obj.id??''),providerPaymentIntentId:String(obj.payment_intent??''),status:settings.requireApproval?'awaiting_approval':'active'});}
export async function listCreatorAdCampaigns(db:DatabaseAdapter,userId:string,spaceId:string){await requireSpaceAccess(db,userId,spaceId,'admin');return (await db.find('creatorAdCampaigns',x=>x.spaceId===spaceId)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
export async function decideAdCampaign(db:DatabaseAdapter,userId:string,spaceId:string,campaignId:string,decision:'approve'|'reject'|'pause'){await requireSpaceAccess(db,userId,spaceId,'admin');const c=await db.get('creatorAdCampaigns',campaignId);if(!c||c.spaceId!==spaceId)throw new Error('CAMPAIGN_NOT_FOUND');const status=decision==='approve'?(c.fundedCents>c.spentCents?'active':'completed'):decision==='pause'?'paused':'rejected';return db.update('creatorAdCampaigns',c.id,{status});}
export async function selectPublicAd(db:DatabaseAdapter,slug:string,visitorKey:string){const offer=await publicAdOffer(db,slug);if(!offer.enabled)return {offer,ad:null};const campaigns=(await db.find('creatorAdCampaigns',x=>x.spaceId===offer.space.id&&x.status==='active'&&x.fundedCents-x.spentCents>=x.cpcCents)).sort((a,b)=>a.spentCents/a.fundedCents-b.spentCents/b.fundedCents);const ad=campaigns[0];if(!ad)return {offer,ad:null};await db.insert('creatorAdEvents',{campaignId:ad.id,spaceId:ad.spaceId,creatorUserId:ad.creatorUserId,eventType:'impression',visitorKey,billedCents:0,platformFeeCents:0,creatorNetCents:0,currency:ad.currency,fraudStatus:'accepted'});return {offer,ad:{id:ad.id,title:ad.title,description:ad.description,imageUrl:ad.imageUrl,targetUrl:ad.targetUrl,label:'Sponsored',cpcCents:ad.cpcCents}};}
export function visitorKey(ip:string,ua:string,campaignOrPage:string,day=new Date().toISOString().slice(0,10)){return createHash('sha256').update(`${ip}|${ua.slice(0,200)}|${campaignOrPage}|${day}`).digest('hex')}
export async function recordAdClick(db:DatabaseAdapter,campaignId:string,vkey:string){return db.transaction(async tx=>{const c=await tx.get('creatorAdCampaigns',campaignId);if(!c||c.status!=='active')throw new Error('CAMPAIGN_NOT_ACTIVE');const duplicate=(await tx.find('creatorAdEvents',x=>x.campaignId===c.id&&x.eventType==='click'&&x.visitorKey===vkey&&x.fraudStatus==='accepted'))[0];if(duplicate)return {charged:false,duplicate:true,targetUrl:c.targetUrl,campaign:c};if(c.fundedCents-c.spentCents<c.cpcCents){await tx.update('creatorAdCampaigns',c.id,{status:'completed'});throw new Error('CAMPAIGN_BUDGET_EXHAUSTED')}const split=adSplit(c.cpcCents);const ev=await tx.insert('creatorAdEvents',{campaignId:c.id,spaceId:c.spaceId,creatorUserId:c.creatorUserId,eventType:'click',visitorKey:vkey,billedCents:c.cpcCents,platformFeeCents:split.platformFeeCents,creatorNetCents:split.creatorNetCents,currency:c.currency,fraudStatus:'accepted'});const spent=c.spentCents+c.cpcCents;await tx.update('creatorAdCampaigns',c.id,{spentCents:spent,status:spent+c.cpcCents>c.fundedCents?'completed':c.status});await tx.insert('creatorRevenueEvents',{creatorUserId:c.creatorUserId,sourceType:'ad_click',sourceId:ev.id,grossCents:c.cpcCents,platformFeeCents:split.platformFeeCents,creatorNetCents:split.creatorNetCents,currency:c.currency,status:'available'});return {charged:true,duplicate:false,targetUrl:c.targetUrl,campaign:await tx.get('creatorAdCampaigns',c.id)};});}
export async function creatorAdDashboard(db:DatabaseAdapter,userId:string,spaceId:string){await requireSpaceAccess(db,userId,spaceId,'admin');const [settings,campaigns,events]=await Promise.all([getAdSettings(db,spaceId),db.find('creatorAdCampaigns',x=>x.spaceId===spaceId),db.find('creatorAdEvents',x=>x.spaceId===spaceId)]);const clicks=events.filter(x=>x.eventType==='click'&&x.fraudStatus==='accepted');return {settings,campaigns,analytics:{campaigns:campaigns.length,activeCampaigns:campaigns.filter(x=>x.status==='active').length,impressions:events.filter(x=>x.eventType==='impression').length,billableClicks:clicks.length,grossCents:clicks.reduce((n,x)=>n+x.billedCents,0),creatorNetCents:clicks.reduce((n,x)=>n+x.creatorNetCents,0),platformFeeCents:clicks.reduce((n,x)=>n+x.platformFeeCents,0),currency:'USD'},note:'Creator-facing ad analytics exclude Yaposan operating expenses.'};}
