import { createHash, randomBytes } from 'node:crypto';
import type { DatabaseAdapter } from './database';
import { requireSpaceAccess } from './spaces';
import { assertNotBlocked } from './social109';
import { createSpacePost } from './spaceSocial';

function slugify(input:string){return input.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,64)}
async function communityRole(db:DatabaseAdapter,communityId:string,userId:string){return (await db.find('socialCommunityMembers',x=>x.communityId===communityId&&x.userId===userId&&x.status==='active'))[0]}
async function requireCommunityModerator(db:DatabaseAdapter,communityId:string,userId:string){const row=await communityRole(db,communityId,userId);if(!row||!['owner','admin','moderator'].includes(row.role))throw new Error('COMMUNITY_MODERATOR_REQUIRED');return row}

export async function createCommunity(db:DatabaseAdapter,userId:string,spaceId:string,input:{name:string;description?:string;visibility?:string;joinPolicy?:string}){
 await requireSpaceAccess(db,userId,spaceId,'editor');const name=input.name.trim().slice(0,100);if(!name)throw new Error('COMMUNITY_NAME_REQUIRED');const base=slugify(name)||'community';const slug=`${base}-${randomBytes(3).toString('hex')}`;const community=await db.insert('socialCommunities',{spaceId,ownerUserId:userId,name,slug,description:input.description?.trim().slice(0,2000)||undefined,visibility:input.visibility==='private'?'private':'public',joinPolicy:(['open','approval','invite'].includes(String(input.joinPolicy))?input.joinPolicy:'open') as 'open'|'approval'|'invite',status:'active'});await db.insert('socialCommunityMembers',{communityId:community.id,userId,role:'owner',status:'active'});return community;
}
export async function listCommunities(db:DatabaseAdapter,userId:string){const communities=(await db.find('socialCommunities',x=>x.status==='active')).filter(x=>x.visibility==='public');const members=await db.find('socialCommunityMembers',x=>x.status==='active');return communities.map(c=>({...c,memberCount:members.filter(m=>m.communityId===c.id).length,joined:members.some(m=>m.communityId===c.id&&m.userId===userId)})).slice(0,100)}
export async function joinCommunity(db:DatabaseAdapter,userId:string,communityId:string){const c=await db.get('socialCommunities',communityId);if(!c||c.status!=='active')throw new Error('COMMUNITY_NOT_FOUND');await assertNotBlocked(db,userId,c.ownerUserId);if(c.membershipPlanId){const paid=(await db.find('creatorMembershipSubscriptions',x=>x.planId===c.membershipPlanId&&x.subscriberUserId===userId&&x.status==='active'))[0];if(!paid&&c.ownerUserId!==userId)throw new Error('PAID_COMMUNITY_MEMBERSHIP_REQUIRED');}const existing=(await db.find('socialCommunityMembers',x=>x.communityId===communityId&&x.userId===userId))[0];const status=c.joinPolicy==='open'?'active':'pending';if(existing)return db.update('socialCommunityMembers',existing.id,{status});return db.insert('socialCommunityMembers',{communityId,userId,role:'member',status})}
export async function createCommunityPost(db:DatabaseAdapter,userId:string,communityId:string,body:string){const c=await db.get('socialCommunities',communityId);if(!c)throw new Error('COMMUNITY_NOT_FOUND');const m=await communityRole(db,communityId,userId);if(!m)throw new Error('COMMUNITY_MEMBERSHIP_REQUIRED');const post=await createSpacePost(db,userId,c.spaceId,body,c.visibility==='public'?'public':'team');await db.insert('socialCommunityPosts',{communityId,postId:post.id,authorUserId:userId,status:'published'});return post}
export async function moderateCommunity(db:DatabaseAdapter,userId:string,communityId:string,input:{targetType:string;targetId:string;action:string;reason?:string}){await requireCommunityModerator(db,communityId,userId);const action=(['hide','remove','warn','mute','ban','restore'].includes(input.action)?input.action:'warn') as 'hide'|'remove'|'warn'|'mute'|'ban'|'restore';if(input.targetType==='post'){const rel=(await db.find('socialCommunityPosts',x=>x.communityId===communityId&&x.postId===input.targetId))[0];if(!rel)throw new Error('COMMUNITY_POST_NOT_FOUND');if(action==='hide'||action==='remove')await db.update('socialCommunityPosts',rel.id,{status:action==='hide'?'hidden':'removed'});if(action==='restore')await db.update('socialCommunityPosts',rel.id,{status:'published'});}if(input.targetType==='member'&&(action==='ban'||action==='restore')){const member=(await db.find('socialCommunityMembers',x=>x.communityId===communityId&&x.userId===input.targetId))[0];if(!member)throw new Error('COMMUNITY_MEMBER_NOT_FOUND');await db.update('socialCommunityMembers',member.id,{status:action==='ban'?'banned':'active'});}return db.insert('socialCommunityModeration',{communityId,actorUserId:userId,targetType:input.targetType==='member'?'member':'post',targetId:input.targetId,action,reason:input.reason?.trim().slice(0,1000)||undefined})}

export async function createSocialPage(db:DatabaseAdapter,userId:string,spaceId:string,input:{name:string;kind?:string;bio?:string;category?:string;website?:string}){await requireSpaceAccess(db,userId,spaceId,'admin');const name=input.name.trim().slice(0,100);if(!name)throw new Error('PAGE_NAME_REQUIRED');const kind=(['creator','business','brand','organization'].includes(String(input.kind))?input.kind:'creator') as 'creator'|'business'|'brand'|'organization';return db.insert('socialPages',{spaceId,ownerUserId:userId,kind,name,slug:`${slugify(name)||'page'}-${randomBytes(3).toString('hex')}`,bio:input.bio?.trim().slice(0,2000)||undefined,category:input.category?.trim().slice(0,120)||undefined,website:input.website?.trim().slice(0,500)||undefined,verified:false,status:'active'})}
export async function listSocialPages(db:DatabaseAdapter){return (await db.find('socialPages',x=>x.status==='active')).slice(0,100)}

export async function createSocialEvent(db:DatabaseAdapter,userId:string,spaceId:string,input:{title:string;description?:string;communityId?:string;pageId?:string;locationType?:string;location?:string;startsAt:string;endsAt?:string;visibility?:string}){await requireSpaceAccess(db,userId,spaceId,'editor');const title=input.title.trim().slice(0,160);if(!title)throw new Error('EVENT_TITLE_REQUIRED');const starts=new Date(input.startsAt);if(Number.isNaN(starts.getTime()))throw new Error('EVENT_START_INVALID');if(input.endsAt&&new Date(input.endsAt).getTime()<starts.getTime())throw new Error('EVENT_END_INVALID');return db.insert('socialEvents',{spaceId,creatorUserId:userId,communityId:input.communityId,pageId:input.pageId,title,description:input.description?.trim().slice(0,4000)||undefined,locationType:(['online','in_person','hybrid'].includes(String(input.locationType))?input.locationType:'online') as 'online'|'in_person'|'hybrid',location:input.location?.trim().slice(0,500)||undefined,startsAt:starts.toISOString(),endsAt:input.endsAt?new Date(input.endsAt).toISOString():undefined,visibility:(['public','community','private'].includes(String(input.visibility))?input.visibility:'public') as 'public'|'community'|'private',status:'scheduled'})}
export async function listUpcomingEvents(db:DatabaseAdapter,userId:string){const now=Date.now();const events=(await db.find('socialEvents',x=>x.status==='scheduled'&&Date.parse(x.startsAt)>=now&&x.visibility==='public')).sort((a,b)=>a.startsAt.localeCompare(b.startsAt));const rsvps=await db.find('socialEventRsvps',()=>true);return events.slice(0,100).map(e=>({...e,goingCount:rsvps.filter(r=>r.eventId===e.id&&r.response==='going').length,myRsvp:rsvps.find(r=>r.eventId===e.id&&r.userId===userId)?.response}))}
export async function rsvpEvent(db:DatabaseAdapter,userId:string,eventId:string,responseInput:string){const event=await db.get('socialEvents',eventId);if(!event||event.status==='cancelled')throw new Error('EVENT_NOT_FOUND');const response=(['going','interested','not_going'].includes(responseInput)?responseInput:'interested') as 'going'|'interested'|'not_going';const existing=(await db.find('socialEventRsvps',x=>x.eventId===eventId&&x.userId===userId))[0];return existing?db.update('socialEventRsvps',existing.id,{response}):db.insert('socialEventRsvps',{eventId,userId,response})}

export async function createLiveSession(db:DatabaseAdapter,userId:string,spaceId:string,input:{title:string;description?:string;communityId?:string;pageId?:string;eventId?:string;playbackUrl?:string}){await requireSpaceAccess(db,userId,spaceId,'editor');const title=input.title.trim().slice(0,160);if(!title)throw new Error('LIVE_TITLE_REQUIRED');const streamKey=randomBytes(24).toString('base64url');const session=await db.insert('socialLiveSessions',{spaceId,hostUserId:userId,communityId:input.communityId,pageId:input.pageId,eventId:input.eventId,title,description:input.description?.trim().slice(0,2000)||undefined,streamKeyHash:createHash('sha256').update(streamKey).digest('hex'),playbackUrl:input.playbackUrl?.trim().slice(0,1000)||undefined,status:'scheduled',viewerCount:0});return {session,streamKey}}
export async function startLiveSession(db:DatabaseAdapter,userId:string,liveId:string){const live=await db.get('socialLiveSessions',liveId);if(!live||live.hostUserId!==userId)throw new Error('LIVE_HOST_REQUIRED');return db.update('socialLiveSessions',liveId,{status:'live',startedAt:new Date().toISOString()})}
export async function endLiveSession(db:DatabaseAdapter,userId:string,liveId:string){const live=await db.get('socialLiveSessions',liveId);if(!live||live.hostUserId!==userId)throw new Error('LIVE_HOST_REQUIRED');return db.update('socialLiveSessions',liveId,{status:'ended',endedAt:new Date().toISOString()})}
export async function listLiveSessions(db:DatabaseAdapter){return (await db.find('socialLiveSessions',x=>x.status==='live'||x.status==='scheduled')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,100)}
export async function sendLiveChat(db:DatabaseAdapter,userId:string,liveId:string,bodyInput:string){const live=await db.get('socialLiveSessions',liveId);if(!live||live.status!=='live')throw new Error('LIVE_NOT_ACTIVE');await assertNotBlocked(db,userId,live.hostUserId);const body=bodyInput.trim().slice(0,1000);if(!body)throw new Error('LIVE_CHAT_REQUIRED');return db.insert('socialLiveChatMessages',{liveSessionId:liveId,userId,body,status:'visible'})}
export async function reactLive(db:DatabaseAdapter,userId:string,liveId:string,kindInput:string){const live=await db.get('socialLiveSessions',liveId);if(!live||live.status!=='live')throw new Error('LIVE_NOT_ACTIVE');const kind=(['like','love','laugh','wow','fire'].includes(kindInput)?kindInput:'like') as 'like'|'love'|'laugh'|'wow'|'fire';return db.insert('socialLiveReactions',{liveSessionId:liveId,userId,kind})}
