import { Ionicons } from "@expo/vector-icons";
import * as ImagePicker from "expo-image-picker";
import { ImageBackground, Modal, Pressable, StyleSheet, Text, View, type ImageSourcePropType } from "react-native";

export type CoverSettings={uri?:string;x:number;y:number;zoom:number};
type Props={visible:boolean;value:CoverSettings;defaultSource?:ImageSourcePropType;onChange:(next:CoverSettings)=>void;onSave:()=>void;onClose:()=>void};
export default function CoverEditorModal({visible,value,defaultSource,onChange,onSave,onClose}:Props){
 const pick=async()=>{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.9});if(!r.canceled)onChange({...value,uri:r.assets[0].uri,x:0,y:0,zoom:1})};
 const nudge=(dx:number,dy:number)=>onChange({...value,x:Math.max(-160,Math.min(160,value.x+dx)),y:Math.max(-100,Math.min(100,value.y+dy))});
 const zoom=(delta:number)=>onChange({...value,zoom:Math.max(1,Math.min(2.2,Number((value.zoom+delta).toFixed(2))))});
 return <Modal transparent visible={visible} animationType="fade" onRequestClose={onClose}><View style={s.backdrop}><View style={s.card}><Text style={s.title}>Adjust cover photo</Text><Text style={s.copy}>Move the photo up, down, left or right and zoom until the cover looks the way you want.</Text><View style={s.preview}>{value.uri||defaultSource?<ImageBackground source={value.uri?{uri:value.uri}:defaultSource} resizeMode="cover" style={s.image} imageStyle={{transform:[{translateX:value.x},{translateY:value.y},{scale:value.zoom}]}}/>:<View style={s.empty}><Ionicons name="image-outline" size={40} color="#7c3aed"/><Text style={s.copy}>Choose a cover photo.</Text></View>}</View><View style={s.controls}><Pressable style={s.ctrl} onPress={()=>nudge(0,-10)}><Ionicons name="arrow-up" size={20}/></Pressable><Pressable style={s.ctrl} onPress={()=>nudge(-10,0)}><Ionicons name="arrow-back" size={20}/></Pressable><Pressable style={s.ctrl} onPress={()=>nudge(10,0)}><Ionicons name="arrow-forward" size={20}/></Pressable><Pressable style={s.ctrl} onPress={()=>nudge(0,10)}><Ionicons name="arrow-down" size={20}/></Pressable><Pressable style={s.ctrl} onPress={()=>zoom(-.1)}><Text style={s.ctrlText}>− Zoom</Text></Pressable><Pressable style={s.ctrl} onPress={()=>zoom(.1)}><Text style={s.ctrlText}>+ Zoom</Text></Pressable></View><Text style={s.status}>Position X {value.x} · Y {value.y} · Zoom {value.zoom.toFixed(1)}×</Text><View style={s.actions}><Pressable style={s.secondary} onPress={()=>void pick()}><Ionicons name="images-outline" size={17} color="#6d28d9"/><Text style={s.secondaryText}>{value.uri?'Replace photo':'Choose photo'}</Text></Pressable><Pressable style={s.secondary} onPress={onClose}><Text style={s.secondaryText}>Cancel</Text></Pressable><Pressable style={s.primary} onPress={onSave}><Text style={s.primaryText}>Save cover</Text></Pressable></View></View></View></Modal>
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:'rgba(15,23,42,.62)',alignItems:'center',justifyContent:'center',padding:20},card:{backgroundColor:'#fff',width:'100%',maxWidth:720,borderRadius:20,padding:20},title:{fontSize:23,fontWeight:'900',color:'#111827'},copy:{color:'#64748b',lineHeight:20,marginTop:5},preview:{height:250,borderRadius:16,overflow:'hidden',backgroundColor:'#ede9fe',marginTop:16},image:{width:'100%',height:'100%'},empty:{flex:1,alignItems:'center',justifyContent:'center'},controls:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:14},ctrl:{borderWidth:1,borderColor:'#ddd6fe',backgroundColor:'#faf5ff',borderRadius:10,paddingHorizontal:12,paddingVertical:9,minWidth:44,alignItems:'center'},ctrlText:{color:'#6d28d9',fontWeight:'800'},status:{fontSize:11,color:'#64748b',marginTop:10},actions:{flexDirection:'row',flexWrap:'wrap',gap:8,justifyContent:'flex-end',marginTop:16},secondary:{borderWidth:1,borderColor:'#ddd6fe',paddingHorizontal:13,paddingVertical:10,borderRadius:10,flexDirection:'row',gap:6,alignItems:'center'},secondaryText:{color:'#6d28d9',fontWeight:'800'},primary:{backgroundColor:'#7c3aed',paddingHorizontal:14,paddingVertical:10,borderRadius:10},primaryText:{color:'#fff',fontWeight:'900'}})
