-- Phase 103: global marketplace, customer entitlements, Yaposan GPU credits, billing ledger, creator earnings/payout accounting.
-- Customer-facing APIs deliberately expose customer charges/credits only; Yaposan company operating expenses are not stored here.
ALTER TABLE space_store_orders ADD COLUMN IF NOT EXISTS provider_checkout_session_id text;
ALTER TABLE space_store_orders ADD COLUMN IF NOT EXISTS provider_payment_intent_id text;
CREATE UNIQUE INDEX IF NOT EXISTS idx_space_store_order_checkout ON space_store_orders(provider_checkout_session_id) WHERE provider_checkout_session_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS marketplace_entitlements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, product_id uuid NOT NULL REFERENCES space_store_products(id) ON DELETE CASCADE, order_id uuid REFERENCES space_store_orders(id) ON DELETE SET NULL, kind text NOT NULL, source text NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,product_id));
CREATE INDEX IF NOT EXISTS idx_marketplace_entitlements_user ON marketplace_entitlements(user_id,updated_at DESC);
CREATE TABLE IF NOT EXISTS gpu_credit_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, credits integer NOT NULL, kind text NOT NULL, pack_id text, amount_cents integer, currency text, provider_event_id text UNIQUE, provider_checkout_session_id text UNIQUE, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_gpu_credit_org_created ON gpu_credit_transactions(organization_id,created_at DESC);
CREATE TABLE IF NOT EXISTS creator_earnings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL UNIQUE REFERENCES space_store_orders(id) ON DELETE CASCADE, space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, product_id uuid NOT NULL REFERENCES space_store_products(id), seller_user_id uuid NOT NULL REFERENCES users(id), gross_cents integer NOT NULL, platform_fee_cents integer NOT NULL, creator_net_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_creator_earnings_seller ON creator_earnings(seller_user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS creator_payouts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), seller_user_id uuid NOT NULL REFERENCES users(id), amount_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', status text NOT NULL DEFAULT 'pending', provider text, provider_payout_id text, note text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_creator_payouts_seller ON creator_payouts(seller_user_id,created_at DESC);
