-- Phase 104: separate Yaposan Admin authorization domain, moderation/audit and admin-only platform cost accounting.
CREATE TABLE IF NOT EXISTS admin_principals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE NOT NULL, password_hash text NOT NULL, role text NOT NULL, status text NOT NULL DEFAULT 'active', last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS admin_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), principal_id uuid NOT NULL REFERENCES admin_principals(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL, revoked_at timestamptz, ip_hash text, user_agent_hash text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_admin_sessions_principal ON admin_sessions(principal_id,expires_at DESC);
CREATE TABLE IF NOT EXISTS admin_audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), principal_id uuid REFERENCES admin_principals(id) ON DELETE SET NULL, action text NOT NULL, target text, request_id text, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_admin_audit_created ON admin_audit_events(created_at DESC);
CREATE TABLE IF NOT EXISTS admin_moderation_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), principal_id uuid NOT NULL REFERENCES admin_principals(id), resource_type text NOT NULL, resource_id text NOT NULL, action text NOT NULL, reason text, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_admin_moderation_resource ON admin_moderation_actions(resource_type,resource_id,created_at DESC);
CREATE TABLE IF NOT EXISTS platform_cost_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), principal_id uuid NOT NULL REFERENCES admin_principals(id), category text NOT NULL, amount_cents integer NOT NULL CHECK(amount_cents >= 0), currency text NOT NULL DEFAULT 'USD', period text, note text, source text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_platform_cost_created ON platform_cost_entries(created_at DESC);
