-- Yaposan 108.0 — AI social media essentials, independently implemented from common OSS patterns.
CREATE TABLE IF NOT EXISTS space_post_reactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,user_id));
CREATE TABLE IF NOT EXISTS space_post_bookmarks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,user_id));
CREATE TABLE IF NOT EXISTS space_post_reposts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,user_id));
CREATE TABLE IF NOT EXISTS space_post_hashtags (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, tag text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,tag));
CREATE INDEX IF NOT EXISTS idx_space_post_hashtags_tag ON space_post_hashtags(space_id,tag,created_at DESC);
CREATE TABLE IF NOT EXISTS social_notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, actor_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL, resource_type text NOT NULL, resource_id text NOT NULL, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_notifications_user ON social_notifications(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS social_conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, created_by_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, title text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS social_conversation_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id uuid NOT NULL REFERENCES social_conversations(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, last_read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(conversation_id,user_id));
CREATE TABLE IF NOT EXISTS social_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, conversation_id uuid NOT NULL REFERENCES social_conversations(id) ON DELETE CASCADE, sender_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_messages_conversation ON social_messages(conversation_id,created_at);
CREATE TABLE IF NOT EXISTS social_blocks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, target_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(space_id,user_id,target_user_id));
CREATE TABLE IF NOT EXISTS social_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, reporter_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, resource_type text NOT NULL, resource_id text NOT NULL, reason text NOT NULL, status text NOT NULL DEFAULT 'open', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_reports_status ON social_reports(space_id,status,created_at DESC);
