-- Yaposan 110.0 — Reels, Stories and Media Platform.
CREATE TABLE IF NOT EXISTS social_media_assets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL, storage_key text NOT NULL UNIQUE, url text, mime_type text NOT NULL, size bigint NOT NULL, caption text, alt_text text, thumbnail_url text, width integer, height integer, duration_ms integer, processing_status text NOT NULL DEFAULT 'uploaded', moderation_status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_media_space ON social_media_assets(space_id,created_at DESC);
CREATE TABLE IF NOT EXISTS social_post_media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, media_asset_id uuid NOT NULL REFERENCES social_media_assets(id) ON DELETE CASCADE, position integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,media_asset_id));
CREATE INDEX IF NOT EXISTS idx_social_post_media_post ON social_post_media(post_id,position);
CREATE TABLE IF NOT EXISTS social_highlights (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, cover_media_asset_id uuid REFERENCES social_media_assets(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS social_stories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, author_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, media_asset_id uuid REFERENCES social_media_assets(id) ON DELETE SET NULL, body text, visibility text NOT NULL DEFAULT 'followers', expires_at timestamptz NOT NULL, highlight_id uuid REFERENCES social_highlights(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_stories_active ON social_stories(expires_at DESC,created_at DESC);
CREATE TABLE IF NOT EXISTS social_story_views (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), story_id uuid NOT NULL REFERENCES social_stories(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, viewed_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(story_id,user_id));
CREATE TABLE IF NOT EXISTS social_reels (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, post_id uuid NOT NULL UNIQUE REFERENCES space_posts(id) ON DELETE CASCADE, author_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, media_asset_id uuid NOT NULL REFERENCES social_media_assets(id) ON DELETE CASCADE, caption text, audio_title text, duration_ms integer, status text NOT NULL DEFAULT 'published', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_reels_created ON social_reels(status,created_at DESC);
