-- Yaposan 111.0 — Communities, Pages, Events and Live.
CREATE TABLE IF NOT EXISTS social_communities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, slug text NOT NULL UNIQUE, description text, visibility text NOT NULL DEFAULT 'public', join_policy text NOT NULL DEFAULT 'open', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_communities_discovery ON social_communities(status,visibility,created_at DESC);
CREATE TABLE IF NOT EXISTS social_community_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), community_id uuid NOT NULL REFERENCES social_communities(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL DEFAULT 'member', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(community_id,user_id));
CREATE INDEX IF NOT EXISTS idx_social_community_members ON social_community_members(community_id,status,role);
CREATE TABLE IF NOT EXISTS social_community_posts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), community_id uuid NOT NULL REFERENCES social_communities(id) ON DELETE CASCADE, post_id uuid NOT NULL UNIQUE REFERENCES space_posts(id) ON DELETE CASCADE, author_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'published', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS social_community_moderation (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), community_id uuid NOT NULL REFERENCES social_communities(id) ON DELETE CASCADE, actor_user_id uuid NOT NULL REFERENCES users(id), target_type text NOT NULL, target_id text NOT NULL, action text NOT NULL, reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS social_pages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL, name text NOT NULL, slug text NOT NULL UNIQUE, bio text, category text, website text, verified boolean NOT NULL DEFAULT false, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_pages_discovery ON social_pages(status,kind,created_at DESC);
CREATE TABLE IF NOT EXISTS social_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id), community_id uuid REFERENCES social_communities(id) ON DELETE SET NULL, page_id uuid REFERENCES social_pages(id) ON DELETE SET NULL, title text NOT NULL, description text, location_type text NOT NULL DEFAULT 'online', location text, starts_at timestamptz NOT NULL, ends_at timestamptz, visibility text NOT NULL DEFAULT 'public', status text NOT NULL DEFAULT 'scheduled', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_events_upcoming ON social_events(status,starts_at);
CREATE TABLE IF NOT EXISTS social_event_rsvps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), event_id uuid NOT NULL REFERENCES social_events(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, response text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(event_id,user_id));
CREATE TABLE IF NOT EXISTS social_live_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, host_user_id uuid NOT NULL REFERENCES users(id), community_id uuid REFERENCES social_communities(id) ON DELETE SET NULL, page_id uuid REFERENCES social_pages(id) ON DELETE SET NULL, event_id uuid REFERENCES social_events(id) ON DELETE SET NULL, title text NOT NULL, description text, stream_key_hash text, playback_url text, status text NOT NULL DEFAULT 'scheduled', started_at timestamptz, ended_at timestamptz, viewer_count integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_live_status ON social_live_sessions(status,created_at DESC);
CREATE TABLE IF NOT EXISTS social_live_chat_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), live_session_id uuid NOT NULL REFERENCES social_live_sessions(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id), body text NOT NULL, status text NOT NULL DEFAULT 'visible', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_live_chat ON social_live_chat_messages(live_session_id,created_at);
CREATE TABLE IF NOT EXISTS social_live_reactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), live_session_id uuid NOT NULL REFERENCES social_live_sessions(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id), kind text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_live_reactions ON social_live_reactions(live_session_id,created_at DESC);
