-- Yaposan 112.0 — AI-native social identities, assistance, discovery and moderation suggestions.
ALTER TABLE space_posts ADD COLUMN IF NOT EXISTS ai_generated boolean NOT NULL DEFAULT false;
ALTER TABLE space_posts ADD COLUMN IF NOT EXISTS ai_agent_id uuid REFERENCES space_ai_agents(id) ON DELETE SET NULL;
ALTER TABLE space_posts ADD COLUMN IF NOT EXISTS ai_disclosure text;
CREATE TABLE IF NOT EXISTS social_ai_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, agent_id uuid NOT NULL UNIQUE REFERENCES space_ai_agents(id) ON DELETE CASCADE, owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, display_name text NOT NULL, handle text NOT NULL UNIQUE, bio text, identity_type text NOT NULL DEFAULT 'ai', disclosure text NOT NULL DEFAULT 'AI agent', autonomous_posting boolean NOT NULL DEFAULT false, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_ai_profiles_discovery ON social_ai_profiles(status,handle);
CREATE TABLE IF NOT EXISTS social_ai_generations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, agent_id uuid REFERENCES space_ai_agents(id) ON DELETE SET NULL, kind text NOT NULL, prompt text NOT NULL, source_text text, output text NOT NULL, provider text, model text, ai_generated boolean NOT NULL DEFAULT true, status text NOT NULL DEFAULT 'completed', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_ai_generations_user ON social_ai_generations(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS social_ai_moderation_suggestions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, reviewer_user_id uuid NOT NULL REFERENCES users(id), resource_type text NOT NULL, resource_id text NOT NULL, risk text NOT NULL, indicators text[] NOT NULL DEFAULT ARRAY[]::text[], status text NOT NULL DEFAULT 'suggested', human_decision text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_social_ai_moderation_review ON social_ai_moderation_suggestions(space_id,status,created_at DESC);
