-- Yaposan 113.0 — creator memberships, tips, paid posts, revenue accounting and analytics.
ALTER TABLE social_communities ADD COLUMN IF NOT EXISTS membership_plan_id uuid;
ALTER TABLE space_posts ADD COLUMN IF NOT EXISTS access_model text NOT NULL DEFAULT 'free';
ALTER TABLE space_posts ADD COLUMN IF NOT EXISTS price_cents integer;
CREATE TABLE IF NOT EXISTS creator_membership_plans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, description text, monthly_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', benefits text[] NOT NULL DEFAULT ARRAY[]::text[], status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_creator_membership_plans ON creator_membership_plans(space_id,status);
CREATE TABLE IF NOT EXISTS creator_membership_subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_id uuid NOT NULL REFERENCES creator_membership_plans(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id), subscriber_user_id uuid NOT NULL REFERENCES users(id), status text NOT NULL DEFAULT 'pending', current_period_end timestamptz, provider_customer_id text, provider_subscription_id text, provider_checkout_session_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(plan_id,subscriber_user_id));
CREATE TABLE IF NOT EXISTS creator_tips (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id), sender_user_id uuid NOT NULL REFERENCES users(id), amount_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', message text, status text NOT NULL DEFAULT 'pending', provider_checkout_session_id text, provider_payment_intent_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS paid_content_access (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), post_id uuid NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE, creator_user_id uuid NOT NULL REFERENCES users(id), buyer_user_id uuid NOT NULL REFERENCES users(id), price_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', status text NOT NULL DEFAULT 'pending', provider_checkout_session_id text, provider_payment_intent_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,buyer_user_id));
CREATE TABLE IF NOT EXISTS creator_revenue_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), creator_user_id uuid NOT NULL REFERENCES users(id), source_type text NOT NULL, source_id text NOT NULL, gross_cents integer NOT NULL, platform_fee_cents integer NOT NULL, creator_net_cents integer NOT NULL, currency text NOT NULL DEFAULT 'USD', status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(source_type,source_id));
CREATE INDEX IF NOT EXISTS idx_creator_revenue_events ON creator_revenue_events(creator_user_id,status,created_at DESC);
