import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {useEffect,useState} from 'react';
import {Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {useAuth} from '../context/AuthContext';
const API_URL=process.env.EXPO_PUBLIC_API_URL ?? (typeof window !== 'undefined'&&!['localhost','127.0.0.1'].includes(window.location.hostname)?'https://api.yaposan.com':'http://localhost:4100');
export default function AccountSecurity(){const auth=useAuth();const [sessions,setSessions]=useState<any[]>([]),[identity,setIdentity]=useState<any>(null),[msg,setMsg]=useState('');const[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[passwordMsg,setPasswordMsg]=useState(''),[showPasswords,setShowPasswords]=useState(false);
 const load=async()=>{const r=await auth.authorizedFetch('/api/v1/security/sessions');if(r.ok)setSessions((await r.json()).items??[]);try{const c=await fetch(`${API_URL}/api/v1/auth/config`);if(c.ok)setIdentity(await c.json())}catch{}};useEffect(()=>{queueMicrotask(()=>{void load()})},[]);
 const changePassword=async()=>{setPasswordMsg('');const r=await auth.authorizedFetch('/api/v1/security/change-password',{method:'POST',body:JSON.stringify({currentPassword,newPassword,confirmPassword})});const b=await r.json();if(!r.ok){setPasswordMsg(b?.error?.message??'Password could not be changed.');return}setCurrentPassword('');setNewPassword('');setConfirmPassword('');setPasswordMsg('Password changed. Existing sessions were revoked; sign in again with the new password.');await auth.signOut()};
 const revoke=async(id:string)=>{const r=await auth.authorizedFetch(`/api/v1/security/sessions/${id}/revoke`,{method:'POST'});if(r.ok){setMsg('Session revoked.');void load()}};const others=async()=>{const r=await auth.authorizedFetch('/api/v1/security/sessions/revoke-others',{method:'POST'});if(r.ok){setMsg('Other sessions revoked.');void load()}};
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.wrap}><Pressable onPress={()=>router.push('/account' as any)}><Text style={s.back}>← Account</Text></Pressable><Text style={s.kicker}>ACCOUNT SECURITY • </Text><Text style={s.title}>Sessions, identity and recovery posture</Text><View style={s.hero}><Ionicons name="shield-checkmark-outline" size={25} color="#166534"/><View style={{flex:1}}><Text style={s.bold}>Recommended production login</Text><Text style={s.meta}>Passkey first → password + authenticator MFA fallback → recovery codes. SMS should not be the primary factor.</Text></View></View>
 <Text style={s.h2}>Identity provider</Text><View style={s.card}><Text style={s.bold}>{identity?.identityProvider==='oidc'?'External OIDC enabled':'Local development identity'}</Text><Text style={s.meta}>{identity?.oidc?.enabled?`Issuer: ${identity.oidc.issuer}`:'Production should configure Keycloak or ZITADEL-compatible OIDC. Local passwords remain a development/test fallback.'}</Text><Text style={s.meta}>PKCE: {identity?.oidc?.pkceRequired?'required':'configure with OIDC'} · Preferred factor: {identity?.recommendedPrimary??'passkey'}</Text></View>
 <Text style={s.h2}>Change Password</Text><View style={s.card}><Text style={s.meta}>Use your current password, then enter and confirm a new strong password. Changing it revokes existing sessions.</Text><View style={s.passwordRow}><TextInput secureTextEntry={!showPasswords} value={currentPassword} onChangeText={setCurrentPassword} placeholder='Current password' style={s.passwordInput}/><Pressable onPress={()=>setShowPasswords(v=>!v)} style={s.eye}><Ionicons name={showPasswords?'eye-off-outline':'eye-outline'} size={20}/></Pressable></View><View style={s.passwordRow}><TextInput secureTextEntry={!showPasswords} value={newPassword} onChangeText={setNewPassword} placeholder='New password' style={s.passwordInput}/><Pressable onPress={()=>setShowPasswords(v=>!v)} style={s.eye}><Ionicons name={showPasswords?'eye-off-outline':'eye-outline'} size={20}/></Pressable></View><View style={s.passwordRow}><TextInput secureTextEntry={!showPasswords} value={confirmPassword} onChangeText={setConfirmPassword} placeholder='Confirm new password' style={s.passwordInput}/><Pressable onPress={()=>setShowPasswords(v=>!v)} style={s.eye}><Ionicons name={showPasswords?'eye-off-outline':'eye-outline'} size={20}/></Pressable></View><Pressable onPress={()=>void changePassword()} style={s.change}><Text style={s.changeText}>Change Password</Text></Pressable>{passwordMsg?<Text style={s.meta}>{passwordMsg}</Text>:null}</View>
 <View style={s.line}><Text style={s.h2}>Active sessions</Text><Pressable onPress={()=>void others()} style={s.danger}><Text style={s.dangerText}>Revoke other sessions</Text></Pressable></View>{sessions.map(x=><View key={x.id} style={s.card}><View style={s.line}><View style={{flex:1}}><Text style={s.bold}>{x.current?'Current session':'Signed-in device'}</Text><Text style={s.meta}>{x.authMethod} · assurance {x.assurance} · last seen {new Date(x.lastSeenAt).toLocaleString()}</Text><Text style={s.meta}>Device {x.deviceFingerprint||'unknown'} · network {x.networkFingerprint||'unknown'}</Text></View>{!x.current&&<Pressable onPress={()=>void revoke(x.id)} style={s.danger}><Text style={s.dangerText}>Revoke</Text></Pressable>}</View></View>)}{!!msg&&<Text style={s.message}>{msg}</Text>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f8fafc'},wrap:{padding:24,maxWidth:900,width:'100%',alignSelf:'center'},back:{color:'#7c3aed',fontWeight:'900',marginBottom:20},kicker:{fontSize:12,fontWeight:'900',letterSpacing:1.3,color:'#0f766e'},title:{fontSize:32,fontWeight:'900',color:'#0f172a',marginTop:6},hero:{flexDirection:'row',gap:12,backgroundColor:'#f0fdf4',borderWidth:1,borderColor:'#bbf7d0',borderRadius:16,padding:16,marginTop:18},h2:{fontSize:20,fontWeight:'900',color:'#0f172a',marginTop:24,marginBottom:9},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0',borderRadius:15,padding:16,marginBottom:9},bold:{fontWeight:'900',color:'#0f172a'},meta:{fontSize:12,color:'#64748b',lineHeight:18,marginTop:4},line:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},danger:{backgroundColor:'#fff1f2',paddingVertical:8,paddingHorizontal:10,borderRadius:10},dangerText:{fontSize:12,fontWeight:'900',color:'#be123c'},message:{color:'#166534',fontWeight:'800',marginTop:12},input:{borderWidth:1,borderColor:'#cbd5e1',borderRadius:10,padding:12,marginTop:10},passwordRow:{borderWidth:1,borderColor:'#cbd5e1',borderRadius:10,marginTop:10,flexDirection:'row',alignItems:'center'},passwordInput:{flex:1,padding:12},eye:{padding:12},change:{backgroundColor:'#0f172a',padding:12,borderRadius:10,alignItems:'center',marginTop:12},changeText:{color:'#fff',fontWeight:'900'}});
