import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { AI_PROVIDERS, DEFAULT_AI_SETTINGS, getProvider, providerStatus, type AIProviderId, type AISettings } from "../ai/providerManager";
import { loadAISettings, loadAIUsage, resetAISettings, saveAISettings, type AIUsageEntry } from "../ai/storage";

export default function AIProviderSettingsPage(){
 const [settings,setSettings]=useState<AISettings>(DEFAULT_AI_SETTINGS); const [usage,setUsage]=useState<AIUsageEntry[]>([]); const [saved,setSaved]=useState("");
 useEffect(()=>{loadAISettings().then(setSettings);loadAIUsage().then(setUsage)},[]);
 const provider=getProvider(settings.provider); const total=useMemo(()=>usage.reduce((n,e)=>n+e.inputTokens+e.outputTokens,0),[usage]);
 const choose=(id:AIProviderId)=>{const next=getProvider(id);setSettings(v=>({...v,provider:id,model:next.models[0]}));setSaved("")};
 const save=async()=>{await saveAISettings(settings);setSaved("AI configuration saved locally.")};
 const reset=async()=>{await resetAISettings();setSettings(DEFAULT_AI_SETTINGS);setSaved("AI configuration reset.")};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <View style={s.top}><Pressable style={s.back} onPress={()=>router.canGoBack() ? router.back() : router.replace("/" as never)}><Ionicons name="arrow-back" size={20} color="#fff"/></Pressable><View><Text style={s.brand}>AI Provider Manager</Text><Text style={s.small}>Phase 24.1G provider architecture, configuration, health, and usage</Text></View></View>
  <View style={s.hero}><View><Text style={s.title}>AI Foundation</Text><Text style={s.sub}>Choose a provider and model. API keys are never embedded in this project; live keys should be stored and called from a secure server in Version 25.</Text></View><Ionicons name="hardware-chip-outline" size={54} color="#c4b5fd"/></View>
  <Text style={s.heading}>Providers</Text><View style={s.grid}>{AI_PROVIDERS.map(p=>{const active=p.id===settings.provider;const status=providerStatus(p);return <Pressable key={p.id} onPress={()=>choose(p.id)} style={[s.card,active&&s.active]}><View style={s.cardTop}><Text style={s.cardTitle}>{p.name}</Text><View style={[s.badge,status!=="ready"&&s.warn]}><Text style={s.badgeText}>{status}</Text></View></View><Text style={s.muted}>{p.capabilities.join(" • ")}</Text><Text style={s.model}>{p.models.join(", ")}</Text></Pressable>})}</View>
  <View style={s.panel}><Text style={s.heading}>Configuration</Text><Text style={s.label}>Model</Text><View style={s.chips}>{provider.models.map(m=><Pressable key={m} onPress={()=>setSettings(v=>({...v,model:m}))} style={[s.chip,settings.model===m&&s.chipActive]}><Text style={[s.chipText,settings.model===m&&s.chipTextActive]}>{m}</Text></Pressable>)}</View><View style={s.row}><Field label="Temperature" value={String(settings.temperature)} onChange={v=>setSettings(x=>({...x,temperature:Number(v)||0}))}/><Field label="Top-P" value={String(settings.topP)} onChange={v=>setSettings(x=>({...x,topP:Number(v)||0}))}/><Field label="Maximum tokens" value={String(settings.maxTokens)} onChange={v=>setSettings(x=>({...x,maxTokens:Number(v)||2048}))}/></View><Toggle label="Streaming responses" value={settings.streaming} onChange={v=>setSettings(x=>({...x,streaming:v}))}/><Toggle label="Use local fallback when provider is unavailable" value={settings.localFallback} onChange={v=>setSettings(x=>({...x,localFallback:v}))}/><View style={s.actions}><Pressable style={s.secondary} onPress={reset}><Text style={s.secondaryText}>Reset</Text></Pressable><Pressable style={s.primary} onPress={save}><Text style={s.primaryText}>Save configuration</Text></Pressable></View>{saved?<Text style={s.success}>{saved}</Text>:null}</View>
  <View style={s.panel}><Text style={s.heading}>Usage dashboard</Text><View style={s.stats}><Stat label="Requests" value={String(usage.length)}/><Stat label="Tokens" value={total.toLocaleString()}/><Stat label="Active provider" value={provider.name}/><Stat label="Status" value={providerStatus(provider)}/></View>{usage.slice(0,6).map((e,i)=><View key={`${e.createdAt}-${i}`} style={s.usage}><Text style={s.usageTitle}>{e.capability} · {e.model}</Text><Text style={s.muted}>{e.inputTokens+e.outputTokens} tokens · {e.durationMs} ms</Text></View>)}{!usage.length?<Text style={s.empty}>Usage will appear after you generate results in an AI workspace.</Text>:null}</View>
 </ScrollView></SafeAreaView>
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <View style={{flex:1}}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType="numeric" style={s.input}/></View>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <View style={s.toggle}><Text style={s.toggleText}>{label}</Text><Switch value={value} onValueChange={onChange}/></View>}
function Stat({label,value}:{label:string;value:string}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.muted}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#eef3f8'},page:{padding:24,gap:17},top:{height:58,backgroundColor:'#102234',borderRadius:14,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:12},back:{width:34,height:34,borderRadius:9,backgroundColor:'#20394f',alignItems:'center',justifyContent:'center'},brand:{color:'#fff',fontWeight:'900',fontSize:16},small:{color:'#9fb1c1',fontSize:10},hero:{backgroundColor:'#241052',borderRadius:18,padding:24,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{color:'#fff',fontSize:31,fontWeight:'900'},sub:{color:'#ddd6fe',maxWidth:800,lineHeight:20,marginTop:7},heading:{fontSize:19,fontWeight:'900',color:'#172033'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{width:280,minHeight:125,backgroundColor:'#fff',borderRadius:15,padding:15,borderWidth:1,borderColor:'#dce5ee'},active:{borderColor:'#7c3aed',borderWidth:2},cardTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},cardTitle:{fontWeight:'900',fontSize:16,color:'#172033'},badge:{backgroundColor:'#dcfce7',borderRadius:20,paddingHorizontal:8,paddingVertical:4},warn:{backgroundColor:'#fef3c7'},badgeText:{fontSize:9,fontWeight:'900',color:'#334155'},muted:{color:'#64748b',fontSize:11,marginTop:6},model:{color:'#7c3aed',fontSize:11,fontWeight:'800',marginTop:9},panel:{backgroundColor:'#fff',borderRadius:16,padding:18,borderWidth:1,borderColor:'#dce5ee',gap:12},label:{fontWeight:'800',color:'#334155',fontSize:12,marginBottom:6},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:12,paddingVertical:8,borderRadius:18,backgroundColor:'#f1f5f9'},chipActive:{backgroundColor:'#7c3aed'},chipText:{fontSize:11,fontWeight:'800',color:'#475569'},chipTextActive:{color:'#fff'},row:{flexDirection:'row',gap:10},input:{height:42,borderWidth:1,borderColor:'#cbd5e1',borderRadius:9,paddingHorizontal:10},toggle:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:5},toggleText:{fontWeight:'700',color:'#334155'},actions:{flexDirection:'row',justifyContent:'flex-end',gap:9},secondary:{paddingHorizontal:15,paddingVertical:10,borderRadius:9,backgroundColor:'#f1f5f9'},secondaryText:{fontWeight:'900',color:'#475569'},primary:{paddingHorizontal:16,paddingVertical:10,borderRadius:9,backgroundColor:'#7c3aed'},primaryText:{color:'#fff',fontWeight:'900'},success:{color:'#15803d',fontWeight:'800'},stats:{flexDirection:'row',flexWrap:'wrap',gap:10},stat:{minWidth:160,backgroundColor:'#f8fafc',borderRadius:12,padding:13},statValue:{fontSize:18,fontWeight:'900',color:'#172033'},usage:{borderTopWidth:1,borderTopColor:'#eef2f7',paddingTop:10},usageTitle:{fontWeight:'800',color:'#334155'},empty:{color:'#94a3b8',paddingVertical:8}})
