import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { AI_PROVIDERS, DEFAULT_AI_SETTINGS, getProvider, providerStatus, type AIProviderId, type AISettings } from "../ai/providerManager";
import { loadAISettings, loadAIUsage, resetAISettings, saveAISettings, type AIUsageEntry } from "../ai/storage";
import { useAuth } from "../context/AuthContext";

const endpoints:Partial<Record<AIProviderId,string>>={openai:"https://api.openai.com/v1/chat/completions",gemini:"https://generativelanguage.googleapis.com/v1beta/models",claude:"https://api.anthropic.com/v1/messages",ollama:"http://127.0.0.1:11434/v1/chat/completions",lmstudio:"http://127.0.0.1:1234/v1/chat/completions"};
type Connected={provider:string;endpoint?:string;model?:string;keyLast4?:string};
export default function AIProviderSettingsPage(){
 const auth=useAuth();const [settings,setSettings]=useState<AISettings>(DEFAULT_AI_SETTINGS);const [usage,setUsage]=useState<AIUsageEntry[]>([]);const [saved,setSaved]=useState("");const [apiKey,setApiKey]=useState("");const [endpoint,setEndpoint]=useState("");const [connected,setConnected]=useState<Connected[]>([]);
 const loadConnections=async()=>{if(!auth.isAuthenticated)return;const r=await auth.authorizedFetch("/api/v1/ai/providers/credentials");if(r.ok)setConnected((await r.json()).items??[])};
 useEffect(()=>{
  let cancelled=false;
  void loadAISettings().then(x=>{if(cancelled)return;setSettings(x);setEndpoint(endpoints[x.provider]??"")});
  void loadAIUsage().then(entries=>{if(!cancelled)setUsage(entries)});
  if(auth.isAuthenticated){
   void auth.authorizedFetch("/api/v1/ai/providers/credentials").then(async r=>{if(!r.ok||cancelled)return;const body=await r.json();if(!cancelled)setConnected(body.items??[])});
  } else {
   queueMicrotask(()=>{if(!cancelled)setConnected([])});
  }
  return()=>{cancelled=true};
 },[auth.isAuthenticated,auth.authorizedFetch]);
 const provider=getProvider(settings.provider);const total=useMemo(()=>usage.reduce((n,e)=>n+e.inputTokens+e.outputTokens,0),[usage]);const connection=connected.find(x=>x.provider===settings.provider);
 const choose=(id:AIProviderId)=>{const next=getProvider(id);setSettings(v=>({...v,provider:id,model:next.models[0]}));setEndpoint(endpoints[id]??"");setApiKey("");setSaved("")};
 const save=async()=>{await saveAISettings(settings);setSaved("AI preferences saved locally.")};
 const connect=async()=>{if(settings.provider==="local")return Alert.alert("Local AI","Yaposan Local does not need a cloud credential.");if(!auth.isAuthenticated)return Alert.alert("Sign in required","Sign in to store provider credentials securely for your workspace.");const r=await auth.authorizedFetch("/api/v1/ai/providers/credentials",{method:"PUT",body:JSON.stringify({provider:settings.provider,apiKey,endpoint,model:settings.model})});const d=await r.json();if(!r.ok)return Alert.alert("Could not connect provider",d?.error?.message??"Request failed");setApiKey("");await loadConnections();setSaved("Provider credential encrypted and saved server-side.")};
 const disconnect=async()=>{if(!connection)return;const r=await auth.authorizedFetch(`/api/v1/ai/providers/credentials/${encodeURIComponent(settings.provider)}`,{method:"DELETE"});if(r.ok){await loadConnections();setSaved("Provider disconnected.")}};
 const reset=async()=>{await resetAISettings();setSettings(DEFAULT_AI_SETTINGS);setEndpoint("");setApiKey("");setSaved("AI configuration reset.")};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <View style={s.top}><Pressable style={s.back} onPress={()=>router.canGoBack()?router.back():router.replace("/" as never)}><Ionicons name="arrow-back" size={20} color="#fff"/></Pressable><View><Text style={s.brand}>AI Provider Manager</Text><Text style={s.small}>Phase 90.7 secure BYO-provider connection and AI cost controls</Text></View></View>
  <View style={s.hero}><View><Text style={s.title}>Connect your AI</Text><Text style={s.sub}>Yaposan stays free. Connect your own provider and pay that provider directly. Cloud API keys are encrypted server-side with AES-256-GCM and are never written to source files or returned by the listing API.</Text></View><Ionicons name="shield-checkmark-outline" size={54} color="#c4b5fd"/></View>
  <Text style={s.heading}>Providers</Text><View style={s.grid}>{AI_PROVIDERS.map(p=>{const active=p.id===settings.provider;const linked=connected.some(x=>x.provider===p.id);const status=p.id==="local"||linked?"ready":providerStatus(p);return <Pressable key={p.id} onPress={()=>choose(p.id)} style={[s.card,active&&s.active]}><View style={s.cardTop}><Text style={s.cardTitle}>{p.name}</Text><View style={[s.badge,status!=="ready"&&s.warn]}><Text style={s.badgeText}>{linked?"connected":status}</Text></View></View><Text style={s.muted}>{p.capabilities.join(" • ")}</Text><Text style={s.model}>{p.models.join(", ")}</Text></Pressable>})}</View>
  {settings.provider!=="local"?<View style={s.panel}><Text style={s.heading}>Secure provider connection</Text><Text style={s.muted}>{connection?`Connected · key ending ${connection.keyLast4||"(local/no key)"}`:"Not connected"}</Text><Text style={s.label}>API endpoint</Text><TextInput value={endpoint} onChangeText={setEndpoint} autoCapitalize="none" style={s.input}/><Text style={s.label}>API key {provider.requiresApiKey?"":"(optional for local servers)"}</Text><TextInput value={apiKey} onChangeText={setApiKey} secureTextEntry autoCapitalize="none" autoCorrect={false} placeholder={connection?"Enter a new key only to replace it":"Provider API key"} style={s.input}/><View style={s.actions}>{connection?<Pressable style={s.secondary} onPress={disconnect}><Text style={s.secondaryText}>Disconnect</Text></Pressable>:null}<Pressable style={s.primary} onPress={connect}><Text style={s.primaryText}>{connection?"Update connection":"Connect securely"}</Text></Pressable></View><Text style={s.muted}>OpenAI, Ollama, LM Studio and custom OpenAI-compatible endpoints use the chat-completions protocol. Gemini and Anthropic use their provider-specific request formats.</Text></View>:null}
  <View style={s.panel}><Text style={s.heading}>Generation preferences</Text><Text style={s.label}>Model</Text><View style={s.chips}>{provider.models.map(m=><Pressable key={m} onPress={()=>setSettings(v=>({...v,model:m}))} style={[s.chip,settings.model===m&&s.chipActive]}><Text style={[s.chipText,settings.model===m&&s.chipTextActive]}>{m}</Text></Pressable>)}</View><View style={s.row}><Field label="Temperature" value={String(settings.temperature)} onChange={v=>setSettings(x=>({...x,temperature:Number(v)||0}))}/><Field label="Top-P" value={String(settings.topP)} onChange={v=>setSettings(x=>({...x,topP:Number(v)||0}))}/><Field label="Maximum tokens" value={String(settings.maxTokens)} onChange={v=>setSettings(x=>({...x,maxTokens:Number(v)||2048}))}/></View><Toggle label="Streaming responses" value={settings.streaming} onChange={v=>setSettings(x=>({...x,streaming:v}))}/><Toggle label="Use local fallback when provider is unavailable" value={settings.localFallback} onChange={v=>setSettings(x=>({...x,localFallback:v}))}/><View style={s.actions}><Pressable style={s.secondary} onPress={reset}><Text style={s.secondaryText}>Reset</Text></Pressable><Pressable style={s.primary} onPress={save}><Text style={s.primaryText}>Save preferences</Text></Pressable></View>{saved?<Text style={s.success}>{saved}</Text>:null}</View>
  <View style={s.panel}><Text style={s.heading}>Usage dashboard</Text><View style={s.stats}><Stat label="Requests" value={String(usage.length)}/><Stat label="Tokens" value={total.toLocaleString()}/><Stat label="Active provider" value={provider.name}/><Stat label="Connection" value={settings.provider==="local"?"Local":connection?"Connected":"Not connected"}/></View>{usage.slice(0,6).map((e,i)=><View key={`${e.createdAt}-${i}`} style={s.usage}><Text style={s.usageTitle}>{e.capability} · {e.model}</Text><Text style={s.muted}>{e.inputTokens+e.outputTokens} tokens · {e.durationMs} ms</Text></View>)}{!usage.length?<Text style={s.empty}>Usage will appear after you generate results in an AI workspace.</Text>:null}</View>
 </ScrollView></SafeAreaView>
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <View style={{flex:1}}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType="numeric" style={s.input}/></View>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <View style={s.toggle}><Text style={s.toggleText}>{label}</Text><Switch value={value} onValueChange={onChange}/></View>}
function Stat({label,value}:{label:string;value:string}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.muted}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#eef3f8'},page:{padding:24,gap:17},top:{height:58,backgroundColor:'#102234',borderRadius:14,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:12},back:{width:34,height:34,borderRadius:9,backgroundColor:'#20394f',alignItems:'center',justifyContent:'center'},brand:{color:'#fff',fontWeight:'900',fontSize:16},small:{color:'#9fb1c1',fontSize:10},hero:{backgroundColor:'#241052',borderRadius:18,padding:24,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{color:'#fff',fontSize:31,fontWeight:'900'},sub:{color:'#ddd6fe',maxWidth:800,lineHeight:20,marginTop:7},heading:{fontSize:19,fontWeight:'900',color:'#172033'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{width:280,minHeight:125,backgroundColor:'#fff',borderRadius:15,padding:15,borderWidth:1,borderColor:'#dce5ee'},active:{borderColor:'#7c3aed',borderWidth:2},cardTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},cardTitle:{fontWeight:'900',fontSize:16,color:'#172033'},badge:{backgroundColor:'#dcfce7',borderRadius:20,paddingHorizontal:8,paddingVertical:4},warn:{backgroundColor:'#fef3c7'},badgeText:{fontSize:9,fontWeight:'900',color:'#334155'},muted:{color:'#64748b',fontSize:11,marginTop:6},model:{color:'#7c3aed',fontSize:11,fontWeight:'800',marginTop:9},panel:{backgroundColor:'#fff',borderRadius:16,padding:18,borderWidth:1,borderColor:'#dce5ee',gap:12},label:{fontWeight:'800',color:'#334155',fontSize:12,marginBottom:6},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:12,paddingVertical:8,borderRadius:18,backgroundColor:'#f1f5f9'},chipActive:{backgroundColor:'#7c3aed'},chipText:{fontSize:11,fontWeight:'800',color:'#475569'},chipTextActive:{color:'#fff'},row:{flexDirection:'row',gap:10},input:{height:42,borderWidth:1,borderColor:'#cbd5e1',borderRadius:9,paddingHorizontal:10},toggle:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:5},toggleText:{fontWeight:'700',color:'#334155'},actions:{flexDirection:'row',justifyContent:'flex-end',gap:9},secondary:{paddingHorizontal:15,paddingVertical:10,borderRadius:9,backgroundColor:'#f1f5f9'},secondaryText:{fontWeight:'900',color:'#475569'},primary:{paddingHorizontal:16,paddingVertical:10,borderRadius:9,backgroundColor:'#7c3aed'},primaryText:{color:'#fff',fontWeight:'900'},success:{color:'#15803d',fontWeight:'800'},stats:{flexDirection:'row',flexWrap:'wrap',gap:10},stat:{minWidth:160,backgroundColor:'#f8fafc',borderRadius:12,padding:13},statValue:{fontSize:18,fontWeight:'900',color:'#172033'},usage:{borderTopWidth:1,borderTopColor:'#eef2f7',paddingTop:10},usageTitle:{fontWeight:'800',color:'#334155'},empty:{color:'#94a3b8',paddingVertical:8}})
