import AsyncStorage from "@react-native-async-storage/async-storage";
import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { generateWithProvider } from "../ai/providerManager";
import { addAIUsage, loadAISettings } from "../ai/storage";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

const META: Record<string,{title:string;icon:keyof typeof Ionicons.glyphMap;description:string;output:string;destination:string;route:string}> = {
 writer:{title:"AI Writer",icon:"create-outline",description:"Draft, rewrite, summarize, translate, and polish publication copy.",output:"publication copy",destination:"Publisher",route:"/editor"},
 image:{title:"Generate Image",icon:"image-outline",description:"Prepare production-ready prompts for artwork, backgrounds, and campaign imagery.",output:"image production brief",destination:"Image Editor",route:"/image-editor"},
 design:{title:"Design Generator",icon:"color-wand-outline",description:"Create structured concepts for flyers, posters, brochures, menus, and social layouts.",output:"design specification",destination:"Publisher",route:"/editor"},
 product:{title:"Product Studio",icon:"camera-outline",description:"Plan background removal, relighting, upscaling, shadows, and marketplace scenes.",output:"product-photo workflow",destination:"Photo Studio",route:"/photo-studio"},
 document:{title:"Document Assistant",icon:"document-text-outline",description:"Review content, accessibility, layout consistency, and preflight readiness.",output:"document review",destination:"Diagnostics",route:"/project-diagnostics"},
 brand:{title:"Brand Assistant",icon:"diamond-outline",description:"Develop brand-aligned copy, palettes, typography direction, and campaign ideas.",output:"brand direction",destination:"Brand Kit",route:"/brand"},
};
export default function AIWorkspace(){
 const {tool="writer"}=useLocalSearchParams<{tool?:string}>(); const meta=META[tool]??META.writer; const key=`yaposan:ai-workspace:${tool}`;
 const [prompt,setPrompt]=useState(""); const [tone,setTone]=useState("Professional"); const [audience,setAudience]=useState("General audience"); const [result,setResult]=useState(""); const [history,setHistory]=useState<string[]>([]);
 useEffect(()=>{AsyncStorage.getItem(key).then(raw=>{if(!raw)return;try{const v=JSON.parse(raw);setHistory(v.history??[]);setPrompt(v.prompt??"");setTone(v.tone??"Professional");setAudience(v.audience??"General audience");}catch{}})},[key]);
 useEffect(()=>{AsyncStorage.setItem(key,JSON.stringify({history,prompt,tone,audience}))},[key,history,prompt,tone,audience]);
 const ready=prompt.trim().length>3;
 const generate=async()=>{if(!ready)return;const settings=await loadAISettings();const generated=await generateWithProvider({capability:(tool === "writer" ? "text" : tool) as any,prompt:prompt.trim(),audience,tone},settings);setResult(generated.text);setHistory(v=>[prompt.trim(),...v.filter(x=>x!==prompt.trim())].slice(0,10));await addAIUsage({...generated,capability:meta.title});};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><View style={s.top}><Pressable style={s.back} onPress={()=>router.canGoBack() ? router.back() : router.replace("/" as never)}><Ionicons name="arrow-back" size={20} color="#fff"/></Pressable><View><Text style={s.brand}>{meta.title}</Text><Text style={s.small}>provider-ready workspace</Text></View></View><View style={s.hero}><View style={s.heroIcon}><Ionicons name={meta.icon} size={30} color="#7c3aed"/></View><View style={{flex:1}}><Text style={s.title}>{meta.title}</Text><Text style={s.sub}>{meta.description}</Text></View></View><View style={s.panel}><Text style={s.label}>What should Yaposan create or analyze?</Text><TextInput multiline value={prompt} onChangeText={setPrompt} style={s.area} placeholder="Describe the goal, content, format, and important requirements..."/><View style={s.row}><Field label="Tone" value={tone} set={setTone}/><Field label="Audience" value={audience} set={setAudience}/></View><View style={s.actions}><Pressable style={s.secondary} onPress={()=>{setPrompt("");setResult("")}}><Text style={s.secondaryText}>Clear</Text></Pressable><Pressable disabled={!ready} style={[s.primary,!ready&&s.disabled]} onPress={generate}><Ionicons name="sparkles" size={17} color="#fff"/><Text style={s.primaryText}>Create result</Text></Pressable></View></View>{result?<View style={s.panel}><Text style={s.heading}>Result</Text><Text style={s.result}>{result}</Text><Pressable style={s.destination} onPress={()=>router.push(meta.route as never)}><Text style={s.destinationText}>Open in {meta.destination}</Text><Ionicons name="arrow-forward" size={16} color="#fff"/></Pressable></View>:null}<View style={s.panel}><Text style={s.heading}>Recent work</Text>{history.length?history.map((item,i)=><Pressable key={`${item}-${i}`} style={s.history} onPress={()=>setPrompt(item)}><Ionicons name="time-outline" size={17} color="#7c3aed"/><Text numberOfLines={1} style={{flex:1}}>{item}</Text></Pressable>):<Text style={s.empty}>No saved prompts yet.</Text>}</View></ScrollView></SafeAreaView>
}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <View style={{flex:1}}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} style={s.input}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#eef3f8"},page:{padding:24,gap:16},top:{height:58,backgroundColor:"#102234",borderRadius:14,paddingHorizontal:15,flexDirection:"row",alignItems:"center",gap:12},back:{width:34,height:34,borderRadius:9,backgroundColor:"#20394f",alignItems:"center",justifyContent:"center"},brand:{color:"#fff",fontWeight:"900",fontSize:16},small:{color:"#9fb1c1",fontSize:10},hero:{backgroundColor:"#241052",borderRadius:18,padding:22,flexDirection:"row",gap:15,alignItems:"center"},heroIcon:{width:58,height:58,borderRadius:16,backgroundColor:"#f3e8ff",alignItems:"center",justifyContent:"center"},title:{color:"#fff",fontSize:30,fontWeight:"900"},sub:{color:"#ddd6fe",marginTop:5,lineHeight:20},panel:{backgroundColor:"#fff",borderRadius:16,padding:18,borderWidth:1,borderColor:"#dce5ee",gap:12},label:{fontWeight:"800",color:"#334155",fontSize:12,marginBottom:6},area:{minHeight:130,borderWidth:1,borderColor:"#cbd5e1",borderRadius:11,padding:12,textAlignVertical:"top",outlineStyle:"none" as never},row:{flexDirection:"row",gap:12},input:{height:44,borderWidth:1,borderColor:"#cbd5e1",borderRadius:9,paddingHorizontal:12},actions:{flexDirection:"row",justifyContent:"flex-end",gap:9},secondary:{paddingHorizontal:15,paddingVertical:10,borderRadius:9,backgroundColor:"#f1f5f9"},secondaryText:{fontWeight:"900",color:"#475569"},primary:{paddingHorizontal:16,paddingVertical:10,borderRadius:9,backgroundColor:"#7c3aed",flexDirection:"row",alignItems:"center",gap:7},disabled:{opacity:.4},primaryText:{color:"#fff",fontWeight:"900"},heading:{fontSize:18,fontWeight:"900",color:"#172033"},result:{color:"#475569",lineHeight:21},destination:{alignSelf:"flex-start",backgroundColor:"#7c3aed",borderRadius:9,paddingHorizontal:15,paddingVertical:10,flexDirection:"row",gap:8,alignItems:"center"},destinationText:{color:"#fff",fontWeight:"900"},history:{height:42,borderRadius:9,backgroundColor:"#f8fafc",paddingHorizontal:11,flexDirection:"row",alignItems:"center",gap:8},empty:{color:"#94a3b8"}})
