import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { createAppProjectDraft } from "../services/phase9110CreationPlatform";
import { loadCreationProject } from "../services/creationProjectStore";
import { saveAppProject } from "../services/phase9112AppStore";
export default function AppStudio(){const params=useLocalSearchParams<{prompt?:string;creationProject?:string|string[]}>();const [prompt,setPrompt]=useState(typeof params.prompt==="string"?params.prompt:"");const [draft,setDraft]=useState<ReturnType<typeof createAppProjectDraft>|null>(null);const creationId=Array.isArray(params.creationProject)?params.creationProject[0]:params.creationProject;useEffect(()=>{if(!creationId)return;void loadCreationProject(creationId).then(source=>{if(!source)return;setPrompt(source.sourcePrompt);setDraft(createAppProjectDraft(source.sourcePrompt));});},[creationId]);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><View style={s.top}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={20} color="#fff"/></Pressable><View><Text style={s.brand}>App Studio</Text><Text style={s.sub}>Phase 91.12 persistent AI app project</Text></View></View><View style={s.panel}><Text style={s.title}>What app will you create?</Text><TextInput multiline value={prompt} onChangeText={setPrompt} placeholder="Create an inventory management app for a small warehouse..." style={s.input}/><Pressable disabled={!prompt.trim()} style={[s.button,!prompt.trim()&&{opacity:.4}]} onPress={()=>setDraft(createAppProjectDraft(prompt))}><Text style={s.buttonText}>Create editable app draft</Text></Pressable></View>{draft?<View style={s.panel}><Text style={s.heading}>{draft.name}</Text><Text style={s.label}>Screens</Text>{draft.screens.map(x=><Text key={x} style={s.item}>✓ {x}</Text>)}<Text style={s.label}>Data model</Text>{draft.dataEntities.map(x=><Text key={x.name} style={s.item}>✓ {x.name}: {x.fields.join(", ")}</Text>)}<Text style={s.label}>Authentication</Text><Text style={s.item}>✓ Roles: {draft.auth.roles.join(", ")}</Text><Text style={s.label}>Workflows</Text>{draft.workflows.map(x=><Text key={x} style={s.item}>✓ {x}</Text>)}<Text style={s.label}>Integrations & deployment</Text>{[...draft.integrations,...draft.deployment].map(x=><Text key={x} style={s.item}>✓ {x}</Text>)}<Text style={s.label}>Foundation</Text>{draft.features.map(x=><Text key={x} style={s.item}>✓ {x}</Text>)}<Pressable style={s.button} onPress={()=>void saveAppProject(draft)}><Text style={s.buttonText}>Save runnable app specification</Text></Pressable></View>:null}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#eef3f8"},page:{padding:24,gap:16},top:{backgroundColor:"#102234",borderRadius:14,padding:18,flexDirection:"row",gap:12,alignItems:"center"},brand:{color:"#fff",fontWeight:"900",fontSize:18},sub:{color:"#9fb1c1",fontSize:11},panel:{backgroundColor:"#fff",borderRadius:16,padding:20,borderWidth:1,borderColor:"#dce5ee",gap:12},title:{fontSize:30,fontWeight:"900",color:"#172033"},heading:{fontSize:20,fontWeight:"900",color:"#172033"},label:{fontWeight:"900",color:"#475569",marginTop:8},input:{minHeight:120,borderWidth:1,borderColor:"#cbd5e1",borderRadius:12,padding:12,textAlignVertical:"top"},button:{alignSelf:"flex-start",backgroundColor:"#7c3aed",paddingHorizontal:16,paddingVertical:11,borderRadius:10},buttonText:{color:"#fff",fontWeight:"900"},item:{color:"#475569"}});
