import { Ionicons } from "@expo/vector-icons";
import { Link } from "expo-router";
import React, { useEffect, useMemo, useRef, useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import type { CommerceStudioState } from "../types/commerceStudio";
import { applyJobResult, calculateCommerceMetrics, createBatchJob, createCommerceState, runBatchJob } from "../utils/commerceStudioEngine";
import { loadCommerceState, saveCommerceState } from "../utils/commerceStudioStorage";

function Btn({ label, icon, onPress, disabled }: { label: string; icon: keyof typeof Ionicons.glyphMap; onPress: () => void; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.btn, disabled && styles.disabled, pressed && !disabled && styles.btnPressed]}><Ionicons name={icon} size={16} color="#17324d"/><Text style={styles.btnText}>{label}</Text></Pressable>; }
export default function AutomationScreen() {
  const [state, setState] = useState<CommerceStudioState>(createCommerceState()); const [running, setRunning] = useState(false); const [progress, setProgress] = useState(0); const abortRef = useRef<AbortController | null>(null);
  useEffect(() => { loadCommerceState().then(setState); }, []); useEffect(() => { saveCommerceState(state); }, [state]);
  const ready = useMemo(() => state.listings.filter((item) => item.status === "ready" || item.status === "failed"), [state]); const metrics = useMemo(() => calculateCommerceMetrics(state), [state]);
  async function run() { if (!ready.length || running) return; const job = createBatchJob(ready); setState((current) => ({ ...current, jobs: [{ ...job, status: "running" }, ...current.jobs] })); setRunning(true); setProgress(0); const controller = new AbortController(); abortRef.current = controller; const completed = await runBatchJob({ ...job, status: "running" }, ready, setProgress, controller.signal); setState((current) => applyJobResult(current, completed)); setRunning(false); abortRef.current = null; }
  return <SafeAreaView style={styles.safe}><View style={styles.topbar}><Link href="/marketplace" asChild><Pressable><Text style={styles.back}>‹ Commerce Studio</Text></Pressable></Link><View><Text style={styles.title}>Commerce Automation</Text><Text style={styles.sub}>Batch listing queue, validation, progress, results, and analytics</Text></View></View><ScrollView contentContainerStyle={styles.page}><View style={styles.metrics}><View style={styles.metric}><Text style={styles.metricValue}>{ready.length}</Text><Text style={styles.metricLabel}>Ready to publish</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{metrics.publishedListings}</Text><Text style={styles.metricLabel}>Published</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{state.jobs.length}</Text><Text style={styles.metricLabel}>Batch jobs</Text></View></View><View style={styles.panel}><Text style={styles.panelTitle}>Batch publishing</Text><Text style={styles.copy}>Validate all ready listings, publish them to selected channels, track individual results, and resume failed products.</Text><View style={styles.row}><Btn label={running ? `Publishing ${progress}%` : "Publish ready listings"} icon="rocket-outline" disabled={!ready.length || running} onPress={run}/>{running && <Btn label="Cancel" icon="close-circle-outline" onPress={() => abortRef.current?.abort()}/>}</View>{running && <View style={styles.progressTrack}><View style={[styles.progressBar,{width:`${progress}%`}]} /></View>}</View><View style={styles.panel}><Text style={styles.panelTitle}>Automation history</Text>{state.jobs.length ? state.jobs.map((job) => <View key={job.id} style={styles.job}><View style={styles.flex}><Text style={styles.jobTitle}>{job.channels.join(", ").toUpperCase() || "No channels"}</Text><Text style={styles.jobMeta}>{job.listingIds.length} listings · {job.results.filter((item) => item.success).length} successful · {job.results.filter((item) => !item.success).length} failed</Text></View><Text style={styles.status}>{job.status} · {job.progress}%</Text></View>) : <View style={styles.emptyState}><Ionicons name="albums-outline" size={28} color="#7b91a6"/><Text style={styles.empty}>No automation jobs yet.</Text><Text style={styles.emptyHint}>Create or import listings in Commerce Studio, mark them Ready, then return here to publish them in a batch.</Text><Link href="/marketplace" asChild><Pressable style={styles.emptyButton}><Text style={styles.emptyButtonText}>Open Commerce Studio</Text></Pressable></Link></View>}</View><View style={styles.panel}><Text style={styles.panelTitle}>Channel analytics</Text>{Object.entries(metrics.channelCounts).map(([channel,count]) => <View key={channel} style={styles.analyticsRow}><Text style={styles.analyticsName}>{channel.toUpperCase()}</Text><Text style={styles.analyticsValue}>{count} listings</Text></View>)}</View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#e8f0f6"},topbar:{backgroundColor:"#102235",borderBottomWidth:5,borderBottomColor:"#07131f",padding:16,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},back:{color:"#dcecff",fontWeight:"800"},title:{color:"#fff",fontSize:22,fontWeight:"900"},sub:{color:"#9fc0dc",fontSize:11,marginTop:3},page:{padding:16,gap:16},metrics:{flexDirection:"row",flexWrap:"wrap",gap:12},metric:{flex:1,minWidth:160,backgroundColor:"#fff",borderRadius:16,padding:16,borderWidth:1,borderColor:"#cfdae4",borderBottomWidth:4,borderBottomColor:"#93a9bb"},metricValue:{fontSize:26,fontWeight:"900",color:"#17324d"},metricLabel:{color:"#71869a",fontWeight:"800"},panel:{backgroundColor:"#f8fbfd",borderRadius:18,padding:16,borderWidth:1,borderColor:"#cfdae4"},panelTitle:{fontSize:17,fontWeight:"900",color:"#183149",marginBottom:10},copy:{color:"#61798d",lineHeight:20,marginBottom:12},row:{flexDirection:"row",gap:8,flexWrap:"wrap"},btn:{flexDirection:"row",alignItems:"center",gap:6,backgroundColor:"#fff",borderWidth:1,borderColor:"#bfd0df",borderRadius:10,padding:11,borderBottomWidth:4,borderBottomColor:"#93a9bb"},btnPressed:{transform:[{translateY:3}],borderBottomWidth:1},btnText:{color:"#17324d",fontWeight:"900"},disabled:{opacity:.4},progressTrack:{height:10,backgroundColor:"#dce6ee",borderRadius:999,overflow:"hidden",marginTop:12},progressBar:{height:"100%",backgroundColor:"#1d4ed8"},job:{flexDirection:"row",alignItems:"center",gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:"#dbe5ed"},flex:{flex:1},jobTitle:{fontWeight:"900",color:"#17324d"},jobMeta:{fontSize:12,color:"#71869a",marginTop:4},status:{fontWeight:"900",fontSize:11,color:"#38556e"},empty:{color:"#71869a",textAlign:"center",fontWeight:"800"},emptyState:{alignItems:"center",justifyContent:"center",padding:28,gap:8},emptyHint:{color:"#6b8298",textAlign:"center",maxWidth:520,lineHeight:19},emptyButton:{marginTop:6,backgroundColor:"#dcecff",paddingHorizontal:16,paddingVertical:10,borderRadius:10},emptyButtonText:{color:"#17324d",fontWeight:"900"},analyticsRow:{flexDirection:"row",justifyContent:"space-between",paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#dbe5ed"},analyticsName:{fontWeight:"900",color:"#17324d"},analyticsValue:{color:"#61798d",fontWeight:"800"}});
