import AsyncStorage from "@react-native-async-storage/async-storage";
import { useEffect,useMemo,useState } from "react";
import { Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { useRouter } from "expo-router";
import { Evidence,PHASE41_CONTROLS,Phase41Control,certifyPhase41,phase41Score } from "../utils/phase41BackendCompletionEngine";
const KEY="yaposan.phase41.evidence";
let evidenceSequence=0;
const nextEvidenceToken=()=>`evidence-${++evidenceSequence}`;
export default function BackendCompletion(){const router=useRouter();const [evidence,setEvidence]=useState<Evidence[]>([]);const [filter,setFilter]=useState("");useEffect(()=>{AsyncStorage.getItem(KEY).then(v=>v&&setEvidence(JSON.parse(v))).catch(()=>{})},[]);const save=(next:Evidence[])=>{setEvidence(next);void AsyncStorage.setItem(KEY,JSON.stringify(next))};const controls=useMemo(()=>PHASE41_CONTROLS.filter(c=>(c.area+" "+c.title).toLowerCase().includes(filter.toLowerCase())),[filter]);const result=certifyPhase41(PHASE41_CONTROLS,evidence);const addEvidence=(c:Phase41Control,kind:Evidence["kind"])=>{const token=nextEvidenceToken();const value=`${kind}-${token}`;save([...evidence,{id:`ev-${token}`,controlId:c.id,kind,value,verified:false}])};return <ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.title}>Phase 41 — Backend Completion</Text><Text style={s.sub}>Evidence-backed backend, cloud, identity, billing, AI, jobs and operations foundation.</Text></View><View style={s.metrics}><View style={s.metric}><Text style={s.num}>{phase41Score(PHASE41_CONTROLS,evidence)}%</Text><Text style={s.label}>Readiness</Text></View><View style={s.metric}><Text style={s.num}>{evidence.filter(x=>x.verified).length}</Text><Text style={s.label}>Verified evidence</Text></View><View style={s.metric}><Text style={s.num}>{result.blockers.length}</Text><Text style={s.label}>Release blockers</Text></View></View><TextInput style={s.search} value={filter} onChangeText={setFilter} placeholder="Search controls" placeholderTextColor="#64748b"/>{controls.map(c=><View key={c.id} style={s.card}><View style={s.row}><Text style={s.id}>{c.id}</Text><Text style={s.area}>{c.area}</Text><Text style={s.status}>{c.status}</Text></View><Text style={s.cardTitle}>{c.title}</Text><Text style={s.req}>Required evidence: {c.requiredEvidence.join(", ")}</Text><View style={s.actions}>{c.requiredEvidence.map(k=><Pressable key={k} style={s.button} onPress={()=>addEvidence(c,k)}><Text style={s.buttonText}>Attach {k}</Text></Pressable>)}</View>{evidence.filter(x=>x.controlId===c.id).map(x=><Pressable key={x.id} style={s.evidence} onPress={()=>save(evidence.map(e=>e.id===x.id?{...e,verified:!e.verified,verifiedAt:!e.verified?new Date().toISOString():undefined,verifiedBy:!e.verified?"Release reviewer":undefined}:e))}><Text style={s.evidenceText}>{x.verified?"✓":"○"} {x.kind}: {x.value}</Text></Pressable>)}</View>)}<View style={s.cert}><Text style={s.certTitle}>{result.certified?"Phase 41 Certified":"Certification blocked"}</Text><Text style={s.req}>{result.certified?`Certified at ${result.certifiedAt}`:"Manual status changes are not enough. Every required evidence item must be attached and verified."}</Text>{result.blockers.slice(0,12).map(x=><Text key={x} style={s.blocker}>• {x}</Text>)}</View></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#07111f"},content:{padding:22,gap:14},header:{gap:7},back:{color:"#67e8f9",fontSize:16},title:{color:"white",fontSize:28,fontWeight:"800"},sub:{color:"#94a3b8",fontSize:15},metrics:{flexDirection:"row",gap:10,flexWrap:"wrap"},metric:{backgroundColor:"#0f1d2e",borderWidth:1,borderColor:"#1e3a5f",borderRadius:14,padding:15,minWidth:150},num:{color:"#67e8f9",fontWeight:"800",fontSize:24},label:{color:"#94a3b8"},search:{backgroundColor:"#0f1d2e",borderColor:"#29415f",borderWidth:1,borderRadius:12,padding:12,color:"white"},card:{backgroundColor:"#0f1d2e",borderWidth:1,borderColor:"#203550",borderRadius:16,padding:16,gap:9},row:{flexDirection:"row",gap:8,alignItems:"center"},id:{color:"#67e8f9",fontWeight:"800"},area:{color:"#cbd5e1"},status:{marginLeft:"auto",color:"#fbbf24"},cardTitle:{color:"white",fontSize:17,fontWeight:"700"},req:{color:"#94a3b8",lineHeight:20},actions:{flexDirection:"row",gap:8,flexWrap:"wrap"},button:{backgroundColor:"#155e75",paddingHorizontal:10,paddingVertical:8,borderRadius:9},buttonText:{color:"white",fontSize:12,fontWeight:"700"},evidence:{backgroundColor:"#0b1625",padding:10,borderRadius:9},evidenceText:{color:"#cbd5e1"},cert:{backgroundColor:"#111827",borderWidth:1,borderColor:"#7c2d12",borderRadius:16,padding:17,gap:7},certTitle:{color:"#fb923c",fontSize:20,fontWeight:"800"},blocker:{color:"#fecaca"}});
