import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useEffect,useState } from "react";
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Switch,Text,TextInput,View } from "react-native";
import { creativeSuiteStorage,DEFAULT_BRANDS,type BrandKitRecord } from "../utils/creativeSuiteStorage";
const uid=()=>`brand-${Date.now()}`;
export default function Brand(){
 const [kits,setKits]=useState<BrandKitRecord[]>([]),[selected,setSelected]=useState<string>(""),[notice,setNotice]=useState("Brand system ready");
 useEffect(()=>{creativeSuiteStorage.loadBrands().then(v=>{setKits(v);setSelected(v[0]?.id??"")})},[]); useEffect(()=>{if(kits.length) void creativeSuiteStorage.saveBrands(kits)},[kits]);
 const kit=kits.find(x=>x.id===selected)??kits[0]; const update=(patch:Partial<BrandKitRecord>)=>setKits(v=>v.map(x=>x.id===kit?.id?{...x,...patch}:x));
 const add=()=>{const x={...DEFAULT_BRANDS[0],id:uid(),name:"New Brand Kit",active:false};setKits(v=>[...v,x]);setSelected(x.id);setNotice("New Brand Kit created.")};
 const apply=()=>{setKits(v=>v.map(x=>({...x,active:x.id===kit?.id})));setNotice(`${kit?.name} is now the active brand.`)};
 return <SafeAreaView style={s.safe}><View style={s.top}><Pressable onPress={()=>router.canGoBack() ? router.back() : router.replace("/" as never)}><Ionicons name="arrow-back" size={22} color="#fff"/></Pressable><View style={{flex:1}}><Text style={s.title}>Brand Kit</Text><Text style={s.sub}>Manage logos, colors, typography, assets, and usage rules.</Text></View><Pressable style={s.primary} onPress={add}><Text style={s.primaryText}>New Brand Kit</Text></Pressable></View><ScrollView contentContainerStyle={s.page}>
 <View style={s.notice}><Ionicons name="information-circle" size={18} color="#0f766e"/><Text style={s.noticeText}>{notice}</Text></View>
 <View style={s.layout}><View style={s.sidebar}><Text style={s.panelTitle}>Brand Kits</Text>{kits.map(x=><Pressable key={x.id} onPress={()=>setSelected(x.id)} style={[s.kitItem,x.id===kit?.id&&s.kitActive]}><View style={[s.swatch,{backgroundColor:x.primary}]}/><View style={{flex:1}}><Text style={s.kitName}>{x.name}</Text><Text style={s.meta}>{x.active?"Active brand":"Saved locally"}</Text></View>{x.active&&<Ionicons name="checkmark-circle" size={18} color="#0f766e"/>}</Pressable>)}<Pressable style={s.assetLink} onPress={()=>router.push("/assets" as never)}><Ionicons name="folder-open-outline" size={20} color="#2563eb"/><Text style={s.assetLinkText}>Open Asset Library</Text></Pressable><Pressable style={s.assetLink} onPress={()=>router.push("/templates" as never)}><Ionicons name="albums-outline" size={20} color="#2563eb"/><Text style={s.assetLinkText}>Open Templates</Text></Pressable></View>
 {kit&&<View style={s.main}><View style={s.preview}><View style={[s.logoPreview,{backgroundColor:kit.primary}]}><Text style={s.logoText}>{kit.name.slice(0,1).toUpperCase()}</Text></View><View><Text style={[s.previewTitle,{fontFamily:kit.headingFont}]}>{kit.name}</Text><Text style={[s.previewBody,{fontFamily:kit.bodyFont}]}>Consistent creative work across print, web, and commerce.</Text><View style={s.palette}>{[kit.primary,kit.secondary,kit.accent].map(c=><View key={c} style={[s.colorDot,{backgroundColor:c}]}/>)}</View></View></View>
 <View style={s.panel}><Text style={s.panelTitle}>Identity</Text><Text style={s.label}>Brand name</Text><TextInput value={kit.name} onChangeText={v=>update({name:v})} style={s.input}/><View style={s.three}>{(["primary","secondary","accent"] as const).map(k=><View key={k} style={{flex:1,minWidth:170}}><Text style={s.label}>{k[0].toUpperCase()+k.slice(1)} color</Text><View style={s.colorRow}><View style={[s.miniSwatch,{backgroundColor:kit[k]}]}/><TextInput value={kit[k]} onChangeText={v=>update({[k]:v})} style={[s.input,{flex:1}]}/></View></View>)}</View></View>
 <View style={s.panel}><Text style={s.panelTitle}>Typography</Text><View style={s.two}><View style={{flex:1}}><Text style={s.label}>Heading font</Text><TextInput value={kit.headingFont} onChangeText={v=>update({headingFont:v})} style={s.input}/></View><View style={{flex:1}}><Text style={s.label}>Body font</Text><TextInput value={kit.bodyFont} onChangeText={v=>update({bodyFont:v})} style={s.input}/></View></View></View>
 <View style={s.panel}><Text style={s.panelTitle}>Brand rules</Text><TextInput multiline value={kit.rules} onChangeText={v=>update({rules:v})} style={[s.input,s.rules]}/><View style={s.actionRow}><View style={s.activeToggle}><Text>Active Brand Kit</Text><Switch value={kit.active} onValueChange={()=>apply()}/></View><Pressable style={s.secondary} onPress={()=>{setKits(v=>v.filter(x=>x.id!==kit.id));setSelected(kits.find(x=>x.id!==kit.id)?.id??"")}}><Text style={{color:"#b91c1c",fontWeight:"700"}}>Delete</Text></Pressable><Pressable style={s.primary} onPress={apply}><Text style={s.primaryText}>Apply Brand Kit</Text></Pressable></View></View>
 </View>}</View></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#eef3f8"},top:{backgroundColor:"#07131f",padding:18,flexDirection:"row",alignItems:"center",gap:16},title:{color:"#fff",fontSize:25,fontWeight:"800"},sub:{color:"#9fb2c5",marginTop:3},primary:{backgroundColor:"#0f766e",paddingHorizontal:16,paddingVertical:11,borderRadius:10},primaryText:{color:"#fff",fontWeight:"800"},secondary:{backgroundColor:"#f1f5f9",paddingHorizontal:16,paddingVertical:11,borderRadius:10},page:{padding:24,gap:16},notice:{flexDirection:"row",gap:8,backgroundColor:"#ecfdf5",padding:12,borderRadius:12,borderWidth:1,borderColor:"#a7f3d0"},noticeText:{color:"#115e59"},layout:{flexDirection:"row",gap:18,alignItems:"flex-start",flexWrap:"wrap"},sidebar:{width:280,backgroundColor:"#fff",borderRadius:16,padding:16,borderWidth:1,borderColor:"#dbe4ee"},main:{flex:1,minWidth:420,gap:16},panel:{backgroundColor:"#fff",borderRadius:16,padding:18,borderWidth:1,borderColor:"#dbe4ee"},panelTitle:{fontWeight:"800",fontSize:18,color:"#172033",marginBottom:12},kitItem:{flexDirection:"row",alignItems:"center",gap:10,padding:11,borderRadius:10,marginBottom:7},kitActive:{backgroundColor:"#ecfdf5"},swatch:{width:28,height:28,borderRadius:8},kitName:{fontWeight:"700",color:"#172033"},meta:{fontSize:12,color:"#64748b",marginTop:2},assetLink:{flexDirection:"row",gap:9,alignItems:"center",paddingVertical:12,borderTopWidth:1,borderTopColor:"#e2e8f0",marginTop:4},assetLinkText:{color:"#2563eb",fontWeight:"700"},preview:{backgroundColor:"#fff",borderRadius:16,padding:20,borderWidth:1,borderColor:"#dbe4ee",flexDirection:"row",gap:18,alignItems:"center"},logoPreview:{width:72,height:72,borderRadius:18,alignItems:"center",justifyContent:"center"},logoText:{color:"#fff",fontSize:34,fontWeight:"900"},previewTitle:{fontSize:25,fontWeight:"800",color:"#172033"},previewBody:{color:"#64748b",marginTop:5},palette:{flexDirection:"row",gap:7,marginTop:12},colorDot:{width:24,height:24,borderRadius:12},label:{fontSize:12,fontWeight:"700",color:"#475569",marginBottom:6,marginTop:8},input:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:10,paddingHorizontal:12,paddingVertical:10,backgroundColor:"#fff"},three:{flexDirection:"row",gap:12,flexWrap:"wrap"},two:{flexDirection:"row",gap:12},colorRow:{flexDirection:"row",alignItems:"center",gap:8},miniSwatch:{width:34,height:34,borderRadius:8,borderWidth:1,borderColor:"#cbd5e1"},rules:{minHeight:110,textAlignVertical:"top"},actionRow:{flexDirection:"row",justifyContent:"flex-end",gap:10,alignItems:"center",marginTop:14,flexWrap:"wrap"},activeToggle:{flexDirection:"row",alignItems:"center",gap:8,marginRight:"auto"}});
