import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { PHASE45_COMPONENTS, type Phase45ComponentKind } from "../utils/phase45ProfessionalComponentEngine";

export default function ComponentLibrary(){const router=useRouter();const [q,setQ]=useState("");const items=useMemo(()=>PHASE45_COMPONENTS.filter(x=>(x.name+" "+x.tags.join(" ")).toLowerCase().includes(q.toLowerCase())),[q]);return <SafeAreaView style={s.root}><View style={s.top}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color="#0f172a"/></Pressable><View><Text style={s.title}>Professional Component Engine</Text><Text style={s.sub}>Phase 45 · 12 reusable editable building blocks</Text></View></View><TextInput value={q} onChangeText={setQ} placeholder="Search components" style={s.search}/><ScrollView contentContainerStyle={s.grid}>{items.map(item=><View key={item.id} style={s.card}><View style={s.preview}>{preview(item.kind)}</View><Text style={s.cardTitle}>{item.name}</Text><Text style={s.desc}>{item.description}</Text><View style={s.tags}><Text style={s.tag}>{item.kind}</Text><Text style={s.tag}>editable</Text><Text style={s.tag}>theme-aware</Text></View></View>)}</ScrollView></SafeAreaView>}
function preview(kind:Phase45ComponentKind){return <View style={{flex:1,padding:14,gap:8}}><View style={{height:10,width:kind==="hero"?"42%":"62%",backgroundColor:"#f59e0b",borderRadius:5}}/><View style={{height:kind==="hero"?44:24,width:"88%",backgroundColor:"#0f172a",borderRadius:8}}/><View style={{height:8,width:"70%",backgroundColor:"#94a3b8",borderRadius:4}}/><View style={{flex:1,flexDirection:"row",gap:7}}>{[1,2,3].map(n=><View key={n} style={{flex:1,backgroundColor:n===2?"#e2e8f0":"#f8fafc",borderRadius:8,borderWidth:1,borderColor:"#e2e8f0"}}/>)}</View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#f8fafc"},top:{flexDirection:"row",gap:16,alignItems:"center",padding:22,backgroundColor:"#fff",borderBottomWidth:1,borderColor:"#e2e8f0"},title:{fontSize:26,fontWeight:"900",color:"#0f172a"},sub:{color:"#64748b",marginTop:3},search:{margin:20,backgroundColor:"#fff",borderWidth:1,borderColor:"#dbe3ee",borderRadius:14,padding:14,fontSize:16},grid:{padding:20,flexDirection:"row",flexWrap:"wrap",gap:18},card:{width:300,backgroundColor:"#fff",borderRadius:18,padding:14,borderWidth:1,borderColor:"#e2e8f0",shadowColor:"#0f172a",shadowOpacity:.08,shadowRadius:14,shadowOffset:{width:0,height:7}},preview:{height:170,backgroundColor:"#fff",borderRadius:13,borderWidth:1,borderColor:"#e2e8f0",overflow:"hidden"},cardTitle:{fontSize:19,fontWeight:"900",color:"#0f172a",marginTop:14},desc:{color:"#64748b",lineHeight:20,marginTop:6},tags:{flexDirection:"row",gap:6,marginTop:12,flexWrap:"wrap"},tag:{fontSize:11,fontWeight:"800",color:"#0f766e",backgroundColor:"#ccfbf1",paddingHorizontal:8,paddingVertical:5,borderRadius:99}});
