import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useAuth } from "../context/AuthContext";

type Product={id:string;name:string;description:string;kind:"template"|"asset"|"plugin";priceCents:number;license:string;status:string;creatorUserId:string};
type Dashboard={products:Product[];metrics:{totalProducts:number;approvedProducts:number;sales:number;grossCents:number;payoutCents:number}};
export default function CreatorMarketplace(){
 const auth=useAuth();const [catalog,setCatalog]=useState<Product[]>([]);const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [loading,setLoading]=useState(true);const [name,setName]=useState("");const [description,setDescription]=useState("");const [price,setPrice]=useState("0");const [kind,setKind]=useState<Product["kind"]>("template");const [referral,setReferral]=useState("");
 const load=useCallback(async()=>{if(!auth.isAuthenticated)return;setLoading(true);try{const [a,b]=await Promise.all([auth.authorizedFetch("/api/v1/creator-marketplace/products"),auth.authorizedFetch("/api/v1/creator-marketplace/dashboard")]);if(a.ok)setCatalog((await a.json()).items??[]);if(b.ok)setDashboard(await b.json())}finally{setLoading(false)}},[auth]);
 useEffect(()=>{if(auth.ready&&!auth.isAuthenticated){router.replace("/sign-in");return;}queueMicrotask(()=>{void load()})},[auth.ready,auth.isAuthenticated,load]);
 const submit=async()=>{const response=await auth.authorizedFetch("/api/v1/creator-marketplace/products",{method:"POST",body:JSON.stringify({name,description,priceCents:Math.round((Number(price)||0)*100),kind,license:"commercial",payload:`${name}:${description}`})});const data=await response.json();if(!response.ok)return Alert.alert("Submission failed",data?.error?.message??"Please try again.");setName("");setDescription("");setPrice("0");await load();Alert.alert("Submitted","Your product is now in marketplace review.")};
 const buy=async(product:Product)=>{const response=await auth.authorizedFetch(`/api/v1/creator-marketplace/products/${product.id}/purchase`,{method:"POST"});const data=await response.json();if(!response.ok)return Alert.alert("Purchase unavailable",data?.error?.message??"Please try again.");Alert.alert(data.alreadyOwned?"Already owned":"Added to library",`${product.name} is now available in your account.`)};
 const createCode=async()=>{const response=await auth.authorizedFetch("/api/v1/referrals/code",{method:"POST"});const data=await response.json();if(response.ok)Alert.alert("Referral code",data.code)};
 const redeem=async()=>{const response=await auth.authorizedFetch("/api/v1/referrals/redeem",{method:"POST",body:JSON.stringify({code:referral})});const data=await response.json();if(!response.ok)return Alert.alert("Could not redeem",data?.error?.message??"Invalid code.");setReferral("");Alert.alert("Referral applied","10 AI credits were added to your referral reward balance.")};
 if(!auth.ready||loading)return <SafeAreaView style={s.center}><ActivityIndicator size="large" color="#7c3aed"/><Text style={s.muted}>Loading creator marketplace…</Text></SafeAreaView>;
 const m=dashboard?.metrics;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <View style={s.top}><Pressable style={s.icon} onPress={()=>router.canGoBack()?router.back():router.replace("/")}><Ionicons name="arrow-back" size={20} color="#fff"/></Pressable><View><Text style={s.brand}>Creator Marketplace</Text><Text style={s.topSub}>sell templates, assets and plugins</Text></View><View style={{flex:1}}/><Pressable style={s.secondary} onPress={()=>void createCode()}><Text style={s.secondaryText}>My referral code</Text></Pressable></View>
  <View style={s.metrics}>{[["Products",m?.totalProducts??0],["Approved",m?.approvedProducts??0],["Sales",m?.sales??0],["Gross",`$${((m?.grossCents??0)/100).toFixed(2)}`],["Creator payout",`$${((m?.payoutCents??0)/100).toFixed(2)}`]].map(([label,value])=><View key={String(label)} style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>)}</View>
  <View style={s.grid}><View style={s.card}><Text style={s.cardTitle}>Submit a product</Text><Text style={s.muted}>Products enter review before appearing publicly.</Text><View style={s.kinds}>{(["template","asset","plugin"] as const).map(v=><Pressable key={v} onPress={()=>setKind(v)} style={[s.chip,kind===v&&s.chipActive]}><Text style={[s.chipText,kind===v&&{color:"#fff"}]}>{v}</Text></Pressable>)}</View><TextInput value={name} onChangeText={setName} placeholder="Product name" style={s.input}/><TextInput value={description} onChangeText={setDescription} placeholder="Description" multiline style={[s.input,{height:96,textAlignVertical:"top"}]}/><TextInput value={price} onChangeText={setPrice} placeholder="Price in USD" keyboardType="decimal-pad" style={s.input}/><Pressable style={s.primary} onPress={()=>void submit()}><Text style={s.primaryText}>Submit for review</Text></Pressable></View>
  <View style={s.card}><Text style={s.cardTitle}>Referral rewards</Text><Text style={s.muted}>Share your code. A successful redemption grants 10 AI credits to the new user reward balance.</Text><TextInput value={referral} onChangeText={setReferral} placeholder="Enter referral code" autoCapitalize="characters" style={s.input}/><Pressable style={s.primary} onPress={()=>void redeem()}><Text style={s.primaryText}>Redeem code</Text></Pressable></View></View>
  <View style={s.card}><Text style={s.cardTitle}>Approved marketplace products</Text><View style={s.catalog}>{catalog.map(product=><View key={product.id} style={s.product}><View style={s.productIcon}><Ionicons name={product.kind==="template"?"document-text-outline":product.kind==="plugin"?"extension-puzzle-outline":"images-outline"} size={25} color="#6d28d9"/></View><View style={{flex:1}}><Text style={s.bold}>{product.name}</Text><Text style={s.muted}>{product.description||`${product.kind} • ${product.license} license`}</Text></View><Text style={s.price}>${(product.priceCents/100).toFixed(2)}</Text><Pressable style={s.buy} onPress={()=>void buy(product)}><Text style={s.buyText}>Add</Text></Pressable></View>)}{!catalog.length&&<Text style={s.muted}>No approved creator products yet. Submit the first one for review.</Text>}</View></View>
  <View style={s.card}><Text style={s.cardTitle}>Your submissions</Text>{dashboard?.products.map(product=><View key={product.id} style={s.row}><Text style={s.bold}>{product.name}</Text><Text style={[s.status,product.status==="approved"&&s.good]}>{product.status}</Text></View>)}{!dashboard?.products.length&&<Text style={s.muted}>You have not submitted any products.</Text>}</View>
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#eef3f8"},center:{flex:1,alignItems:"center",justifyContent:"center",gap:12,backgroundColor:"#eef3f8"},page:{padding:22,gap:16},top:{backgroundColor:"#102234",borderRadius:15,padding:14,flexDirection:"row",alignItems:"center",gap:12},icon:{width:38,height:38,borderRadius:10,backgroundColor:"#20394f",alignItems:"center",justifyContent:"center"},brand:{color:"#fff",fontWeight:"900",fontSize:17},topSub:{color:"#9fb1c1",fontSize:11},secondary:{borderWidth:1,borderColor:"#8b5cf6",borderRadius:10,paddingHorizontal:14,paddingVertical:10},secondaryText:{color:"#ddd6fe",fontWeight:"900"},metrics:{flexDirection:"row",flexWrap:"wrap",gap:10},metric:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dce5ee",borderRadius:14,padding:16,minWidth:145,flexGrow:1},metricValue:{fontSize:24,fontWeight:"900",color:"#7c3aed"},metricLabel:{color:"#64748b",fontSize:12},grid:{flexDirection:"row",flexWrap:"wrap",gap:16},card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dce5ee",borderRadius:16,padding:20,gap:12,flex:1,minWidth:340},cardTitle:{fontSize:20,fontWeight:"900",color:"#172033"},muted:{color:"#64748b",fontSize:12,lineHeight:18},kinds:{flexDirection:"row",gap:8},chip:{paddingHorizontal:12,paddingVertical:8,borderRadius:999,backgroundColor:"#f1f5f9"},chipActive:{backgroundColor:"#7c3aed"},chipText:{fontWeight:"800",textTransform:"capitalize",color:"#475569"},input:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:10,paddingHorizontal:12,paddingVertical:11,backgroundColor:"#f8fafc"},primary:{backgroundColor:"#7c3aed",borderRadius:10,padding:12,alignItems:"center"},primaryText:{color:"#fff",fontWeight:"900"},catalog:{gap:10},product:{flexDirection:"row",alignItems:"center",gap:12,padding:12,borderWidth:1,borderColor:"#e2e8f0",borderRadius:12},productIcon:{width:46,height:46,borderRadius:12,backgroundColor:"#ede9fe",alignItems:"center",justifyContent:"center"},bold:{fontWeight:"900",color:"#172033"},price:{fontWeight:"900",color:"#0f766e"},buy:{backgroundColor:"#0f766e",paddingHorizontal:14,paddingVertical:9,borderRadius:9},buyText:{color:"#fff",fontWeight:"900"},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#eef2f7"},status:{textTransform:"capitalize",fontWeight:"900",color:"#92400e",backgroundColor:"#fef3c7",paddingHorizontal:10,paddingVertical:5,borderRadius:999},good:{color:"#166534",backgroundColor:"#dcfce7"}});
