import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import Head from "expo-router/head";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { useAuth } from "../context/AuthContext";

export default function CreateAiPage(){
 const auth=useAuth(); const [name,setName]=useState(""); const [busy,setBusy]=useState(false); const [existingCheckPending,setExistingCheckPending]=useState(true); const checkingExisting=auth.isAuthenticated && existingCheckPending; const [error,setError]=useState(""); const [requestId,setRequestId]=useState("");
 useEffect(()=>{
  if(!auth.ready){return;}
  if(!auth.isAuthenticated){return;}
  let active=true;
  void auth.authorizedFetch("/api/v1/spaces").then(async response=>{
   const body=await response.json().catch(()=>({items:[]}));
   if(!active)return;
   const items=Array.isArray(body.items)?body.items:[];
   const personal=items.filter((item:any)=>item?.kind==="personal");
   if(response.ok && personal.length){router.replace("/my-space" as never);return;}
   setExistingCheckPending(false);
  }).catch(()=>{if(active)setExistingCheckPending(false)});
  return()=>{active=false};
 },[auth.ready,auth.isAuthenticated]);
 const create=async()=>{setBusy(true);setError("");const rid=`space-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;setRequestId(rid);try{const response=await auth.authorizedFetch("/api/v1/spaces",{method:"POST",headers:{"x-yaposan-client-request-id":rid},body:JSON.stringify({name:name.trim()||"My AI Page",kind:"personal",visibility:"private"})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||"Could not create AI Page");router.replace(`/ai-page?spaceId=${encodeURIComponent(data.space.id)}`)}catch(e){setError(e instanceof Error?e.message:"Could not create AI Page")}finally{setBusy(false)}};
 return <><Head><title>Create My AI Page â€” Yaposan</title><meta name="robots" content="noindex,nofollow"/></Head><SafeAreaView style={s.screen}><View style={s.card}><Pressable onPress={()=>router.replace("/")} style={s.back}><Ionicons name="arrow-back" size={18} color="#5b21b6"/><Text style={s.backText}>Yaposan</Text></Pressable><Text style={s.kicker}>YOUR AI WORLD</Text><Text style={s.title}>Create My AI Page</Text><Text style={s.copy}>Build a personal page for your AI, Studios, creations, followers, publishing, team, and business. This is optional â€” Yaposan Creator remains available without an AI Page.</Text>{!auth.ready||checkingExisting?<ActivityIndicator style={{marginTop:24}}/>:!auth.isAuthenticated?<><View style={s.notice}><Text style={s.noticeTitle}>A free Yaposan account is required.</Text><Text style={s.noticeCopy}>Your account owns the AI Page. Creating an account does not remove access to the regular Yaposan Creator tools.</Text></View><Pressable style={s.primary} onPress={()=>router.push("/register?next=/create-ai-page")}><Text style={s.primaryText}>Create free account</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push("/sign-in?next=/create-ai-page")}><Text style={s.secondaryText}>Sign in</Text></Pressable></>:<><Text style={s.label}>AI Page name</Text><TextInput value={name} onChangeText={setName} placeholder="Example: Dawit's AI Page" style={s.input} maxLength={80}/><Text style={s.help}>Your AI Page starts private. Public, team, and paid visibility can be enabled later.</Text>{error?<View style={s.errorBox}><Text style={s.error}>{error}</Text>{requestId?<Text style={s.errorHelp}>Support ID: {requestId}. If you are the Yaposan platform owner, open Yaposan Admin â†’ Users & Spaces to diagnose and preview the customer page.</Text>:null}</View>:null}<Pressable disabled={busy} style={s.primary} onPress={()=>void create()}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Create AI Page</Text>}</Pressable></>}<Pressable onPress={()=>router.replace("/creator")}><Text style={s.skip}>I just want to use Yaposan Creator â†’</Text></Pressable></View></SafeAreaView></>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#f5f3ff",alignItems:"center",justifyContent:"center",padding:20},card:{width:"100%",maxWidth:560,backgroundColor:"#fff",padding:32,borderRadius:26,borderWidth:1,borderColor:"#ddd6fe"},back:{flexDirection:"row",gap:6,alignItems:"center",marginBottom:28},backText:{fontWeight:"900",color:"#5b21b6"},kicker:{fontSize:12,fontWeight:"900",letterSpacing:1.5,color:"#7c3aed"},title:{fontSize:38,fontWeight:"900",color:"#111827",marginTop:7},copy:{fontSize:16,lineHeight:24,color:"#64748b",marginTop:12},notice:{backgroundColor:"#f5f3ff",borderRadius:16,padding:18,marginTop:24},noticeTitle:{fontWeight:"900",fontSize:16,color:"#312e81"},noticeCopy:{color:"#64748b",lineHeight:21,marginTop:5},label:{fontSize:13,fontWeight:"900",color:"#374151",marginTop:26},input:{borderWidth:1,borderColor:"#c4b5fd",borderRadius:13,padding:14,marginTop:8,fontSize:16},help:{fontSize:12,lineHeight:18,color:"#64748b",marginTop:8},errorBox:{backgroundColor:"#fef2f2",borderWidth:1,borderColor:"#fecaca",padding:12,borderRadius:10,marginTop:10},error:{color:"#b91c1c",fontWeight:"700"},errorHelp:{color:"#7f1d1d",fontSize:11,lineHeight:16,marginTop:6},primary:{backgroundColor:"#6d28d9",padding:15,borderRadius:13,alignItems:"center",marginTop:20},primaryText:{color:"#fff",fontWeight:"900",fontSize:16},secondary:{borderWidth:1,borderColor:"#c4b5fd",padding:14,borderRadius:13,alignItems:"center",marginTop:10},secondaryText:{color:"#5b21b6",fontWeight:"900"},skip:{textAlign:"center",color:"#64748b",fontWeight:"800",marginTop:20}});

