import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '../context/AuthContext';

type Kind='ai'|'studio'|'template'|'workflow'|'digital_product'|'service';
type Product={id:string;kind:Kind;name:string;description?:string;priceCents:number;visibility:'private'|'public';marketplaceListed?:boolean;status:'draft'|'active'|'archived'};
type Store={products:Product[];orders:any[];metrics:{products:number;active:number;orders:number;grossCents:number;creatorNetCents:number}};
const kinds:Kind[]=['ai','studio','template','workflow','digital_product','service'];
const money=(c:number)=>`$${(c/100).toFixed(2)}`;
export default function CreatorStore(){
 const {spaceId}=useLocalSearchParams<{spaceId:string}>();const auth=useAuth();
 const [store,setStore]=useState<Store>({products:[],orders:[],metrics:{products:0,active:0,orders:0,grossCents:0,creatorNetCents:0}}),[name,setName]=useState(''),[kind,setKind]=useState<Kind>('studio'),[price,setPrice]=useState('0'),[message,setMessage]=useState('');
 const load=async()=>{if(!spaceId)return;const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/store`);if(r.ok)setStore(await r.json())};useEffect(()=>{queueMicrotask(()=>{void load()})},[spaceId]);
 const create=async()=>{if(!spaceId||!name.trim())return;const cents=Math.round(Number(price||0)*100);const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/store/products`,{method:'POST',body:JSON.stringify({name,kind,priceCents:cents,visibility:'private',status:'draft'})});const j=await r.json();setMessage(r.ok?'Product created as a private draft.':j.error?.message||'Could not create product.');if(r.ok){setName('');void load()}};
 const patch=async(p:Product,body:any)=>{const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/store/products/${p.id}`,{method:'PATCH',body:JSON.stringify(body)});if(r.ok)void load();else setMessage((await r.json()).error?.message||'Could not update product.')};
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.wrap}><Pressable onPress={()=>router.push(`/ai-page?spaceId=${spaceId}` as any)}><Text style={s.back}>← Back to AI Page</Text></Pressable><View style={s.head}><View><Text style={s.title}>My Store</Text><Text style={s.copy}>Sell AI, Studios, templates, workflows, digital products and services from this creator Page.</Text></View><View style={s.badge}><Ionicons name="storefront" size={18} color="#6d28d9"/><Text style={s.badgeText}>CREATOR-OWNED</Text></View></View>
 <View style={s.metrics}>{[['Products',store.metrics.products],['Active',store.metrics.active],['Orders',store.metrics.orders],['Gross',money(store.metrics.grossCents)],['Creator earnings',money(store.metrics.creatorNetCents)]].map(([k,v])=><View key={String(k)} style={s.metric}><Text style={s.muted}>{k}</Text><Text style={s.metricValue}>{v}</Text></View>)}</View>
 <View style={s.card}><Text style={s.h2}>Create a product</Text><Text style={s.copy}>Products begin as private drafts. Publish them only when you are ready.</Text><TextInput value={name} onChangeText={setName} placeholder="Product name" style={s.input}/><View style={s.kindRow}>{kinds.map(x=><Pressable key={x} onPress={()=>setKind(x)} style={[s.pill,kind===x&&s.pillOn]}><Text style={kind===x?s.pillTextOn:s.pillText}>{x.replace('_',' ')}</Text></Pressable>)}</View><View style={s.formRow}><View style={{flex:1}}><Text style={s.label}>Price (USD)</Text><TextInput value={price} onChangeText={setPrice} keyboardType="decimal-pad" style={s.input}/></View><Pressable style={s.primary} onPress={()=>void create()}><Text style={s.primaryText}>+ Add product</Text></Pressable></View>{!!message&&<Text style={s.message}>{message}</Text>}</View>
 <Text style={s.section}>Products</Text><View style={s.grid}>{store.products.length?store.products.map(p=><View key={p.id} style={s.product}><View style={s.icon}><Ionicons name={p.kind==='ai'?'sparkles':p.kind==='studio'?'grid':'cube-outline'} size={22} color="#6d28d9"/></View><Text style={s.productName}>{p.name}</Text><Text style={s.muted}>{p.kind.replace('_',' ')} · {money(p.priceCents)}</Text><Text style={s.state}>{p.status} · {p.visibility} · {p.marketplaceListed?'Marketplace listed':'Store only'}</Text><View style={s.actions}><Pressable style={s.secondary} onPress={()=>void patch(p,{status:p.status==='active'?'draft':'active',visibility:p.status==='active'?'private':'public'})}><Text style={s.secondaryText}>{p.status==='active'?'Unpublish':'Publish'}</Text></Pressable><Pressable style={s.secondary} onPress={()=>void patch(p,{marketplaceListed:!p.marketplaceListed})}><Text style={s.secondaryText}>{p.marketplaceListed?'Remove from Marketplace':'List in Marketplace'}</Text></Pressable><Pressable style={s.secondary} onPress={()=>void patch(p,{status:'archived',visibility:'private',marketplaceListed:false})}><Text style={s.secondaryText}>Archive</Text></Pressable></View></View>):<View style={s.empty}><Text style={s.h2}>Your store is ready.</Text><Text style={s.copy}>Create your first AI, Studio, template, workflow or digital product above.</Text></View>}</View>
 <View style={s.note}><Text style={s.h2}>Marketplace & earnings</Text><Text style={s.copy}>Public Store products stay on your creator page unless you separately choose List in Marketplace. Free products can be installed immediately; paid products receive customer entitlements only after verified checkout settlement. Creator proceeds are tracked separately from Yaposan platform fees and payout records.</Text><Pressable onPress={()=>router.push('/my-usage' as any)}><Text style={s.back}>Open customer usage & billing →</Text></Pressable></View>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f7f5ff'},wrap:{padding:24,maxWidth:1260,width:'100%',alignSelf:'center'},back:{color:'#6d28d9',fontWeight:'800'},head:{marginTop:18,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:12,flexWrap:'wrap'},title:{fontSize:36,fontWeight:'900',color:'#111827'},copy:{color:'#64748b',lineHeight:21,maxWidth:760,marginTop:5},badge:{flexDirection:'row',gap:6,alignItems:'center',backgroundColor:'#ede9fe',padding:10,borderRadius:999},badgeText:{color:'#6d28d9',fontWeight:'900',fontSize:12},metrics:{flexDirection:'row',gap:10,flexWrap:'wrap',marginTop:22},metric:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e7eb',borderRadius:15,padding:16,minWidth:150,flexGrow:1},muted:{color:'#64748b',fontSize:12},metricValue:{fontSize:24,fontWeight:'900',color:'#111827',marginTop:5},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e7eb',borderRadius:18,padding:18,marginTop:18},h2:{fontSize:20,fontWeight:'900',color:'#111827'},input:{borderWidth:1,borderColor:'#d1d5db',borderRadius:10,padding:11,marginTop:11,backgroundColor:'#fff'},kindRow:{flexDirection:'row',gap:6,flexWrap:'wrap',marginTop:10},pill:{backgroundColor:'#f1f5f9',paddingHorizontal:10,paddingVertical:8,borderRadius:999},pillOn:{backgroundColor:'#6d28d9'},pillText:{color:'#475569',fontWeight:'700',fontSize:12,textTransform:'capitalize'},pillTextOn:{color:'#fff',fontWeight:'800',fontSize:12,textTransform:'capitalize'},formRow:{flexDirection:'row',gap:12,alignItems:'flex-end',marginTop:6,flexWrap:'wrap'},label:{fontSize:12,fontWeight:'800',color:'#475569',marginTop:8},primary:{backgroundColor:'#6d28d9',paddingHorizontal:18,paddingVertical:12,borderRadius:10},primaryText:{color:'#fff',fontWeight:'900'},message:{color:'#047857',fontWeight:'800',marginTop:10},section:{fontSize:23,fontWeight:'900',color:'#111827',marginTop:26,marginBottom:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},product:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e7eb',borderRadius:16,padding:16,minWidth:250,flexGrow:1,flexBasis:280},icon:{width:42,height:42,borderRadius:12,backgroundColor:'#ede9fe',alignItems:'center',justifyContent:'center'},productName:{fontSize:17,fontWeight:'900',color:'#111827',marginTop:11},state:{color:'#6d28d9',fontWeight:'800',fontSize:12,textTransform:'capitalize',marginTop:7},actions:{flexDirection:'row',gap:7,marginTop:13},secondary:{borderWidth:1,borderColor:'#ddd6fe',paddingHorizontal:10,paddingVertical:8,borderRadius:9},secondaryText:{color:'#6d28d9',fontWeight:'800'},empty:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e7eb',borderRadius:16,padding:24,flex:1},note:{backgroundColor:'#ede9fe',padding:18,borderRadius:16,marginTop:24}})
