import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { DesktopOfflineSnapshot, getDesktopOfflineSnapshot, isDesktopOfflineAvailable, removeDesktopOfflineProject, subscribeDesktopOffline } from "../utils/desktopOfflineSyncEngine";

const empty: DesktopOfflineSnapshot = { available:false,online:true,projects:[],queue:[],storageBytes:0,lastCheckedAt:0 };
const size=(n:number)=>n<1024?`${n} B`:n<1024*1024?`${(n/1024).toFixed(1)} KB`:`${(n/1024/1024).toFixed(1)} MB`;
export default function DesktopSync(){
 const [snapshot,setSnapshot]=useState(empty); const [loading,setLoading]=useState(true);
 const refresh=()=>getDesktopOfflineSnapshot().then(setSnapshot).finally(()=>setLoading(false));
 useEffect(()=>{void refresh();return subscribeDesktopOffline(setSnapshot)},[]);
 const exportBackup=async()=>{const api=typeof window!=="undefined"?window.yaposanDesktop?.offline:undefined;if(!api)return Alert.alert("Desktop required","Install and open the Yaposan desktop app to export an offline backup.");const result=await api.exportBackup();if(!result.canceled)Alert.alert("Backup exported",result.filePath||"The offline backup was created.")};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <View style={s.top}><Pressable style={s.icon} onPress={()=>router.canGoBack()?router.back():router.replace("/account" as never)}><Ionicons name="arrow-back" size={20} color="#fff"/></Pressable><View><Text style={s.brand}>Desktop & Offline Sync</Text><Text style={s.sub}>Local-first projects, recovery copies, and reconnect synchronization.</Text></View><View style={{flex:1}}/><Pressable style={s.button} onPress={()=>void refresh()}><Ionicons name="refresh" size={18} color="#fff"/><Text style={s.buttonText}>Refresh</Text></Pressable></View>
  {!isDesktopOfflineAvailable()&&<View style={s.notice}><Ionicons name="desktop-outline" size={26} color="#b45309"/><View style={{flex:1}}><Text style={s.noticeTitle}>Desktop features are not available in this browser</Text><Text style={s.muted}>This control center becomes active in the packaged Windows, macOS, or Linux application.</Text></View></View>}
  {loading?<ActivityIndicator size="large" color="#2563eb"/>:<>
   <View style={s.metrics}><Metric icon="cloud-outline" label="Connection" value={snapshot.online?"Online":"Offline"}/><Metric icon="folder-outline" label="Offline projects" value={String(snapshot.projects.length)}/><Metric icon="sync-outline" label="Queued changes" value={String(snapshot.queue.length)}/><Metric icon="server-outline" label="Local storage" value={size(snapshot.storageBytes)}/></View>
   <View style={s.card}><View style={s.cardHead}><View><Text style={s.title}>Offline projects</Text><Text style={s.muted}>Encrypted-by-device local workspace copies remain available without internet access.</Text></View><Pressable style={s.button} onPress={()=>void exportBackup()}><Ionicons name="download-outline" size={18} color="#fff"/><Text style={s.buttonText}>Export backup</Text></Pressable></View>{snapshot.projects.length?snapshot.projects.map(p=><View key={p.projectId} style={s.row}><Ionicons name="document-text-outline" size={22} color="#2563eb"/><View style={{flex:1}}><Text style={s.rowTitle}>{p.name}</Text><Text style={s.muted}>Revision {p.revision} · {size(p.bytes)} · {new Date(p.updatedAt).toLocaleString()}</Text></View><View style={[s.badge,p.dirty?s.pending:s.synced]}><Text style={s.badgeText}>{p.dirty?"Pending sync":"Synced"}</Text></View><Pressable onPress={()=>Alert.alert("Remove offline copy",`Remove ${p.name} from this device?`,[{text:"Cancel"},{text:"Remove",style:"destructive",onPress:()=>void removeDesktopOfflineProject(p.projectId).then(refresh)}])}><Ionicons name="trash-outline" size={20} color="#dc2626"/></Pressable></View>):<Text style={s.empty}>No offline projects have been saved on this device.</Text>}</View>
   <View style={s.card}><Text style={s.title}>Synchronization queue</Text><Text style={s.muted}>Changes upload automatically after connectivity returns and the user is authenticated.</Text>{snapshot.queue.length?snapshot.queue.map(op=><View key={op.id} style={s.row}><Ionicons name={op.status==="failed"?"warning-outline":"cloud-upload-outline"} size={22} color={op.status==="failed"?"#dc2626":"#0f766e"}/><View style={{flex:1}}><Text style={s.rowTitle}>{op.type.toUpperCase()} · {op.projectId}</Text><Text style={s.muted}>{op.status} · attempts {op.attempts}{op.lastError?` · ${op.lastError}`:""}</Text></View></View>):<Text style={s.empty}>All offline changes are synchronized.</Text>}</View>
  </>}
 </ScrollView></SafeAreaView>
}
function Metric({icon,label,value}:{icon:any;label:string;value:string}){return <View style={s.metric}><Ionicons name={icon} size={24} color="#2563eb"/><Text style={s.metricValue}>{value}</Text><Text style={s.muted}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#eef3f8"},page:{padding:22,gap:16},top:{backgroundColor:"#102234",borderRadius:16,padding:16,flexDirection:"row",alignItems:"center",gap:12},icon:{width:38,height:38,borderRadius:10,backgroundColor:"#20394f",alignItems:"center",justifyContent:"center"},brand:{color:"#fff",fontSize:21,fontWeight:"900"},sub:{color:"#9fb1c1",fontSize:12,marginTop:3},button:{backgroundColor:"#2563eb",borderRadius:10,paddingHorizontal:14,paddingVertical:10,flexDirection:"row",alignItems:"center",gap:7},buttonText:{color:"#fff",fontWeight:"900"},notice:{backgroundColor:"#fffbeb",borderWidth:1,borderColor:"#fde68a",borderRadius:14,padding:16,flexDirection:"row",gap:12,alignItems:"center"},noticeTitle:{fontWeight:"900",color:"#92400e",fontSize:15},muted:{color:"#64748b",fontSize:12,lineHeight:18},metrics:{flexDirection:"row",flexWrap:"wrap",gap:12},metric:{flex:1,minWidth:180,backgroundColor:"#fff",borderRadius:14,padding:18,borderWidth:1,borderColor:"#dce5ee",gap:5},metricValue:{fontSize:25,fontWeight:"900",color:"#172033"},card:{backgroundColor:"#fff",borderRadius:16,padding:20,borderWidth:1,borderColor:"#dce5ee",gap:12},cardHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:12},title:{fontSize:20,fontWeight:"900",color:"#172033"},row:{flexDirection:"row",alignItems:"center",gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:"#eef2f7"},rowTitle:{fontWeight:"900",color:"#172033"},badge:{borderRadius:999,paddingHorizontal:10,paddingVertical:6},pending:{backgroundColor:"#fef3c7"},synced:{backgroundColor:"#dcfce7"},badgeText:{fontWeight:"900",fontSize:10,color:"#334155"},empty:{paddingVertical:20,textAlign:"center",color:"#64748b",fontWeight:"700"}});
