import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useAuth } from '../context/AuthContext';

type Data={subscription:{plan:string;planName:string;status:string};credits:{ai:{balance:number;ledger:any[]};gpu:{balance:number;ledger:any[]}};externalBilling:{message:string;connections:any[]};marketplace:{entitlements:number;orders:number}};
export default function MyUsage(){const auth=useAuth();const [data,setData]=useState<Data|null>(null);const load=async()=>{const r=await auth.authorizedFetch('/api/v1/my-usage');if(r.ok)setData(await r.json())};useEffect(()=>{queueMicrotask(()=>{void load()})},[]);return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.wrap}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Back</Text></Pressable><Text style={s.title}>My Usage & Billing</Text><Text style={s.copy}>Your customer-facing Yaposan balances, subscription foundation, marketplace ownership and provider billing boundary.</Text>{data?<><View style={s.grid}><Card label="Yaposan AI credits" value={String(data.credits.ai.balance)} note={`${data.credits.ai.ledger.length} recent ledger entries`}/><Card label="Yaposan GPU credits" value={String(data.credits.gpu.balance)} note={`${data.credits.gpu.ledger.length} recent ledger entries`}/><Card label="Subscription" value={data.subscription.planName} note={data.subscription.status}/><Card label="Marketplace library" value={String(data.marketplace.entitlements)} note={`${data.marketplace.orders} orders`}/></View><View style={s.card}><Text style={s.h2}>Bring-your-own AI billing</Text><Text style={s.copy}>{data.externalBilling.message}</Text>{data.externalBilling.connections.map(c=><Text key={c.id} style={s.row}>{c.name} · {c.kind} · {c.status}</Text>)}</View><Ledger title="AI credit ledger" rows={data.credits.ai.ledger}/><Ledger title="GPU credit ledger" rows={data.credits.gpu.ledger}/><View style={s.notice}><Text style={s.h2}>Privacy boundary</Text><Text style={s.copy}>This page contains only your balances, usage, customer charges and creator commerce data. Yaposan company operating expenses are not exposed to customers.</Text></View></>:<Text style={s.copy}>Loading usage…</Text>}</ScrollView></SafeAreaView>}
function Card({label,value,note}:{label:string;value:string;note:string}){return <View style={s.metric}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text><Text style={s.small}>{note}</Text></View>}
function Ledger({title,rows}:{title:string;rows:any[]}){return <View style={s.card}><Text style={s.h2}>{title}</Text>{rows.slice(0,20).map(r=><View key={r.id} style={s.ledger}><Text style={s.row}>{r.kind}</Text><Text style={s.amount}>{r.credits>0?'+':''}{r.credits}</Text><Text style={s.small}>{new Date(r.createdAt).toLocaleString()}</Text></View>)}{!rows.length&&<Text style={s.copy}>No ledger activity yet.</Text>}</View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f7f5ff'},wrap:{padding:24,maxWidth:1100,width:'100%',alignSelf:'center'},back:{color:'#6d28d9',fontWeight:'900'},title:{fontSize:36,fontWeight:'900',color:'#111827',marginTop:16},copy:{color:'#64748b',lineHeight:21,maxWidth:800,marginTop:6},grid:{flexDirection:'row',gap:12,flexWrap:'wrap',marginTop:22},metric:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e7eb',borderRadius:16,padding:17,minWidth:220,flexGrow:1},label:{color:'#64748b',fontWeight:'800',fontSize:12},value:{fontSize:25,fontWeight:'900',color:'#111827',marginTop:6},small:{color:'#64748b',fontSize:11,marginTop:4},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e7eb',borderRadius:16,padding:18,marginTop:16},h2:{fontSize:20,fontWeight:'900',color:'#111827'},row:{color:'#334155',fontWeight:'800',marginTop:8},ledger:{borderTopWidth:1,borderTopColor:'#eef2f7',paddingVertical:10},amount:{fontSize:16,fontWeight:'900',color:'#6d28d9'},notice:{backgroundColor:'#ede9fe',borderRadius:16,padding:18,marginTop:16}});
