import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { loadCreationProject } from "../services/creationProjectStore";
import { creationToPresentation, type PresentationDraft } from "../services/studioAdapters";

const blank = (): PresentationDraft => ({ id:`presentation-${Date.now()}`, title:"Untitled Presentation", editable:true, slides:[{id:"slide-1",title:"Presentation title",body:"Add your story here."}] });
export default function PresentationStudio(){
 const params=useLocalSearchParams<{creationProject?:string|string[]}>();const id=Array.isArray(params.creationProject)?params.creationProject[0]:params.creationProject;
 const [deck,setDeck]=useState<PresentationDraft>(blank);const [selected,setSelected]=useState(0);
 useEffect(()=>{if(!id)return;let active=true;void loadCreationProject(id).then(source=>{if(active&&source){setDeck(creationToPresentation(source));setSelected(0)}});return()=>{active=false}},[id]);
 const slide=deck.slides[selected];
 const patch=(field:"title"|"body",value:string)=>setDeck(d=>({...d,slides:d.slides.map((s,i)=>i===selected?{...s,[field]:value}:s)}));
 return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={20} color="#fff"/></Pressable><View><Text style={s.title}>Presentation Studio</Text><Text style={s.sub}>91.12 editable AI presentation handoff</Text></View><Pressable style={s.add} onPress={()=>{setDeck(d=>({...d,slides:[...d.slides,{id:`slide-${Date.now()}`,title:"New slide",body:""}]}));setSelected(deck.slides.length)}}><Text style={s.addText}>+ Slide</Text></Pressable></View><View style={s.body}><ScrollView style={s.rail} contentContainerStyle={{padding:12,gap:8}}>{deck.slides.map((x,i)=><Pressable key={x.id} onPress={()=>setSelected(i)} style={[s.thumb,i===selected&&s.thumbOn]}><Text style={s.thumbNum}>{i+1}</Text><Text numberOfLines={2} style={s.thumbTitle}>{x.title}</Text></Pressable>)}</ScrollView><View style={s.canvas}><View style={s.slide}><TextInput value={slide?.title??""} onChangeText={v=>patch("title",v)} style={s.slideTitle}/><TextInput multiline value={slide?.body??""} onChangeText={v=>patch("body",v)} style={s.slideBody}/></View></View><View style={s.inspector}><Text style={s.h}>Deck</Text><TextInput value={deck.title} onChangeText={title=>setDeck(d=>({...d,title}))} style={s.input}/><Text style={s.meta}>{deck.slides.length} editable slides</Text><Text style={s.h}>Actions</Text><Pressable style={s.button} onPress={()=>setDeck(d=>({...d,slides:d.slides.filter((_,i)=>i!==selected)}))}><Text style={s.buttonText}>Delete selected slide</Text></Pressable><Pressable style={s.button}><Text style={s.buttonText}>Export PDF / PowerPoint</Text></Pressable></View></View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#e8eef5"},header:{minHeight:76,backgroundColor:"#102234",padding:16,flexDirection:"row",gap:12,alignItems:"center"},title:{color:"#fff",fontWeight:"900",fontSize:20},sub:{color:"#9fb1c1",fontSize:11},add:{marginLeft:"auto",backgroundColor:"#7c3aed",paddingHorizontal:14,paddingVertical:9,borderRadius:9},addText:{color:"#fff",fontWeight:"900"},body:{flex:1,flexDirection:"row",gap:12,padding:12},rail:{width:220,backgroundColor:"#fff",borderRadius:14},thumb:{padding:12,borderRadius:10,backgroundColor:"#f1f5f9",gap:5},thumbOn:{borderWidth:2,borderColor:"#7c3aed"},thumbNum:{fontSize:10,color:"#7c3aed",fontWeight:"900"},thumbTitle:{fontWeight:"800",color:"#334155"},canvas:{flex:1,backgroundColor:"#cbd5e1",borderRadius:14,padding:28,justifyContent:"center"},slide:{aspectRatio:16/9,backgroundColor:"#fff",padding:48,shadowColor:"#000",shadowOpacity:.18,shadowRadius:12},slideTitle:{fontSize:38,fontWeight:"900",color:"#172033",marginBottom:24},slideBody:{flex:1,fontSize:20,color:"#475569",textAlignVertical:"top"},inspector:{width:270,backgroundColor:"#fff",borderRadius:14,padding:16,gap:10},h:{fontWeight:"900",fontSize:15,color:"#172033",marginTop:6},input:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:9,padding:10},meta:{fontSize:11,color:"#64748b"},button:{backgroundColor:"#eef2ff",padding:11,borderRadius:9},buttonText:{color:"#5b21b6",fontWeight:"800"}});
