import {Ionicons} from '@expo/vector-icons';
import {router,useLocalSearchParams} from 'expo-router';
import {useEffect,useState} from 'react';
import {Pressable,SafeAreaView,ScrollView,StyleSheet,Switch,Text,View} from 'react-native';
import {useAuth} from '../context/AuthContext';

type V='private'|'team'|'unlisted'|'public'|'paid';
type Item={id:string;label:string;visibility:V;status?:string};
export default function PrivacySettings(){
 const {spaceId}=useLocalSearchParams<{spaceId:string}>();const auth=useAuth();const [data,setData]=useState<any>(null),[message,setMessage]=useState('');
 const load=async()=>{if(!spaceId)return;const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/privacy`);if(r.ok)setData(await r.json())};useEffect(()=>{queueMicrotask(()=>{void load()})},[spaceId]);
 const patchSettings=async(p:any)=>{const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/privacy`,{method:'PATCH',body:JSON.stringify(p)});if(r.ok){setMessage('Privacy settings saved.');void load()}else setMessage((await r.json()).error?.message||'Could not save privacy settings.')};
 const setV=async(type:string,item:Item,v:V)=>{const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/privacy/resources/${type}/${item.id}`,{method:'PATCH',body:JSON.stringify({visibility:v})});if(r.ok)void load();else setMessage((await r.json()).error?.message||'Could not change sharing.')};
 if(!data)return <SafeAreaView style={s.center}><Text>Loading privacy controls…</Text></SafeAreaView>;
 const sections:[string,string,Item[]][]=[['posts','Posts',data.inventory.posts],['ai','AI',data.inventory.ai],['studio','Studios',data.inventory.studios],['project','Projects',data.inventory.projects],['product','Store products',data.inventory.products]];
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.wrap}><Pressable onPress={()=>router.push(`/ai-page?spaceId=${spaceId}` as any)}><Text style={s.back}>← Back to AI Page</Text></Pressable><Text style={s.eyebrow}>PRIVACY & SHARING</Text><Text style={s.title}>You decide what leaves your Page.</Text><Text style={s.copy}>Your Page is the private ownership boundary. Enabling a public page does not make your Page, files, connections, team, prompts, credentials or private work public. Only resources you explicitly mark Public appear on your creator page.</Text>
 <View style={s.card}><View style={s.row}><View style={{flex:1}}><Text style={s.itemTitle}>Who can see my AI Page</Text><Text style={s.meta}>Private keeps the page closed. Followers lets people who follow you open it inside Yaposan. Public makes it available to everyone when public sharing is enabled.</Text></View><View style={s.pills}>{(['private','followers','public'] as const).map(v=><Pressable key={v} onPress={()=>void patchSettings({profileAudience:v})} style={[s.pill,(data.settings.profileAudience??'private')===v&&s.pillOn]}><Text style={(data.settings.profileAudience??'private')===v?s.pillTextOn:s.pillText}>{v}</Text></Pressable>)}</View></View><Row title="Public creator page" copy="Turn on the public presentation layer. Your Page itself stays private." value={!!data.settings.publicPageEnabled} onValue={v=>void patchSettings({publicPageEnabled:v})}/><Row title="Discoverable" copy="Allow this public page to appear in Yaposan discovery surfaces." value={!!data.settings.discoverable} onValue={v=>void patchSettings({discoverable:v})}/><Row title="Show follower count" copy="Follower totals are hidden unless you choose to show them." value={!!data.settings.showFollowerCount} onValue={v=>void patchSettings({showFollowerCount:v})}/><View style={s.row}><View style={{flex:1}}><Text style={s.itemTitle}>Who can DM me</Text><Text style={s.meta}>Everyone allows signed-in Yaposan users to send a DM. Followers limits new DMs to people who follow your Page. Nobody blocks new DM conversations.</Text></View><View style={s.pills}>{(['everyone','followers','nobody'] as const).map(v=><Pressable key={v} onPress={()=>void patchSettings({dmAudience:v})} style={[s.pill,(data.settings.dmAudience??'followers')===v&&s.pillOn]}><Text style={(data.settings.dmAudience??'followers')===v?s.pillTextOn:s.pillText}>{v}</Text></Pressable>)}</View></View><Row title="Allow external data sharing" copy="Off by default. Provider connections receive no Page content unless you separately grant specific scopes/resources." value={!!data.settings.externalSharingEnabled} onValue={v=>void patchSettings({externalSharingEnabled:v})}/></View>
 <Pressable onPress={()=>router.push(`/space-security?spaceId=${spaceId}` as any)} style={{marginTop:16,alignSelf:"flex-start",backgroundColor:"#0f766e",paddingHorizontal:14,paddingVertical:10,borderRadius:10}}><Text style={{color:"#fff",fontWeight:"900"}}>Open Page Security</Text></Pressable>
 <View style={s.notice}><Ionicons name="shield-checkmark" size={24} color="#166534"/><View style={{flex:1}}><Text style={s.noticeTitle}>Privacy-safe defaults</Text><Text style={s.noticeText}>New Pages, posts, AI, Studios and products start private. Public sharing requires an admin-level action. Connection credential references are not returned to the client, and third-party data grants start empty.</Text></View></View>
 {sections.map(([type,title,items])=><View key={type}><Text style={s.h2}>{title}</Text>{items.length?items.map(item=><View key={item.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{item.label||'Untitled'}</Text><Text style={s.meta}>Current: {item.visibility}{item.status?` · ${item.status}`:''}</Text></View><View style={s.pills}>{(['private','team','public'] as V[]).map(v=><Pressable key={v} onPress={()=>void setV(type,item,v)} style={[s.pill,item.visibility===v&&s.pillOn]}><Text style={item.visibility===v?s.pillTextOn:s.pillText}>{v}</Text></Pressable>)}</View></View>):<Text style={s.empty}>No {title.toLowerCase()} yet.</Text>}</View>)}
 <Text style={s.h2}>External provider connections</Text><Text style={s.copy}>Connected providers are not allowed to browse your Page. A future workflow can only send data covered by an explicit grant. Social graph/team-member access is not a grantable scope.</Text>{data.connections.map((c:any)=><View key={c.id} style={s.item}><View><Text style={s.itemTitle}>{c.name}</Text><Text style={s.meta}>{c.kind} · credential {c.hasCredential?'stored securely':'not stored'} · grant {c.grant?.status||'none'}</Text></View></View>)}{!!message&&<Text style={s.message}>{message}</Text>}</ScrollView></SafeAreaView>;
}
function Row({title,copy,value,onValue}:{title:string;copy:string;value:boolean;onValue:(v:boolean)=>void}){return <View style={s.row}><View style={{flex:1}}><Text style={s.itemTitle}>{title}</Text><Text style={s.meta}>{copy}</Text></View><Switch value={value} onValueChange={onValue}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f8fafc'},center:{flex:1,alignItems:'center',justifyContent:'center'},wrap:{padding:24,maxWidth:1050,width:'100%',alignSelf:'center'},back:{color:'#7c3aed',fontWeight:'900',marginBottom:20},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1.5,color:'#7c3aed'},title:{fontSize:34,fontWeight:'900',color:'#0f172a',marginTop:6},copy:{color:'#64748b',lineHeight:21,maxWidth:850,marginTop:8},card:{marginTop:22,backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0',borderRadius:18,paddingHorizontal:18},row:{flexDirection:'row',alignItems:'center',gap:18,paddingVertical:16,borderBottomWidth:1,borderBottomColor:'#f1f5f9'},notice:{flexDirection:'row',gap:12,backgroundColor:'#f0fdf4',borderWidth:1,borderColor:'#bbf7d0',borderRadius:16,padding:16,marginTop:16},noticeTitle:{fontWeight:'900',color:'#166534'},noticeText:{color:'#166534',lineHeight:20,marginTop:3},h2:{fontSize:21,fontWeight:'900',color:'#0f172a',marginTop:28,marginBottom:10},item:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0',borderRadius:14,padding:14,marginBottom:8,flexDirection:'row',gap:12,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap'},itemTitle:{fontWeight:'900',color:'#0f172a'},meta:{color:'#64748b',fontSize:12,marginTop:4,lineHeight:18},pills:{flexDirection:'row',gap:6,flexWrap:'wrap'},pill:{paddingVertical:7,paddingHorizontal:10,borderRadius:999,backgroundColor:'#f1f5f9'},pillOn:{backgroundColor:'#7c3aed'},pillText:{color:'#475569',fontSize:12,fontWeight:'800'},pillTextOn:{color:'#fff',fontSize:12,fontWeight:'900'},empty:{color:'#94a3b8'},message:{marginVertical:20,color:'#166534',fontWeight:'800'}});
