import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { Alert, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { PublisherProject } from "../types/publisher";
import { analyzeProjectStorage, exportProjectPackage, replaceProjectFont, scanFonts, scanLinkedAssets } from "../utils/projectProfessionalManager";
import { loadPublisherProject, savePublisherProject } from "../utils/publisherStorage";

const fmt=(n:number)=>n<1024?`${n} B`:n<1024*1024?`${(n/1024).toFixed(1)} KB`:`${(n/1024/1024).toFixed(1)} MB`;
const currentTimestamp=()=>Date.now();
const ask=(title:string,initial:string,run:(v:string)=>void)=>{if(Platform.OS==="web"&&typeof window!=="undefined"){const v=window.prompt(title,initial);if(v!==null)run(v)}else Alert.prompt?.(title,"",v=>run(v||""),"plain-text",initial)};
export default function ProfessionalFileTools(){
 const {projectId}=useLocalSearchParams<{projectId:string}>(); const [project,setProject]=useState<PublisherProject|null>(null); const [tab,setTab]=useState<"properties"|"assets"|"fonts"|"storage">("properties");
 const refresh=useCallback(async()=>{if(projectId)setProject(await loadPublisherProject(projectId))},[projectId]); useFocusEffect(useCallback(()=>{void refresh()},[refresh]));
 const assets=useMemo(()=>project?scanLinkedAssets(project):[],[project]); const fonts=useMemo(()=>project?scanFonts(project):[],[project]); const storage=useMemo(()=>project?analyzeProjectStorage(project):null,[project]);
 if(!project)return <SafeAreaView style={s.screen}><Text style={s.loading}>Loading project tools…</Text></SafeAreaView>;
 const save=async(next:PublisherProject)=>{setProject(next);await savePublisherProject(next,"Project properties updated")};
 const patch=(updates:Partial<PublisherProject>)=>void save({...project,...updates,updatedAt:currentTimestamp()});
 return <SafeAreaView style={s.screen}><View style={s.header}><Pressable style={s.back} onPress={()=>router.canGoBack() ? router.back() : router.replace("/" as never)}><Ionicons name="arrow-back" size={20} color="white"/></Pressable><View><Text style={s.eyebrow}>ASSETS & PACKAGING</Text><Text style={s.title}>{project.name}</Text></View><Pressable style={s.export} onPress={()=>void exportProjectPackage(project).catch(e=>Alert.alert("Package export failed",e.message))}><Ionicons name="archive-outline" size={18} color="white"/><Text style={s.exportText}>Export Package</Text></Pressable></View><View style={s.tabs}>{(["properties","assets","fonts","storage"] as const).map(v=><Pressable key={v} onPress={()=>setTab(v)} style={[s.tab,tab===v&&s.active]}><Text style={[s.tabText,tab===v&&s.activeText]}>{v[0].toUpperCase()+v.slice(1)}</Text></Pressable>)}</View><ScrollView contentContainerStyle={s.content}>
 {tab==="properties"&&<View style={s.card}><Text style={s.heading}>Project Properties</Text><Text style={s.label}>Project name</Text><TextInput style={s.input} value={project.name} onChangeText={name=>setProject({...project,name})} onBlur={()=>void save(project)}/><Text style={s.label}>Author</Text><TextInput style={s.input} value={project.author||""} onChangeText={author=>setProject({...project,author})} onBlur={()=>void save(project)}/><Text style={s.label}>Description</Text><TextInput style={[s.input,s.multiline]} multiline value={project.description||""} onChangeText={description=>setProject({...project,description})} onBlur={()=>void save(project)}/><Text style={s.label}>Tags (comma separated)</Text><TextInput style={s.input} value={(project.tags||[]).join(", ")} onChangeText={v=>setProject({...project,tags:v.split(",").map(x=>x.trim()).filter(Boolean)})} onBlur={()=>void save(project)}/><View style={s.row}><View style={s.field}><Text style={s.label}>DPI</Text><TextInput style={s.input} keyboardType="numeric" value={String(project.dpi||300)} onChangeText={v=>setProject({...project,dpi:Math.max(72,Number(v)||300)})} onBlur={()=>void save(project)}/></View><View style={s.field}><Text style={s.label}>Color mode</Text><View style={s.pills}>{(["RGB","CMYK"] as const).map(v=><Pressable key={v} style={[s.pill,project.colorMode===v&&s.pillActive]} onPress={()=>patch({colorMode:v})}><Text>{v}</Text></Pressable>)}</View></View></View><Text style={s.meta}>Created: {new Date(project.createdAt).toLocaleString()}</Text><Text style={s.meta}>Modified: {new Date(project.updatedAt).toLocaleString()}</Text><Text style={s.meta}>Pages: {project.pages.length} · First page: {project.pages[0]?.width} × {project.pages[0]?.height} · Margin {project.pages[0]?.margin} · Bleed {project.pages[0]?.bleed}</Text></View>}
 {tab==="assets"&&<View style={s.card}><Text style={s.heading}>Linked Assets ({assets.length})</Text>{assets.map(a=><View key={a.id} style={s.item}><Ionicons name={a.kind==="image"?"image-outline":"code-slash-outline"} size={20} color="#0F766E"/><View style={{flex:1}}><Text style={s.itemTitle}>{a.elementName}</Text><Text style={s.meta}>{a.embedded?"Embedded":"Linked"} · {a.missing?"Missing":"Available"} · {fmt(a.sizeBytes)}</Text><Text numberOfLines={1} style={s.uri}>{a.uri}</Text></View></View>)}{!assets.length&&<Text style={s.empty}>No linked images or SVG assets are used in this project.</Text>}<Text style={s.note}>Embedded assets travel inside the project package. Missing linked files are identified here so they can be replaced from the editor.</Text></View>}
 {tab==="fonts"&&<View style={s.card}><Text style={s.heading}>Font Diagnostics ({fonts.length})</Text>{fonts.map(f=><View key={f.fontFamily} style={s.item}><Ionicons name={f.available?"checkmark-circle":"warning"} size={20} color={f.available?"#059669":"#D97706"}/><View style={{flex:1}}><Text style={s.itemTitle}>{f.fontFamily}</Text><Text style={s.meta}>{f.usageCount} text object(s) · {f.available?"Available":"Missing or unavailable"}</Text></View>{!f.available&&<Pressable style={s.replace} onPress={()=>ask(`Replace ${f.fontFamily}`,"Arial",async value=>{const next=replaceProjectFont(project,f.fontFamily,value.trim()||"Arial");await save(next)})}><Text style={s.replaceText}>Replace</Text></Pressable>}</View>)}{!fonts.length&&<Text style={s.empty}>No text fonts are used in this project.</Text>}</View>}
 {tab==="storage"&&storage&&<View style={s.card}><Text style={s.heading}>Storage Analyzer</Text>{Object.entries({"Total estimated storage":storage.totalBytes,"Project data":storage.projectBytes,"Embedded assets":storage.embeddedAssetBytes}).map(([k,v])=><View key={k} style={s.stat}><Text style={s.statLabel}>{k}</Text><Text style={s.statValue}>{fmt(v)}</Text></View>)}<View style={s.grid}><Text style={s.metric}>{storage.pageCount}\n<Text style={s.metricLabel}>Pages</Text></Text><Text style={s.metric}>{storage.elementCount}\n<Text style={s.metricLabel}>Objects</Text></Text><Text style={s.metric}>{storage.linkedAssetCount}\n<Text style={s.metricLabel}>Assets</Text></Text><Text style={s.metric}>{storage.fontCount}\n<Text style={s.metricLabel}>Fonts</Text></Text></View><Text style={s.note}>Storage is calculated from the saved publication and embedded project assets. External browser/device caches are intentionally excluded.</Text></View>}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#EEF3F8"},loading:{padding:30},header:{minHeight:82,backgroundColor:"#0F1B27",paddingHorizontal:24,flexDirection:"row",alignItems:"center",gap:14},back:{width:38,height:38,borderRadius:8,backgroundColor:"#1D3042",alignItems:"center",justifyContent:"center"},eyebrow:{fontSize:10,color:"#5EEAD4",fontWeight:"900",letterSpacing:1},title:{fontSize:23,color:"white",fontWeight:"900"},export:{marginLeft:"auto",height:40,borderRadius:8,backgroundColor:"#0D9488",paddingHorizontal:14,flexDirection:"row",gap:8,alignItems:"center"},exportText:{color:"white",fontWeight:"800"},tabs:{backgroundColor:"white",paddingHorizontal:24,flexDirection:"row",gap:8,borderBottomWidth:1,borderBottomColor:"#CBD5E1"},tab:{paddingHorizontal:16,paddingVertical:14},active:{borderBottomWidth:3,borderBottomColor:"#0D9488"},tabText:{fontWeight:"700",color:"#64748B"},activeText:{color:"#0F766E"},content:{padding:24},card:{backgroundColor:"white",borderRadius:12,padding:20,maxWidth:980,width:"100%",alignSelf:"center"},heading:{fontSize:20,fontWeight:"900",color:"#17212B",marginBottom:18},label:{fontSize:12,fontWeight:"800",color:"#475569",marginBottom:6,marginTop:10},input:{borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,paddingHorizontal:12,paddingVertical:10,backgroundColor:"#F8FAFC"},multiline:{minHeight:90,textAlignVertical:"top"},row:{flexDirection:"row",gap:16},field:{flex:1},pills:{flexDirection:"row",gap:8},pill:{paddingHorizontal:16,paddingVertical:10,borderRadius:8,backgroundColor:"#E2E8F0"},pillActive:{backgroundColor:"#99F6E4",borderWidth:1,borderColor:"#0D9488"},meta:{fontSize:12,color:"#64748B",marginTop:7},item:{flexDirection:"row",alignItems:"center",gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:"#E2E8F0"},itemTitle:{fontWeight:"800",color:"#17212B"},uri:{fontSize:10,color:"#94A3B8",marginTop:3},replace:{paddingHorizontal:12,paddingVertical:8,borderRadius:7,backgroundColor:"#0F766E"},replaceText:{color:"white",fontWeight:"800"},empty:{paddingVertical:24,color:"#64748B"},note:{marginTop:18,padding:12,borderRadius:8,backgroundColor:"#F0FDFA",color:"#0F766E",fontSize:12},stat:{flexDirection:"row",justifyContent:"space-between",paddingVertical:12,borderBottomWidth:1,borderBottomColor:"#E2E8F0"},statLabel:{fontWeight:"700",color:"#475569"},statValue:{fontWeight:"900",color:"#0F766E"},grid:{flexDirection:"row",gap:10,marginTop:18},metric:{flex:1,textAlign:"center",padding:16,borderRadius:10,backgroundColor:"#F1F5F9",fontSize:24,fontWeight:"900",color:"#17212B"},metricLabel:{fontSize:11,fontWeight:"700",color:"#64748B"}});
