import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import { File as ExpoFile } from "expo-file-system";
import type { PublisherProject } from "../types/publisher";
import { analyzeProjectIntegrity, deduplicateProjectAssets, repairIntegrityIssue, repairProjectIntegrity, relinkProjectAsset, type IntegrityIssue } from "../utils/projectPhase8DManager";
import { listSavedPublisherProjects, loadPublisherProject, savePublisherProject } from "../utils/publisherStorage";

export default function ProjectDiagnosticsScreen(){
 const {projectId}=useLocalSearchParams<{projectId?:string}>();const[project,setProject]=useState<PublisherProject|null>(null),[busy,setBusy]=useState(false),[readOnly,setReadOnly]=useState(false),[ignored,setIgnored]=useState<string[]>([]);
 useEffect(()=>{if(!projectId)return;void Promise.all([loadPublisherProject(projectId),listSavedPublisherProjects()]).then(([p,index])=>{setProject(p);setReadOnly(Boolean(index.find(x=>x.id===projectId)?.readOnly));});},[projectId]);
 const report=useMemo(()=>project?analyzeProjectIntegrity(project):null,[project]);
 const save=async(next:PublisherProject,label:string)=>{if(readOnly){Alert.alert("Read-only project","Use Save As in the editor before making diagnostic repairs.");return;}setBusy(true);try{await savePublisherProject(next,label);setProject(next);Alert.alert("Complete",label);}catch(e){Alert.alert("Unable to save",e instanceof Error?e.message:"Unknown error");}finally{setBusy(false);}};
 const act=async(issue:IntegrityIssue,action:"repair"|"remove"|"replace"|"relink"|"ignore")=>{if(action==="ignore"){setIgnored(v=>[...v,issue.id]);return;}if(action==="relink"){try{let source:string|null=null;if(Platform.OS==="web"&&typeof document!=="undefined"){source=await new Promise((resolve,reject)=>{const input=document.createElement("input");input.type="file";input.accept="image/*,.svg";input.onchange=()=>{const file=input.files?.[0];if(!file)return resolve(null);const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||""));reader.onerror=()=>reject(new Error("Unable to read asset."));if(file.type.includes("svg"))reader.readAsText(file);else reader.readAsDataURL(file);};input.click();});}else{const picked=await DocumentPicker.getDocumentAsync({type:["image/*","image/svg+xml"],copyToCacheDirectory:true});if(!picked.canceled&&picked.assets[0]){const asset=picked.assets[0];source=asset.mimeType?.includes("svg")?await new ExpoFile(asset.uri).text():asset.uri;}}if(source&&issue.pageId&&issue.elementId)await save(relinkProjectAsset(project!,issue.pageId,issue.elementId,source),`Relink: ${issue.message}`);}catch(e){Alert.alert("Relink failed",e instanceof Error?e.message:"Unable to relink asset");}return;}void save(repairIntegrityIssue(project!,issue,action),`${action[0].toUpperCase()+action.slice(1)}: ${issue.message}`);};
 if(!project||!report)return <SafeAreaView style={s.screen}><Text style={s.loading}>Loading diagnostics…</Text></SafeAreaView>;
 const issues=report.issues.filter(i=>!ignored.includes(i.id));
 return <SafeAreaView style={s.screen}><View style={s.header}><Pressable onPress={()=>router.canGoBack() ? router.back() : router.replace("/" as never)} style={s.icon}><Ionicons name="arrow-back" size={20} color="white"/></Pressable><View><Text style={s.eyebrow}>PROJECT INTEGRITY & DIAGNOSTICS</Text><Text style={s.title}>{project.name}</Text></View>{readOnly&&<View style={s.readOnly}><Ionicons name="lock-closed" size={15} color="#92400E"/><Text style={s.readOnlyText}>Read only</Text></View>}</View>
 <ScrollView contentContainerStyle={s.content}><View style={s.summary}>{[["Issues",issues.length],["Missing assets",report.missingAssets],["Missing fonts",report.missingFonts],["Duplicate assets",report.duplicateAssets],["Empty pages",report.emptyPages],["Oversized images",report.oversizedImages]].map(([l,v])=><View key={String(l)} style={s.metric}><Text style={s.metricValue}>{v}</Text><Text style={s.metricLabel}>{l}</Text></View>)}</View>
 <View style={s.actions}><Pressable disabled={busy||readOnly} style={[s.primary,(busy||readOnly)&&s.disabled]} onPress={()=>void save(repairProjectIntegrity(project),"Full integrity repair")}><Text style={s.primaryText}>Repair All Safe Issues</Text></Pressable><Pressable disabled={busy||readOnly} style={[s.secondary,(busy||readOnly)&&s.disabled]} onPress={()=>{const r=deduplicateProjectAssets(project);void save(r.project,`Asset compaction: ${r.duplicates} duplicates, ${r.bytesSaved} bytes removed`);}}><Text style={s.secondaryText}>Compact Duplicate Assets</Text></Pressable></View>
 <Text style={s.section}>Diagnostic Report</Text>{issues.length?issues.map(issue=><View key={issue.id} style={s.issue}><Ionicons name={issue.severity==="error"?"alert-circle":issue.severity==="warning"?"warning":"information-circle"} size={20} color={issue.severity==="error"?"#B91C1C":issue.severity==="warning"?"#B45309":"#0369A1"}/><View style={s.issueBody}><Text style={s.issueText}>{issue.message}</Text><View style={s.issueActions}>{issue.actions.map(a=><Pressable key={a} disabled={busy||(readOnly&&a!=="ignore")} style={s.issueButton} onPress={()=>void act(issue,a)}><Text style={s.issueButtonText}>{a==="replace"?"Replace with Arial":a==="relink"?"Relink File":a[0].toUpperCase()+a.slice(1)}</Text></Pressable>)}</View></View></View>):<View style={s.clean}><Ionicons name="checkmark-circle" size={42} color="#0D9488"/><Text style={s.cleanTitle}>No integrity problems found</Text></View>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#EEF3F8"},loading:{padding:30},header:{minHeight:86,backgroundColor:"#0F1B27",paddingHorizontal:24,flexDirection:"row",alignItems:"center",gap:14},icon:{width:38,height:38,borderRadius:8,backgroundColor:"#1D3042",alignItems:"center",justifyContent:"center"},eyebrow:{color:"#5EEAD4",fontSize:10,fontWeight:"900",letterSpacing:1.2},title:{color:"white",fontSize:23,fontWeight:"900"},readOnly:{marginLeft:"auto",flexDirection:"row",gap:6,backgroundColor:"#FEF3C7",padding:8,borderRadius:8},readOnlyText:{color:"#92400E",fontWeight:"800"},content:{padding:26,gap:16},summary:{flexDirection:"row",flexWrap:"wrap",gap:12},metric:{minWidth:145,backgroundColor:"white",padding:16,borderRadius:12,borderWidth:1,borderColor:"#D9E2EA"},metricValue:{fontSize:26,fontWeight:"900",color:"#0F766E"},metricLabel:{fontSize:11,color:"#64748B",marginTop:4},actions:{flexDirection:"row",gap:10},primary:{backgroundColor:"#0D9488",paddingHorizontal:16,paddingVertical:12,borderRadius:8},primaryText:{color:"white",fontWeight:"900"},secondary:{backgroundColor:"white",paddingHorizontal:16,paddingVertical:12,borderRadius:8,borderWidth:1,borderColor:"#CBD5E1"},secondaryText:{fontWeight:"900",color:"#0F766E"},disabled:{opacity:.45},section:{fontSize:16,fontWeight:"900",color:"#17212B"},issue:{flexDirection:"row",gap:12,backgroundColor:"white",borderRadius:10,padding:14,borderWidth:1,borderColor:"#D9E2EA"},issueBody:{flex:1},issueText:{fontWeight:"700",color:"#334155"},issueActions:{flexDirection:"row",flexWrap:"wrap",gap:7,marginTop:10},issueButton:{paddingHorizontal:10,paddingVertical:7,borderRadius:6,backgroundColor:"#E2E8F0"},issueButtonText:{fontSize:11,fontWeight:"800",color:"#334155"},clean:{alignItems:"center",padding:40},cleanTitle:{fontSize:18,fontWeight:"900",marginTop:10,color:"#0F766E"}});
