import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '../context/AuthContext';

type Role='owner'|'admin'|'editor'|'store_manager'|'viewer';
type Member={id:string;userId:string;email:string;role:Role};
type Invite={id:string;email:string;role:Role;status:string};
const roles:Role[]=['admin','editor','store_manager','viewer'];
export default function SpaceTeam(){
 const {spaceId}=useLocalSearchParams<{spaceId:string}>(); const auth=useAuth();
 const [members,setMembers]=useState<Member[]>([]),[invites,setInvites]=useState<Invite[]>([]),[email,setEmail]=useState(''),[role,setRole]=useState<Role>('editor'),[message,setMessage]=useState('');
 const load=async()=>{if(!spaceId)return;const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/team`);if(r.ok){const j=await r.json();setMembers(j.members||[]);setInvites(j.invites||[])}};
 useEffect(()=>{if(!spaceId)return;let active=true;void auth.authorizedFetch(`/api/v1/spaces/${spaceId}/team`).then(async r=>r.ok?await r.json():null).then(data=>{if(active&&data){setMembers(data.members||[]);setInvites(data.invites||[])}});return()=>{active=false}},[auth,spaceId]);
 const invite=async()=>{if(!email.trim()||!spaceId)return;const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/team/invites`,{method:'POST',body:JSON.stringify({email,role})});const j=await r.json();setMessage(r.ok?(j.accepted?'Member added.':'Invite created.'):(j.error?.message||'Could not invite member.'));if(r.ok){setEmail('');void load()}};
 const change=async(m:Member,next:Role)=>{const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/team/members/${m.id}`,{method:'PATCH',body:JSON.stringify({role:next})});if(r.ok)void load();else setMessage((await r.json()).error?.message||'Could not change role.')};
 const remove=async(m:Member)=>{const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/team/members/${m.id}`,{method:'DELETE'});if(r.ok)void load();else setMessage((await r.json()).error?.message||'Could not remove member.')};
 const revoke=async(i:Invite)=>{const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/team/invites/${i.id}`,{method:'DELETE'});if(r.ok)void load()};
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.wrap}><Pressable onPress={()=>router.push(`/ai-page?spaceId=${spaceId}` as any)}><Text style={s.back}>← Back to AI Page</Text></Pressable><View style={s.head}><View><Text style={s.title}>Team</Text><Text style={s.copy}>Page permissions apply only to this AI Page. They never grant Yaposan platform-admin access.</Text></View><View style={s.badge}><Ionicons name="shield-checkmark" size={18} color="#6d28d9"/><Text style={s.badgeText}>PAGE-SCOPED</Text></View></View>
 <View style={s.card}><Text style={s.h2}>Invite or add a member</Text><Text style={s.copy}>Registered users are added immediately. Other email addresses remain pending invitations.</Text><View style={s.form}><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" placeholder="person@example.com" style={[s.input,{flex:1}]}/><View style={s.roles}>{roles.map(x=><Pressable key={x} onPress={()=>setRole(x)} style={[s.pill,role===x&&s.pillOn]}><Text style={role===x?s.pillTextOn:s.pillText}>{x.replace('_',' ')}</Text></Pressable>)}</View><Pressable style={s.primary} onPress={()=>void invite()}><Text style={s.primaryText}>Invite</Text></Pressable></View>{!!message&&<Text style={s.message}>{message}</Text>}</View>
 <Text style={s.section}>Members</Text><View style={s.grid}>{members.map(m=><View key={m.id} style={s.member}><View style={s.avatar}><Text style={s.avatarText}>{m.email[0]?.toUpperCase()}</Text></View><Text style={s.memberEmail}>{m.email}</Text><Text style={s.role}>{m.role.replace('_',' ')}</Text>{m.role!=='owner'&&<><View style={s.roles}>{roles.map(x=><Pressable key={x} onPress={()=>void change(m,x)} style={[s.smallPill,m.role===x&&s.pillOn]}><Text style={m.role===x?s.pillTextOn:s.smallText}>{x==='store_manager'?'store':x}</Text></Pressable>)}</View><Pressable onPress={()=>void remove(m)}><Text style={s.remove}>Remove from Page</Text></Pressable></>}</View>)}</View>
 {invites.length>0&&<><Text style={s.section}>Pending invitations</Text><View style={s.grid}>{invites.map(i=><View key={i.id} style={s.member}><Ionicons name="mail-unread-outline" size={26} color="#6d28d9"/><Text style={s.memberEmail}>{i.email}</Text><Text style={s.role}>{i.role.replace('_',' ')}</Text><Pressable onPress={()=>void revoke(i)}><Text style={s.remove}>Revoke invite</Text></Pressable></View>)}</View></>}
 <View style={s.note}><Text style={s.h2}>Permission model</Text><Text style={s.copy}>Owner: full control · Admin: Space administration · Editor: AI/Studio/content creation · Store Manager: store products/orders · Viewer: read/use shared resources.</Text></View>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f7f5ff'},wrap:{padding:24,maxWidth:1260,width:'100%',alignSelf:'center'},back:{color:'#6d28d9',fontWeight:'800'},head:{marginTop:18,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:12,flexWrap:'wrap'},title:{fontSize:36,fontWeight:'900',color:'#111827'},copy:{color:'#64748b',lineHeight:21,maxWidth:760,marginTop:5},badge:{flexDirection:'row',gap:6,alignItems:'center',backgroundColor:'#ede9fe',padding:10,borderRadius:999},badgeText:{color:'#6d28d9',fontWeight:'900',fontSize:12},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e7eb',borderRadius:18,padding:18,marginTop:22},h2:{fontSize:20,fontWeight:'900',color:'#111827'},form:{flexDirection:'row',gap:10,alignItems:'center',marginTop:15,flexWrap:'wrap'},input:{borderWidth:1,borderColor:'#d1d5db',borderRadius:10,padding:11,minWidth:240},roles:{flexDirection:'row',gap:5,flexWrap:'wrap'},pill:{backgroundColor:'#f1f5f9',paddingHorizontal:9,paddingVertical:8,borderRadius:999},pillOn:{backgroundColor:'#6d28d9'},pillText:{color:'#475569',fontWeight:'700',fontSize:12,textTransform:'capitalize'},pillTextOn:{color:'#fff',fontWeight:'800',fontSize:12,textTransform:'capitalize'},primary:{backgroundColor:'#6d28d9',paddingHorizontal:18,paddingVertical:11,borderRadius:10},primaryText:{color:'#fff',fontWeight:'900'},message:{color:'#047857',fontWeight:'800',marginTop:10},section:{fontSize:23,fontWeight:'900',color:'#111827',marginTop:26,marginBottom:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},member:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e7eb',borderRadius:16,padding:16,minWidth:270,flexGrow:1,flexBasis:300},avatar:{width:42,height:42,borderRadius:21,backgroundColor:'#7c3aed',alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontWeight:'900',fontSize:18},memberEmail:{fontWeight:'900',color:'#111827',marginTop:10},role:{color:'#6d28d9',fontWeight:'800',textTransform:'capitalize',marginVertical:7},smallPill:{backgroundColor:'#f1f5f9',paddingHorizontal:7,paddingVertical:6,borderRadius:999},smallText:{color:'#64748b',fontWeight:'700',fontSize:11},remove:{color:'#dc2626',fontWeight:'800',marginTop:10},note:{backgroundColor:'#ede9fe',padding:18,borderRadius:16,marginTop:24}})
