import {Ionicons} from '@expo/vector-icons';
import {router,useLocalSearchParams} from 'expo-router';
import {useEffect,useState} from 'react';
import {Pressable,SafeAreaView,ScrollView,StyleSheet,Switch,Text,View} from 'react-native';
import {useAuth} from '../context/AuthContext';
export default function SpaceSecurity(){
 const {spaceId}=useLocalSearchParams<{spaceId:string}>();const auth=useAuth();const [settings,setSettings]=useState<any>(null),[msg,setMsg]=useState('');
 const load=async()=>{if(!spaceId)return;const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/security`);if(r.ok)setSettings((await r.json()).settings)};
 useEffect(()=>{if(!spaceId)return;let active=true;void auth.authorizedFetch(`/api/v1/spaces/${spaceId}/security`).then(async r=>r.ok?await r.json():null).then(data=>{if(active&&data)setSettings(data.settings)});return()=>{active=false}},[auth,spaceId]);
 const patch=async(p:any)=>{const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/security`,{method:'PATCH',body:JSON.stringify(p)});const d=await r.json();if(r.ok){setSettings(d.settings);setMsg('Security policy saved.')}else setMsg(d.error?.message==='STEP_UP_REQUIRED'?'Verify with a passkey or MFA before changing protected Page security settings.':d.error?.message||'Could not update security policy.')};
 if(!settings)return <SafeAreaView style={s.center}><Text>Loading Page security…</Text></SafeAreaView>;
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.wrap}><Pressable onPress={()=>router.push(`/privacy-settings?spaceId=${spaceId}` as any)}><Text style={s.back}>← Privacy & Sharing</Text></Pressable><Text style={s.kicker}>SPACE SECURITY • </Text><Text style={s.title}>Security belongs to each Space.</Text><Text style={s.copy}>Every creator page has its own protection policy. Public publishing, team administration, external connections and uploads are independently controlled. Frontend role labels never authorize sensitive actions—the server enforces Page permissions and assurance.</Text>
 <View style={s.notice}><Ionicons name="key-outline" size={24} color="#166534"/><View style={{flex:1}}><Text style={s.noticeTitle}>Passkey / MFA step-up</Text><Text style={s.noticeText}>For protected actions, a password-only session is not enough. Production deployments should use Keycloak or ZITADEL through OIDC and prefer passkeys, with authenticator MFA as fallback.</Text></View></View>
 <View style={s.card}><Row title="Require passkey/MFA before public sharing" copy="Protects creator-page publishing and resources being changed to public/unlisted/paid." value={settings.requireStepUpForPublicSharing} onValue={v=>void patch({requireStepUpForPublicSharing:v})}/><Row title="Require passkey/MFA for team administration" copy="Protects changes to this security policy and other privileged team actions." value={settings.requireStepUpForTeamAdmin} onValue={v=>void patch({requireStepUpForTeamAdmin:v})}/><Row title="Allow external AI/API connections" copy="Off by default. Privacy data grants are still required separately." value={settings.allowExternalConnections} onValue={v=>void patch({allowExternalConnections:v})}/><Row title="Allow public comments" copy="Keep off when the page is portfolio-only or moderation is unavailable." value={settings.allowPublicComments} onValue={v=>void patch({allowPublicComments:v})}/><Row title="Allow public file downloads" copy="Files remain private unless the page and resource policy explicitly allow a clean asset." value={settings.allowFileDownloads} onValue={v=>void patch({allowFileDownloads:v})}/><Row title="Security alerts" copy="Keep login, sharing and policy-change alerts enabled for this Page." value={settings.securityAlerts} onValue={v=>void patch({securityAlerts:v})}/></View>
 <Text style={s.h2}>Default controls</Text><View style={s.grid}><View style={s.small}><Text style={s.smallTitle}>Invites</Text><Text style={s.meta}>{settings.invitePolicy==='owner_only'?'Owner only':'Owner and admins'}</Text><View style={s.pills}>{['admins_only','owner_only'].map(x=><Pressable key={x} onPress={()=>void patch({invitePolicy:x})} style={[s.pill,settings.invitePolicy===x&&s.pillOn]}><Text style={settings.invitePolicy===x?s.pillTextOn:s.pillText}>{x==='owner_only'?'Owner only':'Admins'}</Text></Pressable>)}</View></View><View style={s.small}><Text style={s.smallTitle}>Upload policy</Text><Text style={s.meta}>Strict quarantines active/archive and large files until malware scanning.</Text><View style={s.pills}>{['strict','standard'].map(x=><Pressable key={x} onPress={()=>void patch({uploadPolicy:x})} style={[s.pill,settings.uploadPolicy===x&&s.pillOn]}><Text style={settings.uploadPolicy===x?s.pillTextOn:s.pillText}>{x}</Text></Pressable>)}</View></View></View>
 {!!msg&&<Text style={s.message}>{msg}</Text>}<Pressable onPress={()=>router.push('/account-security' as any)} style={s.sessions}><Ionicons name="phone-portrait-outline" size={20}/><View><Text style={s.smallTitle}>Account sessions & devices</Text><Text style={s.meta}>Review and revoke active Yaposan sessions.</Text></View></Pressable></ScrollView></SafeAreaView>
}
function Row({title,copy,value,onValue}:{title:string;copy:string;value:boolean;onValue:(v:boolean)=>void}){return <View style={s.row}><View style={{flex:1}}><Text style={s.smallTitle}>{title}</Text><Text style={s.meta}>{copy}</Text></View><Switch value={value} onValueChange={onValue}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f8fafc'},center:{flex:1,alignItems:'center',justifyContent:'center'},wrap:{padding:24,maxWidth:1000,width:'100%',alignSelf:'center'},back:{color:'#7c3aed',fontWeight:'900',marginBottom:20},kicker:{fontSize:12,fontWeight:'900',letterSpacing:1.4,color:'#0f766e'},title:{fontSize:34,fontWeight:'900',color:'#0f172a',marginTop:6},copy:{color:'#64748b',lineHeight:21,marginTop:8,maxWidth:850},notice:{flexDirection:'row',gap:12,backgroundColor:'#f0fdf4',borderWidth:1,borderColor:'#bbf7d0',borderRadius:16,padding:16,marginTop:18},noticeTitle:{fontWeight:'900',color:'#166534'},noticeText:{color:'#166534',lineHeight:20,marginTop:3},card:{marginTop:18,backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0',borderRadius:18,paddingHorizontal:18},row:{flexDirection:'row',alignItems:'center',gap:16,paddingVertical:16,borderBottomWidth:1,borderBottomColor:'#f1f5f9'},smallTitle:{fontWeight:'900',color:'#0f172a'},meta:{fontSize:12,color:'#64748b',lineHeight:18,marginTop:4},h2:{fontSize:20,fontWeight:'900',color:'#0f172a',marginTop:28,marginBottom:10},grid:{flexDirection:'row',gap:12,flexWrap:'wrap'},small:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0',padding:16,borderRadius:16,minWidth:280,flex:1},pills:{flexDirection:'row',gap:7,marginTop:12},pill:{paddingVertical:7,paddingHorizontal:10,borderRadius:999,backgroundColor:'#f1f5f9'},pillOn:{backgroundColor:'#0f766e'},pillText:{fontSize:12,fontWeight:'800',color:'#475569'},pillTextOn:{fontSize:12,fontWeight:'900',color:'#fff'},message:{fontWeight:'800',color:'#166534',marginTop:18},sessions:{marginTop:20,flexDirection:'row',alignItems:'center',gap:12,backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0',borderRadius:14,padding:15}});
