import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '../context/AuthContext';
import { YAPOSAN_TOOL_CATALOG } from '../constants/yaposanTools';

type NodeKind='input'|'tool'|'ai'|'compute'|'output';
type Node={id:string;kind:NodeKind;name:string;refId?:string;config?:Record<string,unknown>};
type Studio={id:string;name:string;description?:string;visibility:'private'|'team'|'public'|'paid';status:string;nodes:Node[];edges:{from:string;to:string}[];version:number};
const kinds:{kind:NodeKind;label:string;icon:any}[]=[{kind:'input',label:'Upload / Input',icon:'cloud-upload-outline'},{kind:'tool',label:'Yaposan Tool',icon:'construct-outline'},{kind:'ai',label:'My AI',icon:'sparkles-outline'},{kind:'compute',label:'Compute / GPU',icon:'hardware-chip-outline'},{kind:'output',label:'Publish / Output',icon:'send-outline'}];

export default function StudioBuilder(){
 const {spaceId}=useLocalSearchParams<{spaceId:string}>();const auth=useAuth();
 const [studios,setStudios]=useState<Studio[]>([]),[selected,setSelected]=useState<Studio|null>(null),[resources,setResources]=useState<any>({ai:[],compute:[]});
 const [name,setName]=useState('My New Studio'),[runInput,setRunInput]=useState('Upload product'),[message,setMessage]=useState('');
 const actionSeq=useRef(0);
 const load=useCallback(async()=>{if(!spaceId)return;const [sr,rr]=await Promise.all([auth.authorizedFetch(`/api/v1/spaces/${spaceId}/studios`),auth.authorizedFetch(`/api/v1/spaces/${spaceId}/resources`)]);if(sr.ok){const j=await sr.json();setStudios(j.items||[]);setSelected(current=>current??j.items?.[0]??null)}if(rr.ok)setResources(await rr.json())},[auth.authorizedFetch,spaceId]);
 useEffect(()=>{queueMicrotask(()=>{void load()})},[load]);
 const create=async()=>{if(!spaceId)return;const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/studios`,{method:'POST',body:JSON.stringify({name,visibility:'private',nodes:[{id:'input-1',kind:'input',name:'Start here'},{id:'output-1',kind:'output',name:'Final output'}],edges:[{from:'input-1',to:'output-1'}]})});if(r.ok){const j=await r.json();setSelected(j.studio);setMessage('Studio created. Add blocks to build your workflow.');void load()}};
 const save=async(nextNodes:Node[],visibility=selected?.visibility||'private',status=selected?.status||'draft')=>{if(!spaceId||!selected)return;const edges=nextNodes.slice(0,-1).map((n,i)=>({from:n.id,to:nextNodes[i+1].id}));const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/studios/${selected.id}`,{method:'PATCH',body:JSON.stringify({nodes:nextNodes,edges,visibility,status})});if(r.ok){const j=await r.json();setSelected(j.studio);setMessage('Saved')}};
 const addBlock=async(kind:NodeKind)=>{if(!selected)return;let refId:string|undefined;let label=kinds.find(x=>x.kind===kind)?.label||kind;if(kind==='tool'){const t=YAPOSAN_TOOL_CATALOG[0];refId=t.id;label=t.name}if(kind==='ai'&&resources.ai?.[0]){refId=resources.ai[0].id;label=resources.ai[0].name}if(kind==='compute'&&resources.compute?.[0]){refId=resources.compute[0].id;label=resources.compute[0].name}actionSeq.current+=1;const node={id:`${kind}-${actionSeq.current}`,kind,name:label,refId};const base=selected.nodes.filter(n=>n.kind!=='output');const output=selected.nodes.find(n=>n.kind==='output');await save([...base,node,...(output?[output]:[])]);};
 const remove=async(id:string)=>{if(!selected)return;await save(selected.nodes.filter(n=>n.id!==id));};
 const move=async(index:number,delta:number)=>{if(!selected)return;const next=[...selected.nodes];const target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];await save(next)};
 const executeRun=async(approvedNodeIds:string[]=[])=>{if(!spaceId||!selected)return;setMessage('Running Studio…');actionSeq.current+=1;const executionKey=`studio-ui:${selected.id}:${actionSeq.current}`;const r=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/studios/${selected.id}/run`,{method:'POST',body:JSON.stringify({input:{text:runInput},approvedNodeIds,executionKey})});const j=await r.json();setMessage(r.ok?`Run succeeded · ${j.run.steps.length} steps · trace ${String(j.run.traceId||'').slice(0,8)}`:`Run failed: ${j.error?.message||'Unknown error'}`)};
 const run=async()=>{if(!spaceId||!selected)return;setMessage('Checking workflow permissions…');const pr=await auth.authorizedFetch(`/api/v1/spaces/${spaceId}/studios/${selected.id}/plan`);const pj=await pr.json();if(!pr.ok){setMessage(`Could not inspect workflow: ${pj.error?.message||'Unknown error'}`);return}const plan=pj.plan;const approvals:string[]=plan.requiredApprovalNodeIds||[];if(!approvals.length){await executeRun([]);return}const names=(plan.nodes||[]).filter((n:any)=>approvals.includes(n.nodeId)).map((n:any)=>`${n.name}: ${(n.sideEffects||[]).join(', ')||n.risk}`).join('\n');Alert.alert('Approve workflow actions',`This run includes actions that need your approval before execution:\n\n${names}`,[{text:'Cancel',style:'cancel',onPress:()=>setMessage('Run cancelled before execution.')},{text:'Approve & Run',onPress:()=>void executeRun(approvals)}]);};
 const palette=useMemo(()=>kinds,[]);
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.wrap}>
  <View style={s.top}><Pressable onPress={()=>router.push(`/ai-page?spaceId=${spaceId}` as any)}><Text style={s.back}>← Back to AI Page</Text></Pressable><Text style={s.badge}>NO-CODE STUDIO</Text></View>
  <Text style={s.title}>Studio Builder</Text><Text style={s.copy}>Build an AI-powered business workflow by adding blocks. No Python, Docker, terminal or Git required.</Text>
  <View style={s.layout}>
   <View style={s.left}><Text style={s.h2}>My Studios</Text><View style={s.newRow}><TextInput value={name} onChangeText={setName} style={s.input}/><Pressable style={s.primary} onPress={()=>void create()}><Text style={s.primaryText}>+ New Studio</Text></Pressable></View>{studios.map(x=><Pressable key={x.id} style={[s.studioRow,selected?.id===x.id&&s.selected]} onPress={()=>setSelected(x)}><Text style={s.studioName}>{x.name}</Text><Text style={s.small}>{x.visibility} · v{x.version}</Text></Pressable>)}</View>
   <View style={s.main}>{selected?<><View style={s.head}><View><Text style={s.h2}>{selected.name}</Text><Text style={s.small}>Drag-and-drop style workflow · use arrows to reorder blocks</Text></View><View style={s.visibility}>{(['private','team','public','paid'] as const).map(v=><Pressable key={v} onPress={()=>void save(selected.nodes,v)} style={[s.pill,selected.visibility===v&&s.pillOn]}><Text style={selected.visibility===v?s.pillTextOn:s.pillText}>{v==='private'?'🔒':v==='team'?'👥':v==='public'?'🌎':'💰'} {v}</Text></Pressable>)}</View><View style={{flexDirection:'row',gap:8,marginTop:10}}><Pressable style={s.primary} onPress={()=>void save(selected.nodes,'public','published')}><Text style={s.primaryText}>Publish Studio</Text></Pressable>{selected.status==='published'&&<Text style={[s.small,{alignSelf:'center'}]}>Published · visible when your AI Page is public</Text>}</View></View>
    <View style={s.palette}><Text style={s.paletteTitle}>Add a block</Text>{palette.map(x=><Pressable key={x.kind} style={s.paletteBtn} onPress={()=>void addBlock(x.kind)}><Ionicons name={x.icon} size={18} color="#6d28d9"/><Text style={s.paletteText}>+ {x.label}</Text></Pressable>)}</View>
    <View style={s.flow}>{selected.nodes.map((n,i)=><View key={n.id}><View style={s.node}><View style={s.nodeIcon}><Ionicons name={(kinds.find(x=>x.kind===n.kind)?.icon||'cube-outline') as any} size={22} color="#fff"/></View><View style={{flex:1}}><Text style={s.nodeTitle}>{n.name}</Text><Text style={s.small}>{n.kind}{n.refId?` · ${n.refId}`:''}</Text></View><Pressable onPress={()=>void move(i,-1)}><Text style={s.move}>↑</Text></Pressable><Pressable onPress={()=>void move(i,1)}><Text style={s.move}>↓</Text></Pressable><Pressable onPress={()=>void remove(n.id)}><Text style={s.remove}>×</Text></Pressable></View>{i<selected.nodes.length-1&&<Text style={s.arrow}>↓</Text>}</View>)}</View>
    <View style={s.runBox}><Text style={s.h2}>Test this Studio</Text><TextInput value={runInput} onChangeText={setRunInput} style={s.input} placeholder="Example input"/><Pressable style={s.run} onPress={()=>void run()}><Ionicons name="play" color="#fff" size={18}/><Text style={s.primaryText}>Run workflow</Text></Pressable>{!!message&&<Text style={s.message}>{message}</Text>}</View>
   </>:<View style={s.empty}><Text style={s.h2}>Create your first Studio</Text><Text style={s.copy}>Start with Input → Output, then add Yaposan tools, your AI and your compute.</Text></View>}</View>
  </View>
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f6f3ff'},wrap:{padding:24,maxWidth:1440,width:'100%',alignSelf:'center'},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{color:'#6d28d9',fontWeight:'800'},badge:{color:'#6d28d9',fontWeight:'900',fontSize:12},title:{fontSize:36,fontWeight:'900',color:'#111827',marginTop:20},copy:{color:'#64748b',marginTop:6,maxWidth:760,lineHeight:22},layout:{flexDirection:'row',gap:18,marginTop:24,alignItems:'flex-start',flexWrap:'wrap'},left:{width:280,backgroundColor:'#fff',borderRadius:18,padding:16,borderWidth:1,borderColor:'#e5e7eb'},main:{flex:1,minWidth:550,backgroundColor:'#fff',borderRadius:18,padding:20,borderWidth:1,borderColor:'#e5e7eb'},h2:{fontSize:20,fontWeight:'900',color:'#111827'},newRow:{gap:8,marginVertical:12},input:{borderWidth:1,borderColor:'#d1d5db',borderRadius:10,padding:11,backgroundColor:'#fff'},primary:{backgroundColor:'#6d28d9',padding:11,borderRadius:10,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},studioRow:{padding:12,borderRadius:10,marginBottom:6,backgroundColor:'#f8fafc'},selected:{backgroundColor:'#ede9fe'},studioName:{fontWeight:'800',color:'#111827'},small:{fontSize:12,color:'#64748b',marginTop:3},head:{gap:12},visibility:{flexDirection:'row',gap:6,flexWrap:'wrap',marginTop:10},pill:{paddingHorizontal:10,paddingVertical:7,borderRadius:999,backgroundColor:'#f1f5f9'},pillOn:{backgroundColor:'#6d28d9'},pillText:{fontSize:12,color:'#475569',fontWeight:'700',textTransform:'capitalize'},pillTextOn:{fontSize:12,color:'#fff',fontWeight:'800',textTransform:'capitalize'},palette:{marginTop:18,padding:14,borderRadius:14,backgroundColor:'#faf5ff',flexDirection:'row',gap:8,alignItems:'center',flexWrap:'wrap'},paletteTitle:{fontWeight:'900',color:'#111827',marginRight:4},paletteBtn:{flexDirection:'row',gap:5,alignItems:'center',backgroundColor:'#fff',borderRadius:9,padding:9,borderWidth:1,borderColor:'#ddd6fe'},paletteText:{color:'#6d28d9',fontWeight:'800',fontSize:12},flow:{maxWidth:620,width:'100%',alignSelf:'center',marginVertical:25},node:{flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:'#ddd6fe',borderRadius:15,padding:14,backgroundColor:'#fff',shadowColor:'#000',shadowOpacity:.05,shadowRadius:8},nodeIcon:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:'#7c3aed'},nodeTitle:{fontWeight:'900',fontSize:15,color:'#111827'},arrow:{textAlign:'center',fontSize:25,color:'#8b5cf6',fontWeight:'900',lineHeight:30},move:{fontSize:20,color:'#6d28d9',padding:4},remove:{fontSize:24,color:'#dc2626',padding:4},runBox:{padding:16,borderRadius:14,backgroundColor:'#f8fafc'},run:{marginTop:10,backgroundColor:'#111827',padding:12,borderRadius:10,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:8},message:{color:'#047857',fontWeight:'800',marginTop:10},empty:{padding:40,alignItems:'center'}});
