import Head from 'expo-router/head';
import {useEffect,useMemo,useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import Phase241IShell from '../components/workspace/Phase241IShell';
import {useAuth} from '../context/AuthContext';
import {downloadProtectedSupportAttachment} from '../utils/supportTransport';
type Ticket={id:string;name:string;email:string;subject:string;category:string;priority:string;status:string;createdAt:string;updatedAt:string;attachmentName?:string;source?:string;page?:string;action?:string}; type Message={id:string;authorType:string;body:string;createdAt:string};
const statuses=['open','in_progress','waiting_for_user','resolved','closed']; const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function SupportInbox(){const auth=useAuth();const token=auth.session?.accessToken;const base=process.env.EXPO_PUBLIC_API_URL ?? (typeof window !== "undefined" && !["localhost", "127.0.0.1"].includes(window.location.hostname) ? "https://api.yaposan.com" : "http://localhost:4100");const [items,setItems]=useState<Ticket[]>([]);const [selected,setSelected]=useState<Ticket>();const [messages,setMessages]=useState<Message[]>([]);const [q,setQ]=useState('');const [status,setStatus]=useState('');const [note,setNote]=useState('');const [error,setError]=useState('');const headers=useMemo(()=>token?{authorization:`Bearer ${token}`}:{},[token]);
 const load=async()=>{if(!token)return;const u=new URL(`${base}/api/v1/admin/support/tickets`);if(q.trim())u.searchParams.set('q',q.trim());if(status)u.searchParams.set('status',status);const r=await fetch(u.toString(),{headers});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message??'Unable to load support inbox.');setItems(d.items??[])};
 const open=async(t:Ticket)=>{const r=await fetch(`${base}/api/v1/admin/support/tickets/${t.id}`,{headers});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message??'Unable to load ticket.');setSelected(d.ticket);setMessages(d.messages??[])};
 useEffect(()=>{queueMicrotask(()=>{void load().catch(e=>setError(String(e.message??e)))})},[token,status]);
 const setTicketStatus=async(next:string)=>{if(!selected)return;const r=await fetch(`${base}/api/v1/admin/support/tickets/${selected.id}`,{method:'PATCH',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({status:next})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message??'Status update failed.');setSelected(d.ticket);await load();await open(d.ticket)};
 const send=async()=>{if(!selected||note.trim().length<2)return;const r=await fetch(`${base}/api/v1/admin/support/tickets/${selected.id}/messages`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({message:note})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message??'Message failed.');setNote('');await open(selected);await load()};
 return <><Head><title>Support Inbox | Yaposan</title><meta name="robots" content="noindex,nofollow"/></Head><Phase241IShell title="Support Inbox" subtitle="Administrator ticket triage, conversation, attachments, and lifecycle management." accent="#0f766e"><ScrollView contentContainerStyle={s.page}><View style={s.filters}><TextInput style={s.input} value={q} onChangeText={setQ} placeholder="Search ticket, email, subject…"/><Pressable style={s.btn} onPress={()=>void load().catch(e=>setError(String(e.message??e)))}><Text style={s.btnText}>Search</Text></Pressable>{['',...statuses].map(x=><Pressable key={x||'all'} style={[s.chip,status===x&&s.chipOn]} onPress={()=>setStatus(x)}><Text style={[s.chipText,status===x&&s.chipTextOn]}>{x?label(x):'All'}</Text></Pressable>)}</View>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.grid}><View style={s.list}>{items.map(t=><Pressable key={t.id} style={[s.ticket,selected?.id===t.id&&s.ticketOn]} onPress={()=>void open(t).catch(e=>setError(String(e.message??e)))}><Text style={s.ticketTitle}>{t.subject}</Text><Text style={s.meta}>{t.name} · {t.email}</Text><Text style={s.meta}>{label(t.status)} · {t.priority} · {t.category}</Text></Pressable>)}</View><View style={s.detail}>{selected?<><Text style={s.title}>{selected.subject}</Text><Text style={s.meta}>{selected.id} · {selected.name} · {selected.email}</Text><Text style={s.meta}>{selected.source||'Unknown source'} · {selected.page||'Unknown page'} · {selected.action||'Unknown action'}</Text><View style={s.filters}>{statuses.map(x=><Pressable key={x} style={[s.chip,selected.status===x&&s.chipOn]} onPress={()=>void setTicketStatus(x).catch(e=>setError(String(e.message??e)))}><Text style={[s.chipText,selected.status===x&&s.chipTextOn]}>{label(x)}</Text></Pressable>)}{selected.attachmentName?<Pressable style={s.btn} onPress={()=>token&&void downloadProtectedSupportAttachment(`${base}/api/v1/admin/support/tickets/${selected.id}/attachment`,token,selected.attachmentName||'support-attachment').catch(e=>setError(String(e.message??e)))}><Text style={s.btnText}>Download attachment</Text></Pressable>:null}</View>{messages.map(m=><View key={m.id} style={s.message}><Text style={s.author}>{m.authorType==='staff'?'Staff':m.authorType==='system'?'System':'User'}</Text><Text style={s.copy}>{m.body}</Text><Text style={s.meta}>{new Date(m.createdAt).toLocaleString()}</Text></View>)}<TextInput style={s.area} multiline value={note} onChangeText={setNote} placeholder="Reply to the user / add support response…"/><Pressable style={s.btn} onPress={()=>void send().catch(e=>setError(String(e.message??e)))}><Text style={s.btnText}>Send support reply</Text></Pressable></>:<Text style={s.copy}>Select a support request.</Text>}</View></View></ScrollView></Phase241IShell></>}
const s=StyleSheet.create({page:{padding:18,gap:12},filters:{flexDirection:'row',flexWrap:'wrap',gap:8,alignItems:'center'},input:{minWidth:260,flex:1,borderWidth:1,borderColor:'#cbd5e1',borderRadius:9,padding:10,backgroundColor:'#fff'},btn:{backgroundColor:'#0f766e',paddingHorizontal:13,paddingVertical:10,borderRadius:9},btnText:{color:'#fff',fontWeight:'900'},chip:{borderWidth:1,borderColor:'#99f6e4',borderRadius:99,paddingHorizontal:10,paddingVertical:7},chipOn:{backgroundColor:'#0f766e'},chipText:{color:'#0f766e',fontWeight:'800'},chipTextOn:{color:'#fff'},grid:{flexDirection:'row',flexWrap:'wrap',gap:14},list:{width:380,maxWidth:'100%',gap:8},ticket:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0',borderRadius:11,padding:12},ticketOn:{borderColor:'#0f766e',backgroundColor:'#f0fdfa'},ticketTitle:{fontWeight:'900',color:'#0f172a'},detail:{flex:1,minWidth:320,backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0',borderRadius:13,padding:15,gap:10},title:{fontSize:20,fontWeight:'900'},meta:{fontSize:11,color:'#64748b',marginTop:3},message:{borderWidth:1,borderColor:'#e2e8f0',borderRadius:9,padding:11,backgroundColor:'#f8fafc'},author:{fontWeight:'900',color:'#0f766e',fontSize:12},copy:{color:'#475569',lineHeight:20},area:{minHeight:100,borderWidth:1,borderColor:'#cbd5e1',borderRadius:9,padding:11,textAlignVertical:'top'},error:{color:'#b91c1c',fontWeight:'800'}})
