import Head from 'expo-router/head';
import {router} from 'expo-router';
import {useEffect,useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import Phase241IShell from '../components/workspace/Phase241IShell';
import {useAuth} from '../context/AuthContext';
import {downloadProtectedSupportAttachment} from '../utils/supportTransport';

type Ticket={id:string;subject:string;category:string;priority:string;status:string;createdAt:string;updatedAt:string;message?:string;attachmentName?:string};
type Message={id:string;authorType:string;body:string;createdAt:string};
const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function SupportRequests(){
 const auth=useAuth(); const [items,setItems]=useState<Ticket[]>([]); const [selected,setSelected]=useState<Ticket>(); const [messages,setMessages]=useState<Message[]>([]); const [reply,setReply]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const base=process.env.EXPO_PUBLIC_API_URL ?? (typeof window !== "undefined" && !["localhost", "127.0.0.1"].includes(window.location.hostname) ? "https://api.yaposan.com" : "http://localhost:4100"); const token=auth.session?.accessToken;
 const headers=token?{authorization:`Bearer ${token}`}:{ };
 const load=async()=>{if(!token)return;setError('');const r=await fetch(`${base}/api/v1/support/tickets/my`,{headers});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message??'Unable to load support requests.');setItems(d.items??[])};
 const open=async(t:Ticket)=>{if(!token)return;setSelected(t);setError('');const r=await fetch(`${base}/api/v1/support/tickets/${t.id}`,{headers});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message??'Unable to load ticket.');setSelected(d.ticket);setMessages(d.messages??[])};
 useEffect(()=>{queueMicrotask(()=>{void load().catch(e=>setError(String(e.message??e)))})},[token]);
 const send=async()=>{if(!selected||!token||reply.trim().length<2)return;setBusy(true);try{const r=await fetch(`${base}/api/v1/support/tickets/${selected.id}/reply`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({message:reply})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message??'Reply failed.');setReply('');await open(selected);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 if(!token)return <Phase241IShell title="My Support Requests" subtitle="Track your Yaposan support tickets and replies." accent="#0891b2"><View style={s.empty}><Text style={s.title}>Sign in to track support requests</Text><Text style={s.copy}>Guest requests can still be submitted from Contact & Support, but ticket history is available after sign in.</Text><Pressable style={s.primary} onPress={()=>router.push('/sign-in')}><Text style={s.primaryText}>Sign in</Text></Pressable></View></Phase241IShell>;
 return <><Head><title>My Support Requests | Yaposan</title><meta name="robots" content="noindex,nofollow"/></Head><Phase241IShell title="My Support Requests" subtitle="Track status, review staff replies, and continue the conversation." accent="#0891b2"><ScrollView contentContainerStyle={s.page}>
  {error?<Text style={s.error}>{error}</Text>:null}<View style={s.grid}><View style={s.list}><View style={s.row}><Text style={s.title}>Requests</Text><Pressable style={s.secondary} onPress={()=>router.push('/contact')}><Text style={s.secondaryText}>New request</Text></Pressable></View>{items.length?items.map(t=><Pressable key={t.id} style={[s.ticket,selected?.id===t.id&&s.ticketOn]} onPress={()=>void open(t).catch(e=>setError(String(e.message??e)))}><Text style={s.ticketTitle}>{t.subject}</Text><Text style={s.meta}>{label(t.status)} · {t.category}</Text><Text style={s.meta}>{new Date(t.updatedAt).toLocaleString()}</Text></Pressable>):<View style={s.empty}><Text style={s.copy}>No support requests yet.</Text></View>}</View>
  <View style={s.detail}>{selected?<><View style={s.row}><View style={{flex:1}}><Text style={s.title}>{selected.subject}</Text><Text style={s.meta}>Ticket {selected.id} · {label(selected.status)} · {selected.priority}</Text></View>{selected.attachmentName?<Pressable style={s.secondary} onPress={()=>token&&void downloadProtectedSupportAttachment(`${base}/api/v1/support/tickets/${selected.id}/attachment`,token,selected.attachmentName||'support-attachment').catch(e=>setError(String(e.message??e)))}><Text style={s.secondaryText}>Attachment</Text></Pressable>:null}</View>{messages.map(m=><View key={m.id} style={[s.message,m.authorType==='staff'&&s.staff]}><Text style={s.author}>{m.authorType==='staff'?'Yaposan Support':m.authorType==='system'?'System':'You'}</Text><Text style={s.copy}>{m.body}</Text><Text style={s.meta}>{new Date(m.createdAt).toLocaleString()}</Text></View>)}<TextInput style={s.area} multiline value={reply} onChangeText={setReply} placeholder="Reply to this support request…"/><Pressable disabled={busy||reply.trim().length<2} style={[s.primary,(busy||reply.trim().length<2)&&s.disabled]} onPress={()=>void send()}><Text style={s.primaryText}>{busy?'Sending…':'Send reply'}</Text></Pressable></>:<View style={s.empty}><Text style={s.title}>Select a request</Text><Text style={s.copy}>Choose a ticket to review its conversation.</Text></View>}</View></View>
 </ScrollView></Phase241IShell></>;
}
const s=StyleSheet.create({page:{padding:18,gap:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:14},list:{width:360,maxWidth:'100%',gap:8},detail:{flex:1,minWidth:300,backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0',borderRadius:14,padding:16,gap:10},title:{fontSize:20,fontWeight:'900',color:'#0f172a'},copy:{color:'#475569',lineHeight:20},row:{flexDirection:'row',alignItems:'center',gap:10,flexWrap:'wrap'},ticket:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e8f0',borderRadius:12,padding:13},ticketOn:{borderColor:'#0891b2',backgroundColor:'#ecfeff'},ticketTitle:{fontWeight:'900',color:'#0f172a'},meta:{fontSize:11,color:'#64748b',marginTop:4},message:{borderWidth:1,borderColor:'#e2e8f0',borderRadius:10,padding:12,backgroundColor:'#f8fafc'},staff:{backgroundColor:'#ecfeff',borderColor:'#a5f3fc'},author:{fontWeight:'900',color:'#0e7490',fontSize:12},area:{minHeight:100,borderWidth:1,borderColor:'#cbd5e1',borderRadius:10,padding:12,textAlignVertical:'top'},primary:{backgroundColor:'#0891b2',paddingHorizontal:15,paddingVertical:11,borderRadius:9,alignSelf:'flex-start'},primaryText:{color:'#fff',fontWeight:'900'},secondary:{borderWidth:1,borderColor:'#a5f3fc',paddingHorizontal:12,paddingVertical:9,borderRadius:9},secondaryText:{color:'#0e7490',fontWeight:'900'},disabled:{opacity:.5},empty:{padding:24,gap:10},error:{color:'#b91c1c',fontWeight:'800'}});
