import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useAuth } from "../context/AuthContext";

type Member={id:string;userId:string;email:string;role:"owner"|"admin"|"editor"|"viewer";status:string;joinedAt:string};
type Notice={id:string;title:string;type:string;createdAt:string};
type Summary={scope:string;totals:{users:number;organizations:number;projects:number;trashedProjects:number;storageBytes:number;activeSubscriptions:number;queuedJobs:number}};

export default function TeamHub(){
 const auth=useAuth();const [members,setMembers]=useState<Member[]>([]);const [notices,setNotices]=useState<Notice[]>([]);const [summary,setSummary]=useState<Summary|null>(null);const [organization,setOrganization]=useState("Workspace");const [role,setRole]=useState("viewer");const [email,setEmail]=useState("");const [loading,setLoading]=useState(true);
 const load=async()=>{if(!auth.isAuthenticated)return;setLoading(true);try{const [m,n,a]=await Promise.all([auth.authorizedFetch("/api/v1/team/members"),auth.authorizedFetch("/api/v1/notifications"),auth.authorizedFetch("/api/v1/admin/summary")]);if(m.ok){const data=await m.json();setMembers(data.items??[]);setOrganization(data.organization?.name??"Workspace");setRole(data.currentRole??"viewer")}if(n.ok)setNotices((await n.json()).items??[]);if(a.ok)setSummary(await a.json())}finally{setLoading(false)}};
 useEffect(()=>{if(auth.ready&&!auth.isAuthenticated)router.replace("/sign-in");else queueMicrotask(()=>{void load()})},[auth.ready,auth.isAuthenticated]);
 const invite=async()=>{if(!email.trim())return;const response=await auth.authorizedFetch("/api/v1/team/invitations",{method:"POST",body:JSON.stringify({email,role:"editor"})});const data=await response.json();if(!response.ok)return Alert.alert("Invitation not completed",data?.error?.message??"The user must register first.");setEmail("");await load();Alert.alert("Member added","The registered user was added as an editor.")};
 const changeRole=async(member:Member,next:Member["role"])=>{const response=await auth.authorizedFetch(`/api/v1/team/members/${member.id}/role`,{method:"PUT",body:JSON.stringify({role:next})});if(!response.ok)return Alert.alert("Could not update role",(await response.json())?.error?.message??"Request failed");await load()};
 if(!auth.ready||loading)return <SafeAreaView style={s.center}><ActivityIndicator size="large" color="#7c3aed"/><Text style={s.muted}>Loading commercial platform…</Text></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <View style={s.top}><Pressable style={s.icon} onPress={()=>router.canGoBack()?router.back():router.replace("/")}><Ionicons name="arrow-back" size={20} color="#fff"/></Pressable><View><Text style={s.brand}>Yaposan Commercial Platform</Text><Text style={s.topSub}>Phase 81 • teams, projects, notifications and administration</Text></View></View>
  <View style={s.hero}><View><Text style={s.title}>{organization}</Text><Text style={s.subtitle}>Your role: {role}. Manage members, review operational activity, and monitor production readiness.</Text></View></View>
  {summary&&<View style={s.metrics}>{Object.entries(summary.totals).map(([key,value])=><View key={key} style={s.metric}><Text style={s.metricValue}>{key==="storageBytes"?`${(Number(value)/1024/1024).toFixed(1)} MB`:String(value)}</Text><Text style={s.metricLabel}>{key.replace(/([A-Z])/g," $1")}</Text></View>)}</View>}
  <View style={s.grid}><View style={s.card}><Text style={s.cardTitle}>Team members</Text><Text style={s.muted}>Owners and admins can add registered users and assign roles.</Text><View style={s.invite}><TextInput value={email} onChangeText={setEmail} placeholder="member@example.com" autoCapitalize="none" style={s.input}/><Pressable style={s.primary} onPress={()=>void invite()}><Text style={s.primaryText}>Add editor</Text></Pressable></View>{members.map(member=><View key={member.id} style={s.row}><View style={s.avatar}><Text style={s.avatarText}>{member.email[0]?.toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.bold}>{member.email}</Text><Text style={s.muted}>{member.status} • {member.role}</Text></View>{member.role!=="owner"&&<View style={s.actions}><Pressable onPress={()=>void changeRole(member,"viewer")}><Text style={s.link}>Viewer</Text></Pressable><Pressable onPress={()=>void changeRole(member,"editor")}><Text style={s.link}>Editor</Text></Pressable><Pressable onPress={()=>void changeRole(member,"admin")}><Text style={s.link}>Admin</Text></Pressable></View>}</View>)}</View>
  <View style={s.card}><Text style={s.cardTitle}>Production notifications</Text><Text style={s.muted}>Recent team, project, export, AI, and billing events.</Text>{notices.slice(0,15).map(item=><View key={item.id} style={s.notice}><Ionicons name="notifications-outline" size={18} color="#7c3aed"/><View style={{flex:1}}><Text style={s.bold}>{item.title}</Text><Text style={s.muted}>{new Date(item.createdAt).toLocaleString()}</Text></View></View>)}{!notices.length&&<Text style={s.muted}>No activity is available yet.</Text>}</View></View>
  <View style={s.card}><Text style={s.cardTitle}>Phase 81 project controls</Text><View style={s.featureGrid}>{["Archive and favorite projects","Project tags and search metadata","30-day trash and recovery foundation","Version restore API","Password-ready share links","Organization member roles","Notification feed","Admin operations summary"].map(text=><View key={text} style={s.feature}><Ionicons name="checkmark-circle" size={18} color="#15803d"/><Text style={s.featureText}>{text}</Text></View>)}</View></View>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#eef3f8"},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#eef3f8",gap:12},page:{padding:22,gap:16},top:{backgroundColor:"#102234",borderRadius:15,padding:14,flexDirection:"row",alignItems:"center",gap:12},icon:{width:38,height:38,borderRadius:10,backgroundColor:"#20394f",alignItems:"center",justifyContent:"center"},brand:{color:"#fff",fontSize:17,fontWeight:"900"},topSub:{color:"#9fb1c1",fontSize:11},hero:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dce5ee",borderRadius:18,padding:24},title:{fontSize:32,fontWeight:"900",color:"#102234"},subtitle:{color:"#64748b",marginTop:7,maxWidth:800},metrics:{flexDirection:"row",flexWrap:"wrap",gap:10},metric:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dce5ee",borderRadius:14,padding:16,minWidth:150,flexGrow:1},metricValue:{fontSize:24,fontWeight:"900",color:"#7c3aed"},metricLabel:{fontSize:12,color:"#64748b",textTransform:"capitalize"},grid:{flexDirection:"row",flexWrap:"wrap",gap:16,alignItems:"flex-start"},card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dce5ee",borderRadius:16,padding:20,gap:12,flex:1,minWidth:360},cardTitle:{fontSize:20,fontWeight:"900",color:"#172033"},muted:{color:"#64748b",fontSize:12,lineHeight:18},invite:{flexDirection:"row",gap:10},input:{flex:1,height:44,borderWidth:1,borderColor:"#cbd5e1",borderRadius:10,paddingHorizontal:12,backgroundColor:"#f8fafc"},primary:{backgroundColor:"#7c3aed",borderRadius:10,paddingHorizontal:16,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontWeight:"900"},row:{flexDirection:"row",alignItems:"center",gap:10,paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#eef2f7"},avatar:{width:38,height:38,borderRadius:19,backgroundColor:"#ede9fe",alignItems:"center",justifyContent:"center"},avatarText:{color:"#6d28d9",fontWeight:"900"},bold:{fontWeight:"900",color:"#172033"},actions:{flexDirection:"row",gap:10},link:{color:"#7c3aed",fontWeight:"800",fontSize:12},notice:{flexDirection:"row",gap:10,alignItems:"center",paddingVertical:9,borderBottomWidth:1,borderBottomColor:"#eef2f7"},featureGrid:{flexDirection:"row",flexWrap:"wrap",gap:10},feature:{flexDirection:"row",alignItems:"center",gap:8,backgroundColor:"#f8fafc",borderRadius:10,padding:12,minWidth:260,flexGrow:1},featureText:{color:"#334155",fontWeight:"700",fontSize:12}});
