import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import Head from "expo-router/head";
import { SafeAreaView, ScrollView, StyleSheet, Text, Pressable, View } from "react-native";
import { YAPOSAN_TOOL_CATALOG, type YaposanToolDefinition } from "../constants/yaposanTools";

type IconName = keyof typeof Ionicons.glyphMap;
const categoryLabels: Record<string,string> = { publish:"Publish", image:"Image", design:"Design", documents:"Documents", web:"Web", ai:"AI-powered" };
const categories = ["publish","image","design","documents","web","ai"] as const;
function accessLabel(tool:YaposanToolDefinition){if(tool.access==="free")return "Free in Yaposan";if(tool.access==="bring_your_own")return "Connect your AI or use Yaposan credits";return "Uses Yaposan credits";}

export default function Tools(){
 const {spaceId}=useLocalSearchParams<{spaceId?:string}>();
 return <><Head><title>Yaposan Tools</title></Head><SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.wrap}>
  <View style={s.top}><View><Text style={s.eyebrow}>YAPOSAN CREATOR</Text><Text style={s.title}>Tools ready when you are.</Text><Text style={s.copy}>Free Yaposan tools are available by default. You do not have to create an AI Page or install Publisher first. AI features that consume provider resources clearly ask you to connect your own provider or use optional Yaposan credits.</Text></View><View style={s.topActions}>{spaceId?<Pressable style={s.secondary} onPress={()=>router.push(`/ai-page?spaceId=${spaceId}` as any)}><Text style={s.secondaryText}>Back to My AI Page</Text></Pressable>:null}<Pressable style={s.primary} onPress={()=>router.push('/creator')}><Text style={s.primaryText}>Open Yaposan Creator</Text></Pressable></View></View>
  <View style={s.ruleCard}><Ionicons name="gift-outline" size={25} color="#7c3aed"/><View style={{flex:1}}><Text style={s.ruleTitle}>Free means included.</Text><Text style={s.ruleCopy}>If a Yaposan capability is free and does not require paid consumption, every user gets access automatically. Provider-powered AI remains visible but never pretends to be unlimited free compute.</Text></View></View>
  {categories.map(category=>{const items=YAPOSAN_TOOL_CATALOG.filter(tool=>tool.category===category);if(!items.length)return null;return <View key={category} style={s.section}><Text style={s.sectionTitle}>{categoryLabels[category]}</Text><View style={s.grid}>{items.map(tool=><Pressable key={tool.id} style={s.card} onPress={()=>router.push(tool.href as any)}><View style={s.icon}><Ionicons name={tool.icon as IconName} size={23} color="#7c3aed"/></View><View style={s.badges}><Text style={[s.badge,tool.access==="free"?s.free:s.connected]}>{tool.access==="free"?"FREE":"PROVIDER-POWERED"}</Text></View><Text style={s.cardTitle}>{tool.name}</Text><Text style={s.cardCopy}>{tool.description}</Text><Text style={s.access}>{accessLabel(tool)}</Text><View style={s.openRow}><Text style={s.open}>Open tool</Text><Ionicons name="arrow-forward" size={17} color="#7c3aed"/></View></Pressable>)}</View></View>})}
 </ScrollView></SafeAreaView></>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f6f7fb'},wrap:{padding:24,maxWidth:1240,width:'100%',alignSelf:'center'},top:{flexDirection:'row',justifyContent:'space-between',gap:20,flexWrap:'wrap',alignItems:'flex-end'},eyebrow:{color:'#7c3aed',fontWeight:'900',letterSpacing:1.2,fontSize:12},title:{fontSize:34,fontWeight:'900',color:'#111827',marginTop:5},copy:{color:'#64748b',maxWidth:760,lineHeight:22,marginTop:8},topActions:{flexDirection:'row',gap:8,flexWrap:'wrap'},primary:{backgroundColor:'#7c3aed',paddingVertical:12,paddingHorizontal:16,borderRadius:11},primaryText:{color:'#fff',fontWeight:'900'},secondary:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd6fe',paddingVertical:12,paddingHorizontal:16,borderRadius:11},secondaryText:{color:'#6d28d9',fontWeight:'900'},ruleCard:{marginTop:22,backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd6fe',borderRadius:16,padding:17,flexDirection:'row',gap:12},ruleTitle:{fontWeight:'900',color:'#111827',fontSize:16},ruleCopy:{color:'#64748b',marginTop:3,lineHeight:20},section:{marginTop:28},sectionTitle:{fontSize:22,fontWeight:'900',color:'#111827',marginBottom:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e7eb',borderRadius:17,padding:17,minWidth:220,flexBasis:260,flexGrow:1,maxWidth:390},icon:{width:43,height:43,borderRadius:12,backgroundColor:'#f1edff',alignItems:'center',justifyContent:'center'},badges:{marginTop:13,flexDirection:'row'},badge:{fontSize:10,fontWeight:'900',paddingVertical:4,paddingHorizontal:7,borderRadius:999,overflow:'hidden'},free:{color:'#047857',backgroundColor:'#d1fae5'},connected:{color:'#6d28d9',backgroundColor:'#ede9fe'},cardTitle:{fontWeight:'900',fontSize:18,color:'#111827',marginTop:10},cardCopy:{color:'#64748b',fontSize:13,lineHeight:19,marginTop:5},access:{fontSize:12,fontWeight:'800',color:'#475569',marginTop:12},openRow:{flexDirection:'row',gap:6,alignItems:'center',marginTop:15},open:{color:'#7c3aed',fontWeight:'900'}});
