import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { Alert, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { SvgXml } from "react-native-svg";
import type { PublisherProject, PublisherProjectVersion } from "../types/publisher";
import { createProjectBackup, createProjectVersion, deleteProjectBackup, deleteProjectVersion, getBackupSettings, listProjectBackups, listProjectVersions, loadPublisherProject, listSavedPublisherProjects, renameProjectVersion, restoreProjectBackup, restoreProjectVersion, saveBackupSettings, type BackupSettings, type ProjectBackup } from "../utils/publisherStorage";
import { exportPublisherProjectFile } from "../utils/projectFileManager";

const ask=(title:string,initial:string,run:(v:string)=>void)=>{if(Platform.OS==="web"&&typeof window!=="undefined"){const v=window.prompt(title,initial)?.trim();if(v)run(v)}else Alert.prompt?.(title,"",v=>{if(v?.trim())run(v.trim())},"plain-text",initial)};
const confirmAction=(title:string,message:string,run:()=>void)=>{if(Platform.OS==="web"&&typeof window!=="undefined"){if(window.confirm(message))run()}else Alert.alert(title,message,[{text:"Cancel",style:"cancel"},{text:"Continue",style:"destructive",onPress:run}])};
const fmt=(v:number)=>new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v));
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]||c));
function preview(project:PublisherProject){const page=project.pages[0];if(!page)return "";const body=page.elements.slice().sort((a,b)=>a.zIndex-b.zIndex).slice(0,60).map((e:any)=>e.type==="text"?`<text x="${e.x}" y="${e.y+(e.fontSize||18)}" font-size="${e.fontSize||18}" fill="${esc(e.textColor||"#111827")}">${esc(String(e.text||"").slice(0,70))}</text>`:`<rect x="${e.x}" y="${e.y}" width="${e.width}" height="${e.height}" fill="${esc(e.fillColor||"transparent")}" stroke="${esc(e.borderColor||"transparent")}"/>`).join("");return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${page.width} ${page.height}"><rect width="100%" height="100%" fill="${esc(page.backgroundColor)}"/>${body}</svg>`}

export default function VersionsScreen(){
 const {projectId}=useLocalSearchParams<{projectId:string}>();
 const [project,setProject]=useState<PublisherProject|null>(null),[versions,setVersions]=useState<PublisherProjectVersion[]>([]),[backups,setBackups]=useState<ProjectBackup[]>([]),[settings,setSettings]=useState<BackupSettings>({enabled:true,intervalMinutes:10,maxBackups:15}),[selected,setSelected]=useState<PublisherProjectVersion|null>(null),[readOnly,setReadOnly]=useState(false);
 const refresh=useCallback(async()=>{if(!projectId)return;const p=await loadPublisherProject(projectId);setProject(p);setReadOnly(Boolean((await listSavedPublisherProjects()).find(x=>x.id===projectId)?.readOnly));setVersions(await listProjectVersions(projectId));setBackups(await listProjectBackups(projectId));setSettings(await getBackupSettings())},[projectId]);
 useFocusEffect(useCallback(()=>{void refresh()},[refresh]));
 const comparison=useMemo(()=>{if(!project||!selected)return null;const a=selected.project,b=project;return {pages:`${a.pages.length} → ${b.pages.length}`,objects:`${a.pages.reduce((n,p)=>n+p.elements.length,0)} → ${b.pages.reduce((n,p)=>n+p.elements.length,0)}`,name:a.name===b.name?"Unchanged":`${a.name} → ${b.name}`}},[project,selected]);
 if(!project)return <SafeAreaView style={s.screen}><Text style={s.loading}>Loading history…</Text></SafeAreaView>;
 const updateSettings=async(patch:Partial<BackupSettings>)=>{const next={...settings,...patch};setSettings(next);await saveBackupSettings(next)};
 return <SafeAreaView style={s.screen}><View style={s.header}><Pressable onPress={()=>router.canGoBack() ? router.back() : router.replace("/" as never)} style={s.icon}><Ionicons name="arrow-back" size={20} color="#E2E8F0"/></Pressable><View><Text style={s.eyebrow}>RECOVERY & VERSION HISTORY</Text><Text style={s.title}>{project.name}</Text></View>{readOnly&&<View style={{marginLeft:"auto",backgroundColor:"#FEF3C7",padding:8,borderRadius:8}}><Text style={{color:"#92400E",fontWeight:"800"}}>Read only</Text></View>}<View style={s.headerActions}><Pressable disabled={readOnly} style={[s.secondary,readOnly&&{opacity:.45}]} onPress={async()=>{await createProjectBackup(project);await refresh()}}><Text style={s.secondaryText}>Backup Now</Text></Pressable><Pressable disabled={readOnly} style={[s.primary,readOnly&&{opacity:.45}]} onPress={()=>ask("Name this version","Milestone",async label=>{await createProjectVersion(project,label);await refresh()})}><Text style={s.primaryText}>Create Version</Text></Pressable></View></View>
 <ScrollView contentContainerStyle={s.content}><View style={s.settings}><Text style={s.sectionTitle}>Automatic Backups</Text><Pressable style={[s.settingPill,settings.enabled&&s.active]} onPress={()=>void updateSettings({enabled:!settings.enabled})}><Text>{settings.enabled?"Enabled":"Disabled"}</Text></Pressable>{([5,10,30] as const).map(v=><Pressable key={v} style={[s.settingPill,settings.intervalMinutes===v&&s.active]} onPress={()=>void updateSettings({intervalMinutes:v})}><Text>{v} min</Text></Pressable>)}<Text style={s.muted}>Keep up to {settings.maxBackups} backups per project.</Text></View>
 <View style={s.columns}><View style={s.list}><Text style={s.sectionTitle}>Version History ({versions.length})</Text>{versions.map(v=><View key={v.id} style={[s.row,selected?.id===v.id&&s.rowSelected]}><Pressable style={s.rowMain} onPress={()=>setSelected(v)}><Text style={s.rowTitle}>{v.label}</Text><Text style={s.muted}>{fmt(v.createdAt)} · {v.project.pages.length} pages</Text></Pressable><Pressable style={s.small} onPress={()=>ask("Rename version",v.label,async label=>{await renameProjectVersion(project.id,v.id,label);await refresh()})}><Ionicons name="pencil" size={16}/></Pressable><Pressable style={s.small} onPress={()=>void exportPublisherProjectFile(v.project)}><Ionicons name="download-outline" size={16}/></Pressable><Pressable style={s.restore} onPress={()=>confirmAction("Restore version",`Restore “${v.label}”? The current project will be saved as a version first.`,async()=>{await restoreProjectVersion(project.id,v.id);await refresh();Alert.alert("Restored","The selected version is now current.")})}><Text style={s.restoreText}>Restore</Text></Pressable><Pressable style={s.small} onPress={()=>confirmAction("Delete version",`Delete “${v.label}”?`,async()=>{await deleteProjectVersion(project.id,v.id);if(selected?.id===v.id)setSelected(null);await refresh()})}><Ionicons name="trash-outline" size={16} color="#B91C1C"/></Pressable></View>)}{!versions.length&&<Text style={s.empty}>No versions yet. Create a named milestone or continue editing to generate save history.</Text>}
 <Text style={[s.sectionTitle,{marginTop:24}]}>Backups ({backups.length})</Text>{backups.map(b=><View key={b.id} style={s.row}><View style={s.rowMain}><Text style={s.rowTitle}>Automatic Backup</Text><Text style={s.muted}>{fmt(b.createdAt)}</Text></View><Pressable style={s.restore} onPress={()=>confirmAction("Restore backup","Restore this backup?",async()=>{await restoreProjectBackup(project.id,b.id);await refresh()})}><Text style={s.restoreText}>Restore</Text></Pressable><Pressable style={s.small} onPress={()=>confirmAction("Delete backup","Delete this backup?",async()=>{await deleteProjectBackup(project.id,b.id);await refresh()})}><Ionicons name="trash-outline" size={16} color="#B91C1C"/></Pressable></View>)}</View>
 <View style={s.preview}><Text style={s.sectionTitle}>Preview & Compare</Text>{selected?<><View style={s.paper}><SvgXml xml={preview(selected.project)} width="100%" height="100%"/></View><Text style={s.compare}>Pages: {comparison?.pages}</Text><Text style={s.compare}>Objects: {comparison?.objects}</Text><Text style={s.compare}>Name: {comparison?.name}</Text><Text style={s.muted}>Previewing {selected.label} from {fmt(selected.createdAt)}</Text></>:<Text style={s.empty}>Select a version to preview and compare it with the current project.</Text>}</View></View></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#EEF3F8"},loading:{padding:30},header:{minHeight:86,backgroundColor:"#0F1B27",paddingHorizontal:26,flexDirection:"row",alignItems:"center",gap:16},icon:{width:38,height:38,borderRadius:8,backgroundColor:"#1D3042",alignItems:"center",justifyContent:"center"},eyebrow:{color:"#5EEAD4",fontSize:10,fontWeight:"900",letterSpacing:1.2},title:{color:"white",fontSize:24,fontWeight:"900"},headerActions:{marginLeft:"auto",flexDirection:"row",gap:10},primary:{paddingHorizontal:15,height:40,borderRadius:8,backgroundColor:"#0D9488",justifyContent:"center"},primaryText:{color:"white",fontWeight:"800"},secondary:{paddingHorizontal:15,height:40,borderRadius:8,backgroundColor:"white",justifyContent:"center"},secondaryText:{color:"#0F766E",fontWeight:"800"},content:{padding:26},settings:{backgroundColor:"white",borderRadius:12,padding:16,flexDirection:"row",alignItems:"center",gap:8,flexWrap:"wrap",marginBottom:18},sectionTitle:{fontSize:16,fontWeight:"900",color:"#17212B",marginRight:10},settingPill:{paddingHorizontal:12,paddingVertical:8,borderRadius:8,backgroundColor:"#E2E8F0"},active:{backgroundColor:"#99F6E4",borderWidth:1,borderColor:"#0D9488"},columns:{flexDirection:"row",gap:18,alignItems:"flex-start"},list:{flex:1.35,backgroundColor:"white",borderRadius:12,padding:16},preview:{flex:0.65,backgroundColor:"white",borderRadius:12,padding:16,minHeight:420},row:{flexDirection:"row",alignItems:"center",gap:7,paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#E2E8F0"},rowSelected:{backgroundColor:"#ECFDF5"},rowMain:{flex:1},rowTitle:{fontWeight:"800",color:"#17212B"},muted:{fontSize:11,color:"#64748B",marginTop:3},small:{width:34,height:34,borderRadius:7,backgroundColor:"#F1F5F9",alignItems:"center",justifyContent:"center"},restore:{height:34,paddingHorizontal:11,borderRadius:7,backgroundColor:"#0F766E",justifyContent:"center"},restoreText:{color:"white",fontWeight:"800",fontSize:11},paper:{height:300,backgroundColor:"#F8FAFC",borderWidth:1,borderColor:"#CBD5E1",marginVertical:14,overflow:"hidden"},compare:{fontSize:12,fontWeight:"700",marginBottom:6,color:"#334155"},empty:{paddingVertical:22,color:"#64748B"}});
