import AsyncStorage from '@react-native-async-storage/async-storage';
import { useLocalSearchParams,router } from 'expo-router';
import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { API_URL, apiReachabilityMessage, readApiError } from '../config/api';
const API=API_URL;
const TOKEN_KEY='yaposan.admin.accessToken.v104';
type Preview=any;
export default function AdminSpacePreview(){const {spaceId,preview}=useLocalSearchParams<{spaceId?:string;preview?:string}>();const[data,setData]=useState<Preview>();const[error,setError]=useState('');const[viewport,setViewport]=useState<'desktop'|'tablet'|'mobile'>('desktop');
 useEffect(()=>{queueMicrotask(()=>{void (async()=>{try{const token=await AsyncStorage.getItem(TOKEN_KEY);if(!token)throw new Error('Admin sign-in required');const endpoint=preview==='template'?`${API}/api/v1/yaposan-admin/preview-template`:`${API}/api/v1/yaposan-admin/spaces/${encodeURIComponent(String(spaceId??''))}/preview`;let r:Response;try{r=await fetch(endpoint,{headers:{'x-yaposan-admin-authorization':token}})}catch(e){throw new Error(apiReachabilityMessage('/api/v1/yaposan-admin/spaces/preview',e))}if(!r.ok)throw new Error(await readApiError(r,'Preview unavailable'));setData(await r.json())}catch(e){setError(e instanceof Error?e.message:'Preview unavailable')}})()})},[spaceId,preview]);
 if(error)return <SafeAreaView style={s.center}><Text style={s.error}>{error}</Text><Pressable onPress={()=>router.replace('/yaposan-admin')}><Text style={s.link}>Back to Yaposan Admin</Text></Pressable></SafeAreaView>;
 if(!data)return <SafeAreaView style={s.center}><ActivityIndicator/><Text>Loading read-only support preview…</Text></SafeAreaView>;
 const d=data;return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.wrap}><View style={s.adminBar}><View><Text style={s.adminTitle}>Yaposan Admin • Read-only Support Preview</Text><Text style={s.adminText}>You are not signed in as this customer. Actions, purchases, messages and edits are disabled. This preview is audit-logged.</Text></View><Pressable style={s.back} onPress={()=>router.replace('/yaposan-admin')}><Text style={s.backText}>Exit Preview</Text></Pressable></View>
 <View style={s.viewportBar}><Text style={s.viewportLabel}>Preview size</Text>{(['desktop','tablet','mobile'] as const).map(v=><Pressable key={v} onPress={()=>setViewport(v)} style={[s.viewportButton,viewport===v&&s.viewportOn]}><Text style={viewport===v?s.viewportTextOn:s.viewportText}>{v}</Text></Pressable>)}</View><View style={[s.previewFrame,viewport==='desktop'?s.desktop:viewport==='tablet'?s.tablet:s.mobile]}><View style={s.hero}><Text style={s.eyebrow}>{d.space.visibility.toUpperCase()} AI PAGE • {d.space.status}</Text><Text style={s.title}>{d.space.name}</Text><Text style={s.copy}>Owner: {d.space.ownerEmail??'Unknown'} • @{d.space.slug}</Text><Text style={s.copy}>Public page: {d.diagnostics.publicPageEnabled?'Enabled':'Disabled'} • Discoverable: {d.diagnostics.discoverable?'Yes':'No'} • Open reports: {d.diagnostics.openReports}</Text></View>
 <Section title="Studios" items={d.studios} empty="No published Studios."/><Section title="AI" items={d.ai} empty="No enabled AI agents."/><Section title="Creations" items={d.creations} empty="No creations."/><Section title="Store" items={d.store} empty="No active products."/><Text style={s.h2}>Updates</Text>{d.posts?.length?d.posts.map((x:any)=><View key={x.id} style={s.card}><Text style={s.body}>{x.body}</Text><Text style={s.meta}>{x.visibility} • {new Date(x.createdAt).toLocaleString()}</Text></View>):<Text style={s.muted}>No posts.</Text>}
 </View></ScrollView></SafeAreaView>}
function Section({title,items,empty}:{title:string;items:any[];empty:string}){return <><Text style={s.h2}>{title}</Text><View style={s.grid}>{items?.length?items.map((x:any)=><View key={x.id} style={s.card}><Text style={s.cardTitle}>{x.name}</Text><Text style={s.muted}>{x.description||x.provider||x.kind||''}</Text><Text style={s.meta}>{x.visibility||x.status||''}</Text></View>):<Text style={s.muted}>{empty}</Text>}</View></>}
const s=StyleSheet.create({viewportBar:{flexDirection:'row',gap:8,alignItems:'center',marginBottom:12},viewportLabel:{fontWeight:'900',marginRight:4},viewportButton:{paddingHorizontal:12,paddingVertical:8,borderRadius:999,backgroundColor:'#e5e7eb'},viewportOn:{backgroundColor:'#111827'},viewportText:{color:'#374151',fontWeight:'800',textTransform:'capitalize'},viewportTextOn:{color:'#fff',fontWeight:'800',textTransform:'capitalize'},previewFrame:{width:'100%',alignSelf:'center',borderWidth:1,borderColor:'#e5e7eb',borderRadius:24,overflow:'hidden',backgroundColor:'#fff'},desktop:{maxWidth:1120},tablet:{maxWidth:768},mobile:{maxWidth:390},root:{flex:1,backgroundColor:'#f8fafc'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12},wrap:{maxWidth:1180,width:'100%',alignSelf:'center',padding:24},adminBar:{backgroundColor:'#111827',borderRadius:16,padding:16,marginBottom:16,flexDirection:'row',gap:18,justifyContent:'space-between',alignItems:'center'},adminTitle:{color:'#fff',fontWeight:'900',fontSize:16},adminText:{color:'#cbd5e1',maxWidth:760,fontSize:12,marginTop:4},back:{backgroundColor:'#fff',paddingHorizontal:14,paddingVertical:10,borderRadius:9},backText:{fontWeight:'900'},hero:{backgroundColor:'#6d28d9',borderRadius:28,padding:32,minHeight:220,justifyContent:'flex-end'},eyebrow:{color:'#ddd6fe',fontWeight:'900'},title:{fontSize:40,fontWeight:'900',color:'#fff',marginTop:8},copy:{color:'#ede9fe',marginTop:5},h2:{fontSize:24,fontWeight:'900',marginTop:28,marginBottom:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e7eb',borderRadius:14,padding:16,minWidth:220,flexBasis:260,flexGrow:1,marginBottom:10},cardTitle:{fontWeight:'900',fontSize:16},body:{lineHeight:21},muted:{color:'#64748b',marginTop:5},meta:{color:'#94a3b8',fontSize:11,marginTop:8},error:{color:'#b91c1c',fontWeight:'800'},link:{color:'#6d28d9',fontWeight:'900'}});
