export type AIProviderId = "local" | "openai" | "gemini" | "claude" | "ollama" | "lmstudio" | "custom";
export type AICapability = "text" | "image" | "design" | "document" | "brand" | "product";
export type AIProviderStatus = "ready" | "configuration-required" | "offline";

export type AIProviderDefinition = {
  id: AIProviderId;
  name: string;
  models: string[];
  capabilities: AICapability[];
  requiresApiKey: boolean;
};

export type AISettings = {
  provider: AIProviderId;
  model: string;
  temperature: number;
  topP: number;
  maxTokens: number;
  streaming: boolean;
  localFallback: boolean;
};

export type AIGenerationRequest = {
  capability: AICapability;
  prompt: string;
  tone?: string;
  audience?: string;
};

export type AIGenerationResult = {
  provider: AIProviderId;
  model: string;
  text: string;
  inputTokens: number;
  outputTokens: number;
  durationMs: number;
  createdAt: string;
};

export const AI_PROVIDERS: AIProviderDefinition[] = [
  { id: "local", name: "Yaposan Local", models: ["yaposan-local-creative"], capabilities: ["text","image","design","document","brand","product"], requiresApiKey: false },
  { id: "openai", name: "OpenAI", models: ["gpt-4.1", "gpt-4.1-mini", "gpt-image-1"], capabilities: ["text","image","design","document","brand","product"], requiresApiKey: true },
  { id: "gemini", name: "Google Gemini", models: ["gemini-2.5-pro", "gemini-2.5-flash"], capabilities: ["text","image","design","document","brand"], requiresApiKey: true },
  { id: "claude", name: "Anthropic Claude", models: ["claude-sonnet-4", "claude-opus-4"], capabilities: ["text","design","document","brand"], requiresApiKey: true },
  { id: "ollama", name: "Ollama", models: ["llama3.2", "qwen2.5"], capabilities: ["text","design","document"], requiresApiKey: false },
  { id: "lmstudio", name: "LM Studio", models: ["local-model"], capabilities: ["text","design","document"], requiresApiKey: false },
  { id: "custom", name: "Custom Provider", models: ["custom-model"], capabilities: ["text","image","design","document","brand","product"], requiresApiKey: true },
];

export const DEFAULT_AI_SETTINGS: AISettings = {
  provider: "local",
  model: "yaposan-local-creative",
  temperature: 0.7,
  topP: 0.9,
  maxTokens: 2048,
  streaming: true,
  localFallback: true,
};

export function getProvider(id: AIProviderId) {
  return AI_PROVIDERS.find((provider) => provider.id === id) ?? AI_PROVIDERS[0];
}

export function providerStatus(provider: AIProviderDefinition, apiKey?: string): AIProviderStatus {
  if (!provider.requiresApiKey) return "ready";
  return apiKey?.trim() ? "ready" : "configuration-required";
}

export function estimateTokens(value: string) {
  return Math.max(1, Math.ceil(value.trim().length / 4));
}

export async function generateWithProvider(request: AIGenerationRequest, settings: AISettings): Promise<AIGenerationResult> {
  const started = Date.now();
  const provider = getProvider(settings.provider);
  const objective = request.prompt.trim();
  if (!objective) throw new Error("A prompt is required.");
  const text = [
    `${provider.name} ${request.capability} result`,
    "",
    `Objective: ${objective}`,
    request.audience ? `Audience: ${request.audience}` : "",
    request.tone ? `Tone: ${request.tone}` : "",
    "",
    "Production plan:",
    "1. Establish a clear visual and content hierarchy.",
    "2. Create three editable variations with accessible contrast.",
    "3. Apply the active Brand Kit and publication specifications.",
    "4. Review spelling, accessibility, preflight, and export readiness.",
    "",
    settings.provider === "local"
      ? "This result was generated by the secure local fallback. Configure a provider key in AI Provider Settings to enable live cloud generation."
      : `The ${provider.name} connector is configured through the provider adapter and is ready for a secure server-side API implementation.`,
  ].filter(Boolean).join("\n");
  return {
    provider: settings.provider,
    model: settings.model,
    text,
    inputTokens: estimateTokens(objective),
    outputTokens: estimateTokens(text),
    durationMs: Math.max(1, Date.now() - started),
    createdAt: new Date().toISOString(),
  };
}
