import type { PublisherElement, PublisherPage, PublisherProject } from "../types/publisher";

export type ChangeKind = "page-added" | "page-removed" | "page-updated" | "element-added" | "element-removed" | "element-updated";
export type VersionChange = { id:string; kind:ChangeKind; pageId:string; elementId?:string; summary:string; before?:unknown; after?:unknown };
export type ProjectVersion = { id:string; label:string; author:string; note?:string; createdAt:number; projectHash:string; project:PublisherProject; changeCount:number; branchId?:string };
export type MergeConflict = { id:string; pageId:string; elementId?:string; field:string; baseValue:unknown; localValue:unknown; incomingValue:unknown };
export type ChangeSet = { schema:"yaposan.phase23.changeset"; version:1; id:string; projectId:string; projectName:string; baseHash:string; createdAt:number; author:string; note?:string; changes:VersionChange[]; sourceProject:PublisherProject };
export type ReleaseChannel = "development" | "review" | "staging" | "production";
export type ProjectBranch = { id:string; name:string; description?:string; channel:ReleaseChannel; createdAt:number; updatedAt:number; createdBy:string; baseVersionId:string; baseHash:string; headHash:string; project:PublisherProject; archivedAt?:number };
export type BranchMergeRecord = { id:string; sourceBranchId:string; sourceBranchName:string; targetBranchId:string; targetBranchName:string; createdAt:number; author:string; conflictCount:number; strategy:"local"|"incoming"; resultHash:string };
export type ApprovalRole = "designer" | "editor" | "legal" | "brand" | "owner";
export type ApprovalDecision = "approved" | "changes-requested";
export type BranchApproval = { id:string; branchId:string; branchHash:string; reviewer:string; role:ApprovalRole; decision:ApprovalDecision; note?:string; createdAt:number };
export type ReleasePolicy = { channel:ReleaseChannel; minimumApprovals:number; requiredRoles:ApprovalRole[]; requireCertified:boolean; requireImmutableVersion:boolean; blockChangesRequested:boolean };
export type PromotionRecord = { id:string; branchId:string; branchName:string; fromChannel:ReleaseChannel; toChannel:ReleaseChannel; promotedBy:string; note?:string; createdAt:number; branchHash:string; readinessScore:number; approvalIds:string[] };
export type ReleaseReadiness = { branchId:string; branchName:string; channel:ReleaseChannel; targetChannel:ReleaseChannel; score:number; ready:boolean; blockers:string[]; warnings:string[]; validApprovals:BranchApproval[]; policy:ReleasePolicy };
export type Phase23Certification = { generatedAt:number; score:number; passed:boolean; issues:string[]; versionCount:number; currentHash:string; branchCount:number; activeBranchId:string; approvalCount?:number; promotionCount?:number };
export type Phase23State = { version:"23.2"; versions:ProjectVersion[]; importedChangeSets:ChangeSet[]; branches:ProjectBranch[]; activeBranchId:string; mergeHistory:BranchMergeRecord[]; approvals:BranchApproval[]; releasePolicies:ReleasePolicy[]; promotionHistory:PromotionRecord[]; lastCertification?:Phase23Certification };

const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const stable=(value:unknown):string=>{ if(Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if(value&&typeof value==="object") return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`; return JSON.stringify(value); };
export function hashProject(project:PublisherProject){ let h=2166136261; const source=stable({ ...project, updatedAt:0, collaborationWorkspace:undefined, phase23Version:undefined }); for(let i=0;i<source.length;i++){ h^=source.charCodeAt(i); h=Math.imul(h,16777619); } return (h>>>0).toString(16).padStart(8,"0"); }
const cleanProject=(project:PublisherProject):PublisherProject=>JSON.parse(JSON.stringify({ ...project, collaborationWorkspace:undefined })) as PublisherProject;
const byId=<T extends {id:string}>(items:T[])=>new Map(items.map(x=>[x.id,x]));
const releaseOrder:ReleaseChannel[]=["development","review","staging","production"];
const defaultReleasePolicies:ReleasePolicy[]=[
 {channel:"development",minimumApprovals:0,requiredRoles:[],requireCertified:false,requireImmutableVersion:false,blockChangesRequested:false},
 {channel:"review",minimumApprovals:1,requiredRoles:["editor"],requireCertified:false,requireImmutableVersion:true,blockChangesRequested:true},
 {channel:"staging",minimumApprovals:2,requiredRoles:["editor","brand"],requireCertified:true,requireImmutableVersion:true,blockChangesRequested:true},
 {channel:"production",minimumApprovals:3,requiredRoles:["editor","brand","owner"],requireCertified:true,requireImmutableVersion:true,blockChangesRequested:true}
];
const defaultMainBranch=(project:PublisherProject,version?:ProjectVersion):ProjectBranch=>({id:"branch-main",name:"Main",description:"Primary production branch",channel:"production",createdAt:project.createdAt||Date.now(),updatedAt:Date.now(),createdBy:"Project Owner",baseVersionId:version?.id??"",baseHash:version?.projectHash??hashProject(project),headHash:hashProject(project),project:cleanProject(project)});

export function getPhase23State(project:PublisherProject):Phase23State {
  const stored=(project as PublisherProject & { collaborationWorkspace?:Partial<Phase23State> }).collaborationWorkspace;
  const versions=stored?.versions??[];
  const branches=stored?.branches?.length?stored.branches:[defaultMainBranch(project,versions[versions.length-1])];
  const activeBranchId=branches.some(branch=>branch.id===stored?.activeBranchId)?stored!.activeBranchId!:branches[0].id;
  return {version:"23.2",versions,importedChangeSets:stored?.importedChangeSets??[],branches,activeBranchId,mergeHistory:stored?.mergeHistory??[],approvals:stored?.approvals??[],releasePolicies:stored?.releasePolicies?.length?stored.releasePolicies:defaultReleasePolicies,promotionHistory:stored?.promotionHistory??[],lastCertification:stored?.lastCertification};
}
export function withPhase23State(project:PublisherProject,state:Phase23State):PublisherProject { return { ...project, collaborationWorkspace:{...state,version:"23.2"}, phase23Version:"23.2", updatedAt:Date.now() } as PublisherProject; }

function diffElements(pageId:string,before:PublisherElement[],after:PublisherElement[]):VersionChange[]{ const a=byId(before),b=byId(after),out:VersionChange[]=[]; for(const [id,item] of b){ const old=a.get(id); if(!old) out.push({id:uid("change"),kind:"element-added",pageId,elementId:id,summary:`Added ${item.type} object`,after:item}); else if(stable(old)!==stable(item)) out.push({id:uid("change"),kind:"element-updated",pageId,elementId:id,summary:`Updated ${item.type} object`,before:old,after:item}); } for(const [id,item] of a) if(!b.has(id)) out.push({id:uid("change"),kind:"element-removed",pageId,elementId:id,summary:`Removed ${item.type} object`,before:item}); return out; }
export function diffProjects(before:PublisherProject,after:PublisherProject):VersionChange[]{ const a=byId(before.pages),b=byId(after.pages),out:VersionChange[]=[]; for(const [id,page] of b){ const old=a.get(id); if(!old) out.push({id:uid("change"),kind:"page-added",pageId:id,summary:`Added page ${page.name}`,after:page}); else { const oldMeta={...old,elements:undefined},newMeta={...page,elements:undefined}; if(stable(oldMeta)!==stable(newMeta)) out.push({id:uid("change"),kind:"page-updated",pageId:id,summary:`Updated page ${page.name}`,before:oldMeta,after:newMeta}); out.push(...diffElements(id,old.elements,page.elements)); } } for(const [id,page] of a) if(!b.has(id)) out.push({id:uid("change"),kind:"page-removed",pageId:id,summary:`Removed page ${page.name}`,before:page}); return out; }

export function createProjectVersion(project:PublisherProject,label:string,author="Project Owner",note?:string):Phase23State { const state=getPhase23State(project); const previous=state.versions[0]?.project; const snapshot=cleanProject(project); const version:ProjectVersion={id:uid("version"),label:label.trim()||`Version ${state.versions.length+1}`,author:author.trim()||"Project Owner",note:note?.trim(),createdAt:Date.now(),projectHash:hashProject(snapshot),project:snapshot,changeCount:previous?diffProjects(previous,snapshot).length:0,branchId:state.activeBranchId}; return {...state,versions:[version,...state.versions].slice(0,100),branches:state.branches.map(branch=>branch.id===state.activeBranchId?{...branch,project:snapshot,headHash:version.projectHash,updatedAt:Date.now()}:branch)}; }
export function restoreProjectVersion(current:PublisherProject,version:ProjectVersion):PublisherProject { const state=getPhase23State(current); return withPhase23State({ ...cleanProject(version.project), id:current.id, name:current.name, updatedAt:Date.now() },state); }

export function createBranch(project:PublisherProject,name:string,createdBy="Project Owner",description?:string,baseVersionId?:string,channel:ReleaseChannel="development"):PublisherProject {
  const state=getPhase23State(project); const normalized=name.trim(); if(!normalized) throw new Error("Branch name is required."); if(state.branches.some(branch=>!branch.archivedAt&&branch.name.toLowerCase()===normalized.toLowerCase())) throw new Error("A branch with this name already exists.");
  const base=baseVersionId?state.versions.find(version=>version.id===baseVersionId):undefined; const source=base?.project??project; const branch:ProjectBranch={id:uid("branch"),name:normalized,description:description?.trim(),channel,createdAt:Date.now(),updatedAt:Date.now(),createdBy:createdBy.trim()||"Project Owner",baseVersionId:base?.id??state.versions[0]?.id??"",baseHash:base?.projectHash??hashProject(source),headHash:hashProject(source),project:cleanProject(source)};
  return withPhase23State(project,{...state,branches:[...state.branches,branch]});
}
export function saveActiveBranch(project:PublisherProject):PublisherProject { const state=getPhase23State(project); const snapshot=cleanProject(project); return withPhase23State(project,{...state,branches:state.branches.map(branch=>branch.id===state.activeBranchId?{...branch,project:snapshot,headHash:hashProject(snapshot),updatedAt:Date.now()}:branch)}); }
export function switchBranch(project:PublisherProject,branchId:string):PublisherProject { let state=getPhase23State(project); const currentSnapshot=cleanProject(project); state={...state,branches:state.branches.map(branch=>branch.id===state.activeBranchId?{...branch,project:currentSnapshot,headHash:hashProject(currentSnapshot),updatedAt:Date.now()}:branch)}; const target=state.branches.find(branch=>branch.id===branchId&&!branch.archivedAt); if(!target) throw new Error("Branch was not found or is archived."); return withPhase23State({...cleanProject(target.project),id:project.id,name:project.name,updatedAt:Date.now()},{...state,activeBranchId:target.id}); }
export function updateBranch(project:PublisherProject,branchId:string,updates:Partial<Pick<ProjectBranch,"name"|"description"|"channel">>):PublisherProject { const state=getPhase23State(project); if(updates.name&&state.branches.some(branch=>branch.id!==branchId&&!branch.archivedAt&&branch.name.toLowerCase()===updates.name!.trim().toLowerCase())) throw new Error("A branch with this name already exists."); return withPhase23State(project,{...state,branches:state.branches.map(branch=>branch.id===branchId?{...branch,...updates,name:updates.name?.trim()||branch.name,updatedAt:Date.now()}:branch)}); }
export function archiveBranch(project:PublisherProject,branchId:string):PublisherProject { const state=getPhase23State(project); if(branchId===state.activeBranchId) throw new Error("Switch to another branch before archiving the active branch."); if(branchId==="branch-main") throw new Error("The Main branch cannot be archived."); return withPhase23State(project,{...state,branches:state.branches.map(branch=>branch.id===branchId?{...branch,archivedAt:Date.now(),updatedAt:Date.now()}:branch)}); }
export function compareBranches(project:PublisherProject,leftBranchId:string,rightBranchId:string):VersionChange[]{ const state=getPhase23State(project); const left=state.branches.find(branch=>branch.id===leftBranchId),right=state.branches.find(branch=>branch.id===rightBranchId); if(!left||!right) throw new Error("Both branches are required for comparison."); return diffProjects(left.project,right.project); }

function fields(value:unknown):Record<string,unknown>{ return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{}; }
export function detectMergeConflicts(base:PublisherProject,local:PublisherProject,incoming:PublisherProject):MergeConflict[]{ const conflicts:MergeConflict[]=[]; const basePages=byId(base.pages),localPages=byId(local.pages),incomingPages=byId(incoming.pages); for(const [pageId,inPage] of incomingPages){ const bPage=basePages.get(pageId),lPage=localPages.get(pageId); if(!bPage||!lPage) continue; const bEls=byId(bPage.elements),lEls=byId(lPage.elements),iEls=byId(inPage.elements); for(const [elementId,iEl] of iEls){ const bEl=bEls.get(elementId),lEl=lEls.get(elementId); if(!bEl||!lEl) continue; const keys=new Set([...Object.keys(fields(bEl)),...Object.keys(fields(lEl)),...Object.keys(fields(iEl))]); for(const field of keys){ const bv=fields(bEl)[field],lv=fields(lEl)[field],iv=fields(iEl)[field]; if(stable(lv)!==stable(bv)&&stable(iv)!==stable(bv)&&stable(lv)!==stable(iv)) conflicts.push({id:uid("conflict"),pageId,elementId,field,baseValue:bv,localValue:lv,incomingValue:iv}); } } } return conflicts; }
function mergeProjects(base:PublisherProject,local:PublisherProject,incoming:PublisherProject,strategy:"local"|"incoming"):{project:PublisherProject;conflicts:MergeConflict[]}{ const conflicts=detectMergeConflicts(base,local,incoming); const conflictKeys=new Set(conflicts.map(c=>`${c.pageId}:${c.elementId??""}:${c.field}`)); const localPages=byId(local.pages),incomingPages=byId(incoming.pages),mergedPages:PublisherPage[]=[]; for(const inPage of incoming.pages){ const localPage=localPages.get(inPage.id); if(!localPage){mergedPages.push(inPage);continue;} const localElements=byId(localPage.elements); const elements=inPage.elements.map(inEl=>{const localEl=localElements.get(inEl.id);if(!localEl)return inEl;if(strategy==="incoming")return inEl;const merged={...inEl} as Record<string,unknown>;for(const key of Object.keys(merged))if(conflictKeys.has(`${inPage.id}:${inEl.id}:${key}`))merged[key]=(localEl as unknown as Record<string,unknown>)[key];return merged as unknown as PublisherElement;}); mergedPages.push({...inPage,elements}); } for(const page of local.pages) if(!incomingPages.has(page.id)) mergedPages.push(page); return {project:{...local,pages:mergedPages,activePageId:mergedPages.some(page=>page.id===local.activePageId)?local.activePageId:mergedPages[0]?.id??local.activePageId,updatedAt:Date.now()},conflicts}; }
export function mergeBranch(project:PublisherProject,sourceBranchId:string,strategy:"local"|"incoming"="incoming",author="Project Owner"):{project:PublisherProject;conflicts:MergeConflict[]}{ const state=getPhase23State(project),source=state.branches.find(branch=>branch.id===sourceBranchId&&!branch.archivedAt),target=state.branches.find(branch=>branch.id===state.activeBranchId); if(!source||!target) throw new Error("Source or target branch was not found."); if(source.id===target.id) throw new Error("Choose a different source branch."); const base=state.versions.find(version=>version.id===source.baseVersionId)?.project??target.project; const merged=mergeProjects(base,project,source.project,strategy); const snapshot=cleanProject(merged.project); const record:BranchMergeRecord={id:uid("merge"),sourceBranchId:source.id,sourceBranchName:source.name,targetBranchId:target.id,targetBranchName:target.name,createdAt:Date.now(),author:author.trim()||"Project Owner",conflictCount:merged.conflicts.length,strategy,resultHash:hashProject(snapshot)}; const nextState={...state,mergeHistory:[record,...state.mergeHistory].slice(0,100),branches:state.branches.map(branch=>branch.id===target.id?{...branch,project:snapshot,headHash:record.resultHash,updatedAt:Date.now()}:branch)}; return {project:withPhase23State(merged.project,nextState),conflicts:merged.conflicts}; }

export function setReleasePolicy(project:PublisherProject,policy:ReleasePolicy):PublisherProject {
 const state=getPhase23State(project);
 const normalized:ReleasePolicy={...policy,minimumApprovals:Math.max(0,Math.floor(policy.minimumApprovals)),requiredRoles:[...new Set(policy.requiredRoles)]};
 return withPhase23State(project,{...state,releasePolicies:releaseOrder.map(channel=>channel===normalized.channel?normalized:state.releasePolicies.find(item=>item.channel===channel)??defaultReleasePolicies.find(item=>item.channel===channel)!)});
}
export function submitBranchApproval(project:PublisherProject,branchId:string,reviewer:string,role:ApprovalRole,decision:ApprovalDecision,note?:string):PublisherProject {
 const state=getPhase23State(project); const branch=state.branches.find(item=>item.id===branchId&&!item.archivedAt); if(!branch) throw new Error("Branch was not found or is archived.");
 const approval:BranchApproval={id:uid("approval"),branchId,branchHash:branch.id===state.activeBranchId?hashProject(project):branch.headHash,reviewer:reviewer.trim()||"Reviewer",role,decision,note:note?.trim(),createdAt:Date.now()};
 const approvals=[approval,...state.approvals.filter(item=>!(item.branchId===branchId&&item.reviewer.toLowerCase()===approval.reviewer.toLowerCase()&&item.role===role))].slice(0,500);
 return withPhase23State(project,{...state,approvals});
}
export function revokeBranchApproval(project:PublisherProject,approvalId:string):PublisherProject { const state=getPhase23State(project); return withPhase23State(project,{...state,approvals:state.approvals.filter(item=>item.id!==approvalId)}); }
export function evaluateReleaseReadiness(project:PublisherProject,branchId:string,targetChannel:ReleaseChannel):ReleaseReadiness {
 const state=getPhase23State(project); const branch=state.branches.find(item=>item.id===branchId&&!item.archivedAt); if(!branch) throw new Error("Branch was not found or is archived."); const policy=state.releasePolicies.find(item=>item.channel===targetChannel)??defaultReleasePolicies.find(item=>item.channel===targetChannel)!;
 const currentHash=branch.id===state.activeBranchId?hashProject(project):branch.headHash; const validApprovals=state.approvals.filter(item=>item.branchId===branchId&&item.branchHash===currentHash&&item.decision==="approved"); const requested=state.approvals.filter(item=>item.branchId===branchId&&item.branchHash===currentHash&&item.decision==="changes-requested"); const blockers:string[]=[]; const warnings:string[]=[];
 if(releaseOrder.indexOf(targetChannel)<=releaseOrder.indexOf(branch.channel)) blockers.push("Target channel must be later than the current channel.");
 if(validApprovals.length<policy.minimumApprovals) blockers.push(`Requires ${policy.minimumApprovals} approval(s); ${validApprovals.length} valid approval(s) recorded.`);
 for(const role of policy.requiredRoles) if(!validApprovals.some(item=>item.role===role)) blockers.push(`Missing required ${role} approval.`);
 if(policy.blockChangesRequested&&requested.length) blockers.push(`${requested.length} reviewer(s) requested changes for the current branch snapshot.`);
 if(policy.requireImmutableVersion&&!state.versions.some(version=>version.projectHash===currentHash&&version.branchId===branchId)) blockers.push("Create an immutable version for the current branch snapshot.");
 const cert=certifyPhase23(project); if(policy.requireCertified&&!cert.passed) blockers.push("Phase 23 production certification must pass before promotion.");
 if(branch.headHash!==currentHash) warnings.push("The active branch has unsaved changes; save the branch snapshot before promotion.");
 const checks=policy.requiredRoles.length+policy.minimumApprovals+Number(policy.requireCertified)+Number(policy.requireImmutableVersion)+Number(policy.blockChangesRequested); const score=Math.max(0,Math.round(100-(blockers.length*100/Math.max(1,checks))));
 return {branchId:branch.id,branchName:branch.name,channel:branch.channel,targetChannel,score,ready:blockers.length===0,blockers,warnings,validApprovals,policy};
}
export function promoteBranch(project:PublisherProject,branchId:string,targetChannel:ReleaseChannel,promotedBy="Project Owner",note?:string):PublisherProject {
 let saved=saveActiveBranch(project); const state=getPhase23State(saved); const branch=state.branches.find(item=>item.id===branchId&&!item.archivedAt); if(!branch) throw new Error("Branch was not found or is archived."); const readiness=evaluateReleaseReadiness(saved,branchId,targetChannel); if(!readiness.ready) throw new Error(readiness.blockers.join(" ")); const hash=branch.id===state.activeBranchId?hashProject(saved):branch.headHash; const record:PromotionRecord={id:uid("promotion"),branchId,branchName:branch.name,fromChannel:branch.channel,toChannel:targetChannel,promotedBy:promotedBy.trim()||"Project Owner",note:note?.trim(),createdAt:Date.now(),branchHash:hash,readinessScore:readiness.score,approvalIds:readiness.validApprovals.map(item=>item.id)};
 return withPhase23State(saved,{...state,branches:state.branches.map(item=>item.id===branchId?{...item,channel:targetChannel,updatedAt:Date.now(),headHash:hash}:item),promotionHistory:[record,...state.promotionHistory].slice(0,200)});
}

export function createChangeSet(project:PublisherProject,baseVersionId:string,author="Project Owner",note?:string):ChangeSet { const state=getPhase23State(project); const base=state.versions.find(v=>v.id===baseVersionId); if(!base) throw new Error("Base version was not found."); return {schema:"yaposan.phase23.changeset",version:1,id:uid("changeset"),projectId:project.id,projectName:project.name,baseHash:base.projectHash,createdAt:Date.now(),author:author.trim()||"Project Owner",note:note?.trim(),changes:diffProjects(base.project,project),sourceProject:cleanProject(project)}; }
export function serializeChangeSet(set:ChangeSet){ return JSON.stringify(set,null,2); }
export function parseChangeSet(source:string):ChangeSet { const value=JSON.parse(source) as ChangeSet; if(value.schema!=="yaposan.phase23.changeset"||value.version!==1||!Array.isArray(value.changes)) throw new Error("Unsupported Phase 23 change set."); return value; }
export function applyChangeSet(project:PublisherProject,set:ChangeSet,strategy:"local"|"incoming"="incoming"):{project:PublisherProject;conflicts:MergeConflict[]} { const state=getPhase23State(project); const base=state.versions.find(v=>v.projectHash===set.baseHash); if(!base) throw new Error("The change set base version is not available in this project."); const merged=mergeProjects(base.project,project,set.sourceProject,strategy); const next=withPhase23State(merged.project,{...state,importedChangeSets:[set,...state.importedChangeSets.filter(x=>x.id!==set.id)].slice(0,50)}); return {project:next,conflicts:merged.conflicts}; }

export function certifyPhase23(project:PublisherProject):Phase23Certification { const state=getPhase23State(project),issues:string[]=[]; if(!project.pages.length) issues.push("Project contains no pages."); if(!state.versions.length) issues.push("No immutable project version has been created."); if(!state.branches.length) issues.push("No project branch exists."); if(!state.branches.some(branch=>branch.id===state.activeBranchId&&!branch.archivedAt)) issues.push("The active branch is missing or archived."); const branchNames=new Set<string>(); for(const branch of state.branches.filter(item=>!item.archivedAt)){const key=branch.name.trim().toLowerCase();if(branchNames.has(key))issues.push(`Duplicate branch name: ${branch.name}`);branchNames.add(key);if(branch.headHash!==hashProject(branch.project))issues.push(`Branch integrity hash is invalid: ${branch.name}`);} const ids=new Set<string>(); for(const page of project.pages){ if(ids.has(page.id)) issues.push(`Duplicate page id: ${page.id}`); ids.add(page.id); for(const el of page.elements){ if(ids.has(el.id)) issues.push(`Duplicate element id: ${el.id}`); ids.add(el.id); } } if(state.versions[0]&&state.versions[0].projectHash!==hashProject(state.versions[0].project)) issues.push("Latest version integrity hash is invalid."); for(const policy of state.releasePolicies){ if(policy.minimumApprovals<policy.requiredRoles.length) issues.push(`Release policy for ${policy.channel} requires fewer approvals than required roles.`); } const score=Math.max(0,100-issues.length*15); return {generatedAt:Date.now(),score,passed:issues.length===0,issues,versionCount:state.versions.length,currentHash:hashProject(project),branchCount:state.branches.filter(branch=>!branch.archivedAt).length,activeBranchId:state.activeBranchId,approvalCount:state.approvals.length,promotionCount:state.promotionHistory.length}; }
export function storePhase23Certification(project:PublisherProject):PublisherProject { const state=getPhase23State(project); return withPhase23State(project,{...state,lastCertification:certifyPhase23(project)}); }
export function exportPhase23Report(project:PublisherProject){ const state=getPhase23State(project); return JSON.stringify({schema:"yaposan.phase23.certification",version:3,phase:"23.2",project:{id:project.id,name:project.name,hash:hashProject(project)},generatedAt:Date.now(),versions:state.versions.map(({project:_,...v})=>v),branches:state.branches.map(({project:_,...branch})=>branch),mergeHistory:state.mergeHistory,approvals:state.approvals,releasePolicies:state.releasePolicies,promotionHistory:state.promotionHistory,importedChangeSets:state.importedChangeSets.map(({sourceProject:_,...s})=>s),certification:certifyPhase23(project)},null,2); }
