import type { PublisherProject } from "../types/publisher";
import { buildPageNumberMap, normalizeDocumentFoundation } from "./documentFoundationEngine";

export type NoteKind = "footnote" | "endnote";
export type ReferenceTargetKind = "page" | "section" | "bookmark" | "element" | "url";
export type DocumentBookmark = { id:string; name:string; pageId:string; elementId?:string; description?:string; createdAt:number; updatedAt:number };
export type DocumentNote = { id:string; kind:NoteKind; marker:string; text:string; pageId:string; elementId?:string; order:number; createdAt:number; updatedAt:number };
export type CrossReference = { id:string; label:string; sourcePageId?:string; sourceElementId?:string; targetKind:ReferenceTargetKind; targetId:string; displayMode:"label"|"page-number"|"label-and-page"; createdAt:number; updatedAt:number };
export type IndexEntry = { id:string; term:string; subterm?:string; pageIds:string[]; see?:string; seeAlso?:string[]; createdAt:number; updatedAt:number };
export type TocEntry = { id:string; title:string; level:number; pageId:string; pageNumber:string; elementId?:string; sectionId?:string };
export type DocumentReferenceState = {
  version:"21.2"; bookmarks:DocumentBookmark[]; notes:DocumentNote[]; crossReferences:CrossReference[]; indexEntries:IndexEntry[];
  tocSettings:{title:string;maxLevel:number;includeSections:boolean;includeStyledHeadings:boolean}; updatedAt:number;
};
export type ReferenceValidationIssue = { id:string; severity:"error"|"warning"; message:string; referenceId?:string };
const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const now=()=>Date.now();

export function createDocumentReferenceState():DocumentReferenceState{return{version:"21.2",bookmarks:[],notes:[],crossReferences:[],indexEntries:[],tocSettings:{title:"Table of Contents",maxLevel:3,includeSections:true,includeStyledHeadings:true},updatedAt:now()};}
export function normalizeDocumentReferences(project:PublisherProject):PublisherProject{
  const base=project.documentReferences??createDocumentReferenceState(); const pageIds=new Set(project.pages.map(p=>p.id)); const elementIds=new Set(project.pages.flatMap(p=>p.elements.map(e=>e.id)));
  const bookmarks=(base.bookmarks??[]).filter(b=>b.id&&pageIds.has(b.pageId)&&(!b.elementId||elementIds.has(b.elementId)));
  const notes=(base.notes??[]).filter(n=>n.id&&pageIds.has(n.pageId)&&(!n.elementId||elementIds.has(n.elementId))).sort((a,b)=>a.order-b.order).map((n,i)=>({...n,order:i+1,marker:n.marker||String(i+1)}));
  const indexEntries=(base.indexEntries??[]).filter(e=>e.id&&e.term).map(e=>({...e,pageIds:[...new Set(e.pageIds.filter(id=>pageIds.has(id)))]}));
  return {...project,phase21Version:"21.2",documentReferences:{...createDocumentReferenceState(),...base,version:"21.2",bookmarks,notes,indexEntries,crossReferences:base.crossReferences??[],updatedAt:now()}};
}
export function addBookmark(project:PublisherProject,input:{name:string;pageId:string;elementId?:string;description?:string}):PublisherProject{const p=normalizeDocumentReferences(project),t=now();if(!p.pages.some(x=>x.id===input.pageId))throw new Error("Bookmark page does not exist.");const b:DocumentBookmark={id:uid("bookmark"),name:input.name.trim()||"Bookmark",pageId:input.pageId,elementId:input.elementId,description:input.description,createdAt:t,updatedAt:t};return{...p,updatedAt:t,documentReferences:{...p.documentReferences!,bookmarks:[...p.documentReferences!.bookmarks,b],updatedAt:t}};}
export function updateBookmark(project:PublisherProject,id:string,updates:Partial<Omit<DocumentBookmark,"id"|"createdAt">>):PublisherProject{const p=normalizeDocumentReferences(project),t=now();return{...p,updatedAt:t,documentReferences:{...p.documentReferences!,bookmarks:p.documentReferences!.bookmarks.map(b=>b.id===id?{...b,...updates,id:b.id,createdAt:b.createdAt,updatedAt:t}:b),updatedAt:t}};}
export function deleteBookmark(project:PublisherProject,id:string):PublisherProject{const p=normalizeDocumentReferences(project),t=now();return{...p,updatedAt:t,documentReferences:{...p.documentReferences!,bookmarks:p.documentReferences!.bookmarks.filter(b=>b.id!==id),crossReferences:p.documentReferences!.crossReferences.filter(r=>!(r.targetKind==="bookmark"&&r.targetId===id)),updatedAt:t}};}
export function addNote(project:PublisherProject,input:{kind:NoteKind;text:string;pageId:string;elementId?:string}):PublisherProject{const p=normalizeDocumentReferences(project),t=now(),same=p.documentReferences!.notes.filter(n=>n.kind===input.kind);const n:DocumentNote={id:uid(input.kind),kind:input.kind,text:input.text.trim(),pageId:input.pageId,elementId:input.elementId,order:same.length+1,marker:String(same.length+1),createdAt:t,updatedAt:t};return{...p,updatedAt:t,documentReferences:{...p.documentReferences!,notes:[...p.documentReferences!.notes,n],updatedAt:t}};}
export function updateNote(project:PublisherProject,id:string,updates:Partial<Omit<DocumentNote,"id"|"createdAt">>):PublisherProject{const p=normalizeDocumentReferences(project),t=now();return{...p,updatedAt:t,documentReferences:{...p.documentReferences!,notes:p.documentReferences!.notes.map(n=>n.id===id?{...n,...updates,id:n.id,createdAt:n.createdAt,updatedAt:t}:n),updatedAt:t}};}
export function deleteNote(project:PublisherProject,id:string):PublisherProject{const p=normalizeDocumentReferences(project),t=now();const notes=p.documentReferences!.notes.filter(n=>n.id!==id).map((n,i)=>({...n,order:i+1,marker:String(i+1)}));return{...p,updatedAt:t,documentReferences:{...p.documentReferences!,notes,updatedAt:t}};}
export function addCrossReference(project:PublisherProject,input:Omit<CrossReference,"id"|"createdAt"|"updatedAt">):PublisherProject{const p=normalizeDocumentReferences(project),t=now();const r:CrossReference={...input,id:uid("xref"),createdAt:t,updatedAt:t};return{...p,updatedAt:t,documentReferences:{...p.documentReferences!,crossReferences:[...p.documentReferences!.crossReferences,r],updatedAt:t}};}
export function deleteCrossReference(project:PublisherProject,id:string):PublisherProject{const p=normalizeDocumentReferences(project),t=now();return{...p,updatedAt:t,documentReferences:{...p.documentReferences!,crossReferences:p.documentReferences!.crossReferences.filter(r=>r.id!==id),updatedAt:t}};}
export function addIndexEntry(project:PublisherProject,input:{term:string;subterm?:string;pageId:string;see?:string}):PublisherProject{const p=normalizeDocumentReferences(project),t=now(),term=input.term.trim();if(!term)throw new Error("Index term is required.");const found=p.documentReferences!.indexEntries.find(e=>e.term.toLowerCase()===term.toLowerCase()&&(e.subterm??"").toLowerCase()===(input.subterm??"").toLowerCase());const entries=found?p.documentReferences!.indexEntries.map(e=>e.id===found.id?{...e,pageIds:[...new Set([...e.pageIds,input.pageId])],updatedAt:t}:e):[...p.documentReferences!.indexEntries,{id:uid("index"),term,subterm:input.subterm?.trim()||undefined,pageIds:[input.pageId],see:input.see?.trim()||undefined,createdAt:t,updatedAt:t}];return{...p,updatedAt:t,documentReferences:{...p.documentReferences!,indexEntries:entries,updatedAt:t}};}
export function deleteIndexEntry(project:PublisherProject,id:string):PublisherProject{const p=normalizeDocumentReferences(project),t=now();return{...p,updatedAt:t,documentReferences:{...p.documentReferences!,indexEntries:p.documentReferences!.indexEntries.filter(e=>e.id!==id),updatedAt:t}};}
export function buildTableOfContents(project:PublisherProject):TocEntry[]{const p=normalizeDocumentFoundation(normalizeDocumentReferences(project)),numbers=new Map(buildPageNumberMap(p).map(n=>[n.pageId,n])),out:TocEntry[]=[];if(p.documentReferences!.tocSettings.includeSections)p.documentFoundation!.sections.forEach(s=>{const pageId=s.pageIds[0];if(pageId)out.push({id:`toc-section-${s.id}`,title:s.name,level:1,pageId,pageNumber:numbers.get(pageId)?.display??"",sectionId:s.id});});if(p.documentReferences!.tocSettings.includeStyledHeadings)p.pages.forEach(page=>page.elements.forEach(e=>{if(e.type!=="text"||!e.text)return;const style=e.documentStyleId??e.paragraphStyleId??"";const match=style.match(/heading[- ]?(\d)/i);if(match){const level=Math.min(Number(match[1]),p.documentReferences!.tocSettings.maxLevel);out.push({id:`toc-element-${e.id}`,title:e.text.split("\n")[0].slice(0,120),level,pageId:page.id,pageNumber:numbers.get(page.id)?.display??"",elementId:e.id});}}));return out.sort((a,b)=>p.pages.findIndex(x=>x.id===a.pageId)-p.pages.findIndex(x=>x.id===b.pageId)||a.level-b.level);}
export function buildIndex(project:PublisherProject){const p=normalizeDocumentFoundation(normalizeDocumentReferences(project)),numbers=new Map(buildPageNumberMap(p).map(n=>[n.pageId,n.display]));return [...p.documentReferences!.indexEntries].sort((a,b)=>a.term.localeCompare(b.term)||((a.subterm??"").localeCompare(b.subterm??""))).map(e=>({...e,pageNumbers:e.pageIds.map(id=>numbers.get(id)??"?")}));}
export function resolveCrossReference(project:PublisherProject,id:string):string{const p=normalizeDocumentFoundation(normalizeDocumentReferences(project)),r=p.documentReferences!.crossReferences.find(x=>x.id===id);if(!r)return"Missing reference";let label=r.label,pageId:string|undefined;if(r.targetKind==="page")pageId=r.targetId;if(r.targetKind==="section"){const s=p.documentFoundation!.sections.find(x=>x.id===r.targetId);label=s?.name??label;pageId=s?.pageIds[0];}if(r.targetKind==="bookmark"){const b=p.documentReferences!.bookmarks.find(x=>x.id===r.targetId);label=b?.name??label;pageId=b?.pageId;}if(r.targetKind==="element"){for(const page of p.pages)if(page.elements.some(e=>e.id===r.targetId)){pageId=page.id;break;}}if(r.targetKind==="url")return r.targetId;const num=buildPageNumberMap(p).find(n=>n.pageId===pageId)?.display??"?";return r.displayMode==="page-number"?num:r.displayMode==="label-and-page"?`${label} (p. ${num})`:label;}
export function validateDocumentReferences(project:PublisherProject):ReferenceValidationIssue[]{const p=normalizeDocumentReferences(project),pageIds=new Set(p.pages.map(x=>x.id)),elementIds=new Set(p.pages.flatMap(x=>x.elements.map(e=>e.id))),bookmarkIds=new Set(p.documentReferences!.bookmarks.map(b=>b.id)),sectionIds=new Set(normalizeDocumentFoundation(p).documentFoundation!.sections.map(s=>s.id));const issues:ReferenceValidationIssue[]=[];p.documentReferences!.crossReferences.forEach(r=>{let ok=true;if(r.targetKind==="page")ok=pageIds.has(r.targetId);else if(r.targetKind==="section")ok=sectionIds.has(r.targetId);else if(r.targetKind==="bookmark")ok=bookmarkIds.has(r.targetId);else if(r.targetKind==="element")ok=elementIds.has(r.targetId);else if(r.targetKind==="url")ok=/^(https?:|mailto:)/i.test(r.targetId);if(!ok)issues.push({id:`broken-${r.id}`,severity:"error",message:`Broken cross-reference: ${r.label}`,referenceId:r.id});});p.documentReferences!.indexEntries.filter(e=>!e.pageIds.length).forEach(e=>issues.push({id:`index-${e.id}`,severity:"warning",message:`Index entry has no valid pages: ${e.term}`,referenceId:e.id}));return issues;}
export function exportDocumentReferences(project:PublisherProject){const p=normalizeDocumentReferences(project);return JSON.stringify({phase:"21.2",exportedAt:new Date().toISOString(),projectId:p.id,tableOfContents:buildTableOfContents(p),index:buildIndex(p),references:p.documentReferences,validation:validateDocumentReferences(p)},null,2);}
