import type { PublisherElement, PublisherProject } from "../types/publisher";
import { buildPageNumberMap, normalizeDocumentFoundation } from "./documentFoundationEngine";

export type SmartVariableKind = "system" | "metadata" | "custom";
export type SmartVariable = { id:string; name:string; token:string; kind:SmartVariableKind; value?:string; description?:string; createdAt:number; updatedAt:number };
export type RunningContentRule = { id:string; name:string; position:"header"|"footer"; scope:"document"|"section"; sectionId?:string; leftTemplate:string; rightTemplate:string; firstPageTemplate?:string; enabled:boolean; createdAt:number; updatedAt:number };
export type DocumentVariableState = { version:"21.3"; variables:SmartVariable[]; runningContent:RunningContentRule[]; dateFormat:"short"|"long"|"iso"; unresolvedFallback:string; updatedAt:number };
export type VariableContext = { pageId?:string; sectionId?:string; elementId?:string; now?:Date; fileName?:string };
export type VariableValidationIssue = { id:string; severity:"error"|"warning"; message:string; ruleId?:string; token?:string };

const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const now=()=>Date.now();
const BUILT_INS: Array<Pick<SmartVariable,"name"|"token"|"kind"|"description">> = [
  {name:"Document Title",token:"{{document.title}}",kind:"metadata",description:"Publication title"},
  {name:"Author",token:"{{document.author}}",kind:"metadata",description:"Publication author"},
  {name:"Company",token:"{{document.company}}",kind:"metadata",description:"Organization name"},
  {name:"Subject",token:"{{document.subject}}",kind:"metadata",description:"Publication subject"},
  {name:"Publisher",token:"{{document.publisher}}",kind:"metadata",description:"Publisher name"},
  {name:"Version",token:"{{document.version}}",kind:"metadata",description:"Document version"},
  {name:"Revision",token:"{{document.revision}}",kind:"metadata",description:"Document revision"},
  {name:"Page Number",token:"{{page.number}}",kind:"system",description:"Formatted page number"},
  {name:"Total Pages",token:"{{page.total}}",kind:"system",description:"Total publication pages"},
  {name:"Section Name",token:"{{section.name}}",kind:"system",description:"Current section or chapter"},
  {name:"Section Number",token:"{{section.number}}",kind:"system",description:"Current section position"},
  {name:"Page Name",token:"{{page.name}}",kind:"system",description:"Current page name"},
  {name:"Current Date",token:"{{date.current}}",kind:"system",description:"Current date"},
  {name:"Modified Date",token:"{{date.modified}}",kind:"system",description:"Last modified date"},
  {name:"File Name",token:"{{file.name}}",kind:"system",description:"Project file name"},
];

export function createDocumentVariableState():DocumentVariableState{const t=now();return{version:"21.3",variables:BUILT_INS.map((v,i)=>({id:`builtin-${i+1}`,...v,createdAt:t,updatedAt:t})),runningContent:[],dateFormat:"long",unresolvedFallback:"",updatedAt:t};}
export function normalizeDocumentVariables(project:PublisherProject):PublisherProject{const base=project.documentVariables??createDocumentVariableState();const defaults=createDocumentVariableState();const byToken=new Map((base.variables??[]).map(v=>[v.token,v]));const variables=[...defaults.variables.map(v=>byToken.get(v.token)??v),...(base.variables??[]).filter(v=>!defaults.variables.some(d=>d.token===v.token)&&v.name&&v.token)];const sectionIds=new Set(normalizeDocumentFoundation(project).documentFoundation!.sections.map(s=>s.id));const runningContent=(base.runningContent??[]).filter(r=>r.id&&r.name&&(!r.sectionId||sectionIds.has(r.sectionId)));return{...project,phase21Version:"21.3",documentVariables:{...defaults,...base,version:"21.3",variables,runningContent,updatedAt:now()}};}

export function addCustomVariable(project:PublisherProject,name:string,value:string):PublisherProject{const p=normalizeDocumentVariables(project),t=now(),clean=name.trim();if(!clean)throw new Error("Variable name is required.");const key=clean.toLowerCase().replace(/[^a-z0-9]+/g,".").replace(/^\.|\.$/g,"")||"value";let token=`{{custom.${key}}}`;let n=2;while(p.documentVariables!.variables.some(v=>v.token===token))token=`{{custom.${key}.${n++}}}`;const variable:SmartVariable={id:uid("variable"),name:clean,token,kind:"custom",value,createdAt:t,updatedAt:t};return{...p,updatedAt:t,documentVariables:{...p.documentVariables!,variables:[...p.documentVariables!.variables,variable],updatedAt:t}};}
export function updateCustomVariable(project:PublisherProject,id:string,updates:Partial<Pick<SmartVariable,"name"|"value"|"description">>):PublisherProject{const p=normalizeDocumentVariables(project),t=now();return{...p,updatedAt:t,documentVariables:{...p.documentVariables!,variables:p.documentVariables!.variables.map(v=>v.id===id&&v.kind==="custom"?{...v,...updates,updatedAt:t}:v),updatedAt:t}};}
export function deleteCustomVariable(project:PublisherProject,id:string):PublisherProject{const p=normalizeDocumentVariables(project),target=p.documentVariables!.variables.find(v=>v.id===id);if(!target||target.kind!=="custom")return p;const t=now();return{...p,updatedAt:t,documentVariables:{...p.documentVariables!,variables:p.documentVariables!.variables.filter(v=>v.id!==id),updatedAt:t}};}
export function addRunningContentRule(project:PublisherProject,input:Omit<RunningContentRule,"id"|"createdAt"|"updatedAt">):PublisherProject{const p=normalizeDocumentVariables(project),t=now();const rule:RunningContentRule={...input,id:uid("running"),createdAt:t,updatedAt:t};return{...p,updatedAt:t,documentVariables:{...p.documentVariables!,runningContent:[...p.documentVariables!.runningContent,rule],updatedAt:t}};}
export function updateRunningContentRule(project:PublisherProject,id:string,updates:Partial<Omit<RunningContentRule,"id"|"createdAt">>):PublisherProject{const p=normalizeDocumentVariables(project),t=now();return{...p,updatedAt:t,documentVariables:{...p.documentVariables!,runningContent:p.documentVariables!.runningContent.map(r=>r.id===id?{...r,...updates,id:r.id,createdAt:r.createdAt,updatedAt:t}:r),updatedAt:t}};}
export function deleteRunningContentRule(project:PublisherProject,id:string):PublisherProject{const p=normalizeDocumentVariables(project),t=now();return{...p,updatedAt:t,documentVariables:{...p.documentVariables!,runningContent:p.documentVariables!.runningContent.filter(r=>r.id!==id),updatedAt:t}};}
function dateValue(value:Date,format:DocumentVariableState["dateFormat"]){if(format==="iso")return value.toISOString().slice(0,10);if(format==="short")return value.toLocaleDateString(undefined,{year:"numeric",month:"numeric",day:"numeric"});return value.toLocaleDateString(undefined,{year:"numeric",month:"long",day:"numeric"});}
export function buildVariableMap(project:PublisherProject,context:VariableContext={}):Record<string,string>{const p=normalizeDocumentFoundation(normalizeDocumentVariables(project)),state=p.documentVariables!,metadata=p.documentFoundation!.metadata,pageId=context.pageId??p.activePageId,page=p.pages.find(x=>x.id===pageId),section=p.documentFoundation!.sections.find(s=>s.pageIds.includes(pageId)),numbers=buildPageNumberMap(p),number=numbers.find(n=>n.pageId===pageId),d=context.now??new Date();const values:Record<string,string>={"{{document.title}}":metadata.title||p.name,"{{document.author}}":metadata.author||"","{{document.company}}":metadata.company||"","{{document.subject}}":metadata.subject||"","{{document.publisher}}":metadata.publisher||"","{{document.version}}":String(p.version),"{{document.revision}}":String(metadata.revision??""),"{{page.number}}":number?.display??"","{{page.total}}":String(p.pages.length),"{{section.name}}":section?.name??"","{{section.number}}":section?String(p.documentFoundation!.sections.findIndex(s=>s.id===section.id)+1):"","{{page.name}}":page?.name??"","{{date.current}}":dateValue(d,state.dateFormat),"{{date.modified}}":dateValue(new Date(p.updatedAt||d.getTime()),state.dateFormat),"{{file.name}}":context.fileName??p.name};state.variables.filter(v=>v.kind==="custom").forEach(v=>{values[v.token]=v.value??"";});return values;}
export function resolveSmartContent(project:PublisherProject,text:string,context:VariableContext={}):string{const p=normalizeDocumentVariables(project),map=buildVariableMap(p,context);return text.replace(/\{\{[^{}]+\}\}/g,token=>Object.prototype.hasOwnProperty.call(map,token)?map[token]:p.documentVariables!.unresolvedFallback);}
export function insertVariableIntoElements(project:PublisherProject,token:string,elementIds:string[]):PublisherProject{const p=normalizeDocumentVariables(project),ids=new Set(elementIds),t=now();if(!p.documentVariables!.variables.some(v=>v.token===token))throw new Error("Variable does not exist.");return{...p,updatedAt:t,pages:p.pages.map(page=>({...page,elements:page.elements.map(element=>ids.has(element.id)&&element.type==="text"?{...element,text:`${element.text??""}${element.text?" ":""}${token}`} : element)}))};}
export function resolveProjectSmartContent(project:PublisherProject):PublisherProject{const p=normalizeDocumentVariables(project),t=now();return{...p,updatedAt:t,pages:p.pages.map(page=>({...page,elements:page.elements.map(element=>element.type==="text"&&element.text?.includes("{{")?{...element,text:resolveSmartContent(p,element.text,{pageId:page.id,elementId:element.id})}:element)}))};}
export function renderRunningContent(project:PublisherProject,pageId:string):{header:string;footer:string}{const p=normalizeDocumentFoundation(normalizeDocumentVariables(project)),info=buildPageNumberMap(p).find(n=>n.pageId===pageId),section=p.documentFoundation!.sections.find(s=>s.pageIds.includes(pageId)),pageIndex=section?.pageIds.indexOf(pageId)??0;const eligible=p.documentVariables!.runningContent.filter(r=>r.enabled&&(r.scope==="document"||r.sectionId===section?.id));const choose=(position:"header"|"footer")=>{const rule=[...eligible].reverse().find(r=>r.position===position);if(!rule)return"";const template=pageIndex===0&&rule.firstPageTemplate!==undefined?rule.firstPageTemplate:info?.side==="left"?rule.leftTemplate:rule.rightTemplate;return resolveSmartContent(p,template,{pageId,sectionId:section?.id});};return{header:choose("header"),footer:choose("footer")};}
export function validateDocumentVariables(project:PublisherProject):VariableValidationIssue[]{const p=normalizeDocumentVariables(project),issues:VariableValidationIssue[]=[],tokens=new Set<string>();p.documentVariables!.variables.forEach(v=>{if(tokens.has(v.token))issues.push({id:`duplicate-${v.id}`,severity:"error",message:`Duplicate variable token ${v.token}.`,token:v.token});tokens.add(v.token);});const known=new Set(p.documentVariables!.variables.map(v=>v.token));p.documentVariables!.runningContent.forEach(r=>{[r.leftTemplate,r.rightTemplate,r.firstPageTemplate??""].join(" ").match(/\{\{[^{}]+\}\}/g)?.forEach(token=>{if(!known.has(token))issues.push({id:`unknown-${r.id}-${token}`,severity:"warning",message:`${r.name} uses unknown token ${token}.`,ruleId:r.id,token});});});return issues;}
export function exportDocumentVariables(project:PublisherProject){const p=normalizeDocumentVariables(project);return JSON.stringify({phase:"21.3",generatedAt:new Date().toISOString(),variables:p.documentVariables,preview:p.pages.map(page=>({pageId:page.id,...renderRunningContent(p,page.id)})),issues:validateDocumentVariables(p)},null,2);}
