import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { File as ExpoFile, Paths } from 'expo-file-system';
import type { PublisherPage, PublisherProject } from '../types/publisher';
import type { BatchExportRequest, ExportFormat, ExportJob, ExportOptions, ExportPreset, ExportSummary, ExportWarning } from '../types/export';
import { pageToSvg } from './pageSvgExport';

const JOBS_KEY='yaposan:phase9:export-jobs',PRESETS_KEY='yaposan:phase9:export-presets';
const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const yieldToUi=()=>new Promise<void>(resolve=>setTimeout(resolve,0));
const safe=(v:string)=>v.trim().replace(/[\\/:*?"<>|]+/g,'-')||'publication';
export const BUILT_IN_EXPORT_PRESETS:ExportPreset[]=[['social','Social Media','Social Media',['png','jpg'],96,'high','RGB'],['flyer','Flyer Print','Flyer',['pdf','png'],300,'maximum','CMYK'],['poster','Poster Print','Poster',['pdf'],300,'maximum','CMYK'],['banner','Banner','Banner',['pdf','png'],150,'high','CMYK'],['business','Business Card','Business Card',['pdf'],600,'maximum','CMYK'],['brochure','Brochure','Brochure',['pdf'],300,'maximum','CMYK'],['booklet','Booklet','Booklet',['pdf'],300,'maximum','CMYK'],['label','Label','Label',['pdf','png'],600,'maximum','CMYK'],['sticker','Sticker','Sticker',['png','pdf'],300,'maximum','CMYK'],['presentation','Presentation','Presentation',['pdf','jpg'],150,'high','RGB']].map(([id,name,category,formats,dpi,quality,colorMode])=>({id:`builtin-${id}`,name:name as string,category:category as ExportPreset['category'],formats:formats as ExportFormat[],dpi:dpi as number,quality:quality as ExportPreset['quality'],colorMode:colorMode as ExportPreset['colorMode'],background:'white',backgroundColor:'#FFFFFF',bleed:['flyer','poster','business','brochure','booklet','label','sticker'].includes(id as string),cropMarks:false,registrationMarks:false,safeArea:true,margins:true,builtIn:true,favorite:false}));
export const DEFAULT_EXPORT_OPTIONS:ExportOptions={formats:['pdf'],pageMode:'all',selectedPageIds:[],pageRange:'',dpi:300,customDpi:300,quality:'high',background:'white',backgroundColor:'#FFFFFF',colorMode:'RGB',bleed:false,bleedSize:9,cropMarks:false,registrationMarks:false,safeArea:true,safeAreaSize:18,margins:true,marginSize:18,hyperlinks:true,bookmarks:true,metadata:true,embedFonts:true,preserveVectors:true,preserveText:true,preserveGradients:true,compression:85,password:'',ownerPassword:'',fileNameTemplate:'{project}-{format}-{number}',autoNumber:true,parallelExports:true,maxConcurrency:2,generateReport:true,pdfXReady:true};
export function resolvePages(project:PublisherProject,o:ExportOptions){if(o.pageMode==='current')return project.pages.filter(p=>p.id===project.activePageId);if(o.pageMode==='selected')return project.pages.filter(p=>o.selectedPageIds.includes(p.id));if(o.pageMode==='range'){const ids=new Set<number>();o.pageRange.split(',').forEach(part=>{const [a,b]=part.trim().split('-').map(Number);if(Number.isFinite(a)){for(let i=a;i<=(Number.isFinite(b)?b:a);i++)ids.add(i-1);}});return project.pages.filter((_,i)=>ids.has(i));}return project.pages;}
function fontAvailable(font:string){return Platform.OS!=='web'||typeof document==='undefined'||!document.fonts||document.fonts.check(`16px "${font}"`);}
export function validateExport(project:PublisherProject,o:ExportOptions):ExportSummary{const pages=resolvePages(project,o),warnings:ExportWarning[]=[];if(!pages.length)warnings.push({code:'NO_PAGES',severity:'error',message:'No pages are selected for export.'});if(!o.formats.length)warnings.push({code:'NO_FORMAT',severity:'error',message:'Select at least one export format.'});pages.forEach(p=>p.elements.forEach(e=>{if(e.hidden)return;if(e.type==='text'){const f=e.fontFamily||'Arial';if(!fontAvailable(f))warnings.push({code:'MISSING_FONT',severity:'error',message:`Font “${f}” is not installed or loaded.`,pageId:p.id,elementId:e.id});if(o.formats.includes('pdf')&&o.preserveText&&!project.embeddedFonts?.[f]&&!['Helvetica','Times','Courier'].includes(f))warnings.push({code:'PDF_FONT_SUBSTITUTION',severity:o.pdfXReady?'error':'warning',message:`PDF text uses “${f}”, but the font bytes are not embedded. Embed/import this font to prevent substitution.`,pageId:p.id,elementId:e.id});if(project.embeddedFontMetadata?.[f]?.embeddingPermission==='restricted')warnings.push({code:'FONT_EMBED_RESTRICTED',severity:'error',message:`Font “${f}” prohibits embedding. Replace it or outline the text before export.`,pageId:p.id,elementId:e.id});const lines=Math.max(1,(e.text||'').split('\n').length),need=(e.fontSize||24)*(e.lineHeight||1.2)*lines;if(need>e.height*1.15)warnings.push({code:'TEXT_OVERFLOW',severity:'warning',message:`Text may overflow “${e.name}” on ${p.name}.`,pageId:p.id,elementId:e.id});}if(e.type==='image'&&!e.imageUri)warnings.push({code:'MISSING_IMAGE',severity:'error',message:`Missing image in ${p.name}.`,pageId:p.id,elementId:e.id});if(e.type==='image'&&e.width*e.height>12000000)warnings.push({code:'OVERSIZED_ASSET',severity:'warning',message:`Oversized image object in ${p.name} may increase memory use.`,pageId:p.id,elementId:e.id});if(!['text','image','svg','rectangle','circle','line','triangle','arrow','star'].includes(e.type))warnings.push({code:'UNSUPPORTED_OBJECT',severity:'warning',message:`Unsupported object ${e.type} will be flattened.`,pageId:p.id,elementId:e.id});if(e.opacity<1&&o.pdfXReady)warnings.push({code:'TRANSPARENCY',severity:'warning',message:`Transparency on “${e.name}” may be flattened for print compatibility.`,pageId:p.id,elementId:e.id});}));if(o.colorMode==='CMYK')warnings.push({code:'CMYK_OUTPUT',severity:'info',message:'Vector colors and raster output will be converted for print-oriented CMYK appearance.'});if(o.colorMode==='grayscale')warnings.push({code:'GRAYSCALE_OUTPUT',severity:'info',message:'All raster and vector output will be converted to grayscale.'});if((o.cropMarks||o.registrationMarks)&&!o.bleed)warnings.push({code:'PRINT_MARKS_NO_BLEED',severity:'warning',message:'Print marks are enabled without bleed.'});return{pages:pages.length,formats:o.formats,estimatedFiles:o.formats.reduce((n,f)=>n+(f==='pdf'?1:pages.length),0)+(o.generateReport?1:0),warnings,blocked:warnings.some(w=>w.severity==='error')};}
function fileName(project:PublisherProject,format:ExportFormat|'report',index:number,o:ExportOptions){const d=new Date(),n=o.autoNumber?String(index+1).padStart(2,'0'):'';return safe(o.fileNameTemplate.replace(/\{project\}/g,project.name).replace(/\{format\}/g,format).replace(/\{date\}/g,d.toISOString().slice(0,10)).replace(/\{time\}/g,d.toTimeString().slice(0,8).replace(/:/g,'-')).replace(/\{number\}/g,n))+'.'+(format==='report'?'json':format);}
function background(o:ExportOptions){return o.background==='transparent'?'transparent':o.background==='custom'?o.backgroundColor:'#FFFFFF';}
function pageSvg(page:PublisherPage,o:ExportOptions){const b=o.bleed?o.bleedSize:0,w=page.width+b*2,h=page.height+b*2;let svg=pageToSvg({...page,backgroundColor:background(o)},{hyperlinks:o.hyperlinks,preserveText:o.preserveText,preserveGradients:o.preserveGradients}).replace(`width="${page.width}" height="${page.height}" viewBox="0 0 ${page.width} ${page.height}"`,`width="${w}" height="${h}" viewBox="${-b} ${-b} ${w} ${h}"`);const m:string[]=[];if(o.safeArea)m.push(`<rect x="${o.safeAreaSize}" y="${o.safeAreaSize}" width="${page.width-o.safeAreaSize*2}" height="${page.height-o.safeAreaSize*2}" fill="none" stroke="#00AEEF" stroke-dasharray="6 4"/>`);if(o.margins)m.push(`<rect x="${o.marginSize}" y="${o.marginSize}" width="${page.width-o.marginSize*2}" height="${page.height-o.marginSize*2}" fill="none" stroke="#777" stroke-dasharray="3 3"/>`);if(o.cropMarks)m.push(`<path d="M${-b} 0h${Math.max(6,b)}M0 ${-b}v${Math.max(6,b)}M${page.width+b} 0h${-Math.max(6,b)}M${page.width} ${-b}v${Math.max(6,b)}M${-b} ${page.height}h${Math.max(6,b)}M0 ${page.height+b}v${-Math.max(6,b)}" stroke="#000" fill="none"/>`);if(o.registrationMarks){const pts=[[-b/2,page.height/2],[page.width+b/2,page.height/2],[page.width/2,-b/2],[page.width/2,page.height+b/2]];m.push(...pts.map(([x,y])=>`<g transform="translate(${x} ${y})"><circle r="5" fill="none" stroke="#000"/><path d="M-8 0h16M0-8v16" stroke="#000"/></g>`));}if(o.colorMode==='grayscale')svg=svg.replace('<svg ','<svg style="filter:grayscale(1)" ');return svg.replace('</svg>',m.join('')+'</svg>');}
async function download(data:string|Blob|Uint8Array,name:string,mime:string){if(Platform.OS==='web'&&typeof document!=='undefined'){const blob=data instanceof Blob?data:new Blob([data as BlobPart],{type:mime}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);return name;}const f=new ExpoFile(Paths.cache,name);f.create({overwrite:true,intermediates:true});if(typeof data==='string')f.write(data);else if(data instanceof Blob)f.write(new Uint8Array(await data.arrayBuffer()));else f.write(data);if(await Sharing.isAvailableAsync())await Sharing.shareAsync(f.uri,{mimeType:mime});return f.uri;}
async function canvasFor(svg:string,dpi:number,o:ExportOptions){if(Platform.OS!=='web'||typeof document==='undefined')throw new Error('Raster export requires the web editor.');const img=new Image(),u=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));await new Promise<void>((res,rej)=>{img.onload=()=>res();img.onerror=()=>rej(new Error('Unable to render page.'));img.src=u;});const c=document.createElement('canvas'),scale=Math.max(.25,dpi/96);c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const x=c.getContext('2d',{willReadFrequently:true});if(!x)throw new Error('Canvas unavailable.');x.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(u);if(o.colorMode!=='RGB'){const d=x.getImageData(0,0,c.width,c.height);for(let i=0;i<d.data.length;i+=4){const r=d.data[i],g=d.data[i+1],b=d.data[i+2],y=Math.round(.299*r+.587*g+.114*b);if(o.colorMode==='grayscale')d.data[i]=d.data[i+1]=d.data[i+2]=y;else{d.data[i]=Math.round(r*.93);d.data[i+1]=Math.round(g*.93);d.data[i+2]=Math.round(b*.93);}}x.putImageData(d,0,0);}return c;}
async function encode(svg:string,format:ExportFormat,dpi:number,q:number,o:ExportOptions){const c=await canvasFor(svg,dpi,o);if(format==='tiff'){const UTIF=await import('utif'),rgba=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data,bytes=UTIF.encodeImage(rgba.buffer as ArrayBuffer,c.width,c.height);return new Blob([bytes],{type:'image/tiff'});}if(format==='bmp'){const BMP=await import('bmp-js'),rgba=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data,enc=BMP.encode({data:Buffer.from(rgba),width:c.width,height:c.height});return new Blob([new Uint8Array(enc.data)],{type:'image/bmp'});}const mime=format==='jpg'?'image/jpeg':format==='webp'?'image/webp':'image/png';return await new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Encoding failed.')),mime,q));}
async function webPdf(project:PublisherProject,pages:PublisherPage[],o:ExportOptions){const PDFDocument=(await import('pdfkit')).default as any,blobStream=(await import('blob-stream')).default as any,SVGtoPDF=(await import('svg-to-pdfkit')).default as any;const doc=new PDFDocument({autoFirstPage:false,compress:o.compression>0,info:o.metadata?{Title:project.name,Author:project.author||'',Subject:project.description||'',Creator:'Yaposan Publisher',Producer:'Yaposan Export Engine',CreationDate:new Date(),ModDate:new Date(),GTS_PDFXVersion:o.pdfXReady?'PDF/X-4':''}:{},userPassword:o.password||undefined,ownerPassword:o.ownerPassword||o.password||undefined,permissions:{printing:'highResolution',modifying:false,copying:false}}),stream=doc.pipe(blobStream()); const registered=new Set<string>(); if(o.embedFonts&&project.embeddedFonts){for(const [name,data] of Object.entries(project.embeddedFonts)){try{const raw=data.includes(',')?data.split(',').pop()||'':data;doc.registerFont(name,Buffer.from(raw,'base64'));registered.add(name);}catch{}}} const fontCallback=(family:string,bold:boolean,italic:boolean)=>{if(registered.has(family))return family;const f=String(family||'Helvetica').toLowerCase();if(f.includes('times'))return bold?(italic?'Times-BoldItalic':'Times-Bold'):(italic?'Times-Italic':'Times-Roman');if(f.includes('courier'))return bold?(italic?'Courier-BoldOblique':'Courier-Bold'):(italic?'Courier-Oblique':'Courier');return bold?(italic?'Helvetica-BoldOblique':'Helvetica-Bold'):(italic?'Helvetica-Oblique':'Helvetica');};for(let i=0;i<pages.length;i++){const p=pages[i],b=o.bleed?o.bleedSize:0;doc.addPage({size:[p.width+b*2,p.height+b*2],margin:0});if(o.bookmarks)doc.outline.addItem(`${i+1}. ${p.name}`);SVGtoPDF(doc,pageSvg(p,o),0,0,{width:p.width+b*2,height:p.height+b*2,preserveAspectRatio:'xMidYMid meet',fontCallback});await yieldToUi();}doc.end();return await new Promise<Blob>((res,rej)=>{stream.on('finish',()=>res(stream.toBlob('application/pdf')));stream.on('error',rej);});}
async function mapLimit<T,R>(items:T[],limit:number,fn:(x:T,i:number)=>Promise<R>,cancel:()=>boolean){const out=new Array<R>(items.length);let next=0;async function worker(){while(next<items.length){if(cancel())throw new Error('Export cancelled.');const i=next++;out[i]=await fn(items[i],i);}}await Promise.all(Array.from({length:Math.min(Math.max(1,limit),items.length)},worker));return out;}
export async function performExport(project:PublisherProject,o:ExportOptions,onProgress:(p:number,s:string)=>void,isCancelled:()=>boolean){const started=Date.now(),summary=validateExport(project,o);if(summary.blocked)throw new Error(summary.warnings.filter(w=>w.severity==='error').map(w=>w.message).join(' '));const pages=resolvePages(project,o),files:string[]=[];let done=0,total=o.formats.reduce((n,f)=>n+(f==='pdf'?1:pages.length),0)+(o.generateReport?1:0);const tick=(s:string)=>{done++;onProgress(Math.round(done/total*100),s)};for(const format of o.formats){await yieldToUi();if(isCancelled())throw new Error('Export cancelled.');if(format==='pdf'){const name=fileName(project,'pdf',0,o);if(Platform.OS==='web')files.push(await download(await webPdf(project,pages,o),name,'application/pdf'));else{const html=`<html><body style="margin:0">${pages.map(p=>pageSvg(p,o)).join('')}</body></html>`,r=await Print.printToFileAsync({html});if(await Sharing.isAvailableAsync())await Sharing.shareAsync(r.uri,{mimeType:'application/pdf'});files.push(r.uri);}tick('PDF complete');continue;}const work=pages.map((p,i)=>({p,i})),out=await mapLimit(work,o.parallelExports?o.maxConcurrency:1,async({p,i})=>{await yieldToUi();const svg=pageSvg(p,o),name=fileName(project,format,i,o);if(format==='svg')return download(svg,name,'image/svg+xml');const q={draft:.55,standard:.75,high:.9,maximum:1}[o.quality];const blob=await encode(svg,format,o.dpi===0?o.customDpi:o.dpi,q,o);return download(blob,name,blob.type);},isCancelled);for(const f of out){files.push(f);tick(`${format.toUpperCase()} page complete`);}}if(o.generateReport){files.push(await download(JSON.stringify({project:project.name,exportedAt:new Date().toISOString(),durationMs:Date.now()-started,options:o,files,warnings:summary.warnings},null,2),fileName(project,'report',0,o),'application/json'));tick('Export report complete');}return{files,warnings:summary.warnings,durationMs:Date.now()-started};}
export async function performBatchExport(request:BatchExportRequest,onProgress:(p:number,s:string)=>void,isCancelled:()=>boolean){const files:string[]=[];for(let i=0;i<request.projects.length;i++){const r=await performExport(request.projects[i],request.options,(p,s)=>onProgress(Math.round(((i+p/100)/request.projects.length)*100),`${request.projects[i].name}: ${s}`),isCancelled);files.push(...r.files);}return files;}
export async function loadExportJobs():Promise<ExportJob[]>{try{return JSON.parse((await AsyncStorage.getItem(JOBS_KEY))||'[]')}catch{return[]}}
export async function saveExportJobs(j:ExportJob[]){await AsyncStorage.setItem(JOBS_KEY,JSON.stringify(j.slice(0,100)))}
export async function loadExportPresets():Promise<ExportPreset[]>{try{const x=JSON.parse((await AsyncStorage.getItem(PRESETS_KEY))||'[]') as ExportPreset[];return[...BUILT_IN_EXPORT_PRESETS.map(p=>({...p,favorite:x.find(v=>v.id===p.id)?.favorite||false})),...x.filter(p=>!p.id.startsWith('builtin-'))]}catch{return BUILT_IN_EXPORT_PRESETS}}
export async function saveCustomPresets(p:ExportPreset[]){await AsyncStorage.setItem(PRESETS_KEY,JSON.stringify(p))}
export function createExportJob(project:PublisherProject,options:ExportOptions):ExportJob{return{id:uid('export'),projectId:project.id,projectName:project.name,createdAt:Date.now(),updatedAt:Date.now(),status:'queued',progress:0,currentStep:'Queued',options,warnings:[],files:[],attempt:1}}
