import * as QRCode from "qrcode";
import type { PublisherElement, PublisherPage, PublisherProject } from "../types/publisher";
import { normalizeFieldKey, queryMergeRecords, resolveBoundElement, resolveVariableText, type MailMergeDataSource, type MailMergeProjectData, type MergeCell, type MergePreviewContext, type MergeRecord } from "./mailMergeEngine";
export type AdvancedFilterOperator = "contains"|"notContains"|"equals"|"notEquals"|"beginsWith"|"endsWith"|"isEmpty"|"isNotEmpty"|"greaterThan"|"greaterThanOrEqual"|"lessThan"|"lessThanOrEqual"|"before"|"after"|"between";
export type AdvancedMergeFilter={id:string;field:string;operator:AdvancedFilterOperator;value?:string;secondValue?:string;join:"and"|"or"};
export type MergeConditionalStyle={field:string;operator:Exclude<AdvancedFilterOperator,"between">;value?:string;textColor?:string;fillColor?:string;borderColor?:string;opacity?:number};
export type MergeConditionalImage={field:string;operator:Exclude<AdvancedFilterOperator,"between">;value?:string;trueImageUri?:string;falseImageUri?:string;fallbackImageUri?:string;missingBehavior?:"keep"|"hide"|"fallback"};
export type MergeCompletionSettings={filters:AdvancedMergeFilter[];filterMode:"and"|"or";outputFolder?:string;rememberOutputFolder?:boolean;reportHistory:MergeCompletionReport[];selectedPreviewRecordId?:string};
export type MergeCompletionIssue={recordId:string;sourceRow:number;severity:"warning"|"error";code:string;message:string;field?:string};
export type MergeCompletionReport={id:string;createdAt:number;sourceName:string;attempted:number;completed:number;skipped:number;duplicatesExcluded:number;validationFailures:number;missingFields:number;missingImages:number;filesCreated:string[];filesFailed:string[];issues:MergeCompletionIssue[];startedAt:number;finishedAt:number;durationMs:number};
export type AddressBookContact={id:string;values:Record<string,MergeCell>;groups:string[];createdAt:number;updatedAt:number};
function rawValue(record:MergeRecord,field:string):MergeCell{const n=normalizeFieldKey(field);if(n in record.values)return record.values[n];const d=field.split(".").map(normalizeFieldKey).join("_");return record.values[d]??""}
function compare(record:MergeRecord,filter:Pick<AdvancedMergeFilter,"field"|"operator"|"value"|"secondValue">):boolean{const actual=String(rawValue(record,filter.field)??"").trim();const expected=String(filter.value??"").trim();const a=actual.toLowerCase(),e=expected.toLowerCase();if(filter.operator==="contains")return a.includes(e);if(filter.operator==="notContains")return!a.includes(e);if(filter.operator==="equals")return a===e;if(filter.operator==="notEquals")return a!==e;if(filter.operator==="beginsWith")return a.startsWith(e);if(filter.operator==="endsWith")return a.endsWith(e);if(filter.operator==="isEmpty")return actual==="";if(filter.operator==="isNotEmpty")return actual!=="";const an=Number(actual.replace(/[$,\s]/g,"")),en=Number(expected.replace(/[$,\s]/g,""));if(["greaterThan","greaterThanOrEqual","lessThan","lessThanOrEqual","between"].includes(filter.operator)&&!Number.isNaN(an)&&!Number.isNaN(en)){if(filter.operator==="greaterThan")return an>en;if(filter.operator==="greaterThanOrEqual")return an>=en;if(filter.operator==="lessThan")return an<en;if(filter.operator==="lessThanOrEqual")return an<=en;const upper=Number(String(filter.secondValue??"").replace(/[$,\s]/g,""));return!Number.isNaN(upper)&&an>=en&&an<=upper}if(filter.operator==="before"||filter.operator==="after"){const ad=Date.parse(actual),ed=Date.parse(expected);return!Number.isNaN(ad)&&!Number.isNaN(ed)&&(filter.operator==="before"?ad<ed:ad>ed)}return false}
export function applyAdvancedFilters(records:MergeRecord[],filters:AdvancedMergeFilter[],mode:"and"|"or"="and"):MergeRecord[]{if(!filters.length)return records;return records.filter(r=>mode==="and"?filters.every(f=>compare(r,f)):filters.some(f=>compare(r,f)))}
export function getCompletionRecords(source:MailMergeDataSource,data:MailMergeProjectData):MergeRecord[]{return applyAdvancedFilters(queryMergeRecords(source,data),data.completionSettings?.filters??[],data.completionSettings?.filterMode??"and")}
function esc(v:string){return v.replace(/[<>&'\"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[c]??c))}
export function makeCode128Svg(value:string,width=420,height=120):string{const bars=[...value].flatMap((ch,i)=>{const code=ch.charCodeAt(0)+i*17;return Array.from({length:7},(_,b)=>((code>>(b%8))&1)?3:1)});const total=bars.reduce((s,v)=>s+v,0)||1;let x=10;const body=bars.map((bar,i)=>{const w=(width-20)*bar/total;const rect=i%2===0?`<rect x="${x.toFixed(2)}" y="8" width="${w.toFixed(2)}" height="${height-30}" fill="#000"/>`:"";x+=w;return rect}).join("");return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}"><rect width="100%" height="100%" fill="#fff"/>${body}<text x="50%" y="${height-8}" text-anchor="middle" font-family="Arial" font-size="14">${esc(value)}</text></svg>`}
export async function makeMergeQrSvg(value:string):Promise<string>{return QRCode.toString(value||" ",{type:"svg",margin:1,errorCorrectionLevel:"M"})}
export async function resolveAdvancedElement(element:PublisherElement,context:MergePreviewContext):Promise<PublisherElement>{let resolved=resolveBoundElement(element,context);const advanced=resolved.mergeBinding?.advanced;if(!advanced)return resolved;const styleRule=advanced.styles?.find(rule=>compare(context.record,{field:rule.field,operator:rule.operator,value:rule.value}));if(styleRule)resolved={...resolved,fillColor:styleRule.fillColor??resolved.fillColor,borderColor:styleRule.borderColor??resolved.borderColor,opacity:styleRule.opacity??resolved.opacity,textColor:styleRule.textColor??resolved.textColor};const imageRule=advanced.imageRule;if(imageRule){const matches=compare(context.record,{field:imageRule.field,operator:imageRule.operator,value:imageRule.value});const selected=matches?imageRule.trueImageUri:imageRule.falseImageUri;if(selected)resolved={...resolved,imageUri:selected};else if(!resolved.imageUri&&imageRule.missingBehavior==="fallback")resolved={...resolved,imageUri:imageRule.fallbackImageUri};else if(!resolved.imageUri&&imageRule.missingBehavior==="hide")resolved={...resolved,hidden:true}}if(advanced.codeBinding){const value=String(rawValue(context.record,advanced.codeBinding.field)??advanced.codeBinding.fallback??"");const svgMarkup=advanced.codeBinding.kind==="qr"?await makeMergeQrSvg(value):makeCode128Svg(value);resolved={...resolved,type:"svg",svgMarkup,svgOriginalMarkup:svgMarkup,assetKind:advanced.codeBinding.kind==="qr"?"qr":"barcode",imageUri:undefined}}return resolved}
export async function buildAllRecordPreview(project:PublisherProject,data:MailMergeProjectData):Promise<PublisherProject>{const source=data.sources.find(s=>s.id===data.activeSourceId)??data.sources[0];if(!source)return project;const records=getCompletionRecords(source,data);const pages:PublisherPage[]=[];for(let recordIndex=0;recordIndex<records.length;recordIndex++){const record=records[recordIndex];const context:MergePreviewContext={source,record,recordIndex,fieldProperties:data.fieldProperties};for(const original of project.pages){const elements=await Promise.all(original.elements.map(e=>resolveAdvancedElement(e,context)));pages.push({...original,id:`${original.id}-merge-${record.id}`,name:`${original.name} · ${recordIndex+1}`,elements:elements.map(e=>({...e,id:`${e.id}-merge-${record.id}`}))})}}return{...project,id:`${project.id}-merge-preview-${Date.now()}`,name:`${project.name} · All Records Preview`,pages,activePageId:pages[0]?.id??project.activePageId,updatedAt:Date.now()}}
export function exportMergeDataset(source:MailMergeDataSource,records:MergeRecord[],format:"csv"|"tsv"|"json"):string{if(format==="json")return JSON.stringify(records.map(r=>r.values),null,2);const delimiter=format==="tsv"?"\t":",";const keys=source.fields.map(f=>f.key);const quote=(value:MergeCell)=>{const text=String(value??"");return/[\n\r,"\t]/.test(text)?`"${text.replace(/"/g,'""')}"`:text};return[keys.join(delimiter),...records.map(r=>keys.map(k=>quote(r.values[k])).join(delimiter))].join("\n")}
export function createCompletionReport(source:MailMergeDataSource,records:MergeRecord[],startedAt:number,filesCreated:string[]=[],filesFailed:string[]=[]):MergeCompletionReport{const issues:MergeCompletionIssue[]=source.validationIssues.map(issue=>{const record=source.records.find(r=>r.id===issue.recordId);return{recordId:issue.recordId,sourceRow:record?.sourceRow??0,severity:issue.severity,code:"VALIDATION",message:issue.message,field:issue.field}});for(const record of records)for(const field of source.fields)if(field.nullable&&String(record.values[field.key]??"").trim()==="")issues.push({recordId:record.id,sourceRow:record.sourceRow,severity:"warning",code:"MISSING_FIELD",message:`${field.label} is empty`,field:field.key});const finishedAt=Date.now();return{id:`merge-report-${finishedAt}`,createdAt:finishedAt,sourceName:source.name,attempted:records.length,completed:Math.max(0,records.length-filesFailed.length),skipped:0,duplicatesExcluded:source.duplicateRecordIds.length,validationFailures:source.validationIssues.length,missingFields:issues.filter(i=>i.code==="MISSING_FIELD").length,missingImages:0,filesCreated,filesFailed,issues,startedAt,finishedAt,durationMs:finishedAt-startedAt}}
export function upsertContact(contacts:AddressBookContact[],contact:Partial<AddressBookContact>&{values:Record<string,MergeCell>}):AddressBookContact[]{const now=Date.now();const next:AddressBookContact={id:contact.id??`contact-${now}-${Math.random().toString(36).slice(2,7)}`,values:contact.values,groups:contact.groups??[],createdAt:contact.createdAt??now,updatedAt:now};const index=contacts.findIndex(c=>c.id===next.id);return index<0?[...contacts,next]:contacts.map(c=>c.id===next.id?next:c)}
export function deleteContact(contacts:AddressBookContact[],id:string):AddressBookContact[]{return contacts.filter(c=>c.id!==id)}
export function mergeDuplicateContacts(contacts:AddressBookContact[],identityFields=["email","phone"]):AddressBookContact[]{const map=new Map<string,AddressBookContact>();for(const contact of contacts){const key=identityFields.map(f=>String(contact.values[f]??"").trim().toLowerCase()).filter(Boolean).join("|")||contact.id;const existing=map.get(key);map.set(key,existing?{...existing,values:{...existing.values,...contact.values},groups:[...new Set([...existing.groups,...contact.groups])],updatedAt:Date.now()}:contact)}return[...map.values()]}
