export type MotionTrackKind = "video" | "audio" | "text" | "image" | "effect";
export type MotionClip = { id:string; name:string; kind:MotionTrackKind; start:number; duration:number; color:string; muted?:boolean; locked?:boolean };
export type MotionProject = { id:string; name:string; width:number; height:number; fps:number; duration:number; playhead:number; playing:boolean; clips:MotionClip[]; updatedAt:number };
const id=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
export const createMotionProject=(name="Untitled Motion Project"):MotionProject=>({id:id(),name,width:1920,height:1080,fps:30,duration:30,playhead:0,playing:false,updatedAt:Date.now(),clips:[{id:id(),name:"Opening scene",kind:"video",start:0,duration:8,color:"#f97316"},{id:id(),name:"Title",kind:"text",start:1,duration:5,color:"#8b5cf6"},{id:id(),name:"Music",kind:"audio",start:0,duration:20,color:"#06b6d4"}]});
export function addMotionClip(p:MotionProject,kind:MotionTrackKind,name?:string):MotionProject{const colors={video:"#f97316",audio:"#06b6d4",text:"#8b5cf6",image:"#22c55e",effect:"#ec4899"};return {...p,clips:[...p.clips,{id:id(),name:name??`${kind[0].toUpperCase()+kind.slice(1)} clip`,kind,start:Math.min(p.playhead,p.duration-1),duration:Math.min(5,p.duration),color:colors[kind]}],updatedAt:Date.now()}}
export function splitMotionClip(p:MotionProject,clipId:string,at:number):MotionProject{const clip=p.clips.find(c=>c.id===clipId);if(!clip||at<=clip.start||at>=clip.start+clip.duration)return p;const left={...clip,duration:at-clip.start};const right={...clip,id:id(),name:`${clip.name} (split)`,start:at,duration:clip.start+clip.duration-at};return {...p,clips:p.clips.flatMap(c=>c.id===clipId?[left,right]:[c]),updatedAt:Date.now()}}
export function removeMotionClip(p:MotionProject,clipId:string):MotionProject{return {...p,clips:p.clips.filter(c=>c.id!==clipId),updatedAt:Date.now()}}
export function setPlayhead(p:MotionProject,value:number):MotionProject{return {...p,playhead:Math.max(0,Math.min(p.duration,value)),updatedAt:Date.now()}}
export function formatTime(seconds:number,fps=30){const m=Math.floor(seconds/60);const s=Math.floor(seconds%60);const f=Math.floor((seconds%1)*fps);return `${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}:${String(f).padStart(2,"0")}`}
