export type Phase40Status="not-started"|"in-progress"|"blocked"|"validated"|"certified";
export type Phase40Module={id:string;title:string;description:string;capabilities:string[];externalRequirements:string[]};
export type ReleaseGate={id:string;moduleId:string;title:string;owner:string;status:Phase40Status;evidence?:string;updatedAt?:string};
export type Studio={id:string;name:string;integrated:boolean;qualityScore:number};
export type DistributionArtifact={id:string;name:string;channel:"web"|"windows"|"macos"|"ios"|"android"|"docs";status:"draft"|"building"|"signed"|"approved"|"published";version:string};
export const PHASE40_MODULES:Phase40Module[]=[
 {id:"40.0",title:"Application Performance",description:"Full application, memory, asset, rendering and delivery optimization.",capabilities:["Lazy loading","Code splitting","Asset optimization","Memory optimization","GPU acceleration","Faster rendering"],externalRequirements:["Performance baseline","Bundle-size budget","Memory profile","Rendering benchmark"]},
 {id:"40.1",title:"Integrated Studio Platform",description:"Unifies all major studios into one coherent workspace, navigation, project and export experience.",capabilities:["Publisher","Photo Studio","Video Studio","Animation Studio","Audio Studio","Presentation Studio","Web Studio","PDF Studio","3D & Mockup Studio","AI Workspace"],externalRequirements:["Studio UX review","Cross-studio project validation","Shared export validation"]},
 {id:"40.2",title:"Marketplace Completion",description:"Template, plugin and asset marketplace with creator operations, revenue sharing and licensing.",capabilities:["Template marketplace","Plugin marketplace","Asset marketplace","Creator dashboard","Revenue sharing","Ratings","Reviews","Downloads","Licensing"],externalRequirements:["Marketplace moderation approval","Creator payout validation","License policy approval"]},
 {id:"40.3",title:"Production Export Engine",description:"Final multi-format export, validation, font/asset packaging and production output governance.",capabilities:["Final export engine","Multi-format export","Export validation","Font packaging","Color validation","Output manifests"],externalRequirements:["Reference export suite","Print validation","Format compatibility report"]},
 {id:"40.4",title:"Batch & Cloud Production",description:"Batch rendering, publishing, AI processing and cloud-render orchestration.",capabilities:["Batch rendering","Batch publishing","Batch AI processing","Cloud rendering","Retry policies","Job evidence"],externalRequirements:["Production worker pool","Cloud render validation","Load-test report"]},
 {id:"40.5",title:"Documentation & Learning",description:"Complete user, admin, API, SDK, help, tutorial and sample-project experience.",capabilities:["User manual","Administrator guide","API docs","Developer SDK guide","Help Center","Interactive tutorials","Sample projects"],externalRequirements:["Editorial sign-off","Documentation hosting","Tutorial QA"]},
 {id:"40.6",title:"Accessibility & Localization",description:"WCAG, keyboard, screen-reader, contrast, localization and multilingual release controls.",capabilities:["WCAG compliance","Keyboard navigation","Screen reader support","High contrast","Localization","Multi-language"],externalRequirements:["Accessibility audit","Translation review","Locale QA"]},
 {id:"40.7",title:"Installer & Update Release",description:"Production installers, signing, auto-update, release notes and migration controls.",capabilities:["Production installer","Auto-update","Release notes","Version migration","Backup migration","Signed packages"],externalRequirements:["Signing certificates","Update feed","Migration rehearsal"]},
 {id:"40.8",title:"Regression & Compatibility",description:"Final regression, browser, operating-system, device and project-compatibility certification.",capabilities:["Regression testing","Browser compatibility","Desktop compatibility","Mobile compatibility","Legacy project migration"],externalRequirements:["Regression report","Compatibility matrix","Migration report"]},
 {id:"40.9",title:"Launch Readiness",description:"Operational launch checklist, support staffing, incident response, status and rollback readiness.",capabilities:["Launch checklist","Support readiness","Incident plan","Status page","Rollback plan","Go-live schedule"],externalRequirements:["Launch checklist approved","Support roster","Rollback drill"]},
 {id:"40.10",title:"Commercial Certification",description:"Legal, security, finance, accessibility, privacy and operational certification evidence.",capabilities:["Legal approval","Security approval","Finance approval","Privacy approval","Accessibility approval","Operations approval"],externalRequirements:["Legal sign-off","Security sign-off","Finance sign-off","Privacy sign-off"]},
 {id:"40.11",title:"Production Release Candidate",description:"Version freeze, signed artifacts, release candidate validation and final go/no-go review.",capabilities:["Version freeze","Release candidate","Signed artifacts","Go/no-go review","Rollback package"],externalRequirements:["All release artifacts approved","Release-candidate test pass","Go/no-go approval"]},
 {id:"40.12",title:"Yaposan Commercial Public Release",description:"Evidence-based public release gate for the integrated Yaposan platform.",capabilities:["Production launch","Public availability","Monitoring activation","Customer onboarding","Post-launch review"],externalRequirements:["All Phase 40 gates certified","All studios integrated","All artifacts published","Commercial release council approval"]}
];
export const DEFAULT_RELEASE_GATES:ReleaseGate[]=PHASE40_MODULES.flatMap(m=>m.externalRequirements.map((title,i)=>({id:`p40-${m.id}-${i+1}`,moduleId:m.id,title,owner:m.id==="40.12"?"Commercial Release Council":"Release Engineering",status:"not-started" as Phase40Status})));
export const DEFAULT_STUDIOS:Studio[]=["Publisher","Photo Studio","Video Studio","Animation Studio","Audio Studio","Presentation Studio","Web Studio","PDF Studio","3D & Mockup Studio","AI Workspace"].map((name,i)=>({id:`studio-${i+1}`,name,integrated:false,qualityScore:0}));
export const DEFAULT_DISTRIBUTION_ARTIFACTS:DistributionArtifact[]=[
 {id:"web",name:"Yaposan Web",channel:"web",status:"draft",version:"40.0.0"},{id:"windows",name:"Yaposan Windows",channel:"windows",status:"draft",version:"40.0.0"},{id:"macos",name:"Yaposan macOS",channel:"macos",status:"draft",version:"40.0.0"},{id:"ios",name:"Yaposan iOS",channel:"ios",status:"draft",version:"40.0.0"},{id:"android",name:"Yaposan Android",channel:"android",status:"draft",version:"40.0.0"},{id:"docs",name:"Yaposan Documentation",channel:"docs",status:"draft",version:"40.0.0"}
];
const SCORE:Record<Phase40Status,number>={"not-started":0,blocked:0,"in-progress":50,validated:85,certified:100};
export const updateReleaseGate=(g:ReleaseGate,status:Phase40Status,evidence?:string):ReleaseGate=>({...g,status,evidence:evidence??g.evidence,updatedAt:new Date().toISOString()});
export function phase40ReadinessScore(items:ReleaseGate[]){return items.length?Math.round(items.reduce((s,x)=>s+SCORE[x.status],0)/items.length):0}
export function phase40ModuleScore(id:string,items:ReleaseGate[]){return phase40ReadinessScore(items.filter(x=>x.moduleId===id))}
export function phase40Blockers(gates:ReleaseGate[],studios:Studio[],artifacts:DistributionArtifact[]){return [...gates.filter(x=>x.status!=="certified").map(x=>`${x.moduleId}: ${x.title}`),...studios.filter(x=>!x.integrated||x.qualityScore<90).map(x=>`Studio: ${x.name}`),...artifacts.filter(x=>x.status!=="published").map(x=>`Artifact: ${x.name}`)]}
export function certifyPhase40(gates:ReleaseGate[],studios:Studio[],artifacts:DistributionArtifact[]){const score=phase40ReadinessScore(gates);const blockers=phase40Blockers(gates,studios,artifacts);return{certified:score===100&&blockers.length===0,score,blockers}}
