import type { PublisherProject } from "../types/publisher";
import type { CollaborationReviewState } from "./collaborationReviewEngine";
import { buildReviewSummary, buildWorkflowSummary, WORKFLOW_STAGES } from "./collaborationReviewEngine";
import { getPhase203CompletionState, type Phase203ReleaseRecord } from "./phase203CompletionEngine";

export type Phase204Severity = "error" | "warning" | "info";
export type Phase204AuditIssue = { id: string; severity: Phase204Severity; category: string; message: string; targetId?: string; repairable: boolean };
export type Phase204AuditReport = { schema: "yaposan.phase20.audit"; version: 1; phase: "20.4"; generatedAt: number; score: number; certified: boolean; errors: number; warnings: number; infos: number; issues: Phase204AuditIssue[]; projectId: string; projectUpdatedAt: number; releaseCount: number; checksum: string };
export type Phase204Certification = { id: string; certificateNumber: string; createdAt: number; projectId: string; projectUpdatedAt: number; auditScore: number; auditChecksum: string; releaseChecksum?: string; statement: string };
export type Phase204State = { version: "20.4"; certifications: Phase204Certification[]; lastAudit?: Phase204AuditReport };

type Extended = CollaborationReviewState & { auditCertification?: Partial<Phase204State> };
const uid = (p:string) => `${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
export function phase204Hash(value:string){ let h=2166136261; for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);} return (h>>>0).toString(16).padStart(8,"0").toUpperCase(); }
export function getPhase204State(state: CollaborationReviewState): Phase204State { const s=(state as Extended).auditCertification; return { version:"20.4", certifications:s?.certifications??[], lastAudit:s?.lastAudit }; }
const issue=(severity:Phase204Severity,category:string,message:string,targetId?:string,repairable=false):Phase204AuditIssue=>({id:uid("audit"),severity,category,message,targetId,repairable});
function duplicates(values:string[]){const seen=new Set<string>();return [...new Set(values.filter(v=>seen.has(v)?true:(seen.add(v),false)))];}
function releasePayload(project:PublisherProject, r:Phase203ReleaseRecord){return JSON.stringify({projectId:project.id,updatedAt:r.projectUpdatedAt,pages:r.pageCount,comments:r.commentCount,tasks:r.taskCount,approvals:r.approvalCount,createdAt:r.createdAt});}
export function runPhase204Audit(project:PublisherProject,state:CollaborationReviewState):Phase204AuditReport{
 const issues:Phase204AuditIssue[]=[]; const pages=project.pages??[]; const pageIds=new Set(pages.map(p=>p.id)); const elements=pages.flatMap(p=>p.elements??[]); const elementIds=new Set(elements.map(e=>e.id)); const memberIds=new Set(state.members.map(m=>m.id));
 if(!project.id) issues.push(issue("error","Project","Project ID is missing.",undefined,false));
 if(!pages.length) issues.push(issue("error","Project","Project has no pages."));
 duplicates(pages.map(p=>p.id)).forEach(id=>issues.push(issue("error","Structure","Duplicate page ID.",id,false)));
 duplicates(elements.map(e=>e.id)).forEach(id=>issues.push(issue("error","Structure","Duplicate element ID.",id,false)));
 duplicates(state.members.map(m=>m.id)).forEach(id=>issues.push(issue("error","Review","Duplicate reviewer ID.",id,true)));
 duplicates(state.comments.map(c=>c.id)).forEach(id=>issues.push(issue("error","Review","Duplicate comment ID.",id,true)));
 duplicates(state.workflow.tasks.map(t=>t.id)).forEach(id=>issues.push(issue("error","Workflow","Duplicate task ID.",id,true)));
 state.comments.forEach(c=>{if(!pageIds.has(c.pageId))issues.push(issue("error","Review","Comment references a missing page.",c.id,true)); if(c.elementId&&!elementIds.has(c.elementId))issues.push(issue("warning","Review","Comment references a missing element.",c.id,true)); if(c.assigneeId&&!memberIds.has(c.assigneeId))issues.push(issue("warning","Review","Comment assignee is missing.",c.id,true));});
 state.workflow.tasks.forEach(t=>{if(t.assigneeId&&!memberIds.has(t.assigneeId))issues.push(issue("warning","Workflow","Task assignee is missing.",t.id,true)); if(!WORKFLOW_STAGES.some(s=>s.id===t.stageId))issues.push(issue("error","Workflow","Task has an invalid stage.",t.id,true)); if(t.status==="complete"&&!t.completedAt)issues.push(issue("warning","Workflow","Completed task has no completion timestamp.",t.id,true));});
 state.approvals.forEach(a=>{if(!memberIds.has(a.reviewerId))issues.push(issue("warning","Approval","Approval references a missing reviewer.",a.id,true));});
 const completion=getPhase203CompletionState(state); completion.releases.forEach(r=>{const expected=phase204Hash(releasePayload(project,r)); if(r.checksum!==expected)issues.push(issue("error","Release","Release checksum verification failed.",r.id,false)); if(r.pageCount<1)issues.push(issue("error","Release","Certified release has no pages.",r.id,false));});
 const review=buildReviewSummary(state), workflow=buildWorkflowSummary(state); if(review.openComments)issues.push(issue("warning","Readiness",`${review.openComments} review comment(s) remain open.`)); if(workflow.blockedTasks)issues.push(issue("error","Readiness",`${workflow.blockedTasks} workflow task(s) are blocked.`)); if(!workflow.releaseGatePassed)issues.push(issue("warning","Readiness",workflow.releaseBlockers.join("; ")));
 if(!issues.length)issues.push(issue("info","Certification","No structural, workflow, review, or release-integrity issues detected."));
 const errors=issues.filter(i=>i.severity==="error").length,warnings=issues.filter(i=>i.severity==="warning").length,infos=issues.filter(i=>i.severity==="info").length; const score=Math.max(0,100-errors*20-warnings*5); const checksum=phase204Hash(JSON.stringify({projectId:project.id,updatedAt:project.updatedAt,issues:issues.map(i=>[i.severity,i.category,i.message,i.targetId]),releases:completion.releases.map(r=>r.checksum)}));
 return {schema:"yaposan.phase20.audit",version:1,phase:"20.4",generatedAt:Date.now(),score,certified:errors===0&&warnings===0,errors,warnings,infos,issues,projectId:project.id,projectUpdatedAt:project.updatedAt,releaseCount:completion.releases.length,checksum};
}
export function repairPhase204Issues(project:PublisherProject,state:CollaborationReviewState):CollaborationReviewState{
 const pageIds=new Set(project.pages.map(p=>p.id)), elementIds=new Set(project.pages.flatMap(p=>p.elements.map(e=>e.id))), memberIds=new Set(state.members.map(m=>m.id)); const now=Date.now();
 const unique=<T extends {id:string}>(items:T[])=>{const seen=new Set<string>();return items.filter(x=>!seen.has(x.id)&&(seen.add(x.id),true));};
 return {...state,members:unique(state.members),comments:unique(state.comments).filter(c=>pageIds.has(c.pageId)).map(c=>({...c,elementId:c.elementId&&elementIds.has(c.elementId)?c.elementId:undefined,assigneeId:c.assigneeId&&memberIds.has(c.assigneeId)?c.assigneeId:undefined})),approvals:unique(state.approvals).filter(a=>memberIds.has(a.reviewerId)),workflow:{...state.workflow,tasks:unique(state.workflow.tasks).map(t=>({...t,stageId:WORKFLOW_STAGES.some(s=>s.id===t.stageId)?t.stageId:"draft",assigneeId:t.assigneeId&&memberIds.has(t.assigneeId)?t.assigneeId:undefined,completedAt:t.status==="complete"?(t.completedAt??now):undefined}))},activity:[{id:uid("activity"),actorId:"local-owner",action:"Repaired recoverable Phase 20.4 audit issues",createdAt:now},...state.activity]} as CollaborationReviewState;
}
export function storePhase204Audit(state:CollaborationReviewState,report:Phase204AuditReport):CollaborationReviewState{const current=getPhase204State(state);return {...state,auditCertification:{...current,lastAudit:report}} as CollaborationReviewState;}
export function certifyPhase204(project:PublisherProject,state:CollaborationReviewState):CollaborationReviewState{const report=runPhase204Audit(project,state);if(!report.certified)throw new Error(`Audit certification blocked: ${report.errors} error(s), ${report.warnings} warning(s).`);const current=getPhase204State(state),latest=getPhase203CompletionState(state).releases.find(r=>!r.archivedAt)??getPhase203CompletionState(state).releases[0];const createdAt=Date.now();const cert:Phase204Certification={id:uid("phase204-cert"),certificateNumber:`YP-20.4-${new Date(createdAt).toISOString().slice(0,10).replace(/-/g,"")}-${report.checksum}`,createdAt,projectId:project.id,projectUpdatedAt:project.updatedAt,auditScore:report.score,auditChecksum:report.checksum,releaseChecksum:latest?.checksum,statement:"Phase 20 collaboration, review, workflow, release, persistence, and integrity controls passed the final audit."};return {...state,lockedForReview:true,auditCertification:{version:"20.4",lastAudit:report,certifications:[cert,...current.certifications]},activity:[{id:uid("activity"),actorId:"local-owner",action:`Issued Phase 20.4 audit certificate ${cert.certificateNumber}`,targetId:cert.id,createdAt},...state.activity]} as CollaborationReviewState;}
export function exportPhase204Audit(project:PublisherProject,state:CollaborationReviewState){const report=runPhase204Audit(project,state);return JSON.stringify({...report,certifications:getPhase204State(state).certifications,review:buildReviewSummary(state),workflow:buildWorkflowSummary(state)},null,2);}
