export type Phase39Status = "not-started" | "in-progress" | "blocked" | "validated" | "production";
export type Phase39Module = { id:string; title:string; description:string; capabilities:string[]; externalRequirements:string[] };
export type EnterpriseControl = { id:string; moduleId:string; title:string; owner:string; status:Phase39Status; evidence?:string; updatedAt?:string };
export type CloudService = { id:string; name:string; category:"identity"|"storage"|"collaboration"|"infrastructure"|"api"|"billing"|"quality"; environment:"development"|"staging"|"production"; configured:boolean; healthy:boolean; lastCheckedAt?:string };
export type SecurityPolicy = { id:string; name:string; enforced:boolean; severity:"standard"|"high"|"critical" };

export const PHASE39_MODULES: Phase39Module[] = [
 {id:"39.0",title:"Identity & Security",description:"Enterprise identity, MFA, SSO, OAuth/OIDC, RBAC, session, device, audit, network and secrets governance.",capabilities:["MFA","Google/Microsoft/Apple SSO","Enterprise SSO","OAuth2/OIDC","RBAC","API keys","Device management","Audit logs","IP restrictions","CSP"],externalRequirements:["Identity provider production tenant","MFA enrollment policy","Enterprise SSO metadata","Secrets vault","Security review"]},
 {id:"39.1",title:"Cloud Project Platform",description:"Cloud projects, synchronization, offline mode, conflict handling, versioning and restore workflows.",capabilities:["Cloud project storage","Automatic sync","Offline mode","Conflict resolution","Version history","Restore versions","Regional storage"],externalRequirements:["Production object storage","Primary database","Synchronization gateway","Regional data policy"]},
 {id:"39.2",title:"Shared Cloud Libraries",description:"Shared assets, templates, Brand Kits and AI prompt libraries with governed workspace access.",capabilities:["Shared libraries","Shared assets","Shared templates","Shared Brand Kits","Shared AI prompts","Workspace permissions"],externalRequirements:["Shared-library storage","Search indexing","Permission policy validation"]},
 {id:"39.3",title:"Backup & Disaster Recovery",description:"Scheduled backups, immutable recovery points, restore drills and regional disaster-recovery governance.",capabilities:["Scheduled backups","Cloud backups","Point-in-time restore","Disaster recovery","Regional replication","Restore drills"],externalRequirements:["Backup destination","Retention policy","Recovery environment","Successful restore drill"]},
 {id:"39.4",title:"Real-Time Collaboration",description:"Presence, live cursors, editing, comments, reviews, approvals, mentions, notifications and activity feeds.",capabilities:["Live cursors","Live editing","Presence","Comments","Review mode","Approvals","Mentions","Activity feed","Chat integration"],externalRequirements:["Realtime gateway","Presence service","Notification provider","Conflict-resolution validation"]},
 {id:"39.5",title:"Enterprise Administration",description:"Organization, workspace, user, seat, licensing, usage, billing and feature-control administration.",capabilities:["Organization dashboard","Workspace management","User invites","Seat licensing","Usage dashboard","Billing dashboard","Subscriptions","Feature flags","License verification"],externalRequirements:["Organization directory","Billing account","License signing keys","Admin approval workflow"]},
 {id:"39.6",title:"Production Infrastructure",description:"Workers, queues, notifications, observability, CDN, caching, environments, Docker and Kubernetes readiness.",capabilities:["Background workers","Render queue","AI queue","Export queue","Notification service","Health/error/crash monitoring","Metrics/logging","CDN","Cache optimization","Docker","Kubernetes"],externalRequirements:["Worker cluster","Queue broker","Observability destination","CDN account","Container registry"]},
 {id:"39.7",title:"API & Developer Platform",description:"Versioned REST, GraphQL, SDK, webhook, documentation and monitoring governance.",capabilities:["REST API","GraphQL API","Plugin SDK","Marketplace SDK","Webhooks","Public API docs","API versioning","API monitoring"],externalRequirements:["API gateway","Public documentation hosting","Webhook signing keys","API security review"]},
 {id:"39.8",title:"Commercial Billing Platform",description:"Stripe-ready subscriptions, tiering, usage limits, AI credits, invoices, coupons, trials and payment history.",capabilities:["Stripe integration","Free/Pro/Business/Enterprise","Usage limits","AI credits","Invoices","Coupons","Trials","Payment history"],externalRequirements:["Stripe production account","Billing webhooks","Tax configuration","Finance approval"]},
 {id:"39.9",title:"Enterprise Security Operations",description:"Security dashboard, policy enforcement, incident evidence, session response and threat-monitoring controls.",capabilities:["Security dashboard","Policy center","Session revocation","Device response","Threat events","Compliance evidence"],externalRequirements:["Security monitoring destination","Incident-response owner","Penetration test"]},
 {id:"39.10",title:"Cloud Operations Center",description:"Unified health, queue, storage, collaboration, API and billing operational control center.",capabilities:["Service inventory","Health checks","SLO dashboard","Queue depth","Capacity tracking","Operational runbooks"],externalRequirements:["Production service inventory","SLO approval","On-call schedule"]},
 {id:"39.11",title:"Enterprise Test Certification",description:"Unit, integration, E2E, performance, security, accessibility, browser and mobile test governance.",capabilities:["Unit tests","Integration tests","E2E tests","Performance tests","Security tests","Accessibility tests","Browser matrix","Mobile tests"],externalRequirements:["CI runners","Browser/device lab","Security test report","Accessibility report"]},
 {id:"39.12",title:"Enterprise Cloud Completion",description:"Evidence-based completion gate requiring all critical controls and production services to be validated.",capabilities:["Completion manifest","Executive sign-off","Production evidence","Rollback plan","Operations handoff"],externalRequirements:["All critical controls production","All required services healthy","Enterprise release council approval"]}
];

export const DEFAULT_ENTERPRISE_CONTROLS: EnterpriseControl[] = PHASE39_MODULES.flatMap(m=>m.externalRequirements.map((title,i)=>({id:`p39-${m.id}-${i+1}`,moduleId:m.id,title,owner:m.id==="39.12"?"Enterprise Release Council":"Platform Engineering",status:"not-started" as Phase39Status})));
export const DEFAULT_CLOUD_SERVICES: CloudService[] = [
 {id:"identity",name:"Identity provider",category:"identity",environment:"production",configured:false,healthy:false},
 {id:"database",name:"Cloud database",category:"storage",environment:"production",configured:false,healthy:false},
 {id:"object-storage",name:"Object storage",category:"storage",environment:"production",configured:false,healthy:false},
 {id:"realtime",name:"Realtime collaboration gateway",category:"collaboration",environment:"production",configured:false,healthy:false},
 {id:"workers",name:"Background worker cluster",category:"infrastructure",environment:"production",configured:false,healthy:false},
 {id:"api",name:"API gateway",category:"api",environment:"production",configured:false,healthy:false},
 {id:"billing",name:"Billing provider",category:"billing",environment:"production",configured:false,healthy:false},
 {id:"ci",name:"Quality automation",category:"quality",environment:"production",configured:false,healthy:false}
];
export const DEFAULT_SECURITY_POLICIES: SecurityPolicy[] = [
 {id:"mfa",name:"Require MFA",enforced:false,severity:"critical"},{id:"csp",name:"Enforce Content Security Policy",enforced:false,severity:"high"},{id:"ip",name:"IP restriction policy",enforced:false,severity:"high"},{id:"sessions",name:"Session expiration and revocation",enforced:false,severity:"critical"},{id:"secrets",name:"Central secrets management",enforced:false,severity:"critical"},{id:"rate",name:"API rate limiting",enforced:false,severity:"high"}
];
const SCORE:Record<Phase39Status,number>={"not-started":0,blocked:0,"in-progress":50,validated:85,production:100};
export const updateEnterpriseControl=(c:EnterpriseControl,status:Phase39Status,evidence?:string):EnterpriseControl=>({...c,status,evidence:evidence??c.evidence,updatedAt:new Date().toISOString()});
export function enterpriseReadinessScore(items:EnterpriseControl[]){return items.length?Math.round(items.reduce((s,x)=>s+SCORE[x.status],0)/items.length):0}
export function enterpriseModuleScore(id:string,items:EnterpriseControl[]){return enterpriseReadinessScore(items.filter(x=>x.moduleId===id))}
export function phase39Blockers(controls:EnterpriseControl[],services:CloudService[],policies:SecurityPolicy[]){return [...controls.filter(x=>x.status!=="production").map(x=>`${x.moduleId}: ${x.title}`),...services.filter(x=>!x.configured||!x.healthy).map(x=>`Service: ${x.name}`),...policies.filter(x=>x.severity==="critical"&&!x.enforced).map(x=>`Policy: ${x.name}`)]}
export function certifyPhase39(controls:EnterpriseControl[],services:CloudService[],policies:SecurityPolicy[]){const score=enterpriseReadinessScore(controls);const blockers=phase39Blockers(controls,services,policies);return{certified:score===100&&blockers.length===0,score,blockers}}
