import type { PublisherElement, PublisherPage } from "../types/publisher";

export type Phase45ComponentKind = "hero"|"feature-card"|"cta"|"header"|"footer"|"statistics"|"testimonial"|"pricing"|"team"|"gallery"|"timeline"|"faq";
export type Phase45Theme = { primary:string; secondary:string; accent:string; surface:string; text:string; muted:string; fontHeading:string; fontBody:string };
export type Phase45ComponentDefinition = { id:string; name:string; kind:Phase45ComponentKind; description:string; defaultHeight:number; tags:string[] };
export type Phase45InsertOptions = { x?:number; y?:number; width?:number; height?:number; content?:Record<string,string>; theme?:Partial<Phase45Theme> };

export const PHASE45_DEFAULT_THEME: Phase45Theme = { primary:"#0f172a", secondary:"#1e293b", accent:"#f59e0b", surface:"#ffffff", text:"#0f172a", muted:"#64748b", fontHeading:"Aptos Display", fontBody:"Aptos" };

export const PHASE45_COMPONENTS: Phase45ComponentDefinition[] = [
  ["hero","Hero",320],["feature-card","Feature Card",180],["cta","CTA Banner",150],["header","Header",86],["footer","Footer",120],["statistics","Statistics Block",170],["testimonial","Testimonial",190],["pricing","Pricing Table",300],["team","Team Section",250],["gallery","Gallery",280],["timeline","Timeline",240],["faq","FAQ",260],
].map(([kind,name,defaultHeight],i)=>({id:`phase45-${kind}`,name:String(name),kind:kind as Phase45ComponentKind,description:`Reusable ${name} component with editable content and theme-aware styling.`,defaultHeight:Number(defaultHeight),tags:["phase 45","reusable","professional",String(kind)]}));

const el=(id:string,name:string,type:PublisherElement["type"],x:number,y:number,width:number,height:number,zIndex:number,extra:Partial<PublisherElement>={}):PublisherElement=>({id,name,type,x,y,width,height,rotation:0,zIndex,opacity:1,...extra});
const text=(id:string,value:string,x:number,y:number,w:number,h:number,size:number,color:string,weight:PublisherElement["fontWeight"]="700",align:PublisherElement["textAlign"]="left",font="Aptos"):PublisherElement=>el(id,id,"text",x,y,w,h,20,{text:value,fontSize:size,textColor:color,fontWeight:weight,textAlign:align,fontFamily:font,lineHeight:size*1.15});

export function buildPhase45Component(kind:Phase45ComponentKind, options:Phase45InsertOptions={}):PublisherElement[]{
  const x=options.x??48,y=options.y??48,w=options.width??720,h=options.height??PHASE45_COMPONENTS.find(c=>c.kind===kind)?.defaultHeight??200;
  const t={...PHASE45_DEFAULT_THEME,...options.theme}; const c=options.content??{}; const p=`p45-${kind}-${Date.now()}`;
  if(kind==="header") return [el(`${p}-bg`,"Header Background","rectangle",x,y,w,h,1,{fillColor:t.surface}),text(`${p}-brand`,c.brand??"YAPOSAN",x+24,y+22,220,42,24,t.primary,"900","left",t.fontHeading),text(`${p}-nav`,c.nav??"HOME   SERVICES   WORK   CONTACT",x+w-390,y+28,360,30,13,t.muted,"700","right",t.fontBody)];
  if(kind==="hero") return [el(`${p}-bg`,"Hero Background","rectangle",x,y,w,h,1,{fillColor:t.primary,borderRadius:24}),el(`${p}-accent`,"Hero Accent","circle",x+w-210,y-40,260,260,2,{fillColor:t.accent,opacity:.9}),text(`${p}-eyebrow`,c.eyebrow??"BUILT FOR MODERN TEAMS",x+48,y+48,w*.58,26,13,t.accent,"900","left",t.fontBody),text(`${p}-title`,c.title??"Create work people remember.",x+48,y+86,w*.58,112,44,"#ffffff","900","left",t.fontHeading),text(`${p}-body`,c.body??"A flexible, reusable hero component with professional spacing, hierarchy, and brand-ready styling.",x+48,y+210,w*.52,70,16,"#cbd5e1","500","left",t.fontBody),el(`${p}-button`,"Hero Button","rectangle",x+48,y+h-62,170,42,8,{fillColor:t.accent,borderRadius:21}),text(`${p}-button-text`,c.cta??"GET STARTED",x+48,y+h-51,170,24,13,t.primary,"900","center",t.fontBody)];
  if(kind==="feature-card") return [el(`${p}-card`,"Feature Card","rectangle",x,y,w,h,1,{fillColor:t.surface,borderColor:"#e2e8f0",borderWidth:1,borderRadius:20}),el(`${p}-icon`,"Feature Icon","circle",x+28,y+28,52,52,2,{fillColor:t.accent}),text(`${p}-title`,c.title??"Professional feature",x+28,y+98,w-56,34,24,t.text,"900","left",t.fontHeading),text(`${p}-body`,c.body??"Use this reusable card across flyers, brochures, presentations, and web layouts.",x+28,y+138,w-56,h-150,15,t.muted,"500","left",t.fontBody)];
  if(kind==="cta") return [el(`${p}-bg`,"CTA Background","rectangle",x,y,w,h,1,{fillColor:t.accent,borderRadius:22}),text(`${p}-title`,c.title??"Ready to build something better?",x+34,y+30,w-250,44,27,t.primary,"900","left",t.fontHeading),text(`${p}-body`,c.body??"Start with a professional reusable component.",x+34,y+78,w-250,34,14,t.secondary,"600","left",t.fontBody),el(`${p}-button`,"CTA Button","rectangle",x+w-190,y+43,156,54,5,{fillColor:t.primary,borderRadius:27}),text(`${p}-button-text`,c.cta??"START NOW",x+w-190,y+59,156,24,13,"#ffffff","900","center",t.fontBody)];
  if(kind==="footer") return [el(`${p}-bg`,"Footer Background","rectangle",x,y,w,h,1,{fillColor:t.primary}),text(`${p}-brand`,c.brand??"YAPOSAN",x+30,y+28,220,34,22,"#ffffff","900","left",t.fontHeading),text(`${p}-copy`,c.copy??"Design. Publish. Grow.",x+30,y+68,260,28,13,"#94a3b8","600","left",t.fontBody),text(`${p}-links`,c.links??"Privacy   Terms   Contact",x+w-300,y+46,270,30,13,"#cbd5e1","700","right",t.fontBody)];
  if(kind==="statistics") return [el(`${p}-bg`,"Statistics Background","rectangle",x,y,w,h,1,{fillColor:"#f8fafc",borderRadius:20}),...([c.stat1??"120+",c.stat2??"98%",c.stat3??"24/7"].flatMap((v,i)=>[text(`${p}-v${i}`,v,x+30+i*w/3,y+36,w/3-60,48,34,t.primary,"900","center",t.fontHeading),text(`${p}-l${i}`,["PROJECTS","SATISFACTION","SUPPORT"][i],x+30+i*w/3,y+94,w/3-60,25,12,t.muted,"800","center",t.fontBody)]))];
  if(kind==="testimonial") return [el(`${p}-card`,"Testimonial Card","rectangle",x,y,w,h,1,{fillColor:t.surface,borderColor:"#e2e8f0",borderWidth:1,borderRadius:20}),text(`${p}-quote`,c.quote??"“This component system changed how quickly our team creates consistent, professional pages.”",x+42,y+34,w-84,88,24,t.text,"700","left",t.fontHeading),text(`${p}-name`,c.name??"ALEX MORGAN · CREATIVE DIRECTOR",x+42,y+h-48,w-84,26,12,t.accent,"900","left",t.fontBody)];
  if(kind==="pricing") return [el(`${p}-bg`,"Pricing Background","rectangle",x,y,w,h,1,{fillColor:"#f8fafc",borderRadius:20}),...(["STARTER","PRO","ENTERPRISE"].flatMap((name,i)=>{const cw=(w-64)/3,cx=x+16+i*(cw+16);return [el(`${p}-c${i}`,`${name} Plan`,"rectangle",cx,y+18,cw,h-36,2,{fillColor:i===1?t.primary:t.surface,borderColor:"#e2e8f0",borderWidth:1,borderRadius:18}),text(`${p}-n${i}`,name,cx+20,y+42,cw-40,26,13,i===1?t.accent:t.muted,"900","center",t.fontBody),text(`${p}-p${i}`,["$0","$19","Custom"][i],cx+20,y+84,cw-40,48,32,i===1?"#fff":t.text,"900","center",t.fontHeading),text(`${p}-f${i}`,"Core tools\nBrand styles\nProfessional export",cx+24,y+150,cw-48,100,14,i===1?"#cbd5e1":t.muted,"600","center",t.fontBody)]}))];
  if(kind==="team"||kind==="gallery") return [el(`${p}-bg`,"Section Background","rectangle",x,y,w,h,1,{fillColor:"#f8fafc",borderRadius:20}),text(`${p}-title`,c.title??(kind==="team"?"Meet the team":"Selected work"),x+28,y+24,w-56,42,30,t.text,"900","left",t.fontHeading),...Array.from({length:4},(_,i)=>el(`${p}-item${i}`,kind==="team"?`Team Member ${i+1}`:`Gallery Image ${i+1}`,"rectangle",x+28+i*((w-84)/4),y+88,(w-112)/4,h-116,2,{fillColor:["#cbd5e1","#94a3b8","#64748b","#334155"][i],borderRadius:14}))];
  if(kind==="timeline") return [text(`${p}-title`,c.title??"Our process",x,y,w,42,30,t.text,"900","left",t.fontHeading),el(`${p}-line`,"Timeline Line","rectangle",x+44,y+90,w-88,4,1,{fillColor:"#cbd5e1"}),...Array.from({length:4},(_,i)=>[el(`${p}-dot${i}`,`Timeline Dot ${i+1}`,"circle",x+36+i*(w-88)/3,y+80,24,24,2,{fillColor:t.accent}),text(`${p}-step${i}`,`0${i+1}\n${["DISCOVER","DESIGN","BUILD","LAUNCH"][i]}`,x+10+i*(w-40)/4,y+122,(w-40)/4,58,13,t.text,"900","center",t.fontBody)]).flat()];
  return [el(`${p}-bg`,"FAQ Background","rectangle",x,y,w,h,1,{fillColor:t.surface,borderColor:"#e2e8f0",borderWidth:1,borderRadius:20}),text(`${p}-title`,c.title??"Frequently asked questions",x+30,y+24,w-60,42,28,t.text,"900","left",t.fontHeading),...Array.from({length:4},(_,i)=>[text(`${p}-q${i}`,c[`q${i+1}`]??["Can I edit every element?","Can I change the colors?","Can I reuse this component?","Does it work in exports?"][i],x+30,y+82+i*42,w-90,28,15,t.text,"700","left",t.fontBody),text(`${p}-plus${i}`,"+",x+w-56,y+80+i*42,26,28,20,t.accent,"900","center",t.fontBody)]).flat()];
}

export function insertPhase45Component(page:PublisherPage,kind:Phase45ComponentKind,options:Phase45InsertOptions={}):PublisherPage{return {...page,elements:[...page.elements,...buildPhase45Component(kind,options)]};}
export function createPhase45ShowcasePage():PublisherPage{let page:PublisherPage={id:"phase45-showcase",name:"Phase 45 Component Showcase",width:816,height:2200,orientation:"portrait",sizeKey:"custom",backgroundColor:"#ffffff",margin:48,bleed:0,elements:[]}; let y=36; for(const kind of ["header","hero","feature-card","statistics","testimonial","pricing","timeline","faq","cta","footer"] as Phase45ComponentKind[]){page=insertPhase45Component(page,kind,{x:48,y,width:720}); y+= (PHASE45_COMPONENTS.find(c=>c.kind===kind)?.defaultHeight??180)+28;} return page;}
