import JSZip from 'jszip';
import type { PublisherProject } from '../types/publisher';
import { buildProductionOutputPlan, type ProductionArtifact, type ProductionOutputPlan } from './productionOutputEngine';
import { pageToSvg } from './pageSvgExport';

const HISTORY_KEY = 'yaposan:phase13.5:press-package-history';
export type PressPackageStatus = 'completed' | 'blocked' | 'failed';
export type PressPackageHistoryItem = { id:string; projectId:string; projectName:string; createdAt:number; status:PressPackageStatus; fileName:string; uri:string; bytes:number; jobId:string; sha256:string; artifactCount:number; error?:string };
export type PressPackageProgress = (progress:number, step:string)=>void;
export type PressPackageResult = { plan:ProductionOutputPlan; fileName:string; uri:string; bytes:number; sha256:string; history:PressPackageHistoryItem };

const safe=(v:string)=>v.trim().replace(/[^a-z0-9._-]+/gi,'-').replace(/^-+|-+$/g,'')||'publication';
const rot=(rotation:number)=>rotation?` rotate(${rotation})`:'';

export function sha256Bytes(bytes:Uint8Array):string {
  const K=new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]);
  const l=bytes.length, bitHi=Math.floor(l/0x20000000), bitLo=(l<<3)>>>0, total=((l+9+63)>>6)<<6, data=new Uint8Array(total); data.set(bytes); data[l]=0x80;
  const dv=new DataView(data.buffer); dv.setUint32(total-8,bitHi); dv.setUint32(total-4,bitLo);
  let h0=0x6a09e667,h1=0xbb67ae85,h2=0x3c6ef372,h3=0xa54ff53a,h4=0x510e527f,h5=0x9b05688c,h6=0x1f83d9ab,h7=0x5be0cd19; const w=new Uint32Array(64); const rr=(x:number,n:number)=>(x>>>n)|(x<<(32-n));
  for(let o=0;o<total;o+=64){for(let i=0;i<16;i++)w[i]=dv.getUint32(o+i*4);for(let i=16;i<64;i++){const a=w[i-15],b=w[i-2],s0=rr(a,7)^rr(a,18)^(a>>>3),s1=rr(b,17)^rr(b,19)^(b>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0;}let a=h0,b=h1,c=h2,d=h3,e=h4,f=h5,g=h6,h=h7;for(let i=0;i<64;i++){const S1=rr(e,6)^rr(e,11)^rr(e,25),ch=(e&f)^(~e&g),t1=(h+S1+ch+K[i]+w[i])>>>0,S0=rr(a,2)^rr(a,13)^rr(a,22),maj=(a&b)^(a&c)^(b&c),t2=(S0+maj)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0;}h0=(h0+a)>>>0;h1=(h1+b)>>>0;h2=(h2+c)>>>0;h3=(h3+d)>>>0;h4=(h4+e)>>>0;h5=(h5+f)>>>0;h6=(h6+g)>>>0;h7=(h7+h)>>>0;}
  return [h0,h1,h2,h3,h4,h5,h6,h7].map(v=>v.toString(16).padStart(8,'0')).join('');
}
export const sha256Text=(text:string)=>sha256Bytes(new TextEncoder().encode(text));

function finishingArtifactsFromObjects(project:PublisherProject):ProductionArtifact[]{
 const keys:[string,string][]=[['die-cut','die|cut|dieline|cutcontour'],['foil','foil'],['varnish','varnish|spot.?uv|uv'],['emboss','emboss|deboss'],['score','score|fold'],['perforate','perforat']]; const out:ProductionArtifact[]=[];
 for(const [op,pattern] of keys){const rx=new RegExp(pattern,'i'); project.pages.forEach((p,i)=>{const elements=p.elements.filter(e=>rx.test(e.name||''));if(!elements.length)return;const svg=pageToSvg({...p,elements},{hyperlinks:false,preserveText:true,preserveGradients:false});out.push({path:`Finishing/${op}-page-${i+1}.svg`,mimeType:'image/svg+xml',kind:'finishing',content:svg.replace('<svg ',`<svg data-finishing-plate="${op}" data-overprint="true" `)});});}return out;
}
function imposedSheetSvg(project:PublisherProject, plan:ProductionOutputPlan, sheetIndex:number){const s=plan.sheets[sheetIndex];let body='';for(const slot of s.slots){if(slot.pageNumber==null)continue;const p=project.pages[slot.pageNumber-1];if(!p)continue;const svg=pageToSvg(p,{hyperlinks:false,preserveText:true,preserveGradients:true}).replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'');const scale=Math.min(slot.width/p.width,slot.height/p.height);body+=`<g transform="translate(${slot.x} ${slot.y})${rot(slot.rotation)} scale(${scale})">${svg}</g>`;}return `<svg xmlns="http://www.w3.org/2000/svg" width="${s.width}" height="${s.height}" viewBox="0 0 ${s.width} ${s.height}" data-sheet="${s.sheet}" data-side="${s.side}">${body}</svg>`;}

async function pdfFromSvgs(svgs:string[], title:string):Promise<Uint8Array>{
 const PDFDocument=(await import('pdfkit')).default as any, SVGtoPDF=(await import('svg-to-pdfkit')).default as any; const chunks:Uint8Array[]=[];
 const doc=new PDFDocument({autoFirstPage:false,compress:true,info:{Title:title,Creator:'Yaposan Publisher',Producer:'Yaposan Press Package'}});doc.on('data',(c:Uint8Array)=>chunks.push(new Uint8Array(c)));const done=new Promise<Uint8Array>((res,rej)=>{doc.on('end',()=>{const n=chunks.reduce((a,c)=>a+c.length,0),all=new Uint8Array(n);let o=0;for(const c of chunks){all.set(c,o);o+=c.length;}res(all)});doc.on('error',rej)});
 for(const svg of svgs){const m=svg.match(/viewBox="[^"]*\s([\d.]+)\s([\d.]+)"/)||svg.match(/width="([\d.]+)" height="([\d.]+)"/);const w=Number(m?.[1]||612),h=Number(m?.[2]||792);doc.addPage({size:[w,h],margin:0});SVGtoPDF(doc,svg,0,0,{width:w,height:h,preserveAspectRatio:'xMidYMid meet'});}doc.end();return done;
}

function collectAssets(project:PublisherProject){const assets:{path:string;content:string}[]=[];for(const [name,data] of Object.entries(project.embeddedFonts||{}))assets.push({path:`Assets/Fonts/${safe(name)}.base64.txt`,content:data});project.pages.forEach((p,pi)=>p.elements.forEach((e,ei)=>{if(e.type==='image'&&e.imageUri)assets.push({path:`Assets/Images/page-${pi+1}-${ei+1}-${safe(e.name||'image')}.uri.txt`,content:e.imageUri!});if(e.type==='svg'&&e.svgMarkup)assets.push({path:`Assets/SVG/page-${pi+1}-${ei+1}-${safe(e.name||'vector')}.svg`,content:e.svgMarkup!});}));return assets;}

export async function buildPressPackageZip(project:PublisherProject,onProgress:PressPackageProgress=()=>{},isCancelled=()=>false):Promise<{bytes:Uint8Array;plan:ProductionOutputPlan;sha256:string;fileChecksums:Record<string,string>}>{
 onProgress(5,'Running production preflight');const plan=buildProductionOutputPlan(project);if(plan.blocked)throw new Error('Press package is blocked by preflight or PDF/X readiness errors.');if(isCancelled())throw new Error('Press package cancelled.');
 const zip=new JSZip(), files:Record<string,Uint8Array|string>={}; const add=(path:string,data:Uint8Array|string)=>{files[path]=data;zip.file(path,data)};
 onProgress(15,'Creating production artwork');const composite=plan.artifacts.filter(a=>a.kind==='composite');composite.forEach(a=>add(`Artwork/${a.path}`,a.content));
 const compositePdf=await pdfFromSvgs(composite.map(a=>a.content),`${project.name} Composite`);add(`PDF/${safe(project.name)}-Composite.pdf`,compositePdf);
 onProgress(35,'Creating separations and finishing plates');for(const group of ['Cyan','Magenta','Yellow','Black']){const arts=plan.artifacts.filter(a=>a.kind==='separation'&&a.path.toLowerCase().includes(group.toLowerCase()));if(arts.length)add(`Separations/${group}.pdf`,await pdfFromSvgs(arts.map(a=>a.content),`${project.name} ${group} Plate`));}
 plan.artifacts.filter(a=>a.kind==='separation').forEach(a=>add(`Separations/SVG/${a.path.split('/').pop()}`,a.content));const realFinishing=finishingArtifactsFromObjects(project);(realFinishing.length?realFinishing:plan.artifacts.filter(a=>a.kind==='finishing')).forEach(a=>add(a.path.startsWith('Finishing/')?a.path:`Finishing/${a.path.split('/').pop()}`,a.content));
 onProgress(55,'Rendering imposed press sheets');const imposed=plan.sheets.map((_,i)=>imposedSheetSvg(project,plan,i));if(imposed.length){imposed.forEach((s,i)=>add(`Imposition/Sheet-${i+1}.svg`,s));add(`PDF/${safe(project.name)}-Imposed.pdf`,await pdfFromSvgs(imposed,`${project.name} Imposed Sheets`));}
 onProgress(70,'Collecting assets and reports');for(const a of collectAssets(project))add(a.path,a.content);for(const a of plan.artifacts.filter(a=>['job-ticket','preflight','manifest','imposition'].includes(a.kind)))add(`Reports/${a.path.split('/').pop()}`,a.content);add('Reports/PDFX-Certification-Readiness.json',JSON.stringify(plan.pdfx,null,2));
 const fileChecksums:Record<string,string>={};for(const [path,data] of Object.entries(files))fileChecksums[path]=typeof data==='string'?sha256Text(data):sha256Bytes(data);add('Reports/SHA256SUMS.json',JSON.stringify(fileChecksums,null,2));add('README-PRESS-PACKAGE.txt',`Yaposan Publisher \nProject: ${project.name}\nJob: ${plan.jobId}\nGenerated: ${new Date().toISOString()}\nArtifacts: ${Object.keys(files).length}\nPDF/X readiness: ${plan.pdfx.compliant?'READY':'NOT READY'}\n`);
 onProgress(88,'Compressing press package');const bytes=await zip.generateAsync({type:'uint8array',compression:'DEFLATE',compressionOptions:{level:6}},m=>onProgress(88+Math.round(m.percent*.1),'Compressing press package'));const sha256=sha256Bytes(bytes);onProgress(100,'Press package complete');return{bytes,plan,sha256,fileChecksums};
}

async function deliver(bytes:Uint8Array,name:string){const { Platform }=await import('react-native');if(Platform.OS==='web'&&typeof document!=='undefined'){const blob=new Blob([bytes as BlobPart],{type:'application/zip'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return name;}const [{ File:ExpoFile, Paths }, Sharing]=await Promise.all([import('expo-file-system'),import('expo-sharing')]);const f=new ExpoFile(Paths.cache,name);f.create({overwrite:true,intermediates:true});f.write(bytes);if(await Sharing.isAvailableAsync())await Sharing.shareAsync(f.uri,{mimeType:'application/zip'});return f.uri;}
export async function loadPressPackageHistory():Promise<PressPackageHistoryItem[]>{try{const {default:AsyncStorage}=await import('@react-native-async-storage/async-storage');return JSON.parse(await AsyncStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}}
export async function savePressPackageHistory(items:PressPackageHistoryItem[]){const {default:AsyncStorage}=await import('@react-native-async-storage/async-storage');await AsyncStorage.setItem(HISTORY_KEY,JSON.stringify(items.slice(0,50)))}
export async function generateAndDeliverPressPackage(project:PublisherProject,onProgress:PressPackageProgress=()=>{},isCancelled=()=>false):Promise<PressPackageResult>{const built=await buildPressPackageZip(project,onProgress,isCancelled),fileName=`${safe(project.name)}-Press-Package-${new Date().toISOString().slice(0,10)}.zip`,uri=await deliver(built.bytes,fileName);const history:PressPackageHistoryItem={id:`press-${Date.now()}`,projectId:project.id,projectName:project.name,createdAt:Date.now(),status:'completed',fileName,uri,bytes:built.bytes.length,jobId:built.plan.jobId,sha256:built.sha256,artifactCount:built.plan.artifacts.length};await savePressPackageHistory([history,...await loadPressPackageHistory()]);return{plan:built.plan,fileName,uri,bytes:built.bytes.length,sha256:built.sha256,history};}
