export type ExportFormat2="pdf"|"svg"|"png"|"jpg"|"webp"|"tiff"|"avif"|"html"|"package";
export type ExportIntent2="screen"|"print"|"press"|"archive"|"web";
export type PDFStandard2="PDF-1.7"|"PDF-A-2b"|"PDF-A-3b"|"PDF-X-1a"|"PDF-X-3"|"PDF-X-4";
export type ExportPageRange2={mode:"all"|"current"|"custom";currentPage?:number;pages?:number[]};
export type ExportPreset2={id:string;name:string;format:ExportFormat2;intent:ExportIntent2;dpi:number;quality:number;transparent:boolean;colorSpace:"rgb"|"cmyk"|"gray";embedFonts:boolean;outlineRestrictedFonts:boolean;includeBleed:boolean;includeMarks:boolean;optimize:boolean;pdfStandard?:PDFStandard2;responsive?:boolean};
export type ExportAsset2={id:string;name:string;kind:"image"|"font"|"profile"|"link"|"data";bytes:number;hash?:string;embedded:boolean;license?:"allowed"|"restricted"|"unknown";source?:string};
export type ExportPage2={id:string;number:number;width:number;height:number;bleed?:number;visible?:boolean;elements:number};
export type ExportDocument2={id:string;title:string;pages:ExportPage2[];assets?:ExportAsset2[];fonts?:Array<{family:string;embedded:boolean;restricted?:boolean}>;colorProfiles?:string[];links?:string[];metadata?:Record<string,string>;accessibility?:{tagged:boolean;language?:string;title?:string;readingOrderValid?:boolean};version?:string};
export type ExportIssue2={severity:"error"|"warning"|"info";code:string;message:string;pageId?:string;assetId?:string};
export type ExportArtifact2={name:string;format:ExportFormat2;mime:string;estimatedBytes:number;pages:number[];settings:ExportPreset2;checksumSeed:string};
export type ProductionManifest2={version:"64.0";documentId:string;createdAt:string;artifacts:Array<{name:string;format:ExportFormat2;estimatedBytes:number;checksumSeed:string}>;assets:Array<{id:string;name:string;kind:ExportAsset2["kind"];bytes:number;hash:string;embedded:boolean}>;profiles:string[];metadata:Record<string,string>;issues:ExportIssue2[]};
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,Number.isFinite(n)?n:min));
const stableHash=(value:string)=>{let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,"0");};
const mimeFor=(format:ExportFormat2)=>({pdf:"application/pdf",svg:"image/svg+xml",png:"image/png",jpg:"image/jpeg",webp:"image/webp",tiff:"image/tiff",avif:"image/avif",html:"text/html",package:"application/zip"}[format]);
export const DEFAULT_EXPORT_PRESETS2:ExportPreset2[]=[
{id:"web-png",name:"Web PNG",format:"png",intent:"web",dpi:144,quality:.92,transparent:true,colorSpace:"rgb",embedFonts:true,outlineRestrictedFonts:true,includeBleed:false,includeMarks:false,optimize:true,responsive:false},
{id:"press-pdfx4",name:"Press PDF/X-4",format:"pdf",intent:"press",dpi:300,quality:1,transparent:false,colorSpace:"cmyk",embedFonts:true,outlineRestrictedFonts:true,includeBleed:true,includeMarks:true,optimize:false,pdfStandard:"PDF-X-4"},
{id:"archive-pdfa",name:"Archive PDF/A-2b",format:"pdf",intent:"archive",dpi:300,quality:1,transparent:false,colorSpace:"rgb",embedFonts:true,outlineRestrictedFonts:true,includeBleed:false,includeMarks:false,optimize:true,pdfStandard:"PDF-A-2b"},
{id:"responsive-html",name:"Responsive HTML",format:"html",intent:"web",dpi:96,quality:.88,transparent:true,colorSpace:"rgb",embedFonts:false,outlineRestrictedFonts:false,includeBleed:false,includeMarks:false,optimize:true,responsive:true},
];
export function normalizeExportPreset2(input:Partial<ExportPreset2>&Pick<ExportPreset2,"id"|"name"|"format">):ExportPreset2{const format=input.format;const intent=input.intent??(format==="html"?"web":format==="pdf"?"print":"screen");return{id:input.id.trim()||"custom",name:input.name.trim()||"Custom Export",format,intent,dpi:Math.round(clamp(input.dpi??(intent==="press"?300:144),36,2400)),quality:clamp(input.quality??.9,0,1),transparent:format==="jpg"||format==="pdf"?false:input.transparent??true,colorSpace:input.colorSpace??(intent==="press"?"cmyk":"rgb"),embedFonts:input.embedFonts??true,outlineRestrictedFonts:input.outlineRestrictedFonts??true,includeBleed:input.includeBleed??intent==="press",includeMarks:input.includeMarks??intent==="press",optimize:input.optimize??intent!=="press",pdfStandard:format==="pdf"?(input.pdfStandard??(intent==="press"?"PDF-X-4":"PDF-1.7")):undefined,responsive:format==="html"?(input.responsive??true):undefined};}
export function resolvePageRange2(document:ExportDocument2,range:ExportPageRange2):number[]{const available=document.pages.filter(p=>p.visible!==false).map(p=>p.number).sort((a,b)=>a-b);if(range.mode==="all")return available;if(range.mode==="current")return available.includes(range.currentPage??-1)?[range.currentPage!]:[];return[...new Set(range.pages??[])].filter(n=>available.includes(n)).sort((a,b)=>a-b);}
export function deduplicateAssets2(assets:ExportAsset2[]=[]):ExportAsset2[]{const seen=new Map<string,ExportAsset2>();for(const asset of assets){const hash=asset.hash??stableHash(`${asset.kind}:${asset.name}:${asset.bytes}:${asset.source??""}`);const key=`${asset.kind}:${hash}`;const existing=seen.get(key);if(!existing||(!existing.embedded&&asset.embedded))seen.set(key,{...asset,hash});}return[...seen.values()];}
export function estimateExportBytes2(document:ExportDocument2,preset:ExportPreset2,pages:number[]):number{const selected=document.pages.filter(p=>pages.includes(p.number));const area=selected.reduce((sum,p)=>sum+p.width*p.height,0);const pixels=area*(preset.dpi/72)**2;const channels=preset.colorSpace==="gray"?1:preset.colorSpace==="cmyk"?4:3;const compression=preset.format==="jpg"||preset.format==="webp"||preset.format==="avif"?.08+(1-preset.quality)*.12:preset.format==="png"?.32:preset.format==="pdf"?.18:preset.format==="svg"||preset.format==="html"?.025:.5;const assetBytes=deduplicateAssets2(document.assets).reduce((sum,a)=>sum+(a.embedded?a.bytes:0),0);return Math.max(512,Math.round(pixels*channels*compression+assetBytes*(preset.optimize?.65:1)));}
export function validateExport2(document:ExportDocument2,presetInput:ExportPreset2,pages:number[]):ExportIssue2[]{const preset=normalizeExportPreset2(presetInput);const issues:ExportIssue2[]=[];if(!pages.length)issues.push({severity:"error",code:"NO_PAGES",message:"No exportable pages were selected."});for(const page of document.pages){if(pages.includes(page.number)&&(page.width<=0||page.height<=0))issues.push({severity:"error",code:"INVALID_PAGE_SIZE",message:`Page ${page.number} has an invalid size.`,pageId:page.id});if(preset.includeBleed&&pages.includes(page.number)&&(page.bleed??0)<=0)issues.push({severity:"warning",code:"MISSING_BLEED",message:`Page ${page.number} has no bleed.`,pageId:page.id});}for(const asset of document.assets??[]){if(asset.license==="restricted"&&asset.embedded)issues.push({severity:"error",code:"RESTRICTED_ASSET",message:`Restricted asset cannot be embedded: ${asset.name}`,assetId:asset.id});if(asset.license==="unknown")issues.push({severity:"warning",code:"UNKNOWN_LICENSE",message:`Asset license is unknown: ${asset.name}`,assetId:asset.id});if(!asset.embedded&&!asset.source)issues.push({severity:"warning",code:"MISSING_LINK",message:`Linked asset has no source: ${asset.name}`,assetId:asset.id});}for(const font of document.fonts??[]){if(preset.embedFonts&&!font.embedded&&!font.restricted)issues.push({severity:"warning",code:"FONT_NOT_EMBEDDED",message:`Font is not embedded: ${font.family}`});if(font.restricted&&!preset.outlineRestrictedFonts)issues.push({severity:"error",code:"RESTRICTED_FONT",message:`Restricted font must be outlined: ${font.family}`});}if(preset.intent==="press"&&preset.colorSpace!=="cmyk")issues.push({severity:"warning",code:"PRESS_COLOR_SPACE",message:"Press exports should normally use CMYK."});if(preset.pdfStandard?.startsWith("PDF-X")&&!(document.colorProfiles??[]).length)issues.push({severity:"error",code:"OUTPUT_INTENT",message:"PDF/X requires an output color profile."});if(preset.pdfStandard?.startsWith("PDF-A")&&!document.metadata?.title&&!document.title)issues.push({severity:"error",code:"ARCHIVE_METADATA",message:"PDF/A requires document title metadata."});if((preset.format==="pdf"||preset.format==="html")&&!document.accessibility?.tagged)issues.push({severity:"warning",code:"UNTAGGED_CONTENT",message:"The export is not accessibility-tagged."});if(document.accessibility?.tagged&&!document.accessibility.readingOrderValid)issues.push({severity:"warning",code:"READING_ORDER",message:"Tagged content has an invalid reading order."});return issues;}
export function buildExportArtifact2(document:ExportDocument2,presetInput:ExportPreset2,range:ExportPageRange2={mode:"all"}):ExportArtifact2{const preset=normalizeExportPreset2(presetInput);const pages=resolvePageRange2(document,range);const suffix=preset.format==="package"?"zip":preset.format;const safe=(document.title||document.id).trim().replace(/[^a-z0-9._-]+/gi,"-").replace(/^-+|-+$/g,"")||"export";const estimatedBytes=estimateExportBytes2(document,preset,pages);const checksumSeed=stableHash(JSON.stringify({id:document.id,version:document.version??"1",pages,preset,estimatedBytes}));return{name:`${safe}.${suffix}`,format:preset.format,mime:mimeFor(preset.format),estimatedBytes,pages,settings:preset,checksumSeed};}
export function buildBatchExportPlan2(document:ExportDocument2,presets:ExportPreset2[],range:ExportPageRange2={mode:"all"}){const artifacts=presets.map(p=>buildExportArtifact2(document,p,range));const issues=presets.flatMap(p=>validateExport2(document,p,resolvePageRange2(document,range)).map(i=>({...i,code:`${p.id}:${i.code}`})));return{version:"64.0",documentId:document.id,artifacts,issues,estimatedBytes:artifacts.reduce((s,a)=>s+a.estimatedBytes,0),ready:!issues.some(i=>i.severity==="error")};}
export function buildProductionManifest2(document:ExportDocument2,artifacts:ExportArtifact2[],issues:ExportIssue2[]=[],createdAt=new Date().toISOString()):ProductionManifest2{return{version:"64.0",documentId:document.id,createdAt,artifacts:artifacts.map(a=>({name:a.name,format:a.format,estimatedBytes:a.estimatedBytes,checksumSeed:a.checksumSeed})),assets:deduplicateAssets2(document.assets).map(a=>({id:a.id,name:a.name,kind:a.kind,bytes:a.bytes,hash:a.hash!,embedded:a.embedded})),profiles:[...new Set(document.colorProfiles??[])],metadata:{title:document.title,...document.metadata},issues};}
export function buildExportPlan2(document:ExportDocument2,preset:ExportPreset2,range:ExportPageRange2={mode:"all"}){const artifact=buildExportArtifact2(document,preset,range);const issues=validateExport2(document,artifact.settings,artifact.pages);return{version:"64.0",documentId:document.id,artifact,issues,ready:!issues.some(i=>i.severity==="error"),pipeline:["preflight","resolve-pages","collect-assets","render","color-convert","encode","optimize","checksum"]};}
