import type { PublisherElement } from "../types/publisher";
import { applyPixelKernel, clonePixelBuffer, createPixelBuffer, paintBrushStroke, type BrushPoint, type BrushStrokeOptions, type PixelKernel, type RasterPixelBuffer, type SelectionMask } from "./professionalRasterPixelEngine";

export type RasterPreviewResult={buffer:RasterPixelBuffer;dataUrl?:string;warnings:string[]};
export type RasterJobProgress=(progress:number,label:string)=>void;

export async function decodeImageUriToPixelBuffer(uri:string):Promise<RasterPixelBuffer>{
  const g=globalThis as any; if(!g.document||!g.Image)throw new Error("Image decoding requires a browser Canvas environment or a registered native decoder.");
  const image:any=await new Promise((resolve,reject)=>{const img=new g.Image();img.crossOrigin="anonymous";img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("Unable to decode image URI."));img.src=uri;});
  const canvas=g.document.createElement("canvas");canvas.width=image.naturalWidth||image.width;canvas.height=image.naturalHeight||image.height;const ctx=canvas.getContext("2d",{willReadFrequently:true});if(!ctx)throw new Error("Canvas 2D context is unavailable.");ctx.drawImage(image,0,0);const source=ctx.getImageData(0,0,canvas.width,canvas.height);const buffer=createPixelBuffer(canvas.width,canvas.height,8,"srgb");(buffer.data as Uint8ClampedArray).set(source.data);return buffer;
}
export function encodePixelBufferToDataUrl(buffer:RasterPixelBuffer,mime="image/png",quality=.92):string{const g=globalThis as any;if(!g.document)throw new Error("Image encoding requires a browser Canvas environment or a registered native encoder.");const canvas=g.document.createElement("canvas");canvas.width=buffer.width;canvas.height=buffer.height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas 2D context is unavailable.");const bytes=new Uint8ClampedArray(buffer.data.length);const max=buffer.depth===16?65535:1;for(let i=0;i<bytes.length;i++)bytes[i]=buffer.depth===8?Number(buffer.data[i]):Math.round((Number(buffer.data[i])/max)*255);ctx.putImageData(new g.ImageData(bytes,buffer.width,buffer.height),0,0);return canvas.toDataURL(mime,quality);}

function adjustmentKernel(kind:string,settings:Record<string,number>):[PixelKernel,Record<string,number>]|null{switch(kind){case "brightness-contrast":return ["brightness-contrast",{brightness:settings.brightness??0,contrast:settings.contrast??0}];case "exposure":return ["exposure",{stops:settings.exposure??settings.amount??0}];case "hsl":case "vibrance":return ["saturation",{amount:settings.saturation??settings.amount??0}];case "blur":return ["gaussian-blur",{radius:settings.radius??settings.amount??2}];case "sharpen":return ["unsharp-mask",{radius:settings.radius??2,amount:settings.amount??1}];default:return null;}}
function filterKernel(kind:string):PixelKernel|null{const map:Record<string,PixelKernel>={"gaussian-blur":"gaussian-blur","unsharp-mask":"unsharp-mask",median:"median",mosaic:"mosaic",emboss:"emboss","edge-detect":"edge-detect",noise:"noise-reduction"};return map[kind]??null;}
export function renderRasterElementBuffer(element:PublisherElement,source:RasterPixelBuffer,onProgress?:RasterJobProgress):RasterPixelBuffer{let out=clonePixelBuffer(source);let step=0;const adjustments=(element.rasterAdjustments??[]).filter(x=>x.enabled);const filters=(element.rasterSmartFilters??[]).filter(x=>x.enabled);const total=Math.max(1,adjustments.length+filters.length+1);const progress=(label:string)=>onProgress?.(++step/total,label);const direct=element.imageAdjustments??{};out=applyPixelKernel(out,"brightness-contrast",{brightness:Number(direct.brightness??100)-100,contrast:Number(direct.contrast??100)-100});out=applyPixelKernel(out,"saturation",{amount:Number(direct.saturation??100)-100});if(Number(direct.exposure??0)!==0)out=applyPixelKernel(out,"exposure",{stops:Number(direct.exposure??0)/50});progress("Direct corrections");for(const layer of adjustments){const mapping=adjustmentKernel(layer.kind,(layer.settings??{}) as Record<string,number>);if(mapping)out=applyPixelKernel(out,mapping[0],mapping[1]);progress(layer.name);}for(const filter of filters){const kernel=filterKernel(filter.kind);if(kernel)out=applyPixelKernel(out,kernel,filter.settings??{});progress(filter.name);}return out;}
export async function renderRasterElementPreview(element:PublisherElement,onProgress?:RasterJobProgress):Promise<RasterPreviewResult>{if(!element.imageUri)throw new Error("Selected image has no image URI.");const source=await decodeImageUriToPixelBuffer(element.imageUri);const buffer=renderRasterElementBuffer(element,source,onProgress);let dataUrl:string|undefined;const warnings:string[]=[];try{dataUrl=encodePixelBufferToDataUrl(buffer);}catch(error){warnings.push(error instanceof Error?error.message:String(error));}return {buffer,dataUrl,warnings};}
export function applyInteractiveBrush(buffer:RasterPixelBuffer,points:BrushPoint[],options:BrushStrokeOptions,mask?:SelectionMask){return paintBrushStroke(buffer,points,options,mask);}
