export type PdfStandard = "PDF" | "PDF/A-1b" | "PDF/A-2b" | "PDF/A-3b" | "PDF/X-1a" | "PDF/X-3" | "PDF/X-4";
export type PdfAnnotationKind = "highlight" | "underline" | "strikeout" | "comment" | "freehand" | "rectangle" | "ellipse" | "stamp" | "redaction";
export type PdfFormFieldKind = "text" | "checkbox" | "radio" | "dropdown" | "date" | "signature";
export type PdfPageRecord = { id:string; sourceIndex:number; rotation:0|90|180|270; selected:boolean; label:string; width:number; height:number };
export type PdfAnnotation = { id:string; pageId:string; kind:PdfAnnotationKind; x:number; y:number; width:number; height:number; text?:string; color?:string };
export type PdfFormField = { id:string; pageId:string; kind:PdfFormFieldKind; name:string; x:number; y:number; width:number; height:number; required:boolean; value?:string };
export type PdfBookmark = { id:string; title:string; pageId:string; level:number };
export type PdfMetadata = { title:string; author:string; subject:string; keywords:string[]; language:string; creator:string; producer:string };
export type PdfSecurity = { ownerPassword?:string; userPassword?:string; allowPrinting:boolean; allowCopying:boolean; allowModification:boolean; allowAnnotations:boolean };
export type PdfStudioDocument = { id:string; name:string; bytes?:Uint8Array; pages:PdfPageRecord[]; annotations:PdfAnnotation[]; fields:PdfFormField[]; bookmarks:PdfBookmark[]; metadata:PdfMetadata; security:PdfSecurity; standard:PdfStandard; ocrText:Record<string,string>; optimized:boolean; updatedAt:number };

const uid = (prefix:string) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
export const createPdfStudioDocument = (name="Untitled PDF"):PdfStudioDocument => ({ id:uid("pdf"), name, pages:[], annotations:[], fields:[], bookmarks:[], metadata:{ title:name, author:"", subject:"", keywords:[], language:"en-US", creator:"Yaposan Publisher", producer:"Yaposan Professional PDF Studio" }, security:{ allowPrinting:true, allowCopying:true, allowModification:true, allowAnnotations:true }, standard:"PDF", ocrText:{}, optimized:false, updatedAt:Date.now() });

export async function importPdf(bytes:Uint8Array, name:string):Promise<PdfStudioDocument>{
  const { PDFDocument } = await import("pdf-lib");
  const pdf = await PDFDocument.load(bytes, { ignoreEncryption:false, updateMetadata:false });
  const pages = pdf.getPages().map((page:any,index:number) => { const size=page.getSize(); return { id:uid("page"), sourceIndex:index, rotation:((page.getRotation()?.angle||0)%360) as 0|90|180|270, selected:false, label:`Page ${index+1}`, width:size.width, height:size.height }; });
  const metadata:PdfMetadata = { title:pdf.getTitle?.()||name, author:pdf.getAuthor?.()||"", subject:pdf.getSubject?.()||"", keywords:pdf.getKeywords?.()?.split(/[,;]/).map((v:string)=>v.trim()).filter(Boolean)||[], language:"en-US", creator:pdf.getCreator?.()||"Yaposan Publisher", producer:pdf.getProducer?.()||"Yaposan Professional PDF Studio" };
  return { ...createPdfStudioDocument(name), bytes, pages, metadata };
}

export function rotatePage(doc:PdfStudioDocument,pageId:string,delta:90|-90):PdfStudioDocument { return { ...doc, pages:doc.pages.map(p=>p.id===pageId?{...p,rotation:(((p.rotation+delta+360)%360) as 0|90|180|270)}:p), updatedAt:Date.now() }; }
export function reorderPage(doc:PdfStudioDocument,pageId:string,toIndex:number):PdfStudioDocument { const pages=[...doc.pages]; const from=pages.findIndex(p=>p.id===pageId); if(from<0)return doc; const [page]=pages.splice(from,1); pages.splice(Math.max(0,Math.min(toIndex,pages.length)),0,page); return {...doc,pages,updatedAt:Date.now()}; }
export function deletePages(doc:PdfStudioDocument,ids:string[]):PdfStudioDocument { const set=new Set(ids); return {...doc,pages:doc.pages.filter(p=>!set.has(p.id)),annotations:doc.annotations.filter(a=>!set.has(a.pageId)),fields:doc.fields.filter(f=>!set.has(f.pageId)),bookmarks:doc.bookmarks.filter(b=>!set.has(b.pageId)),updatedAt:Date.now()}; }
export function addAnnotation(doc:PdfStudioDocument,input:Omit<PdfAnnotation,"id">):PdfStudioDocument { return {...doc,annotations:[...doc.annotations,{...input,id:uid("annotation")}],updatedAt:Date.now()}; }
export function addFormField(doc:PdfStudioDocument,input:Omit<PdfFormField,"id">):PdfStudioDocument { return {...doc,fields:[...doc.fields,{...input,id:uid("field")}],updatedAt:Date.now()}; }
export function addBookmark(doc:PdfStudioDocument,title:string,pageId:string,level=0):PdfStudioDocument { return {...doc,bookmarks:[...doc.bookmarks,{id:uid("bookmark"),title,pageId,level}],updatedAt:Date.now()}; }

export async function mergePdfBytes(files:Uint8Array[]):Promise<Uint8Array>{ const { PDFDocument }=await import("pdf-lib"); const out=await PDFDocument.create(); for(const bytes of files){const source=await PDFDocument.load(bytes); const copied=await out.copyPages(source,source.getPageIndices()); copied.forEach((p:any)=>out.addPage(p));} return out.save({useObjectStreams:true,addDefaultPage:false,objectsPerTick:50}); }
export async function splitPdfBytes(bytes:Uint8Array,groups:number[][]):Promise<Uint8Array[]>{ const {PDFDocument}=await import("pdf-lib"); const src=await PDFDocument.load(bytes); const result:Uint8Array[]=[]; for(const indexes of groups){const out=await PDFDocument.create(); const copied=await out.copyPages(src,indexes); copied.forEach((p:any)=>out.addPage(p)); result.push(await out.save({useObjectStreams:true,addDefaultPage:false}));} return result; }
export async function exportPdf(doc:PdfStudioDocument):Promise<Uint8Array>{ if(!doc.bytes) throw new Error("Import a PDF before exporting."); const {PDFDocument,degrees,rgb}=await import("pdf-lib"); const src=await PDFDocument.load(doc.bytes); const out=await PDFDocument.create(); const copied=await out.copyPages(src,doc.pages.map(p=>p.sourceIndex)); copied.forEach((p:any,i:number)=>{p.setRotation(degrees(doc.pages[i].rotation));out.addPage(p);}); out.setTitle(doc.metadata.title);out.setAuthor(doc.metadata.author);out.setSubject(doc.metadata.subject);out.setKeywords(doc.metadata.keywords);out.setCreator(doc.metadata.creator);out.setProducer(doc.metadata.producer); const form=out.getForm(); for(const field of doc.fields){const index=doc.pages.findIndex(p=>p.id===field.pageId); if(index<0)continue; const page=out.getPage(index); if(field.kind==="text"||field.kind==="date"){const f=form.createTextField(field.name);f.setText(field.value||"");f.addToPage(page,{x:field.x,y:field.y,width:field.width,height:field.height,borderWidth:1});} else if(field.kind==="checkbox"){form.createCheckBox(field.name).addToPage(page,{x:field.x,y:field.y,width:field.width,height:field.height});} else if(field.kind==="dropdown"){const f=form.createDropdown(field.name);f.addOptions(["Option 1","Option 2"]);f.addToPage(page,{x:field.x,y:field.y,width:field.width,height:field.height});}}
 for(const a of doc.annotations){const index=doc.pages.findIndex(p=>p.id===a.pageId);if(index<0)continue;const page=out.getPage(index);const color=rgb(1,0.85,0.15); if(a.kind==="highlight")page.drawRectangle({x:a.x,y:a.y,width:a.width,height:a.height,color,opacity:.35}); else if(a.kind==="underline")page.drawLine({start:{x:a.x,y:a.y},end:{x:a.x+a.width,y:a.y},thickness:2,color}); else page.drawRectangle({x:a.x,y:a.y,width:a.width,height:a.height,borderColor:color,borderWidth:1,opacity:.15}); }
 return out.save({useObjectStreams:doc.optimized,addDefaultPage:false,objectsPerTick:50}); }
export async function runOcr(image:Blob,language="eng",onProgress?:(value:number)=>void):Promise<string>{const mod=await import("tesseract.js"); const result=await mod.recognize(image,language,{logger:(m:any)=>{if(m.status==="recognizing text")onProgress?.(m.progress||0);}});return result.data.text;}
function toArrayBuffer(bytes: Uint8Array): ArrayBuffer {
  const copy = new Uint8Array(bytes.byteLength);
  copy.set(bytes);
  return copy.buffer;
}

export async function sha256Signature(bytes:Uint8Array,signer:string):Promise<{signer:string;algorithm:"SHA-256";digest:string;signedAt:string}>{const hash=await crypto.subtle.digest("SHA-256",toArrayBuffer(bytes));const digest=Array.from(new Uint8Array(hash)).map(v=>v.toString(16).padStart(2,"0")).join("");return {signer,algorithm:"SHA-256",digest,signedAt:new Date().toISOString()};}
export function validatePdf(doc:PdfStudioDocument){const issues:string[]=[];if(!doc.pages.length)issues.push("Document has no pages");if(!doc.metadata.title.trim())issues.push("Metadata title is missing");if(!doc.metadata.language.trim())issues.push("Document language is missing");if(doc.standard.startsWith("PDF/A")&&!doc.metadata.title)issues.push("PDF/A requires descriptive metadata");if(doc.standard.startsWith("PDF/X")&&doc.fields.length)issues.push("PDF/X output should flatten interactive form fields");if(Object.keys(doc.ocrText).length<doc.pages.length)issues.push("Some pages have no searchable OCR text");return {valid:issues.length===0,issues,score:Math.max(0,100-issues.length*12)};}
