import type { PublisherElement } from "../types/publisher";

export type PixelDepth = 8 | 16 | 32;
export type PixelArray = Uint8ClampedArray | Uint16Array | Float32Array;
export type RasterPixelBuffer = { width:number; height:number; depth:PixelDepth; data:PixelArray; colorSpace:"srgb"|"display-p3"|"adobe-rgb"|"prophoto-rgb"|"linear-srgb"; premultiplied:boolean };
export type PixelKernel = "brightness-contrast"|"exposure"|"saturation"|"gaussian-blur"|"unsharp-mask"|"median"|"mosaic"|"edge-detect"|"emboss"|"noise-reduction";
export type PixelKernelOptions = Record<string, number | boolean | string>;
export type SelectionMask = { width:number; height:number; data:Float32Array };
export type BrushPoint = { x:number; y:number; pressure?:number; tiltX?:number; tiltY?:number };
export type BrushStrokeOptions = { size:number; hardness:number; opacity:number; flow:number; spacing:number; color:[number,number,number,number]; erase?:boolean };
export type RasterNativeCapability = { backend:"webgpu"|"webgl2"|"skia"|"canvas2d"|"cpu"; available:boolean; highBitDepth:boolean; floatTextures:boolean; rawCodecs:string[]; icc:boolean; psd:boolean };

const clamp=(v:number,min=0,max=1)=>Math.max(min,Math.min(max,Number.isFinite(v)?v:min));
const maxFor=(depth:PixelDepth)=>depth===8?255:depth===16?65535:1;
const read=(b:RasterPixelBuffer,i:number)=>b.depth===32?Number(b.data[i]):Number(b.data[i])/maxFor(b.depth);
const write=(b:RasterPixelBuffer,i:number,v:number)=>{ const n=clamp(v); if(b.depth===32)(b.data as Float32Array)[i]=n; else (b.data as Uint8ClampedArray|Uint16Array)[i]=Math.round(n*maxFor(b.depth)); };
const idx=(b:RasterPixelBuffer,x:number,y:number)=>((y*b.width+x)*4);

export function createPixelBuffer(width:number,height:number,depth:PixelDepth=8,colorSpace:RasterPixelBuffer["colorSpace"]="srgb"):RasterPixelBuffer {
  const length=Math.max(1,Math.floor(width))*Math.max(1,Math.floor(height))*4;
  const data:PixelArray=depth===8?new Uint8ClampedArray(length):depth===16?new Uint16Array(length):new Float32Array(length);
  return {width:Math.max(1,Math.floor(width)),height:Math.max(1,Math.floor(height)),depth,data,colorSpace,premultiplied:false};
}
export function clonePixelBuffer(buffer:RasterPixelBuffer):RasterPixelBuffer { const out=createPixelBuffer(buffer.width,buffer.height,buffer.depth,buffer.colorSpace); out.data.set(buffer.data as any); out.premultiplied=buffer.premultiplied; return out; }
export function convertPixelDepth(buffer:RasterPixelBuffer,depth:PixelDepth):RasterPixelBuffer { const out=createPixelBuffer(buffer.width,buffer.height,depth,buffer.colorSpace); for(let i=0;i<buffer.data.length;i++)write(out,i,read(buffer,i)); return out; }

export function applyBrightnessContrast(buffer:RasterPixelBuffer,brightness=0,contrast=0):RasterPixelBuffer { const out=clonePixelBuffer(buffer); const c=clamp((contrast+100)/200,0,1)*2; for(let i=0;i<out.data.length;i+=4){for(let k=0;k<3;k++)write(out,i+k,(read(buffer,i+k)-.5)*c+.5+brightness/100);} return out; }
export function applyExposure(buffer:RasterPixelBuffer,stops=0):RasterPixelBuffer { const out=clonePixelBuffer(buffer),gain=Math.pow(2,stops); for(let i=0;i<out.data.length;i+=4)for(let k=0;k<3;k++)write(out,i+k,read(buffer,i+k)*gain); return out; }
export function applySaturation(buffer:RasterPixelBuffer,amount=0):RasterPixelBuffer { const out=clonePixelBuffer(buffer),s=1+amount/100; for(let i=0;i<out.data.length;i+=4){const r=read(buffer,i),g=read(buffer,i+1),b=read(buffer,i+2),l=.2126*r+.7152*g+.0722*b; write(out,i,l+(r-l)*s);write(out,i+1,l+(g-l)*s);write(out,i+2,l+(b-l)*s);} return out; }

function sample(buffer:RasterPixelBuffer,x:number,y:number,c:number){x=Math.max(0,Math.min(buffer.width-1,x));y=Math.max(0,Math.min(buffer.height-1,y));return read(buffer,idx(buffer,x,y)+c);}
export function applyBoxBlur(buffer:RasterPixelBuffer,radius=2):RasterPixelBuffer { const out=createPixelBuffer(buffer.width,buffer.height,buffer.depth,buffer.colorSpace); const r=Math.max(1,Math.min(32,Math.round(radius))); for(let y=0;y<buffer.height;y++)for(let x=0;x<buffer.width;x++){const o=idx(out,x,y);for(let c=0;c<4;c++){let sum=0,n=0;for(let yy=-r;yy<=r;yy++)for(let xx=-r;xx<=r;xx++){sum+=sample(buffer,x+xx,y+yy,c);n++;}write(out,o+c,sum/n);}} return out; }

export function applyGaussianBlur(buffer:RasterPixelBuffer,radius=2,sigma=Math.max(.5,radius/2)):RasterPixelBuffer {
  const r=Math.max(1,Math.min(32,Math.ceil(radius))); const kernel:number[]=[]; let total=0;
  for(let i=-r;i<=r;i++){const v=Math.exp(-(i*i)/(2*sigma*sigma));kernel.push(v);total+=v;} for(let i=0;i<kernel.length;i++)kernel[i]/=total;
  const temp=createPixelBuffer(buffer.width,buffer.height,buffer.depth,buffer.colorSpace),out=createPixelBuffer(buffer.width,buffer.height,buffer.depth,buffer.colorSpace);
  for(let y=0;y<buffer.height;y++)for(let x=0;x<buffer.width;x++){const o=idx(temp,x,y);for(let c=0;c<4;c++){let sum=0;for(let k=-r;k<=r;k++)sum+=sample(buffer,x+k,y,c)*kernel[k+r];write(temp,o+c,sum);}}
  for(let y=0;y<buffer.height;y++)for(let x=0;x<buffer.width;x++){const o=idx(out,x,y);for(let c=0;c<4;c++){let sum=0;for(let k=-r;k<=r;k++)sum+=sample(temp,x,y+k,c)*kernel[k+r];write(out,o+c,sum);}} return out;
}
export function applyMedian(buffer:RasterPixelBuffer,radius=1):RasterPixelBuffer { const out=clonePixelBuffer(buffer),r=Math.max(1,Math.min(5,Math.round(radius))); for(let y=0;y<buffer.height;y++)for(let x=0;x<buffer.width;x++){const o=idx(out,x,y);for(let c=0;c<3;c++){const values:number[]=[];for(let yy=-r;yy<=r;yy++)for(let xx=-r;xx<=r;xx++)values.push(sample(buffer,x+xx,y+yy,c));values.sort((a,b)=>a-b);write(out,o+c,values[Math.floor(values.length/2)]);}} return out; }
export function applyMosaic(buffer:RasterPixelBuffer,size=8):RasterPixelBuffer { const out=clonePixelBuffer(buffer),block=Math.max(2,Math.min(256,Math.round(size))); for(let y=0;y<buffer.height;y+=block)for(let x=0;x<buffer.width;x+=block){const sums=[0,0,0,0];let n=0;for(let yy=y;yy<Math.min(buffer.height,y+block);yy++)for(let xx=x;xx<Math.min(buffer.width,x+block);xx++){const i=idx(buffer,xx,yy);for(let c=0;c<4;c++)sums[c]+=read(buffer,i+c);n++;}for(let yy=y;yy<Math.min(buffer.height,y+block);yy++)for(let xx=x;xx<Math.min(buffer.width,x+block);xx++){const i=idx(out,xx,yy);for(let c=0;c<4;c++)write(out,i+c,sums[c]/n);}} return out; }
export function applyEmboss(buffer:RasterPixelBuffer,amount=1):RasterPixelBuffer { const out=clonePixelBuffer(buffer); for(let y=0;y<buffer.height;y++)for(let x=0;x<buffer.width;x++){const o=idx(out,x,y);for(let c=0;c<3;c++)write(out,o+c,.5+(sample(buffer,x+1,y+1,c)-sample(buffer,x-1,y-1,c))*amount);write(out,o+3,sample(buffer,x,y,3));} return out; }
export function applyNoiseReduction(buffer:RasterPixelBuffer,strength=.5,radius=1):RasterPixelBuffer { const smooth=applyMedian(buffer,radius),out=clonePixelBuffer(buffer),mix=clamp(strength); for(let i=0;i<out.data.length;i+=4)for(let c=0;c<3;c++)write(out,i+c,read(buffer,i+c)*(1-mix)+read(smooth,i+c)*mix); return out; }

export function applyUnsharpMask(buffer:RasterPixelBuffer,radius=2,amount=1):RasterPixelBuffer { const blur=applyBoxBlur(buffer,radius),out=clonePixelBuffer(buffer); for(let i=0;i<out.data.length;i+=4)for(let c=0;c<3;c++)write(out,i+c,read(buffer,i+c)+(read(buffer,i+c)-read(blur,i+c))*amount); return out; }
export function applyEdgeDetect(buffer:RasterPixelBuffer):RasterPixelBuffer { const out=createPixelBuffer(buffer.width,buffer.height,buffer.depth,buffer.colorSpace); const gx=[-1,0,1,-2,0,2,-1,0,1],gy=[-1,-2,-1,0,0,0,1,2,1]; for(let y=0;y<buffer.height;y++)for(let x=0;x<buffer.width;x++){let sx=0,sy=0,p=0;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){const l=.2126*sample(buffer,x+xx,y+yy,0)+.7152*sample(buffer,x+xx,y+yy,1)+.0722*sample(buffer,x+xx,y+yy,2);sx+=l*gx[p];sy+=l*gy[p++];}const m=clamp(Math.hypot(sx,sy));const o=idx(out,x,y);write(out,o,m);write(out,o+1,m);write(out,o+2,m);write(out,o+3,1);} return out; }
export function applyPixelKernel(buffer:RasterPixelBuffer,kernel:PixelKernel,options:PixelKernelOptions={}):RasterPixelBuffer { switch(kernel){case "brightness-contrast":return applyBrightnessContrast(buffer,Number(options.brightness??0),Number(options.contrast??0));case "exposure":return applyExposure(buffer,Number(options.stops??0));case "saturation":return applySaturation(buffer,Number(options.amount??0));case "gaussian-blur":return applyGaussianBlur(buffer,Number(options.radius??2),Number(options.sigma??Math.max(.5,Number(options.radius??2)/2)));case "unsharp-mask":return applyUnsharpMask(buffer,Number(options.radius??2),Number(options.amount??1));case "median":return applyMedian(buffer,Number(options.radius??1));case "mosaic":return applyMosaic(buffer,Number(options.size??8));case "emboss":return applyEmboss(buffer,Number(options.amount??1));case "noise-reduction":return applyNoiseReduction(buffer,Number(options.strength??.5),Number(options.radius??1));case "edge-detect":return applyEdgeDetect(buffer);default:return clonePixelBuffer(buffer);} }

export function createRectSelection(width:number,height:number,x:number,y:number,w:number,h:number,feather=0):SelectionMask { const data=new Float32Array(width*height); const f=Math.max(0,feather); for(let py=0;py<height;py++)for(let px=0;px<width;px++){const dx=Math.max(x-px,0,px-(x+w)),dy=Math.max(y-py,0,py-(y+h));data[py*width+px]=f?clamp(1-Math.hypot(dx,dy)/f):(px>=x&&px<=x+w&&py>=y&&py<=y+h?1:0);} return {width,height,data}; }
export function combineSelectionMasks(a:SelectionMask,b:SelectionMask,mode:"add"|"subtract"|"intersect"):SelectionMask { const data=new Float32Array(a.data.length); for(let i=0;i<data.length;i++)data[i]=mode==="add"?Math.max(a.data[i],b.data[i]):mode==="subtract"?clamp(a.data[i]-b.data[i]):Math.min(a.data[i],b.data[i]); return {width:a.width,height:a.height,data}; }

export function paintBrushStroke(buffer:RasterPixelBuffer,points:BrushPoint[],options:BrushStrokeOptions,mask?:SelectionMask):RasterPixelBuffer { const out=clonePixelBuffer(buffer),radius=Math.max(.5,options.size/2),step=Math.max(1,radius*Math.max(.02,options.spacing)); const dab=(cx:number,cy:number,p=1)=>{const minX=Math.max(0,Math.floor(cx-radius)),maxX=Math.min(out.width-1,Math.ceil(cx+radius)),minY=Math.max(0,Math.floor(cy-radius)),maxY=Math.min(out.height-1,Math.ceil(cy+radius));for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const d=Math.hypot(x-cx,y-cy)/radius;if(d>1)continue;const hard=clamp(options.hardness),fall=d<=hard?1:clamp((1-d)/(1-hard||1));const sel=mask?mask.data[y*out.width+x]:1;const a=fall*options.opacity*options.flow*p*sel;const i=idx(out,x,y);if(options.erase){write(out,i+3,read(out,i+3)*(1-a));}else{for(let c=0;c<3;c++)write(out,i+c,read(out,i+c)*(1-a)+options.color[c]*a);write(out,i+3,read(out,i+3)+(1-read(out,i+3))*options.color[3]*a);}}}; for(let n=0;n<points.length-1;n++){const a=points[n],b=points[n+1],dist=Math.hypot(b.x-a.x,b.y-a.y),count=Math.max(1,Math.ceil(dist/step));for(let t=0;t<=count;t++){const q=t/count;dab(a.x+(b.x-a.x)*q,a.y+(b.y-a.y)*q,(a.pressure??1)*(1-q)+(b.pressure??1)*q);}} if(points.length===1)dab(points[0].x,points[0].y,points[0].pressure??1); return out; }

export function cloneStamp(buffer:RasterPixelBuffer,source:{x:number;y:number},target:{x:number;y:number},radius:number,opacity=1):RasterPixelBuffer { const out=clonePixelBuffer(buffer),r=Math.max(1,Math.round(radius)); for(let y=-r;y<=r;y++)for(let x=-r;x<=r;x++){if(x*x+y*y>r*r)continue;const tx=Math.round(target.x+x),ty=Math.round(target.y+y),sx=Math.round(source.x+x),sy=Math.round(source.y+y);if(tx<0||ty<0||tx>=out.width||ty>=out.height)continue;const oi=idx(out,tx,ty);for(let c=0;c<4;c++)write(out,oi+c,read(out,oi+c)*(1-opacity)+sample(buffer,sx,sy,c)*opacity);} return out; }
export function healSpot(buffer:RasterPixelBuffer,target:{x:number;y:number},radius:number):RasterPixelBuffer { const blurred=applyBoxBlur(buffer,Math.max(1,radius/3)),out=clonePixelBuffer(buffer),r=Math.max(1,Math.round(radius)); for(let y=-r;y<=r;y++)for(let x=-r;x<=r;x++){const d=Math.hypot(x,y)/r;if(d>1)continue;const tx=Math.round(target.x+x),ty=Math.round(target.y+y);if(tx<0||ty<0||tx>=out.width||ty>=out.height)continue;const a=1-d,oi=idx(out,tx,ty);for(let c=0;c<3;c++)write(out,oi+c,read(out,oi+c)*(1-a)+read(blurred,oi+c)*a);} return out; }

export function mergeHDR(buffers:RasterPixelBuffer[],weights?:number[]):RasterPixelBuffer { if(!buffers.length)throw new Error("HDR merge requires at least one image."); const out=createPixelBuffer(buffers[0].width,buffers[0].height,32,"linear-srgb"); const ws=weights?.length===buffers.length?weights:buffers.map(()=>1); const total=ws.reduce((a,b)=>a+b,0)||1; for(let i=0;i<out.data.length;i++)write(out,i,buffers.reduce((s,b,n)=>s+read(b,i)*ws[n],0)/total); return out; }
export function focusStack(buffers:RasterPixelBuffer[]):RasterPixelBuffer { if(!buffers.length)throw new Error("Focus stack requires images."); const out=clonePixelBuffer(buffers[0]); for(let y=1;y<out.height-1;y++)for(let x=1;x<out.width-1;x++){let best=0,bestScore=-1;for(let n=0;n<buffers.length;n++){const b=buffers[n],c=sample(b,x,y,0),score=Math.abs(c-sample(b,x-1,y,0))+Math.abs(c-sample(b,x+1,y,0))+Math.abs(c-sample(b,x,y-1,0))+Math.abs(c-sample(b,x,y+1,0));if(score>bestScore){bestScore=score;best=n;}}const oi=idx(out,x,y);for(let c=0;c<4;c++)write(out,oi+c,read(buffers[best],oi+c));} return out; }

export function buildNativeCapabilityReport():RasterNativeCapability[]{ const g=globalThis as any; return [
  {backend:"webgpu",available:Boolean(g.navigator?.gpu),highBitDepth:Boolean(g.navigator?.gpu),floatTextures:Boolean(g.navigator?.gpu),rawCodecs:[],icc:false,psd:false},
  {backend:"webgl2",available:typeof g.WebGL2RenderingContext!=="undefined",highBitDepth:true,floatTextures:true,rawCodecs:[],icc:false,psd:false},
  {backend:"skia",available:Boolean(g.__YAPOSAN_SKIA__),highBitDepth:Boolean(g.__YAPOSAN_SKIA__),floatTextures:Boolean(g.__YAPOSAN_SKIA__),rawCodecs:g.__YAPOSAN_RAW_CODECS__??[],icc:Boolean(g.__YAPOSAN_ICC__),psd:Boolean(g.__YAPOSAN_PSD__)},
  {backend:"canvas2d",available:typeof g.OffscreenCanvas!=="undefined"||typeof g.document!=="undefined",highBitDepth:false,floatTextures:false,rawCodecs:[],icc:false,psd:false},
  {backend:"cpu",available:true,highBitDepth:true,floatTextures:true,rawCodecs:[],icc:false,psd:false},
]; }
export function certifyRasterPixelExecution(element:PublisherElement){ const caps=buildNativeCapabilityReport(),runtime=element.rasterRuntime; const issues:{severity:"error"|"warning"|"info";message:string}[]=[]; if(!caps.some(c=>c.available))issues.push({severity:"error",message:"No raster execution backend is available."}); if((element.rasterColorProfile?.bitDepth??8)>8&&!caps.some(c=>c.available&&c.highBitDepth))issues.push({severity:"error",message:"No high-bit-depth backend is available."}); if(element.rasterRawDevelopment?.enabled&&!caps.some(c=>c.rawCodecs.length))issues.push({severity:"warning",message:"RAW settings are configured, but no native camera codec is registered."}); if(runtime?.layeredExport?.format==="psd-compatible"&&!caps.some(c=>c.psd))issues.push({severity:"warning",message:"PSD export needs a registered native PSD codec; Yaposan layered export remains available."}); if(!issues.length)issues.push({severity:"info",message:"Raster pixel execution is certified for the active environment."}); return {capabilities:caps,issues}; }
