export type RGBColor2={r:number;g:number;b:number;a?:number};
export type CMYKColor2={c:number;m:number;y:number;k:number;a?:number};
export type LabColor2={l:number;a:number;b:number;alpha?:number};
export type ColorValue2={space:"rgb";value:RGBColor2}|{space:"cmyk";value:CMYKColor2}|{space:"lab";value:LabColor2}|{space:"spot";name:string;tint:number;alternate:CMYKColor2};
export type ICCProfile2={id:string;name:string;space:"rgb"|"cmyk"|"lab";version:string;intent:"perceptual"|"relative-colorimetric"|"absolute-colorimetric"|"saturation";blackPointCompensation:boolean;description?:string};
export type SpotColor2={name:string;alternate:CMYKColor2;tint:number;overprint:boolean;registration?:boolean};
export type ColorSwatch2={id:string;name:string;color:ColorValue2;global:boolean;group?:string;locked?:boolean};
export type ProofSettings2={sourceProfile:ICCProfile2;proofProfile:ICCProfile2;paperColor:boolean;blackInk:boolean;simulateOverprint:boolean;gamutWarning:boolean};
export type SeparationPlate2={name:string;kind:"process"|"spot"|"registration";coverage:number;overprintObjects:string[]};
const clamp=(n:number,min=0,max=1)=>Math.max(min,Math.min(max,Number.isFinite(n)?n:min));
const round=(n:number,p=4)=>Number(n.toFixed(p));
export const normalizeRGB2=(v:RGBColor2):RGBColor2=>({r:clamp(v.r,0,255),g:clamp(v.g,0,255),b:clamp(v.b,0,255),a:clamp(v.a??1)});
export const normalizeCMYK2=(v:CMYKColor2):CMYKColor2=>({c:clamp(v.c),m:clamp(v.m),y:clamp(v.y),k:clamp(v.k),a:clamp(v.a??1)});
export const normalizeLab2=(v:LabColor2):LabColor2=>({l:clamp(v.l,0,100),a:clamp(v.a,-128,127),b:clamp(v.b,-128,127),alpha:clamp(v.alpha??1)});
export function rgbToCmyk2(input:RGBColor2):CMYKColor2{const v=normalizeRGB2(input),r=v.r/255,g=v.g/255,b=v.b/255,k=1-Math.max(r,g,b);if(k>=.999999)return{c:0,m:0,y:0,k:1,a:v.a};return{c:round((1-r-k)/(1-k)),m:round((1-g-k)/(1-k)),y:round((1-b-k)/(1-k)),k:round(k),a:v.a};}
export function cmykToRgb2(input:CMYKColor2):RGBColor2{const v=normalizeCMYK2(input);return{r:Math.round(255*(1-v.c)*(1-v.k)),g:Math.round(255*(1-v.m)*(1-v.k)),b:Math.round(255*(1-v.y)*(1-v.k)),a:v.a};}
const pivotRgb=(n:number)=>n>.04045?Math.pow((n+.055)/1.055,2.4):n/12.92;
const pivotXyz=(n:number)=>n>.008856?Math.cbrt(n):(7.787*n)+(16/116);
export function rgbToLab2(input:RGBColor2):LabColor2{const v=normalizeRGB2(input);const r=pivotRgb(v.r/255),g=pivotRgb(v.g/255),b=pivotRgb(v.b/255);const x=(r*.4124+g*.3576+b*.1805)/.95047,y=(r*.2126+g*.7152+b*.0722),z=(r*.0193+g*.1192+b*.9505)/1.08883;const fx=pivotXyz(x),fy=pivotXyz(y),fz=pivotXyz(z);return{l:round(116*fy-16),a:round(500*(fx-fy)),b:round(200*(fy-fz)),alpha:v.a};}
export function deltaE76_2(a:LabColor2,b:LabColor2){const x=normalizeLab2(a),y=normalizeLab2(b);return round(Math.sqrt((x.l-y.l)**2+(x.a-y.a)**2+(x.b-y.b)**2));}
export function convertColor2(color:ColorValue2,target:"rgb"|"cmyk"|"lab"):ColorValue2{let rgb:RGBColor2;if(color.space==="rgb")rgb=color.value;else if(color.space==="cmyk")rgb=cmykToRgb2(color.value);else if(color.space==="spot")rgb=cmykToRgb2({...color.alternate,c:color.alternate.c*color.tint,m:color.alternate.m*color.tint,y:color.alternate.y*color.tint,k:color.alternate.k*color.tint});else{const l=normalizeLab2(color.value);const y=(l.l+16)/116,x=l.a/500+y,z=y-l.b/200;const inv=(n:number)=>n**3>.008856?n**3:(n-16/116)/7.787;const X=.95047*inv(x),Y=inv(y),Z=1.08883*inv(z);const linear=[X*3.2406+Y*-1.5372+Z*-.4986,X*-.9689+Y*1.8758+Z*.0415,X*.0557+Y*-.204+Z*1.057];const gamma=(n:number)=>255*(n>.0031308?1.055*n**(1/2.4)-.055:12.92*n);rgb=normalizeRGB2({r:gamma(linear[0]),g:gamma(linear[1]),b:gamma(linear[2]),a:l.alpha});}if(target==="rgb")return{space:"rgb",value:normalizeRGB2(rgb)};if(target==="cmyk")return{space:"cmyk",value:rgbToCmyk2(rgb)};return{space:"lab",value:rgbToLab2(rgb)};}
export function createSpotColor2(name:string,alternate:CMYKColor2,tint=1,overprint=true):SpotColor2{if(!name.trim())throw new Error("Spot color name is required");return{name:name.trim(),alternate:normalizeCMYK2(alternate),tint:clamp(tint),overprint};}
export function applyInkLimit2(color:CMYKColor2,maxTotalInk=3):CMYKColor2{const v=normalizeCMYK2(color),total=v.c+v.m+v.y+v.k,limit=clamp(maxTotalInk,0,4);if(total<=limit||total===0)return v;const scale=limit/total;return{c:round(v.c*scale),m:round(v.m*scale),y:round(v.y*scale),k:round(v.k*scale),a:v.a};}
export function isOutOfGamut2(color:ColorValue2,targetProfile:ICCProfile2){const c=convertColor2(color,"cmyk");if(c.space!=="cmyk")return false;const total=c.value.c+c.value.m+c.value.y+c.value.k;const threshold=targetProfile.space==="cmyk"?3.2:2.8;return total>threshold||Math.max(c.value.c,c.value.m,c.value.y)>0.98;}
export function buildSoftProof2(colors:ColorValue2[],settings:ProofSettings2){return colors.map((source,index)=>{const converted=convertColor2(source,settings.proofProfile.space);const warning=settings.gamutWarning&&isOutOfGamut2(source,settings.proofProfile);return{id:`proof-${index+1}`,source,converted,gamutWarning:warning,paperSimulation:settings.paperColor,blackInkSimulation:settings.blackInk};});}
export function buildSeparations2(objects:Array<{id:string;color:ColorValue2;overprint?:boolean}>):SeparationPlate2[]{const map=new Map<string,SeparationPlate2>();const add=(name:string,kind:SeparationPlate2["kind"],amount:number,id:string,overprint:boolean)=>{if(amount<=0)return;const plate=map.get(name)??{name,kind,coverage:0,overprintObjects:[]};plate.coverage=round(plate.coverage+amount);if(overprint)plate.overprintObjects.push(id);map.set(name,plate);};for(const o of objects){if(o.color.space==="spot"){add(o.color.name,"spot",clamp(o.color.tint),o.id,!!o.overprint);continue;}const c=convertColor2(o.color,"cmyk");if(c.space!=="cmyk")continue;add("Cyan","process",c.value.c,o.id,!!o.overprint);add("Magenta","process",c.value.m,o.id,!!o.overprint);add("Yellow","process",c.value.y,o.id,!!o.overprint);add("Black","process",c.value.k,o.id,!!o.overprint);}return[...map.values()].map(p=>({...p,coverage:round(p.coverage/Math.max(1,objects.length)),overprintObjects:[...new Set(p.overprintObjects)]}));}
export function mergeSwatches2(base:ColorSwatch2[],incoming:ColorSwatch2[]){const result=new Map(base.map(s=>[s.id,{...s}]));for(const swatch of incoming){const existing=result.get(swatch.id);if(existing?.locked)continue;result.set(swatch.id,{...swatch,name:swatch.name.trim()||"Untitled Swatch"});}return[...result.values()];}
const luminance=(rgb:RGBColor2)=>{const c=[rgb.r,rgb.g,rgb.b].map(v=>{const n=v/255;return n<=.03928?n/12.92:((n+.055)/1.055)**2.4;});return .2126*c[0]+.7152*c[1]+.0722*c[2];};
export function contrastRatio2(foreground:ColorValue2,background:ColorValue2){const f=convertColor2(foreground,"rgb"),b=convertColor2(background,"rgb");if(f.space!=="rgb"||b.space!=="rgb")return 1;const l1=luminance(f.value),l2=luminance(b.value);return round((Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05),2);}
export function validateColorEngine2(document:{profiles?:ICCProfile2[];swatches?:ColorSwatch2[];objects?:Array<{id:string;color:ColorValue2}>}){const issues:Array<{severity:"error"|"warning";message:string}>=[];const profileIds=new Set<string>();for(const p of document.profiles??[]){if(profileIds.has(p.id))issues.push({severity:"error",message:`Duplicate ICC profile: ${p.id}`});profileIds.add(p.id);}const swatchIds=new Set<string>();for(const s of document.swatches??[]){if(swatchIds.has(s.id))issues.push({severity:"error",message:`Duplicate swatch: ${s.id}`});swatchIds.add(s.id);if(!s.name.trim())issues.push({severity:"warning",message:`Unnamed swatch: ${s.id}`});}for(const o of document.objects??[]){if(o.color.space==="spot"&&!o.color.name.trim())issues.push({severity:"error",message:`Object ${o.id} has unnamed spot color`});}return issues;}
export function buildColorPlan2(document:any){return{version:"63.0",workingSpace:document.workingSpace??"sRGB IEC61966-2.1",proofing:document.proofSettings??null,swatchCount:(document.swatches??[]).length,separations:buildSeparations2(document.objects??[]),issues:validateColorEngine2(document)};}
