import AsyncStorage from "@react-native-async-storage/async-storage";
import { Platform } from "react-native";
import { createBlankProject } from "../constants/publisher";
import type { PublisherPage, PublisherProject, PublisherProjectVersion, SavedProjectSummary } from "../types/publisher";
import { analyzeProjectIntegrity } from "./projectPhase8DManager";
import { scanLinkedAssets } from "./projectProfessionalManager";

const CURRENT_PROJECT_KEY = "yaposan.publisher.phase2.current";
const PROJECT_INDEX_KEY = "yaposan.publisher.phase8.index";
const PROJECT_KEY_PREFIX = "yaposan.publisher.phase2.project.";
const VERSION_KEY_PREFIX = "yaposan.publisher.phase8.versions.";
const RECOVERY_INDEX_KEY = "yaposan.publisher.phase8b.recovery.index";
const RECOVERY_KEY_PREFIX = "yaposan.publisher.phase8b.recovery.";
const BACKUP_SETTINGS_KEY = "yaposan.publisher.phase8b.backup.settings";
const BACKUP_KEY_PREFIX = "yaposan.publisher.phase8b.backups.";
const FOLDERS_KEY = "yaposan.publisher.phase8a.folders";
const MAX_VERSIONS = 50;
const MAX_BACKUPS = 30;

export type RecoveryRecord = { projectId:string; projectName:string; createdAt:number; savedAt:number; project:PublisherProject };
export type BackupSettings = { enabled:boolean; intervalMinutes:5|10|30; maxBackups:number };
export type ProjectBackup = { id:string; projectId:string; createdAt:number; project:PublisherProject };

function getBrowserStorage(): Storage | null { if (Platform.OS !== "web" || typeof window === "undefined") return null; return window.localStorage; }
async function setValue(key:string,value:string){ const s=getBrowserStorage(); if(s){s.setItem(key,value);return;} await AsyncStorage.setItem(key,value); }
async function getValue(key:string){ const s=getBrowserStorage(); return s?s.getItem(key):AsyncStorage.getItem(key); }
async function removeValue(key:string){ const s=getBrowserStorage(); if(s){s.removeItem(key);return;} await AsyncStorage.removeItem(key); }

function normalizePage(page: Partial<PublisherPage>, index:number): PublisherPage {
 const width=Number(page.width)||816,height=Number(page.height)||1056;
 return {id:page.id||`page-${Date.now()}-${index}`,name:page.name||`Page ${index+1}`,width,height,orientation:page.orientation||(width>height?"landscape":"portrait"),sizeKey:page.sizeKey||"letter",backgroundColor:page.backgroundColor||"#FFFFFF",margin:Number.isFinite(page.margin)?Number(page.margin):36,bleed:Number.isFinite(page.bleed)?Number(page.bleed):12,elements:Array.isArray(page.elements)?page.elements.map((e:any,i)=>({...e,id:e.id||`object-${Date.now()}-${i}`,type:e.type||"rectangle",name:e.name||`${e.type||"object"} ${i+1}`,x:Number.isFinite(e.x)?Number(e.x):0,y:Number.isFinite(e.y)?Number(e.y):0,width:Number.isFinite(e.width)&&Number(e.width)>0?Number(e.width):100,height:Number.isFinite(e.height)&&Number(e.height)>0?Number(e.height):100,rotation:Number.isFinite(e.rotation)?Number(e.rotation):0,zIndex:Number.isFinite(e.zIndex)?Number(e.zIndex):i+1,opacity:Number.isFinite(e.opacity)?Math.max(0,Math.min(1,Number(e.opacity))):1})):[]};
}
export function normalizePublisherProject(value:unknown): PublisherProject { if(!value||typeof value!=="object") return createBlankProject(); const src=value as Partial<PublisherProject>; const pages=Array.isArray(src.pages)&&src.pages.length?src.pages.map(normalizePage):createBlankProject().pages; const now=Date.now(); return {id:src.id||`project-${now}`,name:src.name||"Untitled Publication",createdAt:src.createdAt||now,updatedAt:src.updatedAt||now,pages,activePageId:pages.some(p=>p.id===src.activePageId)?String(src.activePageId):pages[0].id,autoSave:src.autoSave??true,version:2,author:src.author||"",description:src.description||"",tags:Array.isArray(src.tags)?src.tags:[],dpi:Number(src.dpi)||300,colorMode:src.colorMode==="CMYK"?"CMYK":"RGB",embeddedFonts:src.embeddedFonts&&typeof src.embeddedFonts==="object"?src.embeddedFonts:{},embeddedFontMetadata:src.embeddedFontMetadata&&typeof src.embeddedFontMetadata==="object"?src.embeddedFontMetadata:{}}; }
function sizeOf(project:PublisherProject){ const json=JSON.stringify(project); try{return new Blob([json]).size}catch{return json.length} }
function colorFor(project:PublisherProject){ return project.pages[0]?.backgroundColor||"#E9F5F3"; }
function esc(value:unknown){return String(value??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]||c));}
function thumbnailFor(project:PublisherProject){
 const page=project.pages[0]; if(!page)return ""; const w=Math.max(1,page.width),h=Math.max(1,page.height);
 const body=page.elements.slice().sort((a,b)=>a.zIndex-b.zIndex).slice(0,80).map((e:any)=>{const common=`transform="rotate(${Number(e.rotation)||0} ${e.x+e.width/2} ${e.y+e.height/2})" opacity="${e.opacity??1}"`; if(e.type==="text")return `<text x="${e.x}" y="${e.y+(e.fontSize||18)}" font-family="${esc(e.fontFamily||"Arial")}" font-size="${Math.max(8,Number(e.fontSize)||18)}" font-weight="${esc(e.fontWeight||"400")}" fill="${esc(e.textColor||"#17212B")}" ${common}>${esc(String(e.text||"").slice(0,80))}</text>`; if(e.type==="circle")return `<ellipse cx="${e.x+e.width/2}" cy="${e.y+e.height/2}" rx="${e.width/2}" ry="${e.height/2}" fill="${esc(e.fillColor||"transparent")}" stroke="${esc(e.borderColor||"transparent")}" stroke-width="${e.borderWidth||0}" ${common}/>`; if(e.type==="image"&&e.imageUri)return `<image href="${esc(e.imageUri)}" x="${e.x}" y="${e.y}" width="${e.width}" height="${e.height}" preserveAspectRatio="xMidYMid slice" ${common}/>`; return `<rect x="${e.x}" y="${e.y}" width="${e.width}" height="${e.height}" rx="${e.borderRadius||0}" fill="${esc(e.fillColor||"transparent")}" stroke="${esc(e.borderColor||"transparent")}" stroke-width="${e.borderWidth||0}" ${common}/>`;}).join("");
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}"><rect width="100%" height="100%" fill="${esc(page.backgroundColor||"#fff")}"/>${body}</svg>`;
}
function cloneProject(project:PublisherProject){ return normalizePublisherProject(JSON.parse(JSON.stringify(project))); }

export async function saveCurrentPublisherProject(project:PublisherProject){ await setValue(CURRENT_PROJECT_KEY,JSON.stringify({...project,updatedAt:Date.now()})); }
export async function loadCurrentPublisherProject(){ const v=await getValue(CURRENT_PROJECT_KEY); if(!v)return null; try{return normalizePublisherProject(JSON.parse(v))}catch{return null} }
export async function clearCurrentPublisherProject(){ await removeValue(CURRENT_PROJECT_KEY); }
export async function listSavedPublisherProjects(){ const v=await getValue(PROJECT_INDEX_KEY); if(!v)return []; try{const a=JSON.parse(v) as SavedProjectSummary[];return Array.isArray(a)?a.sort((x,y)=>y.updatedAt-x.updatedAt):[]}catch{return[]} }
async function writeProjectIndex(items:SavedProjectSummary[]){ await setValue(PROJECT_INDEX_KEY,JSON.stringify(items)); }

export async function createProjectVersion(project:PublisherProject,label="Manual version"){ const key=`${VERSION_KEY_PREFIX}${project.id}`; const items=await listProjectVersions(project.id); const snapshot=cloneProject(project); const last=items[0]; if(last&&JSON.stringify(last.project)===JSON.stringify(snapshot)&&last.label===label)return last; const v:PublisherProjectVersion={id:`version-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,projectId:project.id,createdAt:Date.now(),label,project:snapshot}; await setValue(key,JSON.stringify([v,...items].slice(0,MAX_VERSIONS))); return v; }
export async function listProjectVersions(projectId:string){ const raw=await getValue(`${VERSION_KEY_PREFIX}${projectId}`); try{return raw?JSON.parse(raw) as PublisherProjectVersion[]:[]}catch{return[]} }
export async function renameProjectVersion(projectId:string,versionId:string,label:string){ const summary=(await listSavedPublisherProjects()).find(x=>x.id===projectId); if(summary?.readOnly)throw new Error("Read-only projects cannot modify history or backups."); const items=await listProjectVersions(projectId); await setValue(`${VERSION_KEY_PREFIX}${projectId}`,JSON.stringify(items.map(v=>v.id===versionId?{...v,label:label.trim()||v.label}:v))); }
export async function deleteProjectVersion(projectId:string,versionId:string){ const summary=(await listSavedPublisherProjects()).find(x=>x.id===projectId); if(summary?.readOnly)throw new Error("Read-only projects cannot modify history or backups."); const items=await listProjectVersions(projectId); await setValue(`${VERSION_KEY_PREFIX}${projectId}`,JSON.stringify(items.filter(v=>v.id!==versionId))); }
export async function restoreProjectVersion(projectId:string,versionId:string){ const summary=(await listSavedPublisherProjects()).find(x=>x.id===projectId); if(summary?.readOnly)throw new Error("Read-only projects cannot restore versions."); const versions=await listProjectVersions(projectId); const found=versions.find(v=>v.id===versionId); if(!found)return null; const current=await loadPublisherProject(projectId); if(current)await createProjectVersion(current,"Before restore"); const restored={...cloneProject(found.project),id:projectId,updatedAt:Date.now()}; await savePublisherProject(restored,"Restored version",false); return restored; }

export async function getBackupSettings():Promise<BackupSettings>{ const raw=await getValue(BACKUP_SETTINGS_KEY); try{return {...{enabled:true,intervalMinutes:10,maxBackups:15},...JSON.parse(raw||"{}")}}catch{return {enabled:true,intervalMinutes:10,maxBackups:15}} }
export async function saveBackupSettings(settings:BackupSettings){ await setValue(BACKUP_SETTINGS_KEY,JSON.stringify(settings)); }
export async function createProjectBackup(project:PublisherProject){ const settings=await getBackupSettings(); if(!settings.enabled)return null; const items=await listProjectBackups(project.id); const backup:ProjectBackup={id:`backup-${Date.now()}`,projectId:project.id,createdAt:Date.now(),project:cloneProject(project)}; await setValue(`${BACKUP_KEY_PREFIX}${project.id}`,JSON.stringify([backup,...items].slice(0,Math.min(MAX_BACKUPS,settings.maxBackups)))); return backup; }
export async function listProjectBackups(projectId:string){ const raw=await getValue(`${BACKUP_KEY_PREFIX}${projectId}`); try{return raw?JSON.parse(raw) as ProjectBackup[]:[]}catch{return[]} }
export async function deleteProjectBackup(projectId:string,backupId:string){ const summary=(await listSavedPublisherProjects()).find(x=>x.id===projectId); if(summary?.readOnly)throw new Error("Read-only projects cannot modify history or backups."); const items=await listProjectBackups(projectId); await setValue(`${BACKUP_KEY_PREFIX}${projectId}`,JSON.stringify(items.filter(v=>v.id!==backupId))); }
export async function restoreProjectBackup(projectId:string,backupId:string){ const summary=(await listSavedPublisherProjects()).find(x=>x.id===projectId); if(summary?.readOnly)throw new Error("Read-only projects cannot restore backups."); const items=await listProjectBackups(projectId); const found=items.find(v=>v.id===backupId); if(!found)return null; const restored={...cloneProject(found.project),id:projectId,updatedAt:Date.now()}; await savePublisherProject(restored,"Restored backup"); return restored; }

async function recoveryIds(){ const raw=await getValue(RECOVERY_INDEX_KEY); try{return raw?JSON.parse(raw) as string[]:[]}catch{return[]} }
export async function saveRecoveryProject(project:PublisherProject){ const record:RecoveryRecord={projectId:project.id,projectName:project.name,createdAt:Date.now(),savedAt:project.updatedAt,project:cloneProject(project)}; await setValue(`${RECOVERY_KEY_PREFIX}${project.id}`,JSON.stringify(record)); const ids=await recoveryIds(); await setValue(RECOVERY_INDEX_KEY,JSON.stringify([project.id,...ids.filter(id=>id!==project.id)])); return record; }
export async function loadRecoveryProject(projectId?:string){ const id=projectId||(await recoveryIds())[0]; if(!id)return null; const raw=await getValue(`${RECOVERY_KEY_PREFIX}${id}`); try{return raw?JSON.parse(raw) as RecoveryRecord:null}catch{return null} }
export async function listRecoveryProjects(){ const ids=await recoveryIds(); const values=await Promise.all(ids.map(id=>loadRecoveryProject(id))); return values.filter(Boolean) as RecoveryRecord[]; }
export async function clearRecoveryProject(projectId?:string){ if(projectId){await removeValue(`${RECOVERY_KEY_PREFIX}${projectId}`);const ids=await recoveryIds();await setValue(RECOVERY_INDEX_KEY,JSON.stringify(ids.filter(id=>id!==projectId)));return;} for(const id of await recoveryIds())await removeValue(`${RECOVERY_KEY_PREFIX}${id}`);await removeValue(RECOVERY_INDEX_KEY); }

async function savePublisherProjectCore(project:PublisherProject,label="Save",capturePrevious=true){ const normalized=normalizePublisherProject({...project,updatedAt:Date.now()}); const previous=await loadPublisherProject(normalized.id); if(previous&&capturePrevious) await createProjectVersion(previous,label); await setValue(`${PROJECT_KEY_PREFIX}${normalized.id}`,JSON.stringify(normalized)); await saveCurrentPublisherProject(normalized); await clearRecoveryProject(normalized.id); const index=await listSavedPublisherProjects(); const old=index.find(i=>i.id===normalized.id); const diagnostic=analyzeProjectIntegrity(normalized); const firstPage=normalized.pages[0]; const summary:SavedProjectSummary={id:normalized.id,name:normalized.name,createdAt:normalized.createdAt,updatedAt:normalized.updatedAt,pageCount:normalized.pages.length,favorite:old?.favorite??false,folder:old?.folder??"",deletedAt:old?.deletedAt??null,archivedAt:old?.archivedAt??null,readOnly:old?.readOnly??false,thumbnailColor:colorFor(normalized),description:normalized.description||old?.description||"",tags:normalized.tags||old?.tags||[],author:normalized.author||old?.author||"",sizeBytes:sizeOf(normalized),thumbnailSvg:thumbnailFor(normalized),pageWidth:firstPage?.width,pageHeight:firstPage?.height,orientation:firstPage?.orientation,missingAssets:diagnostic.missingAssets,missingFonts:diagnostic.missingFonts,assetKinds:Array.from(new Set(scanLinkedAssets(normalized).map(a=>a.kind)))}; await writeProjectIndex([summary,...index.filter(i=>i.id!==normalized.id)]); }

export type SaveQueueState={status:"idle"|"queued"|"saving"|"retrying"|"completed"|"failed";pending:number;attempt:number;projectId?:string;error?:string};
let saveQueue:Promise<void>=Promise.resolve(); let saveGeneration=0; let lastFailedProject:PublisherProject|null=null; let saveState:SaveQueueState={status:"idle",pending:0,attempt:0}; const saveListeners=new Set<(state:SaveQueueState)=>void>();
const publishSaveState=(patch:Partial<SaveQueueState>)=>{saveState={...saveState,...patch};saveListeners.forEach(listener=>listener(saveState));};
export function getSaveQueueStatus(){return saveState;}
export function subscribeSaveQueue(listener:(state:SaveQueueState)=>void){saveListeners.add(listener);listener(saveState);return()=>{saveListeners.delete(listener);};}
export function cancelPendingSaves(){saveGeneration+=1;publishSaveState({status:"idle",pending:0,error:undefined});}
export async function retryFailedSave(project?:PublisherProject,label="Manual retry"){const target=project??lastFailedProject;if(!target)throw new Error("There is no failed save to retry.");return savePublisherProject(target,label);}
export async function savePublisherProject(project:PublisherProject,label="Save",capturePrevious=true){
 const existing=(await listSavedPublisherProjects()).find(x=>x.id===project.id); if(existing?.readOnly)throw new Error("This project is read-only. Use Save As to create an editable copy.");
 const generation=saveGeneration; publishSaveState({status:"queued",pending:saveState.pending+1,projectId:project.id,error:undefined});
 const run=async()=>{if(generation!==saveGeneration)return;let lastError:unknown;for(let attempt=1;attempt<=3;attempt+=1){try{publishSaveState({status:attempt===1?"saving":"retrying",attempt,projectId:project.id});await savePublisherProjectCore(project,label,capturePrevious);publishSaveState({status:"completed",attempt,projectId:project.id});return;}catch(error){lastError=error;if(attempt<3)await new Promise(resolve=>setTimeout(resolve,250*attempt));}}const message=lastError instanceof Error?lastError.message:"Unable to save project after three attempts.";lastFailedProject=project;publishSaveState({status:"failed",error:message,projectId:project.id});throw new Error(message);};
 const queued=saveQueue.then(run,run);saveQueue=queued.then(()=>undefined,()=>undefined);try{return await queued;}finally{const pending=Math.max(0,saveState.pending-1);publishSaveState({pending,status:pending?"queued":saveState.status==="failed"?"failed":"idle"});}
}
export async function loadPublisherProject(id:string){ const v=await getValue(`${PROJECT_KEY_PREFIX}${id}`); if(!v)return null; try{return normalizePublisherProject(JSON.parse(v))}catch{return null} }
export async function renamePublisherProject(id:string,name:string){ const p=await loadPublisherProject(id);if(!p)return null;const n={...p,name:name.trim()||p.name,updatedAt:Date.now()};await savePublisherProject(n,"Rename");return n; }
export async function duplicatePublisherProject(id:string){const p=await loadPublisherProject(id);if(!p)return null;const now=Date.now();const c=normalizePublisherProject({...JSON.parse(JSON.stringify(p)),id:`project-${now}-${Math.random().toString(36).slice(2,8)}`,name:`${p.name} Copy`,createdAt:now,updatedAt:now});await savePublisherProject(c,"Duplicate");return c;}
export async function deletePublisherProject(id:string){ const index=await listSavedPublisherProjects(); await writeProjectIndex(index.map(i=>i.id===id?{...i,deletedAt:Date.now()}:i)); }
export async function restoreDeletedPublisherProject(id:string){ const index=await listSavedPublisherProjects(); await writeProjectIndex(index.map(i=>i.id===id?{...i,deletedAt:null,updatedAt:Date.now()}:i)); }
export async function permanentlyDeletePublisherProject(id:string){ await removeValue(`${PROJECT_KEY_PREFIX}${id}`);await removeValue(`${VERSION_KEY_PREFIX}${id}`);await removeValue(`${BACKUP_KEY_PREFIX}${id}`);await clearRecoveryProject(id);const index=await listSavedPublisherProjects();await writeProjectIndex(index.filter(i=>i.id!==id)); }
export async function emptyProjectTrash(){ const index=await listSavedPublisherProjects(); for(const i of index.filter(x=>x.deletedAt))await permanentlyDeletePublisherProject(i.id); }
export async function updateProjectSummary(id:string,patch:Partial<SavedProjectSummary>){const index=await listSavedPublisherProjects();await writeProjectIndex(index.map(i=>i.id===id?{...i,...patch}:i));}
export async function getProjectStorageStats(){const items=await listSavedPublisherProjects();return {projects:items.filter(i=>!i.deletedAt).length,trash:items.filter(i=>i.deletedAt).length,bytes:items.reduce((n,i)=>n+(i.sizeBytes||0),0),versions:(await Promise.all(items.map(i=>listProjectVersions(i.id)))).reduce((n,v)=>n+v.length,0)};}
export async function listProjectFolders(){const raw=await getValue(FOLDERS_KEY);try{return raw?JSON.parse(raw) as string[]:[]}catch{return[]}}
export async function createProjectFolder(name:string){const clean=name.trim();if(!clean)return;const items=await listProjectFolders();if(!items.some(x=>x.toLowerCase()===clean.toLowerCase()))await setValue(FOLDERS_KEY,JSON.stringify([...items,clean].sort((a,b)=>a.localeCompare(b))));}
export async function renameProjectFolder(oldName:string,newName:string){const clean=newName.trim();if(!clean)return;const items=await listProjectFolders();await setValue(FOLDERS_KEY,JSON.stringify(items.map(x=>x===oldName?clean:x).filter((x,i,a)=>a.indexOf(x)===i)));const index=await listSavedPublisherProjects();await writeProjectIndex(index.map(x=>x.folder===oldName?{...x,folder:clean}:x));}
export async function deleteProjectFolder(name:string){const items=await listProjectFolders();await setValue(FOLDERS_KEY,JSON.stringify(items.filter(x=>x!==name)));const index=await listSavedPublisherProjects();await writeProjectIndex(index.map(x=>x.folder===name?{...x,folder:""}:x));}
export async function moveProjectsToFolder(ids:string[],folder:string){if(folder)await createProjectFolder(folder);const set=new Set(ids);const index=await listSavedPublisherProjects();await writeProjectIndex(index.map(x=>set.has(x.id)?{...x,folder}:x));}
export async function setProjectsFavorite(ids:string[],favorite:boolean){const set=new Set(ids);const index=await listSavedPublisherProjects();await writeProjectIndex(index.map(x=>set.has(x.id)?{...x,favorite}:x));}
export async function trashProjects(ids:string[]){const set=new Set(ids);const index=await listSavedPublisherProjects();await writeProjectIndex(index.map(x=>set.has(x.id)?{...x,deletedAt:Date.now()}:x));}
export async function restoreProjects(ids:string[]){const set=new Set(ids);const index=await listSavedPublisherProjects();await writeProjectIndex(index.map(x=>set.has(x.id)?{...x,deletedAt:null,updatedAt:Date.now()}:x));}

export function createPublisherAutoSave(getProject:()=>PublisherProject,delayMs=1200,onSaved?:()=>void){let timer:ReturnType<typeof setTimeout>|null=null;const cancel=()=>{if(timer)clearTimeout(timer);timer=null};const flush=async()=>{cancel();const p=getProject();if(p.autoSave){await savePublisherProject(p,"Autosave");onSaved?.()}};const schedule=()=>{cancel();timer=setTimeout(()=>void flush(),delayMs)};return{schedule,cancel,flush};}
export function createPublisherRecoveryWriter(getProject:()=>PublisherProject,delayMs=1500){let timer:ReturnType<typeof setTimeout>|null=null;const cancel=()=>{if(timer)clearTimeout(timer);timer=null};const flush=async()=>{cancel();await saveRecoveryProject(getProject())};const schedule=()=>{cancel();timer=setTimeout(()=>void flush(),delayMs)};return{schedule,cancel,flush};}

export async function setProjectsArchived(ids:string[],archived:boolean){const set=new Set(ids);const index=await listSavedPublisherProjects();await writeProjectIndex(index.map(x=>set.has(x.id)?{...x,archivedAt:archived?Date.now():null}:x));}
export async function setProjectsReadOnly(ids:string[],readOnly:boolean){const set=new Set(ids);const index=await listSavedPublisherProjects();await writeProjectIndex(index.map(x=>set.has(x.id)?{...x,readOnly}:x));}
export async function duplicateProjects(ids:string[]){const results=[];for(const id of ids){const copy=await duplicatePublisherProject(id);if(copy)results.push(copy);}return results;}
