export type WebBlockType = "hero" | "text" | "image" | "gallery" | "button" | "form" | "pricing" | "faq" | "footer";
export type WebBreakpoint = "desktop" | "tablet" | "mobile";
export type WebBlock = { id:string; type:WebBlockType; title:string; content:string; visible:boolean };
export type WebProject = { id:string; name:string; slug:string; breakpoint:WebBreakpoint; blocks:WebBlock[]; seo:{title:string;description:string;keywords:string}; publish:{domain:string;analytics:boolean;forms:boolean} };
export const WEB_BLOCK_LIBRARY: Array<{type:WebBlockType;title:string;description:string}> = [
 {type:"hero",title:"Hero",description:"Headline, copy and primary action"},{type:"text",title:"Text",description:"Rich editorial content"},{type:"image",title:"Image",description:"Responsive image or product visual"},{type:"gallery",title:"Gallery",description:"Grid, carousel or masonry gallery"},{type:"button",title:"Button",description:"Linked call-to-action"},{type:"form",title:"Form",description:"Contact, signup, survey or order form"},{type:"pricing",title:"Pricing",description:"Plans and feature comparison"},{type:"faq",title:"FAQ",description:"Expandable questions and answers"},{type:"footer",title:"Footer",description:"Navigation, legal and social links"}
];
export function createWebProject(name="Untitled Website"):WebProject{return {id:`web-${Date.now()}`,name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"website",breakpoint:"desktop",blocks:[{id:"hero-1",type:"hero",title:"Create something remarkable",content:"Build and publish a professional website without leaving Yaposan.",visible:true},{id:"footer-1",type:"footer",title:"Footer",content:"© Yaposan",visible:true}],seo:{title:name,description:"Professional website created in Yaposan Web Studio.",keywords:"design, website, yaposan"},publish:{domain:"",analytics:true,forms:true}}}
export function addWebBlock(project:WebProject,type:WebBlockType):WebProject{const preset=WEB_BLOCK_LIBRARY.find(x=>x.type===type)!;return {...project,blocks:[...project.blocks,{id:`${type}-${Date.now()}`,type,title:preset.title,content:preset.description,visible:true}]}}
export function moveWebBlock(project:WebProject,id:string,direction:-1|1):WebProject{const blocks=[...project.blocks];const i=blocks.findIndex(x=>x.id===id);const j=i+direction;if(i<0||j<0||j>=blocks.length)return project;[blocks[i],blocks[j]]=[blocks[j],blocks[i]];return {...project,blocks}}
export function buildWebExport(project:WebProject,format:"html"|"pwa"|"static-zip"){return {id:`deploy-${Date.now()}`,projectId:project.id,format,status:"ready" as const,files:["index.html","assets/","styles.css","site.json"],createdAt:new Date().toISOString()}}
