import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";

export default function AIAccessManager(){
  return <View style={{gap:14}}>
    <View style={s.card}><Text style={s.eyebrow}>BRING YOUR OWN AI</Text><Text style={s.title}>Yaposan provides the platform. You choose the AI.</Text><Text style={s.body}>AI-powered features use your connected provider account or supported local AI. Your provider bills you directly for its usage; Yaposan does not charge for your provider&apos;s AI usage.</Text></View>
    <View style={s.grid}>
      <View style={[s.option,s.recommended,{borderColor:"#9333ea"}]}><Text style={s.badge}>RECOMMENDED</Text><Ionicons name="key-outline" size={24} color="#9333ea"/><Text style={s.optionTitle}>Connect Your AI Provider</Text><Text style={s.price}>Pay provider directly</Text><Text style={s.body}>Connect OpenAI, Gemini, Anthropic, or another compatible provider. Your provider account and limits apply.</Text><Pressable style={[s.button,{backgroundColor:"#9333ea"}]} onPress={()=>router.push("/ai-provider-settings" as never)}><Text style={s.buttonText}>Connect My AI</Text></Pressable></View>
      <View style={[s.option,{borderColor:"#14b8a6"}]}><Ionicons name="home-outline" size={24} color="#14b8a6"/><Text style={s.optionTitle}>Use Local AI</Text><Text style={s.price}>Free · Your hardware</Text><Text style={s.body}>Connect supported local AI such as Ollama or LM Studio. No Yaposan cloud-AI charges are required for supported local workflows.</Text><Pressable style={[s.button,{backgroundColor:"#14b8a6"}]} onPress={()=>router.push("/ai-provider-settings" as never)}><Text style={s.buttonText}>Connect Local AI</Text></Pressable></View>
    </View>
    <View style={s.card}><Text style={s.title}>How AI works in Yaposan</Text><Text style={s.body}>Publisher and standard editing tools can work without AI. When Photo Studio, Yaposan AI, or another tool needs an AI provider, Yaposan uses the provider or local AI you configured. If none is configured, Yaposan should ask you to connect one instead of silently using a Yaposan-paid cloud provider.</Text></View>
  </View>;
}
const s=StyleSheet.create({card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dbe4ee",borderRadius:16,padding:18,gap:8},eyebrow:{color:"#0f766e",fontSize:11,fontWeight:"900",letterSpacing:1},title:{fontSize:20,fontWeight:"900",color:"#172033"},body:{color:"#64748b",fontSize:12,lineHeight:18},grid:{flexDirection:"row",flexWrap:"wrap",gap:12},option:{backgroundColor:"#fff",borderWidth:2,borderRadius:16,padding:16,width:"48%",minWidth:240,gap:8},recommended:{shadowColor:"#9333ea",shadowOpacity:.18,shadowRadius:10,shadowOffset:{width:0,height:4}},badge:{alignSelf:"flex-start",backgroundColor:"#9333ea",color:"#fff",fontWeight:"900",fontSize:9,paddingHorizontal:8,paddingVertical:4,borderRadius:999},optionTitle:{fontWeight:"900",fontSize:16,color:"#172033"},price:{fontWeight:"900",fontSize:18,color:"#334155"},button:{marginTop:"auto",padding:11,borderRadius:10,alignItems:"center"},buttonText:{color:"#fff",fontWeight:"900"}});
