import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Linking, Platform, Pressable, StyleSheet, Text, View } from "react-native";
import { useAuth } from "../../context/AuthContext";

const creditPacks = [
  { id:"small", label: "Small", price: "$2", note: "200 hosted AI credits" },
  { id:"standard", label: "Standard", price: "$5", note: "550 hosted AI credits" },
  { id:"more", label: "More", price: "$10", note: "1,200 hosted AI credits" },
] as const;

type Budget={limitUsd:number;usedUsd:number;remainingUsd:number;available:boolean};
export default function AIAccessManager(){
  const auth=useAuth(); const [balance,setBalance]=useState<number|null>(null); const [budget,setBudget]=useState<Budget|null>(null);
  const refresh=async()=>{if(!auth.isAuthenticated)return;try{const [a,b]=await Promise.all([auth.authorizedFetch("/api/v1/ai-credits/balance"),auth.authorizedFetch("/api/v1/ai/community-budget")]);if(a.ok)setBalance((await a.json()).balance??0);if(b.ok)setBudget(await b.json())}catch{}};
  useEffect(()=>{void refresh()},[auth.isAuthenticated]);
  const creditInfo=()=>Alert.alert("Yaposan AI Credits", "Credits are prepaid, non-subscription usage for Yaposan-hosted cloud AI. You can always use local AI or pay your own provider directly instead.");
  const buyCredits=async(pack:string)=>{if(!auth.isAuthenticated)return Alert.alert("Sign in required","Sign in before purchasing AI credits so the pack can be credited to your workspace.");try{const origin=Platform.OS==="web"&&typeof window!=="undefined"?window.location.origin:"https://app.yaposan.com";const response=await auth.authorizedFetch("/api/v1/ai-credits/checkout",{method:"POST",body:JSON.stringify({pack,successUrl:`${origin}/account?aiCredits=purchased`,cancelUrl:`${origin}/account?aiCredits=cancelled`})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message??"Checkout could not be started.");if(data.url)await Linking.openURL(data.url)}catch(error){Alert.alert("AI credit checkout",error instanceof Error?error.message:"Checkout could not be started.")}};
  return <View style={{gap:14}}>
    <View style={s.card}><Text style={s.eyebrow}>FREE & OPEN SOURCE</Text><Text style={s.title}>Yaposan has no paid application tier</Text><Text style={s.body}>Core Yaposan features stay free. You choose separately how AI requests are paid for, and you can avoid cloud AI charges entirely by using local tools.</Text></View>
    <View style={s.grid}>
      <View style={[s.option,{borderColor:"#14b8a6"}]}><Ionicons name="home-outline" size={24} color="#14b8a6"/><Text style={s.optionTitle}>Yaposan Local</Text><Text style={s.price}>Free</Text><Text style={s.body}>Use supported local AI tools without API charges.</Text><Pressable style={[s.button,{backgroundColor:"#14b8a6"}]} onPress={()=>router.push("/ai" as never)}><Text style={s.buttonText}>Use local AI</Text></Pressable></View>
      <View style={[s.option,{borderColor:"#2563eb"}]}><Ionicons name="globe-outline" size={24} color="#2563eb"/><Text style={s.optionTitle}>Community AI</Text><Text style={s.price}>Free · Limited</Text><Text style={s.body}>{budget?`${budget.available?"Available":"Monthly budget reached"} · $${budget.remainingUsd.toFixed(2)} shared budget remaining this month.`:"Sponsored from Yaposan's shared monthly community budget and subject to availability."}</Text><Pressable style={[s.button,{backgroundColor:"#2563eb"}]} onPress={()=>router.push("/ai" as never)}><Text style={s.buttonText}>Try Community AI</Text></Pressable></View>
      <View style={[s.option,s.recommended,{borderColor:"#9333ea"}]}><Text style={s.badge}>RECOMMENDED</Text><Ionicons name="key-outline" size={24} color="#9333ea"/><Text style={s.optionTitle}>Use My AI Provider</Text><Text style={s.price}>Pay provider directly</Text><Text style={s.body}>Connect OpenAI, Gemini, Anthropic, Ollama, LM Studio, or a custom provider. Provider keys are encrypted server-side.</Text><Pressable style={[s.button,{backgroundColor:"#9333ea"}]} onPress={()=>router.push("/ai-provider-settings" as never)}><Text style={s.buttonText}>Connect provider</Text></Pressable></View>
      <View style={[s.option,{borderColor:"#f59e0b"}]}><Ionicons name="sparkles" size={24} color="#f59e0b"/><Text style={s.optionTitle}>Yaposan AI Credits</Text><Text style={s.price}>Pay as you go</Text><Text style={s.body}>{balance===null?"Prepay only for Yaposan-hosted AI usage. No recurring application subscription.":`${balance.toLocaleString()} credits available. Hosted requests reserve credits before provider spend.`}</Text><Pressable style={[s.button,{backgroundColor:"#f59e0b"}]} onPress={creditInfo}><Text style={s.buttonText}>Credit purchase info</Text></Pressable></View>
    </View>
    <View style={s.card}><Text style={s.title}>Buy AI Credits</Text><Text style={s.body}>Credit packs are prepaid so Yaposan does not spend on a hosted cloud-AI request before funds are available.</Text><View style={s.packs}>{creditPacks.map(pack=><Pressable key={pack.price} onPress={()=>buyCredits(pack.id)} style={s.pack}><Text style={s.packPrice}>{pack.price}</Text><Text style={s.optionTitle}>{pack.label}</Text><Text style={s.body}>{pack.note}</Text></Pressable>)}</View><Text style={s.note}>Phase 90.7 adds shared Community AI budget enforcement, hosted-AI credit reservation and settlement, and encrypted BYO-provider credentials. Yaposan remains free/open source.</Text></View>
  </View>;
}
const s=StyleSheet.create({card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dbe4ee",borderRadius:16,padding:18,gap:8},eyebrow:{color:"#0f766e",fontSize:11,fontWeight:"900",letterSpacing:1},title:{fontSize:20,fontWeight:"900",color:"#172033"},body:{color:"#64748b",fontSize:12,lineHeight:18},grid:{flexDirection:"row",flexWrap:"wrap",gap:12},option:{backgroundColor:"#fff",borderWidth:2,borderRadius:16,padding:16,width:"48%",minWidth:240,gap:8},recommended:{shadowColor:"#9333ea",shadowOpacity:.18,shadowRadius:10,shadowOffset:{width:0,height:4}},badge:{alignSelf:"flex-start",backgroundColor:"#9333ea",color:"#fff",fontWeight:"900",fontSize:9,paddingHorizontal:8,paddingVertical:4,borderRadius:999},optionTitle:{fontWeight:"900",fontSize:16,color:"#172033"},price:{fontWeight:"900",fontSize:18,color:"#334155"},button:{marginTop:"auto",padding:11,borderRadius:10,alignItems:"center"},buttonText:{color:"#fff",fontWeight:"900"},packs:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:6},pack:{minWidth:150,flexGrow:1,borderWidth:1,borderColor:"#e2e8f0",borderRadius:12,padding:14,backgroundColor:"#f8fafc"},packPrice:{fontSize:24,fontWeight:"900",color:"#172033"},note:{color:"#475569",fontSize:11,lineHeight:17,fontWeight:"700",marginTop:4}});
