import { existsSync, readFileSync } from "node:fs";
const required=["src/app/product-photo-studio.tsx","src/components/ProductPhotoMaskTouchup.web.tsx","server/backgroundRemoval.ts","services/background-removal/app.py","release/phase91.0/quality-targets.json","release/phase91.0/cost-policy.json","release/phase91.0/organization-pilot.json","release/phase91.0/model-policy.json","tests/phase910-production-product-photo-engine.test.mjs","PHASE91.0-PRODUCTION-PRODUCT-PHOTO-ENGINE.md"];
for(const f of required) if(!existsSync(f)) throw new Error(`Missing Phase 91.0 artifact: ${f}`);
const pkg=JSON.parse(readFileSync("package.json","utf8"));
if(!pkg.scripts?.test?.includes("test:phase91.0")) throw new Error("Top-level npm test must include Phase 91.0");
const cost=JSON.parse(readFileSync("release/phase91.0/cost-policy.json","utf8"));
if(cost.paidPerImageProviderEnabled || cost.paidProviderMonthlyBudgetUsd!==0 || cost.autoOverage) throw new Error("Paid API fallback must remain disabled with zero default budget and no auto-overage");
const q=JSON.parse(readFileSync("release/phase91.0/quality-targets.json","utf8"));
if(q.certifiedEquivalentToPhotoRoom || q.certifiedEquivalentToRemovalAI) throw new Error("Competitive-equivalence claims require real benchmark evidence");
if(q.minimumBenchmarkImages<200 || q.recommendedBenchmarkImages<500) throw new Error("91.0 benchmark evidence floor is too weak");
console.log("Phase 91.0 production product-photo engine structural gate passed. Real organization benchmark evidence remains required before competitive-quality certification.");
