import { existsSync, readFileSync } from 'node:fs';
const read=p=>readFileSync(p,'utf8');const fail=m=>{throw new Error(`Phase 91.4: ${m}`)};
for(const f of ['release/phase91.4/parity-policy.json','release/phase91.4/benchmark-template.csv','scripts/evaluate-phase91.4-parity.mjs','tests/phase914-quality-parity-hardening.test.mjs','PHASE91.4-PRODUCT-PHOTO-QUALITY-PARITY-HARDENING.md'])if(!existsSync(f))fail(`missing ${f}`);
const app=read('services/background-removal/app.py');for(const token of ['ImageOps.exif_transpose','mask_iou','connected_components','model-disagreement','candidate_count','model_agreement_iou','product_pixel_policy','shadow_policy','/warmup'])if(!app.includes(token))fail(`engine missing ${token}`);
const server=read('server/backgroundRemoval.ts');for(const token of ['candidateCount','modelAgreementIou','maskDiagnostics','engineVersion'])if(!server.includes(token))fail(`server contract missing ${token}`);
const env=read('.env.example');for(const line of ['YAPOSAN_BG_DETAIL_MODEL=birefnet-general','YAPOSAN_BG_AGREEMENT_IOU=0.90','YAPOSAN_BG_AUTO_DETAIL_DIFFICULTY=0.30'])if(!env.includes(line))fail(`env mismatch ${line}`);
const policy=JSON.parse(read('release/phase91.4/parity-policy.json'));if(policy.claimStatus!=='PARITY_TARGET_NOT_EXTERNALLY_CERTIFIED')fail('must not self-certify commercial parity');if(policy.maximumUnexpectedPaidApiSpendUsd!==0)fail('unexpected paid API spend must remain $0');
const cost=JSON.parse(read('release/phase91.0/cost-policy.json'));if(cost.paidPerImageProviderEnabled!==false||cost.paidProviderMonthlyBudgetUsd!==0||cost.autoOverage!==false)fail('paid-provider firewall changed');
const current=['src/app/product-photo-studio.tsx','services/background-removal/app.py','server/backgroundRemoval.ts','PHASE91.4-PRODUCT-PHOTO-QUALITY-PARITY-HARDENING.md'];for(const f of current)if(/good\s*will/i.test(read(f)))fail(`customer-specific branding in ${f}`);

const pack=read('scripts/create-source-release.mjs');for(const token of ['release/phase91.4/parity-policy.json','release/phase91.4/benchmark-template.csv','scripts/evaluate-phase91.4-parity.mjs','scripts/verify-phase91.4.mjs','tests/phase914-quality-parity-hardening.test.mjs','PHASE91.4-PRODUCT-PHOTO-QUALITY-PARITY-HARDENING.md'])if(!pack.includes(token))fail(`source packager missing ${token}`);const pkg=JSON.parse(read('package.json'));if(!/test:phase91\.4/.test(pkg.scripts.test||''))fail('top-level npm test missing 91.4');if(!/check:phase91\.4/.test(pkg.scripts['verify:phase91.4']||''))fail('verify:phase91.4 missing final check');
console.log('Phase 91.4 Product Photo quality-parity hardening gate passed.');
