import { useState } from "react";
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useAuth } from "../../context/AuthContext";
export default function AuthModal({visible,mode="signin",reason,onClose,onSuccess}:{visible:boolean;mode?:"signin"|"register";reason?:string;onClose:()=>void;onSuccess?:()=>void}){
 const auth=useAuth();const [tab,setTab]=useState(mode);const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const submit=async()=>{setBusy(true);setError("");try{if(tab==="signin")await auth.signIn(email.trim(),password);else await auth.register(email.trim(),password);onSuccess?.();onClose()}catch(e){setError(e instanceof Error?e.message:"Unable to continue")}finally{setBusy(false)}};
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.backdrop}><View style={s.card}><Text style={s.title}>{tab==="signin"?"Sign in to Yaposan":"Create your free account"}</Text><Text style={s.reason}>{reason??"Save projects securely and access them from any device."}</Text><View style={s.tabs}><Pressable onPress={()=>setTab("signin")} style={[s.tab,tab==="signin"&&s.active]}><Text style={s.tabText}>Sign In</Text></Pressable><Pressable onPress={()=>setTab("register")} style={[s.tab,tab==="register"&&s.active]}><Text style={s.tabText}>Create Account</Text></Pressable></View><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="Email address" style={s.input}/><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Password" style={s.input}/>{tab==="register"?<Text style={s.help}>Use at least 12 characters with upper/lowercase, a number, and a symbol.</Text>:null}{error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={busy||!email||!password} onPress={()=>void submit()} style={[s.primary,(busy||!email||!password)&&s.disabled]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>{tab==="signin"?"Sign In":"Create Free Account"}</Text>}</Pressable><Pressable onPress={onClose} style={s.secondary}><Text style={s.secondaryText}>Continue Editing</Text></Pressable></View></View></Modal>
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(2,8,23,.72)",alignItems:"center",justifyContent:"center",padding:20},card:{width:"100%",maxWidth:460,backgroundColor:"#fff",borderRadius:20,padding:24},title:{fontSize:25,fontWeight:"900",color:"#0f172a"},reason:{marginTop:8,color:"#475569",lineHeight:21},tabs:{flexDirection:"row",backgroundColor:"#eef2ff",borderRadius:12,padding:4,marginTop:20,marginBottom:14},tab:{flex:1,padding:10,alignItems:"center",borderRadius:9},active:{backgroundColor:"#fff"},tabText:{fontWeight:"800",color:"#312e81"},input:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:12,paddingHorizontal:14,paddingVertical:13,marginTop:11,fontSize:16},help:{fontSize:12,color:"#64748b",marginTop:8},error:{color:"#b91c1c",fontWeight:"700",marginTop:10},primary:{backgroundColor:"#6d28d9",padding:14,borderRadius:12,alignItems:"center",marginTop:16},disabled:{opacity:.55},primaryText:{color:"#fff",fontWeight:"900",fontSize:16},secondary:{padding:13,alignItems:"center",marginTop:7},secondaryText:{color:"#475569",fontWeight:"800"}})
